# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion_CTNET.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,77,0,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,82,0,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,85,0,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,87,0,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,88,0,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,86,0,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,89,0,6,Soleado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,95,0,7,Soleado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,100,0,8,Soleado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,100,1,9,Soleado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,93,2,10,Soleado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,79,2,11,Soleado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,64,6,12,Nublado,Soleado
13,2022-09-01 13:00:00,25478.471342,23,51,11,13,Nublado,Soleado
14,2022-09-01 14:00:00,29057.585772,25,41,12,14,Nublado,Soleado
15,2022-09-01 15:00:00,30000.000000,26,35,11,15,Nublado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,33,8,16,Nublado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,34,5,17,Nublado,Nublado
18,2022-09-01 18:00:00,29900.303971,27,37,3,18,Nublado,Nublado
19,2022-09-01 19:00:00,18282.505369,26,41,2,19,Nublado,Nublado
20,2022-09-01 20:00:00,3411.083740,24,48,0,20,Nublado,Nublado
21,2022-09-01 21:00:00,382.187718,22,55,0,21,Soleado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,61,0,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,68,0,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster GMM"] == "Soleado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
60,2022-09-03 12:00:00,17723.695569,21,58,4,12,Nublado,Soleado,11246.659307,27523.885172
62,2022-09-03 14:00:00,21548.984244,24,42,6,14,Nublado,Soleado,20400.000000,28500.000000
63,2022-09-03 15:00:00,25500.000000,24,39,7,15,Nublado,Soleado,21548.984244,24647.568577
64,2022-09-03 16:00:00,23122.803757,25,41,6,16,Nublado,Soleado,25500.000000,25500.000000
84,2022-09-04 12:00:00,22850.891263,21,66,6,12,Nublado,Soleado,17646.593401,17723.695569
85,2022-09-04 13:00:00,27000.000000,22,58,10,13,Nublado,Soleado,22850.891263,20400.000000
86,2022-09-04 14:00:00,25168.164594,23,51,12,14,Nublado,Soleado,27000.000000,21548.984244
87,2022-09-04 15:00:00,24300.000000,23,47,10,15,Nublado,Soleado,25168.164594,25500.000000
88,2022-09-04 16:00:00,19686.387416,24,46,7,16,Nublado,Soleado,24300.000000,23122.803757
109,2022-09-05 13:00:00,30000.000000,21,60,6,13,Nublado,Soleado,25558.205239,27000.000000

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
60,21,58,4,12,11246.659307,27523.885172
62,24,42,6,14,20400.000000,28500.000000
63,24,39,7,15,21548.984244,24647.568577
64,25,41,6,16,25500.000000,25500.000000
84,21,66,6,12,17646.593401,17723.695569
...,...,...,...,...,...,...
18254,23,46,9,13,26286.000000,25559.000000
18255,25,39,8,14,25653.000000,25579.000000
18277,21,51,6,12,26323.000000,26286.000000
18278,23,44,7,13,26277.000000,25653.000000
18279,24,38,8,14,25598.000000,25362.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
60     17723.695569
62     21548.984244
63     25500.000000
64     23122.803757
84     22850.891263
...             ...
18254  25653.000000
18255  25362.000000
18277  26277.000000
18278  25598.000000
18279  25399.000000

[1984 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 1388, y_train: 1388
X_val: 298, y_val: 298
X_test: 298, y_test: 298

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.2        0.79104478 0.         0.28571429 0.37488864 0.91746284]
 [0.35       0.55223881 0.2        0.57142857 0.68       0.95      ]
 [0.35       0.50746269 0.3        0.71428571 0.71829947 0.82158562]
 ...
 [0.35       0.79104478 0.1        0.         0.8229     0.91186667]
 [0.5        0.58208955 0.5        0.14285714 0.90826667 0.9442    ]
 [0.65       0.40298507 0.8        0.28571429 0.94696667 0.93683333]]
(1388, 6)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
60,0.20,0.791045,0.0,0.285714,0.374889,0.917463
62,0.35,0.552239,0.2,0.571429,0.680000,0.950000
63,0.35,0.507463,0.3,0.714286,0.718299,0.821586
64,0.40,0.537313,0.2,0.857143,0.850000,0.850000
84,0.20,0.910448,0.2,0.285714,0.588220,0.590790
...,...,...,...,...,...,...
15015,0.70,0.402985,0.8,0.571429,0.928933,0.932600
15016,0.75,0.328358,0.5,0.714286,0.932600,0.965300
15035,0.35,0.791045,0.1,0.000000,0.822900,0.911867
15036,0.50,0.582090,0.5,0.142857,0.908267,0.944200
15037,0.65,0.402985,0.8,0.285714,0.946967,0.936833

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.75       0.29850746 1.         0.42857143 0.9369     0.92893333]
 [0.8        0.25373134 0.8        0.57142857 0.92893333 0.9326    ]
 [0.9        0.20895522 0.5        0.71428571 0.9326     0.97063333]
 ...
 [0.45       0.6119403  0.5        0.71428571 0.95016667 0.8617    ]
 [0.2        0.94029851 0.4        0.14285714 0.89683333 0.92476667]
 [0.3        0.82089552 0.8        0.28571429 0.92476667 0.93596667]]
(298, 6)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
15038,0.75,0.298507,1.0,0.428571,0.936900,0.928933
15039,0.80,0.253731,0.8,0.571429,0.928933,0.932600
15040,0.90,0.208955,0.5,0.714286,0.932600,0.970633
15059,0.40,0.701493,0.1,0.000000,0.693167,0.908267
15060,0.55,0.507463,0.5,0.142857,0.727967,0.946967
...,...,...,...,...,...,...
16526,0.35,0.716418,1.0,0.428571,0.935967,0.848067
16527,0.45,0.641791,0.8,0.571429,0.943800,0.851767
16528,0.45,0.611940,0.5,0.714286,0.950167,0.861700
16548,0.20,0.940299,0.4,0.142857,0.896833,0.924767
16549,0.30,0.820896,0.8,0.285714,0.924767,0.935967

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.35       0.73134328 0.8        0.42857143 0.9375     0.9438    ]
 [0.45       0.67164179 0.8        0.57142857 0.95086667 0.95016667]
 [0.45       0.64179104 0.5        0.71428571 0.95153333 0.95743333]
 ...
 [0.2        0.68656716 0.2        0.28571429 0.87743333 0.8762    ]
 [0.3        0.58208955 0.3        0.42857143 0.8759     0.8551    ]
 [0.35       0.49253731 0.4        0.57142857 0.85326667 0.8454    ]]
(298, 6)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
16550,0.35,0.731343,0.8,0.428571,0.937500,0.943800
16551,0.45,0.671642,0.8,0.571429,0.950867,0.950167
16552,0.45,0.641791,0.5,0.714286,0.951533,0.957433
16572,0.25,0.895522,0.2,0.142857,0.933400,0.924767
16573,0.30,0.791045,0.8,0.285714,0.852400,0.937500
...,...,...,...,...,...,...
18254,0.30,0.611940,0.5,0.428571,0.876200,0.851967
18255,0.40,0.507463,0.4,0.571429,0.855100,0.852633
18277,0.20,0.686567,0.2,0.285714,0.877433,0.876200
18278,0.30,0.582090,0.3,0.428571,0.875900,0.855100
18279,0.35,0.492537,0.4,0.571429,0.853267,0.845400

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.19047619 0.76811594 0.         0.28571429 0.37488864 0.91746284]
 [0.33333333 0.53623188 0.2        0.57142857 0.68       0.95      ]
 [0.33333333 0.49275362 0.3        0.71428571 0.71829947 0.82158562]
 ...
 [0.19047619 0.66666667 0.2        0.28571429 0.87743333 0.8762    ]
 [0.28571429 0.56521739 0.3        0.42857143 0.8759     0.8551    ]
 [0.33333333 0.47826087 0.4        0.57142857 0.85326667 0.8454    ]]
(1984, 6)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
60,0.190476,0.768116,0.0,0.285714,0.374889,0.917463
62,0.333333,0.536232,0.2,0.571429,0.680000,0.950000
63,0.333333,0.492754,0.3,0.714286,0.718299,0.821586
64,0.380952,0.521739,0.2,0.857143,0.850000,0.850000
84,0.190476,0.884058,0.2,0.285714,0.588220,0.590790
...,...,...,...,...,...,...
18254,0.285714,0.594203,0.5,0.428571,0.876200,0.851967
18255,0.380952,0.492754,0.4,0.571429,0.855100,0.852633
18277,0.190476,0.666667,0.2,0.285714,0.877433,0.876200
18278,0.285714,0.565217,0.3,0.428571,0.875900,0.855100
18279,0.333333,0.478261,0.4,0.571429,0.853267,0.845400

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.59078985]
 [0.71829947]
 [0.85      ]
 ...
 [0.90826667]
 [0.94696667]
 [0.9369    ]]
(1388, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
60       0.590790
62       0.718299
63       0.850000
64       0.770760
84       0.761696
...           ...
15015    0.932600
15016    0.970633
15035    0.908267
15036    0.946967
15037    0.936900

[1388 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[0.92893333]
 [0.9326    ]
 [0.97063333]
 [0.72796667]
 [0.751     ]
 [0.9429    ]
 [0.93506667]
 [0.885     ]
 [0.86473333]
 [0.8983    ]
 [0.95563333]
 [0.98136667]
 [0.97883333]
 [0.94683333]
 [0.92646667]
 [0.9025    ]
 [0.9426    ]
 [0.93683333]
 [0.93753333]
 [0.9363    ]
 [0.92646667]
 [0.90996667]
 [0.9332    ]
 [0.94056667]
 [0.93186667]
 [0.95676667]
 [0.83383333]
 [0.9332    ]
 [0.9537    ]
 [0.85843333]
 [0.77453333]
 [0.76263333]
 [0.9332    ]
 [0.9479    ]
 [0.95776667]
 [0.96316667]
 [0.9624    ]
 [0.9332    ]
 [0.9484    ]
 [0.96203333]
 [0.96876667]
 [0.95776667]
 [0.93553333]
 [0.94413333]
 [0.84376667]
 [0.84483333]
 [0.96416667]
 [0.94396667]
 [0.97616667]
 [0.97016667]
 [0.97313333]
 [0.94583333]
 [0.9501    ]
 [0.93826667]
 [0.9582    ]
 [0.95276667]
 [0.94963333]
 [0.95856667]
 [0.9593    ]
 [0.94006667]
 [0.96873333]
 [0.95253333]
 [0.95486667]
 [0.97816667]
 [0.95946667]
 [0.91103333]
 [0.94243333]
 [0.94176667]
 [0.93916667]
 [0.93993333]
 [0.9288    ]
 [0.7288    ]
 [0.77463333]
 [0.7569    ]
 [0.75133333]
 [0.8674    ]
 [0.77346667]
 [0.97976667]
 [0.9742    ]
 [0.98153333]
 [0.94706667]
 [0.94543333]
 [0.94243333]
 [0.94176667]
 [0.94386667]
 [0.9725    ]
 [0.9308    ]
 [0.943     ]
 [0.94176667]
 [0.94886667]
 [0.95573333]
 [0.95593333]
 [0.9482    ]
 [0.94176667]
 [0.9482    ]
 [0.96123333]
 [0.95666667]
 [0.91103333]
 [0.9482    ]
 [0.94463333]
 [0.93916667]
 [0.6743    ]
 [0.8359    ]
 [0.7596    ]
 [0.97846667]
 [0.9731    ]
 [0.974     ]
 [0.9657    ]
 [0.8589    ]
 [0.94716667]
 [0.9805    ]
 [0.9791    ]
 [0.9787    ]
 [0.95886667]
 [0.95263333]
 [0.9495    ]
 [0.9808    ]
 [0.98196667]
 [0.97453333]
 [0.9628    ]
 [0.95946667]
 [0.96563333]
 [0.96843333]
 [0.96723333]
 [0.9436    ]
 [0.93903333]
 [0.9349    ]
 [0.9482    ]
 [0.94176667]
 [0.94283333]
 [0.93653333]
 [0.93116667]
 [0.93306667]
 [0.9554    ]
 [0.94776667]
 [0.94003333]
 [0.93653333]
 [0.9356    ]
 [0.8319    ]
 [0.95456667]
 [0.97073333]
 [0.97656667]
 [0.94936667]
 [0.9278    ]
 [0.7711    ]
 [0.60836667]
 [0.85406667]
 [0.94046667]
 [0.9288    ]
 [0.9154    ]
 [0.96963333]
 [0.97063333]
 [0.95266667]
 [0.9444    ]
 [0.9288    ]
 [0.91876667]
 [0.96546667]
 [0.96666667]
 [0.95023333]
 [0.94056667]
 [0.9288    ]
 [0.91623333]
 [0.94683333]
 [0.94586667]
 [0.93916667]
 [0.93653333]
 [0.9356    ]
 [0.93696667]
 [0.94776667]
 [0.94386667]
 [0.94776667]
 [0.93916667]
 [0.93653333]
 [0.9288    ]
 [0.91493333]
 [0.59383333]
 [0.94096667]
 [0.94473333]
 [0.9435    ]
 [0.93916667]
 [0.93696667]
 [0.9288    ]
 [0.94776667]
 [0.94176667]
 [0.94543333]
 [0.95876667]
 [0.94533333]
 [0.94133333]
 [0.94803333]
 [0.94803333]
 [0.95443333]
 [0.95203333]
 [0.94433333]
 [0.94283333]
 [0.93916667]
 [0.93653333]
 [0.93036667]
 [0.94176667]
 [0.93916667]
 [0.93653333]
 [0.67313333]
 [0.94193333]
 [0.93916667]
 [0.93653333]
 [0.93386667]
 [0.92616667]
 [0.92313333]
 [0.92316667]
 [0.91553333]
 [0.91063333]
 [0.8989    ]
 [0.9276    ]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.91063333]
 [0.92123333]
 [0.91896667]
 [0.9173    ]
 [0.9135    ]
 [0.93066667]
 [0.9218    ]
 [0.9522    ]
 [0.9401    ]
 [0.8244    ]
 [0.378     ]
 [0.32013333]
 [0.316     ]
 [0.37496667]
 [0.35636667]
 [0.9       ]
 [0.89676667]
 [0.8788    ]
 [0.89866667]
 [0.842     ]
 [0.9       ]
 [0.9       ]
 [0.87366667]
 [0.9       ]
 [0.84603333]
 [0.9304    ]
 [0.92123333]
 [0.83      ]
 [0.91613333]
 [0.91063333]
 [0.63076667]
 [0.65176667]
 [0.71903333]
 [0.7635    ]
 [0.91553333]
 [0.82056667]
 [0.27      ]
 [0.26786667]
 [0.26763333]
 [0.28973333]
 [0.16096667]
 [0.2012    ]
 [0.405     ]
 [0.32163333]
 [0.40356667]
 [0.36216667]
 [0.36216667]
 [0.9       ]
 [0.8863    ]
 [0.9       ]
 [0.8048    ]
 [0.8048    ]
 [0.51786667]
 [0.6633    ]
 [0.73633333]
 [0.75536667]
 [0.7569    ]
 [0.3966    ]
 [0.39583333]
 [0.38616667]
 [0.5203    ]
 [0.45426667]
 [0.4549    ]
 [0.45376667]
 [0.27963333]
 [0.28206667]
 [0.392     ]
 [0.4501    ]
 [0.39206667]
 [0.39176667]
 [0.4462    ]
 [0.92476667]
 [0.83566667]
 [0.84806667]
 [0.85176667]
 [0.8617    ]
 [0.92476667]
 [0.93596667]
 [0.9438    ]
 [0.95016667]
 [0.95743333]
 [0.92476667]
 [0.9375    ]]
(298, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
15038    0.928933
15039    0.932600
15040    0.970633
15059    0.727967
15060    0.751000
...           ...
16526    0.943800
16527    0.950167
16528    0.957433
16548    0.924767
16549    0.937500

[298 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.95086667]
 [0.95153333]
 [0.95743333]
 [0.8524    ]
 [0.8321    ]
 [0.9522    ]
 [0.6613    ]
 [0.65823333]
 [0.39263333]
 [0.39453333]
 [0.46656667]
 [0.4486    ]
 [0.51253333]
 [0.66073333]
 [0.66416667]
 [0.688     ]
 [0.66283333]
 [0.92123333]
 [0.9215    ]
 [0.91553333]
 [0.91133333]
 [0.8989    ]
 [0.92446667]
 [0.92853333]
 [0.91553333]
 [0.91063333]
 [0.7407    ]
 [0.737     ]
 [0.83793333]
 [0.824     ]
 [0.82563333]
 [0.92456667]
 [0.94646667]
 [0.95036667]
 [0.94076667]
 [0.92476667]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.81956667]
 [0.92196667]
 [0.92623333]
 [0.92043333]
 [0.9242    ]
 [0.9156    ]
 [0.92236667]
 [0.8345    ]
 [0.72543333]
 [0.82626667]
 [0.9101    ]
 [0.92196667]
 [0.92103333]
 [0.9068    ]
 [0.91263333]
 [0.90873333]
 [0.92196667]
 [0.92593333]
 [0.90816667]
 [0.92106667]
 [0.9109    ]
 [0.92196667]
 [0.92456667]
 [0.90863333]
 [0.9157    ]
 [0.91783333]
 [0.92613333]
 [0.92293333]
 [0.9093    ]
 [0.90856667]
 [0.90463333]
 [0.8344    ]
 [0.92103333]
 [0.90856667]
 [0.9144    ]
 [0.92196667]
 [0.92103333]
 [0.91476667]
 [0.9144    ]
 [0.90236667]
 [0.83153333]
 [0.73783333]
 [0.72696667]
 [0.72986667]
 [0.90236667]
 [0.92473333]
 [0.93346667]
 [0.93503333]
 [0.90513333]
 [0.90503333]
 [0.92626667]
 [0.9386    ]
 [0.9374    ]
 [0.90716667]
 [0.81213333]
 [0.92556667]
 [0.93563333]
 [0.93943333]
 [0.90893333]
 [0.90616667]
 [0.73936667]
 [0.72716667]
 [0.726     ]
 [0.92393333]
 [0.93076667]
 [0.92466667]
 [0.919     ]
 [0.9105    ]
 [0.9374    ]
 [0.9068    ]
 [0.91156667]
 [0.81476667]
 [0.939     ]
 [0.9426    ]
 [0.94876667]
 [0.954     ]
 [0.94613333]
 [0.93453333]
 [0.91673333]
 [0.93386667]
 [0.75203333]
 [0.75153333]
 [0.74626667]
 [0.74663333]
 [0.7315    ]
 [0.97796667]
 [0.92286667]
 [0.95126667]
 [0.93203333]
 [0.8664    ]
 [0.99603333]
 [0.9275    ]
 [0.94186667]
 [0.93336667]
 [0.7441    ]
 [0.92196667]
 [0.92473333]
 [0.91503333]
 [0.9171    ]
 [0.9446    ]
 [0.96206667]
 [0.86333333]
 [0.86216667]
 [0.76416667]
 [0.756     ]
 [0.96596667]
 [0.96363333]
 [0.9583    ]
 [0.9552    ]
 [0.95      ]
 [0.96846667]
 [0.96363333]
 [0.9616    ]
 [0.9552    ]
 [0.95      ]
 [0.92196667]
 [0.92103333]
 [0.9068    ]
 [0.90693333]
 [0.90326667]
 [0.95373333]
 [0.93163333]
 [0.93036667]
 [0.93206667]
 [0.93726667]
 [0.96083333]
 [0.92233333]
 [0.90866667]
 [0.90966667]
 [0.90236667]
 [0.82976667]
 [0.8321    ]
 [0.91196667]
 [0.81583333]
 [0.6497    ]
 [0.82976667]
 [0.82893333]
 [0.81613333]
 [0.6591    ]
 [0.38563333]
 [0.38703333]
 [0.3811    ]
 [0.38356667]
 [0.38253333]
 [0.0828    ]
 [0.08283333]
 [0.082     ]
 [0.0822    ]
 [0.0819    ]
 [0.39023333]
 [0.27863333]
 [0.27263333]
 [0.27396667]
 [0.2749    ]
 [0.44023333]
 [0.56633333]
 [0.51426667]
 [0.50846667]
 [0.43786667]
 [0.37723333]
 [0.08256667]
 [0.647     ]
 [0.38296667]
 [0.378     ]
 [0.38356667]
 [0.43863333]
 [0.68306667]
 [0.52456667]
 [0.5601    ]
 [0.9214    ]
 [0.65593333]
 [0.8526    ]
 [0.5256    ]
 [0.4984    ]
 [0.58486667]
 [0.58226667]
 [0.9487    ]
 [0.93423333]
 [0.89173333]
 [0.91693333]
 [0.91146667]
 [0.89813333]
 [0.88903333]
 [0.91223333]
 [0.90286667]
 [0.88903333]
 [0.91323333]
 [0.89513333]
 [0.89286667]
 [0.9185    ]
 [0.7185    ]
 [0.7143    ]
 [0.8219    ]
 [0.80806667]
 [0.89286667]
 [0.91323333]
 [0.89813333]
 [0.89673333]
 [0.91323333]
 [0.64686667]
 [0.8975    ]
 [0.91416667]
 [0.8992    ]
 [0.89216667]
 [0.7821    ]
 [0.86836667]
 [0.91403333]
 [0.922     ]
 [0.89383333]
 [0.91443333]
 [0.87146667]
 [0.922     ]
 [0.9105    ]
 [0.9114    ]
 [0.91413333]
 [0.89873333]
 [0.89206667]
 [0.89613333]
 [0.89583333]
 [0.90356667]
 [0.8923    ]
 [0.8883    ]
 [0.82103333]
 [0.91063333]
 [0.9003    ]
 [0.8923    ]
 [0.89466667]
 [0.89583333]
 [0.91063333]
 [0.90356667]
 [0.8923    ]
 [0.89613333]
 [0.89583333]
 [0.83453333]
 [0.89136667]
 [0.87756667]
 [0.8949    ]
 [0.88706667]
 [0.87463333]
 [0.8788    ]
 [0.87466667]
 [0.87696667]
 [0.85716667]
 [0.8817    ]
 [0.8046    ]
 [0.7149    ]
 [0.87166667]
 [0.86963333]
 [0.8727    ]
 [0.85196667]
 [0.85263333]
 [0.84776667]
 [0.87186667]
 [0.8762    ]
 [0.8551    ]
 [0.8454    ]
 [0.8759    ]
 [0.85326667]
 [0.84663333]]
(298, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
16550    0.950867
16551    0.951533
16552    0.957433
16572    0.852400
16573    0.832100
...           ...
18254    0.855100
18255    0.845400
18277    0.875900
18278    0.853267
18279    0.846633

[298 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.59078985]
 [0.71829947]
 [0.85      ]
 ...
 [0.8759    ]
 [0.85326667]
 [0.84663333]]
(1984, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
60       0.590790
62       0.718299
63       0.850000
64       0.770760
84       0.761696
...           ...
18254    0.855100
18255    0.845400
18277    0.875900
18278    0.853267
18279    0.846633

[1984 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.255558 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 614
[LightGBM] [Info] Number of data points in the train set: 1388, number of used features: 6
[LightGBM] [Info] Start training from score 0.884575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
16550   28000.79621
16551  27441.039487
16552  27653.008343
16572  28695.531858
16573   26100.23055
...             ...
18254  25624.012047
18255  25407.643926
18277  26526.444089
18278  26062.873849
18279  25466.884147

[298 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
16550     28526.0
16551     28546.0
16552     28723.0
16572     25572.0
16573     24963.0
...           ...
18254     25653.0
18255     25362.0
18277     26277.0
18278     25598.0
18279     25399.0

[298 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
16550     28526.0   28000.79621
16551     28546.0  27441.039487
16552     28723.0  27653.008343
16572     25572.0  28695.531858
16573     24963.0   26100.23055
...           ...           ...
18254     25653.0  25624.012047
18255     25362.0  25407.643926
18277     26277.0  26526.444089
18278     25598.0  26062.873849
18279     25399.0  25466.884147

[298 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1654.2360
RMSE: 3114.7331
R²: 0.6976

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
16550     28526.0   28000.79621  28084.034609
16551     28546.0  27441.039487   27743.33194
16552     28723.0  27653.008343  28106.194443
16572     25572.0  28695.531858       28406.4
16573     24963.0   26100.23055  26665.619348
...           ...           ...           ...
18254     25653.0  25624.012047  26388.864157
18255     25362.0  25407.643926  25765.293528
18277     26277.0  26526.444089  26570.909285
18278     25598.0  26062.873849  26251.964527
18279     25399.0  25466.884147  25856.443648

[298 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (1340, 48, 6), y_train: (1340, 1)
X_val: (250, 48, 6), y_val: (250, 1)
X_test: (250, 48, 6), y_test: (250, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 68s 4s/step - loss: 0.8183 - mean_absolute_error: 0.8944 - mean_absolute_percentage_error: 2147.2354 - root_mean_squared_error: 0.9046 - val_loss: 0.7526 - val_mean_absolute_error: 0.8611 - val_mean_absolute_percentage_error: 99.5525 - val_root_mean_squared_error: 0.8675
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 4s/step - loss: 0.8091 - mean_absolute_error: 0.8890 - mean_absolute_percentage_error: 35967.1016 - root_mean_squared_error: 0.8995 - val_loss: 0.7453 - val_mean_absolute_error: 0.8568 - val_mean_absolute_percentage_error: 99.0519 - val_root_mean_squared_error: 0.8633
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.8046 - mean_absolute_error: 0.8879 - mean_absolute_percentage_error: 67292.2656 - root_mean_squared_error: 0.8970 - val_loss: 0.7373 - val_mean_absolute_error: 0.8522 - val_mean_absolute_percentage_error: 98.5018 - val_root_mean_squared_error: 0.8587
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 10s 4s/step - loss: 0.7924 - mean_absolute_error: 0.8800 - mean_absolute_percentage_error: 106049.6484 - root_mean_squared_error: 0.8902 - val_loss: 0.7285 - val_mean_absolute_error: 0.8470 - val_mean_absolute_percentage_error: 97.8934 - val_root_mean_squared_error: 0.8535
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - loss: 0.7823 - mean_absolute_error: 0.8739 - mean_absolute_percentage_error: 175304.8906 - root_mean_squared_error: 0.8845 - val_loss: 0.7187 - val_mean_absolute_error: 0.8412 - val_mean_absolute_percentage_error: 97.2113 - val_root_mean_squared_error: 0.8478
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 5s/step - loss: 0.7748 - mean_absolute_error: 0.8701 - mean_absolute_percentage_error: 222442.1406 - root_mean_squared_error: 0.8802 - val_loss: 0.7078 - val_mean_absolute_error: 0.8347 - val_mean_absolute_percentage_error: 96.4441 - val_root_mean_squared_error: 0.8413
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step - loss: 0.7622 - mean_absolute_error: 0.8633 - mean_absolute_percentage_error: 246285.9219 - root_mean_squared_error: 0.8730 - val_loss: 0.6955 - val_mean_absolute_error: 0.8273 - val_mean_absolute_percentage_error: 95.5718 - val_root_mean_squared_error: 0.8340
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - loss: 0.7480 - mean_absolute_error: 0.8544 - mean_absolute_percentage_error: 322259.0625 - root_mean_squared_error: 0.8649 - val_loss: 0.6817 - val_mean_absolute_error: 0.8189 - val_mean_absolute_percentage_error: 94.5826 - val_root_mean_squared_error: 0.8256
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 1s/step - loss: 0.7366 - mean_absolute_error: 0.8485 - mean_absolute_percentage_error: 329675.8125 - root_mean_squared_error: 0.8582 - val_loss: 0.6661 - val_mean_absolute_error: 0.8093 - val_mean_absolute_percentage_error: 93.4591 - val_root_mean_squared_error: 0.8162
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.7205 - mean_absolute_error: 0.8394 - mean_absolute_percentage_error: 475278.5938 - root_mean_squared_error: 0.8488 - val_loss: 0.6486 - val_mean_absolute_error: 0.7984 - val_mean_absolute_percentage_error: 92.1787 - val_root_mean_squared_error: 0.8054
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 4s/step - loss: 0.6985 - mean_absolute_error: 0.8257 - mean_absolute_percentage_error: 601750.8750 - root_mean_squared_error: 0.8358 - val_loss: 0.6289 - val_mean_absolute_error: 0.7860 - val_mean_absolute_percentage_error: 90.7166 - val_root_mean_squared_error: 0.7931
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 3s/step - loss: 0.6771 - mean_absolute_error: 0.8124 - mean_absolute_percentage_error: 633068.0000 - root_mean_squared_error: 0.8229 - val_loss: 0.6068 - val_mean_absolute_error: 0.7718 - val_mean_absolute_percentage_error: 89.0475 - val_root_mean_squared_error: 0.7790
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 17s 5s/step - loss: 0.6571 - mean_absolute_error: 0.8004 - mean_absolute_percentage_error: 857659.4375 - root_mean_squared_error: 0.8106 - val_loss: 0.5822 - val_mean_absolute_error: 0.7557 - val_mean_absolute_percentage_error: 87.1453 - val_root_mean_squared_error: 0.7630
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 3s/step - loss: 0.6326 - mean_absolute_error: 0.7858 - mean_absolute_percentage_error: 742512.0000 - root_mean_squared_error: 0.7953 - val_loss: 0.5548 - val_mean_absolute_error: 0.7373 - val_mean_absolute_percentage_error: 84.9856 - val_root_mean_squared_error: 0.7448
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.6009 - mean_absolute_error: 0.7653 - mean_absolute_percentage_error: 1249270.8750 - root_mean_squared_error: 0.7752 - val_loss: 0.5245 - val_mean_absolute_error: 0.7165 - val_mean_absolute_percentage_error: 82.5380 - val_root_mean_squared_error: 0.7242
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 1s/step - loss: 0.5692 - mean_absolute_error: 0.7441 - mean_absolute_percentage_error: 1144287.2500 - root_mean_squared_error: 0.7545 - val_loss: 0.4912 - val_mean_absolute_error: 0.6929 - val_mean_absolute_percentage_error: 79.7569 - val_root_mean_squared_error: 0.7009
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 5s/step - loss: 0.5369 - mean_absolute_error: 0.7223 - mean_absolute_percentage_error: 1415788.5000 - root_mean_squared_error: 0.7327 - val_loss: 0.4549 - val_mean_absolute_error: 0.6662 - val_mean_absolute_percentage_error: 76.6123 - val_root_mean_squared_error: 0.6745
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 23s 5s/step - loss: 0.4943 - mean_absolute_error: 0.6926 - mean_absolute_percentage_error: 1829079.2500 - root_mean_squared_error: 0.7030 - val_loss: 0.4157 - val_mean_absolute_error: 0.6361 - val_mean_absolute_percentage_error: 73.0647 - val_root_mean_squared_error: 0.6447
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - loss: 0.4571 - mean_absolute_error: 0.6653 - mean_absolute_percentage_error: 1757004.2500 - root_mean_squared_error: 0.6761 - val_loss: 0.3737 - val_mean_absolute_error: 0.6022 - val_mean_absolute_percentage_error: 69.0745 - val_root_mean_squared_error: 0.6113
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 2s/step - loss: 0.4115 - mean_absolute_error: 0.6302 - mean_absolute_percentage_error: 2204372.2500 - root_mean_squared_error: 0.6415 - val_loss: 0.3295 - val_mean_absolute_error: 0.5643 - val_mean_absolute_percentage_error: 64.6116 - val_root_mean_squared_error: 0.5740
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 3s/step - loss: 0.3621 - mean_absolute_error: 0.5892 - mean_absolute_percentage_error: 2446865.0000 - root_mean_squared_error: 0.6017 - val_loss: 0.2837 - val_mean_absolute_error: 0.5221 - val_mean_absolute_percentage_error: 59.6476 - val_root_mean_squared_error: 0.5327
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.3170 - mean_absolute_error: 0.5509 - mean_absolute_percentage_error: 2884086.0000 - root_mean_squared_error: 0.5630 - val_loss: 0.2373 - val_mean_absolute_error: 0.4756 - val_mean_absolute_percentage_error: 54.1707 - val_root_mean_squared_error: 0.4871
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 3s/step - loss: 0.2727 - mean_absolute_error: 0.5078 - mean_absolute_percentage_error: 3573966.2500 - root_mean_squared_error: 0.5222 - val_loss: 0.1916 - val_mean_absolute_error: 0.4248 - val_mean_absolute_percentage_error: 48.2031 - val_root_mean_squared_error: 0.4377
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 2s/step - loss: 0.2233 - mean_absolute_error: 0.4563 - mean_absolute_percentage_error: 4548739.0000 - root_mean_squared_error: 0.4726 - val_loss: 0.1479 - val_mean_absolute_error: 0.3705 - val_mean_absolute_percentage_error: 41.8832 - val_root_mean_squared_error: 0.3845
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 5s/step - loss: 0.1776 - mean_absolute_error: 0.4039 - mean_absolute_percentage_error: 3938906.2500 - root_mean_squared_error: 0.4214 - val_loss: 0.1078 - val_mean_absolute_error: 0.3125 - val_mean_absolute_percentage_error: 35.1452 - val_root_mean_squared_error: 0.3283
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step - loss: 0.1363 - mean_absolute_error: 0.3470 - mean_absolute_percentage_error: 4326231.0000 - root_mean_squared_error: 0.3692 - val_loss: 0.0730 - val_mean_absolute_error: 0.2519 - val_mean_absolute_percentage_error: 28.1510 - val_root_mean_squared_error: 0.2703
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 7s 3s/step - loss: 0.1042 - mean_absolute_error: 0.2941 - mean_absolute_percentage_error: 4419286.0000 - root_mean_squared_error: 0.3228 - val_loss: 0.0454 - val_mean_absolute_error: 0.1934 - val_mean_absolute_percentage_error: 21.5415 - val_root_mean_squared_error: 0.2131
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 18s 5s/step - loss: 0.0770 - mean_absolute_error: 0.2391 - mean_absolute_percentage_error: 6440977.0000 - root_mean_squared_error: 0.2774 - val_loss: 0.0261 - val_mean_absolute_error: 0.1406 - val_mean_absolute_percentage_error: 15.7745 - val_root_mean_squared_error: 0.1614
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 1s/step - loss: 0.0581 - mean_absolute_error: 0.1950 - mean_absolute_percentage_error: 5560299.0000 - root_mean_squared_error: 0.2411 - val_loss: 0.0150 - val_mean_absolute_error: 0.1068 - val_mean_absolute_percentage_error: 12.4591 - val_root_mean_squared_error: 0.1226
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.0437 - mean_absolute_error: 0.1586 - mean_absolute_percentage_error: 6807432.0000 - root_mean_squared_error: 0.2090 - val_loss: 0.0112 - val_mean_absolute_error: 0.0873 - val_mean_absolute_percentage_error: 10.8341 - val_root_mean_squared_error: 0.1059
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 4s/step - loss: 0.0445 - mean_absolute_error: 0.1547 - mean_absolute_percentage_error: 8848419.0000 - root_mean_squared_error: 0.2108 - val_loss: 0.0122 - val_mean_absolute_error: 0.0859 - val_mean_absolute_percentage_error: 11.1961 - val_root_mean_squared_error: 0.1105
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.0479 - mean_absolute_error: 0.1624 - mean_absolute_percentage_error: 7227741.0000 - root_mean_squared_error: 0.2188 - val_loss: 0.0148 - val_mean_absolute_error: 0.0878 - val_mean_absolute_percentage_error: 11.7462 - val_root_mean_squared_error: 0.1217
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 4s/step - loss: 0.0426 - mean_absolute_error: 0.1547 - mean_absolute_percentage_error: 6122839.0000 - root_mean_squared_error: 0.2062 - val_loss: 0.0168 - val_mean_absolute_error: 0.0909 - val_mean_absolute_percentage_error: 12.2695 - val_root_mean_squared_error: 0.1295
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 4s/step - loss: 0.0486 - mean_absolute_error: 0.1678 - mean_absolute_percentage_error: 8034521.0000 - root_mean_squared_error: 0.2205 - val_loss: 0.0167 - val_mean_absolute_error: 0.0907 - val_mean_absolute_percentage_error: 12.2435 - val_root_mean_squared_error: 0.1292
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.0501 - mean_absolute_error: 0.1694 - mean_absolute_percentage_error: 8276812.5000 - root_mean_squared_error: 0.2238 - val_loss: 0.0150 - val_mean_absolute_error: 0.0878 - val_mean_absolute_percentage_error: 11.7713 - val_root_mean_squared_error: 0.1226
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 6s/step - loss: 0.0440 - mean_absolute_error: 0.1547 - mean_absolute_percentage_error: 7537307.0000 - root_mean_squared_error: 0.2097 - val_loss: 0.0129 - val_mean_absolute_error: 0.0858 - val_mean_absolute_percentage_error: 11.3097 - val_root_mean_squared_error: 0.1137
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.0462 - mean_absolute_error: 0.1605 - mean_absolute_percentage_error: 8166509.0000 - root_mean_squared_error: 0.2150 - val_loss: 0.0114 - val_mean_absolute_error: 0.0846 - val_mean_absolute_percentage_error: 10.9141 - val_root_mean_squared_error: 0.1070
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 7s 3s/step - loss: 0.0417 - mean_absolute_error: 0.1514 - mean_absolute_percentage_error: 7775113.0000 - root_mean_squared_error: 0.2042 - val_loss: 0.0109 - val_mean_absolute_error: 0.0850 - val_mean_absolute_percentage_error: 10.7008 - val_root_mean_squared_error: 0.1043
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 17s 5s/step - loss: 0.0412 - mean_absolute_error: 0.1515 - mean_absolute_percentage_error: 6852816.5000 - root_mean_squared_error: 0.2030 - val_loss: 0.0110 - val_mean_absolute_error: 0.0876 - val_mean_absolute_percentage_error: 10.7886 - val_root_mean_squared_error: 0.1051
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 18s 2s/step - loss: 0.0403 - mean_absolute_error: 0.1498 - mean_absolute_percentage_error: 6759513.0000 - root_mean_squared_error: 0.2009 - val_loss: 0.0114 - val_mean_absolute_error: 0.0908 - val_mean_absolute_percentage_error: 11.0118 - val_root_mean_squared_error: 0.1069
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 4s/step - loss: 0.0427 - mean_absolute_error: 0.1539 - mean_absolute_percentage_error: 7647989.5000 - root_mean_squared_error: 0.2066 - val_loss: 0.0115 - val_mean_absolute_error: 0.0913 - val_mean_absolute_percentage_error: 11.0409 - val_root_mean_squared_error: 0.1071
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 26s 5s/step - loss: 0.0411 - mean_absolute_error: 0.1518 - mean_absolute_percentage_error: 7877533.0000 - root_mean_squared_error: 0.2027 - val_loss: 0.0111 - val_mean_absolute_error: 0.0893 - val_mean_absolute_percentage_error: 10.8599 - val_root_mean_squared_error: 0.1054
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - loss: 0.0429 - mean_absolute_error: 0.1550 - mean_absolute_percentage_error: 7322111.5000 - root_mean_squared_error: 0.2072 - val_loss: 0.0107 - val_mean_absolute_error: 0.0869 - val_mean_absolute_percentage_error: 10.6693 - val_root_mean_squared_error: 0.1036
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 5s/step - loss: 0.0401 - mean_absolute_error: 0.1490 - mean_absolute_percentage_error: 7543436.0000 - root_mean_squared_error: 0.2002 - val_loss: 0.0105 - val_mean_absolute_error: 0.0849 - val_mean_absolute_percentage_error: 10.5448 - val_root_mean_squared_error: 0.1023
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 22s 4s/step - loss: 0.0423 - mean_absolute_error: 0.1517 - mean_absolute_percentage_error: 8026489.5000 - root_mean_squared_error: 0.2056 - val_loss: 0.0103 - val_mean_absolute_error: 0.0833 - val_mean_absolute_percentage_error: 10.4671 - val_root_mean_squared_error: 0.1017
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 6s/step - loss: 0.0418 - mean_absolute_error: 0.1516 - mean_absolute_percentage_error: 8004491.0000 - root_mean_squared_error: 0.2044 - val_loss: 0.0104 - val_mean_absolute_error: 0.0823 - val_mean_absolute_percentage_error: 10.4497 - val_root_mean_squared_error: 0.1019
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - loss: 0.0417 - mean_absolute_error: 0.1559 - mean_absolute_percentage_error: 5708137.5000 - root_mean_squared_error: 0.2042 - val_loss: 0.0104 - val_mean_absolute_error: 0.0819 - val_mean_absolute_percentage_error: 10.4472 - val_root_mean_squared_error: 0.1021
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.0405 - mean_absolute_error: 0.1456 - mean_absolute_percentage_error: 7932277.0000 - root_mean_squared_error: 0.2011 - val_loss: 0.0104 - val_mean_absolute_error: 0.0816 - val_mean_absolute_percentage_error: 10.4162 - val_root_mean_squared_error: 0.1018
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 6s/step - loss: 0.0399 - mean_absolute_error: 0.1487 - mean_absolute_percentage_error: 6914418.0000 - root_mean_squared_error: 0.1996 - val_loss: 0.0102 - val_mean_absolute_error: 0.0815 - val_mean_absolute_percentage_error: 10.3611 - val_root_mean_squared_error: 0.1011
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 5s/step - loss: 0.0400 - mean_absolute_error: 0.1503 - mean_absolute_percentage_error: 6569442.5000 - root_mean_squared_error: 0.2001 - val_loss: 0.0100 - val_mean_absolute_error: 0.0817 - val_mean_absolute_percentage_error: 10.3124 - val_root_mean_squared_error: 0.1002

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

8/8 ━━━━━━━━━━━━━━━━━━━━ 17s 1s/step

array([[0.87212104],
       [0.871561  ],
       [0.8701927 ],
       [0.87201685],
       [0.8719718 ],
       [0.8712695 ],
       [0.8704179 ],
       [0.8702238 ],
       [0.87077135],
       [0.8721224 ],
       [0.87349445],
       [0.8735046 ],
       [0.87489945],
       [0.87598854],
       [0.87706894],
       [0.87765074],
       [0.8790534 ],
       [0.88020366],
       [0.8797138 ],
       [0.88020486],
       [0.88059384],
       [0.8811379 ],
       [0.88207364],
       [0.8816673 ],
       [0.8815842 ],
       [0.8828508 ],
       [0.8829713 ],
       [0.8828495 ],
       [0.8828546 ],
       [0.8825051 ],
       [0.88320875],
       [0.8824282 ],
       [0.88301367],
       [0.88239974],
       [0.88306314],
       [0.8852775 ],
       [0.88347125],
       [0.883336  ],
       [0.8825051 ],
       [0.8819286 ],
       [0.88242894],
       [0.88073325],
       [0.88029104],
       [0.87971294],
       [0.879996  ],
       [0.88122743],
       [0.8800948 ],
       [0.87965274],
       [0.87942046],
       [0.87952954],
       [0.8806583 ],
       [0.8796905 ],
       [0.8788442 ],
       [0.8782837 ],
       [0.87761956],
       [0.8787555 ],
       [0.8782693 ],
       [0.876697  ],
       [0.87489253],
       [0.8738623 ],
       [0.87444115],
       [0.8736325 ],
       [0.8726794 ],
       [0.87066853],
       [0.8709279 ],
       [0.87165195],
       [0.871162  ],
       [0.87052494],
       [0.86843735],
       [0.8689262 ],
       [0.868123  ],
       [0.8676042 ],
       [0.866663  ],
       [0.86516505],
       [0.8659939 ],
       [0.86431366],
       [0.8627656 ],
       [0.86229414],
       [0.8616221 ],
       [0.8636959 ],
       [0.86294854],
       [0.8608371 ],
       [0.86026424],
       [0.8608548 ],
       [0.86329865],
       [0.8631572 ],
       [0.86202806],
       [0.862878  ],
       [0.8642617 ],
       [0.86627764],
       [0.86666137],
       [0.8645748 ],
       [0.8640064 ],
       [0.8645288 ],
       [0.8657058 ],
       [0.8656523 ],
       [0.86444974],
       [0.8641553 ],
       [0.8644513 ],
       [0.8660465 ],
       [0.86517084],
       [0.8648759 ],
       [0.8663811 ],
       [0.86719686],
       [0.8682248 ],
       [0.8684337 ],
       [0.8691116 ],
       [0.8696812 ],
       [0.87086207],
       [0.8719111 ],
       [0.87166065],
       [0.87199223],
       [0.8718538 ],
       [0.87225205],
       [0.8722187 ],
       [0.87167174],
       [0.8720989 ],
       [0.87238365],
       [0.8737735 ],
       [0.875004  ],
       [0.87475   ],
       [0.87459016],
       [0.87442476],
       [0.8756792 ],
       [0.8778346 ],
       [0.87746274],
       [0.87677705],
       [0.87601167],
       [0.8765929 ],
       [0.8789212 ],
       [0.878167  ],
       [0.8775483 ],
       [0.8763202 ],
       [0.8763106 ],
       [0.8778365 ],
       [0.8755233 ],
       [0.8750437 ],
       [0.8735829 ],
       [0.87313825],
       [0.8744342 ],
       [0.8708617 ],
       [0.87037313],
       [0.86863965],
       [0.86771005],
       [0.8675245 ],
       [0.8627866 ],
       [0.8627374 ],
       [0.86062366],
       [0.85954434],
       [0.8574664 ],
       [0.85715955],
       [0.85510826],
       [0.8513505 ],
       [0.8511036 ],
       [0.85131353],
       [0.8473994 ],
       [0.84531784],
       [0.8408591 ],
       [0.84133416],
       [0.84173304],
       [0.84077215],
       [0.8385704 ],
       [0.8358547 ],
       [0.8361714 ],
       [0.8375828 ],
       [0.83330536],
       [0.8317974 ],
       [0.8273575 ],
       [0.82899934],
       [0.82960874],
       [0.82799286],
       [0.82613945],
       [0.8225089 ],
       [0.8230155 ],
       [0.82395035],
       [0.82327527],
       [0.82217246],
       [0.82269675],
       [0.8236773 ],
       [0.8219093 ],
       [0.82084125],
       [0.8185796 ],
       [0.8207426 ],
       [0.8222916 ],
       [0.8213686 ],
       [0.8200865 ],
       [0.81936   ],
       [0.8208106 ],
       [0.8233871 ],
       [0.8247306 ],
       [0.82602483],
       [0.82525456],
       [0.8271254 ],
       [0.83003396],
       [0.82962674],
       [0.83052194],
       [0.8313582 ],
       [0.8338805 ],
       [0.83237135],
       [0.8339416 ],
       [0.8365639 ],
       [0.8357967 ],
       [0.83510363],
       [0.8375289 ],
       [0.83977646],
       [0.843172  ],
       [0.84148   ],
       [0.8432875 ],
       [0.843388  ],
       [0.8445527 ],
       [0.84643525],
       [0.8458716 ],
       [0.8467916 ],
       [0.84760696],
       [0.8471515 ],
       [0.8496626 ],
       [0.84930533],
       [0.85048354],
       [0.85041064],
       [0.85064036],
       [0.85195416],
       [0.85264367],
       [0.8535721 ],
       [0.8537123 ],
       [0.85108453],
       [0.850661  ],
       [0.85097593],
       [0.8527753 ],
       [0.85359406],
       [0.8530006 ],
       [0.85317117],
       [0.8538645 ],
       [0.85486525],
       [0.85421383],
       [0.8547241 ],
       [0.85653734],
       [0.8568898 ],
       [0.855557  ],
       [0.85445184],
       [0.85533303],
       [0.85534155],
       [0.8557419 ],
       [0.8567153 ],
       [0.855529  ],
       [0.8567856 ],
       [0.8571621 ],
       [0.8586131 ],
       [0.8582311 ],
       [0.85825014],
       [0.85817784]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
16550     28526.0   28000.79621  28084.034609           NaN
16551     28546.0  27441.039487   27743.33194           NaN
16552     28723.0  27653.008343  28106.194443           NaN
16572     25572.0  28695.531858       28406.4           NaN
16573     24963.0   26100.23055  26665.619348           NaN
...           ...           ...           ...           ...
18254     25653.0  25624.012047  26388.864157  25714.863281
18255     25362.0  25407.643926  25765.293528  25758.392578
18277     26277.0  26526.444089  26570.909285  25746.933594
18278     25598.0  26062.873849  26251.964527  25747.503906
18279     25399.0  25466.884147  25856.443648  25745.335938

[298 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 145s 9s/step - loss: 0.8069 - mean_absolute_error: 0.8878 - mean_absolute_percentage_error: 41334.4766 - root_mean_squared_error: 0.8983 - val_loss: 0.6770 - val_mean_absolute_error: 0.8160 - val_mean_absolute_percentage_error: 94.2462 - val_root_mean_squared_error: 0.8228
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 28s 2s/step - loss: 0.7168 - mean_absolute_error: 0.8368 - mean_absolute_percentage_error: 490076.4062 - root_mean_squared_error: 0.8466 - val_loss: 0.5334 - val_mean_absolute_error: 0.7227 - val_mean_absolute_percentage_error: 83.2632 - val_root_mean_squared_error: 0.7304
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 7s/step - loss: 0.5560 - mean_absolute_error: 0.7355 - mean_absolute_percentage_error: 1415517.2500 - root_mean_squared_error: 0.7455 - val_loss: 0.3067 - val_mean_absolute_error: 0.5437 - val_mean_absolute_percentage_error: 62.1860 - val_root_mean_squared_error: 0.5538
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 4s/step - loss: 0.3083 - mean_absolute_error: 0.5416 - mean_absolute_percentage_error: 3211195.5000 - root_mean_squared_error: 0.5549 - val_loss: 0.0564 - val_mean_absolute_error: 0.2182 - val_mean_absolute_percentage_error: 24.3237 - val_root_mean_squared_error: 0.2374
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 31s 7s/step - loss: 0.0629 - mean_absolute_error: 0.2150 - mean_absolute_percentage_error: 5920694.0000 - root_mean_squared_error: 0.2502 - val_loss: 0.0874 - val_mean_absolute_error: 0.2761 - val_mean_absolute_percentage_error: 34.3167 - val_root_mean_squared_error: 0.2956
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 3s/step - loss: 0.1181 - mean_absolute_error: 0.2848 - mean_absolute_percentage_error: 9545499.0000 - root_mean_squared_error: 0.3433 - val_loss: 0.0994 - val_mean_absolute_error: 0.2970 - val_mean_absolute_percentage_error: 36.7808 - val_root_mean_squared_error: 0.3152
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 7s/step - loss: 0.0932 - mean_absolute_error: 0.2471 - mean_absolute_percentage_error: 9924054.0000 - root_mean_squared_error: 0.3051 - val_loss: 0.0122 - val_mean_absolute_error: 0.0851 - val_mean_absolute_percentage_error: 11.1035 - val_root_mean_squared_error: 0.1102
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 4s/step - loss: 0.0357 - mean_absolute_error: 0.1345 - mean_absolute_percentage_error: 7641805.0000 - root_mean_squared_error: 0.1889 - val_loss: 0.0294 - val_mean_absolute_error: 0.1511 - val_mean_absolute_percentage_error: 16.8902 - val_root_mean_squared_error: 0.1715
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 29s 7s/step - loss: 0.0596 - mean_absolute_error: 0.2119 - mean_absolute_percentage_error: 7107288.0000 - root_mean_squared_error: 0.2441 - val_loss: 0.0360 - val_mean_absolute_error: 0.1697 - val_mean_absolute_percentage_error: 18.9250 - val_root_mean_squared_error: 0.1897
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 44s 7s/step - loss: 0.0641 - mean_absolute_error: 0.2220 - mean_absolute_percentage_error: 6272613.0000 - root_mean_squared_error: 0.2532 - val_loss: 0.0181 - val_mean_absolute_error: 0.1170 - val_mean_absolute_percentage_error: 13.3740 - val_root_mean_squared_error: 0.1346
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 48s 8s/step - loss: 0.0394 - mean_absolute_error: 0.1537 - mean_absolute_percentage_error: 6696256.0000 - root_mean_squared_error: 0.1983 - val_loss: 0.0120 - val_mean_absolute_error: 0.0850 - val_mean_absolute_percentage_error: 11.0751 - val_root_mean_squared_error: 0.1096
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 37s 4s/step - loss: 0.0340 - mean_absolute_error: 0.1284 - mean_absolute_percentage_error: 7907156.5000 - root_mean_squared_error: 0.1845 - val_loss: 0.0234 - val_mean_absolute_error: 0.1141 - val_mean_absolute_percentage_error: 15.1893 - val_root_mean_squared_error: 0.1530
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 28s 6s/step - loss: 0.0388 - mean_absolute_error: 0.1432 - mean_absolute_percentage_error: 6899497.0000 - root_mean_squared_error: 0.1970 - val_loss: 0.0227 - val_mean_absolute_error: 0.1116 - val_mean_absolute_percentage_error: 14.8821 - val_root_mean_squared_error: 0.1507
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 3s/step - loss: 0.0394 - mean_absolute_error: 0.1406 - mean_absolute_percentage_error: 9428658.0000 - root_mean_squared_error: 0.1985 - val_loss: 0.0128 - val_mean_absolute_error: 0.0859 - val_mean_absolute_percentage_error: 11.2941 - val_root_mean_squared_error: 0.1132
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 28s 5s/step - loss: 0.0341 - mean_absolute_error: 0.1279 - mean_absolute_percentage_error: 7507355.0000 - root_mean_squared_error: 0.1847 - val_loss: 0.0116 - val_mean_absolute_error: 0.0905 - val_mean_absolute_percentage_error: 11.0447 - val_root_mean_squared_error: 0.1075
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 29s 9s/step - loss: 0.0334 - mean_absolute_error: 0.1306 - mean_absolute_percentage_error: 7169031.5000 - root_mean_squared_error: 0.1828 - val_loss: 0.0125 - val_mean_absolute_error: 0.0965 - val_mean_absolute_percentage_error: 11.5442 - val_root_mean_squared_error: 0.1119
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 44s 9s/step - loss: 0.0360 - mean_absolute_error: 0.1391 - mean_absolute_percentage_error: 7309906.5000 - root_mean_squared_error: 0.1897 - val_loss: 0.0113 - val_mean_absolute_error: 0.0882 - val_mean_absolute_percentage_error: 10.8835 - val_root_mean_squared_error: 0.1062
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 6s/step - loss: 0.0320 - mean_absolute_error: 0.1266 - mean_absolute_percentage_error: 6462306.5000 - root_mean_squared_error: 0.1788 - val_loss: 0.0121 - val_mean_absolute_error: 0.0854 - val_mean_absolute_percentage_error: 11.1328 - val_root_mean_squared_error: 0.1102
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 32s 8s/step - loss: 0.0310 - mean_absolute_error: 0.1237 - mean_absolute_percentage_error: 7608078.0000 - root_mean_squared_error: 0.1761 - val_loss: 0.0139 - val_mean_absolute_error: 0.0867 - val_mean_absolute_percentage_error: 11.5387 - val_root_mean_squared_error: 0.1181
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 43s 8s/step - loss: 0.0303 - mean_absolute_error: 0.1217 - mean_absolute_percentage_error: 6492406.5000 - root_mean_squared_error: 0.1740 - val_loss: 0.0130 - val_mean_absolute_error: 0.0860 - val_mean_absolute_percentage_error: 11.3379 - val_root_mean_squared_error: 0.1139
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 48s 8s/step - loss: 0.0319 - mean_absolute_error: 0.1262 - mean_absolute_percentage_error: 8298695.0000 - root_mean_squared_error: 0.1786 - val_loss: 0.0115 - val_mean_absolute_error: 0.0850 - val_mean_absolute_percentage_error: 10.9406 - val_root_mean_squared_error: 0.1073
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 43s 7s/step - loss: 0.0288 - mean_absolute_error: 0.1187 - mean_absolute_percentage_error: 7149879.0000 - root_mean_squared_error: 0.1697 - val_loss: 0.0111 - val_mean_absolute_error: 0.0854 - val_mean_absolute_percentage_error: 10.7868 - val_root_mean_squared_error: 0.1053
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 46s 8s/step - loss: 0.0309 - mean_absolute_error: 0.1245 - mean_absolute_percentage_error: 7096991.0000 - root_mean_squared_error: 0.1756 - val_loss: 0.0111 - val_mean_absolute_error: 0.0852 - val_mean_absolute_percentage_error: 10.7959 - val_root_mean_squared_error: 0.1055
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 40s 6s/step - loss: 0.0285 - mean_absolute_error: 0.1186 - mean_absolute_percentage_error: 5556768.0000 - root_mean_squared_error: 0.1685 - val_loss: 0.0113 - val_mean_absolute_error: 0.0849 - val_mean_absolute_percentage_error: 10.8773 - val_root_mean_squared_error: 0.1065
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 8s/step - loss: 0.0304 - mean_absolute_error: 0.1192 - mean_absolute_percentage_error: 7656617.5000 - root_mean_squared_error: 0.1743 - val_loss: 0.0113 - val_mean_absolute_error: 0.0849 - val_mean_absolute_percentage_error: 10.8690 - val_root_mean_squared_error: 0.1064
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 37s 5s/step - loss: 0.0287 - mean_absolute_error: 0.1162 - mean_absolute_percentage_error: 7330008.0000 - root_mean_squared_error: 0.1695 - val_loss: 0.0113 - val_mean_absolute_error: 0.0848 - val_mean_absolute_percentage_error: 10.8486 - val_root_mean_squared_error: 0.1062
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 8s/step - loss: 0.0280 - mean_absolute_error: 0.1192 - mean_absolute_percentage_error: 6649923.0000 - root_mean_squared_error: 0.1672 - val_loss: 0.0112 - val_mean_absolute_error: 0.0848 - val_mean_absolute_percentage_error: 10.8313 - val_root_mean_squared_error: 0.1060
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 42s 6s/step - loss: 0.0307 - mean_absolute_error: 0.1243 - mean_absolute_percentage_error: 7108131.5000 - root_mean_squared_error: 0.1753 - val_loss: 0.0117 - val_mean_absolute_error: 0.0849 - val_mean_absolute_percentage_error: 10.9939 - val_root_mean_squared_error: 0.1082
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 9s/step - loss: 0.0304 - mean_absolute_error: 0.1189 - mean_absolute_percentage_error: 7943789.5000 - root_mean_squared_error: 0.1745 - val_loss: 0.0122 - val_mean_absolute_error: 0.0852 - val_mean_absolute_percentage_error: 11.1232 - val_root_mean_squared_error: 0.1103
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 4s/step - loss: 0.0286 - mean_absolute_error: 0.1176 - mean_absolute_percentage_error: 6377652.0000 - root_mean_squared_error: 0.1691 - val_loss: 0.0115 - val_mean_absolute_error: 0.0847 - val_mean_absolute_percentage_error: 10.9361 - val_root_mean_squared_error: 0.1074
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 38s 9s/step - loss: 0.0284 - mean_absolute_error: 0.1156 - mean_absolute_percentage_error: 7270274.0000 - root_mean_squared_error: 0.1686 - val_loss: 0.0110 - val_mean_absolute_error: 0.0850 - val_mean_absolute_percentage_error: 10.7456 - val_root_mean_squared_error: 0.1049
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 6s/step - loss: 0.0296 - mean_absolute_error: 0.1194 - mean_absolute_percentage_error: 7578123.0000 - root_mean_squared_error: 0.1720 - val_loss: 0.0110 - val_mean_absolute_error: 0.0847 - val_mean_absolute_percentage_error: 10.7458 - val_root_mean_squared_error: 0.1050
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 5s/step - loss: 0.0296 - mean_absolute_error: 0.1175 - mean_absolute_percentage_error: 7899961.5000 - root_mean_squared_error: 0.1720 - val_loss: 0.0113 - val_mean_absolute_error: 0.0843 - val_mean_absolute_percentage_error: 10.8376 - val_root_mean_squared_error: 0.1063
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 28s 9s/step - loss: 0.0299 - mean_absolute_error: 0.1198 - mean_absolute_percentage_error: 8200432.0000 - root_mean_squared_error: 0.1727 - val_loss: 0.0116 - val_mean_absolute_error: 0.0844 - val_mean_absolute_percentage_error: 10.9374 - val_root_mean_squared_error: 0.1078
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 43s 7s/step - loss: 0.0299 - mean_absolute_error: 0.1173 - mean_absolute_percentage_error: 8121502.0000 - root_mean_squared_error: 0.1728 - val_loss: 0.0118 - val_mean_absolute_error: 0.0843 - val_mean_absolute_percentage_error: 10.9766 - val_root_mean_squared_error: 0.1088
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 18s 6s/step - loss: 0.0288 - mean_absolute_error: 0.1162 - mean_absolute_percentage_error: 7074751.5000 - root_mean_squared_error: 0.1697 - val_loss: 0.0117 - val_mean_absolute_error: 0.0839 - val_mean_absolute_percentage_error: 10.9075 - val_root_mean_squared_error: 0.1080
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 32s 10s/step - loss: 0.0278 - mean_absolute_error: 0.1159 - mean_absolute_percentage_error: 7083428.0000 - root_mean_squared_error: 0.1667 - val_loss: 0.0111 - val_mean_absolute_error: 0.0833 - val_mean_absolute_percentage_error: 10.7209 - val_root_mean_squared_error: 0.1053
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 30s 8s/step - loss: 0.0272 - mean_absolute_error: 0.1131 - mean_absolute_percentage_error: 7775653.0000 - root_mean_squared_error: 0.1651 - val_loss: 0.0107 - val_mean_absolute_error: 0.0830 - val_mean_absolute_percentage_error: 10.5865 - val_root_mean_squared_error: 0.1037
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 5s/step - loss: 0.0267 - mean_absolute_error: 0.1131 - mean_absolute_percentage_error: 6843857.0000 - root_mean_squared_error: 0.1635 - val_loss: 0.0108 - val_mean_absolute_error: 0.0823 - val_mean_absolute_percentage_error: 10.5669 - val_root_mean_squared_error: 0.1037
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 28s 8s/step - loss: 0.0264 - mean_absolute_error: 0.1145 - mean_absolute_percentage_error: 6312744.5000 - root_mean_squared_error: 0.1624 - val_loss: 0.0108 - val_mean_absolute_error: 0.0816 - val_mean_absolute_percentage_error: 10.5237 - val_root_mean_squared_error: 0.1037
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 33s 8s/step - loss: 0.0293 - mean_absolute_error: 0.1178 - mean_absolute_percentage_error: 7730735.0000 - root_mean_squared_error: 0.1712 - val_loss: 0.0111 - val_mean_absolute_error: 0.0807 - val_mean_absolute_percentage_error: 10.5449 - val_root_mean_squared_error: 0.1055
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 4s/step - loss: 0.0274 - mean_absolute_error: 0.1122 - mean_absolute_percentage_error: 7769139.5000 - root_mean_squared_error: 0.1657 - val_loss: 0.0112 - val_mean_absolute_error: 0.0795 - val_mean_absolute_percentage_error: 10.4341 - val_root_mean_squared_error: 0.1057
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 17s 6s/step - loss: 0.0270 - mean_absolute_error: 0.1126 - mean_absolute_percentage_error: 7324440.0000 - root_mean_squared_error: 0.1643 - val_loss: 0.0104 - val_mean_absolute_error: 0.0782 - val_mean_absolute_percentage_error: 10.1622 - val_root_mean_squared_error: 0.1020
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 36s 11s/step - loss: 0.0274 - mean_absolute_error: 0.1144 - mean_absolute_percentage_error: 7600557.0000 - root_mean_squared_error: 0.1655 - val_loss: 0.0102 - val_mean_absolute_error: 0.0767 - val_mean_absolute_percentage_error: 9.9599 - val_root_mean_squared_error: 0.1010
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 35s 8s/step - loss: 0.0259 - mean_absolute_error: 0.1108 - mean_absolute_percentage_error: 6704140.0000 - root_mean_squared_error: 0.1609 - val_loss: 0.0105 - val_mean_absolute_error: 0.0745 - val_mean_absolute_percentage_error: 9.7750 - val_root_mean_squared_error: 0.1026
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 47s 8s/step - loss: 0.0259 - mean_absolute_error: 0.1104 - mean_absolute_percentage_error: 7814658.5000 - root_mean_squared_error: 0.1609 - val_loss: 0.0106 - val_mean_absolute_error: 0.0742 - val_mean_absolute_percentage_error: 9.7366 - val_root_mean_squared_error: 0.1028
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 35s 5s/step - loss: 0.0260 - mean_absolute_error: 0.1109 - mean_absolute_percentage_error: 7728234.5000 - root_mean_squared_error: 0.1613 - val_loss: 0.0104 - val_mean_absolute_error: 0.0745 - val_mean_absolute_percentage_error: 9.7305 - val_root_mean_squared_error: 0.1018
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 31s 8s/step - loss: 0.0258 - mean_absolute_error: 0.1102 - mean_absolute_percentage_error: 7121242.0000 - root_mean_squared_error: 0.1605 - val_loss: 0.0098 - val_mean_absolute_error: 0.0751 - val_mean_absolute_percentage_error: 9.7176 - val_root_mean_squared_error: 0.0989
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 37s 5s/step - loss: 0.0251 - mean_absolute_error: 0.1102 - mean_absolute_percentage_error: 8088911.5000 - root_mean_squared_error: 0.1582 - val_loss: 0.0096 - val_mean_absolute_error: 0.0755 - val_mean_absolute_percentage_error: 9.7171 - val_root_mean_squared_error: 0.0979
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 26s 7s/step - loss: 0.0245 - mean_absolute_error: 0.1078 - mean_absolute_percentage_error: 7281031.5000 - root_mean_squared_error: 0.1564 - val_loss: 0.0096 - val_mean_absolute_error: 0.0754 - val_mean_absolute_percentage_error: 9.7243 - val_root_mean_squared_error: 0.0982

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

8/8 ━━━━━━━━━━━━━━━━━━━━ 15s 704ms/step

array([[0.8726911 ],
       [0.87249213],
       [0.8689657 ],
       [0.869546  ],
       [0.87474954],
       [0.8749793 ],
       [0.87496156],
       [0.8757536 ],
       [0.8747025 ],
       [0.8798923 ],
       [0.8827706 ],
       [0.8851206 ],
       [0.88753414],
       [0.8864283 ],
       [0.88982433],
       [0.89180475],
       [0.8937475 ],
       [0.8955782 ],
       [0.8932132 ],
       [0.8933301 ],
       [0.89558744],
       [0.89734334],
       [0.89707744],
       [0.89603144],
       [0.89731175],
       [0.8987145 ],
       [0.9001654 ],
       [0.89907223],
       [0.89972466],
       [0.8998817 ],
       [0.9002709 ],
       [0.90158635],
       [0.9002516 ],
       [0.9000081 ],
       [0.9021053 ],
       [0.90312815],
       [0.90267366],
       [0.9016976 ],
       [0.9010266 ],
       [0.8992475 ],
       [0.90041167],
       [0.8989498 ],
       [0.8975012 ],
       [0.8979803 ],
       [0.8978551 ],
       [0.89889115],
       [0.89881223],
       [0.89703184],
       [0.89705414],
       [0.89729494],
       [0.8986507 ],
       [0.8965641 ],
       [0.8952483 ],
       [0.89373004],
       [0.89190406],
       [0.8910678 ],
       [0.8894742 ],
       [0.8876638 ],
       [0.8858821 ],
       [0.8828434 ],
       [0.88208395],
       [0.881023  ],
       [0.8808289 ],
       [0.87582743],
       [0.8726725 ],
       [0.87282795],
       [0.87638277],
       [0.87703514],
       [0.87178165],
       [0.86866635],
       [0.868895  ],
       [0.8674109 ],
       [0.8637685 ],
       [0.8597971 ],
       [0.8578835 ],
       [0.8558157 ],
       [0.85148543],
       [0.84682417],
       [0.8468502 ],
       [0.8515136 ],
       [0.85546017],
       [0.8518995 ],
       [0.8473188 ],
       [0.8499702 ],
       [0.8549976 ],
       [0.85891324],
       [0.8596559 ],
       [0.85839254],
       [0.8628156 ],
       [0.86697096],
       [0.86979395],
       [0.8681282 ],
       [0.8618202 ],
       [0.8622989 ],
       [0.86655176],
       [0.86994106],
       [0.8658629 ],
       [0.86142075],
       [0.8664319 ],
       [0.87059104],
       [0.873909  ],
       [0.8765097 ],
       [0.8744524 ],
       [0.8787753 ],
       [0.88177663],
       [0.8844514 ],
       [0.8863142 ],
       [0.8845135 ],
       [0.8875077 ],
       [0.889512  ],
       [0.8912841 ],
       [0.8913848 ],
       [0.89100444],
       [0.89052415],
       [0.8886133 ],
       [0.89038455],
       [0.89077705],
       [0.8897386 ],
       [0.8925424 ],
       [0.8941712 ],
       [0.89589566],
       [0.89702004],
       [0.8958381 ],
       [0.8970226 ],
       [0.89867413],
       [0.9000883 ],
       [0.89933807],
       [0.89725614],
       [0.8970502 ],
       [0.8986664 ],
       [0.8996285 ],
       [0.8967605 ],
       [0.89482677],
       [0.89380777],
       [0.8937517 ],
       [0.892732  ],
       [0.8906662 ],
       [0.8878964 ],
       [0.8847593 ],
       [0.883838  ],
       [0.8828369 ],
       [0.88008857],
       [0.8771501 ],
       [0.8750146 ],
       [0.87547004],
       [0.872811  ],
       [0.8691767 ],
       [0.8649587 ],
       [0.8606598 ],
       [0.85908586],
       [0.85678905],
       [0.85217863],
       [0.8462748 ],
       [0.84082043],
       [0.84004253],
       [0.8370757 ],
       [0.8310581 ],
       [0.8239712 ],
       [0.8181277 ],
       [0.8180478 ],
       [0.81649363],
       [0.81536955],
       [0.81328636],
       [0.8085231 ],
       [0.80751806],
       [0.8041509 ],
       [0.7971694 ],
       [0.79003704],
       [0.7839963 ],
       [0.7848597 ],
       [0.79007596],
       [0.79035395],
       [0.7794246 ],
       [0.77354276],
       [0.77325976],
       [0.7726639 ],
       [0.7685005 ],
       [0.7697855 ],
       [0.7663896 ],
       [0.7652277 ],
       [0.76334804],
       [0.76025933],
       [0.7609286 ],
       [0.76168287],
       [0.76195276],
       [0.7625961 ],
       [0.7624226 ],
       [0.7635289 ],
       [0.7657308 ],
       [0.7680088 ],
       [0.764455  ],
       [0.7605401 ],
       [0.76148516],
       [0.7622223 ],
       [0.76245093],
       [0.7637528 ],
       [0.76378816],
       [0.76467377],
       [0.76446265],
       [0.7657354 ],
       [0.7677154 ],
       [0.7675367 ],
       [0.7677977 ],
       [0.76961714],
       [0.7715576 ],
       [0.7720646 ],
       [0.77197516],
       [0.77288073],
       [0.7751196 ],
       [0.77548605],
       [0.77495736],
       [0.77550834],
       [0.77714014],
       [0.7775296 ],
       [0.777524  ],
       [0.77829534],
       [0.778173  ],
       [0.7777036 ],
       [0.77092874],
       [0.76983076],
       [0.7700327 ],
       [0.7705393 ],
       [0.77580875],
       [0.7751115 ],
       [0.7706798 ],
       [0.7675052 ],
       [0.767857  ],
       [0.7729421 ],
       [0.7735593 ],
       [0.77208024],
       [0.7727631 ],
       [0.7766152 ],
       [0.7771838 ],
       [0.7764994 ],
       [0.77693397],
       [0.77703196],
       [0.7818875 ],
       [0.7780529 ],
       [0.77829975],
       [0.7782969 ],
       [0.778997  ],
       [0.7799897 ],
       [0.7805465 ],
       [0.7797783 ],
       [0.78010947],
       [0.78059715],
       [0.7832188 ],
       [0.7833063 ],
       [0.78224474],
       [0.78268796]], dtype=float32)

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
16550     28526.0   28000.79621  28084.034609           NaN
16551     28546.0  27441.039487   27743.33194           NaN
16552     28723.0  27653.008343  28106.194443           NaN
16572     25572.0  28695.531858       28406.4           NaN
16573     24963.0   26100.23055  26665.619348           NaN
...           ...           ...           ...           ...
18254     25653.0  25624.012047  26388.864157  23417.914062
18255     25362.0  25407.643926  25765.293528  23496.564453
18277     26277.0  26526.444089  26570.909285  23499.189453
18278     25598.0  26062.873849  26251.964527  23467.341797
18279     25399.0  25466.884147  25856.443648  23480.638672

[298 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,601 (1.55 MB)

 Trainable params: 405,345 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 328s 487ms/step - loss: 0.2298 - mae: 0.5852 - val_loss: 0.2573 - val_mae: 0.6950
Epoch 2/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 89s 477ms/step - loss: 0.1855 - mae: 0.5148 - val_loss: 0.1726 - val_mae: 0.5542
Epoch 3/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 84s 465ms/step - loss: 0.1635 - mae: 0.4744 - val_loss: 0.1311 - val_mae: 0.4674
Epoch 4/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 72s 386ms/step - loss: 0.1581 - mae: 0.4579 - val_loss: 0.0858 - val_mae: 0.3270
Epoch 5/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 96s 444ms/step - loss: 0.1316 - mae: 0.4080 - val_loss: 0.0663 - val_mae: 0.2991
Epoch 6/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 83s 420ms/step - loss: 0.1121 - mae: 0.3778 - val_loss: 0.0594 - val_mae: 0.2728
Epoch 7/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 85s 404ms/step - loss: 0.1109 - mae: 0.3631 - val_loss: 0.0707 - val_mae: 0.2923
Epoch 8/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 94s 447ms/step - loss: 0.1094 - mae: 0.3618 - val_loss: 0.0559 - val_mae: 0.2477
Epoch 9/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 73s 374ms/step - loss: 0.1226 - mae: 0.3563 - val_loss: 0.1054 - val_mae: 0.3700
Epoch 10/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 97s 437ms/step - loss: 0.1004 - mae: 0.3459 - val_loss: 0.0516 - val_mae: 0.2346
Epoch 11/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 58s 324ms/step - loss: 0.1053 - mae: 0.3497 - val_loss: 0.0724 - val_mae: 0.2937
Epoch 12/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 116s 502ms/step - loss: 0.0960 - mae: 0.3218 - val_loss: 0.0708 - val_mae: 0.2983
Epoch 13/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 132s 418ms/step - loss: 0.0877 - mae: 0.3075 - val_loss: 0.0567 - val_mae: 0.2581
Epoch 14/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 92s 513ms/step - loss: 0.0908 - mae: 0.3156 - val_loss: 0.0554 - val_mae: 0.2493
Epoch 15/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 119s 346ms/step - loss: 0.1020 - mae: 0.3274 - val_loss: 0.0627 - val_mae: 0.2707
Epoch 16/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 113s 491ms/step - loss: 0.0888 - mae: 0.3033 - val_loss: 0.0522 - val_mae: 0.2323
Epoch 17/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 74s 395ms/step - loss: 0.0887 - mae: 0.3125 - val_loss: 0.0580 - val_mae: 0.2620
Epoch 18/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 94s 435ms/step - loss: 0.0868 - mae: 0.3098 - val_loss: 0.0603 - val_mae: 0.2716
Epoch 19/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 95s 526ms/step - loss: 0.0872 - mae: 0.3056 - val_loss: 0.0504 - val_mae: 0.2286
Epoch 20/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 145s 518ms/step - loss: 0.0806 - mae: 0.2907 - val_loss: 0.0480 - val_mae: 0.2119
Epoch 21/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 148s 523ms/step - loss: 0.0857 - mae: 0.3003 - val_loss: 0.0682 - val_mae: 0.2882
Epoch 22/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 137s 442ms/step - loss: 0.0825 - mae: 0.2963 - val_loss: 0.0744 - val_mae: 0.3086
Epoch 23/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 90s 458ms/step - loss: 0.0782 - mae: 0.2812 - val_loss: 0.0534 - val_mae: 0.2314
Epoch 24/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 84s 445ms/step - loss: 0.0767 - mae: 0.2762 - val_loss: 0.0538 - val_mae: 0.2467
Epoch 25/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 91s 471ms/step - loss: 0.0787 - mae: 0.2833 - val_loss: 0.0511 - val_mae: 0.2227
Epoch 26/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 78s 413ms/step - loss: 0.0745 - mae: 0.2832 - val_loss: 0.0492 - val_mae: 0.2189
Epoch 27/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 74s 406ms/step - loss: 0.0741 - mae: 0.2760 - val_loss: 0.0510 - val_mae: 0.2320
Epoch 28/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 99s 482ms/step - loss: 0.0664 - mae: 0.2601 - val_loss: 0.0568 - val_mae: 0.2606
Epoch 29/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 95s 518ms/step - loss: 0.0678 - mae: 0.2698 - val_loss: 0.0522 - val_mae: 0.2402
Epoch 30/100
168/168 ━━━━━━━━━━━━━━━━━━━━ 146s 512ms/step - loss: 0.0693 - mae: 0.2598 - val_loss: 0.0579 - val_mae: 0.2747

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002612B65DD30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
8/8 ━━━━━━━━━━━━━━━━━━━━ 65s 4s/step

array([[0.9218264 ],
       [0.8446328 ],
       [1.0652634 ],
       [1.0239036 ],
       [1.0946991 ],
       [1.0523978 ],
       [1.099423  ],
       [1.1439434 ],
       [1.1041492 ],
       [1.0478956 ],
       [0.9613395 ],
       [0.8591307 ],
       [0.78919536],
       [0.7996155 ],
       [0.75218964],
       [0.6940972 ],
       [0.6398144 ],
       [0.62347853],
       [0.6627694 ],
       [0.6594491 ],
       [0.6360996 ],
       [0.6954222 ],
       [0.7163104 ],
       [0.76867485],
       [0.720865  ],
       [0.71936387],
       [0.73646075],
       [0.7602855 ],
       [0.7419674 ],
       [0.68399656],
       [0.68718386],
       [0.6713588 ],
       [0.68194354],
       [0.6701453 ],
       [0.6287475 ],
       [0.6519225 ],
       [0.67223   ],
       [0.7283652 ],
       [0.717574  ],
       [0.73067856],
       [0.75270617],
       [0.7437881 ],
       [0.7496493 ],
       [0.7207644 ],
       [0.667727  ],
       [0.6848287 ],
       [0.6731316 ],
       [0.70653546],
       [0.67693466],
       [0.6587002 ],
       [0.6674035 ],
       [0.7176923 ],
       [0.72209156],
       [0.7218741 ],
       [0.6828505 ],
       [0.7442341 ],
       [0.7349868 ],
       [0.7606331 ],
       [0.76233387],
       [0.76167643],
       [0.79371303],
       [0.8299899 ],
       [0.76649433],
       [0.7458816 ],
       [0.7971082 ],
       [0.83099437],
       [0.8057574 ],
       [0.7839136 ],
       [0.7741641 ],
       [0.8129071 ],
       [0.8110851 ],
       [0.79498005],
       [0.8473234 ],
       [0.78119236],
       [0.93916136],
       [0.83217424],
       [0.90011406],
       [0.79169697],
       [0.9660661 ],
       [0.9388052 ],
       [1.0183159 ],
       [0.9738124 ],
       [0.98048735],
       [0.9410105 ],
       [0.9819025 ],
       [0.8435667 ],
       [0.92907506],
       [0.83676445],
       [0.9925996 ],
       [0.9393832 ],
       [0.9704196 ],
       [0.9679911 ],
       [1.0537623 ],
       [0.98731005],
       [0.9813715 ],
       [0.88202107],
       [0.90349   ],
       [0.88756675],
       [0.91332805],
       [0.7448323 ],
       [0.7186278 ],
       [0.66680694],
       [0.6701547 ],
       [0.5990217 ],
       [0.5713721 ],
       [0.5101098 ],
       [0.536067  ],
       [0.5645928 ],
       [0.5645293 ],
       [0.5222397 ],
       [0.53129506],
       [0.5694044 ],
       [0.59484863],
       [0.59176767],
       [0.60865664],
       [0.6188456 ],
       [0.6264588 ],
       [0.6517918 ],
       [0.6378694 ],
       [0.6344923 ],
       [0.6268477 ],
       [0.65604734],
       [0.68232816],
       [0.68714297],
       [0.65827197],
       [0.643805  ],
       [0.6355849 ],
       [0.66347015],
       [0.6220577 ],
       [0.63047487],
       [0.59853566],
       [0.6477304 ],
       [0.59406227],
       [0.5935025 ],
       [0.5771045 ],
       [0.6145551 ],
       [0.7316774 ],
       [0.90931284],
       [1.0260926 ],
       [1.0146701 ],
       [0.98263747],
       [1.0262464 ],
       [1.0721223 ],
       [1.1265785 ],
       [1.0721351 ],
       [0.9090527 ],
       [0.845062  ],
       [0.73123884],
       [0.5130384 ],
       [0.28208482],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.14968419],
       [0.20225966],
       [0.13930547],
       [0.        ],
       [0.        ],
       [0.3916437 ],
       [0.41220272],
       [0.61130285],
       [0.39267197],
       [0.9393413 ],
       [0.80748355],
       [1.1173309 ],
       [0.59211195],
       [0.86747557],
       [0.8042748 ],
       [0.9742999 ],
       [0.6709742 ],
       [0.54703563],
       [0.5057078 ],
       [0.6903256 ],
       [0.6029266 ],
       [0.68782353],
       [0.32848483],
       [0.50045514],
       [0.46643567],
       [0.5361673 ],
       [0.22308588],
       [0.28645414]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
16550     28526.0   28000.79621  28084.034609           NaN           NaN
16551     28546.0  27441.039487   27743.33194           NaN           NaN
16552     28723.0  27653.008343  28106.194443           NaN           NaN
16572     25572.0  28695.531858       28406.4           NaN           NaN
16573     24963.0   26100.23055  26665.619348           NaN           NaN
...           ...           ...           ...           ...           ...
18254     25653.0  25624.012047  26388.864157  23417.914062  15013.654297
18255     25362.0  25407.643926  25765.293528  23496.564453  13993.070312
18277     26277.0  26526.444089  26570.909285  23499.189453  16085.019531
18278     25598.0  26062.873849  26251.964527  23467.341797   6692.576172
18279     25399.0  25466.884147  25856.443648  23480.638672   8593.624023

[298 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

16815    24788.0
16816    27303.0
16836    27659.0
16837    27631.0
16838    27204.0
          ...
18254    25653.0
18255    25362.0
18277    26277.0
18278    25598.0
18279    25399.0
Name: Generación, Length: 250, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 6)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      1,600 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 473,281 (1.81 MB)

 Trainable params: 473,281 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50

84/84 ━━━━━━━━━━━━━━━━━━━━ 205s 556ms/step - loss: 1.4312 - mae: 0.4158 - val_loss: 0.9585 - val_mae: 0.0966
Epoch 2/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 64s 297ms/step - loss: 0.8721 - mae: 0.0874 - val_loss: 0.7043 - val_mae: 0.0964
Epoch 3/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 49s 318ms/step - loss: 0.6365 - mae: 0.0894 - val_loss: 0.5124 - val_mae: 0.1040
Epoch 4/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 42s 392ms/step - loss: 0.4606 - mae: 0.0874 - val_loss: 0.3735 - val_mae: 0.0988
Epoch 5/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 35s 320ms/step - loss: 0.3341 - mae: 0.0883 - val_loss: 0.2773 - val_mae: 0.0944
Epoch 6/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 38s 217ms/step - loss: 0.2402 - mae: 0.0844 - val_loss: 0.2042 - val_mae: 0.1118
Epoch 7/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 34s 336ms/step - loss: 0.1792 - mae: 0.0870 - val_loss: 0.1555 - val_mae: 0.1060
Epoch 8/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 44s 397ms/step - loss: 0.1309 - mae: 0.0826 - val_loss: 0.1267 - val_mae: 0.0964
Epoch 9/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 45s 410ms/step - loss: 0.1016 - mae: 0.0770 - val_loss: 0.1004 - val_mae: 0.0962
Epoch 10/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 41s 388ms/step - loss: 0.0773 - mae: 0.0741 - val_loss: 0.0859 - val_mae: 0.0968
Epoch 11/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 32s 296ms/step - loss: 0.0641 - mae: 0.0777 - val_loss: 0.0703 - val_mae: 0.0957
Epoch 12/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 42s 246ms/step - loss: 0.0502 - mae: 0.0740 - val_loss: 0.0609 - val_mae: 0.0926
Epoch 13/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 53s 365ms/step - loss: 0.0450 - mae: 0.0815 - val_loss: 0.0499 - val_mae: 0.1143
Epoch 14/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 43s 386ms/step - loss: 0.0360 - mae: 0.0706 - val_loss: 0.0438 - val_mae: 0.0889
Epoch 15/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 44s 443ms/step - loss: 0.0295 - mae: 0.0675 - val_loss: 0.0371 - val_mae: 0.0865
Epoch 16/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 49s 472ms/step - loss: 0.0282 - mae: 0.0709 - val_loss: 0.0369 - val_mae: 0.0910
Epoch 17/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 79s 353ms/step - loss: 0.0233 - mae: 0.0642 - val_loss: 0.0341 - val_mae: 0.1001
Epoch 18/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 37s 276ms/step - loss: 0.0220 - mae: 0.0681 - val_loss: 0.0311 - val_mae: 0.0895
Epoch 19/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 63s 472ms/step - loss: 0.0203 - mae: 0.0667 - val_loss: 0.0305 - val_mae: 0.0865
Epoch 20/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 50s 509ms/step - loss: 0.0157 - mae: 0.0607 - val_loss: 0.0261 - val_mae: 0.0981
Epoch 21/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 69s 293ms/step - loss: 0.0169 - mae: 0.0656 - val_loss: 0.0292 - val_mae: 0.0952
Epoch 22/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 28s 262ms/step - loss: 0.0157 - mae: 0.0664 - val_loss: 0.0323 - val_mae: 0.0980
Epoch 23/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 0.0152 - mae: 0.0660 - val_loss: 0.0260 - val_mae: 0.0865
Epoch 24/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 59s 464ms/step - loss: 0.0143 - mae: 0.0624 - val_loss: 0.0256 - val_mae: 0.0943
Epoch 25/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 37s 359ms/step - loss: 0.0133 - mae: 0.0632 - val_loss: 0.0258 - val_mae: 0.0867
Epoch 26/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 47s 344ms/step - loss: 0.0118 - mae: 0.0603 - val_loss: 0.0272 - val_mae: 0.0908
Epoch 27/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 49s 368ms/step - loss: 0.0107 - mae: 0.0575 - val_loss: 0.0280 - val_mae: 0.0908
Epoch 28/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 45s 353ms/step - loss: 0.0122 - mae: 0.0609 - val_loss: 0.0247 - val_mae: 0.0866
Epoch 29/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 44s 326ms/step - loss: 0.0129 - mae: 0.0624 - val_loss: 0.0250 - val_mae: 0.0914
Epoch 30/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 49s 366ms/step - loss: 0.0114 - mae: 0.0619 - val_loss: 0.0308 - val_mae: 0.0989
Epoch 31/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 40s 281ms/step - loss: 0.0123 - mae: 0.0632 - val_loss: 0.0261 - val_mae: 0.0925
Epoch 32/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 59s 424ms/step - loss: 0.0110 - mae: 0.0676 - val_loss: 0.0273 - val_mae: 0.0907
Epoch 33/50
84/84 ━━━━━━━━━━━━━━━━━━━━ 39s 315ms/step - loss: 0.0099 - mae: 0.0618 - val_loss: 0.0266 - val_mae: 0.0905

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x00000261345CB280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/8 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

8/8 ━━━━━━━━━━━━━━━━━━━━ 36s 2s/step

array([[0.8821268 ],
       [0.813296  ],
       [0.86029994],
       [0.9017311 ],
       [0.8786804 ],
       [0.8796775 ],
       [0.89616364],
       [0.90947884],
       [0.920426  ],
       [0.9074693 ],
       [0.91090506],
       [0.8978666 ],
       [0.89998966],
       [0.917474  ],
       [0.90970993],
       [0.906845  ],
       [0.89216065],
       [0.89585215],
       [0.9157665 ],
       [0.9185402 ],
       [0.9136083 ],
       [0.9033811 ],
       [0.89861166],
       [0.90283614],
       [0.85737133],
       [0.86131465],
       [0.8821773 ],
       [0.8986905 ],
       [0.89702135],
       [0.8923531 ],
       [0.88754743],
       [0.87391615],
       [0.89705175],
       [0.86261433],
       [0.79543716],
       [0.7333737 ],
       [0.77214974],
       [0.85859686],
       [0.86413187],
       [0.8998439 ],
       [0.89792246],
       [0.8755396 ],
       [0.90761566],
       [0.91750926],
       [0.88636035],
       [0.8969802 ],
       [0.88157344],
       [0.91035986],
       [0.89360917],
       [0.88839334],
       [0.88814956],
       [0.88464147],
       [0.8577952 ],
       [0.79245   ],
       [0.76990706],
       [0.8296085 ],
       [0.8687915 ],
       [0.8761457 ],
       [0.86401415],
       [0.85800564],
       [0.8968525 ],
       [0.90228176],
       [0.85878354],
       [0.83224916],
       [0.8750314 ],
       [0.894393  ],
       [0.8732602 ],
       [0.8662618 ],
       [0.8604219 ],
       [0.90315753],
       [0.8684279 ],
       [0.9017232 ],
       [0.84954137],
       [0.8131539 ],
       [0.7817133 ],
       [0.7601168 ],
       [0.743167  ],
       [0.84616566],
       [0.87433285],
       [0.8547923 ],
       [0.8462869 ],
       [0.87797314],
       [0.92988414],
       [0.925176  ],
       [0.88796633],
       [0.8737556 ],
       [0.87585163],
       [0.89422274],
       [0.8766966 ],
       [0.8804049 ],
       [0.86602813],
       [0.8703386 ],
       [0.890351  ],
       [0.9106659 ],
       [0.8755878 ],
       [0.85070825],
       [0.81499046],
       [0.86624235],
       [0.8806171 ],
       [0.89990413],
       [0.8788585 ],
       [0.90149516],
       [0.9213888 ],
       [0.92344624],
       [0.9087735 ],
       [0.90087587],
       [0.8986241 ],
       [0.9024654 ],
       [0.88650435],
       [0.88968337],
       [0.87245256],
       [0.87814945],
       [0.89765334],
       [0.9104495 ],
       [0.9154826 ],
       [0.89151436],
       [0.8678668 ],
       [0.8793866 ],
       [0.8973278 ],
       [0.8868237 ],
       [0.868268  ],
       [0.8732446 ],
       [0.85693777],
       [0.8324171 ],
       [0.8164161 ],
       [0.8372178 ],
       [0.82746595],
       [0.77530026],
       [0.7865038 ],
       [0.81940293],
       [0.7965029 ],
       [0.6594363 ],
       [0.5546506 ],
       [0.5105981 ],
       [0.5295294 ],
       [0.61040324],
       [0.54041344],
       [0.46012127],
       [0.5199547 ],
       [0.59734434],
       [0.71286386],
       [0.83568066],
       [0.86655825],
       [0.83880156],
       [0.763297  ],
       [0.8449498 ],
       [0.95461327],
       [0.9063973 ],
       [0.8992254 ],
       [0.8651831 ],
       [0.8911131 ],
       [0.7923977 ],
       [0.76042867],
       [0.7553518 ],
       [0.8397823 ],
       [0.82050526],
       [0.70309937],
       [0.7421006 ],
       [0.799184  ],
       [0.89741284],
       [0.8132834 ],
       [0.74332386],
       [0.9313733 ],
       [1.0077116 ],
       [0.9700218 ],
       [0.90198046],
       [0.7457251 ],
       [0.662358  ],
       [0.824673  ],
       [0.90192384],
       [0.9054968 ],
       [0.8998196 ],
       [0.9128594 ],
       [0.99044377],
       [0.95883375],
       [0.9495912 ],
       [0.9143129 ],
       [0.8831412 ],
       [0.8804074 ],
       [0.8706329 ],
       [0.89146644],
       [0.8552217 ],
       [0.80017155],
       [0.6895744 ],
       [0.70994115],
       [0.74586356],
       [0.8000694 ],
       [0.7890168 ],
       [0.8811632 ],
       [0.8429186 ],
       [0.8359913 ],
       [0.78395075],
       [0.71902215],
       [0.778737  ],
       [0.8279813 ],
       [0.8572772 ],
       [0.859774  ],
       [0.7942818 ],
       [0.7896583 ],
       [0.84121746],
       [0.80537444],
       [0.8211467 ],
       [0.8383426 ],
       [0.8704299 ],
       [0.8164108 ],
       [0.8224877 ],
       [0.83193535],
       [0.85135776],
       [0.7993695 ],
       [0.81430644],
       [0.8213048 ],
       [0.8462387 ],
       [0.801113  ],
       [0.81434304],
       [0.82533497],
       [0.8444244 ],
       [0.84389234],
       [0.8390593 ],
       [0.82927847],
       [0.82329893],
       [0.8353376 ],
       [0.85070014],
       [0.851621  ],
       [0.83429605],
       [0.84127146],
       [0.8546353 ],
       [0.8247989 ],
       [0.8331979 ],
       [0.82797676],
       [0.8403762 ],
       [0.83937544],
       [0.7879919 ],
       [0.8154331 ],
       [0.8205424 ],
       [0.828872  ],
       [0.82295793],
       [0.8380397 ],
       [0.8171721 ],
       [0.84833324],
       [0.8634184 ],
       [0.85452205],
       [0.84131736],
       [0.8213242 ],
       [0.82333976],
       [0.82265836],
       [0.8359948 ],
       [0.850596  ],
       [0.83468527],
       [0.8624254 ],
       [0.86372465]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
16550,28526.0,28000.79621,28084.034609,NaN,NaN,NaN
16551,28546.0,27441.039487,27743.33194,NaN,NaN,NaN
16552,28723.0,27653.008343,28106.194443,NaN,NaN,NaN
16572,25572.0,28695.531858,28406.4,NaN,NaN,NaN
16573,24963.0,26100.23055,26665.619348,NaN,NaN,NaN
...,...,...,...,...,...,...
18254,25653.0,25624.012047,26388.864157,23417.914062,15013.654297,25079.843750
18255,25362.0,25407.643926,25765.293528,23496.564453,13993.070312,25517.880859
18277,26277.0,26526.444089,26570.909285,23499.189453,16085.019531,25040.558594
18278,25598.0,26062.873849,26251.964527,23467.341797,6692.576172,25872.761719
18279,25399.0,25466.884147,25856.443648,23480.638672,8593.624023,25911.740234

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1654.2360
RMSE: 3114.7331
R²: 0.6976
Random Forest
MAE: 1717.0140
RMSE: 3069.3600
R²: 0.7063
CTNET
MAE: 4013.1179
RMSE: 6267.6130
R²: -0.1586
Forecast
MAE: 11959.2745
RMSE: 15365.9355
R²: -5.9638
Photovoltaic
MAE: 3065.4999
RMSE: 4982.9021
R²: 0.2677

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

42/42 ━━━━━━━━━━━━━━━━━━━━ 8s 69ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

42/42 ━━━━━━━━━━━━━━━━━━━━ 12s 138ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

42/42 ━━━━━━━━━━━━━━━━━━━━ 12s 79ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
60,17723.695569,18408.915820,17545.731151,NaN,NaN,NaN
62,21548.984244,17569.041197,21494.093666,NaN,NaN,NaN
63,25500.000000,20654.095675,24452.052101,NaN,NaN,NaN
64,23122.803757,24667.524780,23947.572378,NaN,NaN,NaN
84,22850.891263,16658.483574,21862.076445,NaN,NaN,NaN
...,...,...,...,...,...,...
15015,27978.000000,27534.177708,27838.222500,27428.035156,25066.638672,27297.425781
15016,29119.000000,27768.920192,28719.702500,27427.982422,25372.681641,27150.839844
15035,27248.000000,26921.211591,27329.209666,27429.828125,25485.687500,27527.341797
15036,28409.000000,28519.728260,28334.940000,27410.865234,25117.064453,27150.839844
15037,28107.000000,27795.372180,28028.885000,27407.744141,24891.695312,27781.619141

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1126.8062
RMSE: 2270.1274
R²: 0.6779
Random Forest
MAE: 401.4045
RMSE: 776.9427
R²: 0.9623
CTNET
MAE: 2128.3299
RMSE: 3600.4636
R²: 0.1555
Forecast
MAE: 7040.2763
RMSE: 10030.2871
R²: -5.5541
Photovoltaic
MAE: 1601.5441
RMSE: 2637.8954
R²: 0.5467

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.10_Predicciones_Conjunto_soleado GMM CTNET.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_10_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_10_RandomForest_model.pkl")

['4_10_RandomForest_model.pkl']

In [87]:
CTNET.save("4_10_CTNET_model.keras")
Forecast_model.save("4_10_Forecast_model.keras")
Photo_model.save("4_10_Photo_model.keras")