# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion_CTNET.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,77,0,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,82,0,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,85,0,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,87,0,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,88,0,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,86,0,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,89,0,6,Soleado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,95,0,7,Soleado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,100,0,8,Soleado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,100,1,9,Soleado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,93,2,10,Soleado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,79,2,11,Soleado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,64,6,12,Nublado,Soleado
13,2022-09-01 13:00:00,25478.471342,23,51,11,13,Nublado,Soleado
14,2022-09-01 14:00:00,29057.585772,25,41,12,14,Nublado,Soleado
15,2022-09-01 15:00:00,30000.000000,26,35,11,15,Nublado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,33,8,16,Nublado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,34,5,17,Nublado,Nublado
18,2022-09-01 18:00:00,29900.303971,27,37,3,18,Nublado,Nublado
19,2022-09-01 19:00:00,18282.505369,26,41,2,19,Nublado,Nublado
20,2022-09-01 20:00:00,3411.083740,24,48,0,20,Nublado,Nublado
21,2022-09-01 21:00:00,382.187718,22,55,0,21,Soleado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,61,0,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,68,0,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster GMM"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
36,2022-09-02 12:00:00,27523.885172,21,57,4,12,Nublado,Nublado,17036.043251,29196.986647
37,2022-09-02 13:00:00,20596.278869,23,45,5,13,Nublado,Nublado,27523.885172,25478.471342
38,2022-09-02 14:00:00,28500.000000,24,37,6,14,Nublado,Nublado,20596.278869,29057.585772
39,2022-09-02 15:00:00,24647.568577,26,33,5,15,Nublado,Nublado,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,34,4,16,Nublado,Nublado,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,36,2,17,Nublado,Nublado,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,39,1,18,Nublado,Nublado,24281.956494,29900.303971
43,2022-09-02 19:00:00,11972.590689,25,44,1,19,Nublado,Nublado,22733.515002,18282.505369
61,2022-09-03 13:00:00,20400.000000,23,48,5,13,Nublado,Nublado,17723.695569,20596.278869
65,2022-09-03 17:00:00,25602.778606,25,45,5,17,Nublado,Nublado,23122.803757,24281.956494

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,21,57,4,12,17036.043251,29196.986647
37,23,45,5,13,27523.885172,25478.471342
38,24,37,6,14,20596.278869,29057.585772
39,26,33,5,15,28500.000000,30000.000000
40,27,34,4,16,24647.568577,28062.328964
...,...,...,...,...,...,...
18281,26,31,4,16,25562.000000,25385.000000
18282,26,32,2,17,25386.000000,22664.000000
18283,25,33,1,18,22872.000000,15736.000000
18284,23,38,0,19,15825.000000,1407.000000
18285,22,45,0,20,1450.000000,0.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
36     27523.885172
37     20596.278869
38     28500.000000
39     24647.568577
40     25500.000000
...             ...
18281  25386.000000
18282  22872.000000
18283  15825.000000
18284   1450.000000
18285      0.000000

[4646 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 3252, y_train: 3252
X_val: 697, y_val: 697
X_test: 697, y_test: 697

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.43333333 0.98113208 0.4        0.4        0.56786811 0.97323289]
 [0.5        0.75471698 0.5        0.46666667 0.91746284 0.84928238]
 [0.53333333 0.60377358 0.6        0.53333333 0.68654263 0.96858619]
 ...
 [0.4        0.67924528 0.         1.         0.         0.        ]
 [0.26666667 0.81132075 0.4        0.33333333 0.6396     0.67536667]
 [0.4        0.56603774 0.5        0.4        0.66776667 0.65666667]]
(3252, 6)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.433333,0.981132,0.4,0.400000,0.567868,0.973233
37,0.500000,0.754717,0.5,0.466667,0.917463,0.849282
38,0.533333,0.603774,0.6,0.533333,0.686543,0.968586
39,0.600000,0.528302,0.5,0.600000,0.950000,1.000000
40,0.633333,0.547170,0.4,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
12596,0.633333,0.226415,0.0,0.866667,0.319667,0.173900
12597,0.500000,0.396226,0.0,0.933333,0.026400,0.000000
12598,0.400000,0.679245,0.0,1.000000,0.000000,0.000000
12612,0.266667,0.811321,0.4,0.333333,0.639600,0.675367
12613,0.400000,0.566038,0.5,0.400000,0.667767,0.656667

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.5        0.39622642 0.6        0.46666667 0.65776667 0.71383333]
 [0.56666667 0.30188679 0.5        0.53333333 0.63403333 0.62716667]
 [0.63333333 0.22641509 0.4        0.6        0.63616667 0.62633333]
 ...
 [0.4        0.49056604 0.3        0.2        0.37583333 0.7706    ]
 [0.53333333 0.30188679 0.5        0.26666667 0.74553333 0.859     ]
 [0.9        0.05660377 0.7        0.6        0.84236667 0.94003333]]
(697, 6)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
12614,0.500000,0.396226,0.6,0.466667,0.657767,0.713833
12615,0.566667,0.301887,0.5,0.533333,0.634033,0.627167
12616,0.633333,0.226415,0.4,0.600000,0.636167,0.626333
12617,0.666667,0.150943,0.3,0.666667,0.655400,0.626067
12618,0.733333,0.113208,0.2,0.733333,0.737567,0.527167
...,...,...,...,...,...,...
14590,0.633333,0.490566,0.0,1.000000,0.009467,0.000000
14601,0.300000,0.716981,0.2,0.133333,0.044967,0.422800
14602,0.400000,0.490566,0.3,0.200000,0.375833,0.770600
14603,0.533333,0.301887,0.5,0.266667,0.745533,0.859000
14608,0.900000,0.056604,0.7,0.600000,0.842367,0.940033

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.93333333 0.03773585 0.2        0.66666667 0.83383333 0.91813333]
 [0.96666667 0.03773585 0.2        0.73333333 0.72056667 0.88203333]
 [0.93333333 0.03773585 0.1        0.8        0.67996667 0.7186    ]
 ...
 [0.56666667 0.52830189 0.1        0.8        0.7624     0.52453333]
 [0.5        0.62264151 0.         0.86666667 0.5275     0.0469    ]
 [0.46666667 0.75471698 0.         0.93333333 0.04833333 0.        ]]
(697, 6)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
14609,0.933333,0.037736,0.2,0.666667,0.833833,0.918133
14610,0.966667,0.037736,0.2,0.733333,0.720567,0.882033
14611,0.933333,0.037736,0.1,0.800000,0.679967,0.718600
14612,0.900000,0.037736,0.0,0.866667,0.574900,0.273700
14613,0.800000,0.075472,0.0,0.933333,0.218967,0.009467
...,...,...,...,...,...,...
18281,0.600000,0.490566,0.4,0.666667,0.852067,0.846167
18282,0.600000,0.509434,0.2,0.733333,0.846200,0.755467
18283,0.566667,0.528302,0.1,0.800000,0.762400,0.524533
18284,0.500000,0.622642,0.0,0.866667,0.527500,0.046900
18285,0.466667,0.754717,0.0,0.933333,0.048333,0.000000

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.41935484 0.94736842 0.4        0.4        0.56786811 0.97323289]
 [0.48387097 0.73684211 0.5        0.46666667 0.91746284 0.84928238]
 [0.51612903 0.59649123 0.6        0.53333333 0.68654263 0.96858619]
 ...
 [0.5483871  0.52631579 0.1        0.8        0.7624     0.52453333]
 [0.48387097 0.61403509 0.         0.86666667 0.5275     0.0469    ]
 [0.4516129  0.73684211 0.         0.93333333 0.04833333 0.        ]]
(4646, 6)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.419355,0.947368,0.4,0.400000,0.567868,0.973233
37,0.483871,0.736842,0.5,0.466667,0.917463,0.849282
38,0.516129,0.596491,0.6,0.533333,0.686543,0.968586
39,0.580645,0.526316,0.5,0.600000,0.950000,1.000000
40,0.612903,0.543860,0.4,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
18281,0.580645,0.491228,0.4,0.666667,0.852067,0.846167
18282,0.580645,0.508772,0.2,0.733333,0.846200,0.755467
18283,0.548387,0.526316,0.1,0.800000,0.762400,0.524533
18284,0.483871,0.614035,0.0,0.866667,0.527500,0.046900
18285,0.451613,0.736842,0.0,0.933333,0.048333,0.000000

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.        ]
 [0.66776667]
 [0.65776667]]
(3252, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
36       0.917463
37       0.686543
38       0.950000
39       0.821586
40       0.850000
...           ...
12596    0.026400
12597    0.000000
12598    0.000000
12612    0.667767
12613    0.657767

[3252 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[6.34033333e-01]
 [6.36166667e-01]
 [6.55400000e-01]
 [7.37566667e-01]
 [5.70933333e-01]
 [3.33533333e-01]
 [2.61000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.70400000e-01]
 [6.63633333e-01]
 [6.37766667e-01]
 [6.27166667e-01]
 [6.26333333e-01]
 [6.40166667e-01]
 [6.02466667e-01]
 [3.65333333e-01]
 [3.65333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.34700000e-01]
 [8.30300000e-01]
 [7.99833333e-01]
 [7.87100000e-01]
 [7.82933333e-01]
 [8.26866667e-01]
 [7.83933333e-01]
 [4.66100000e-01]
 [4.78000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.34700000e-01]
 [8.40866667e-01]
 [8.04600000e-01]
 [7.83966667e-01]
 [7.82933333e-01]
 [8.25166667e-01]
 [7.76633333e-01]
 [4.66033333e-01]
 [6.56666667e-01]
 [6.38400000e-01]
 [6.27833333e-01]
 [6.29333333e-01]
 [6.26066667e-01]
 [6.02466667e-01]
 [3.65333333e-01]
 [3.47666667e-02]
 [6.34033333e-01]
 [6.27166667e-01]
 [6.33666667e-01]
 [6.26066667e-01]
 [6.02466667e-01]
 [3.65333333e-01]
 [3.28833333e-01]
 [3.33833333e-01]
 [3.16300000e-01]
 [7.93233333e-01]
 [8.00033333e-01]
 [7.86866667e-01]
 [4.59900000e-01]
 [8.20833333e-01]
 [8.02466667e-01]
 [7.83966667e-01]
 [8.05566667e-01]
 [8.13566667e-01]
 [7.97433333e-01]
 [4.59833333e-01]
 [4.69333333e-02]
 [0.00000000e+00]
 [8.12700000e-01]
 [7.91266667e-01]
 [7.82000000e-01]
 [7.75200000e-01]
 [7.80900000e-01]
 [7.62700000e-01]
 [4.56633333e-01]
 [4.81000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.41900000e-01]
 [8.29366667e-01]
 [7.92533333e-01]
 [7.83966667e-01]
 [7.89666667e-01]
 [7.82600000e-01]
 [7.68333333e-01]
 [4.66666667e-01]
 [4.67666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.11833333e-01]
 [7.55933333e-01]
 [7.38766667e-01]
 [7.13266667e-01]
 [7.10400000e-01]
 [7.04633333e-01]
 [7.07200000e-01]
 [6.77800000e-01]
 [3.80400000e-01]
 [4.24000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.30866667e-01]
 [6.64266667e-01]
 [6.49600000e-01]
 [7.98233333e-01]
 [7.92033333e-01]
 [7.82033333e-01]
 [8.03066667e-01]
 [6.93200000e-01]
 [4.26033333e-01]
 [6.04666667e-02]
 [6.34033333e-01]
 [6.27166667e-01]
 [7.04633333e-01]
 [6.26066667e-01]
 [6.77800000e-01]
 [4.34333333e-01]
 [4.24666667e-02]
 [8.34500000e-01]
 [7.88233333e-01]
 [7.85266667e-01]
 [7.53400000e-01]
 [4.82533333e-01]
 [5.28333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.85000000e-01]
 [6.68100000e-01]
 [6.40133333e-01]
 [6.29733333e-01]
 [6.02466667e-01]
 [3.92200000e-01]
 [4.24333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.51233333e-01]
 [6.59100000e-01]
 [7.16500000e-01]
 [7.84200000e-01]
 [7.82933333e-01]
 [7.85666667e-01]
 [6.77800000e-01]
 [4.21233333e-01]
 [3.88333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.74166667e-01]
 [6.92266667e-01]
 [6.70433333e-01]
 [6.43100000e-01]
 [6.45766667e-01]
 [6.42366667e-01]
 [6.47166667e-01]
 [6.39833333e-01]
 [4.34033333e-01]
 [6.20000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.17400000e-01]
 [8.18666667e-01]
 [6.90233333e-01]
 [4.11033333e-01]
 [4.34666667e-02]
 [0.00000000e+00]
 [8.95366667e-01]
 [8.77033333e-01]
 [8.45600000e-01]
 [8.54000000e-01]
 [8.59233333e-01]
 [8.16733333e-01]
 [6.04733333e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.96300000e-01]
 [8.99033333e-01]
 [9.30666667e-01]
 [9.73033333e-01]
 [9.93833333e-01]
 [8.74733333e-01]
 [5.55833333e-01]
 [3.56000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.48066667e-01]
 [9.48866667e-01]
 [9.88166667e-01]
 [9.31333333e-01]
 [8.76566667e-01]
 [8.45000000e-01]
 [7.41766667e-01]
 [5.00300000e-01]
 [3.33333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.00000000e+00]
 [9.96200000e-01]
 [1.00000000e+00]
 [9.83100000e-01]
 [9.71766667e-01]
 [9.95633333e-01]
 [8.73600000e-01]
 [5.62600000e-01]
 [4.62666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.89700000e-01]
 [8.95366667e-01]
 [8.77033333e-01]
 [8.61566667e-01]
 [8.45600000e-01]
 [8.54000000e-01]
 [8.67133333e-01]
 [8.29233333e-01]
 [6.04733333e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.01633333e-01]
 [6.87333333e-01]
 [6.86233333e-01]
 [7.82533333e-01]
 [7.05233333e-01]
 [6.93266667e-01]
 [5.18433333e-01]
 [9.64333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.16300000e-01]
 [7.10033333e-01]
 [6.79466667e-01]
 [6.84666667e-01]
 [6.92800000e-01]
 [6.66866667e-01]
 [4.91366667e-01]
 [9.59666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.61666667e-01]
 [8.47233333e-01]
 [8.92566667e-01]
 [8.91833333e-01]
 [8.84000000e-01]
 [8.81533333e-01]
 [8.92833333e-01]
 [8.93833333e-01]
 [8.53433333e-01]
 [5.14800000e-01]
 [5.18333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.03733333e-01]
 [6.26766667e-01]
 [7.09333333e-01]
 [7.83833333e-01]
 [6.76500000e-01]
 [6.85366667e-01]
 [6.87533333e-01]
 [6.60733333e-01]
 [4.83800000e-01]
 [9.24333333e-02]
 [0.00000000e+00]
 [6.76500000e-01]
 [6.89666667e-01]
 [7.04466667e-01]
 [6.53366667e-01]
 [4.85666667e-01]
 [5.99333333e-01]
 [6.08266667e-01]
 [6.53366667e-01]
 [4.23333333e-01]
 [9.31666667e-02]
 [8.27966667e-01]
 [8.54000000e-01]
 [7.82533333e-01]
 [7.58700000e-01]
 [5.93666667e-01]
 [1.34566667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.95366667e-01]
 [8.68233333e-01]
 [8.61400000e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.01333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.48333333e-01]
 [9.95633333e-01]
 [9.95933333e-01]
 [9.86300000e-01]
 [9.94966667e-01]
 [9.92933333e-01]
 [8.74533333e-01]
 [4.33266667e-01]
 [4.10333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79666667e-01]
 [8.95366667e-01]
 [6.92400000e-01]
 [6.88233333e-01]
 [7.55933333e-01]
 [4.88400000e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79666667e-01]
 [8.98466667e-01]
 [6.89233333e-01]
 [6.07833333e-01]
 [4.00200000e-01]
 [3.87033333e-01]
 [9.06333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.98300000e-01]
 [8.66466667e-01]
 [8.47600000e-01]
 [6.41966667e-01]
 [4.83833333e-01]
 [9.58000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.62066667e-01]
 [8.68733333e-01]
 [8.07700000e-01]
 [5.96633333e-01]
 [6.85733333e-01]
 [6.81133333e-01]
 [7.68600000e-01]
 [9.80400000e-01]
 [9.75433333e-01]
 [9.28733333e-01]
 [9.71900000e-01]
 [9.31933333e-01]
 [5.67633333e-01]
 [6.32233333e-01]
 [8.27033333e-01]
 [6.72166667e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.40666667e-01]
 [9.62433333e-01]
 [9.33600000e-01]
 [8.93933333e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.34900000e-01]
 [2.00000000e-04]
 [0.00000000e+00]
 [9.28266667e-01]
 [9.40400000e-01]
 [9.32766667e-01]
 [9.17500000e-01]
 [8.86200000e-01]
 [6.76433333e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.41633333e-01]
 [7.15233333e-01]
 [8.17833333e-01]
 [8.14000000e-01]
 [5.41133333e-01]
 [9.63333333e-02]
 [7.49966667e-01]
 [7.56900000e-01]
 [7.67166667e-01]
 [7.36500000e-01]
 [7.29200000e-01]
 [6.37000000e-01]
 [7.18033333e-01]
 [5.17733333e-01]
 [1.03866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.66666667e-04]
 [5.93533333e-01]
 [7.68333333e-01]
 [9.49966667e-01]
 [9.51900000e-01]
 [9.51733333e-01]
 [9.75366667e-01]
 [9.35800000e-01]
 [9.04766667e-01]
 [9.29900000e-01]
 [9.22133333e-01]
 [6.47666667e-01]
 [1.32900000e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [7.42033333e-01]
 [9.55433333e-01]
 [8.95366667e-01]
 [9.50333333e-01]
 [8.83566667e-01]
 [8.60766667e-01]
 [8.27766667e-01]
 [6.04733333e-01]
 [1.28500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.12766667e-01]
 [8.79666667e-01]
 [9.16966667e-01]
 [8.54000000e-01]
 [9.44766667e-01]
 [9.41966667e-01]
 [6.38733333e-01]
 [1.34233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79966667e-01]
 [8.59233333e-01]
 [8.16733333e-01]
 [6.04733333e-01]
 [8.61933333e-01]
 [8.16733333e-01]
 [6.57833333e-01]
 [1.33966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.86333333e-01]
 [9.03966667e-01]
 [7.73300000e-01]
 [7.45766667e-01]
 [5.59166667e-01]
 [9.18666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [4.93366667e-01]
 [7.06200000e-01]
 [7.16300000e-01]
 [6.87366667e-01]
 [6.82566667e-01]
 [4.99900000e-01]
 [9.83666667e-02]
 [6.66666667e-05]
 [0.00000000e+00]
 [6.55566667e-01]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.41066667e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.67033333e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38166667e-01]
 [9.25733333e-01]
 [9.19733333e-01]
 [8.77900000e-01]
 [7.23600000e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.45666667e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.77900000e-01]
 [7.15266667e-01]
 [2.00866667e-01]
 [1.60000000e-03]
 [9.43833333e-01]
 [9.43233333e-01]
 [9.32266667e-01]
 [9.13333333e-01]
 [8.77900000e-01]
 [7.08766667e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.95466667e-01]
 [9.69366667e-01]
 [9.55300000e-01]
 [8.80333333e-01]
 [5.72166667e-01]
 [1.18833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.40600000e-01]
 [8.18700000e-01]
 [7.90133333e-01]
 [5.67033333e-01]
 [1.55000000e-01]
 [1.23333333e-03]
 [0.00000000e+00]
 [6.55566667e-01]
 [7.40466667e-01]
 [7.53133333e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.72700000e-01]
 [1.58866667e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [6.36766667e-01]
 [6.19600000e-01]
 [5.03100000e-01]
 [1.43233333e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [3.42366667e-01]
 [8.34100000e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.19733333e-01]
 [8.85233333e-01]
 [7.12900000e-01]
 [1.93533333e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [3.80700000e-01]
 [8.66833333e-01]
 [9.74500000e-01]
 [9.95466667e-01]
 [9.61066667e-01]
 [8.29166667e-01]
 [5.44333333e-01]
 [1.08133333e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [9.25600000e-01]
 [9.35966667e-01]
 [7.27733333e-01]
 [7.90133333e-01]
 [6.37900000e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [7.48566667e-01]
 [7.49766667e-01]
 [7.52966667e-01]
 [7.50966667e-01]
 [6.56566667e-01]
 [6.55966667e-01]
 [6.14533333e-01]
 [5.72466667e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [9.35966667e-01]
 [8.42266667e-01]
 [7.42566667e-01]
 [9.28733333e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.85233333e-01]
 [6.39533333e-01]
 [1.65300000e-01]
 [1.73333333e-03]
 [0.00000000e+00]
 [7.48766667e-01]
 [7.55500000e-01]
 [7.48433333e-01]
 [8.33766667e-01]
 [7.43200000e-01]
 [8.18700000e-01]
 [7.98633333e-01]
 [6.37900000e-01]
 [2.08033333e-01]
 [1.76666667e-03]
 [0.00000000e+00]
 [9.35966667e-01]
 [9.35866667e-01]
 [9.30333333e-01]
 [9.34100000e-01]
 [9.35533333e-01]
 [5.46000000e-01]
 [5.34800000e-01]
 [4.25333333e-01]
 [1.48633333e-01]
 [1.56666667e-03]
 [0.00000000e+00]
 [7.64600000e-01]
 [7.68100000e-01]
 [7.65933333e-01]
 [7.58566667e-01]
 [7.55666667e-01]
 [6.59333333e-01]
 [7.54133333e-01]
 [7.20366667e-01]
 [6.26533333e-01]
 [1.58300000e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [7.50133333e-01]
 [7.21133333e-01]
 [5.39600000e-01]
 [1.97433333e-01]
 [2.83333333e-03]
 [0.00000000e+00]
 [7.48133333e-01]
 [7.17766667e-01]
 [6.09200000e-01]
 [1.62733333e-01]
 [3.23333333e-03]
 [0.00000000e+00]
 [9.12066667e-01]
 [8.52033333e-01]
 [5.46600000e-01]
 [7.90333333e-02]
 [0.00000000e+00]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.73033333e-01]
 [2.57900000e-01]
 [3.46666667e-03]
 [0.00000000e+00]
 [8.43900000e-01]
 [8.10266667e-01]
 [6.97233333e-01]
 [2.65466667e-01]
 [9.37666667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.74700000e-01]
 [2.49433333e-01]
 [2.73333333e-03]
 [8.40366667e-01]
 [7.17966667e-01]
 [6.85333333e-01]
 [2.01966667e-01]
 [3.80000000e-03]
 [0.00000000e+00]
 [9.84933333e-01]
 [9.31033333e-01]
 [7.18566667e-01]
 [1.62233333e-01]
 [2.66666667e-04]
 [0.00000000e+00]
 [7.57933333e-01]
 [9.64766667e-01]
 [9.63200000e-01]
 [9.37400000e-01]
 [9.37700000e-01]
 [9.21500000e-01]
 [8.86033333e-01]
 [7.33966667e-01]
 [2.35400000e-01]
 [6.50000000e-03]
 [0.00000000e+00]
 [4.26866667e-01]
 [8.85433333e-01]
 [9.77866667e-01]
 [9.36966667e-01]
 [9.04700000e-01]
 [7.61466667e-01]
 [2.68533333e-01]
 [4.10000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.40333333e-02]
 [4.63500000e-01]
 [8.89200000e-01]
 [9.82566667e-01]
 [9.59700000e-01]
 [9.41300000e-01]
 [9.06166667e-01]
 [7.84833333e-01]
 [2.75000000e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [9.40866667e-01]
 [9.07500000e-01]
 [7.73100000e-01]
 [2.98533333e-01]
 [2.60000000e-03]
 [0.00000000e+00]
 [7.50133333e-01]
 [7.21133333e-01]
 [6.09200000e-01]
 [2.20066667e-01]
 [4.03333333e-03]
 [0.00000000e+00]
 [9.42933333e-01]
 [9.18133333e-01]
 [8.82033333e-01]
 [7.18600000e-01]
 [2.73700000e-01]
 [9.46666667e-03]
 [0.00000000e+00]
 [3.75833333e-01]
 [7.45533333e-01]
 [7.42033333e-01]
 [8.33833333e-01]]
(697, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
12614    0.634033
12615    0.636167
12616    0.655400
12617    0.737567
12618    0.570933
...           ...
14590    0.000000
14601    0.375833
14602    0.745533
14603    0.742033
14608    0.833833

[697 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.72056667]
 [0.67996667]
 [0.5749    ]
 [0.21896667]
 [0.00756667]
 [0.        ]
 [0.81536667]
 [0.90996667]
 [0.80986667]
 [0.76953333]
 [0.5749    ]
 [0.22023333]
 [0.0078    ]
 [0.        ]
 [0.81026667]
 [0.76496667]
 [0.7186    ]
 [0.2851    ]
 [0.0097    ]
 [0.        ]
 [0.80986667]
 [0.8513    ]
 [0.7186    ]
 [0.2862    ]
 [0.01033333]
 [0.        ]
 [0.83926667]
 [0.72      ]
 [0.68456667]
 [0.5749    ]
 [0.2982    ]
 [0.0105    ]
 [0.        ]
 [0.        ]
 [0.05056667]
 [0.39346667]
 [0.6523    ]
 [0.72796667]
 [0.74653333]
 [0.75363333]
 [0.7465    ]
 [0.7461    ]
 [0.7414    ]
 [0.72333333]
 [0.6804    ]
 [0.57563333]
 [0.22806667]
 [0.00756667]
 [0.        ]
 [0.57076667]
 [0.71923333]
 [0.74653333]
 [0.66036667]
 [0.65023333]
 [0.7461    ]
 [0.74116667]
 [0.6299    ]
 [0.59496667]
 [0.58286667]
 [0.22686667]
 [0.00763333]
 [0.        ]
 [0.4228    ]
 [0.6523    ]
 [0.8983    ]
 [0.6337    ]
 [0.51133333]
 [0.64676667]
 [0.24633333]
 [0.00973333]
 [0.        ]
 [0.81536667]
 [0.9052    ]
 [0.93603333]
 [0.83383333]
 [0.80986667]
 [0.8728    ]
 [0.75536667]
 [0.30716667]
 [0.00893333]
 [0.        ]
 [0.85713333]
 [0.9203    ]
 [0.92646667]
 [0.89986667]
 [0.76496667]
 [0.51163333]
 [0.1642    ]
 [0.0063    ]
 [0.        ]
 [0.83173333]
 [0.6299    ]
 [0.51      ]
 [0.50793333]
 [0.21896667]
 [0.00963333]
 [0.        ]
 [0.48836667]
 [0.8665    ]
 [0.9173    ]
 [0.89986667]
 [0.84996667]
 [0.732     ]
 [0.24633333]
 [0.0115    ]
 [0.        ]
 [0.81536667]
 [0.90996667]
 [0.76186667]
 [0.91093333]
 [0.69393333]
 [0.24933333]
 [0.009     ]
 [0.        ]
 [0.80986667]
 [0.84996667]
 [0.5749    ]
 [0.21896667]
 [0.00756667]
 [0.        ]
 [0.69496667]
 [0.7502    ]
 [0.85563333]
 [0.90473333]
 [0.79736667]
 [0.2799    ]
 [0.00856667]
 [0.        ]
 [0.        ]
 [0.0565    ]
 [0.48006667]
 [0.81946667]
 [0.92343333]
 [0.74293333]
 [0.73216667]
 [0.59493333]
 [0.21896667]
 [0.00806667]
 [0.        ]
 [0.95383333]
 [0.85996667]
 [0.72946667]
 [0.2737    ]
 [0.00983333]
 [0.        ]
 [0.95473333]
 [0.8543    ]
 [0.71996667]
 [0.2737    ]
 [0.0095    ]
 [0.        ]
 [0.95686667]
 [0.85466667]
 [0.72766667]
 [0.2827    ]
 [0.01016667]
 [0.        ]
 [0.7583    ]
 [0.73773333]
 [0.64983333]
 [0.32096667]
 [0.0174    ]
 [0.        ]
 [0.89986667]
 [0.85396667]
 [0.72283333]
 [0.2737    ]
 [0.02876667]
 [0.        ]
 [0.89986667]
 [0.85796667]
 [0.7186    ]
 [0.2737    ]
 [0.01706667]
 [0.        ]
 [0.80986667]
 [0.7725    ]
 [0.64676667]
 [0.24756667]
 [0.01043333]
 [0.        ]
 [0.93453333]
 [0.72763333]
 [0.77396667]
 [0.64676667]
 [0.2829    ]
 [0.0191    ]
 [0.        ]
 [0.93103333]
 [0.9082    ]
 [0.8592    ]
 [0.72476667]
 [0.28226667]
 [0.01946667]
 [0.        ]
 [0.9348    ]
 [0.72953333]
 [0.69536667]
 [0.57733333]
 [0.22626667]
 [0.01726667]
 [0.        ]
 [0.8389    ]
 [0.9059    ]
 [0.80986667]
 [0.67996667]
 [0.50303333]
 [0.11496667]
 [0.00816667]
 [0.        ]
 [0.94036667]
 [0.85836667]
 [0.79713333]
 [0.3988    ]
 [0.02593333]
 [0.        ]
 [0.95703333]
 [0.8807    ]
 [0.82156667]
 [0.3956    ]
 [0.02733333]
 [0.        ]
 [0.94446667]
 [0.89293333]
 [0.768     ]
 [0.34953333]
 [0.02876667]
 [0.        ]
 [0.8208    ]
 [0.78856667]
 [0.68943333]
 [0.35676667]
 [0.0301    ]
 [0.        ]
 [0.85126667]
 [0.78006667]
 [0.69566667]
 [0.35676667]
 [0.0335    ]
 [0.        ]
 [0.8673    ]
 [0.94856667]
 [0.9458    ]
 [0.7962    ]
 [0.73963333]
 [0.37316667]
 [0.02813333]
 [0.        ]
 [0.84413333]
 [0.91103333]
 [0.7296    ]
 [0.80933333]
 [0.78803333]
 [0.40506667]
 [0.03346667]
 [0.        ]
 [0.8243    ]
 [0.91103333]
 [0.9241    ]
 [0.86676667]
 [0.76606667]
 [0.42396667]
 [0.0338    ]
 [0.        ]
 [0.8237    ]
 [0.91103333]
 [0.91926667]
 [0.86676667]
 [0.6952    ]
 [0.37006667]
 [0.03346667]
 [0.        ]
 [0.8208    ]
 [0.70683333]
 [0.55156667]
 [0.38056667]
 [0.03136667]
 [0.        ]
 [0.7531    ]
 [0.818     ]
 [0.74176667]
 [0.3495    ]
 [0.02446667]
 [0.        ]
 [0.9354    ]
 [0.9109    ]
 [0.82416667]
 [0.45596667]
 [0.0394    ]
 [0.        ]
 [0.94076667]
 [0.9109    ]
 [0.82416667]
 [0.46683333]
 [0.0379    ]
 [0.        ]
 [0.92876667]
 [0.89913333]
 [0.6494    ]
 [0.35516667]
 [0.04673333]
 [0.        ]
 [0.9193    ]
 [0.785     ]
 [0.7128    ]
 [0.32696667]
 [0.044     ]
 [0.        ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.40376667]
 [0.0505    ]
 [0.        ]
 [0.9074    ]
 [0.68956667]
 [0.6108    ]
 [0.37246667]
 [0.04123333]
 [0.        ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.39786667]
 [0.03346667]
 [0.        ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.404     ]
 [0.03453333]
 [0.        ]
 [0.912     ]
 [0.86706667]
 [0.77026667]
 [0.41783333]
 [0.03356667]
 [0.        ]
 [0.912     ]
 [0.86676667]
 [0.77336667]
 [0.3964    ]
 [0.03346667]
 [0.        ]
 [0.90956667]
 [0.94046667]
 [0.9214    ]
 [0.85693333]
 [0.6903    ]
 [0.6948    ]
 [0.3181    ]
 [0.02866667]
 [0.59166667]
 [0.5925    ]
 [0.58783333]
 [0.912     ]
 [0.78006667]
 [0.6946    ]
 [0.9314    ]
 [0.8848    ]
 [0.7935    ]
 [0.42906667]
 [0.9233    ]
 [0.90183333]
 [0.81353333]
 [0.912     ]
 [0.86676667]
 [0.70006667]
 [0.4085    ]
 [0.912     ]
 [0.62406667]
 [0.86446667]
 [0.77156667]
 [0.8989    ]
 [0.86173333]
 [0.77603333]
 [0.90476667]
 [0.86173333]
 [0.7702    ]
 [0.36326667]
 [0.444     ]
 [0.42223333]
 [0.69733333]
 [0.39323333]
 [0.03236667]
 [0.3083    ]
 [0.336     ]
 [0.32383333]
 [0.19636667]
 [0.0184    ]
 [0.85893333]
 [0.80036667]
 [0.7702    ]
 [0.32726667]
 [0.03023333]
 [0.85996667]
 [0.80066667]
 [0.7702    ]
 [0.42076667]
 [0.03893333]
 [0.90623333]
 [0.86173333]
 [0.77143333]
 [0.35383333]
 [0.04793333]
 [0.7987    ]
 [0.74013333]
 [0.6512    ]
 [0.55643333]
 [0.2518    ]
 [0.4346    ]
 [0.3771    ]
 [0.34846667]
 [0.3632    ]
 [0.37996667]
 [0.34693333]
 [0.20373333]
 [0.38693333]
 [0.36546667]
 [0.3293    ]
 [0.24296667]
 [0.39356667]
 [0.58406667]
 [0.89363333]
 [0.79943333]
 [0.80903333]
 [0.78476667]
 [0.70753333]
 [0.39843333]
 [0.8989    ]
 [0.8784    ]
 [0.77786667]
 [0.8989    ]
 [0.87786667]
 [0.7854    ]
 [0.57636667]
 [0.4958    ]
 [0.3774    ]
 [0.5035    ]
 [0.62146667]
 [0.65876667]
 [0.63633333]
 [0.5772    ]
 [0.5515    ]
 [0.49453333]
 [0.31843333]
 [0.9155    ]
 [0.89793333]
 [0.7702    ]
 [0.82336667]
 [0.86173333]
 [0.79553333]
 [0.37243333]
 [0.9099    ]
 [0.865     ]
 [0.69463333]
 [0.2981    ]
 [0.78643333]
 [0.69196667]
 [0.63806667]
 [0.3462    ]
 [0.9093    ]
 [0.87486667]
 [0.78106667]
 [0.38866667]
 [0.02246667]
 [0.9121    ]
 [0.86623333]
 [0.78116667]
 [0.39193333]
 [0.02276667]
 [0.8249    ]
 [0.78143333]
 [0.69826667]
 [0.39193333]
 [0.88623333]
 [0.87336667]
 [0.8009    ]
 [0.3411    ]
 [0.01933333]
 [0.        ]
 [0.81956667]
 [0.8202    ]
 [0.8783    ]
 [0.80133333]
 [0.36993333]
 [0.0213    ]
 [0.        ]
 [0.87806667]
 [0.85183333]
 [0.71376667]
 [0.30506667]
 [0.0167    ]
 [0.87826667]
 [0.76673333]
 [0.67466667]
 [0.28106667]
 [0.87786667]
 [0.74743333]
 [0.44653333]
 [0.1602    ]
 [0.88676667]
 [0.83873333]
 [0.64      ]
 [0.22886667]
 [0.87896667]
 [0.83016667]
 [0.64546667]
 [0.90576667]
 [0.9074    ]
 [0.89053333]
 [0.71376667]
 [0.90826667]
 [0.73996667]
 [0.60356667]
 [0.35273333]
 [0.78376667]
 [0.74533333]
 [0.59436667]
 [0.7099    ]
 [0.73996667]
 [0.57583333]
 [0.92463333]
 [0.94343333]
 [0.92596667]
 [0.89053333]
 [0.6747    ]
 [0.9326    ]
 [0.92056667]
 [0.9436    ]
 [0.66456667]
 [0.5003    ]
 [0.6026    ]
 [0.27746667]
 [0.73483333]
 [0.75106667]
 [0.74076667]
 [0.70643333]
 [0.55113333]
 [0.24633333]
 [0.7242    ]
 [0.69666667]
 [0.66436667]
 [0.51526667]
 [0.18306667]
 [0.832     ]
 [0.8181    ]
 [0.60666667]
 [0.71483333]
 [0.7251    ]
 [0.5234    ]
 [0.12676667]
 [0.8959    ]
 [0.87016667]
 [0.72956667]
 [0.27533333]
 [0.74076667]
 [0.71673333]
 [0.59863333]
 [0.18846667]
 [0.92596667]
 [0.8974    ]
 [0.76766667]
 [0.20596667]
 [0.00503333]
 [0.92596667]
 [0.88663333]
 [0.75743333]
 [0.23426667]
 [0.90243333]
 [0.87916667]
 [0.57983333]
 [0.21093333]
 [0.91026667]
 [0.7636    ]
 [0.6073    ]
 [0.18306667]
 [0.87976667]
 [0.8222    ]
 [0.6484    ]
 [0.22886667]
 [0.49086667]
 [0.59793333]
 [0.5747    ]
 [0.20596667]
 [0.58003333]
 [0.55733333]
 [0.40286667]
 [0.4381    ]
 [0.35406667]
 [0.1929    ]
 [0.01676667]
 [0.08046667]
 [0.07586667]
 [0.0574    ]
 [0.5007    ]
 [0.53933333]
 [0.2123    ]
 [0.26853333]
 [0.31293333]
 [0.50653333]
 [0.56166667]
 [0.8941    ]
 [0.8       ]
 [0.64013333]
 [0.71526667]
 [0.71113333]
 [0.70473333]
 [0.1301    ]
 [0.8941    ]
 [0.89443333]
 [0.71126667]
 [0.1301    ]
 [0.9238    ]
 [0.9137    ]
 [0.90866667]
 [0.87236667]
 [0.62396667]
 [0.1301    ]
 [0.8941    ]
 [0.84303333]
 [0.8987    ]
 [0.71526667]
 [0.53956667]
 [0.80966667]
 [0.57223333]
 [0.80633333]
 [0.80466667]
 [0.53956667]
 [0.4996    ]
 [0.87446667]
 [0.8313    ]
 [0.906     ]
 [0.87833333]
 [0.6069    ]
 [0.906     ]
 [0.87833333]
 [0.59856667]
 [0.88786667]
 [0.86076667]
 [0.5905    ]
 [0.07903333]
 [0.85373333]
 [0.7758    ]
 [0.59476667]
 [0.07676667]
 [0.7854    ]
 [0.63586667]
 [0.46996667]
 [0.78563333]
 [0.71536667]
 [0.52683333]
 [0.8509    ]
 [0.77896667]
 [0.53383333]
 [0.05713333]
 [0.84476667]
 [0.69613333]
 [0.46423333]
 [0.62646667]
 [0.7777    ]
 [0.72793333]
 [0.5151    ]
 [0.85193333]
 [0.84953333]
 [0.8389    ]
 [0.84076667]
 [0.61913333]
 [0.79653333]
 [0.85433333]
 [0.85406667]
 [0.842     ]
 [0.84313333]
 [0.76006667]
 [0.47626667]
 [0.84993333]
 [0.85183333]
 [0.84156667]
 [0.84376667]
 [0.75776667]
 [0.52603333]
 [0.04826667]
 [0.8391    ]
 [0.76006667]
 [0.52973333]
 [0.04583333]
 [0.8481    ]
 [0.84616667]
 [0.75546667]
 [0.52453333]
 [0.0469    ]
 [0.85206667]
 [0.8462    ]
 [0.7624    ]
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(697, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
14609    0.720567
14610    0.679967
14611    0.574900
14612    0.218967
14613    0.007567
...           ...
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000

[697 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(4646, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
36       0.917463
37       0.686543
38       0.950000
39       0.821586
40       0.850000
...           ...
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000

[4646 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.051028 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 620
[LightGBM] [Info] Number of data points in the train set: 3252, number of used features: 6
[LightGBM] [Info] Start training from score 0.515719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
14609  24312.477855
14610  21363.704588
14611  16662.192043
14612   6329.374684
14613    374.941399
...             ...
18281  26751.870947
18282   23370.96659
18283  15084.108971
18284   1894.938407
18285           0.0

[697 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
14609     21617.0
14610     20399.0
14611     17247.0
14612      6569.0
14613       227.0
...           ...
18281     25386.0
18282     22872.0
18283     15825.0
18284      1450.0
18285         0.0

[697 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
14609     21617.0  24312.477855
14610     20399.0  21363.704588
14611     17247.0  16662.192043
14612      6569.0   6329.374684
14613       227.0    374.941399
...           ...           ...
18281     25386.0  26751.870947
18282     22872.0   23370.96659
18283     15825.0  15084.108971
18284      1450.0   1894.938407
18285         0.0           0.0

[697 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1504.7843
RMSE: 2382.9166
R²: 0.9394

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
14609     21617.0  24312.477855  25032.668096
14610     20399.0  21363.704588  20701.133338
14611     17247.0  16662.192043  15987.507201
14612      6569.0   6329.374684   7427.492492
14613       227.0    374.941399       349.495
...           ...           ...           ...
18281     25386.0  26751.870947  26019.654367
18282     22872.0   23370.96659  22637.749887
18283     15825.0  15084.108971  16064.234452
18284      1450.0   1894.938407   2119.455433
18285         0.0           0.0      0.077852

[697 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (3204, 48, 6), y_train: (3204, 1)
X_val: (649, 48, 6), y_val: (649, 1)
X_test: (649, 48, 6), y_test: (649, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 153s 4s/step - loss: 0.3892 - mean_absolute_error: 0.5067 - mean_absolute_percentage_error: 186859.7031 - root_mean_squared_error: 0.6238 - val_loss: 0.3786 - val_mean_absolute_error: 0.5311 - val_mean_absolute_percentage_error: 793283.3125 - val_root_mean_squared_error: 0.6153
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 44s 4s/step - loss: 0.3854 - mean_absolute_error: 0.5066 - mean_absolute_percentage_error: 1175555.0000 - root_mean_squared_error: 0.6207 - val_loss: 0.3702 - val_mean_absolute_error: 0.5254 - val_mean_absolute_percentage_error: 1703847.7500 - val_root_mean_squared_error: 0.6084
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - loss: 0.3713 - mean_absolute_error: 0.4960 - mean_absolute_percentage_error: 2362575.7500 - root_mean_squared_error: 0.6093 - val_loss: 0.3607 - val_mean_absolute_error: 0.5189 - val_mean_absolute_percentage_error: 2747888.7500 - val_root_mean_squared_error: 0.6006
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 31s 4s/step - loss: 0.3656 - mean_absolute_error: 0.4945 - mean_absolute_percentage_error: 3676168.7500 - root_mean_squared_error: 0.6046 - val_loss: 0.3497 - val_mean_absolute_error: 0.5113 - val_mean_absolute_percentage_error: 3982023.0000 - val_root_mean_squared_error: 0.5914
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 3s/step - loss: 0.3537 - mean_absolute_error: 0.4850 - mean_absolute_percentage_error: 5404997.0000 - root_mean_squared_error: 0.5947 - val_loss: 0.3359 - val_mean_absolute_error: 0.5021 - val_mean_absolute_percentage_error: 5567852.5000 - val_root_mean_squared_error: 0.5796
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.3368 - mean_absolute_error: 0.4732 - mean_absolute_percentage_error: 7335006.0000 - root_mean_squared_error: 0.5803 - val_loss: 0.3192 - val_mean_absolute_error: 0.4904 - val_mean_absolute_percentage_error: 7563660.0000 - val_root_mean_squared_error: 0.5650
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.3293 - mean_absolute_error: 0.4715 - mean_absolute_percentage_error: 10194807.0000 - root_mean_squared_error: 0.5738 - val_loss: 0.2990 - val_mean_absolute_error: 0.4758 - val_mean_absolute_percentage_error: 10072943.0000 - val_root_mean_squared_error: 0.5468
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.2948 - mean_absolute_error: 0.4443 - mean_absolute_percentage_error: 13206629.0000 - root_mean_squared_error: 0.5429 - val_loss: 0.2748 - val_mean_absolute_error: 0.4576 - val_mean_absolute_percentage_error: 13238318.0000 - val_root_mean_squared_error: 0.5242
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 26s 3s/step - loss: 0.2753 - mean_absolute_error: 0.4318 - mean_absolute_percentage_error: 17839316.0000 - root_mean_squared_error: 0.5246 - val_loss: 0.2458 - val_mean_absolute_error: 0.4354 - val_mean_absolute_percentage_error: 17342476.0000 - val_root_mean_squared_error: 0.4958
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.2576 - mean_absolute_error: 0.4245 - mean_absolute_percentage_error: 22500726.0000 - root_mean_squared_error: 0.5075 - val_loss: 0.2126 - val_mean_absolute_error: 0.4086 - val_mean_absolute_percentage_error: 22588194.0000 - val_root_mean_squared_error: 0.4611
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 33s 4s/step - loss: 0.2227 - mean_absolute_error: 0.3972 - mean_absolute_percentage_error: 28222246.0000 - root_mean_squared_error: 0.4719 - val_loss: 0.1785 - val_mean_absolute_error: 0.3779 - val_mean_absolute_percentage_error: 28838700.0000 - val_root_mean_squared_error: 0.4225
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 3s/step - loss: 0.1905 - mean_absolute_error: 0.3739 - mean_absolute_percentage_error: 37436192.0000 - root_mean_squared_error: 0.4364 - val_loss: 0.1479 - val_mean_absolute_error: 0.3457 - val_mean_absolute_percentage_error: 35747088.0000 - val_root_mean_squared_error: 0.3845
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 15s 2s/step - loss: 0.1682 - mean_absolute_error: 0.3573 - mean_absolute_percentage_error: 46677124.0000 - root_mean_squared_error: 0.4102 - val_loss: 0.1219 - val_mean_absolute_error: 0.3118 - val_mean_absolute_percentage_error: 43618660.0000 - val_root_mean_squared_error: 0.3492
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 32s 3s/step - loss: 0.1517 - mean_absolute_error: 0.3466 - mean_absolute_percentage_error: 56127224.0000 - root_mean_squared_error: 0.3894 - val_loss: 0.1050 - val_mean_absolute_error: 0.2807 - val_mean_absolute_percentage_error: 51822808.0000 - val_root_mean_squared_error: 0.3241
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 18s 2s/step - loss: 0.1407 - mean_absolute_error: 0.3360 - mean_absolute_percentage_error: 61751144.0000 - root_mean_squared_error: 0.3752 - val_loss: 0.0995 - val_mean_absolute_error: 0.2658 - val_mean_absolute_percentage_error: 57288396.0000 - val_root_mean_squared_error: 0.3155
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 28s 3s/step - loss: 0.1422 - mean_absolute_error: 0.3372 - mean_absolute_percentage_error: 75329040.0000 - root_mean_squared_error: 0.3770 - val_loss: 0.0987 - val_mean_absolute_error: 0.2619 - val_mean_absolute_percentage_error: 59011608.0000 - val_root_mean_squared_error: 0.3142
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - loss: 0.1437 - mean_absolute_error: 0.3375 - mean_absolute_percentage_error: 75088376.0000 - root_mean_squared_error: 0.3790 - val_loss: 0.0985 - val_mean_absolute_error: 0.2598 - val_mean_absolute_percentage_error: 59958128.0000 - val_root_mean_squared_error: 0.3138
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.1414 - mean_absolute_error: 0.3335 - mean_absolute_percentage_error: 70960656.0000 - root_mean_squared_error: 0.3760 - val_loss: 0.0985 - val_mean_absolute_error: 0.2609 - val_mean_absolute_percentage_error: 59467944.0000 - val_root_mean_squared_error: 0.3139
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 15s 2s/step - loss: 0.1402 - mean_absolute_error: 0.3335 - mean_absolute_percentage_error: 74849648.0000 - root_mean_squared_error: 0.3744 - val_loss: 0.0988 - val_mean_absolute_error: 0.2633 - val_mean_absolute_percentage_error: 58370492.0000 - val_root_mean_squared_error: 0.3144
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 27s 3s/step - loss: 0.1395 - mean_absolute_error: 0.3348 - mean_absolute_percentage_error: 68960608.0000 - root_mean_squared_error: 0.3735 - val_loss: 0.1009 - val_mean_absolute_error: 0.2709 - val_mean_absolute_percentage_error: 55206292.0000 - val_root_mean_squared_error: 0.3176
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 27s 4s/step - loss: 0.1389 - mean_absolute_error: 0.3342 - mean_absolute_percentage_error: 68875928.0000 - root_mean_squared_error: 0.3727 - val_loss: 0.1026 - val_mean_absolute_error: 0.2756 - val_mean_absolute_percentage_error: 53520688.0000 - val_root_mean_squared_error: 0.3203
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 39s 2s/step - loss: 0.1406 - mean_absolute_error: 0.3365 - mean_absolute_percentage_error: 66222344.0000 - root_mean_squared_error: 0.3750 - val_loss: 0.1014 - val_mean_absolute_error: 0.2724 - val_mean_absolute_percentage_error: 54635540.0000 - val_root_mean_squared_error: 0.3184
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.1386 - mean_absolute_error: 0.3343 - mean_absolute_percentage_error: 67149064.0000 - root_mean_squared_error: 0.3723 - val_loss: 0.0994 - val_mean_absolute_error: 0.2665 - val_mean_absolute_percentage_error: 56997672.0000 - val_root_mean_squared_error: 0.3153
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 32s 4s/step - loss: 0.1351 - mean_absolute_error: 0.3285 - mean_absolute_percentage_error: 68006648.0000 - root_mean_squared_error: 0.3675 - val_loss: 0.0983 - val_mean_absolute_error: 0.2608 - val_mean_absolute_percentage_error: 59505756.0000 - val_root_mean_squared_error: 0.3136
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - loss: 0.1378 - mean_absolute_error: 0.3303 - mean_absolute_percentage_error: 69970024.0000 - root_mean_squared_error: 0.3712 - val_loss: 0.0981 - val_mean_absolute_error: 0.2567 - val_mean_absolute_percentage_error: 61464408.0000 - val_root_mean_squared_error: 0.3132
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.1411 - mean_absolute_error: 0.3318 - mean_absolute_percentage_error: 71993296.0000 - root_mean_squared_error: 0.3755 - val_loss: 0.0983 - val_mean_absolute_error: 0.2542 - val_mean_absolute_percentage_error: 62877576.0000 - val_root_mean_squared_error: 0.3135
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 35s 4s/step - loss: 0.1417 - mean_absolute_error: 0.3319 - mean_absolute_percentage_error: 76497288.0000 - root_mean_squared_error: 0.3765 - val_loss: 0.0980 - val_mean_absolute_error: 0.2565 - val_mean_absolute_percentage_error: 61569672.0000 - val_root_mean_squared_error: 0.3131
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - loss: 0.1435 - mean_absolute_error: 0.3365 - mean_absolute_percentage_error: 77728688.0000 - root_mean_squared_error: 0.3789 - val_loss: 0.0980 - val_mean_absolute_error: 0.2595 - val_mean_absolute_percentage_error: 60105616.0000 - val_root_mean_squared_error: 0.3131
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1378 - mean_absolute_error: 0.3303 - mean_absolute_percentage_error: 70248840.0000 - root_mean_squared_error: 0.3712 - val_loss: 0.0997 - val_mean_absolute_error: 0.2682 - val_mean_absolute_percentage_error: 56312000.0000 - val_root_mean_squared_error: 0.3157
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 38s 5s/step - loss: 0.1379 - mean_absolute_error: 0.3314 - mean_absolute_percentage_error: 63708968.0000 - root_mean_squared_error: 0.3713 - val_loss: 0.1025 - val_mean_absolute_error: 0.2765 - val_mean_absolute_percentage_error: 53325784.0000 - val_root_mean_squared_error: 0.3202
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 26s 2s/step - loss: 0.1372 - mean_absolute_error: 0.3309 - mean_absolute_percentage_error: 63890572.0000 - root_mean_squared_error: 0.3704 - val_loss: 0.1012 - val_mean_absolute_error: 0.2731 - val_mean_absolute_percentage_error: 54442260.0000 - val_root_mean_squared_error: 0.3181
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.1357 - mean_absolute_error: 0.3283 - mean_absolute_percentage_error: 62892008.0000 - root_mean_squared_error: 0.3684 - val_loss: 0.0989 - val_mean_absolute_error: 0.2661 - val_mean_absolute_percentage_error: 57177988.0000 - val_root_mean_squared_error: 0.3145
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 23s 4s/step - loss: 0.1320 - mean_absolute_error: 0.3216 - mean_absolute_percentage_error: 65583960.0000 - root_mean_squared_error: 0.3633 - val_loss: 0.0982 - val_mean_absolute_error: 0.2631 - val_mean_absolute_percentage_error: 58567476.0000 - val_root_mean_squared_error: 0.3134
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 2s/step - loss: 0.1306 - mean_absolute_error: 0.3185 - mean_absolute_percentage_error: 70421704.0000 - root_mean_squared_error: 0.3614 - val_loss: 0.0980 - val_mean_absolute_error: 0.2613 - val_mean_absolute_percentage_error: 59493184.0000 - val_root_mean_squared_error: 0.3130
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step - loss: 0.1318 - mean_absolute_error: 0.3181 - mean_absolute_percentage_error: 69599328.0000 - root_mean_squared_error: 0.3630 - val_loss: 0.0978 - val_mean_absolute_error: 0.2597 - val_mean_absolute_percentage_error: 60333716.0000 - val_root_mean_squared_error: 0.3127
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 3s/step - loss: 0.1330 - mean_absolute_error: 0.3202 - mean_absolute_percentage_error: 71533784.0000 - root_mean_squared_error: 0.3647 - val_loss: 0.0978 - val_mean_absolute_error: 0.2550 - val_mean_absolute_percentage_error: 62520200.0000 - val_root_mean_squared_error: 0.3127
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.1290 - mean_absolute_error: 0.3106 - mean_absolute_percentage_error: 71727952.0000 - root_mean_squared_error: 0.3591 - val_loss: 0.0980 - val_mean_absolute_error: 0.2532 - val_mean_absolute_percentage_error: 63575696.0000 - val_root_mean_squared_error: 0.3131
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 35s 4s/step - loss: 0.1279 - mean_absolute_error: 0.3089 - mean_absolute_percentage_error: 67563368.0000 - root_mean_squared_error: 0.3576 - val_loss: 0.0976 - val_mean_absolute_error: 0.2553 - val_mean_absolute_percentage_error: 62252708.0000 - val_root_mean_squared_error: 0.3123
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 3s/step - loss: 0.1248 - mean_absolute_error: 0.3072 - mean_absolute_percentage_error: 68327048.0000 - root_mean_squared_error: 0.3533 - val_loss: 0.0974 - val_mean_absolute_error: 0.2562 - val_mean_absolute_percentage_error: 61696356.0000 - val_root_mean_squared_error: 0.3121
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.1279 - mean_absolute_error: 0.3125 - mean_absolute_percentage_error: 67425560.0000 - root_mean_squared_error: 0.3575 - val_loss: 0.0974 - val_mean_absolute_error: 0.2565 - val_mean_absolute_percentage_error: 61457168.0000 - val_root_mean_squared_error: 0.3120
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 2s/step - loss: 0.1295 - mean_absolute_error: 0.3141 - mean_absolute_percentage_error: 68888184.0000 - root_mean_squared_error: 0.3598 - val_loss: 0.0974 - val_mean_absolute_error: 0.2548 - val_mean_absolute_percentage_error: 62389344.0000 - val_root_mean_squared_error: 0.3121
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 3s/step - loss: 0.1255 - mean_absolute_error: 0.3085 - mean_absolute_percentage_error: 66083428.0000 - root_mean_squared_error: 0.3542 - val_loss: 0.0976 - val_mean_absolute_error: 0.2538 - val_mean_absolute_percentage_error: 63084228.0000 - val_root_mean_squared_error: 0.3124
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 2s/step - loss: 0.1253 - mean_absolute_error: 0.3052 - mean_absolute_percentage_error: 69734800.0000 - root_mean_squared_error: 0.3540 - val_loss: 0.0991 - val_mean_absolute_error: 0.2510 - val_mean_absolute_percentage_error: 66079452.0000 - val_root_mean_squared_error: 0.3149
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 28s 3s/step - loss: 0.1260 - mean_absolute_error: 0.3013 - mean_absolute_percentage_error: 75181960.0000 - root_mean_squared_error: 0.3550 - val_loss: 0.0997 - val_mean_absolute_error: 0.2507 - val_mean_absolute_percentage_error: 66669040.0000 - val_root_mean_squared_error: 0.3157
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 26s 3s/step - loss: 0.1273 - mean_absolute_error: 0.3054 - mean_absolute_percentage_error: 72554424.0000 - root_mean_squared_error: 0.3567 - val_loss: 0.0976 - val_mean_absolute_error: 0.2538 - val_mean_absolute_percentage_error: 63247836.0000 - val_root_mean_squared_error: 0.3125
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.1272 - mean_absolute_error: 0.3097 - mean_absolute_percentage_error: 64823148.0000 - root_mean_squared_error: 0.3566 - val_loss: 0.0972 - val_mean_absolute_error: 0.2558 - val_mean_absolute_percentage_error: 61827312.0000 - val_root_mean_squared_error: 0.3118
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 15s 1s/step - loss: 0.1241 - mean_absolute_error: 0.3040 - mean_absolute_percentage_error: 64565992.0000 - root_mean_squared_error: 0.3522 - val_loss: 0.0973 - val_mean_absolute_error: 0.2551 - val_mean_absolute_percentage_error: 62267360.0000 - val_root_mean_squared_error: 0.3119
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1259 - mean_absolute_error: 0.3074 - mean_absolute_percentage_error: 65348432.0000 - root_mean_squared_error: 0.3549 - val_loss: 0.0978 - val_mean_absolute_error: 0.2526 - val_mean_absolute_percentage_error: 64093516.0000 - val_root_mean_squared_error: 0.3128
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 2s/step - loss: 0.1268 - mean_absolute_error: 0.3053 - mean_absolute_percentage_error: 69790168.0000 - root_mean_squared_error: 0.3560 - val_loss: 0.0984 - val_mean_absolute_error: 0.2516 - val_mean_absolute_percentage_error: 65163652.0000 - val_root_mean_squared_error: 0.3137
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - loss: 0.1290 - mean_absolute_error: 0.3100 - mean_absolute_percentage_error: 72961552.0000 - root_mean_squared_error: 0.3591 - val_loss: 0.0978 - val_mean_absolute_error: 0.2528 - val_mean_absolute_percentage_error: 63966132.0000 - val_root_mean_squared_error: 0.3127

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

21/21 ━━━━━━━━━━━━━━━━━━━━ 21s 396ms/step

array([[0.5059599 ],
       [0.5029956 ],
       [0.50568545],
       [0.5104246 ],
       [0.51614064],
       [0.5208788 ],
       [0.52315134],
       [0.52240264],
       [0.52098244],
       [0.5197147 ],
       [0.5172834 ],
       [0.5167684 ],
       [0.5174764 ],
       [0.5167272 ],
       [0.51516336],
       [0.51471823],
       [0.51799417],
       [0.52281886],
       [0.52508926],
       [0.5256483 ],
       [0.52525645],
       [0.5234683 ],
       [0.51955193],
       [0.5153869 ],
       [0.5203881 ],
       [0.52913827],
       [0.53392637],
       [0.5343628 ],
       [0.53545225],
       [0.53730553],
       [0.5409675 ],
       [0.54144615],
       [0.540031  ],
       [0.53888047],
       [0.54228854],
       [0.54683673],
       [0.547083  ],
       [0.5448188 ],
       [0.5426137 ],
       [0.53856796],
       [0.5339338 ],
       [0.5287147 ],
       [0.52364635],
       [0.52968425],
       [0.5299931 ],
       [0.5279184 ],
       [0.52630085],
       [0.5274067 ],
       [0.52763206],
       [0.52495223],
       [0.5216976 ],
       [0.5225318 ],
       [0.5247593 ],
       [0.52350163],
       [0.52156633],
       [0.5200451 ],
       [0.51850766],
       [0.51675636],
       [0.5136462 ],
       [0.5178955 ],
       [0.52647454],
       [0.5296637 ],
       [0.5320505 ],
       [0.532395  ],
       [0.5283255 ],
       [0.52325755],
       [0.5189654 ],
       [0.5220281 ],
       [0.5260078 ],
       [0.5273054 ],
       [0.5270235 ],
       [0.5259008 ],
       [0.519512  ],
       [0.52054113],
       [0.52265483],
       [0.52164   ],
       [0.5201733 ],
       [0.5198645 ],
       [0.5194611 ],
       [0.51898974],
       [0.5172678 ],
       [0.5193545 ],
       [0.51739866],
       [0.5136134 ],
       [0.51490486],
       [0.51721334],
       [0.51678866],
       [0.5186344 ],
       [0.52030057],
       [0.52078706],
       [0.51844245],
       [0.51094466],
       [0.5143082 ],
       [0.5176223 ],
       [0.5192483 ],
       [0.5211243 ],
       [0.5227414 ],
       [0.5208483 ],
       [0.5221184 ],
       [0.52054334],
       [0.51746213],
       [0.51449645],
       [0.51003927],
       [0.50757957],
       [0.51193833],
       [0.5165257 ],
       [0.51755613],
       [0.5137357 ],
       [0.5065512 ],
       [0.5018525 ],
       [0.50416535],
       [0.50537527],
       [0.50602955],
       [0.5064077 ],
       [0.50523347],
       [0.5005332 ],
       [0.5024974 ],
       [0.5053558 ],
       [0.50723994],
       [0.50733554],
       [0.50558597],
       [0.5016676 ],
       [0.5015261 ],
       [0.5014366 ],
       [0.50049305],
       [0.49875486],
       [0.49722898],
       [0.49637902],
       [0.50037235],
       [0.5013878 ],
       [0.50046885],
       [0.49752074],
       [0.49333507],
       [0.48872066],
       [0.49154302],
       [0.4921071 ],
       [0.49305338],
       [0.49391487],
       [0.49499577],
       [0.49465245],
       [0.4902603 ],
       [0.49275628],
       [0.4949234 ],
       [0.4962289 ],
       [0.49868622],
       [0.49948487],
       [0.49551502],
       [0.49140352],
       [0.4956844 ],
       [0.49826133],
       [0.50034565],
       [0.5009753 ],
       [0.49788022],
       [0.4944967 ],
       [0.4921263 ],
       [0.49480683],
       [0.50166756],
       [0.50543606],
       [0.50365144],
       [0.50156635],
       [0.50176036],
       [0.5005813 ],
       [0.50009286],
       [0.50488746],
       [0.5045187 ],
       [0.5030285 ],
       [0.5033272 ],
       [0.50260484],
       [0.5019079 ],
       [0.5066714 ],
       [0.50770104],
       [0.5061267 ],
       [0.50518507],
       [0.50394946],
       [0.5035284 ],
       [0.50860596],
       [0.50889885],
       [0.5096406 ],
       [0.509656  ],
       [0.50786895],
       [0.50665426],
       [0.51040196],
       [0.50888264],
       [0.5077756 ],
       [0.506789  ],
       [0.50529134],
       [0.5031894 ],
       [0.50680774],
       [0.508923  ],
       [0.5059912 ],
       [0.50275844],
       [0.49952167],
       [0.49784154],
       [0.5021147 ],
       [0.50884366],
       [0.51053244],
       [0.5078842 ],
       [0.50628793],
       [0.50622296],
       [0.50582355],
       [0.5043782 ],
       [0.5099396 ],
       [0.5149848 ],
       [0.51392883],
       [0.51057535],
       [0.5090221 ],
       [0.5093457 ],
       [0.5088571 ],
       [0.5070287 ],
       [0.5127371 ],
       [0.5191865 ],
       [0.5190615 ],
       [0.5174362 ],
       [0.5171389 ],
       [0.51715076],
       [0.5179134 ],
       [0.5168517 ],
       [0.51803505],
       [0.52029973],
       [0.5220991 ],
       [0.52311474],
       [0.5256262 ],
       [0.5264198 ],
       [0.52301294],
       [0.51862913],
       [0.52061874],
       [0.522377  ],
       [0.5230905 ],
       [0.52216756],
       [0.5192378 ],
       [0.5160956 ],
       [0.51992196],
       [0.52188283],
       [0.52328986],
       [0.5246755 ],
       [0.52122563],
       [0.515971  ],
       [0.5210195 ],
       [0.5240268 ],
       [0.52668273],
       [0.5278614 ],
       [0.5222253 ],
       [0.51591176],
       [0.51811993],
       [0.51783097],
       [0.5195272 ],
       [0.52098906],
       [0.52027875],
       [0.5185146 ],
       [0.51944757],
       [0.5182298 ],
       [0.5176087 ],
       [0.5147522 ],
       [0.51316506],
       [0.5125751 ],
       [0.51736593],
       [0.5198639 ],
       [0.5161614 ],
       [0.5118253 ],
       [0.50835407],
       [0.504681  ],
       [0.50800383],
       [0.5106124 ],
       [0.5122845 ],
       [0.51183015],
       [0.5080369 ],
       [0.50318515],
       [0.504908  ],
       [0.5047313 ],
       [0.5033925 ],
       [0.5032334 ],
       [0.5038716 ],
       [0.5033642 ],
       [0.5052646 ],
       [0.50582355],
       [0.5073006 ],
       [0.5081693 ],
       [0.5084856 ],
       [0.5079004 ],
       [0.5098441 ],
       [0.510745  ],
       [0.51087266],
       [0.5107013 ],
       [0.51118284],
       [0.5103714 ],
       [0.51175386],
       [0.51106113],
       [0.510477  ],
       [0.50917566],
       [0.5088014 ],
       [0.50762683],
       [0.5084951 ],
       [0.50792515],
       [0.5076136 ],
       [0.5067238 ],
       [0.50604975],
       [0.5046849 ],
       [0.5081799 ],
       [0.5084584 ],
       [0.5102968 ],
       [0.5121256 ],
       [0.5147135 ],
       [0.51621884],
       [0.51505923],
       [0.51204735],
       [0.5154609 ],
       [0.5184294 ],
       [0.52232796],
       [0.5265551 ],
       [0.52634007],
       [0.5248758 ],
       [0.5287863 ],
       [0.5298692 ],
       [0.53312284],
       [0.53563154],
       [0.5377057 ],
       [0.5376268 ],
       [0.53932184],
       [0.5444832 ],
       [0.5483209 ],
       [0.5510663 ],
       [0.5487042 ],
       [0.54982215],
       [0.5528107 ],
       [0.55546796],
       [0.5582438 ],
       [0.562774  ],
       [0.56281495],
       [0.5630326 ],
       [0.56710327],
       [0.5687773 ],
       [0.56997424],
       [0.5704184 ],
       [0.5726189 ],
       [0.570697  ],
       [0.570646  ],
       [0.5719548 ],
       [0.5717764 ],
       [0.5716652 ],
       [0.5695134 ],
       [0.56703895],
       [0.5676672 ],
       [0.5663939 ],
       [0.56931406],
       [0.5713831 ],
       [0.56679523],
       [0.5643385 ],
       [0.5609201 ],
       [0.5646741 ],
       [0.5666123 ],
       [0.56641257],
       [0.56647855],
       [0.5650516 ],
       [0.5653757 ],
       [0.5635929 ],
       [0.5629369 ],
       [0.5608473 ],
       [0.5568903 ],
       [0.5601727 ],
       [0.56099826],
       [0.5627072 ],
       [0.5625305 ],
       [0.55709034],
       [0.55350226],
       [0.551053  ],
       [0.5471584 ],
       [0.5473713 ],
       [0.53909487],
       [0.5361565 ],
       [0.5334043 ],
       [0.5333366 ],
       [0.52667636],
       [0.5214469 ],
       [0.5149504 ],
       [0.50834745],
       [0.50042254],
       [0.49687213],
       [0.49711192],
       [0.49680954],
       [0.49580798],
       [0.49330774],
       [0.49190816],
       [0.5024542 ],
       [0.5059159 ],
       [0.5076932 ],
       [0.51787513],
       [0.5257849 ],
       [0.5303503 ],
       [0.5367002 ],
       [0.53997445],
       [0.54007417],
       [0.53901047],
       [0.53795457],
       [0.5388973 ],
       [0.54016   ],
       [0.54653853],
       [0.54255944],
       [0.53959733],
       [0.53814554],
       [0.545296  ],
       [0.5462513 ],
       [0.54375976],
       [0.547042  ],
       [0.5485682 ],
       [0.5507626 ],
       [0.55141896],
       [0.55240065],
       [0.5499461 ],
       [0.5467692 ],
       [0.5458043 ],
       [0.5544122 ],
       [0.55654746],
       [0.5560042 ],
       [0.5568257 ],
       [0.5606466 ],
       [0.56220865],
       [0.5637736 ],
       [0.5639463 ],
       [0.5624823 ],
       [0.5667624 ],
       [0.5685645 ],
       [0.5701179 ],
       [0.5699242 ],
       [0.5689997 ],
       [0.57210404],
       [0.5706274 ],
       [0.5689152 ],
       [0.5683065 ],
       [0.571848  ],
       [0.5704165 ],
       [0.56775516],
       [0.5660872 ],
       [0.5628138 ],
       [0.55866426],
       [0.5605842 ],
       [0.5585051 ],
       [0.5567722 ],
       [0.556553  ],
       [0.5561737 ],
       [0.5551304 ],
       [0.55298096],
       [0.5550537 ],
       [0.5546203 ],
       [0.55172306],
       [0.54984397],
       [0.54836655],
       [0.5533103 ],
       [0.5534857 ],
       [0.55109197],
       [0.5480962 ],
       [0.54937106],
       [0.5485878 ],
       [0.5481796 ],
       [0.5455258 ],
       [0.5464958 ],
       [0.5462559 ],
       [0.5463412 ],
       [0.5443495 ],
       [0.5471277 ],
       [0.5481259 ],
       [0.5492384 ],
       [0.55104417],
       [0.55202407],
       [0.55368   ],
       [0.5546036 ],
       [0.5572622 ],
       [0.55869323],
       [0.5564114 ],
       [0.5549806 ],
       [0.55906165],
       [0.5594216 ],
       [0.55848354],
       [0.5606323 ],
       [0.5592162 ],
       [0.5598511 ],
       [0.56473273],
       [0.56429946],
       [0.56512165],
       [0.56558233],
       [0.5661776 ],
       [0.5716644 ],
       [0.57464844],
       [0.57520705],
       [0.57600564],
       [0.57477087],
       [0.5738221 ],
       [0.5743872 ],
       [0.5789408 ],
       [0.5816533 ],
       [0.5796168 ],
       [0.57891035],
       [0.579447  ],
       [0.5792578 ],
       [0.5814525 ],
       [0.58026236],
       [0.5788582 ],
       [0.577729  ],
       [0.5768501 ],
       [0.5793497 ],
       [0.5788707 ],
       [0.5788984 ],
       [0.57988614],
       [0.5794116 ],
       [0.57893527],
       [0.57753533],
       [0.57993937],
       [0.5786074 ],
       [0.5768675 ],
       [0.5750917 ],
       [0.57515365],
       [0.5743056 ],
       [0.5729147 ],
       [0.56989735],
       [0.57135826],
       [0.57053035],
       [0.5712375 ],
       [0.5707073 ],
       [0.56751066],
       [0.5703048 ],
       [0.57049435],
       [0.5691686 ],
       [0.56841195],
       [0.5688364 ],
       [0.5666763 ],
       [0.56558746],
       [0.5626128 ],
       [0.5650555 ],
       [0.56385463],
       [0.5599298 ],
       [0.55611026],
       [0.5574319 ],
       [0.5563409 ],
       [0.55658656],
       [0.55641437],
       [0.55674917],
       [0.5540127 ],
       [0.55281144],
       [0.55207855],
       [0.554299  ],
       [0.5524017 ],
       [0.5514445 ],
       [0.5497876 ],
       [0.54829746],
       [0.5476504 ],
       [0.5464525 ],
       [0.5432067 ],
       [0.539757  ],
       [0.53656787],
       [0.53337735],
       [0.5316544 ],
       [0.5306576 ],
       [0.52873844],
       [0.52654237],
       [0.5227541 ],
       [0.52115685],
       [0.52147394],
       [0.52201587],
       [0.51981133],
       [0.5220874 ],
       [0.5242112 ],
       [0.52389824],
       [0.52110946],
       [0.5240259 ],
       [0.5232592 ],
       [0.525433  ],
       [0.52650887],
       [0.5305638 ],
       [0.53247255],
       [0.5334966 ],
       [0.5326058 ],
       [0.5318361 ],
       [0.5291311 ],
       [0.5349872 ],
       [0.53538674],
       [0.5371396 ],
       [0.53958404],
       [0.54005057],
       [0.5452779 ],
       [0.54535466],
       [0.5486375 ],
       [0.5498842 ],
       [0.54999685],
       [0.5536941 ],
       [0.55797297],
       [0.5599574 ],
       [0.5634276 ],
       [0.5649229 ],
       [0.5644188 ],
       [0.56965655],
       [0.57269233],
       [0.5732147 ],
       [0.5777175 ],
       [0.57953984],
       [0.5805647 ],
       [0.58146745],
       [0.58571047],
       [0.5860371 ],
       [0.5859427 ],
       [0.5844063 ],
       [0.5884074 ],
       [0.5890085 ],
       [0.58772105],
       [0.59090865],
       [0.5893962 ],
       [0.58766276],
       [0.5888678 ],
       [0.5879151 ],
       [0.5875909 ],
       [0.587297  ],
       [0.58936447],
       [0.5891989 ],
       [0.58755636],
       [0.58917934],
       [0.58949435],
       [0.58792436],
       [0.5861545 ],
       [0.58944345],
       [0.5913208 ],
       [0.5922769 ],
       [0.59247047],
       [0.59143114],
       [0.5938273 ],
       [0.5943992 ],
       [0.59459907],
       [0.5954456 ],
       [0.59421664],
       [0.59315675],
       [0.5916277 ],
       [0.59405977],
       [0.5945595 ],
       [0.5934122 ],
       [0.5933863 ],
       [0.5924617 ],
       [0.5910451 ],
       [0.58938116],
       [0.590815  ],
       [0.5894636 ],
       [0.5880633 ],
       [0.58643   ],
       [0.58775544],
       [0.58814937],
       [0.5881294 ],
       [0.5870163 ],
       [0.58579665],
       [0.587953  ],
       [0.58892554],
       [0.58839995],
       [0.5868882 ],
       [0.5860664 ]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
14609     21617.0  24312.477855  25032.668096           NaN
14610     20399.0  21363.704588  20701.133338           NaN
14611     17247.0  16662.192043  15987.507201           NaN
14612      6569.0   6329.374684   7427.492492           NaN
14613       227.0    374.941399       349.495           NaN
...           ...           ...           ...           ...
18281     25386.0  26751.870947  26019.654367  17638.589844
18282     22872.0   23370.96659  22637.749887  17667.765625
18283     15825.0  15084.108971  16064.234452  17651.998047
18284      1450.0   1894.938407   2119.455433  17606.646484
18285         0.0           0.0      0.077852  17581.992188

[697 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 219s 10s/step - loss: 0.3658 - mean_absolute_error: 0.4951 - mean_absolute_percentage_error: 4155668.5000 - root_mean_squared_error: 0.6046 - val_loss: 0.1970 - val_mean_absolute_error: 0.3951 - val_mean_absolute_percentage_error: 25299122.0000 - val_root_mean_squared_error: 0.4439
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 77s 8s/step - loss: 0.1800 - mean_absolute_error: 0.3645 - mean_absolute_percentage_error: 48039816.0000 - root_mean_squared_error: 0.4237 - val_loss: 0.1719 - val_mean_absolute_error: 0.3170 - val_mean_absolute_percentage_error: 92058688.0000 - val_root_mean_squared_error: 0.4146
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 73s 6s/step - loss: 0.2127 - mean_absolute_error: 0.3680 - mean_absolute_percentage_error: 107094784.0000 - root_mean_squared_error: 0.4610 - val_loss: 0.1055 - val_mean_absolute_error: 0.2834 - val_mean_absolute_percentage_error: 51195656.0000 - val_root_mean_squared_error: 0.3249
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 49s 7s/step - loss: 0.1497 - mean_absolute_error: 0.3425 - mean_absolute_percentage_error: 59050004.0000 - root_mean_squared_error: 0.3868 - val_loss: 0.1442 - val_mean_absolute_error: 0.3419 - val_mean_absolute_percentage_error: 36660660.0000 - val_root_mean_squared_error: 0.3798
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 7s/step - loss: 0.1610 - mean_absolute_error: 0.3526 - mean_absolute_percentage_error: 49533412.0000 - root_mean_squared_error: 0.4012 - val_loss: 0.1075 - val_mean_absolute_error: 0.2869 - val_mean_absolute_percentage_error: 50096212.0000 - val_root_mean_squared_error: 0.3279
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 7s/step - loss: 0.1372 - mean_absolute_error: 0.3336 - mean_absolute_percentage_error: 65696636.0000 - root_mean_squared_error: 0.3703 - val_loss: 0.1012 - val_mean_absolute_error: 0.2501 - val_mean_absolute_percentage_error: 67354192.0000 - val_root_mean_squared_error: 0.3182
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 5s/step - loss: 0.1498 - mean_absolute_error: 0.3398 - mean_absolute_percentage_error: 83905136.0000 - root_mean_squared_error: 0.3870 - val_loss: 0.0997 - val_mean_absolute_error: 0.2510 - val_mean_absolute_percentage_error: 65442516.0000 - val_root_mean_squared_error: 0.3158
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 50s 7s/step - loss: 0.1360 - mean_absolute_error: 0.3308 - mean_absolute_percentage_error: 75060408.0000 - root_mean_squared_error: 0.3688 - val_loss: 0.1057 - val_mean_absolute_error: 0.2826 - val_mean_absolute_percentage_error: 51283472.0000 - val_root_mean_squared_error: 0.3251
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 6s/step - loss: 0.1386 - mean_absolute_error: 0.3368 - mean_absolute_percentage_error: 61938628.0000 - root_mean_squared_error: 0.3723 - val_loss: 0.1060 - val_mean_absolute_error: 0.2833 - val_mean_absolute_percentage_error: 51088024.0000 - val_root_mean_squared_error: 0.3256
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 7s/step - loss: 0.1399 - mean_absolute_error: 0.3378 - mean_absolute_percentage_error: 61957740.0000 - root_mean_squared_error: 0.3741 - val_loss: 0.1058 - val_mean_absolute_error: 0.2830 - val_mean_absolute_percentage_error: 51177264.0000 - val_root_mean_squared_error: 0.3253
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 6s/step - loss: 0.1380 - mean_absolute_error: 0.3376 - mean_absolute_percentage_error: 66999764.0000 - root_mean_squared_error: 0.3715 - val_loss: 0.0984 - val_mean_absolute_error: 0.2603 - val_mean_absolute_percentage_error: 59688524.0000 - val_root_mean_squared_error: 0.3137
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 6s/step - loss: 0.1373 - mean_absolute_error: 0.3326 - mean_absolute_percentage_error: 75511288.0000 - root_mean_squared_error: 0.3705 - val_loss: 0.0997 - val_mean_absolute_error: 0.2510 - val_mean_absolute_percentage_error: 65502492.0000 - val_root_mean_squared_error: 0.3158
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 5s/step - loss: 0.1387 - mean_absolute_error: 0.3299 - mean_absolute_percentage_error: 81966064.0000 - root_mean_squared_error: 0.3724 - val_loss: 0.0984 - val_mean_absolute_error: 0.2601 - val_mean_absolute_percentage_error: 59790412.0000 - val_root_mean_squared_error: 0.3136
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 63s 8s/step - loss: 0.1368 - mean_absolute_error: 0.3341 - mean_absolute_percentage_error: 73207000.0000 - root_mean_squared_error: 0.3699 - val_loss: 0.1073 - val_mean_absolute_error: 0.2863 - val_mean_absolute_percentage_error: 50247780.0000 - val_root_mean_squared_error: 0.3276
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 34s 4s/step - loss: 0.1386 - mean_absolute_error: 0.3353 - mean_absolute_percentage_error: 58308496.0000 - root_mean_squared_error: 0.3722 - val_loss: 0.1024 - val_mean_absolute_error: 0.2750 - val_mean_absolute_percentage_error: 53680708.0000 - val_root_mean_squared_error: 0.3200
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 47s 4s/step - loss: 0.1329 - mean_absolute_error: 0.3283 - mean_absolute_percentage_error: 67686880.0000 - root_mean_squared_error: 0.3646 - val_loss: 0.1007 - val_mean_absolute_error: 0.2500 - val_mean_absolute_percentage_error: 66969832.0000 - val_root_mean_squared_error: 0.3173
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 6s/step - loss: 0.1441 - mean_absolute_error: 0.3310 - mean_absolute_percentage_error: 84802144.0000 - root_mean_squared_error: 0.3796 - val_loss: 0.1002 - val_mean_absolute_error: 0.2496 - val_mean_absolute_percentage_error: 66945836.0000 - val_root_mean_squared_error: 0.3165
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 49s 7s/step - loss: 0.1357 - mean_absolute_error: 0.3270 - mean_absolute_percentage_error: 74418568.0000 - root_mean_squared_error: 0.3684 - val_loss: 0.1009 - val_mean_absolute_error: 0.2737 - val_mean_absolute_percentage_error: 54192376.0000 - val_root_mean_squared_error: 0.3177
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 0.1324 - mean_absolute_error: 0.3278 - mean_absolute_percentage_error: 71285288.0000 - root_mean_squared_error: 0.3638 - val_loss: 0.0979 - val_mean_absolute_error: 0.2577 - val_mean_absolute_percentage_error: 60816072.0000 - val_root_mean_squared_error: 0.3128
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 67s 5s/step - loss: 0.1298 - mean_absolute_error: 0.3217 - mean_absolute_percentage_error: 73378544.0000 - root_mean_squared_error: 0.3603 - val_loss: 0.0981 - val_mean_absolute_error: 0.2541 - val_mean_absolute_percentage_error: 62811752.0000 - val_root_mean_squared_error: 0.3132
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 62s 8s/step - loss: 0.1287 - mean_absolute_error: 0.3153 - mean_absolute_percentage_error: 74147552.0000 - root_mean_squared_error: 0.3587 - val_loss: 0.0997 - val_mean_absolute_error: 0.2511 - val_mean_absolute_percentage_error: 65872880.0000 - val_root_mean_squared_error: 0.3158
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 53s 8s/step - loss: 0.1255 - mean_absolute_error: 0.3084 - mean_absolute_percentage_error: 75414088.0000 - root_mean_squared_error: 0.3542 - val_loss: 0.0986 - val_mean_absolute_error: 0.2532 - val_mean_absolute_percentage_error: 63796572.0000 - val_root_mean_squared_error: 0.3140
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 51s 7s/step - loss: 0.1217 - mean_absolute_error: 0.3006 - mean_absolute_percentage_error: 70112880.0000 - root_mean_squared_error: 0.3489 - val_loss: 0.1043 - val_mean_absolute_error: 0.2506 - val_mean_absolute_percentage_error: 70193336.0000 - val_root_mean_squared_error: 0.3229
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 45s 7s/step - loss: 0.1286 - mean_absolute_error: 0.3012 - mean_absolute_percentage_error: 75986192.0000 - root_mean_squared_error: 0.3586 - val_loss: 0.0999 - val_mean_absolute_error: 0.2504 - val_mean_absolute_percentage_error: 66209360.0000 - val_root_mean_squared_error: 0.3160
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 34s 5s/step - loss: 0.1269 - mean_absolute_error: 0.3129 - mean_absolute_percentage_error: 72267680.0000 - root_mean_squared_error: 0.3562 - val_loss: 0.1018 - val_mean_absolute_error: 0.2744 - val_mean_absolute_percentage_error: 53887384.0000 - val_root_mean_squared_error: 0.3191
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 71s 10s/step - loss: 0.1321 - mean_absolute_error: 0.3256 - mean_absolute_percentage_error: 58294152.0000 - root_mean_squared_error: 0.3635 - val_loss: 0.1016 - val_mean_absolute_error: 0.2739 - val_mean_absolute_percentage_error: 54043392.0000 - val_root_mean_squared_error: 0.3188
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 77s 8s/step - loss: 0.1250 - mean_absolute_error: 0.3118 - mean_absolute_percentage_error: 65330920.0000 - root_mean_squared_error: 0.3536 - val_loss: 0.1096 - val_mean_absolute_error: 0.2532 - val_mean_absolute_percentage_error: 73559104.0000 - val_root_mean_squared_error: 0.3310
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 88s 9s/step - loss: 0.1316 - mean_absolute_error: 0.2926 - mean_absolute_percentage_error: 82325440.0000 - root_mean_squared_error: 0.3627 - val_loss: 0.1033 - val_mean_absolute_error: 0.2531 - val_mean_absolute_percentage_error: 68744424.0000 - val_root_mean_squared_error: 0.3214
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 78s 7s/step - loss: 0.1241 - mean_absolute_error: 0.3059 - mean_absolute_percentage_error: 69968848.0000 - root_mean_squared_error: 0.3523 - val_loss: 0.1021 - val_mean_absolute_error: 0.2728 - val_mean_absolute_percentage_error: 54700156.0000 - val_root_mean_squared_error: 0.3195
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 58s 9s/step - loss: 0.1279 - mean_absolute_error: 0.3189 - mean_absolute_percentage_error: 60520800.0000 - root_mean_squared_error: 0.3575 - val_loss: 0.0988 - val_mean_absolute_error: 0.2555 - val_mean_absolute_percentage_error: 62752140.0000 - val_root_mean_squared_error: 0.3143
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 66s 5s/step - loss: 0.1226 - mean_absolute_error: 0.3070 - mean_absolute_percentage_error: 66482116.0000 - root_mean_squared_error: 0.3501 - val_loss: 0.1009 - val_mean_absolute_error: 0.2527 - val_mean_absolute_percentage_error: 67033272.0000 - val_root_mean_squared_error: 0.3176
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 65s 9s/step - loss: 0.1237 - mean_absolute_error: 0.2912 - mean_absolute_percentage_error: 75330872.0000 - root_mean_squared_error: 0.3517 - val_loss: 0.1187 - val_mean_absolute_error: 0.2614 - val_mean_absolute_percentage_error: 77548528.0000 - val_root_mean_squared_error: 0.3445
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.1225 - mean_absolute_error: 0.2863 - mean_absolute_percentage_error: 76245704.0000 - root_mean_squared_error: 0.3499 - val_loss: 0.0980 - val_mean_absolute_error: 0.2597 - val_mean_absolute_percentage_error: 59983548.0000 - val_root_mean_squared_error: 0.3131
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.1225 - mean_absolute_error: 0.3103 - mean_absolute_percentage_error: 60649016.0000 - root_mean_squared_error: 0.3500 - val_loss: 0.0989 - val_mean_absolute_error: 0.2638 - val_mean_absolute_percentage_error: 58042804.0000 - val_root_mean_squared_error: 0.3145
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 67s 9s/step - loss: 0.1230 - mean_absolute_error: 0.3124 - mean_absolute_percentage_error: 59263048.0000 - root_mean_squared_error: 0.3506 - val_loss: 0.1058 - val_mean_absolute_error: 0.2555 - val_mean_absolute_percentage_error: 70878944.0000 - val_root_mean_squared_error: 0.3252
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 49s 7s/step - loss: 0.1152 - mean_absolute_error: 0.2871 - mean_absolute_percentage_error: 71778000.0000 - root_mean_squared_error: 0.3394 - val_loss: 0.0988 - val_mean_absolute_error: 0.2526 - val_mean_absolute_percentage_error: 65696964.0000 - val_root_mean_squared_error: 0.3143
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 90s 7s/step - loss: 0.1030 - mean_absolute_error: 0.2757 - mean_absolute_percentage_error: 60868660.0000 - root_mean_squared_error: 0.3210 - val_loss: 0.0904 - val_mean_absolute_error: 0.2523 - val_mean_absolute_percentage_error: 53505684.0000 - val_root_mean_squared_error: 0.3007
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 85s 7s/step - loss: 0.1032 - mean_absolute_error: 0.2772 - mean_absolute_percentage_error: 44105920.0000 - root_mean_squared_error: 0.3213 - val_loss: 0.0826 - val_mean_absolute_error: 0.2359 - val_mean_absolute_percentage_error: 52822100.0000 - val_root_mean_squared_error: 0.2874
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 7s/step - loss: 0.0882 - mean_absolute_error: 0.2450 - mean_absolute_percentage_error: 47927436.0000 - root_mean_squared_error: 0.2970 - val_loss: 0.0787 - val_mean_absolute_error: 0.2334 - val_mean_absolute_percentage_error: 45769444.0000 - val_root_mean_squared_error: 0.2804
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 53s 8s/step - loss: 0.0755 - mean_absolute_error: 0.2238 - mean_absolute_percentage_error: 43319676.0000 - root_mean_squared_error: 0.2748 - val_loss: 0.0752 - val_mean_absolute_error: 0.2274 - val_mean_absolute_percentage_error: 37172580.0000 - val_root_mean_squared_error: 0.2743
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 39s 5s/step - loss: 0.0698 - mean_absolute_error: 0.2149 - mean_absolute_percentage_error: 41451972.0000 - root_mean_squared_error: 0.2641 - val_loss: 0.0786 - val_mean_absolute_error: 0.2285 - val_mean_absolute_percentage_error: 51558568.0000 - val_root_mean_squared_error: 0.2804
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 52s 8s/step - loss: 0.0768 - mean_absolute_error: 0.2239 - mean_absolute_percentage_error: 54387156.0000 - root_mean_squared_error: 0.2771 - val_loss: 0.0769 - val_mean_absolute_error: 0.2311 - val_mean_absolute_percentage_error: 38290016.0000 - val_root_mean_squared_error: 0.2774
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 53s 8s/step - loss: 0.0707 - mean_absolute_error: 0.2182 - mean_absolute_percentage_error: 42763600.0000 - root_mean_squared_error: 0.2659 - val_loss: 0.0676 - val_mean_absolute_error: 0.2119 - val_mean_absolute_percentage_error: 34599564.0000 - val_root_mean_squared_error: 0.2601
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 71s 6s/step - loss: 0.0680 - mean_absolute_error: 0.2052 - mean_absolute_percentage_error: 29600352.0000 - root_mean_squared_error: 0.2607 - val_loss: 0.0785 - val_mean_absolute_error: 0.2302 - val_mean_absolute_percentage_error: 35963864.0000 - val_root_mean_squared_error: 0.2802
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 51s 6s/step - loss: 0.0661 - mean_absolute_error: 0.2052 - mean_absolute_percentage_error: 40280312.0000 - root_mean_squared_error: 0.2570 - val_loss: 0.0786 - val_mean_absolute_error: 0.2295 - val_mean_absolute_percentage_error: 40471836.0000 - val_root_mean_squared_error: 0.2803
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 8s/step - loss: 0.0634 - mean_absolute_error: 0.2000 - mean_absolute_percentage_error: 46465044.0000 - root_mean_squared_error: 0.2517 - val_loss: 0.0756 - val_mean_absolute_error: 0.2239 - val_mean_absolute_percentage_error: 45439724.0000 - val_root_mean_squared_error: 0.2750
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 94s 9s/step - loss: 0.0621 - mean_absolute_error: 0.1999 - mean_absolute_percentage_error: 48331204.0000 - root_mean_squared_error: 0.2491 - val_loss: 0.0707 - val_mean_absolute_error: 0.2163 - val_mean_absolute_percentage_error: 29075190.0000 - val_root_mean_squared_error: 0.2659
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 81s 8s/step - loss: 0.0668 - mean_absolute_error: 0.2075 - mean_absolute_percentage_error: 31419804.0000 - root_mean_squared_error: 0.2585 - val_loss: 0.0720 - val_mean_absolute_error: 0.2182 - val_mean_absolute_percentage_error: 43522064.0000 - val_root_mean_squared_error: 0.2683
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 31s 5s/step - loss: 0.0709 - mean_absolute_error: 0.2152 - mean_absolute_percentage_error: 47601936.0000 - root_mean_squared_error: 0.2661 - val_loss: 0.0656 - val_mean_absolute_error: 0.2093 - val_mean_absolute_percentage_error: 38862788.0000 - val_root_mean_squared_error: 0.2561
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 75s 9s/step - loss: 0.0673 - mean_absolute_error: 0.2109 - mean_absolute_percentage_error: 50808408.0000 - root_mean_squared_error: 0.2594 - val_loss: 0.0858 - val_mean_absolute_error: 0.2337 - val_mean_absolute_percentage_error: 61165816.0000 - val_root_mean_squared_error: 0.2929

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

21/21 ━━━━━━━━━━━━━━━━━━━━ 21s 423ms/step

array([[0.677957  ],
       [0.74930465],
       [0.9543879 ],
       [0.99708134],
       [0.9356892 ],
       [0.7655897 ],
       [0.758396  ],
       [0.67938036],
       [0.38771638],
       [0.31287763],
       [0.28373677],
       [0.43926272],
       [0.6370201 ],
       [0.6657094 ],
       [0.7030028 ],
       [0.7899409 ],
       [1.0917351 ],
       [0.9970025 ],
       [0.5630158 ],
       [0.49899086],
       [0.49302605],
       [0.57160234],
       [0.5249633 ],
       [0.5066996 ],
       [0.7568704 ],
       [0.82791495],
       [0.85321474],
       [0.8378831 ],
       [0.57359695],
       [0.47416192],
       [0.5543943 ],
       [0.6721227 ],
       [0.6556852 ],
       [0.600535  ],
       [0.8069048 ],
       [0.87511694],
       [0.835178  ],
       [0.5116378 ],
       [0.42611554],
       [0.31728292],
       [0.41420585],
       [0.5744175 ],
       [0.5831064 ],
       [0.8101547 ],
       [0.7289185 ],
       [0.69380796],
       [0.5078384 ],
       [0.5842795 ],
       [0.6880785 ],
       [0.57839364],
       [0.7008843 ],
       [0.77827805],
       [0.70750064],
       [0.4658777 ],
       [0.44286203],
       [0.41645953],
       [0.5304486 ],
       [0.6179266 ],
       [0.5647589 ],
       [0.7077681 ],
       [0.83589053],
       [0.6570648 ],
       [0.47862512],
       [0.49907282],
       [0.586047  ],
       [0.6625761 ],
       [0.6152425 ],
       [0.5753434 ],
       [0.5355068 ],
       [0.4107549 ],
       [0.33580366],
       [0.5337633 ],
       [0.7108165 ],
       [0.8458866 ],
       [0.8746772 ],
       [0.51248455],
       [0.4016132 ],
       [0.38880044],
       [0.47102836],
       [0.60561085],
       [0.6255538 ],
       [0.59339035],
       [0.51455843],
       [0.7375625 ],
       [0.8773731 ],
       [0.80640817],
       [0.5331402 ],
       [0.46473226],
       [0.35929117],
       [0.31122014],
       [0.4826285 ],
       [0.57332134],
       [0.8222581 ],
       [0.6258165 ],
       [0.46223608],
       [0.49281904],
       [0.73452026],
       [0.703506  ],
       [0.83379555],
       [0.597868  ],
       [0.44735625],
       [0.39152429],
       [0.57700944],
       [0.63121957],
       [0.8004399 ],
       [0.5512713 ],
       [0.38524508],
       [0.2882847 ],
       [0.52925175],
       [0.65780973],
       [0.6989987 ],
       [0.63953304],
       [0.43495426],
       [0.3748974 ],
       [0.6221533 ],
       [0.6256288 ],
       [0.5754698 ],
       [0.5655244 ],
       [0.35469323],
       [0.26317173],
       [0.5617844 ],
       [0.6291251 ],
       [0.7003454 ],
       [0.64343065],
       [0.42519757],
       [0.3455559 ],
       [0.57272995],
       [0.62437254],
       [0.5515136 ],
       [0.5974028 ],
       [0.32992184],
       [0.30756742],
       [0.556871  ],
       [0.5965209 ],
       [0.71644145],
       [0.597276  ],
       [0.44417164],
       [0.27665117],
       [0.4330462 ],
       [0.6106503 ],
       [0.5550477 ],
       [0.7609436 ],
       [0.565429  ],
       [0.42635795],
       [0.3180577 ],
       [0.47973457],
       [0.62607825],
       [0.61391675],
       [0.69249   ],
       [0.6702933 ],
       [0.45272133],
       [0.30925593],
       [0.505264  ],
       [0.6452929 ],
       [0.52636606],
       [0.66794795],
       [0.73906827],
       [0.7040913 ],
       [0.39275852],
       [0.43520373],
       [0.46020418],
       [0.59723425],
       [0.5542533 ],
       [0.74005234],
       [0.5645682 ],
       [0.4328163 ],
       [0.47340724],
       [0.623868  ],
       [0.6210747 ],
       [0.72099304],
       [0.6336334 ],
       [0.48197943],
       [0.22481146],
       [0.44778252],
       [0.63561976],
       [0.73142076],
       [0.53868234],
       [0.48706725],
       [0.30045986],
       [0.4595532 ],
       [0.65546215],
       [0.77529955],
       [0.60468435],
       [0.44433382],
       [0.39050725],
       [0.5802883 ],
       [0.64949906],
       [0.53398085],
       [0.58668834],
       [0.45508882],
       [0.36705747],
       [0.58027565],
       [0.670733  ],
       [0.70164245],
       [0.82263863],
       [0.6991992 ],
       [0.41011366],
       [0.32039317],
       [0.49999586],
       [0.61132735],
       [0.62610614],
       [0.6676067 ],
       [0.72142243],
       [0.7176845 ],
       [0.47636577],
       [0.42720386],
       [0.58328146],
       [0.5825857 ],
       [0.5613374 ],
       [0.7273985 ],
       [0.78586113],
       [0.7190249 ],
       [0.5284537 ],
       [0.4381489 ],
       [0.45956114],
       [0.5835098 ],
       [0.6205367 ],
       [0.7352953 ],
       [0.8234348 ],
       [0.80743253],
       [0.4992436 ],
       [0.46381244],
       [0.41564307],
       [0.5930594 ],
       [0.7164915 ],
       [0.67873037],
       [0.52614427],
       [0.4109053 ],
       [0.4823464 ],
       [0.6822711 ],
       [0.73159206],
       [0.7070223 ],
       [0.6399828 ],
       [0.40667987],
       [0.40407434],
       [0.5886346 ],
       [0.5971497 ],
       [0.7549968 ],
       [0.6167829 ],
       [0.41246983],
       [0.40405512],
       [0.5815398 ],
       [0.6234609 ],
       [0.74449766],
       [0.60545033],
       [0.4433156 ],
       [0.2568312 ],
       [0.4455251 ],
       [0.6519215 ],
       [0.77915704],
       [0.58072364],
       [0.4534199 ],
       [0.25608715],
       [0.5116856 ],
       [0.7009197 ],
       [0.7823788 ],
       [0.6284109 ],
       [0.4540593 ],
       [0.43143794],
       [0.63282526],
       [0.64915895],
       [0.7916192 ],
       [0.636973  ],
       [0.4067828 ],
       [0.33624187],
       [0.5579601 ],
       [0.5876171 ],
       [0.6902828 ],
       [0.6353501 ],
       [0.3738521 ],
       [0.33700755],
       [0.5478371 ],
       [0.6084619 ],
       [0.70207924],
       [0.6146933 ],
       [0.3495482 ],
       [0.33975253],
       [0.5706489 ],
       [0.61017233],
       [0.7235958 ],
       [0.6327915 ],
       [0.39548835],
       [0.29849666],
       [0.54963046],
       [0.6249634 ],
       [0.6834562 ],
       [0.6385907 ],
       [0.4076806 ],
       [0.27759907],
       [0.52991575],
       [0.63478535],
       [0.698722  ],
       [0.6313727 ],
       [0.42461994],
       [0.24439491],
       [0.4662523 ],
       [0.63241947],
       [0.77408254],
       [0.8433311 ],
       [0.7264706 ],
       [0.36073282],
       [0.37970462],
       [0.38895658],
       [0.49909943],
       [0.6726395 ],
       [0.76778996],
       [0.745831  ],
       [0.7160979 ],
       [0.5974606 ],
       [0.65504503],
       [0.77028155],
       [0.883283  ],
       [0.5137752 ],
       [0.3653024 ],
       [0.46674144],
       [0.90022254],
       [0.6513168 ],
       [0.38388082],
       [0.7366568 ],
       [0.7559391 ],
       [0.5068418 ],
       [0.4312044 ],
       [0.8424194 ],
       [0.8374657 ],
       [0.6544272 ],
       [0.59352463],
       [0.91532457],
       [0.8527027 ],
       [0.7394473 ],
       [0.8247694 ],
       [0.64084226],
       [0.48640195],
       [0.50769895],
       [0.8620537 ],
       [0.61865234],
       [0.52852786],
       [0.6209271 ],
       [0.7074791 ],
       [0.67815614],
       [0.77153355],
       [0.74471664],
       [0.65788007],
       [0.65080947],
       [0.6576022 ],
       [0.5479674 ],
       [0.5272395 ],
       [0.5944779 ],
       [0.6069165 ],
       [0.76674306],
       [0.6844291 ],
       [0.47436583],
       [0.45002934],
       [0.5166746 ],
       [0.7972677 ],
       [0.6290469 ],
       [0.41447   ],
       [0.4136501 ],
       [0.63289154],
       [0.85955846],
       [0.751153  ],
       [0.6158023 ],
       [0.64477646],
       [0.4588721 ],
       [0.4359514 ],
       [0.5763655 ],
       [0.584552  ],
       [0.63126105],
       [0.5416198 ],
       [0.5720793 ],
       [0.6503555 ],
       [0.58341   ],
       [0.5593462 ],
       [0.5810066 ],
       [0.48488224],
       [0.41563126],
       [0.4403254 ],
       [0.43202525],
       [0.47938058],
       [0.4842618 ],
       [0.4680434 ],
       [0.31103012],
       [0.3267481 ],
       [0.74839544],
       [0.59072745],
       [0.38552395],
       [0.62881124],
       [0.65664274],
       [0.48576227],
       [0.6575898 ],
       [0.51470923],
       [0.40405786],
       [0.5198746 ],
       [0.6282815 ],
       [0.6494771 ],
       [0.6607832 ],
       [0.95216566],
       [0.6612471 ],
       [0.49692202],
       [0.58465195],
       [0.8305232 ],
       [0.66916835],
       [0.5448427 ],
       [0.81200874],
       [0.61823666],
       [0.34450248],
       [0.41138855],
       [0.82647514],
       [0.57815814],
       [0.3727412 ],
       [0.41359285],
       [0.82475173],
       [0.56831765],
       [0.40023974],
       [0.5420692 ],
       [0.8620244 ],
       [0.6570167 ],
       [0.47659418],
       [0.5124747 ],
       [0.6871013 ],
       [0.8908566 ],
       [0.6647264 ],
       [0.525626  ],
       [0.49301407],
       [0.69223166],
       [0.9052167 ],
       [0.63400584],
       [0.4292184 ],
       [0.5441346 ],
       [0.8594966 ],
       [0.51256484],
       [0.35844675],
       [0.51334023],
       [0.6526022 ],
       [0.55993295],
       [0.79200554],
       [0.641328  ],
       [0.4792991 ],
       [0.38782737],
       [0.5910269 ],
       [0.6209792 ],
       [0.53935117],
       [0.752481  ],
       [0.60460633],
       [0.5088552 ],
       [0.46207884],
       [0.6758017 ],
       [0.83552456],
       [0.60519236],
       [0.50531244],
       [0.47585204],
       [0.8036761 ],
       [0.47904006],
       [0.39351845],
       [0.5301582 ],
       [0.7588706 ],
       [0.521733  ],
       [0.4218115 ],
       [0.509047  ],
       [0.8278302 ],
       [0.78787506],
       [0.52356994],
       [0.7504655 ],
       [0.7479794 ],
       [0.6543957 ],
       [0.44567308],
       [0.76094186],
       [0.69230765],
       [0.46550244],
       [0.52935445],
       [0.83462715],
       [0.6403837 ],
       [0.5612159 ],
       [0.8210285 ],
       [0.62783146],
       [0.53830564],
       [0.8814796 ],
       [0.7891703 ],
       [0.478911  ],
       [0.54592925],
       [0.58836997],
       [0.8227098 ],
       [0.73743725],
       [0.77715665],
       [0.7970686 ],
       [0.56245744],
       [0.50333333],
       [0.63651335],
       [0.90941155],
       [0.8237122 ],
       [0.57418776],
       [0.53481096],
       [0.645977  ],
       [0.6638901 ],
       [0.8919242 ],
       [0.6902967 ],
       [0.4726176 ],
       [0.5793165 ],
       [0.7698548 ],
       [0.7634615 ],
       [0.59660584],
       [0.6791738 ],
       [0.8741658 ],
       [0.545992  ],
       [0.38335517],
       [0.5537212 ],
       [0.9503088 ],
       [0.58388835],
       [0.4267216 ],
       [0.50210154],
       [0.8703979 ],
       [0.56407154],
       [0.48173943],
       [0.6226742 ],
       [0.8829634 ],
       [0.62463504],
       [0.4317641 ],
       [0.49582934],
       [0.66263866],
       [0.89153576],
       [0.7026988 ],
       [0.4435763 ],
       [0.47532707],
       [0.9414385 ],
       [0.58814615],
       [0.37383285],
       [0.45814845],
       [0.9044496 ],
       [0.5723528 ],
       [0.30708954],
       [0.5214797 ],
       [0.9321867 ],
       [0.600072  ],
       [0.3966978 ],
       [0.47444233],
       [0.7041277 ],
       [0.61809534],
       [0.40003946],
       [0.5167477 ],
       [0.77561235],
       [0.58383775],
       [0.58371687],
       [0.543888  ],
       [0.6174613 ],
       [0.6037643 ],
       [0.597052  ],
       [0.5274121 ],
       [0.5177893 ],
       [0.58713824],
       [0.5394529 ],
       [0.4463791 ],
       [0.4882197 ],
       [0.531127  ],
       [0.5203731 ],
       [0.41424733],
       [0.44578722],
       [0.5316748 ],
       [0.5496577 ],
       [0.43260953],
       [0.7194481 ],
       [0.4746754 ],
       [0.3180634 ],
       [0.40176326],
       [0.73295593],
       [0.5367415 ],
       [0.34826872],
       [0.4128762 ],
       [0.7762098 ],
       [0.6928271 ],
       [0.50864977],
       [0.45277166],
       [0.41393217],
       [0.48583266],
       [0.7699727 ],
       [0.7550478 ],
       [0.64658034],
       [0.6378588 ],
       [0.6802845 ],
       [0.7068166 ],
       [0.65988535],
       [0.7270265 ],
       [0.6150431 ],
       [0.5933188 ],
       [0.793764  ],
       [0.7503842 ],
       [0.6868646 ],
       [0.8965316 ],
       [0.852109  ],
       [0.5447024 ],
       [0.8176224 ],
       [0.7820407 ],
       [0.43900704],
       [0.8039499 ],
       [0.6349373 ],
       [0.3726274 ],
       [0.5525156 ],
       [0.91645616],
       [0.68626964],
       [0.5309203 ],
       [0.6432111 ],
       [0.91560423],
       [0.68575263],
       [0.59049684],
       [0.7216281 ],
       [0.6036448 ],
       [0.622616  ],
       [0.7124517 ],
       [0.5691588 ],
       [0.5406121 ],
       [0.62636113],
       [0.8958749 ],
       [0.7329328 ],
       [0.48506403],
       [0.83284026],
       [0.78596604],
       [0.5107973 ],
       [0.5383463 ],
       [0.82641774],
       [0.7815608 ],
       [0.64357233],
       [0.63443005],
       [0.6415545 ],
       [0.75699604],
       [0.7274151 ],
       [0.738377  ],
       [0.78648937],
       [0.7535474 ],
       [0.64127946],
       [0.6330582 ],
       [0.9432302 ],
       [0.81848466],
       [0.8008778 ],
       [0.80946964],
       [0.60466653],
       [0.53273636],
       [0.622811  ],
       [0.9024094 ],
       [0.61000514],
       [0.5595008 ],
       [0.6702248 ],
       [0.92716664],
       [0.7041684 ],
       [0.5838027 ],
       [0.520274  ],
       [0.5703415 ],
       [0.8979424 ],
       [0.64921975],
       [0.47637793],
       [0.40908065],
       [0.6830193 ]], dtype=float32)

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
14609     21617.0  24312.477855  25032.668096           NaN
14610     20399.0  21363.704588  20701.133338           NaN
14611     17247.0  16662.192043  15987.507201           NaN
14612      6569.0   6329.374684   7427.492492           NaN
14613       227.0    374.941399       349.495           NaN
...           ...           ...           ...           ...
18281     25386.0  26751.870947  26019.654367  26938.273438
18282     22872.0   23370.96659  22637.749887  19476.591797
18283     15825.0  15084.108971  16064.234452  14291.337891
18284      1450.0   1894.938407   2119.455433  12272.419922
18285         0.0           0.0      0.077852  20490.578125

[697 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,601 (1.55 MB)

 Trainable params: 405,345 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 549s 560ms/step - loss: 0.1648 - mae: 0.4687 - val_loss: 0.0989 - val_mae: 0.3939
Epoch 2/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 215s 523ms/step - loss: 0.1131 - mae: 0.3854 - val_loss: 0.0422 - val_mae: 0.2320
Epoch 3/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 269s 529ms/step - loss: 0.0902 - mae: 0.3417 - val_loss: 0.0293 - val_mae: 0.2017
Epoch 4/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 262s 514ms/step - loss: 0.0795 - mae: 0.3201 - val_loss: 0.0236 - val_mae: 0.1771
Epoch 5/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 275s 533ms/step - loss: 0.0709 - mae: 0.3021 - val_loss: 0.0193 - val_mae: 0.1556
Epoch 6/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 259s 509ms/step - loss: 0.0619 - mae: 0.2743 - val_loss: 0.0170 - val_mae: 0.1400
Epoch 7/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 247s 461ms/step - loss: 0.0565 - mae: 0.2571 - val_loss: 0.0160 - val_mae: 0.1335
Epoch 8/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 192s 426ms/step - loss: 0.0548 - mae: 0.2547 - val_loss: 0.0154 - val_mae: 0.1225
Epoch 9/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 193s 392ms/step - loss: 0.0514 - mae: 0.2396 - val_loss: 0.0181 - val_mae: 0.1422
Epoch 10/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 159s 384ms/step - loss: 0.0489 - mae: 0.2335 - val_loss: 0.0126 - val_mae: 0.1112
Epoch 11/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 239s 464ms/step - loss: 0.0484 - mae: 0.2378 - val_loss: 0.0141 - val_mae: 0.1227
Epoch 12/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 194s 467ms/step - loss: 0.0462 - mae: 0.2302 - val_loss: 0.0123 - val_mae: 0.1096
Epoch 13/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 224s 507ms/step - loss: 0.0450 - mae: 0.2228 - val_loss: 0.0148 - val_mae: 0.1148
Epoch 14/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 271s 517ms/step - loss: 0.0461 - mae: 0.2268 - val_loss: 0.0129 - val_mae: 0.1078
Epoch 15/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 185s 448ms/step - loss: 0.0447 - mae: 0.2240 - val_loss: 0.0239 - val_mae: 0.1313
Epoch 16/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 169s 404ms/step - loss: 0.0380 - mae: 0.2025 - val_loss: 0.0176 - val_mae: 0.1181
Epoch 17/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 187s 449ms/step - loss: 0.0385 - mae: 0.2002 - val_loss: 0.0232 - val_mae: 0.1270
Epoch 18/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 181s 447ms/step - loss: 0.0356 - mae: 0.1946 - val_loss: 0.0126 - val_mae: 0.1040
Epoch 19/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 189s 400ms/step - loss: 0.0367 - mae: 0.1953 - val_loss: 0.0121 - val_mae: 0.1037
Epoch 20/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 234s 466ms/step - loss: 0.0327 - mae: 0.1859 - val_loss: 0.0272 - val_mae: 0.1408
Epoch 21/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 184s 405ms/step - loss: 0.0322 - mae: 0.1803 - val_loss: 0.0218 - val_mae: 0.1260
Epoch 22/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 191s 463ms/step - loss: 0.0302 - mae: 0.1766 - val_loss: 0.0147 - val_mae: 0.1146
Epoch 23/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 205s 457ms/step - loss: 0.0299 - mae: 0.1770 - val_loss: 0.0262 - val_mae: 0.1396
Epoch 24/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 184s 402ms/step - loss: 0.0329 - mae: 0.1861 - val_loss: 0.0133 - val_mae: 0.1072
Epoch 25/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 212s 414ms/step - loss: 0.0316 - mae: 0.1817 - val_loss: 0.0136 - val_mae: 0.1042
Epoch 26/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 179s 427ms/step - loss: 0.0313 - mae: 0.1821 - val_loss: 0.0131 - val_mae: 0.1064
Epoch 27/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 179s 430ms/step - loss: 0.0301 - mae: 0.1732 - val_loss: 0.0245 - val_mae: 0.1343
Epoch 28/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 179s 364ms/step - loss: 0.0265 - mae: 0.1642 - val_loss: 0.0134 - val_mae: 0.1118
Epoch 29/100
401/401 ━━━━━━━━━━━━━━━━━━━━ 212s 372ms/step - loss: 0.0271 - mae: 0.1680 - val_loss: 0.0145 - val_mae: 0.1108

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

21/21 ━━━━━━━━━━━━━━━━━━━━ 70s 2s/step

array([[0.        ],
       [0.        ],
       [0.77839005],
       [0.7316328 ],
       [0.75527555],
       [0.8038016 ],
       [0.76146895],
       [0.7211652 ],
       [0.64035994],
       [0.37215838],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.57861173],
       [0.62578595],
       [0.69638985],
       [0.6923325 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.7432423 ],
       [0.78991807],
       [0.80969614],
       [0.8199906 ],
       [0.6786061 ],
       [0.52533215],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.6226164 ],
       [0.8046098 ],
       [0.7970454 ],
       [0.82858855],
       [0.80587286],
       [0.7183381 ],
       [0.4957407 ],
       [0.        ],
       [0.27093333],
       [0.7703099 ],
       [0.8251013 ],
       [0.75843847],
       [0.6297493 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.7148011 ],
       [0.5984097 ],
       [0.73633635],
       [0.77449626],
       [0.80472344],
       [0.45740515],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.06112352],
       [0.8288373 ],
       [0.7993317 ],
       [0.79312974],
       [0.7497458 ],
       [0.24111359],
       [0.        ],
       [0.        ],
       [0.82819635],
       [0.86271316],
       [0.8447896 ],
       [0.3449861 ],
       [0.        ],
       [0.        ],
       [0.80944777],
       [0.83882076],
       [0.8518842 ],
       [0.82164335],
       [0.80716467],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.7111407 ],
       [0.3469681 ],
       [0.73118293],
       [0.6219943 ],
       [0.75952536],
       [0.82536   ],
       [0.81217986],
       [0.6816881 ],
       [0.39255834],
       [0.        ],
       [0.        ],
       [0.5710047 ],
       [0.8557939 ],
       [0.824748  ],
       [0.35840303],
       [0.        ],
       [0.        ],
       [0.8607325 ],
       [0.8695099 ],
       [0.8352335 ],
       [0.48558855],
       [0.        ],
       [0.        ],
       [0.8069331 ],
       [0.8659388 ],
       [0.8230271 ],
       [0.39482266],
       [0.        ],
       [0.        ],
       [0.7956396 ],
       [0.8598624 ],
       [0.79817826],
       [0.39270383],
       [0.        ],
       [0.        ],
       [0.8060118 ],
       [0.867366  ],
       [0.83696365],
       [0.32913768],
       [0.        ],
       [0.        ],
       [0.83670354],
       [0.8799132 ],
       [0.8471847 ],
       [0.4858362 ],
       [0.        ],
       [0.        ],
       [0.8266683 ],
       [0.8691909 ],
       [0.83312494],
       [0.47816414],
       [0.        ],
       [0.        ],
       [0.8531753 ],
       [0.86429644],
       [0.8119214 ],
       [0.7437095 ],
       [0.33256382],
       [0.        ],
       [0.        ],
       [0.7797455 ],
       [0.8408716 ],
       [0.82300705],
       [0.76878226],
       [0.22470924],
       [0.        ],
       [0.        ],
       [0.7523074 ],
       [0.8473716 ],
       [0.8399329 ],
       [0.73454   ],
       [0.13258478],
       [0.        ],
       [0.        ],
       [0.70287037],
       [0.8116594 ],
       [0.79528147],
       [0.8016819 ],
       [0.6965903 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.762895  ],
       [0.84094346],
       [0.7510584 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.742808  ],
       [0.8578422 ],
       [0.79966295],
       [0.37945336],
       [0.        ],
       [0.        ],
       [0.733883  ],
       [0.873945  ],
       [0.82491523],
       [0.5449664 ],
       [0.        ],
       [0.        ],
       [0.76163906],
       [0.8929807 ],
       [0.83402896],
       [0.5034048 ],
       [0.        ],
       [0.        ],
       [0.77584213],
       [0.8709198 ],
       [0.8372393 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.82031   ],
       [0.8417945 ],
       [0.8304924 ],
       [0.8618607 ],
       [0.78168344],
       [0.22751434],
       [0.        ],
       [0.        ],
       [0.728747  ],
       [0.82105076],
       [0.8106602 ],
       [0.82248414],
       [0.7049868 ],
       [0.22653407],
       [0.        ],
       [0.        ],
       [0.6750296 ],
       [0.8266494 ],
       [0.8209152 ],
       [0.8158677 ],
       [0.7647119 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.55061543],
       [0.8403732 ],
       [0.8222892 ],
       [0.83027947],
       [0.7937315 ],
       [0.09119919],
       [0.        ],
       [0.        ],
       [0.65699846],
       [0.86616486],
       [0.816977  ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.7557833 ],
       [0.8702953 ],
       [0.77829874],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.71206415],
       [0.8664924 ],
       [0.8248194 ],
       [0.5667797 ],
       [0.46241486],
       [0.737502  ],
       [0.8065757 ],
       [0.85199744],
       [0.7831012 ],
       [0.5489628 ],
       [0.18447416],
       [0.        ],
       [0.7638922 ],
       [0.8415158 ],
       [0.7662518 ],
       [0.48216522],
       [0.        ],
       [0.        ],
       [0.74661857],
       [0.83523995],
       [0.7563367 ],
       [0.1686564 ],
       [0.        ],
       [0.        ],
       [0.69381094],
       [0.8352987 ],
       [0.71859336],
       [0.2817753 ],
       [0.        ],
       [0.        ],
       [0.7742154 ],
       [0.82980245],
       [0.7472822 ],
       [0.24103177],
       [0.        ],
       [0.21934816],
       [0.7552854 ],
       [0.8158855 ],
       [0.67040694],
       [0.24699172],
       [0.        ],
       [0.        ],
       [0.729941  ],
       [0.82881063],
       [0.74491507],
       [0.27627236],
       [0.        ],
       [0.        ],
       [0.66560704],
       [0.8483811 ],
       [0.7697458 ],
       [0.28688878],
       [0.        ],
       [0.        ],
       [0.6363433 ],
       [0.8694271 ],
       [0.80428946],
       [0.38337773],
       [0.        ],
       [0.        ],
       [0.7241136 ],
       [0.8570499 ],
       [0.87032396],
       [0.8609014 ],
       [0.77163494],
       [0.62593305],
       [0.23091584],
       [0.        ],
       [0.676996  ],
       [0.8048255 ],
       [0.75741696],
       [0.72229576],
       [0.74299043],
       [0.7752495 ],
       [0.7730914 ],
       [0.8064358 ],
       [0.71957684],
       [0.5665719 ],
       [0.5591891 ],
       [0.7953402 ],
       [0.71930325],
       [0.6151497 ],
       [0.76629084],
       [0.7191634 ],
       [0.62756765],
       [0.626413  ],
       [0.7170242 ],
       [0.6797642 ],
       [0.6912611 ],
       [0.72362775],
       [0.7811565 ],
       [0.7276742 ],
       [0.6514215 ],
       [0.7630763 ],
       [0.69881076],
       [0.5946296 ],
       [0.5606618 ],
       [0.7686482 ],
       [0.55314994],
       [0.42266095],
       [0.23716749],
       [0.61726093],
       [0.54833543],
       [0.403373  ],
       [0.34109533],
       [0.20583695],
       [0.3365345 ],
       [0.6957389 ],
       [0.52745676],
       [0.25330734],
       [0.        ],
       [0.5012354 ],
       [0.72420895],
       [0.6510044 ],
       [0.5663482 ],
       [0.40592718],
       [0.6557903 ],
       [0.76687896],
       [0.6817796 ],
       [0.5036966 ],
       [0.35565835],
       [0.6430779 ],
       [0.7447566 ],
       [0.69074947],
       [0.6915395 ],
       [0.6837868 ],
       [0.61007416],
       [0.6127917 ],
       [0.64542556],
       [0.6240378 ],
       [0.6652102 ],
       [0.5074046 ],
       [0.48967594],
       [0.5346462 ],
       [0.6319515 ],
       [0.48124123],
       [0.45644927],
       [0.518432  ],
       [0.60142255],
       [0.50899714],
       [0.5726383 ],
       [0.58834857],
       [0.63847625],
       [0.5929076 ],
       [0.38941634],
       [0.35610503],
       [0.6775468 ],
       [0.59919626],
       [0.5542014 ],
       [0.68835247],
       [0.64699984],
       [0.5799466 ],
       [0.63646823],
       [0.55668676],
       [0.5252059 ],
       [0.5343785 ],
       [0.59092367],
       [0.6392661 ],
       [0.6528299 ],
       [0.6662572 ],
       [0.55441225],
       [0.4414953 ],
       [0.4497379 ],
       [0.65565896],
       [0.6153074 ],
       [0.5853045 ],
       [0.68435585],
       [0.6146467 ],
       [0.47543842],
       [0.5134248 ],
       [0.70967954],
       [0.6417513 ],
       [0.46177304],
       [0.42428136],
       [0.731302  ],
       [0.6183825 ],
       [0.40122712],
       [0.4131552 ],
       [0.7526155 ],
       [0.6221869 ],
       [0.26345217],
       [0.        ],
       [0.29106826],
       [0.78718245],
       [0.72925705],
       [0.4848894 ],
       [0.05611432],
       [0.5995119 ],
       [0.82131064],
       [0.7146611 ],
       [0.520196  ],
       [0.35673776],
       [0.78832823],
       [0.6904716 ],
       [0.4583075 ],
       [0.        ],
       [0.42616558],
       [0.7421216 ],
       [0.7856706 ],
       [0.69622874],
       [0.6260606 ],
       [0.4669912 ],
       [0.        ],
       [0.25171164],
       [0.73710877],
       [0.77751905],
       [0.72466934],
       [0.43007767],
       [0.21038935],
       [0.62481713],
       [0.78547907],
       [0.70530605],
       [0.5395782 ],
       [0.6049341 ],
       [0.7800996 ],
       [0.67258435],
       [0.43474334],
       [0.4781741 ],
       [0.7651697 ],
       [0.65899587],
       [0.24324304],
       [0.5094291 ],
       [0.7817943 ],
       [0.71604216],
       [0.66047543],
       [0.7459307 ],
       [0.71921   ],
       [0.6790691 ],
       [0.5954645 ],
       [0.7657998 ],
       [0.71007776],
       [0.5405288 ],
       [0.5457343 ],
       [0.75648123],
       [0.6452013 ],
       [0.5795488 ],
       [0.7416487 ],
       [0.6322101 ],
       [0.53273314],
       [0.7692174 ],
       [0.7480167 ],
       [0.68814987],
       [0.6119843 ],
       [0.5346914 ],
       [0.7840062 ],
       [0.77434385],
       [0.75379145],
       [0.70622504],
       [0.5873459 ],
       [0.51563686],
       [0.50679034],
       [0.75565743],
       [0.7170858 ],
       [0.53954804],
       [0.25963277],
       [0.33650154],
       [0.36916876],
       [0.7132832 ],
       [0.57836497],
       [0.433515  ],
       [0.25951576],
       [0.25625497],
       [0.7370143 ],
       [0.63754165],
       [0.48869324],
       [0.7186324 ],
       [0.60157937],
       [0.25123405],
       [0.25900468],
       [0.76936716],
       [0.6748661 ],
       [0.50969267],
       [0.5840611 ],
       [0.76613337],
       [0.65872556],
       [0.4437775 ],
       [0.42958564],
       [0.7853703 ],
       [0.67942417],
       [0.44645286],
       [0.25888374],
       [0.72010964],
       [0.79287636],
       [0.74015176],
       [0.52113426],
       [0.38555574],
       [0.78017324],
       [0.71719086],
       [0.4907561 ],
       [0.36292893],
       [0.7986325 ],
       [0.72546864],
       [0.3993724 ],
       [0.583047  ],
       [0.7990401 ],
       [0.6864696 ],
       [0.29456365],
       [0.45170087],
       [0.7458136 ],
       [0.5340747 ],
       [0.3556425 ],
       [0.4135326 ],
       [0.7119125 ],
       [0.55156547],
       [0.5503847 ],
       [0.4644671 ],
       [0.52949077],
       [0.5359299 ],
       [0.56752604],
       [0.3546297 ],
       [0.30721414],
       [0.43791378],
       [0.45219445],
       [0.4475069 ],
       [0.41952807],
       [0.4120254 ],
       [0.4319334 ],
       [0.4283371 ],
       [0.4972142 ],
       [0.5028182 ],
       [0.53576994],
       [0.48785746],
       [0.56234235],
       [0.44726288],
       [0.28033894],
       [0.2930136 ],
       [0.6834608 ],
       [0.5920252 ],
       [0.43452156],
       [0.30488938],
       [0.74076223],
       [0.6955844 ],
       [0.6546736 ],
       [0.5545526 ],
       [0.31903905],
       [0.34405512],
       [0.7380787 ],
       [0.6747993 ],
       [0.7043755 ],
       [0.67452985],
       [0.6467661 ],
       [0.6915385 ],
       [0.66775155],
       [0.6984849 ],
       [0.6634408 ],
       [0.65189594],
       [0.6709359 ],
       [0.66133684],
       [0.6707285 ],
       [0.6760614 ],
       [0.63140047],
       [0.55674833],
       [0.6800855 ],
       [0.6285563 ],
       [0.50315017],
       [0.68205833],
       [0.63716686],
       [0.44139326],
       [0.58246195],
       [0.7215568 ],
       [0.63994306],
       [0.47007883],
       [0.61030805],
       [0.7457788 ],
       [0.628718  ],
       [0.5518232 ],
       [0.72840804],
       [0.5542894 ],
       [0.50722766],
       [0.7364335 ],
       [0.58382446],
       [0.2963122 ],
       [0.5964122 ],
       [0.75851434],
       [0.6583264 ],
       [0.6038706 ],
       [0.73325974],
       [0.6607722 ],
       [0.5578964 ],
       [0.45340174],
       [0.7487861 ],
       [0.71842915],
       [0.6858535 ],
       [0.6643381 ],
       [0.6129896 ],
       [0.7412633 ],
       [0.73377633],
       [0.7323612 ],
       [0.7219771 ],
       [0.6794904 ],
       [0.63393193],
       [0.6446764 ],
       [0.76566154],
       [0.75800776],
       [0.7465525 ],
       [0.7322784 ],
       [0.6370472 ],
       [0.49072456],
       [0.63450754],
       [0.76392627],
       [0.6506393 ],
       [0.47984153],
       [0.63342667],
       [0.79045826],
       [0.75504476],
       [0.6175897 ],
       [0.25248384],
       [0.5136073 ],
       [0.7854109 ],
       [0.76195216],
       [0.6124265 ],
       [0.21774027],
       [0.2348963 ]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
14609     21617.0  24312.477855  25032.668096           NaN           NaN
14610     20399.0  21363.704588  20701.133338           NaN           NaN
14611     17247.0  16662.192043  15987.507201           NaN           NaN
14612      6569.0   6329.374684   7427.492492           NaN           NaN
14613       227.0    374.941399       349.495           NaN           NaN
...           ...           ...           ...           ...           ...
18281     25386.0  26751.870947  26019.654367  26938.273438  23562.326172
18282     22872.0   23370.96659  22637.749887  19476.591797  22858.564453
18283     15825.0  15084.108971  16064.234452  14291.337891  18372.794922
18284      1450.0   1894.938407   2119.455433  12272.419922   6532.208008
18285         0.0           0.0      0.077852  20490.578125   7046.889160

[697 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

14734        0.0
14746    17123.0
14747    21577.0
14748    22396.0
14749    19811.0
          ...
18281    25386.0
18282    22872.0
18283    15825.0
18284     1450.0
18285        0.0
Name: Generación, Length: 649, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 6)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      1,600 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 473,281 (1.81 MB)

 Trainable params: 473,281 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 313s 288ms/step - loss: 1.1948 - mae: 0.3311 - val_loss: 0.7217 - val_mae: 0.3413
Epoch 2/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 52s 122ms/step - loss: 0.6148 - mae: 0.3000 - val_loss: 0.3851 - val_mae: 0.2907
Epoch 3/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 61s 208ms/step - loss: 0.3141 - mae: 0.2214 - val_loss: 0.1768 - val_mae: 0.1431
Epoch 4/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 53s 231ms/step - loss: 0.1675 - mae: 0.1585 - val_loss: 0.1076 - val_mae: 0.1308
Epoch 5/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 77s 189ms/step - loss: 0.1040 - mae: 0.1397 - val_loss: 0.0737 - val_mae: 0.1271
Epoch 6/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 38s 155ms/step - loss: 0.0781 - mae: 0.1462 - val_loss: 0.0541 - val_mae: 0.1182
Epoch 7/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 55s 205ms/step - loss: 0.0619 - mae: 0.1362 - val_loss: 0.0458 - val_mae: 0.1182
Epoch 8/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 94s 241ms/step - loss: 0.0495 - mae: 0.1263 - val_loss: 0.0376 - val_mae: 0.1111
Epoch 9/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 67s 149ms/step - loss: 0.0464 - mae: 0.1289 - val_loss: 0.0342 - val_mae: 0.1136
Epoch 10/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 46s 163ms/step - loss: 0.0403 - mae: 0.1231 - val_loss: 0.0315 - val_mae: 0.1118
Epoch 11/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 54s 205ms/step - loss: 0.0386 - mae: 0.1237 - val_loss: 0.0274 - val_mae: 0.1076
Epoch 12/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 43s 193ms/step - loss: 0.0341 - mae: 0.1180 - val_loss: 0.0301 - val_mae: 0.1183
Epoch 13/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 39s 175ms/step - loss: 0.0343 - mae: 0.1199 - val_loss: 0.0299 - val_mae: 0.1198
Epoch 14/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 48s 189ms/step - loss: 0.0325 - mae: 0.1187 - val_loss: 0.0240 - val_mae: 0.1047
Epoch 15/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 30s 122ms/step - loss: 0.0295 - mae: 0.1122 - val_loss: 0.0295 - val_mae: 0.1223
Epoch 16/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 60s 198ms/step - loss: 0.0294 - mae: 0.1133 - val_loss: 0.0264 - val_mae: 0.1146
Epoch 17/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 68s 116ms/step - loss: 0.0313 - mae: 0.1182 - val_loss: 0.0243 - val_mae: 0.1035
Epoch 18/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 62s 199ms/step - loss: 0.0275 - mae: 0.1090 - val_loss: 0.0279 - val_mae: 0.1182
Epoch 19/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 44s 189ms/step - loss: 0.0299 - mae: 0.1162 - val_loss: 0.0230 - val_mae: 0.1008
Epoch 20/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 34s 137ms/step - loss: 0.0274 - mae: 0.1096 - val_loss: 0.0208 - val_mae: 0.0992
Epoch 21/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 47s 163ms/step - loss: 0.0255 - mae: 0.1079 - val_loss: 0.0208 - val_mae: 0.0985
Epoch 22/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 52s 199ms/step - loss: 0.0254 - mae: 0.1051 - val_loss: 0.0206 - val_mae: 0.0971
Epoch 23/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 36s 154ms/step - loss: 0.0243 - mae: 0.1043 - val_loss: 0.0251 - val_mae: 0.1099
Epoch 24/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 32s 149ms/step - loss: 0.0253 - mae: 0.1067 - val_loss: 0.0205 - val_mae: 0.1000
Epoch 25/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 59s 213ms/step - loss: 0.0247 - mae: 0.1056 - val_loss: 0.0196 - val_mae: 0.0941
Epoch 26/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 46s 195ms/step - loss: 0.0233 - mae: 0.1017 - val_loss: 0.0206 - val_mae: 0.0958
Epoch 27/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 40s 172ms/step - loss: 0.0235 - mae: 0.1026 - val_loss: 0.0205 - val_mae: 0.0990
Epoch 28/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 48s 188ms/step - loss: 0.0220 - mae: 0.0997 - val_loss: 0.0201 - val_mae: 0.0995
Epoch 29/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 45s 188ms/step - loss: 0.0223 - mae: 0.1000 - val_loss: 0.0241 - val_mae: 0.1065
Epoch 30/50
201/201 ━━━━━━━━━━━━━━━━━━━━ 44s 181ms/step - loss: 0.0231 - mae: 0.0990 - val_loss: 0.0207 - val_mae: 0.0948

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

21/21 ━━━━━━━━━━━━━━━━━━━━ 28s 685ms/step

array([[0.00851196],
       [0.429486  ],
       [0.7655398 ],
       [0.74209803],
       [0.7376799 ],
       [0.7590738 ],
       [0.7907348 ],
       [0.8023163 ],
       [0.7716597 ],
       [0.67604625],
       [0.47289535],
       [0.16891873],
       [0.00713791],
       [0.00846365],
       [0.29486433],
       [0.57771295],
       [0.65203995],
       [0.713242  ],
       [0.73109394],
       [0.66442245],
       [0.34734085],
       [0.03475136],
       [0.01746897],
       [0.37449226],
       [0.67329645],
       [0.7451466 ],
       [0.7475993 ],
       [0.77037007],
       [0.7185883 ],
       [0.63711405],
       [0.593696  ],
       [0.09774473],
       [0.00961406],
       [0.47990647],
       [0.75913084],
       [0.8065916 ],
       [0.78937525],
       [0.7334015 ],
       [0.6701183 ],
       [0.45070025],
       [0.02541204],
       [0.3537065 ],
       [0.71692103],
       [0.7793214 ],
       [0.7750149 ],
       [0.65354806],
       [0.09210671],
       [0.01080937],
       [0.05860504],
       [0.7015324 ],
       [0.6295229 ],
       [0.70647985],
       [0.7984462 ],
       [0.8363853 ],
       [0.70167917],
       [0.21173307],
       [0.0126374 ],
       [0.00795758],
       [0.3522567 ],
       [0.8387875 ],
       [0.8373062 ],
       [0.78922373],
       [0.6242114 ],
       [0.24380495],
       [0.00910925],
       [0.01285479],
       [0.8415891 ],
       [0.80656785],
       [0.760858  ],
       [0.35159227],
       [0.00868204],
       [0.00589116],
       [0.7233915 ],
       [0.7976039 ],
       [0.8499047 ],
       [0.8076135 ],
       [0.8029684 ],
       [0.23930185],
       [0.01178615],
       [0.00611273],
       [0.5606198 ],
       [0.60431665],
       [0.66533816],
       [0.77890986],
       [0.832293  ],
       [0.8884422 ],
       [0.9302595 ],
       [0.77921396],
       [0.3242021 ],
       [0.00681419],
       [0.00653104],
       [0.38367283],
       [0.8707331 ],
       [0.77261955],
       [0.4995721 ],
       [0.01548471],
       [0.01825482],
       [0.8179464 ],
       [0.8391334 ],
       [0.7611744 ],
       [0.4287956 ],
       [0.01471686],
       [0.01992832],
       [0.76164955],
       [0.83597666],
       [0.7589172 ],
       [0.37741134],
       [0.01357009],
       [0.00752593],
       [0.76120836],
       [0.846157  ],
       [0.7099115 ],
       [0.32920694],
       [0.01630738],
       [0.01133272],
       [0.7426682 ],
       [0.8416961 ],
       [0.76806146],
       [0.4590567 ],
       [0.02757486],
       [0.00810381],
       [0.78471524],
       [0.86369526],
       [0.79730517],
       [0.46579626],
       [0.02239072],
       [0.00802446],
       [0.7880886 ],
       [0.8765048 ],
       [0.7962864 ],
       [0.47774896],
       [0.02336348],
       [0.01193855],
       [0.8395803 ],
       [0.91202897],
       [0.8550839 ],
       [0.71899515],
       [0.3459012 ],
       [0.01271462],
       [0.22450262],
       [0.8629622 ],
       [0.89296633],
       [0.8942646 ],
       [0.8294181 ],
       [0.43162256],
       [0.01328976],
       [0.02799231],
       [0.855112  ],
       [0.9219592 ],
       [0.8839038 ],
       [0.7235463 ],
       [0.2859812 ],
       [0.00666471],
       [0.02014649],
       [0.7848423 ],
       [0.8775628 ],
       [0.87995225],
       [0.82701665],
       [0.7211339 ],
       [0.15532334],
       [0.00875338],
       [0.03334475],
       [0.77913064],
       [0.77475876],
       [0.6651611 ],
       [0.17007253],
       [0.01544153],
       [0.02738211],
       [0.7202435 ],
       [0.7886369 ],
       [0.7365593 ],
       [0.3772296 ],
       [0.01652037],
       [0.00750289],
       [0.722525  ],
       [0.85981387],
       [0.7756219 ],
       [0.4533269 ],
       [0.01698478],
       [0.00530031],
       [0.71858424],
       [0.9084782 ],
       [0.7945168 ],
       [0.39534566],
       [0.01959223],
       [0.00924672],
       [0.7389414 ],
       [0.83621526],
       [0.75623095],
       [0.32189676],
       [0.03020426],
       [0.05161984],
       [0.8320023 ],
       [0.8651955 ],
       [0.92334205],
       [0.93015915],
       [0.8376908 ],
       [0.29221818],
       [0.01163991],
       [0.01847556],
       [0.8058998 ],
       [0.8377602 ],
       [0.8989675 ],
       [0.8833876 ],
       [0.7300601 ],
       [0.18712601],
       [0.01571083],
       [0.00591805],
       [0.72911394],
       [0.84884655],
       [0.9044964 ],
       [0.82922846],
       [0.7856457 ],
       [0.23658854],
       [0.0063987 ],
       [0.00484682],
       [0.5794832 ],
       [0.87477666],
       [0.91584176],
       [0.84820765],
       [0.76218206],
       [0.19752985],
       [0.00899326],
       [0.00790999],
       [0.6721663 ],
       [0.789432  ],
       [0.68142265],
       [0.30566475],
       [0.01359602],
       [0.00898279],
       [0.5707668 ],
       [0.8028926 ],
       [0.6709272 ],
       [0.24604459],
       [0.02268497],
       [0.01078494],
       [0.54552495],
       [0.7916027 ],
       [0.75928754],
       [0.5606486 ],
       [0.55203074],
       [0.87122834],
       [0.91755253],
       [0.90427226],
       [0.79397583],
       [0.4334629 ],
       [0.04763268],
       [0.4124677 ],
       [0.8997933 ],
       [0.84287804],
       [0.7375707 ],
       [0.4586086 ],
       [0.02940625],
       [0.18654552],
       [0.89033586],
       [0.86450607],
       [0.72874266],
       [0.1289966 ],
       [0.01954402],
       [0.04277879],
       [0.7840443 ],
       [0.7770534 ],
       [0.6864962 ],
       [0.29336676],
       [0.02854197],
       [0.34227517],
       [0.9284329 ],
       [0.8380198 ],
       [0.70242256],
       [0.23262031],
       [0.02570468],
       [0.43076578],
       [0.8927794 ],
       [0.792778  ],
       [0.62907875],
       [0.20319445],
       [0.0242606 ],
       [0.08154459],
       [0.8844176 ],
       [0.8028959 ],
       [0.70316833],
       [0.26175076],
       [0.01116869],
       [0.01041136],
       [0.70206016],
       [0.8155996 ],
       [0.74000293],
       [0.30587322],
       [0.01211627],
       [0.00627534],
       [0.57599926],
       [0.84089774],
       [0.7756395 ],
       [0.36654243],
       [0.01688797],
       [0.00631162],
       [0.74410635],
       [0.8962838 ],
       [0.96153575],
       [0.87984884],
       [0.85029846],
       [0.72251564],
       [0.48338053],
       [0.33853012],
       [0.8586173 ],
       [0.9123845 ],
       [0.80545264],
       [0.7167328 ],
       [0.9513795 ],
       [0.9744794 ],
       [1.005701  ],
       [1.0140489 ],
       [0.82001567],
       [0.48317483],
       [0.5913996 ],
       [0.8606947 ],
       [0.70131606],
       [0.5242835 ],
       [0.77731544],
       [0.7195061 ],
       [0.6333235 ],
       [0.7413108 ],
       [0.76920974],
       [0.76175255],
       [0.823697  ],
       [0.91504073],
       [0.9963488 ],
       [0.7795389 ],
       [0.6723282 ],
       [0.80056626],
       [0.6777855 ],
       [0.50608855],
       [0.63588744],
       [0.75298053],
       [0.42750123],
       [0.06909255],
       [0.21684888],
       [0.6414903 ],
       [0.5613926 ],
       [0.21016333],
       [0.08542317],
       [0.03803433],
       [0.18590152],
       [0.48665315],
       [0.527102  ],
       [0.25772256],
       [0.18660963],
       [0.51067644],
       [0.6712501 ],
       [0.5375698 ],
       [0.49346545],
       [0.5004448 ],
       [0.6914518 ],
       [0.788668  ],
       [0.6226726 ],
       [0.35686448],
       [0.4053174 ],
       [0.7988369 ],
       [0.8165789 ],
       [0.62081665],
       [0.68520004],
       [0.7558567 ],
       [0.77602285],
       [0.61789244],
       [0.6585893 ],
       [0.57768756],
       [0.626137  ],
       [0.3686421 ],
       [0.19175187],
       [0.3544983 ],
       [0.47471684],
       [0.29537782],
       [0.11941275],
       [0.28851095],
       [0.44819686],
       [0.41103354],
       [0.3624752 ],
       [0.5602753 ],
       [0.5582039 ],
       [0.5247565 ],
       [0.3091853 ],
       [0.38510412],
       [0.5857863 ],
       [0.567895  ],
       [0.5722161 ],
       [0.7129808 ],
       [0.63580304],
       [0.63015634],
       [0.68735474],
       [0.45015013],
       [0.38677925],
       [0.504159  ],
       [0.55878586],
       [0.6965557 ],
       [0.6862647 ],
       [0.7269605 ],
       [0.4810979 ],
       [0.2756866 ],
       [0.42070895],
       [0.6693167 ],
       [0.69856554],
       [0.6989055 ],
       [0.73662204],
       [0.5949778 ],
       [0.49564597],
       [0.6595163 ],
       [0.75203025],
       [0.6613558 ],
       [0.4309754 ],
       [0.56434137],
       [0.7800389 ],
       [0.6411602 ],
       [0.34107372],
       [0.5758401 ],
       [0.77890474],
       [0.64422244],
       [0.24065022],
       [0.03422445],
       [0.5568617 ],
       [0.83285934],
       [0.69870776],
       [0.38333416],
       [0.11047366],
       [0.79431385],
       [0.8694401 ],
       [0.70478386],
       [0.3909583 ],
       [0.41019955],
       [0.7834209 ],
       [0.69797045],
       [0.41609058],
       [0.0366611 ],
       [0.52257025],
       [0.88863796],
       [0.90814763],
       [0.7538296 ],
       [0.64990395],
       [0.46022505],
       [0.01622665],
       [0.29472134],
       [0.87450343],
       [0.85529715],
       [0.6884559 ],
       [0.39161325],
       [0.07775987],
       [0.76336235],
       [0.84174937],
       [0.6453633 ],
       [0.43083256],
       [0.75118417],
       [0.8206648 ],
       [0.6188268 ],
       [0.295684  ],
       [0.47953704],
       [0.7223286 ],
       [0.53593624],
       [0.22699955],
       [0.5853638 ],
       [0.8426844 ],
       [0.68002546],
       [0.7489391 ],
       [0.79261243],
       [0.76384336],
       [0.59477353],
       [0.6612094 ],
       [0.8048251 ],
       [0.68569064],
       [0.501945  ],
       [0.6607    ],
       [0.8172237 ],
       [0.60327744],
       [0.50488067],
       [0.7951239 ],
       [0.605437  ],
       [0.47661602],
       [0.85139453],
       [0.85966593],
       [0.7347626 ],
       [0.6485655 ],
       [0.6434553 ],
       [0.90033215],
       [0.9186789 ],
       [0.8466666 ],
       [0.8171273 ],
       [0.6543188 ],
       [0.47996342],
       [0.71839833],
       [0.8158668 ],
       [0.7754764 ],
       [0.52796406],
       [0.4184818 ],
       [0.42527363],
       [0.62009996],
       [0.66362184],
       [0.49587494],
       [0.31813595],
       [0.19449893],
       [0.48355046],
       [0.696446  ],
       [0.5923322 ],
       [0.49382195],
       [0.72644144],
       [0.51450354],
       [0.24464492],
       [0.43539736],
       [0.7547198 ],
       [0.6714459 ],
       [0.45459053],
       [0.79184884],
       [0.83574396],
       [0.62725264],
       [0.30146918],
       [0.46854147],
       [0.77810115],
       [0.6945359 ],
       [0.31734002],
       [0.4784235 ],
       [0.88676316],
       [0.9268996 ],
       [0.773257  ],
       [0.44397506],
       [0.55351067],
       [0.8878883 ],
       [0.7305904 ],
       [0.42448348],
       [0.50160027],
       [0.8806341 ],
       [0.7121364 ],
       [0.37903333],
       [0.77251995],
       [0.919668  ],
       [0.6885348 ],
       [0.25911427],
       [0.5928033 ],
       [0.8198211 ],
       [0.45860705],
       [0.21608353],
       [0.42740992],
       [0.7062693 ],
       [0.5382829 ],
       [0.39942273],
       [0.4989893 ],
       [0.44983912],
       [0.42815992],
       [0.47739345],
       [0.29116154],
       [0.14564894],
       [0.22776237],
       [0.42877445],
       [0.4455488 ],
       [0.38707742],
       [0.48236987],
       [0.453883  ],
       [0.42207113],
       [0.4753525 ],
       [0.51371247],
       [0.60749984],
       [0.6087719 ],
       [0.58776325],
       [0.36601207],
       [0.19581388],
       [0.38534814],
       [0.6519993 ],
       [0.5978789 ],
       [0.4472945 ],
       [0.54376316],
       [0.76619095],
       [0.78408825],
       [0.6768908 ],
       [0.6936631 ],
       [0.4410495 ],
       [0.63971084],
       [0.8095086 ],
       [0.7592488 ],
       [0.7428712 ],
       [0.75465924],
       [0.7195733 ],
       [0.78293985],
       [0.80347985],
       [0.86308604],
       [0.82834417],
       [0.8115231 ],
       [0.8627278 ],
       [0.87614596],
       [0.8787709 ],
       [0.9116505 ],
       [0.7299662 ],
       [0.65972334],
       [0.8445066 ],
       [0.69069964],
       [0.53524387],
       [0.7557146 ],
       [0.6469689 ],
       [0.434957  ],
       [0.7707644 ],
       [0.8582137 ],
       [0.6397119 ],
       [0.37126377],
       [0.7756082 ],
       [0.89193666],
       [0.61460084],
       [0.39509556],
       [0.7070357 ],
       [0.51139426],
       [0.39585662],
       [0.68486583],
       [0.47235355],
       [0.20758319],
       [0.7027078 ],
       [0.8134672 ],
       [0.61643887],
       [0.60143274],
       [0.7601784 ],
       [0.6214645 ],
       [0.43615106],
       [0.50757414],
       [0.7905168 ],
       [0.85049266],
       [0.7446001 ],
       [0.7938106 ],
       [0.65676516],
       [0.8762341 ],
       [0.9215359 ],
       [0.8846492 ],
       [0.8387937 ],
       [0.77289444],
       [0.74540955],
       [0.85749984],
       [0.94859064],
       [0.9551287 ],
       [0.84971946],
       [0.8347238 ],
       [0.65874785],
       [0.54636824],
       [0.8289172 ],
       [0.90056974],
       [0.6452875 ],
       [0.39455017],
       [0.79413086],
       [0.9137226 ],
       [0.80554837],
       [0.479225  ],
       [0.24372023],
       [0.7361043 ],
       [0.8525538 ],
       [0.7642378 ],
       [0.5042037 ],
       [0.16506097],
       [0.47807878]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
14609,21617.0,24312.477855,25032.668096,NaN,NaN,NaN
14610,20399.0,21363.704588,20701.133338,NaN,NaN,NaN
14611,17247.0,16662.192043,15987.507201,NaN,NaN,NaN
14612,6569.0,6329.374684,7427.492492,NaN,NaN,NaN
14613,227.0,374.941399,349.495,NaN,NaN,NaN
...,...,...,...,...,...,...
18281,25386.0,26751.870947,26019.654367,26938.273438,23562.326172,25576.613281
18282,22872.0,23370.96659,22637.749887,19476.591797,22858.564453,22927.134766
18283,15825.0,15084.108971,16064.234452,14291.337891,18372.794922,15126.110352
18284,1450.0,1894.938407,2119.455433,12272.419922,6532.208008,4951.829102
18285,0.0,0.0,0.077852,20490.578125,7046.889160,14342.363281

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1504.7843
RMSE: 2382.9166
R²: 0.9394
Random Forest
MAE: 1513.2853
RMSE: 2476.0689
R²: 0.9345
CTNET
MAE: 6632.2267
RMSE: 8413.6818
R²: 0.2375
Forecast
MAE: 4183.7473
RMSE: 5805.3628
R²: 0.6370
Photovoltaic
MAE: 3708.5321
RMSE: 5241.4415
R²: 0.7041

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

101/101 ━━━━━━━━━━━━━━━━━━━━ 15s 93ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

101/101 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

101/101 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
36,27523.885172,21365.227112,23981.312960,NaN,NaN,NaN
37,20596.278869,26648.355787,23474.697202,NaN,NaN,NaN
38,28500.000000,22480.825478,25083.710825,NaN,NaN,NaN
39,24647.568577,27450.230111,25678.095627,NaN,NaN,NaN
40,25500.000000,23918.077465,25129.541912,NaN,NaN,NaN
...,...,...,...,...,...,...
12596,792.000000,2535.317889,2228.205000,12075.732422,0.000000,1547.947144
12597,0.000000,0.000000,0.000000,9251.398438,0.000000,102.846786
12598,0.000000,95.412834,0.000000,16431.587891,0.000000,383.516602
12612,20033.000000,21501.104937,19819.580000,23643.132812,24218.046875,23807.849609
12613,19733.000000,19555.414672,19914.145000,30000.000000,23740.185547,26140.939453

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1055.3486
RMSE: 1926.5182
R²: 0.9670
Random Forest
MAE: 379.4911
RMSE: 732.1718
R²: 0.9952
CTNET
MAE: 6804.4540
RMSE: 8648.7357
R²: 0.3370
Forecast
MAE: 4186.9731
RMSE: 6044.1702
R²: 0.6762
Photovoltaic
MAE: 2798.8321
RMSE: 4274.4204
R²: 0.8381

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.11_Predicciones_Conjunto_nublado GMM CTNET.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_11_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_11_RandomForest_model.pkl")

['4_11_RandomForest_model.pkl']

In [87]:
CTNET.save("4_11_CTNET_model.keras")
Forecast_model.save("4_11_Forecast_model.keras")
Photo_model.save("4_11_Photo_model.keras")