# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,7,77,0,4,15,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,7,82,0,4,16,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,9,85,0,3,16,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,11,87,0,3,16,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,11,88,0,3,16,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,15,86,0,3,14,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,47,89,0,3,16,6,Nublado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,51,95,0,4,17,7,Nublado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,47,100,0,3,18,8,Nublado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,5,100,1,4,18,9,Nublado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,5,93,2,4,18,10,Nublado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,5,79,2,4,17,11,Nublado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,5,64,6,3,15,12,Nublado,Lluvioso
13,2022-09-01 13:00:00,25478.471342,23,5,51,11,3,13,13,Soleado,Lluvioso
14,2022-09-01 14:00:00,29057.585772,25,3,41,12,1,11,14,Soleado,Lluvioso
15,2022-09-01 15:00:00,30000.000000,26,0,35,11,1,9,15,Soleado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,0,33,8,1,9,16,Soleado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,0,34,5,1,11,17,Soleado,Soleado
18,2022-09-01 18:00:00,29900.303971,27,0,37,3,2,11,18,Soleado,Soleado
19,2022-09-01 19:00:00,18282.505369,26,0,41,2,3,12,19,Soleado,Soleado
20,2022-09-01 20:00:00,3411.083740,24,2,48,0,3,12,20,Nublado,Lluvioso
21,2022-09-01 21:00:00,382.187718,22,6,55,0,3,13,21,Nublado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,6,61,0,4,13,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,6,68,0,4,14,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster KMeans"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
30,2022-09-02 06:00:00,0.000000,17,7,91,0,4,15,6,Nublado,Lluvioso,0.000000,0.000000
31,2022-09-02 07:00:00,0.000000,17,7,94,0,3,16,7,Nublado,Lluvioso,0.000000,6.584959
32,2022-09-02 08:00:00,438.814997,16,5,97,0,3,15,8,Nublado,Lluvioso,0.000000,560.422022
33,2022-09-02 09:00:00,5908.000884,17,0,93,1,2,16,9,Nublado,Lluvioso,438.814997,7720.582326
34,2022-09-02 10:00:00,5030.740421,18,0,85,2,2,15,10,Nublado,Lluvioso,5908.000884,9433.109309
39,2022-09-02 15:00:00,24647.568577,26,7,33,5,4,8,15,Nublado,Lluvioso,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,7,34,4,4,9,16,Nublado,Lluvioso,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,7,36,2,4,12,17,Nublado,Lluvioso,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,7,39,1,4,12,18,Nublado,Lluvioso,24281.956494,29900.303971
43,2022-09-02 19:00:00,11972.590689,25,7,44,1,4,12,19,Nublado,Lluvioso,22733.515002,18282.505369

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,17,7,91,0,4,15,6,0.000000,0.000000
31,17,7,94,0,3,16,7,0.000000,6.584959
32,16,5,97,0,3,15,8,0.000000,560.422022
33,17,0,93,1,2,16,9,438.814997,7720.582326
34,18,0,85,2,2,15,10,5908.000884,9433.109309
...,...,...,...,...,...,...,...,...,...
18273,14,0,87,1,4,11,8,67.000000,7302.000000
18274,15,0,83,2,4,12,9,7356.000000,18014.000000
18275,17,0,71,4,3,12,10,17638.000000,23010.000000
18276,19,0,60,5,3,11,11,23339.000000,26156.000000
18278,23,0,44,7,4,10,13,26277.000000,25653.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
30         0.000000
31         0.000000
32       438.814997
33      5908.000884
34      5030.740421
...             ...
18273   7356.000000
18274  17638.000000
18275  23339.000000
18276  26323.000000
18278  25598.000000

[5214 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 3649, y_train: 3649
X_val: 782, y_val: 782
X_test: 783, y_test: 783

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[5.00000000e-01 7.77777778e-02 9.04255319e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [5.00000000e-01 7.77777778e-02 9.36170213e-01 ... 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [4.68750000e-01 5.55555556e-02 9.68085106e-01 ... 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [2.50000000e-01 1.11111111e-02 9.78723404e-01 ... 6.66666667e-02
  0.00000000e+00 0.00000000e+00]
 [2.18750000e-01 0.00000000e+00 1.00000000e+00 ... 1.33333333e-01
  0.00000000e+00 5.96666667e-03]
 [1.87500000e-01 0.00000000e+00 1.00000000e+00 ... 2.00000000e-01
  9.83333333e-03 3.62200000e-01]]
(3649, 9)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.50000,0.077778,0.904255,0.000000,0.666667,0.789474,0.000000,0.000000,0.000000
31,0.50000,0.077778,0.936170,0.000000,0.333333,0.842105,0.066667,0.000000,0.000219
32,0.46875,0.055556,0.968085,0.000000,0.333333,0.789474,0.133333,0.000000,0.018681
33,0.50000,0.000000,0.925532,0.083333,0.000000,0.842105,0.200000,0.014627,0.257353
34,0.53125,0.000000,0.840426,0.166667,0.000000,0.789474,0.266667,0.196933,0.314437
...,...,...,...,...,...,...,...,...,...
12958,0.53125,0.000000,0.446809,0.000000,0.333333,0.368421,1.000000,0.000000,0.000000
12967,0.28125,0.011111,0.978723,0.000000,1.000000,0.473684,0.000000,0.000000,0.000000
12968,0.25000,0.011111,0.978723,0.000000,1.000000,0.473684,0.066667,0.000000,0.000000
12969,0.21875,0.000000,1.000000,0.000000,0.333333,0.421053,0.133333,0.000000,0.005967
12970,0.18750,0.000000,1.000000,0.083333,0.333333,0.368421,0.200000,0.009833,0.362200

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.28125    0.         0.82978723 ... 0.26666667 0.31593333 0.63086667]
 [0.375      0.         0.67021277 ... 0.33333333 0.65066667 0.66426667]
 [0.46875    0.         0.54255319 ... 0.4        0.67886667 0.6496    ]
 ...
 [0.75       0.02222222 0.43617021 ... 0.86666667 0.34693333 0.1592    ]
 [0.6875     0.06666667 0.5106383  ... 0.93333333 0.20373333 0.0115    ]
 [0.46875    0.07777778 0.87234043 ... 0.         0.         0.        ]]
(782, 9)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
12971,0.28125,0.000000,0.829787,0.166667,0.333333,0.368421,0.266667,0.315933,0.630867
12972,0.37500,0.000000,0.670213,0.166667,0.333333,0.368421,0.333333,0.650667,0.664267
12973,0.46875,0.000000,0.542553,0.250000,0.333333,0.368421,0.400000,0.678867,0.649600
12974,0.53125,0.000000,0.457447,0.250000,0.333333,0.368421,0.466667,0.656667,0.798233
12981,0.53125,0.000000,0.436170,0.000000,0.666667,0.368421,0.933333,0.042467,0.000000
...,...,...,...,...,...,...,...,...,...
16383,0.78125,0.000000,0.382979,0.750000,0.666667,0.631579,0.533333,0.900000,0.362167
16387,0.78125,0.000000,0.382979,0.166667,0.666667,0.631579,0.800000,0.379967,0.348467
16388,0.75000,0.022222,0.436170,0.000000,1.000000,0.684211,0.866667,0.346933,0.159200
16389,0.68750,0.066667,0.510638,0.000000,0.333333,0.684211,0.933333,0.203733,0.011500
16399,0.46875,0.077778,0.872340,0.000000,1.000000,0.736842,0.000000,0.000000,0.000000

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.46875    0.06666667 0.87234043 ... 0.06666667 0.         0.06736667]
 [0.46875    0.02222222 0.86170213 ... 0.13333333 0.0214     0.4988    ]
 [0.5        0.02222222 0.80851064 ... 0.2        0.2268     0.8451    ]
 ...
 [0.5        0.         0.69148936 ... 0.26666667 0.58793333 0.767     ]
 [0.5625     0.         0.57446809 ... 0.33333333 0.77796667 0.87186667]
 [0.6875     0.         0.40425532 ... 0.46666667 0.8759     0.8551    ]]
(783, 9)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
16400,0.46875,0.066667,0.872340,0.000000,1.000000,0.736842,0.066667,0.000000,0.067367
16401,0.46875,0.022222,0.861702,0.083333,1.000000,0.736842,0.133333,0.021400,0.498800
16402,0.50000,0.022222,0.808511,0.166667,1.000000,0.736842,0.200000,0.226800,0.845100
16403,0.59375,0.022222,0.702128,0.166667,1.000000,0.736842,0.266667,0.350033,0.895933
16404,0.65625,0.022222,0.606383,0.583333,0.333333,0.736842,0.333333,0.438233,0.900000
...,...,...,...,...,...,...,...,...,...
18273,0.40625,0.000000,0.861702,0.083333,0.666667,0.578947,0.133333,0.002233,0.243400
18274,0.43750,0.000000,0.819149,0.166667,0.666667,0.631579,0.200000,0.245200,0.600467
18275,0.50000,0.000000,0.691489,0.333333,0.333333,0.631579,0.266667,0.587933,0.767000
18276,0.56250,0.000000,0.574468,0.416667,0.333333,0.578947,0.333333,0.777967,0.871867
18278,0.68750,0.000000,0.404255,0.583333,0.666667,0.526316,0.466667,0.875900,0.855100

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[4.32432432e-01 7.77777778e-02 9.06250000e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.32432432e-01 7.77777778e-02 9.37500000e-01 ... 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [4.05405405e-01 5.55555556e-02 9.68750000e-01 ... 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [4.32432432e-01 0.00000000e+00 6.97916667e-01 ... 2.66666667e-01
  5.87933333e-01 7.67000000e-01]
 [4.86486486e-01 0.00000000e+00 5.83333333e-01 ... 3.33333333e-01
  7.77966667e-01 8.71866667e-01]
 [5.94594595e-01 0.00000000e+00 4.16666667e-01 ... 4.66666667e-01
  8.75900000e-01 8.55100000e-01]]
(5214, 9)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.432432,0.077778,0.906250,0.000000,0.666667,0.75,0.000000,0.000000,0.000000
31,0.432432,0.077778,0.937500,0.000000,0.333333,0.80,0.066667,0.000000,0.000219
32,0.405405,0.055556,0.968750,0.000000,0.333333,0.75,0.133333,0.000000,0.018681
33,0.432432,0.000000,0.927083,0.083333,0.000000,0.80,0.200000,0.014627,0.257353
34,0.459459,0.000000,0.843750,0.166667,0.000000,0.75,0.266667,0.196933,0.314437
...,...,...,...,...,...,...,...,...,...
18273,0.351351,0.000000,0.864583,0.083333,0.666667,0.55,0.133333,0.002233,0.243400
18274,0.378378,0.000000,0.822917,0.166667,0.666667,0.60,0.200000,0.245200,0.600467
18275,0.432432,0.000000,0.697917,0.333333,0.333333,0.60,0.266667,0.587933,0.767000
18276,0.486486,0.000000,0.583333,0.416667,0.333333,0.55,0.333333,0.777967,0.871867
18278,0.594595,0.000000,0.416667,0.583333,0.666667,0.50,0.466667,0.875900,0.855100

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.        ]
 [0.00983333]
 [0.31593333]]
(3649, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
12958    0.000000
12967    0.000000
12968    0.000000
12969    0.009833
12970    0.315933

[3649 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[6.50666667e-01]
 [6.78866667e-01]
 [6.56666667e-01]
 [6.34033333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.17000000e-02]
 [4.02500000e-01]
 [6.29733333e-01]
 [6.02466667e-01]
 [3.92200000e-01]
 [4.24333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [3.76966667e-01]
 [7.10300000e-01]
 [7.51233333e-01]
 [7.85666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.57333333e-02]
 [4.93300000e-01]
 [8.19466667e-01]
 [8.34700000e-01]
 [8.20833333e-01]
 [7.17400000e-01]
 [8.18666667e-01]
 [6.90233333e-01]
 [4.11033333e-01]
 [4.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [5.93533333e-01]
 [6.08633333e-01]
 [8.79666667e-01]
 [6.04733333e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32066667e-01]
 [2.87266667e-01]
 [8.49266667e-01]
 [8.96300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.34133333e-01]
 [9.95633333e-01]
 [8.73600000e-01]
 [5.62600000e-01]
 [4.62666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.04733333e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [2.69333333e-02]
 [4.75066667e-01]
 [5.05100000e-01]
 [7.07666667e-01]
 [7.24233333e-01]
 [7.01633333e-01]
 [6.87333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.85666667e-02]
 [4.76400000e-01]
 [4.86900000e-01]
 [7.03733333e-01]
 [7.16300000e-01]
 [6.92800000e-01]
 [6.66866667e-01]
 [4.91366667e-01]
 [9.59666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.94666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79000000e-02]
 [5.37166667e-01]
 [5.50066667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.35333333e-02]
 [1.42433333e-01]
 [1.70400000e-01]
 [6.15766667e-01]
 [6.26766667e-01]
 [6.28100000e-01]
 [6.09866667e-01]
 [9.53333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.99333333e-02]
 [4.15466667e-01]
 [4.86900000e-01]
 [7.03733333e-01]
 [7.21466667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.68666667e-02]
 [3.79866667e-01]
 [4.05700000e-01]
 [5.93666667e-01]
 [1.34566667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [6.09333333e-01]
 [6.15400000e-01]
 [8.61400000e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.01333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.02733333e-01]
 [7.33566667e-01]
 [9.86300000e-01]
 [9.94966667e-01]
 [9.92933333e-01]
 [8.74533333e-01]
 [4.33266667e-01]
 [4.10333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [5.95633333e-01]
 [6.29866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.06333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.00000000e-04]
 [4.15466667e-01]
 [4.44233333e-01]
 [8.68733333e-01]
 [8.07700000e-01]
 [5.96633333e-01]
 [1.10966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.66666667e-05]
 [1.89933333e-01]
 [6.10200000e-01]
 [7.91700000e-01]
 [8.05833333e-01]
 [7.12233333e-01]
 [6.85733333e-01]
 [6.81133333e-01]
 [7.68600000e-01]
 [9.80400000e-01]
 [7.70233333e-01]
 [4.56866667e-01]
 [1.07900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.56133333e-01]
 [4.50066667e-01]
 [6.51266667e-01]
 [9.75433333e-01]
 [9.28733333e-01]
 [9.71900000e-01]
 [9.31933333e-01]
 [5.67633333e-01]
 [6.32233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.74833333e-01]
 [6.28000000e-01]
 [7.55433333e-01]
 [7.36500000e-01]
 [7.29200000e-01]
 [6.37000000e-01]
 [7.18033333e-01]
 [5.17733333e-01]
 [1.03866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.66666667e-04]
 [0.00000000e+00]
 [6.66666667e-05]
 [5.93533333e-01]
 [6.18800000e-01]
 [8.85000000e-01]
 [8.95366667e-01]
 [8.79966667e-01]
 [8.78133333e-01]
 [0.00000000e+00]
 [4.00000000e-04]
 [5.93533333e-01]
 [6.08633333e-01]
 [9.83666667e-02]
 [6.66666667e-05]
 [0.00000000e+00]
 [1.06333333e-02]
 [7.41066667e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.67033333e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.33000000e-02]
 [3.42366667e-01]
 [8.38633333e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38166667e-01]
 [0.00000000e+00]
 [3.52166667e-01]
 [8.19466667e-01]
 [9.29666667e-01]
 [0.00000000e+00]
 [1.32333333e-02]
 [2.79033333e-01]
 [6.55566667e-01]
 [7.40466667e-01]
 [1.23333333e-03]
 [1.43233333e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [9.19733333e-01]
 [8.85233333e-01]
 [7.12900000e-01]
 [1.93533333e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06333333e-02]
 [2.73866667e-01]
 [7.52966667e-01]
 [7.50966667e-01]
 [6.56566667e-01]
 [6.55966667e-01]
 [6.14533333e-01]
 [0.00000000e+00]
 [1.38333333e-02]
 [3.42366667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [1.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.19666667e-02]
 [2.73866667e-01]
 [6.63866667e-01]
 [7.43800000e-01]
 [1.76666667e-03]
 [0.00000000e+00]
 [3.10300000e-01]
 [7.40766667e-01]
 [9.27233333e-01]
 [1.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.34333333e-02]
 [2.91733333e-01]
 [7.18000000e-01]
 [7.64600000e-01]
 [7.68100000e-01]
 [7.65933333e-01]
 [7.58566667e-01]
 [7.55666667e-01]
 [6.59333333e-01]
 [7.54133333e-01]
 [7.20366667e-01]
 [6.26533333e-01]
 [1.58300000e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [2.83333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.01000000e-02]
 [7.48133333e-01]
 [7.90333333e-02]
 [0.00000000e+00]
 [2.79333333e-02]
 [3.94066667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38000000e-02]
 [2.01066667e-01]
 [4.30800000e-01]
 [4.64833333e-01]
 [4.58433333e-01]
 [4.54800000e-01]
 [7.52700000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.10666667e-02]
 [4.37533333e-01]
 [8.85433333e-01]
 [2.49433333e-01]
 [0.00000000e+00]
 [3.64000000e-02]
 [3.85233333e-01]
 [8.97466667e-01]
 [6.85333333e-01]
 [2.01966667e-01]
 [0.00000000e+00]
 [2.15666667e-02]
 [0.00000000e+00]
 [2.30666667e-02]
 [2.81900000e-01]
 [5.97866667e-01]
 [7.57933333e-01]
 [9.64766667e-01]
 [9.81133333e-01]
 [9.63200000e-01]
 [9.37400000e-01]
 [9.37700000e-01]
 [9.21500000e-01]
 [0.00000000e+00]
 [3.00666667e-02]
 [4.26866667e-01]
 [4.10000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.46000000e-02]
 [4.65733333e-01]
 [8.82200000e-01]
 [9.89600000e-01]
 [0.00000000e+00]
 [4.58333333e-02]
 [4.38600000e-01]
 [8.90033333e-01]
 [9.74766667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [4.22800000e-01]
 [7.70600000e-01]
 [8.59000000e-01]
 [9.42933333e-01]
 [2.73700000e-01]
 [9.46666667e-03]
 [7.20566667e-01]
 [6.79966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.27333333e-02]
 [0.00000000e+00]
 [4.67666667e-02]
 [3.91000000e-01]
 [6.52300000e-01]
 [6.32733333e-01]
 [2.85100000e-01]
 [9.70000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.62000000e-02]
 [3.79400000e-01]
 [0.00000000e+00]
 [4.92333333e-02]
 [3.97033333e-01]
 [8.50133333e-01]
 [8.45200000e-01]
 [8.39266667e-01]
 [7.20000000e-01]
 [6.84566667e-01]
 [5.74900000e-01]
 [2.98200000e-01]
 [1.05000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [3.93466667e-01]
 [6.52300000e-01]
 [7.27966667e-01]
 [7.46533333e-01]
 [7.53633333e-01]
 [7.46500000e-01]
 [7.46100000e-01]
 [7.41400000e-01]
 [7.23333333e-01]
 [6.80400000e-01]
 [5.75633333e-01]
 [2.28066667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93333333e-02]
 [3.28866667e-01]
 [5.70766667e-01]
 [7.19233333e-01]
 [7.46533333e-01]
 [6.60366667e-01]
 [6.50233333e-01]
 [7.46100000e-01]
 [7.41166667e-01]
 [6.29900000e-01]
 [5.94966667e-01]
 [5.82866667e-01]
 [2.26866667e-01]
 [7.63333333e-03]
 [0.00000000e+00]
 [9.36033333e-01]
 [8.99866667e-01]
 [5.74666667e-02]
 [8.66500000e-01]
 [9.17300000e-01]
 [0.00000000e+00]
 [5.69333333e-02]
 [4.74933333e-01]
 [0.00000000e+00]
 [8.79000000e-02]
 [4.69800000e-01]
 [7.27633333e-01]
 [5.77333333e-01]
 [2.26266667e-01]
 [1.72666667e-02]
 [0.00000000e+00]
 [8.16666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.16333333e-02]
 [6.95666667e-01]
 [3.56766667e-01]
 [3.35000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.23966667e-01]
 [3.38000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.24166667e-01]
 [4.55966667e-01]
 [3.94000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.71000000e-02]
 [5.83100000e-01]
 [0.00000000e+00]
 [7.76333333e-02]
 [5.28933333e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.21533333e-01]
 [0.00000000e+00]
 [7.79333333e-02]
 [5.26466667e-01]
 [9.40466667e-01]
 [9.21400000e-01]
 [8.56933333e-01]
 [6.90300000e-01]
 [6.94800000e-01]
 [3.18100000e-01]
 [2.86666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.33333333e-03]
 [4.65666667e-02]
 [7.42000000e-02]
 [8.20000000e-02]
 [8.50000000e-02]
 [8.47666667e-02]
 [8.45333333e-02]
 [8.44333333e-02]
 [8.40333333e-02]
 [9.64666667e-02]
 [7.80000000e-02]
 [6.91000000e-02]
 [1.18933333e-01]
 [1.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.42333333e-02]
 [4.01966667e-01]
 [5.76600000e-01]
 [6.37700000e-01]
 [9.39166667e-01]
 [9.14933333e-01]
 [3.96400000e-01]
 [3.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93666667e-02]
 [5.16633333e-01]
 [8.24633333e-01]
 [5.73933333e-01]
 [5.94400000e-01]
 [5.94600000e-01]
 [5.91666667e-01]
 [5.92500000e-01]
 [5.87833333e-01]
 [9.12000000e-01]
 [8.67033333e-01]
 [7.66066667e-01]
 [3.58066667e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.50000000e-02]
 [4.14800000e-01]
 [6.60433333e-01]
 [5.73933333e-01]
 [5.93733333e-01]
 [5.93833333e-01]
 [9.39700000e-01]
 [9.37200000e-01]
 [9.31833333e-01]
 [9.15333333e-01]
 [8.69733333e-01]
 [7.66066667e-01]
 [2.85400000e-01]
 [2.41000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.02333333e-02]
 [5.16633333e-01]
 [8.24900000e-01]
 [9.11033333e-01]
 [9.44466667e-01]
 [9.44500000e-01]
 [9.40966667e-01]
 [9.39266667e-01]
 [9.34466667e-01]
 [2.74366667e-01]
 [2.60033333e-01]
 [2.31266667e-01]
 [1.94666667e-01]
 [1.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.17866667e-01]
 [8.29166667e-01]
 [9.15400000e-01]
 [9.44733333e-01]
 [9.12000000e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.46133333e-01]
 [8.40400000e-01]
 [9.17433333e-01]
 [9.47766667e-01]
 [0.00000000e+00]
 [8.25000000e-02]
 [5.39233333e-01]
 [8.24700000e-01]
 [9.11100000e-01]
 [9.41333333e-01]
 [9.48033333e-01]
 [8.13533333e-01]
 [4.57200000e-01]
 [4.96666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.18166667e-01]
 [8.30233333e-01]
 [9.11033333e-01]
 [9.44333333e-01]
 [7.00066667e-01]
 [4.08500000e-01]
 [4.69000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.81666667e-02]
 [5.21533333e-01]
 [8.27466667e-01]
 [9.11033333e-01]
 [9.48200000e-01]
 [9.41766667e-01]
 [9.36533333e-01]
 [6.73133333e-01]
 [9.12000000e-01]
 [6.24066667e-01]
 [5.01733333e-01]
 [3.64933333e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.21333333e-02]
 [5.18833333e-01]
 [8.27000000e-01]
 [9.11233333e-01]
 [8.55500000e-01]
 [9.41933333e-01]
 [9.33866667e-01]
 [8.21300000e-01]
 [7.80066667e-01]
 [5.63466667e-01]
 [4.56366667e-01]
 [3.40666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.71666667e-02]
 [3.60533333e-01]
 [5.79133333e-01]
 [5.85166667e-01]
 [6.07233333e-01]
 [6.03966667e-01]
 [5.94433333e-01]
 [5.88066667e-01]
 [5.90700000e-01]
 [4.46866667e-01]
 [4.23133333e-01]
 [3.83533333e-01]
 [3.29333333e-01]
 [2.31666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.54666667e-02]
 [4.35333333e-01]
 [7.98266667e-01]
 [8.94266667e-01]
 [9.26166667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.59666667e-02]
 [4.37000000e-01]
 [7.98366667e-01]
 [8.97400000e-01]
 [9.27600000e-01]
 [9.21233333e-01]
 [9.18966667e-01]
 [2.87333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [8.01333333e-01]
 [8.94866667e-01]
 [9.24766667e-01]
 [9.21233333e-01]
 [9.18966667e-01]
 [0.00000000e+00]
 [3.93666667e-02]
 [3.98566667e-01]
 [8.03900000e-01]
 [8.94266667e-01]
 [0.00000000e+00]
 [3.30333333e-02]
 [3.24500000e-01]
 [5.35133333e-01]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [8.46033333e-01]
 [8.59966667e-01]
 [8.00666667e-01]
 [7.70200000e-01]
 [3.89333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.09666667e-02]
 [4.37133333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.30400000e-01]
 [0.00000000e+00]
 [3.08333333e-02]
 [2.51400000e-01]
 [4.96333333e-01]
 [5.67933333e-01]
 [6.47633333e-01]
 [6.30766667e-01]
 [6.51766667e-01]
 [7.19033333e-01]
 [7.40133333e-01]
 [6.64433333e-01]
 [2.87466667e-01]
 [1.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.64666667e-01]
 [8.06500000e-01]
 [8.96166667e-01]
 [9.25000000e-01]
 [9.24933333e-01]
 [8.27066667e-01]
 [9.15533333e-01]
 [8.20566667e-01]
 [6.51200000e-01]
 [5.56433333e-01]
 [5.66766667e-01]
 [3.28733333e-01]
 [5.51000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.87666667e-02]
 [2.30066667e-01]
 [4.55966667e-01]
 [6.44833333e-01]
 [6.65833333e-01]
 [6.64366667e-01]
 [6.62500000e-01]
 [6.60866667e-01]
 [5.76833333e-01]
 [3.14633333e-01]
 [3.01600000e-01]
 [4.34866667e-01]
 [3.04900000e-01]
 [3.72000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40333333e-02]
 [1.79900000e-01]
 [4.45933333e-01]
 [3.23633333e-01]
 [2.70000000e-01]
 [2.01200000e-01]
 [2.51800000e-01]
 [3.47666667e-01]
 [1.97800000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.68333333e-02]
 [1.82600000e-01]
 [3.02933333e-01]
 [3.23700000e-01]
 [4.05000000e-01]
 [3.21633333e-01]
 [4.03566667e-01]
 [3.48466667e-01]
 [1.59200000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [4.98800000e-01]
 [8.45100000e-01]
 [8.95933333e-01]
 [9.00000000e-01]
 [8.86300000e-01]
 [9.00000000e-01]
 [8.04800000e-01]
 [3.46933333e-01]
 [2.03733333e-01]
 [1.49000000e-02]
 [0.00000000e+00]]
(782, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
12971    0.650667
12972    0.678867
12973    0.656667
12974    0.634033
12981    0.000000
...           ...
16383    0.804800
16387    0.346933
16388    0.203733
16389    0.014900
16399    0.000000

[782 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[2.14000000e-02]
 [2.26800000e-01]
 [3.50033333e-01]
 [4.38233333e-01]
 [5.17866667e-01]
 [2.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79666667e-02]
 [2.78633333e-01]
 [4.04633333e-01]
 [3.96600000e-01]
 [3.95833333e-01]
 [3.86166667e-01]
 [5.20300000e-01]
 [4.55600000e-01]
 [3.93566667e-01]
 [2.66166667e-01]
 [2.36933333e-01]
 [2.46166667e-01]
 [2.48333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20333333e-02]
 [2.95566667e-01]
 [4.52433333e-01]
 [5.00800000e-01]
 [4.54266667e-01]
 [2.79633333e-01]
 [2.82066667e-01]
 [2.80133333e-01]
 [2.70033333e-01]
 [4.37733333e-01]
 [2.42166667e-01]
 [2.97333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.84000000e-02]
 [2.61400000e-01]
 [5.28433333e-01]
 [5.05033333e-01]
 [3.92000000e-01]
 [4.46200000e-01]
 [8.93633333e-01]
 [7.99433333e-01]
 [3.90766667e-01]
 [4.55000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93000000e-02]
 [3.93100000e-01]
 [7.95400000e-01]
 [9.24766667e-01]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.00500000e-01]
 [9.24766667e-01]
 [0.00000000e+00]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.96833333e-01]
 [9.24766667e-01]
 [9.37500000e-01]
 [7.85400000e-01]
 [3.59033333e-01]
 [3.83666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.33400000e-01]
 [8.52400000e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.93000000e-02]
 [1.40800000e-01]
 [2.47800000e-01]
 [3.81700000e-01]
 [3.92633333e-01]
 [3.94533333e-01]
 [4.66566667e-01]
 [4.48600000e-01]
 [5.12533333e-01]
 [5.03500000e-01]
 [6.21466667e-01]
 [7.75366667e-01]
 [1.92633333e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.38333333e-02]
 [4.69166667e-01]
 [8.33500000e-01]
 [8.16000000e-01]
 [6.67466667e-01]
 [6.60733333e-01]
 [6.64166667e-01]
 [6.88000000e-01]
 [6.62833333e-01]
 [6.58766667e-01]
 [6.36333333e-01]
 [8.15333333e-01]
 [4.41033333e-01]
 [4.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.23966667e-01]
 [9.25500000e-01]
 [9.15766667e-01]
 [9.10633333e-01]
 [8.99166667e-01]
 [8.67500000e-01]
 [7.71733333e-01]
 [3.93133333e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43333333e-02]
 [4.39333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.21233333e-01]
 [8.61733333e-01]
 [7.70200000e-01]
 [4.02500000e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.31433333e-01]
 [9.24466667e-01]
 [9.15533333e-01]
 [9.10633333e-01]
 [9.00833333e-01]
 [8.61766667e-01]
 [7.73533333e-01]
 [3.93266667e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.58666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [7.16600000e-01]
 [7.40700000e-01]
 [5.51500000e-01]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.73900000e-01]
 [9.24566667e-01]
 [9.50366667e-01]
 [9.40766667e-01]
 [9.15500000e-01]
 [8.97933333e-01]
 [7.70200000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.38900000e-01]
 [7.95400000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [2.97733333e-01]
 [7.97666667e-01]
 [8.92133333e-01]
 [2.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.68666667e-02]
 [4.04933333e-01]
 [7.88133333e-01]
 [8.82633333e-01]
 [0.00000000e+00]
 [2.79000000e-02]
 [3.97200000e-01]
 [7.90900000e-01]
 [0.00000000e+00]
 [2.82000000e-02]
 [4.01833333e-01]
 [7.97833333e-01]
 [0.00000000e+00]
 [2.41666667e-02]
 [3.93333333e-01]
 [8.23766667e-01]
 [9.00666667e-01]
 [9.26133333e-01]
 [3.41100000e-01]
 [1.93333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.08000000e-02]
 [3.21433333e-01]
 [7.44300000e-01]
 [8.14833333e-01]
 [8.34400000e-01]
 [8.19566667e-01]
 [8.20200000e-01]
 [0.00000000e+00]
 [2.10000000e-02]
 [3.20100000e-01]
 [6.98633333e-01]
 [9.21966667e-01]
 [0.00000000e+00]
 [2.20666667e-02]
 [3.70033333e-01]
 [7.77866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40666667e-02]
 [3.77433333e-01]
 [7.84366667e-01]
 [9.24733333e-01]
 [9.35033333e-01]
 [9.05133333e-01]
 [0.00000000e+00]
 [2.28000000e-02]
 [3.40100000e-01]
 [7.78033333e-01]
 [8.86700000e-01]
 [9.26266667e-01]
 [6.40000000e-01]
 [2.28866667e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.38000000e-02]
 [3.74066667e-01]
 [7.80300000e-01]
 [8.81166667e-01]
 [9.25566667e-01]
 [6.45466667e-01]
 [2.28866667e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06666667e-02]
 [2.83600000e-01]
 [6.43000000e-01]
 [7.04933333e-01]
 [7.41166667e-01]
 [7.39366667e-01]
 [7.27166667e-01]
 [7.26000000e-01]
 [9.05766667e-01]
 [9.07400000e-01]
 [8.90533333e-01]
 [7.13766667e-01]
 [1.52666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.38166667e-01]
 [7.77400000e-01]
 [8.85766667e-01]
 [9.23933333e-01]
 [9.30766667e-01]
 [9.24666667e-01]
 [9.19000000e-01]
 [6.03566667e-01]
 [3.52733333e-01]
 [7.50000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.99333333e-02]
 [3.41533333e-01]
 [7.73633333e-01]
 [9.07933333e-01]
 [9.37200000e-01]
 [9.37400000e-01]
 [9.06800000e-01]
 [5.94366667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.63333333e-01]
 [7.73633333e-01]
 [8.95666667e-01]
 [9.39000000e-01]
 [9.42600000e-01]
 [9.48766667e-01]
 [7.39966667e-01]
 [5.75833333e-01]
 [2.85466667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74333333e-02]
 [3.84800000e-01]
 [8.13333333e-01]
 [9.17600000e-01]
 [9.38200000e-01]
 [9.34533333e-01]
 [9.24633333e-01]
 [9.16733333e-01]
 [9.43433333e-01]
 [9.25966667e-01]
 [8.90533333e-01]
 [6.74700000e-01]
 [2.71400000e-01]
 [9.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74000000e-02]
 [3.83966667e-01]
 [8.16733333e-01]
 [9.14666667e-01]
 [9.40133333e-01]
 [9.33866667e-01]
 [9.32600000e-01]
 [6.02600000e-01]
 [2.77466667e-01]
 [8.63333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.84333333e-02]
 [3.84966667e-01]
 [8.08000000e-01]
 [7.33100000e-01]
 [7.46000000e-01]
 [7.52033333e-01]
 [5.51133333e-01]
 [2.46333333e-01]
 [6.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.14333333e-02]
 [2.73366667e-01]
 [6.37833333e-01]
 [7.21900000e-01]
 [7.56166667e-01]
 [7.46266667e-01]
 [7.46633333e-01]
 [5.15266667e-01]
 [1.83066667e-01]
 [9.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.46000000e-02]
 [2.85633333e-01]
 [9.27366667e-01]
 [6.06666667e-01]
 [7.76666667e-02]
 [4.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.52000000e-02]
 [2.73033333e-01]
 [9.27566667e-01]
 [5.23400000e-01]
 [0.00000000e+00]
 [7.29566667e-01]
 [2.75333333e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.98300000e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [9.62066667e-01]
 [5.98633333e-01]
 [1.88466667e-01]
 [4.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.99666667e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [0.00000000e+00]
 [1.32666667e-02]
 [4.06533333e-01]
 [8.33866667e-01]
 [2.34266667e-01]
 [7.83333333e-03]
 [0.00000000e+00]
 [1.39333333e-02]
 [3.30833333e-01]
 [7.73633333e-01]
 [8.81166667e-01]
 [9.02433333e-01]
 [2.10933333e-01]
 [0.00000000e+00]
 [1.44333333e-02]
 [3.70966667e-01]
 [8.09266667e-01]
 [9.07600000e-01]
 [9.53733333e-01]
 [9.31633333e-01]
 [9.30366667e-01]
 [6.07300000e-01]
 [1.83066667e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.35200000e-01]
 [7.74566667e-01]
 [9.60833333e-01]
 [6.48400000e-01]
 [2.28866667e-01]
 [6.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38666667e-02]
 [2.64666667e-01]
 [6.18900000e-01]
 [7.96200000e-01]
 [8.29766667e-01]
 [5.97933333e-01]
 [5.74700000e-01]
 [2.05966667e-01]
 [4.26666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.30833333e-01]
 [6.96266667e-01]
 [7.06233333e-01]
 [8.29766667e-01]
 [5.57333333e-01]
 [4.02866667e-01]
 [3.13033333e-01]
 [1.28166667e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [1.78433333e-01]
 [3.79433333e-01]
 [3.75233333e-01]
 [3.54066667e-01]
 [1.92900000e-01]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.00000000e-04]
 [2.86666667e-02]
 [6.97000000e-02]
 [8.04000000e-02]
 [8.28000000e-02]
 [8.28333333e-02]
 [8.04666667e-02]
 [7.58666667e-02]
 [5.74000000e-02]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.26666667e-03]
 [9.30666667e-02]
 [3.39300000e-01]
 [3.83733333e-01]
 [3.90233333e-01]
 [2.74900000e-01]
 [5.11933333e-01]
 [4.20900000e-01]
 [3.76766667e-01]
 [6.52000000e-02]
 [1.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.30000000e-03]
 [1.54933333e-01]
 [3.28166667e-01]
 [5.02700000e-01]
 [5.86100000e-01]
 [4.40233333e-01]
 [5.66333333e-01]
 [2.12300000e-01]
 [6.03000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.13333333e-03]
 [1.88500000e-01]
 [6.96900000e-01]
 [5.36066667e-01]
 [4.37866667e-01]
 [3.77233333e-01]
 [2.66866667e-01]
 [8.25666667e-02]
 [2.68533333e-01]
 [3.12933333e-01]
 [4.77433333e-01]
 [6.67000000e-02]
 [5.01333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.96666667e-03]
 [1.77100000e-01]
 [3.93700000e-01]
 [5.02500000e-01]
 [6.47000000e-01]
 [3.82966667e-01]
 [3.78000000e-01]
 [3.83566667e-01]
 [4.38633333e-01]
 [5.06533333e-01]
 [5.61666667e-01]
 [3.48500000e-01]
 [8.61333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [5.00333333e-01]
 [6.83066667e-01]
 [5.24566667e-01]
 [8.94100000e-01]
 [8.00000000e-01]
 [6.40133333e-01]
 [1.37500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.95566667e-01]
 [8.06100000e-01]
 [8.52600000e-01]
 [5.25600000e-01]
 [4.98400000e-01]
 [5.84866667e-01]
 [7.04733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98800000e-01]
 [7.79066667e-01]
 [8.98533333e-01]
 [9.48700000e-01]
 [0.00000000e+00]
 [5.70000000e-03]
 [3.06733333e-01]
 [8.07833333e-01]
 [9.19166667e-01]
 [9.24300000e-01]
 [8.98133333e-01]
 [8.89033333e-01]
 [9.23800000e-01]
 [9.13700000e-01]
 [9.08666667e-01]
 [8.72366667e-01]
 [6.23966667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98633333e-01]
 [7.87133333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [9.02866667e-01]
 [8.43033333e-01]
 [6.48733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.94566667e-01]
 [7.76166667e-01]
 [8.93433333e-01]
 [9.13266667e-01]
 [9.01833333e-01]
 [8.92866667e-01]
 [9.18500000e-01]
 [8.98700000e-01]
 [8.97766667e-01]
 [8.44533333e-01]
 [6.39566667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.86666667e-03]
 [2.35633333e-01]
 [6.19466667e-01]
 [7.35333333e-01]
 [7.29766667e-01]
 [7.18500000e-01]
 [7.14300000e-01]
 [8.21900000e-01]
 [8.08066667e-01]
 [7.15266667e-01]
 [5.39566667e-01]
 [3.49433333e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [8.97600000e-01]
 [9.12233333e-01]
 [9.00266667e-01]
 [8.92866667e-01]
 [9.13233333e-01]
 [8.09666667e-01]
 [5.72233333e-01]
 [6.07633333e-01]
 [3.05733333e-01]
 [5.46333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.63333333e-03]
 [2.15000000e-01]
 [7.74333333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [8.98133333e-01]
 [9.13233333e-01]
 [8.06333333e-01]
 [8.04666667e-01]
 [5.39566667e-01]
 [2.62066667e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [2.88766667e-01]
 [7.75733333e-01]
 [6.45166667e-01]
 [6.57400000e-01]
 [6.46866667e-01]
 [8.97500000e-01]
 [9.14166667e-01]
 [8.99200000e-01]
 [4.99600000e-01]
 [4.78266667e-01]
 [3.27833333e-01]
 [9.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.70000000e-03]
 [2.50900000e-01]
 [7.80300000e-01]
 [9.22300000e-01]
 [9.05033333e-01]
 [8.92166667e-01]
 [7.82100000e-01]
 [8.68366667e-01]
 [9.14033333e-01]
 [8.74466667e-01]
 [8.31300000e-01]
 [5.14600000e-01]
 [5.67000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.60266667e-01]
 [8.07900000e-01]
 [9.17700000e-01]
 [9.27500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.70000000e-03]
 [2.93166667e-01]
 [8.13733333e-01]
 [9.19500000e-01]
 [9.26933333e-01]
 [9.22000000e-01]
 [0.00000000e+00]
 [2.26666667e-03]
 [2.75633333e-01]
 [7.94333333e-01]
 [9.03866667e-01]
 [9.07400000e-01]
 [8.98733333e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.51233333e-01]
 [7.08300000e-01]
 [8.33333333e-01]
 [9.10633333e-01]
 [9.03566667e-01]
 [0.00000000e+00]
 [2.46666667e-03]
 [2.53400000e-01]
 [7.06433333e-01]
 [8.33366667e-01]
 [9.10633333e-01]
 [0.00000000e+00]
 [2.63333333e-03]
 [2.55600000e-01]
 [7.08300000e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.62266667e-01]
 [7.08300000e-01]
 [8.30033333e-01]
 [8.34533333e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.32966667e-01]
 [5.81266667e-01]
 [7.39900000e-01]
 [8.51400000e-01]
 [0.00000000e+00]
 [4.43333333e-03]
 [2.47100000e-01]
 [5.77166667e-01]
 [7.70533333e-01]
 [5.15100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.56666667e-03]
 [2.38433333e-01]
 [5.76833333e-01]
 [7.49866667e-01]
 [8.57533333e-01]
 [8.71666667e-01]
 [8.51933333e-01]
 [8.49533333e-01]
 [8.38900000e-01]
 [8.40766667e-01]
 [6.19133333e-01]
 [4.17800000e-01]
 [4.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.43333333e-03]
 [1.98000000e-01]
 [5.41133333e-01]
 [6.99333333e-01]
 [8.47766667e-01]
 [7.96533333e-01]
 [8.54333333e-01]
 [8.54066667e-01]
 [8.42000000e-01]
 [8.43133333e-01]
 [7.60066667e-01]
 [4.76266667e-01]
 [4.14000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.35666667e-01]
 [5.97333333e-01]
 [7.50633333e-01]
 [8.56600000e-01]
 [8.69633333e-01]
 [8.49933333e-01]
 [8.51833333e-01]
 [5.26033333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.36666667e-03]
 [2.41600000e-01]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.45200000e-01]
 [5.87933333e-01]
 [7.77966667e-01]
 [8.77433333e-01]
 [8.53266667e-01]]
(783, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
16400    0.021400
16401    0.226800
16402    0.350033
16403    0.438233
16404    0.517867
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18278    0.853267

[783 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.77796667]
 [0.87743333]
 [0.85326667]]
(5214, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18278    0.853267

[5214 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.177061 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 747
[LightGBM] [Info] Number of data points in the train set: 3649, number of used features: 9
[LightGBM] [Info] Start training from score 0.295448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
16400   1485.421686
16401  11718.606066
16402  18614.042112
16403   17689.00615
16404  17039.389972
...             ...
18273   6900.654023
18274   20543.60541
18275  23189.371101
18276  26104.467998
18278   26678.02481

[783 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
16400       642.0
16401      6804.0
16402     10501.0
16403     13147.0
16404     15536.0
...           ...
18273      7356.0
18274     17638.0
18275     23339.0
18276     26323.0
18278     25598.0

[783 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
16400       642.0   1485.421686
16401      6804.0  11718.606066
16402     10501.0  18614.042112
16403     13147.0   17689.00615
16404     15536.0  17039.389972
...           ...           ...
18273      7356.0   6900.654023
18274     17638.0   20543.60541
18275     23339.0  23189.371101
18276     26323.0  26104.467998
18278     25598.0   26678.02481

[783 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1424.1067
RMSE: 2418.9925
R²: 0.9503

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
16400       642.0   1485.421686   1850.979413
16401      6804.0  11718.606066  11182.089488
16402     10501.0  18614.042112  19279.054526
16403     13147.0   17689.00615  17438.807493
16404     15536.0  17039.389972  16974.916203
...           ...           ...           ...
18273      7356.0   6900.654023   5846.106045
18274     17638.0   20543.60541  19516.687678
18275     23339.0  23189.371101  21231.472263
18276     26323.0  26104.467998  24456.544978
18278     25598.0   26678.02481    26577.9225

[783 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (3601, 48, 9), y_train: (3601, 1)
X_val: (734, 48, 9), y_val: (734, 1)
X_test: (735, 48, 9), y_test: (735, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 99s 3s/step - loss: 0.1892 - mean_absolute_error: 0.2915 - mean_absolute_percentage_error: 480896.1875 - root_mean_squared_error: 0.4349 - val_loss: 0.1760 - val_mean_absolute_error: 0.2925 - val_mean_absolute_percentage_error: 2641551.5000 - val_root_mean_squared_error: 0.4196
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - loss: 0.1829 - mean_absolute_error: 0.2871 - mean_absolute_percentage_error: 3112354.2500 - root_mean_squared_error: 0.4277 - val_loss: 0.1700 - val_mean_absolute_error: 0.2904 - val_mean_absolute_percentage_error: 6072492.0000 - val_root_mean_squared_error: 0.4123
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 761ms/step - loss: 0.1801 - mean_absolute_error: 0.2868 - mean_absolute_percentage_error: 6482014.0000 - root_mean_squared_error: 0.4244 - val_loss: 0.1628 - val_mean_absolute_error: 0.2882 - val_mean_absolute_percentage_error: 10329943.0000 - val_root_mean_squared_error: 0.4035
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 7s 685ms/step - loss: 0.1682 - mean_absolute_error: 0.2805 - mean_absolute_percentage_error: 10636879.0000 - root_mean_squared_error: 0.4101 - val_loss: 0.1543 - val_mean_absolute_error: 0.2860 - val_mean_absolute_percentage_error: 15670891.0000 - val_root_mean_squared_error: 0.3928
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1623 - mean_absolute_error: 0.2802 - mean_absolute_percentage_error: 15668405.0000 - root_mean_squared_error: 0.4028 - val_loss: 0.1443 - val_mean_absolute_error: 0.2835 - val_mean_absolute_percentage_error: 22427628.0000 - val_root_mean_squared_error: 0.3799
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 12s 2s/step - loss: 0.1537 - mean_absolute_error: 0.2788 - mean_absolute_percentage_error: 22763890.0000 - root_mean_squared_error: 0.3921 - val_loss: 0.1330 - val_mean_absolute_error: 0.2806 - val_mean_absolute_percentage_error: 30982406.0000 - val_root_mean_squared_error: 0.3647
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1394 - mean_absolute_error: 0.2735 - mean_absolute_percentage_error: 30232008.0000 - root_mean_squared_error: 0.3734 - val_loss: 0.1207 - val_mean_absolute_error: 0.2780 - val_mean_absolute_percentage_error: 41794768.0000 - val_root_mean_squared_error: 0.3475
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 822ms/step - loss: 0.1298 - mean_absolute_error: 0.2781 - mean_absolute_percentage_error: 40143760.0000 - root_mean_squared_error: 0.3602 - val_loss: 0.1088 - val_mean_absolute_error: 0.2760 - val_mean_absolute_percentage_error: 55068600.0000 - val_root_mean_squared_error: 0.3299
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.1202 - mean_absolute_error: 0.2797 - mean_absolute_percentage_error: 53187428.0000 - root_mean_squared_error: 0.3467 - val_loss: 0.0995 - val_mean_absolute_error: 0.2758 - val_mean_absolute_percentage_error: 70142640.0000 - val_root_mean_squared_error: 0.3154
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.1122 - mean_absolute_error: 0.2835 - mean_absolute_percentage_error: 66309776.0000 - root_mean_squared_error: 0.3349 - val_loss: 0.0946 - val_mean_absolute_error: 0.2777 - val_mean_absolute_percentage_error: 85368992.0000 - val_root_mean_squared_error: 0.3075
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 14s 1s/step - loss: 0.1084 - mean_absolute_error: 0.2900 - mean_absolute_percentage_error: 81942448.0000 - root_mean_squared_error: 0.3293 - val_loss: 0.0939 - val_mean_absolute_error: 0.2806 - val_mean_absolute_percentage_error: 96249720.0000 - val_root_mean_squared_error: 0.3064
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 7s 639ms/step - loss: 0.1114 - mean_absolute_error: 0.2959 - mean_absolute_percentage_error: 89387288.0000 - root_mean_squared_error: 0.3337 - val_loss: 0.0942 - val_mean_absolute_error: 0.2821 - val_mean_absolute_percentage_error: 99928208.0000 - val_root_mean_squared_error: 0.3069
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1098 - mean_absolute_error: 0.2961 - mean_absolute_percentage_error: 91750608.0000 - root_mean_squared_error: 0.3314 - val_loss: 0.0939 - val_mean_absolute_error: 0.2807 - val_mean_absolute_percentage_error: 96436312.0000 - val_root_mean_squared_error: 0.3064
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1074 - mean_absolute_error: 0.2900 - mean_absolute_percentage_error: 87563808.0000 - root_mean_squared_error: 0.3276 - val_loss: 0.0939 - val_mean_absolute_error: 0.2790 - val_mean_absolute_percentage_error: 91106096.0000 - val_root_mean_squared_error: 0.3065
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1101 - mean_absolute_error: 0.2918 - mean_absolute_percentage_error: 80215312.0000 - root_mean_squared_error: 0.3318 - val_loss: 0.0942 - val_mean_absolute_error: 0.2784 - val_mean_absolute_percentage_error: 88659904.0000 - val_root_mean_squared_error: 0.3068
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.1106 - mean_absolute_error: 0.2913 - mean_absolute_percentage_error: 80789776.0000 - root_mean_squared_error: 0.3325 - val_loss: 0.0942 - val_mean_absolute_error: 0.2784 - val_mean_absolute_percentage_error: 88471576.0000 - val_root_mean_squared_error: 0.3069
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1096 - mean_absolute_error: 0.2896 - mean_absolute_percentage_error: 80693888.0000 - root_mean_squared_error: 0.3310 - val_loss: 0.0941 - val_mean_absolute_error: 0.2786 - val_mean_absolute_percentage_error: 89390456.0000 - val_root_mean_squared_error: 0.3067
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1095 - mean_absolute_error: 0.2909 - mean_absolute_percentage_error: 81928808.0000 - root_mean_squared_error: 0.3309 - val_loss: 0.0940 - val_mean_absolute_error: 0.2789 - val_mean_absolute_percentage_error: 90698816.0000 - val_root_mean_squared_error: 0.3066
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1082 - mean_absolute_error: 0.2893 - mean_absolute_percentage_error: 82661640.0000 - root_mean_squared_error: 0.3290 - val_loss: 0.0940 - val_mean_absolute_error: 0.2790 - val_mean_absolute_percentage_error: 90734800.0000 - val_root_mean_squared_error: 0.3066
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.1078 - mean_absolute_error: 0.2889 - mean_absolute_percentage_error: 82547296.0000 - root_mean_squared_error: 0.3284 - val_loss: 0.0940 - val_mean_absolute_error: 0.2789 - val_mean_absolute_percentage_error: 90571160.0000 - val_root_mean_squared_error: 0.3066
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 872ms/step - loss: 0.1119 - mean_absolute_error: 0.2945 - mean_absolute_percentage_error: 83219944.0000 - root_mean_squared_error: 0.3344 - val_loss: 0.0941 - val_mean_absolute_error: 0.2787 - val_mean_absolute_percentage_error: 89888456.0000 - val_root_mean_squared_error: 0.3067
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.1064 - mean_absolute_error: 0.2867 - mean_absolute_percentage_error: 81892296.0000 - root_mean_squared_error: 0.3262 - val_loss: 0.0942 - val_mean_absolute_error: 0.2785 - val_mean_absolute_percentage_error: 88910488.0000 - val_root_mean_squared_error: 0.3068
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1087 - mean_absolute_error: 0.2897 - mean_absolute_percentage_error: 82886296.0000 - root_mean_squared_error: 0.3296 - val_loss: 0.0942 - val_mean_absolute_error: 0.2784 - val_mean_absolute_percentage_error: 88320728.0000 - val_root_mean_squared_error: 0.3069
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 828ms/step - loss: 0.1046 - mean_absolute_error: 0.2837 - mean_absolute_percentage_error: 81114928.0000 - root_mean_squared_error: 0.3234 - val_loss: 0.0943 - val_mean_absolute_error: 0.2782 - val_mean_absolute_percentage_error: 87529248.0000 - val_root_mean_squared_error: 0.3071
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.1045 - mean_absolute_error: 0.2842 - mean_absolute_percentage_error: 78813120.0000 - root_mean_squared_error: 0.3232 - val_loss: 0.0944 - val_mean_absolute_error: 0.2780 - val_mean_absolute_percentage_error: 87011424.0000 - val_root_mean_squared_error: 0.3072
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 927ms/step - loss: 0.1052 - mean_absolute_error: 0.2854 - mean_absolute_percentage_error: 84004680.0000 - root_mean_squared_error: 0.3244 - val_loss: 0.0948 - val_mean_absolute_error: 0.2773 - val_mean_absolute_percentage_error: 84010456.0000 - val_root_mean_squared_error: 0.3080
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 14s 1s/step - loss: 0.1071 - mean_absolute_error: 0.2874 - mean_absolute_percentage_error: 83040576.0000 - root_mean_squared_error: 0.3273 - val_loss: 0.0952 - val_mean_absolute_error: 0.2769 - val_mean_absolute_percentage_error: 82002872.0000 - val_root_mean_squared_error: 0.3086
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1049 - mean_absolute_error: 0.2847 - mean_absolute_percentage_error: 82071992.0000 - root_mean_squared_error: 0.3238 - val_loss: 0.0951 - val_mean_absolute_error: 0.2768 - val_mean_absolute_percentage_error: 82384808.0000 - val_root_mean_squared_error: 0.3084
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1037 - mean_absolute_error: 0.2829 - mean_absolute_percentage_error: 82557688.0000 - root_mean_squared_error: 0.3220 - val_loss: 0.0960 - val_mean_absolute_error: 0.2761 - val_mean_absolute_percentage_error: 78813496.0000 - val_root_mean_squared_error: 0.3098
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.1048 - mean_absolute_error: 0.2827 - mean_absolute_percentage_error: 79240696.0000 - root_mean_squared_error: 0.3237 - val_loss: 0.0965 - val_mean_absolute_error: 0.2757 - val_mean_absolute_percentage_error: 76903248.0000 - val_root_mean_squared_error: 0.3106
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1033 - mean_absolute_error: 0.2809 - mean_absolute_percentage_error: 82435568.0000 - root_mean_squared_error: 0.3214 - val_loss: 0.0967 - val_mean_absolute_error: 0.2753 - val_mean_absolute_percentage_error: 75961752.0000 - val_root_mean_squared_error: 0.3110
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.1028 - mean_absolute_error: 0.2787 - mean_absolute_percentage_error: 79315416.0000 - root_mean_squared_error: 0.3206 - val_loss: 0.0960 - val_mean_absolute_error: 0.2752 - val_mean_absolute_percentage_error: 77526904.0000 - val_root_mean_squared_error: 0.3099
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1017 - mean_absolute_error: 0.2782 - mean_absolute_percentage_error: 81272336.0000 - root_mean_squared_error: 0.3190 - val_loss: 0.0967 - val_mean_absolute_error: 0.2746 - val_mean_absolute_percentage_error: 75082176.0000 - val_root_mean_squared_error: 0.3109
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.1022 - mean_absolute_error: 0.2774 - mean_absolute_percentage_error: 78326144.0000 - root_mean_squared_error: 0.3197 - val_loss: 0.0950 - val_mean_absolute_error: 0.2748 - val_mean_absolute_percentage_error: 79925368.0000 - val_root_mean_squared_error: 0.3082
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1006 - mean_absolute_error: 0.2749 - mean_absolute_percentage_error: 77846176.0000 - root_mean_squared_error: 0.3171 - val_loss: 0.0962 - val_mean_absolute_error: 0.2740 - val_mean_absolute_percentage_error: 75040984.0000 - val_root_mean_squared_error: 0.3102
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1020 - mean_absolute_error: 0.2762 - mean_absolute_percentage_error: 75158072.0000 - root_mean_squared_error: 0.3193 - val_loss: 0.0959 - val_mean_absolute_error: 0.2737 - val_mean_absolute_percentage_error: 75351344.0000 - val_root_mean_squared_error: 0.3097
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 1s/step - loss: 0.1030 - mean_absolute_error: 0.2770 - mean_absolute_percentage_error: 80953160.0000 - root_mean_squared_error: 0.3210 - val_loss: 0.0956 - val_mean_absolute_error: 0.2734 - val_mean_absolute_percentage_error: 75644704.0000 - val_root_mean_squared_error: 0.3092
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 8s 759ms/step - loss: 0.1004 - mean_absolute_error: 0.2726 - mean_absolute_percentage_error: 76633688.0000 - root_mean_squared_error: 0.3168 - val_loss: 0.0956 - val_mean_absolute_error: 0.2731 - val_mean_absolute_percentage_error: 75061936.0000 - val_root_mean_squared_error: 0.3091
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.0998 - mean_absolute_error: 0.2719 - mean_absolute_percentage_error: 77548856.0000 - root_mean_squared_error: 0.3159 - val_loss: 0.0953 - val_mean_absolute_error: 0.2728 - val_mean_absolute_percentage_error: 75167416.0000 - val_root_mean_squared_error: 0.3087
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - loss: 0.0994 - mean_absolute_error: 0.2715 - mean_absolute_percentage_error: 78123152.0000 - root_mean_squared_error: 0.3153 - val_loss: 0.0958 - val_mean_absolute_error: 0.2722 - val_mean_absolute_percentage_error: 72943952.0000 - val_root_mean_squared_error: 0.3095
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.0996 - mean_absolute_error: 0.2707 - mean_absolute_percentage_error: 76355520.0000 - root_mean_squared_error: 0.3155 - val_loss: 0.0961 - val_mean_absolute_error: 0.2718 - val_mean_absolute_percentage_error: 71352584.0000 - val_root_mean_squared_error: 0.3101
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 26s 2s/step - loss: 0.1021 - mean_absolute_error: 0.2732 - mean_absolute_percentage_error: 74244552.0000 - root_mean_squared_error: 0.3195 - val_loss: 0.0950 - val_mean_absolute_error: 0.2716 - val_mean_absolute_percentage_error: 73397240.0000 - val_root_mean_squared_error: 0.3082
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.0992 - mean_absolute_error: 0.2710 - mean_absolute_percentage_error: 76692040.0000 - root_mean_squared_error: 0.3149 - val_loss: 0.0937 - val_mean_absolute_error: 0.2711 - val_mean_absolute_percentage_error: 75666400.0000 - val_root_mean_squared_error: 0.3061
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.0999 - mean_absolute_error: 0.2731 - mean_absolute_percentage_error: 77807000.0000 - root_mean_squared_error: 0.3160 - val_loss: 0.0938 - val_mean_absolute_error: 0.2703 - val_mean_absolute_percentage_error: 74030144.0000 - val_root_mean_squared_error: 0.3062
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.0998 - mean_absolute_error: 0.2712 - mean_absolute_percentage_error: 78387008.0000 - root_mean_squared_error: 0.3159 - val_loss: 0.0934 - val_mean_absolute_error: 0.2694 - val_mean_absolute_percentage_error: 73362096.0000 - val_root_mean_squared_error: 0.3056
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.0995 - mean_absolute_error: 0.2713 - mean_absolute_percentage_error: 77916160.0000 - root_mean_squared_error: 0.3154 - val_loss: 0.0921 - val_mean_absolute_error: 0.2684 - val_mean_absolute_percentage_error: 74623088.0000 - val_root_mean_squared_error: 0.3034
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 18s 1s/step - loss: 0.0957 - mean_absolute_error: 0.2638 - mean_absolute_percentage_error: 71974752.0000 - root_mean_squared_error: 0.3093 - val_loss: 0.0927 - val_mean_absolute_error: 0.2671 - val_mean_absolute_percentage_error: 70762008.0000 - val_root_mean_squared_error: 0.3045
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.0978 - mean_absolute_error: 0.2687 - mean_absolute_percentage_error: 73331120.0000 - root_mean_squared_error: 0.3127 - val_loss: 0.0899 - val_mean_absolute_error: 0.2660 - val_mean_absolute_percentage_error: 75182896.0000 - val_root_mean_squared_error: 0.2999
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.0966 - mean_absolute_error: 0.2670 - mean_absolute_percentage_error: 77224840.0000 - root_mean_squared_error: 0.3109 - val_loss: 0.0902 - val_mean_absolute_error: 0.2637 - val_mean_absolute_percentage_error: 70491288.0000 - val_root_mean_squared_error: 0.3003
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 15s 1s/step - loss: 0.0970 - mean_absolute_error: 0.2660 - mean_absolute_percentage_error: 72351888.0000 - root_mean_squared_error: 0.3115 - val_loss: 0.0884 - val_mean_absolute_error: 0.2610 - val_mean_absolute_percentage_error: 70037304.0000 - val_root_mean_squared_error: 0.2973

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

23/23 ━━━━━━━━━━━━━━━━━━━━ 14s 357ms/step

array([[0.20636004],
       [0.21218029],
       [0.21842426],
       [0.23275986],
       [0.2622364 ],
       [0.26994184],
       [0.2747161 ],
       [0.27569607],
       [0.2718992 ],
       [0.27850738],
       [0.29675904],
       [0.29263696],
       [0.28222615],
       [0.2900171 ],
       [0.3074705 ],
       [0.3153673 ],
       [0.31506833],
       [0.3102987 ],
       [0.29964423],
       [0.27214795],
       [0.25492063],
       [0.2480689 ],
       [0.24975416],
       [0.2542193 ],
       [0.2717655 ],
       [0.30526367],
       [0.33614632],
       [0.36833432],
       [0.35459152],
       [0.3508117 ],
       [0.3559769 ],
       [0.3501242 ],
       [0.36101225],
       [0.38539514],
       [0.40035108],
       [0.41472885],
       [0.41750035],
       [0.41883606],
       [0.39787132],
       [0.37962183],
       [0.37038314],
       [0.35004583],
       [0.3481113 ],
       [0.34927365],
       [0.35650998],
       [0.36301   ],
       [0.39317036],
       [0.41795763],
       [0.42603204],
       [0.4331496 ],
       [0.43940407],
       [0.42926285],
       [0.42364535],
       [0.42964956],
       [0.41211015],
       [0.3925727 ],
       [0.36394086],
       [0.34132648],
       [0.32769963],
       [0.30736205],
       [0.30318037],
       [0.31004557],
       [0.34058717],
       [0.37450078],
       [0.4031734 ],
       [0.42958194],
       [0.44025847],
       [0.44430438],
       [0.4410262 ],
       [0.43169865],
       [0.432586  ],
       [0.4184551 ],
       [0.40779412],
       [0.39706013],
       [0.38667104],
       [0.37066358],
       [0.36220658],
       [0.35589454],
       [0.3773203 ],
       [0.3872982 ],
       [0.40140662],
       [0.416863  ],
       [0.4343307 ],
       [0.4449791 ],
       [0.4475694 ],
       [0.44213632],
       [0.42960364],
       [0.40087515],
       [0.38420898],
       [0.3731891 ],
       [0.38251242],
       [0.3915803 ],
       [0.4096193 ],
       [0.42817056],
       [0.44020793],
       [0.4496032 ],
       [0.4454363 ],
       [0.43924588],
       [0.43659225],
       [0.41959575],
       [0.40854317],
       [0.40228274],
       [0.3885933 ],
       [0.37311992],
       [0.36108026],
       [0.37911138],
       [0.3972041 ],
       [0.42139828],
       [0.44329962],
       [0.45924714],
       [0.46364635],
       [0.44811264],
       [0.4352171 ],
       [0.42174283],
       [0.4137409 ],
       [0.41108933],
       [0.41124192],
       [0.41102016],
       [0.40828717],
       [0.40915096],
       [0.41660726],
       [0.4042406 ],
       [0.3987995 ],
       [0.39373037],
       [0.38333586],
       [0.38348573],
       [0.38013238],
       [0.38402256],
       [0.39498904],
       [0.38119572],
       [0.36372033],
       [0.34922418],
       [0.36203817],
       [0.38205728],
       [0.40076506],
       [0.36084482],
       [0.3358312 ],
       [0.33246657],
       [0.3267099 ],
       [0.3229078 ],
       [0.3429433 ],
       [0.36232343],
       [0.34334883],
       [0.33939144],
       [0.3653608 ],
       [0.396737  ],
       [0.38862082],
       [0.37282088],
       [0.36068472],
       [0.36998627],
       [0.3533438 ],
       [0.35419106],
       [0.3528985 ],
       [0.36816463],
       [0.380212  ],
       [0.37571397],
       [0.3531191 ],
       [0.33550978],
       [0.3177137 ],
       [0.32949957],
       [0.32958248],
       [0.33965105],
       [0.35759872],
       [0.37801504],
       [0.38536713],
       [0.37645286],
       [0.36803034],
       [0.34820858],
       [0.3397917 ],
       [0.33821997],
       [0.36307925],
       [0.37371054],
       [0.37271342],
       [0.3727966 ],
       [0.37369385],
       [0.3934528 ],
       [0.3606064 ],
       [0.3690197 ],
       [0.3727545 ],
       [0.37567422],
       [0.38951686],
       [0.4047083 ],
       [0.41517955],
       [0.40231273],
       [0.39039925],
       [0.3823153 ],
       [0.37637973],
       [0.38342276],
       [0.38670972],
       [0.40248927],
       [0.38754   ],
       [0.3677803 ],
       [0.34521347],
       [0.33121476],
       [0.354138  ],
       [0.35908657],
       [0.3783153 ],
       [0.41523203],
       [0.43454114],
       [0.4434872 ],
       [0.42593604],
       [0.39681843],
       [0.36396238],
       [0.3508443 ],
       [0.35108575],
       [0.34896305],
       [0.36785445],
       [0.3973291 ],
       [0.40744188],
       [0.41236946],
       [0.42019704],
       [0.4251898 ],
       [0.42928693],
       [0.42466304],
       [0.4052175 ],
       [0.38935155],
       [0.37544665],
       [0.35122523],
       [0.33367702],
       [0.34431487],
       [0.34924808],
       [0.3719846 ],
       [0.39121595],
       [0.40352568],
       [0.40705928],
       [0.40482754],
       [0.38951835],
       [0.37028956],
       [0.34413618],
       [0.3210791 ],
       [0.30624852],
       [0.31711948],
       [0.31928778],
       [0.33744317],
       [0.36972004],
       [0.39338043],
       [0.4003818 ],
       [0.40902787],
       [0.4138113 ],
       [0.3915238 ],
       [0.36298868],
       [0.3449695 ],
       [0.33757272],
       [0.34212577],
       [0.36238322],
       [0.3785973 ],
       [0.39365748],
       [0.40432066],
       [0.41195968],
       [0.39455107],
       [0.3817818 ],
       [0.35771975],
       [0.32534352],
       [0.31464744],
       [0.32287595],
       [0.32610965],
       [0.34004417],
       [0.37009647],
       [0.3867871 ],
       [0.40237853],
       [0.41447756],
       [0.41743678],
       [0.41224173],
       [0.40802827],
       [0.3945017 ],
       [0.3799155 ],
       [0.36148557],
       [0.34924227],
       [0.3408078 ],
       [0.3276784 ],
       [0.35356298],
       [0.3721647 ],
       [0.39743325],
       [0.42613548],
       [0.4465506 ],
       [0.45553392],
       [0.45779747],
       [0.45518383],
       [0.4342423 ],
       [0.41021004],
       [0.3885822 ],
       [0.36946496],
       [0.37446293],
       [0.38081092],
       [0.3951406 ],
       [0.42121413],
       [0.4385679 ],
       [0.452554  ],
       [0.4567461 ],
       [0.43421143],
       [0.4036672 ],
       [0.37187827],
       [0.34562436],
       [0.3505401 ],
       [0.35723427],
       [0.37443966],
       [0.40164512],
       [0.4220225 ],
       [0.43843338],
       [0.4462714 ],
       [0.4491042 ],
       [0.43328598],
       [0.4121717 ],
       [0.3931152 ],
       [0.3763618 ],
       [0.37390274],
       [0.36998734],
       [0.37674952],
       [0.391361  ],
       [0.38372102],
       [0.37544215],
       [0.37104952],
       [0.36837253],
       [0.38001132],
       [0.38716832],
       [0.39721456],
       [0.41651228],
       [0.40299794],
       [0.39443177],
       [0.37295988],
       [0.34728926],
       [0.32645807],
       [0.3114655 ],
       [0.3233962 ],
       [0.34118772],
       [0.35494262],
       [0.3835949 ],
       [0.40495738],
       [0.4156292 ],
       [0.3973492 ],
       [0.364981  ],
       [0.33406228],
       [0.3197203 ],
       [0.31255537],
       [0.31696415],
       [0.34108257],
       [0.3744714 ],
       [0.39862093],
       [0.3812885 ],
       [0.3785941 ],
       [0.38252488],
       [0.40226904],
       [0.35712   ],
       [0.3218888 ],
       [0.3156058 ],
       [0.31291774],
       [0.32934275],
       [0.35448742],
       [0.3765337 ],
       [0.37376437],
       [0.34357715],
       [0.33952802],
       [0.34395579],
       [0.3540688 ],
       [0.3823127 ],
       [0.39623722],
       [0.4023735 ],
       [0.40480682],
       [0.40523157],
       [0.3793774 ],
       [0.35649195],
       [0.31853914],
       [0.29203257],
       [0.30009308],
       [0.32547054],
       [0.34664595],
       [0.3744998 ],
       [0.3933522 ],
       [0.37765417],
       [0.35980144],
       [0.34667584],
       [0.32092467],
       [0.3188258 ],
       [0.32144994],
       [0.32881913],
       [0.34205025],
       [0.36597714],
       [0.39125302],
       [0.37673575],
       [0.36238435],
       [0.34381944],
       [0.32238513],
       [0.30749318],
       [0.32298443],
       [0.3329678 ],
       [0.3551636 ],
       [0.3776126 ],
       [0.3883039 ],
       [0.38217503],
       [0.36505893],
       [0.35632083],
       [0.33439305],
       [0.3118819 ],
       [0.29295567],
       [0.28353125],
       [0.28499153],
       [0.29470047],
       [0.30310056],
       [0.3197622 ],
       [0.34485406],
       [0.3154758 ],
       [0.29545146],
       [0.27661207],
       [0.26935962],
       [0.26119995],
       [0.26877633],
       [0.2698414 ],
       [0.27873227],
       [0.29191417],
       [0.30894965],
       [0.32001325],
       [0.3268543 ],
       [0.31667063],
       [0.30708724],
       [0.30341452],
       [0.2931368 ],
       [0.28332454],
       [0.27708128],
       [0.28812987],
       [0.29968056],
       [0.31010792],
       [0.3117438 ],
       [0.3084031 ],
       [0.30681205],
       [0.3032526 ],
       [0.2939098 ],
       [0.28547367],
       [0.27783337],
       [0.2706847 ],
       [0.26572388],
       [0.25868762],
       [0.2646865 ],
       [0.26580065],
       [0.27554646],
       [0.29614088],
       [0.32046303],
       [0.33222702],
       [0.33034047],
       [0.31872472],
       [0.29425204],
       [0.2695499 ],
       [0.2517986 ],
       [0.2374126 ],
       [0.24278116],
       [0.25158662],
       [0.26695836],
       [0.2843681 ],
       [0.317556  ],
       [0.32841384],
       [0.3369865 ],
       [0.3428512 ],
       [0.33086422],
       [0.31290814],
       [0.29719645],
       [0.28720096],
       [0.26195642],
       [0.25220805],
       [0.23797825],
       [0.24026045],
       [0.26599672],
       [0.290154  ],
       [0.31252977],
       [0.33369187],
       [0.34428707],
       [0.3500224 ],
       [0.33643705],
       [0.30203423],
       [0.27467382],
       [0.24064425],
       [0.2293869 ],
       [0.22951719],
       [0.22619641],
       [0.22721535],
       [0.22827038],
       [0.23393136],
       [0.25433975],
       [0.27543625],
       [0.30337736],
       [0.32139292],
       [0.3383182 ],
       [0.3421009 ],
       [0.32871184],
       [0.314551  ],
       [0.28159213],
       [0.26272073],
       [0.25028846],
       [0.24506646],
       [0.2417211 ],
       [0.25635535],
       [0.27502865],
       [0.28983924],
       [0.30266583],
       [0.30386344],
       [0.30491582],
       [0.3047438 ],
       [0.28430477],
       [0.25878337],
       [0.23821336],
       [0.23105502],
       [0.22820783],
       [0.24472922],
       [0.27685526],
       [0.30261174],
       [0.30703774],
       [0.29494336],
       [0.29059952],
       [0.28401116],
       [0.30249542],
       [0.3110272 ],
       [0.32006985],
       [0.33023828],
       [0.3397807 ],
       [0.35070738],
       [0.35819015],
       [0.3520852 ],
       [0.34523216],
       [0.33858147],
       [0.32808042],
       [0.32513714],
       [0.32175604],
       [0.33974507],
       [0.35597494],
       [0.37535378],
       [0.3911494 ],
       [0.40385514],
       [0.408905  ],
       [0.40023628],
       [0.38850775],
       [0.35707703],
       [0.32571042],
       [0.3100524 ],
       [0.2951956 ],
       [0.30947986],
       [0.3204897 ],
       [0.3482068 ],
       [0.37934357],
       [0.41187832],
       [0.4394978 ],
       [0.4525037 ],
       [0.46245864],
       [0.4607184 ],
       [0.45196316],
       [0.45219746],
       [0.45057344],
       [0.441394  ],
       [0.42605713],
       [0.4223303 ],
       [0.41858837],
       [0.41937166],
       [0.43025738],
       [0.44185588],
       [0.46096078],
       [0.47172898],
       [0.47759524],
       [0.4788475 ],
       [0.47791323],
       [0.4762663 ],
       [0.4657714 ],
       [0.45513716],
       [0.44845682],
       [0.43772766],
       [0.4302195 ],
       [0.42746887],
       [0.42564762],
       [0.44616172],
       [0.45999184],
       [0.46872965],
       [0.4749517 ],
       [0.4768922 ],
       [0.47643313],
       [0.47742358],
       [0.47308215],
       [0.4743834 ],
       [0.47145298],
       [0.4682539 ],
       [0.46644828],
       [0.46240342],
       [0.46052402],
       [0.46428412],
       [0.46428338],
       [0.4723033 ],
       [0.4770894 ],
       [0.48103008],
       [0.48569733],
       [0.48903957],
       [0.48879907],
       [0.487403  ],
       [0.48551747],
       [0.47993806],
       [0.4622189 ],
       [0.44640335],
       [0.4309986 ],
       [0.42195717],
       [0.420067  ],
       [0.41850463],
       [0.4246152 ],
       [0.43326995],
       [0.43979368],
       [0.45482063],
       [0.46769738],
       [0.47487167],
       [0.4714093 ],
       [0.4683784 ],
       [0.45583662],
       [0.43454465],
       [0.4065777 ],
       [0.36890754],
       [0.34500432],
       [0.32629782],
       [0.32509583],
       [0.33211684],
       [0.35475355],
       [0.3706939 ],
       [0.39578718],
       [0.41967025],
       [0.42976922],
       [0.42886046],
       [0.42858028],
       [0.42936465],
       [0.42125842],
       [0.405108  ],
       [0.37002063],
       [0.33659187],
       [0.31031397],
       [0.2966917 ],
       [0.29223546],
       [0.29241955],
       [0.31013554],
       [0.31487203],
       [0.32782382],
       [0.3572024 ],
       [0.38360164],
       [0.38330558],
       [0.3427393 ],
       [0.34104875],
       [0.32977614],
       [0.32415292],
       [0.33371615],
       [0.34745243],
       [0.35841873],
       [0.3608226 ],
       [0.34652436],
       [0.33575097],
       [0.33691147],
       [0.354018  ],
       [0.36257434],
       [0.37756303],
       [0.37740633],
       [0.36972377],
       [0.37854627],
       [0.3951704 ],
       [0.41256627],
       [0.41881543],
       [0.42971155],
       [0.43639752],
       [0.43129155],
       [0.42959097],
       [0.42794415],
       [0.43536302],
       [0.44276384],
       [0.44564763],
       [0.42214426],
       [0.4081637 ],
       [0.40560734],
       [0.41167122],
       [0.3911687 ],
       [0.3950778 ],
       [0.40452614],
       [0.42559424],
       [0.4481349 ],
       [0.46471885],
       [0.4525293 ],
       [0.44723585],
       [0.4508355 ],
       [0.45206717],
       [0.4559318 ],
       [0.46648222],
       [0.45677352],
       [0.44938645],
       [0.4451973 ],
       [0.45485994],
       [0.46499726],
       [0.45370302],
       [0.44379953],
       [0.438194  ],
       [0.43251124],
       [0.43191484],
       [0.4427744 ],
       [0.45497015],
       [0.46165368],
       [0.46129414],
       [0.4579831 ],
       [0.4532792 ],
       [0.44790605],
       [0.44055822],
       [0.43866876],
       [0.42706522],
       [0.4083926 ],
       [0.3904235 ],
       [0.37938085],
       [0.39240912],
       [0.39540142],
       [0.41493765],
       [0.43233365],
       [0.43894795],
       [0.4418626 ],
       [0.44705144],
       [0.44468227],
       [0.4391256 ],
       [0.42849752],
       [0.4152319 ],
       [0.39935818],
       [0.39252618],
       [0.37847698],
       [0.3682772 ],
       [0.35684597],
       [0.3710879 ],
       [0.39899564],
       [0.43171713],
       [0.44375074],
       [0.44480836],
       [0.43222544],
       [0.41749585],
       [0.3749239 ],
       [0.3357257 ],
       [0.3092844 ],
       [0.3070796 ],
       [0.30920094],
       [0.32466108],
       [0.32345065],
       [0.3331455 ],
       [0.35258877],
       [0.38088694],
       [0.40366897],
       [0.40278998]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
16400       642.0   1485.421686   1850.979413           NaN
16401      6804.0  11718.606066  11182.089488           NaN
16402     10501.0  18614.042112  19279.054526           NaN
16403     13147.0   17689.00615  17438.807493           NaN
16404     15536.0  17039.389972  16974.916203           NaN
...           ...           ...           ...           ...
18273      7356.0   6900.654023   5846.106045   9994.365234
18274     17638.0   20543.60541  19516.687678  10577.663086
18275     23339.0  23189.371101  21231.472263  11426.608398
18276     26323.0  26104.467998  24456.544978  12110.069336
18278     25598.0   26678.02481    26577.9225  12083.699219

[783 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 120s 6s/step - loss: 0.1741 - mean_absolute_error: 0.2840 - mean_absolute_percentage_error: 8652461.0000 - root_mean_squared_error: 0.4171 - val_loss: 0.1036 - val_mean_absolute_error: 0.2757 - val_mean_absolute_percentage_error: 62603792.0000 - val_root_mean_squared_error: 0.3218
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 4s/step - loss: 0.1165 - mean_absolute_error: 0.2947 - mean_absolute_percentage_error: 81631552.0000 - root_mean_squared_error: 0.3413 - val_loss: 0.0972 - val_mean_absolute_error: 0.2881 - val_mean_absolute_percentage_error: 112659272.0000 - val_root_mean_squared_error: 0.3118
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 43s 4s/step - loss: 0.1097 - mean_absolute_error: 0.2949 - mean_absolute_percentage_error: 89104056.0000 - root_mean_squared_error: 0.3312 - val_loss: 0.0983 - val_mean_absolute_error: 0.2759 - val_mean_absolute_percentage_error: 72689152.0000 - val_root_mean_squared_error: 0.3136
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.1111 - mean_absolute_error: 0.2835 - mean_absolute_percentage_error: 67053372.0000 - root_mean_squared_error: 0.3334 - val_loss: 0.0943 - val_mean_absolute_error: 0.2781 - val_mean_absolute_percentage_error: 87387664.0000 - val_root_mean_squared_error: 0.3070
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 31s 5s/step - loss: 0.1069 - mean_absolute_error: 0.2898 - mean_absolute_percentage_error: 82570328.0000 - root_mean_squared_error: 0.3270 - val_loss: 0.0944 - val_mean_absolute_error: 0.2828 - val_mean_absolute_percentage_error: 101761920.0000 - val_root_mean_squared_error: 0.3072
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 27s 5s/step - loss: 0.1062 - mean_absolute_error: 0.2926 - mean_absolute_percentage_error: 92926776.0000 - root_mean_squared_error: 0.3260 - val_loss: 0.0938 - val_mean_absolute_error: 0.2795 - val_mean_absolute_percentage_error: 92805848.0000 - val_root_mean_squared_error: 0.3063
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 5s/step - loss: 0.1071 - mean_absolute_error: 0.2901 - mean_absolute_percentage_error: 80608256.0000 - root_mean_squared_error: 0.3273 - val_loss: 0.0943 - val_mean_absolute_error: 0.2780 - val_mean_absolute_percentage_error: 86870264.0000 - val_root_mean_squared_error: 0.3071
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 6s/step - loss: 0.1068 - mean_absolute_error: 0.2877 - mean_absolute_percentage_error: 78926760.0000 - root_mean_squared_error: 0.3267 - val_loss: 0.0939 - val_mean_absolute_error: 0.2791 - val_mean_absolute_percentage_error: 91626712.0000 - val_root_mean_squared_error: 0.3064
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 6s/step - loss: 0.1068 - mean_absolute_error: 0.2912 - mean_absolute_percentage_error: 83919408.0000 - root_mean_squared_error: 0.3269 - val_loss: 0.0938 - val_mean_absolute_error: 0.2804 - val_mean_absolute_percentage_error: 95735848.0000 - val_root_mean_squared_error: 0.3063
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 5s/step - loss: 0.1078 - mean_absolute_error: 0.2927 - mean_absolute_percentage_error: 86743648.0000 - root_mean_squared_error: 0.3283 - val_loss: 0.0939 - val_mean_absolute_error: 0.2788 - val_mean_absolute_percentage_error: 90282144.0000 - val_root_mean_squared_error: 0.3065
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 6s/step - loss: 0.1075 - mean_absolute_error: 0.2902 - mean_absolute_percentage_error: 84059824.0000 - root_mean_squared_error: 0.3278 - val_loss: 0.0941 - val_mean_absolute_error: 0.2783 - val_mean_absolute_percentage_error: 88489736.0000 - val_root_mean_squared_error: 0.3067
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.1032 - mean_absolute_error: 0.2858 - mean_absolute_percentage_error: 85362464.0000 - root_mean_squared_error: 0.3212 - val_loss: 0.0938 - val_mean_absolute_error: 0.2786 - val_mean_absolute_percentage_error: 90105992.0000 - val_root_mean_squared_error: 0.3063
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 5s/step - loss: 0.1037 - mean_absolute_error: 0.2877 - mean_absolute_percentage_error: 85726904.0000 - root_mean_squared_error: 0.3221 - val_loss: 0.0962 - val_mean_absolute_error: 0.2760 - val_mean_absolute_percentage_error: 77553832.0000 - val_root_mean_squared_error: 0.3102
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 5s/step - loss: 0.1012 - mean_absolute_error: 0.2797 - mean_absolute_percentage_error: 77639344.0000 - root_mean_squared_error: 0.3182 - val_loss: 0.0969 - val_mean_absolute_error: 0.2750 - val_mean_absolute_percentage_error: 76260528.0000 - val_root_mean_squared_error: 0.3113
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 39s 4s/step - loss: 0.1020 - mean_absolute_error: 0.2780 - mean_absolute_percentage_error: 76421968.0000 - root_mean_squared_error: 0.3194 - val_loss: 0.0932 - val_mean_absolute_error: 0.2766 - val_mean_absolute_percentage_error: 89024296.0000 - val_root_mean_squared_error: 0.3052
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 4s/step - loss: 0.0996 - mean_absolute_error: 0.2771 - mean_absolute_percentage_error: 84094832.0000 - root_mean_squared_error: 0.3156 - val_loss: 0.0927 - val_mean_absolute_error: 0.2747 - val_mean_absolute_percentage_error: 86492032.0000 - val_root_mean_squared_error: 0.3045
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 44s 4s/step - loss: 0.0997 - mean_absolute_error: 0.2754 - mean_absolute_percentage_error: 86784120.0000 - root_mean_squared_error: 0.3157 - val_loss: 0.0923 - val_mean_absolute_error: 0.2718 - val_mean_absolute_percentage_error: 81409944.0000 - val_root_mean_squared_error: 0.3039
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 34s 6s/step - loss: 0.0994 - mean_absolute_error: 0.2759 - mean_absolute_percentage_error: 82473416.0000 - root_mean_squared_error: 0.3153 - val_loss: 0.0905 - val_mean_absolute_error: 0.2714 - val_mean_absolute_percentage_error: 85613256.0000 - val_root_mean_squared_error: 0.3008
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 6s/step - loss: 0.0981 - mean_absolute_error: 0.2726 - mean_absolute_percentage_error: 83872304.0000 - root_mean_squared_error: 0.3131 - val_loss: 0.0852 - val_mean_absolute_error: 0.2644 - val_mean_absolute_percentage_error: 89034288.0000 - val_root_mean_squared_error: 0.2919
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.0953 - mean_absolute_error: 0.2674 - mean_absolute_percentage_error: 82331696.0000 - root_mean_squared_error: 0.3087 - val_loss: 0.0791 - val_mean_absolute_error: 0.2539 - val_mean_absolute_percentage_error: 84664720.0000 - val_root_mean_squared_error: 0.2812
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 33s 6s/step - loss: 0.0878 - mean_absolute_error: 0.2555 - mean_absolute_percentage_error: 80778936.0000 - root_mean_squared_error: 0.2962 - val_loss: 0.0495 - val_mean_absolute_error: 0.1872 - val_mean_absolute_percentage_error: 57213072.0000 - val_root_mean_squared_error: 0.2225
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 49s 7s/step - loss: 0.0649 - mean_absolute_error: 0.2027 - mean_absolute_percentage_error: 56174132.0000 - root_mean_squared_error: 0.2547 - val_loss: 0.0397 - val_mean_absolute_error: 0.1546 - val_mean_absolute_percentage_error: 51853032.0000 - val_root_mean_squared_error: 0.1992
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 5s/step - loss: 0.0641 - mean_absolute_error: 0.1967 - mean_absolute_percentage_error: 52730064.0000 - root_mean_squared_error: 0.2532 - val_loss: 0.0429 - val_mean_absolute_error: 0.1636 - val_mean_absolute_percentage_error: 55834984.0000 - val_root_mean_squared_error: 0.2072
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 43s 5s/step - loss: 0.0616 - mean_absolute_error: 0.1934 - mean_absolute_percentage_error: 54911916.0000 - root_mean_squared_error: 0.2481 - val_loss: 0.0443 - val_mean_absolute_error: 0.1670 - val_mean_absolute_percentage_error: 42844420.0000 - val_root_mean_squared_error: 0.2104
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 27s 5s/step - loss: 0.0606 - mean_absolute_error: 0.1916 - mean_absolute_percentage_error: 45290516.0000 - root_mean_squared_error: 0.2462 - val_loss: 0.0417 - val_mean_absolute_error: 0.1514 - val_mean_absolute_percentage_error: 42937548.0000 - val_root_mean_squared_error: 0.2043
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 54s 6s/step - loss: 0.0591 - mean_absolute_error: 0.1829 - mean_absolute_percentage_error: 48948256.0000 - root_mean_squared_error: 0.2430 - val_loss: 0.0411 - val_mean_absolute_error: 0.1620 - val_mean_absolute_percentage_error: 45088080.0000 - val_root_mean_squared_error: 0.2027
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 5s/step - loss: 0.0550 - mean_absolute_error: 0.1812 - mean_absolute_percentage_error: 44451228.0000 - root_mean_squared_error: 0.2345 - val_loss: 0.0371 - val_mean_absolute_error: 0.1400 - val_mean_absolute_percentage_error: 35068320.0000 - val_root_mean_squared_error: 0.1925
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 45s 7s/step - loss: 0.0547 - mean_absolute_error: 0.1714 - mean_absolute_percentage_error: 40927240.0000 - root_mean_squared_error: 0.2339 - val_loss: 0.0365 - val_mean_absolute_error: 0.1527 - val_mean_absolute_percentage_error: 50606644.0000 - val_root_mean_squared_error: 0.1911
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 6s/step - loss: 0.0531 - mean_absolute_error: 0.1754 - mean_absolute_percentage_error: 44691764.0000 - root_mean_squared_error: 0.2305 - val_loss: 0.0349 - val_mean_absolute_error: 0.1469 - val_mean_absolute_percentage_error: 46116876.0000 - val_root_mean_squared_error: 0.1868
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 7s/step - loss: 0.0516 - mean_absolute_error: 0.1697 - mean_absolute_percentage_error: 37547832.0000 - root_mean_squared_error: 0.2271 - val_loss: 0.0324 - val_mean_absolute_error: 0.1323 - val_mean_absolute_percentage_error: 34575716.0000 - val_root_mean_squared_error: 0.1801
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 6s/step - loss: 0.0512 - mean_absolute_error: 0.1621 - mean_absolute_percentage_error: 35328016.0000 - root_mean_squared_error: 0.2262 - val_loss: 0.0364 - val_mean_absolute_error: 0.1553 - val_mean_absolute_percentage_error: 55185756.0000 - val_root_mean_squared_error: 0.1909
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 47s 7s/step - loss: 0.0504 - mean_absolute_error: 0.1779 - mean_absolute_percentage_error: 50340728.0000 - root_mean_squared_error: 0.2245 - val_loss: 0.0345 - val_mean_absolute_error: 0.1436 - val_mean_absolute_percentage_error: 43293768.0000 - val_root_mean_squared_error: 0.1857
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 39s 6s/step - loss: 0.0497 - mean_absolute_error: 0.1622 - mean_absolute_percentage_error: 37843660.0000 - root_mean_squared_error: 0.2230 - val_loss: 0.0339 - val_mean_absolute_error: 0.1374 - val_mean_absolute_percentage_error: 37544156.0000 - val_root_mean_squared_error: 0.1842
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 44s 6s/step - loss: 0.0462 - mean_absolute_error: 0.1544 - mean_absolute_percentage_error: 32809268.0000 - root_mean_squared_error: 0.2150 - val_loss: 0.0316 - val_mean_absolute_error: 0.1275 - val_mean_absolute_percentage_error: 28851644.0000 - val_root_mean_squared_error: 0.1778
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 39s 5s/step - loss: 0.0459 - mean_absolute_error: 0.1487 - mean_absolute_percentage_error: 31495768.0000 - root_mean_squared_error: 0.2142 - val_loss: 0.0304 - val_mean_absolute_error: 0.1244 - val_mean_absolute_percentage_error: 29000168.0000 - val_root_mean_squared_error: 0.1744
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 44s 5s/step - loss: 0.0424 - mean_absolute_error: 0.1469 - mean_absolute_percentage_error: 32381506.0000 - root_mean_squared_error: 0.2059 - val_loss: 0.0324 - val_mean_absolute_error: 0.1276 - val_mean_absolute_percentage_error: 28787356.0000 - val_root_mean_squared_error: 0.1799
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 5s/step - loss: 0.0419 - mean_absolute_error: 0.1404 - mean_absolute_percentage_error: 29771854.0000 - root_mean_squared_error: 0.2047 - val_loss: 0.0316 - val_mean_absolute_error: 0.1253 - val_mean_absolute_percentage_error: 30943092.0000 - val_root_mean_squared_error: 0.1777
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 8s/step - loss: 0.0409 - mean_absolute_error: 0.1413 - mean_absolute_percentage_error: 31772128.0000 - root_mean_squared_error: 0.2022 - val_loss: 0.0303 - val_mean_absolute_error: 0.1201 - val_mean_absolute_percentage_error: 26357164.0000 - val_root_mean_squared_error: 0.1740
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 35s 5s/step - loss: 0.0425 - mean_absolute_error: 0.1406 - mean_absolute_percentage_error: 30820950.0000 - root_mean_squared_error: 0.2061 - val_loss: 0.0310 - val_mean_absolute_error: 0.1170 - val_mean_absolute_percentage_error: 22985152.0000 - val_root_mean_squared_error: 0.1761
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 53s 7s/step - loss: 0.0414 - mean_absolute_error: 0.1382 - mean_absolute_percentage_error: 27724510.0000 - root_mean_squared_error: 0.2036 - val_loss: 0.0419 - val_mean_absolute_error: 0.1578 - val_mean_absolute_percentage_error: 47234548.0000 - val_root_mean_squared_error: 0.2046
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 85s 8s/step - loss: 0.0432 - mean_absolute_error: 0.1481 - mean_absolute_percentage_error: 35262444.0000 - root_mean_squared_error: 0.2078 - val_loss: 0.0338 - val_mean_absolute_error: 0.1253 - val_mean_absolute_percentage_error: 24657642.0000 - val_root_mean_squared_error: 0.1840
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 5s/step - loss: 0.0419 - mean_absolute_error: 0.1376 - mean_absolute_percentage_error: 29634680.0000 - root_mean_squared_error: 0.2046 - val_loss: 0.0327 - val_mean_absolute_error: 0.1274 - val_mean_absolute_percentage_error: 22040590.0000 - val_root_mean_squared_error: 0.1808
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 58s 8s/step - loss: 0.0421 - mean_absolute_error: 0.1407 - mean_absolute_percentage_error: 25750560.0000 - root_mean_squared_error: 0.2051 - val_loss: 0.0334 - val_mean_absolute_error: 0.1138 - val_mean_absolute_percentage_error: 13959020.0000 - val_root_mean_squared_error: 0.1827
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 83s 6s/step - loss: 0.0400 - mean_absolute_error: 0.1364 - mean_absolute_percentage_error: 27070352.0000 - root_mean_squared_error: 0.2000 - val_loss: 0.0327 - val_mean_absolute_error: 0.1174 - val_mean_absolute_percentage_error: 17955196.0000 - val_root_mean_squared_error: 0.1807
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 44s 7s/step - loss: 0.0392 - mean_absolute_error: 0.1286 - mean_absolute_percentage_error: 25315314.0000 - root_mean_squared_error: 0.1980 - val_loss: 0.0349 - val_mean_absolute_error: 0.1348 - val_mean_absolute_percentage_error: 29463712.0000 - val_root_mean_squared_error: 0.1868
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 39s 6s/step - loss: 0.0391 - mean_absolute_error: 0.1385 - mean_absolute_percentage_error: 29837714.0000 - root_mean_squared_error: 0.1978 - val_loss: 0.0302 - val_mean_absolute_error: 0.1153 - val_mean_absolute_percentage_error: 21968562.0000 - val_root_mean_squared_error: 0.1737
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 32s 5s/step - loss: 0.0367 - mean_absolute_error: 0.1309 - mean_absolute_percentage_error: 26329116.0000 - root_mean_squared_error: 0.1916 - val_loss: 0.0311 - val_mean_absolute_error: 0.1157 - val_mean_absolute_percentage_error: 22430550.0000 - val_root_mean_squared_error: 0.1763
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 42s 5s/step - loss: 0.0365 - mean_absolute_error: 0.1262 - mean_absolute_percentage_error: 26183322.0000 - root_mean_squared_error: 0.1910 - val_loss: 0.0331 - val_mean_absolute_error: 0.1201 - val_mean_absolute_percentage_error: 22184394.0000 - val_root_mean_squared_error: 0.1818
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 5s/step - loss: 0.0376 - mean_absolute_error: 0.1291 - mean_absolute_percentage_error: 25717712.0000 - root_mean_squared_error: 0.1940 - val_loss: 0.0331 - val_mean_absolute_error: 0.1166 - val_mean_absolute_percentage_error: 17431074.0000 - val_root_mean_squared_error: 0.1820
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.0367 - mean_absolute_error: 0.1263 - mean_absolute_percentage_error: 24282790.0000 - root_mean_squared_error: 0.1917 - val_loss: 0.0337 - val_mean_absolute_error: 0.1158 - val_mean_absolute_percentage_error: 22456322.0000 - val_root_mean_squared_error: 0.1836

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

23/23 ━━━━━━━━━━━━━━━━━━━━ 24s 429ms/step

array([[0.01158301],
       [0.01909353],
       [0.10304229],
       [0.5667744 ],
       [0.57705253],
       [0.82304674],
       [0.01873512],
       [0.1178408 ],
       [0.60313505],
       [0.70437944],
       [0.7857744 ],
       [0.80544645],
       [0.20825447],
       [0.6573958 ],
       [0.7080984 ],
       [0.709789  ],
       [0.7446922 ],
       [0.7440092 ],
       [0.5094593 ],
       [0.0256865 ],
       [0.01241064],
       [0.01837815],
       [0.01820627],
       [0.12468305],
       [0.64880735],
       [0.6628656 ],
       [0.735369  ],
       [0.80515605],
       [0.06171402],
       [0.02783627],
       [0.03151066],
       [0.18363217],
       [0.64018166],
       [0.65750664],
       [0.60417074],
       [0.5286783 ],
       [0.48038572],
       [0.49012214],
       [0.23361686],
       [0.31374952],
       [0.43672037],
       [0.4347693 ],
       [0.49195656],
       [0.2677983 ],
       [0.09438153],
       [0.06850504],
       [0.03269611],
       [0.12901546],
       [0.22177805],
       [0.45099786],
       [0.70773953],
       [0.46822697],
       [0.14172742],
       [0.6910676 ],
       [0.69441235],
       [0.56895983],
       [0.6087649 ],
       [0.34289357],
       [0.49922633],
       [0.25728315],
       [0.06232334],
       [0.02511792],
       [0.02418379],
       [0.16561268],
       [0.63401014],
       [0.6565501 ],
       [0.7156201 ],
       [0.74194854],
       [0.74524635],
       [0.7221152 ],
       [0.74653697],
       [0.69909906],
       [0.6464985 ],
       [0.5847486 ],
       [0.5690212 ],
       [0.20274691],
       [0.01527958],
       [0.00943537],
       [0.14486511],
       [0.18136056],
       [0.62976897],
       [0.67610663],
       [0.7347703 ],
       [0.79615587],
       [0.82785827],
       [0.7809658 ],
       [0.65762776],
       [0.33741018],
       [0.04628066],
       [0.02713242],
       [0.01867801],
       [0.17467268],
       [0.66112417],
       [0.68974346],
       [0.7183799 ],
       [0.7469029 ],
       [0.78492874],
       [0.7713848 ],
       [0.69914585],
       [0.70975393],
       [0.69723123],
       [0.65119696],
       [0.33266592],
       [0.04638562],
       [0.01814102],
       [0.24453607],
       [0.32062453],
       [0.7016514 ],
       [0.7461423 ],
       [0.81042767],
       [0.7449848 ],
       [0.55428857],
       [0.0312418 ],
       [0.19796002],
       [0.641406  ],
       [0.71760505],
       [0.7694127 ],
       [0.80940443],
       [0.8163715 ],
       [0.76927954],
       [0.73506206],
       [0.7040422 ],
       [0.6303474 ],
       [0.5057577 ],
       [0.03775865],
       [0.25941858],
       [0.41542047],
       [0.61499673],
       [0.42484143],
       [0.2997119 ],
       [0.02328646],
       [0.14066516],
       [0.67524725],
       [0.7297718 ],
       [0.7532664 ],
       [0.01367486],
       [0.01532494],
       [0.01611108],
       [0.07996535],
       [0.61317736],
       [0.7503592 ],
       [0.70167106],
       [0.02684789],
       [0.09392308],
       [0.6640152 ],
       [0.7757082 ],
       [0.3316836 ],
       [0.15850937],
       [0.50322944],
       [0.24945761],
       [0.0277845 ],
       [0.15078548],
       [0.6058385 ],
       [0.70156723],
       [0.7494431 ],
       [0.7418355 ],
       [0.06284161],
       [0.02266747],
       [0.02867476],
       [0.02598827],
       [0.10376915],
       [0.5902541 ],
       [0.6616966 ],
       [0.65873665],
       [0.5862134 ],
       [0.5708547 ],
       [0.54793906],
       [0.03127923],
       [0.15708432],
       [0.5955089 ],
       [0.6332653 ],
       [0.5648765 ],
       [0.03052048],
       [0.09855545],
       [0.56716335],
       [0.64292616],
       [0.06134596],
       [0.0298032 ],
       [0.3508358 ],
       [0.45446658],
       [0.22896172],
       [0.7233358 ],
       [0.7408084 ],
       [0.73688716],
       [0.02708764],
       [0.11645328],
       [0.51944596],
       [0.6051117 ],
       [0.7094576 ],
       [0.757668  ],
       [0.13711554],
       [0.11687011],
       [0.0269967 ],
       [0.01966585],
       [0.02524278],
       [0.10009916],
       [0.6000665 ],
       [0.68457097],
       [0.7503291 ],
       [0.7863851 ],
       [0.3198105 ],
       [0.18704431],
       [0.03156016],
       [0.03876604],
       [0.02719705],
       [0.36974418],
       [0.65282327],
       [0.6759346 ],
       [0.69696456],
       [0.6895674 ],
       [0.67640597],
       [0.641162  ],
       [0.6154807 ],
       [0.58539146],
       [0.65328133],
       [0.65095466],
       [0.6164881 ],
       [0.01890177],
       [0.02312971],
       [0.29282397],
       [0.51731604],
       [0.6790862 ],
       [0.7259943 ],
       [0.81970686],
       [0.82843465],
       [0.78527206],
       [0.83121186],
       [0.5137646 ],
       [0.02714878],
       [0.01469777],
       [0.01766564],
       [0.02392159],
       [0.12235114],
       [0.68726873],
       [0.74748737],
       [0.7845773 ],
       [0.79801506],
       [0.7792007 ],
       [0.7456164 ],
       [0.28551924],
       [0.04078368],
       [0.02370492],
       [0.10859233],
       [0.6839786 ],
       [0.73210585],
       [0.79813063],
       [0.80830604],
       [0.80659133],
       [0.78678197],
       [0.41916472],
       [0.55279964],
       [0.3878647 ],
       [0.01291309],
       [0.0121268 ],
       [0.01933616],
       [0.06696836],
       [0.59547335],
       [0.6875817 ],
       [0.7834744 ],
       [0.79194385],
       [0.77548987],
       [0.7424161 ],
       [0.71519595],
       [0.6859703 ],
       [0.6670277 ],
       [0.6280622 ],
       [0.57099354],
       [0.3360265 ],
       [0.0181682 ],
       [0.01272697],
       [0.02173734],
       [0.09773412],
       [0.62351125],
       [0.70660365],
       [0.8054519 ],
       [0.7859614 ],
       [0.7682521 ],
       [0.7455942 ],
       [0.3384285 ],
       [0.02750834],
       [0.01118052],
       [0.01304714],
       [0.02570474],
       [0.1223343 ],
       [0.69200927],
       [0.74586004],
       [0.8067048 ],
       [0.770623  ],
       [0.6417312 ],
       [0.22734521],
       [0.02333022],
       [0.02048525],
       [0.01313068],
       [0.02853332],
       [0.12144032],
       [0.6348771 ],
       [0.67468566],
       [0.69868   ],
       [0.69356436],
       [0.6844619 ],
       [0.6731936 ],
       [0.15845554],
       [0.02381376],
       [0.01362361],
       [0.01221345],
       [0.02882221],
       [0.12912573],
       [0.69829375],
       [0.45409828],
       [0.25816104],
       [0.03185051],
       [0.0245434 ],
       [0.01559737],
       [0.02286514],
       [0.08799207],
       [0.6477071 ],
       [0.44621998],
       [0.15941395],
       [0.24968563],
       [0.31464106],
       [0.04282229],
       [0.01894864],
       [0.02323811],
       [0.02697921],
       [0.09441693],
       [0.55998546],
       [0.6522276 ],
       [0.74522364],
       [0.7172565 ],
       [0.3771876 ],
       [0.12254183],
       [0.02447738],
       [0.01770341],
       [0.02729344],
       [0.11259511],
       [0.6651119 ],
       [0.73763055],
       [0.75034684],
       [0.01527719],
       [0.07133339],
       [0.63768965],
       [0.7369343 ],
       [0.05463596],
       [0.01856218],
       [0.01994109],
       [0.09058498],
       [0.6428026 ],
       [0.6966878 ],
       [0.6590645 ],
       [0.54305774],
       [0.02672056],
       [0.02383399],
       [0.0890695 ],
       [0.6497446 ],
       [0.7302186 ],
       [0.73917216],
       [0.72829133],
       [0.7629086 ],
       [0.6993484 ],
       [0.27185908],
       [0.0492082 ],
       [0.02162542],
       [0.01800785],
       [0.02393664],
       [0.34086716],
       [0.51112044],
       [0.29002175],
       [0.68617094],
       [0.19521989],
       [0.14647022],
       [0.02363386],
       [0.02291431],
       [0.0258793 ],
       [0.10736026],
       [0.5570884 ],
       [0.6173187 ],
       [0.671114  ],
       [0.69066316],
       [0.31965664],
       [0.27566054],
       [0.41608354],
       [0.06576388],
       [0.0222181 ],
       [0.02206847],
       [0.08361185],
       [0.6474241 ],
       [0.69705874],
       [0.6769813 ],
       [0.6088328 ],
       [0.35697666],
       [0.5293453 ],
       [0.4705024 ],
       [0.22302054],
       [0.03718836],
       [0.02640512],
       [0.24939735],
       [0.34996969],
       [0.58496076],
       [0.6712408 ],
       [0.5127533 ],
       [0.20092094],
       [0.10932599],
       [0.23680817],
       [0.09438394],
       [0.03490337],
       [0.38982755],
       [0.42643812],
       [0.6515024 ],
       [0.7325066 ],
       [0.5209683 ],
       [0.55930096],
       [0.6921001 ],
       [0.4630164 ],
       [0.42675495],
       [0.364759  ],
       [0.20840773],
       [0.15158994],
       [0.08609104],
       [0.07008323],
       [0.1164078 ],
       [0.11999863],
       [0.01659087],
       [0.02900208],
       [0.05879312],
       [0.26444575],
       [0.53569263],
       [0.20954825],
       [0.12983212],
       [0.11795731],
       [0.09612736],
       [0.06022039],
       [0.04192409],
       [0.13812009],
       [0.53011835],
       [0.7020228 ],
       [0.06460008],
       [0.13287716],
       [0.43382752],
       [0.5834928 ],
       [0.10396743],
       [0.04506547],
       [0.07410906],
       [0.03679143],
       [0.05065689],
       [0.08102892],
       [0.55089897],
       [0.57036954],
       [0.34966356],
       [0.39357522],
       [0.01273811],
       [0.46216816],
       [0.43613148],
       [0.48746496],
       [0.4428963 ],
       [0.41948152],
       [0.29758108],
       [0.11659645],
       [0.03023309],
       [0.02011403],
       [0.06026387],
       [0.36888367],
       [0.6134112 ],
       [0.6433169 ],
       [0.36372614],
       [0.13412608],
       [0.29948902],
       [0.26255965],
       [0.04666172],
       [0.40226954],
       [0.23024113],
       [0.37340823],
       [0.30441123],
       [0.12127648],
       [0.03843832],
       [0.02358897],
       [0.01776033],
       [0.05450695],
       [0.55003935],
       [0.6083335 ],
       [0.72447914],
       [0.28456357],
       [0.24175464],
       [0.4348108 ],
       [0.5967861 ],
       [0.06390198],
       [0.01648942],
       [0.01132469],
       [0.0121302 ],
       [0.1722915 ],
       [0.5099436 ],
       [0.78606725],
       [0.81945187],
       [0.843249  ],
       [0.5979547 ],
       [0.36931953],
       [0.24101432],
       [0.02009702],
       [0.01258081],
       [0.01650868],
       [0.03065688],
       [0.65596265],
       [0.7090077 ],
       [0.71696717],
       [0.6630036 ],
       [0.0151578 ],
       [0.03424272],
       [0.5117716 ],
       [0.6390754 ],
       [0.7663112 ],
       [0.7683651 ],
       [0.7393434 ],
       [0.68977195],
       [0.66540736],
       [0.67832893],
       [0.6710304 ],
       [0.6510165 ],
       [0.5608675 ],
       [0.14041114],
       [0.07379203],
       [0.03042318],
       [0.01633182],
       [0.06295725],
       [0.6655051 ],
       [0.73035777],
       [0.72989225],
       [0.82028157],
       [0.80351466],
       [0.7193703 ],
       [0.62151855],
       [0.32748413],
       [0.04085011],
       [0.01779753],
       [0.02254926],
       [0.0697339 ],
       [0.5513971 ],
       [0.70025283],
       [0.7788672 ],
       [0.81866854],
       [0.81963366],
       [0.78212136],
       [0.71940833],
       [0.68845713],
       [0.6985132 ],
       [0.71058863],
       [0.615302  ],
       [0.22860688],
       [0.14384392],
       [0.11085002],
       [0.03961362],
       [0.18140899],
       [0.6767193 ],
       [0.7325385 ],
       [0.76499325],
       [0.7554375 ],
       [0.71378094],
       [0.64589506],
       [0.6094731 ],
       [0.6827135 ],
       [0.63923216],
       [0.57103074],
       [0.5471224 ],
       [0.24877192],
       [0.07445417],
       [0.02952401],
       [0.03523596],
       [0.10814989],
       [0.5767655 ],
       [0.67747253],
       [0.77691394],
       [0.81407684],
       [0.84417284],
       [0.84494734],
       [0.77616614],
       [0.753138  ],
       [0.6767812 ],
       [0.5602465 ],
       [0.40574962],
       [0.11818844],
       [0.08353069],
       [0.03003775],
       [0.03501514],
       [0.10587865],
       [0.6049282 ],
       [0.6914584 ],
       [0.752619  ],
       [0.7731127 ],
       [0.8107973 ],
       [0.7885813 ],
       [0.6999188 ],
       [0.67762905],
       [0.52256453],
       [0.3333287 ],
       [0.10164678],
       [0.08551459],
       [0.02159604],
       [0.0229393 ],
       [0.43023595],
       [0.6746388 ],
       [0.7442647 ],
       [0.7491614 ],
       [0.71350294],
       [0.74683774],
       [0.72194546],
       [0.79182637],
       [0.79664546],
       [0.6584783 ],
       [0.4105617 ],
       [0.38461047],
       [0.15485351],
       [0.03665384],
       [0.01732455],
       [0.02056481],
       [0.09726849],
       [0.5802419 ],
       [0.73014313],
       [0.77991843],
       [0.80707425],
       [0.8508935 ],
       [0.76178896],
       [0.73502547],
       [0.781236  ],
       [0.68509775],
       [0.48016375],
       [0.23896563],
       [0.02797791],
       [0.0338333 ],
       [0.01559462],
       [0.3023018 ],
       [0.32518888],
       [0.6645263 ],
       [0.7490148 ],
       [0.8218974 ],
       [0.7863043 ],
       [0.05656384],
       [0.03722712],
       [0.16264689],
       [0.67673427],
       [0.71940917],
       [0.7617168 ],
       [0.78612095],
       [0.700991  ],
       [0.01745996],
       [0.03832567],
       [0.6374754 ],
       [0.6896898 ],
       [0.78103733],
       [0.7283413 ],
       [0.7561241 ],
       [0.01834789],
       [0.04660836],
       [0.66197807],
       [0.6920949 ],
       [0.7597592 ],
       [0.77162343],
       [0.75666517],
       [0.02251033],
       [0.05976807],
       [0.5879852 ],
       [0.714324  ],
       [0.75706863],
       [0.7260091 ],
       [0.0253825 ],
       [0.05709689],
       [0.4502631 ],
       [0.41904438],
       [0.02578625],
       [0.08755936],
       [0.6338901 ],
       [0.69985026],
       [0.712624  ],
       [0.67170995],
       [0.02292797],
       [0.07389861],
       [0.6003953 ],
       [0.67231923],
       [0.7002136 ],
       [0.6392563 ],
       [0.19586839],
       [0.27290952],
       [0.6056101 ],
       [0.64030164],
       [0.6400539 ],
       [0.49646676],
       [0.03910793],
       [0.02953431],
       [0.08352904],
       [0.5109304 ],
       [0.5939403 ],
       [0.68917185],
       [0.7303366 ],
       [0.7397776 ],
       [0.7023718 ],
       [0.66168517],
       [0.6347378 ],
       [0.6186715 ],
       [0.59412396],
       [0.2515816 ],
       [0.02455599],
       [0.01414257],
       [0.01310894],
       [0.01630714],
       [0.02893103],
       [0.49928805],
       [0.56942755],
       [0.6713899 ],
       [0.7072921 ],
       [0.73207176],
       [0.6846093 ],
       [0.69210845],
       [0.66883266],
       [0.6524209 ],
       [0.41920215],
       [0.0759165 ],
       [0.01694938],
       [0.01564753],
       [0.01629094],
       [0.579034  ],
       [0.5640413 ],
       [0.8037625 ],
       [0.79183465],
       [0.8018865 ],
       [0.7480846 ],
       [0.7494965 ],
       [0.07361184],
       [0.01135078],
       [0.00889693],
       [0.35483494],
       [0.28049028],
       [0.5487816 ],
       [0.01891324],
       [0.02374221],
       [0.5388419 ],
       [0.66962296],
       [0.80443364],
       [0.37338185]], dtype=float32)

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
16400       642.0   1485.421686   1850.979413           NaN
16401      6804.0  11718.606066  11182.089488           NaN
16402     10501.0  18614.042112  19279.054526           NaN
16403     13147.0   17689.00615  17438.807493           NaN
16404     15536.0  17039.389972  16974.916203           NaN
...           ...           ...           ...           ...
18273      7356.0   6900.654023   5846.106045    712.266174
18274     17638.0   20543.60541  19516.687678  16165.256836
18275     23339.0  23189.371101  21231.472263  20088.689453
18276     26323.0  26104.467998  24456.544978  24133.009766
18278     25598.0   26678.02481    26577.9225  11201.456055

[783 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,985 (1.55 MB)

 Trainable params: 405,729 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 461s 487ms/step - loss: 0.1321 - mae: 0.3677 - val_loss: 0.1383 - val_mae: 0.3902
Epoch 2/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 220s 383ms/step - loss: 0.0874 - mae: 0.2892 - val_loss: 0.1309 - val_mae: 0.3821
Epoch 3/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 194s 354ms/step - loss: 0.0831 - mae: 0.2821 - val_loss: 0.1174 - val_mae: 0.3582
Epoch 4/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 156s 331ms/step - loss: 0.0708 - mae: 0.2568 - val_loss: 0.0714 - val_mae: 0.2703
Epoch 5/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 232s 388ms/step - loss: 0.0681 - mae: 0.2488 - val_loss: 0.0710 - val_mae: 0.2668
Epoch 6/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 225s 429ms/step - loss: 0.0577 - mae: 0.2267 - val_loss: 0.0632 - val_mae: 0.2610
Epoch 7/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 197s 409ms/step - loss: 0.0535 - mae: 0.2245 - val_loss: 0.0545 - val_mae: 0.2400
Epoch 8/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 219s 436ms/step - loss: 0.0455 - mae: 0.1986 - val_loss: 0.0396 - val_mae: 0.2045
Epoch 9/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 180s 376ms/step - loss: 0.0444 - mae: 0.1973 - val_loss: 0.0385 - val_mae: 0.2002
Epoch 10/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 205s 374ms/step - loss: 0.0422 - mae: 0.1934 - val_loss: 0.0360 - val_mae: 0.1912
Epoch 11/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 224s 412ms/step - loss: 0.0382 - mae: 0.1824 - val_loss: 0.0358 - val_mae: 0.1883
Epoch 12/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 183s 393ms/step - loss: 0.0352 - mae: 0.1752 - val_loss: 0.0473 - val_mae: 0.2247
Epoch 13/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 223s 431ms/step - loss: 0.0358 - mae: 0.1762 - val_loss: 0.0355 - val_mae: 0.1873
Epoch 14/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 194s 401ms/step - loss: 0.0323 - mae: 0.1656 - val_loss: 0.0304 - val_mae: 0.1693
Epoch 15/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 196s 375ms/step - loss: 0.0334 - mae: 0.1707 - val_loss: 0.0343 - val_mae: 0.1835
Epoch 16/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 173s 300ms/step - loss: 0.0306 - mae: 0.1626 - val_loss: 0.0369 - val_mae: 0.1947
Epoch 17/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 201s 430ms/step - loss: 0.0324 - mae: 0.1663 - val_loss: 0.0318 - val_mae: 0.1729
Epoch 18/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 236s 498ms/step - loss: 0.0290 - mae: 0.1589 - val_loss: 0.0315 - val_mae: 0.1704
Epoch 19/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 274s 511ms/step - loss: 0.0305 - mae: 0.1620 - val_loss: 0.0304 - val_mae: 0.1680
Epoch 20/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 253s 478ms/step - loss: 0.0304 - mae: 0.1615 - val_loss: 0.0332 - val_mae: 0.1783
Epoch 21/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 281s 507ms/step - loss: 0.0293 - mae: 0.1539 - val_loss: 0.0300 - val_mae: 0.1687
Epoch 22/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 259s 487ms/step - loss: 0.0288 - mae: 0.1554 - val_loss: 0.0290 - val_mae: 0.1607
Epoch 23/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 246s 440ms/step - loss: 0.0261 - mae: 0.1477 - val_loss: 0.0310 - val_mae: 0.1715
Epoch 24/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 189s 403ms/step - loss: 0.0259 - mae: 0.1471 - val_loss: 0.0296 - val_mae: 0.1654
Epoch 25/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 174s 380ms/step - loss: 0.0269 - mae: 0.1476 - val_loss: 0.0328 - val_mae: 0.1782
Epoch 26/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 208s 383ms/step - loss: 0.0267 - mae: 0.1503 - val_loss: 0.0302 - val_mae: 0.1681
Epoch 27/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 245s 470ms/step - loss: 0.0266 - mae: 0.1502 - val_loss: 0.0299 - val_mae: 0.1638
Epoch 28/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 213s 465ms/step - loss: 0.0246 - mae: 0.1452 - val_loss: 0.0305 - val_mae: 0.1700
Epoch 29/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 209s 447ms/step - loss: 0.0263 - mae: 0.1463 - val_loss: 0.0312 - val_mae: 0.1622
Epoch 30/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 226s 488ms/step - loss: 0.0251 - mae: 0.1416 - val_loss: 0.0290 - val_mae: 0.1663
Epoch 31/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 266s 480ms/step - loss: 0.0240 - mae: 0.1418 - val_loss: 0.0290 - val_mae: 0.1559
Epoch 32/100
451/451 ━━━━━━━━━━━━━━━━━━━━ 258s 459ms/step - loss: 0.0233 - mae: 0.1395 - val_loss: 0.0317 - val_mae: 0.1741

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

23/23 ━━━━━━━━━━━━━━━━━━━━ 88s 2s/step

array([[0.        ],
       [0.        ],
       [0.18055815],
       [0.5791993 ],
       [0.5102185 ],
       [0.3486672 ],
       [0.        ],
       [0.22459531],
       [0.5873128 ],
       [0.6484679 ],
       [0.4912983 ],
       [0.45978707],
       [0.        ],
       [0.5534802 ],
       [0.6566276 ],
       [0.75677526],
       [0.7758445 ],
       [0.6465111 ],
       [0.673817  ],
       [0.21723151],
       [0.        ],
       [0.        ],
       [0.07166737],
       [0.38640216],
       [0.6757587 ],
       [0.7122274 ],
       [0.74775827],
       [0.7120526 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28061748],
       [0.6326781 ],
       [0.6301483 ],
       [0.4875728 ],
       [0.63615584],
       [0.65196   ],
       [0.6787219 ],
       [0.55887586],
       [0.5657383 ],
       [0.36356255],
       [0.32341218],
       [0.30619344],
       [0.24874777],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.18019032],
       [0.43545237],
       [0.56553316],
       [0.63365334],
       [0.6570789 ],
       [0.62357515],
       [0.5609774 ],
       [0.55919707],
       [0.6519065 ],
       [0.5955063 ],
       [0.5584563 ],
       [0.50182396],
       [0.20006734],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2014839 ],
       [0.5549979 ],
       [0.60426575],
       [0.6203833 ],
       [0.63731664],
       [0.66413873],
       [0.66386503],
       [0.70229304],
       [0.673952  ],
       [0.63725865],
       [0.6192662 ],
       [0.63960373],
       [0.31043398],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23365736],
       [0.6226411 ],
       [0.6789361 ],
       [0.6997218 ],
       [0.6903877 ],
       [0.5297747 ],
       [0.4991169 ],
       [0.3574235 ],
       [0.26778376],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.32431296],
       [0.6077177 ],
       [0.6296667 ],
       [0.6862042 ],
       [0.7211665 ],
       [0.63058406],
       [0.63791895],
       [0.75895935],
       [0.70482486],
       [0.693563  ],
       [0.5831182 ],
       [0.33266103],
       [0.        ],
       [0.        ],
       [0.07684589],
       [0.38203576],
       [0.56117344],
       [0.5492412 ],
       [0.47166976],
       [0.4867513 ],
       [0.34897438],
       [0.        ],
       [0.23230854],
       [0.6058537 ],
       [0.6573418 ],
       [0.6854853 ],
       [0.6624193 ],
       [0.6688268 ],
       [0.6854606 ],
       [0.68370074],
       [0.56380594],
       [0.4283882 ],
       [0.27897078],
       [0.        ],
       [0.        ],
       [0.37002882],
       [0.5256096 ],
       [0.41462418],
       [0.        ],
       [0.25820956],
       [0.36600956],
       [0.54595125],
       [0.5069    ],
       [0.41129735],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23428994],
       [0.6018968 ],
       [0.5504936 ],
       [0.48382077],
       [0.        ],
       [0.2759809 ],
       [0.56222564],
       [0.5136221 ],
       [0.        ],
       [0.19932497],
       [0.3687757 ],
       [0.22381625],
       [0.        ],
       [0.13332732],
       [0.5246174 ],
       [0.44122347],
       [0.40841362],
       [0.37381008],
       [0.11474538],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.18490717],
       [0.6219664 ],
       [0.6495452 ],
       [0.46494782],
       [0.43773374],
       [0.624102  ],
       [0.68051994],
       [0.        ],
       [0.359173  ],
       [0.62176585],
       [0.58344764],
       [0.3973466 ],
       [0.        ],
       [0.23459151],
       [0.551689  ],
       [0.55940855],
       [0.        ],
       [0.        ],
       [0.28334165],
       [0.43500838],
       [0.34287626],
       [0.37381893],
       [0.7257761 ],
       [0.58599687],
       [0.        ],
       [0.25949007],
       [0.6543868 ],
       [0.689607  ],
       [0.7188296 ],
       [0.66139746],
       [0.3009679 ],
       [0.03611827],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2353636 ],
       [0.64218754],
       [0.6847562 ],
       [0.5009978 ],
       [0.47655967],
       [0.3050448 ],
       [0.06519546],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.33357278],
       [0.645078  ],
       [0.7006056 ],
       [0.7294234 ],
       [0.7639622 ],
       [0.7635244 ],
       [0.7818108 ],
       [0.75709426],
       [0.76763296],
       [0.7416192 ],
       [0.3727781 ],
       [0.22971225],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.48138723],
       [0.65531015],
       [0.55460775],
       [0.7490648 ],
       [0.7396733 ],
       [0.84345436],
       [0.7261846 ],
       [0.47982457],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.38780138],
       [0.67284304],
       [0.7107406 ],
       [0.7628624 ],
       [0.78360087],
       [0.8050171 ],
       [0.8153553 ],
       [0.3006176 ],
       [0.        ],
       [0.        ],
       [0.42593935],
       [0.69122773],
       [0.7341411 ],
       [0.7235899 ],
       [0.7501954 ],
       [0.73641396],
       [0.7432559 ],
       [0.39914328],
       [0.5228715 ],
       [0.19666013],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23691785],
       [0.6873412 ],
       [0.7277709 ],
       [0.7631624 ],
       [0.7760609 ],
       [0.7967372 ],
       [0.80266523],
       [0.8057894 ],
       [0.80051273],
       [0.7315419 ],
       [0.6326436 ],
       [0.49376193],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.20268118],
       [0.6445456 ],
       [0.69406813],
       [0.64119637],
       [0.7587236 ],
       [0.76944256],
       [0.7923297 ],
       [0.17443123],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2560992 ],
       [0.62194574],
       [0.6138052 ],
       [0.5040051 ],
       [0.5161112 ],
       [0.46450707],
       [0.21297994],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28553882],
       [0.70589346],
       [0.7321229 ],
       [0.7396941 ],
       [0.76857954],
       [0.7666414 ],
       [0.7845744 ],
       [0.1842418 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.392747  ],
       [0.679711  ],
       [0.5000113 ],
       [0.20591766],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3484697 ],
       [0.6423812 ],
       [0.46972016],
       [0.13394551],
       [0.        ],
       [0.31579933],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.27665898],
       [0.7120921 ],
       [0.75057054],
       [0.78219175],
       [0.5215707 ],
       [0.28872058],
       [0.01526642],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3744938 ],
       [0.67974836],
       [0.6377079 ],
       [0.53644   ],
       [0.        ],
       [0.29078424],
       [0.6161963 ],
       [0.56516534],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3347315 ],
       [0.65508956],
       [0.614149  ],
       [0.515801  ],
       [0.74600804],
       [0.        ],
       [0.        ],
       [0.3513036 ],
       [0.6339824 ],
       [0.6174196 ],
       [0.54051805],
       [0.54087305],
       [0.7463125 ],
       [0.82282203],
       [0.3204125 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.35136107],
       [0.5532285 ],
       [0.43972108],
       [0.4530585 ],
       [0.39007917],
       [0.00426731],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.29366338],
       [0.6674456 ],
       [0.7003145 ],
       [0.71686983],
       [0.65649956],
       [0.2534517 ],
       [0.264085  ],
       [0.01220933],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23612005],
       [0.62664366],
       [0.5735127 ],
       [0.5499085 ],
       [0.48384336],
       [0.40865633],
       [0.48645547],
       [0.28950682],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1515384 ],
       [0.27547595],
       [0.5386124 ],
       [0.5788971 ],
       [0.5287614 ],
       [0.14621331],
       [0.04851291],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1910074 ],
       [0.31400844],
       [0.55563843],
       [0.57577443],
       [0.5622297 ],
       [0.54055333],
       [0.45924786],
       [0.38945282],
       [0.2126303 ],
       [0.18884149],
       [0.09079349],
       [0.        ],
       [0.        ],
       [0.08046851],
       [0.18015015],
       [0.3390599 ],
       [0.4332782 ],
       [0.45265967],
       [0.38454023],
       [0.4559993 ],
       [0.35514486],
       [0.33647338],
       [0.1620436 ],
       [0.17725092],
       [0.        ],
       [0.        ],
       [0.08810419],
       [0.22572407],
       [0.3801194 ],
       [0.50844073],
       [0.52207416],
       [0.49034077],
       [0.45014974],
       [0.39966074],
       [0.16303504],
       [0.0347431 ],
       [0.        ],
       [0.        ],
       [0.00723016],
       [0.1726509 ],
       [0.36235753],
       [0.4277552 ],
       [0.44447878],
       [0.45819107],
       [0.48431313],
       [0.49596515],
       [0.45857736],
       [0.3613105 ],
       [0.33938465],
       [0.24708983],
       [0.24477321],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19559315],
       [0.32696488],
       [0.41378102],
       [0.42860237],
       [0.4395868 ],
       [0.4309931 ],
       [0.45591497],
       [0.4294025 ],
       [0.45867714],
       [0.2687611 ],
       [0.3392885 ],
       [0.26726896],
       [0.21422696],
       [0.        ],
       [0.01821897],
       [0.0219144 ],
       [0.19349447],
       [0.4263816 ],
       [0.49382755],
       [0.61248213],
       [0.58459896],
       [0.49040288],
       [0.3886437 ],
       [0.3630956 ],
       [0.10839262],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.31629813],
       [0.40463823],
       [0.43098477],
       [0.5975878 ],
       [0.6698746 ],
       [0.63528514],
       [0.12332816],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.20999253],
       [0.5038117 ],
       [0.51606894],
       [0.3816544 ],
       [0.43641043],
       [0.        ],
       [0.11454789],
       [0.5741658 ],
       [0.6812644 ],
       [0.7205152 ],
       [0.7789259 ],
       [0.79023147],
       [0.8270855 ],
       [0.81228065],
       [0.82485676],
       [0.77253664],
       [0.73821557],
       [0.56413347],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22621024],
       [0.6324995 ],
       [0.6604326 ],
       [0.75789386],
       [0.7535516 ],
       [0.68421453],
       [0.54480815],
       [0.5374371 ],
       [0.23922786],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19962353],
       [0.5933442 ],
       [0.6568721 ],
       [0.6717354 ],
       [0.70342404],
       [0.73875505],
       [0.73283875],
       [0.7228776 ],
       [0.7584856 ],
       [0.6935619 ],
       [0.6853271 ],
       [0.53128207],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.06117854],
       [0.29347804],
       [0.6413709 ],
       [0.6555272 ],
       [0.672315  ],
       [0.6706823 ],
       [0.69253016],
       [0.6845339 ],
       [0.71479195],
       [0.6651566 ],
       [0.61417735],
       [0.510796  ],
       [0.33811286],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.03414399],
       [0.21596944],
       [0.55037755],
       [0.6297972 ],
       [0.6935911 ],
       [0.689885  ],
       [0.70846194],
       [0.6217058 ],
       [0.7404865 ],
       [0.7167667 ],
       [0.7105692 ],
       [0.46653292],
       [0.36916843],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.200784  ],
       [0.55105287],
       [0.60246813],
       [0.6555698 ],
       [0.6987325 ],
       [0.5914105 ],
       [0.60426915],
       [0.71020645],
       [0.60748327],
       [0.5331488 ],
       [0.26321626],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.05110408],
       [0.23157883],
       [0.4782789 ],
       [0.5756318 ],
       [0.66417855],
       [0.6339159 ],
       [0.5759771 ],
       [0.55197376],
       [0.5627177 ],
       [0.51989144],
       [0.58140045],
       [0.35672083],
       [0.31487188],
       [0.1720734 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.20159453],
       [0.49205515],
       [0.5659901 ],
       [0.6312247 ],
       [0.67902774],
       [0.67450815],
       [0.6959981 ],
       [0.5585274 ],
       [0.5339658 ],
       [0.4032137 ],
       [0.37090948],
       [0.19194421],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.13173446],
       [0.22163945],
       [0.52876437],
       [0.5498431 ],
       [0.5208861 ],
       [0.49218744],
       [0.        ],
       [0.        ],
       [0.34019724],
       [0.5270072 ],
       [0.627351  ],
       [0.6844374 ],
       [0.640507  ],
       [0.46900418],
       [0.        ],
       [0.2871042 ],
       [0.6020956 ],
       [0.67858964],
       [0.7020897 ],
       [0.5215822 ],
       [0.4872875 ],
       [0.        ],
       [0.27752   ],
       [0.6382801 ],
       [0.6618655 ],
       [0.71395475],
       [0.6476338 ],
       [0.48825672],
       [0.        ],
       [0.2253429 ],
       [0.5605798 ],
       [0.55478334],
       [0.47260275],
       [0.46083388],
       [0.        ],
       [0.31124613],
       [0.40159202],
       [0.3768457 ],
       [0.        ],
       [0.22052678],
       [0.4584061 ],
       [0.5217803 ],
       [0.40139616],
       [0.39551824],
       [0.        ],
       [0.18958756],
       [0.53252405],
       [0.61245525],
       [0.6491921 ],
       [0.39070132],
       [0.        ],
       [0.22115701],
       [0.43467858],
       [0.49717662],
       [0.6485471 ],
       [0.5255535 ],
       [0.        ],
       [0.        ],
       [0.28960797],
       [0.5717868 ],
       [0.6251521 ],
       [0.65923   ],
       [0.6790386 ],
       [0.7119772 ],
       [0.7199188 ],
       [0.7273375 ],
       [0.6900472 ],
       [0.69621956],
       [0.6219876 ],
       [0.29488918],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.00888662],
       [0.5067098 ],
       [0.6134179 ],
       [0.6540582 ],
       [0.6747045 ],
       [0.71149486],
       [0.713894  ],
       [0.73064953],
       [0.73161393],
       [0.708163  ],
       [0.386965  ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2066564 ],
       [0.4418594 ],
       [0.5249578 ],
       [0.5354572 ],
       [0.7202275 ],
       [0.82677925],
       [0.7515139 ],
       [0.2421214 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3391445 ],
       [0.53620976],
       [0.21443564],
       [0.37114552],
       [0.59325707],
       [0.63184905],
       [0.496037  ],
       [0.46521693]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
16400       642.0   1485.421686   1850.979413           NaN           NaN
16401      6804.0  11718.606066  11182.089488           NaN           NaN
16402     10501.0  18614.042112  19279.054526           NaN           NaN
16403     13147.0   17689.00615  17438.807493           NaN           NaN
16404     15536.0  17039.389972  16974.916203           NaN           NaN
...           ...           ...           ...           ...           ...
18273      7356.0   6900.654023   5846.106045    712.266174  11134.365234
18274     17638.0   20543.60541  19516.687678  16165.256836  17797.712891
18275     23339.0  23189.371101  21231.472263  20088.689453  18955.470703
18276     26323.0  26104.467998  24456.544978  24133.009766  14881.110352
18278     25598.0   26678.02481    26577.9225  11201.456055  13956.507812

[783 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

16495        0.0
16496     1179.0
16497    11793.0
16498    23862.0
16500    27743.0
          ...
18273     7356.0
18274    17638.0
18275    23339.0
18276    26323.0
18278    25598.0
Name: Generación, Length: 735, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 9)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      2,368 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 474,049 (1.81 MB)

 Trainable params: 474,049 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50

226/226 ━━━━━━━━━━━━━━━━━━━━ 363s 344ms/step - loss: 1.0836 - mae: 0.2751 - val_loss: 0.5936 - val_mae: 0.3221
Epoch 2/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 62s 225ms/step - loss: 0.4806 - mae: 0.2846 - val_loss: 0.2998 - val_mae: 0.3024
Epoch 3/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 74s 172ms/step - loss: 0.2146 - mae: 0.2155 - val_loss: 0.1419 - val_mae: 0.1931
Epoch 4/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 99s 221ms/step - loss: 0.1102 - mae: 0.1638 - val_loss: 0.0987 - val_mae: 0.1856
Epoch 5/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 78s 178ms/step - loss: 0.0768 - mae: 0.1583 - val_loss: 0.0881 - val_mae: 0.1861
Epoch 6/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 99s 229ms/step - loss: 0.0590 - mae: 0.1493 - val_loss: 0.1052 - val_mae: 0.2102
Epoch 7/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 56s 218ms/step - loss: 0.0588 - mae: 0.1535 - val_loss: 0.0770 - val_mae: 0.1914
Epoch 8/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 47s 179ms/step - loss: 0.0513 - mae: 0.1474 - val_loss: 0.0707 - val_mae: 0.1796
Epoch 9/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 87s 179ms/step - loss: 0.0463 - mae: 0.1390 - val_loss: 0.0694 - val_mae: 0.1784
Epoch 10/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 92s 207ms/step - loss: 0.0494 - mae: 0.1491 - val_loss: 0.0658 - val_mae: 0.1753
Epoch 11/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 85s 200ms/step - loss: 0.0438 - mae: 0.1404 - val_loss: 0.0653 - val_mae: 0.1771
Epoch 12/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 91s 219ms/step - loss: 0.0401 - mae: 0.1337 - val_loss: 0.0682 - val_mae: 0.1820
Epoch 13/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 81s 195ms/step - loss: 0.0425 - mae: 0.1368 - val_loss: 0.0660 - val_mae: 0.1723
Epoch 14/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 86s 190ms/step - loss: 0.0388 - mae: 0.1298 - val_loss: 0.0644 - val_mae: 0.1720
Epoch 15/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 94s 221ms/step - loss: 0.0391 - mae: 0.1308 - val_loss: 0.0643 - val_mae: 0.1741
Epoch 16/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 82s 201ms/step - loss: 0.0388 - mae: 0.1312 - val_loss: 0.0647 - val_mae: 0.1707
Epoch 17/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 41s 155ms/step - loss: 0.0361 - mae: 0.1266 - val_loss: 0.0632 - val_mae: 0.1706
Epoch 18/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 30s 123ms/step - loss: 0.0385 - mae: 0.1304 - val_loss: 0.0620 - val_mae: 0.1669
Epoch 19/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 56s 177ms/step - loss: 0.0344 - mae: 0.1200 - val_loss: 0.0906 - val_mae: 0.2029
Epoch 20/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 45s 176ms/step - loss: 0.0383 - mae: 0.1300 - val_loss: 0.0627 - val_mae: 0.1680
Epoch 21/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 80s 150ms/step - loss: 0.0353 - mae: 0.1209 - val_loss: 0.0631 - val_mae: 0.1703
Epoch 22/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 49s 196ms/step - loss: 0.0345 - mae: 0.1197 - val_loss: 0.0679 - val_mae: 0.1730
Epoch 23/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 81s 165ms/step - loss: 0.0322 - mae: 0.1160 - val_loss: 0.0612 - val_mae: 0.1658
Epoch 24/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 46s 171ms/step - loss: 0.0325 - mae: 0.1155 - val_loss: 0.0631 - val_mae: 0.1718
Epoch 25/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 38s 145ms/step - loss: 0.0333 - mae: 0.1207 - val_loss: 0.0654 - val_mae: 0.1748
Epoch 26/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 53s 179ms/step - loss: 0.0340 - mae: 0.1200 - val_loss: 0.0644 - val_mae: 0.1678
Epoch 27/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 52s 190ms/step - loss: 0.0334 - mae: 0.1183 - val_loss: 0.0632 - val_mae: 0.1701
Epoch 28/50
226/226 ━━━━━━━━━━━━━━━━━━━━ 77s 148ms/step - loss: 0.0317 - mae: 0.1142 - val_loss: 0.0681 - val_mae: 0.1714

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

23/23 ━━━━━━━━━━━━━━━━━━━━ 35s 866ms/step

array([[ 7.04868790e-03],
       [ 4.04664166e-02],
       [ 2.44134456e-01],
       [ 7.06092000e-01],
       [ 6.08939528e-01],
       [ 3.84140909e-01],
       [ 1.83531314e-01],
       [ 2.94742107e-01],
       [ 6.31554961e-01],
       [ 7.09556103e-01],
       [ 4.70561057e-01],
       [ 4.47456568e-01],
       [ 1.37081459e-01],
       [ 4.49688464e-01],
       [ 8.00388515e-01],
       [ 1.04231822e+00],
       [ 1.07957542e+00],
       [ 8.46226037e-01],
       [ 7.23464251e-01],
       [ 1.49178818e-01],
       [ 1.43082310e-02],
       [ 9.58504248e-03],
       [ 1.81454569e-01],
       [ 3.60414654e-01],
       [ 8.27250302e-01],
       [ 8.96868050e-01],
       [ 9.22353804e-01],
       [ 8.01602960e-01],
       [ 2.70325728e-02],
       [ 2.41547897e-02],
       [ 1.32010013e-01],
       [ 3.14393729e-01],
       [ 7.59261966e-01],
       [ 6.50186896e-01],
       [ 4.12922680e-01],
       [ 4.88438636e-01],
       [ 7.52671540e-01],
       [ 7.65576363e-01],
       [ 6.32057130e-01],
       [ 5.42732477e-01],
       [ 4.32573408e-01],
       [ 3.14682454e-01],
       [ 3.96327108e-01],
       [ 2.29345232e-01],
       [ 1.50606539e-02],
       [ 1.33770844e-02],
       [ 1.20520279e-01],
       [ 1.81025505e-01],
       [ 6.01316154e-01],
       [ 7.33765543e-01],
       [ 8.60105276e-01],
       [ 8.27089906e-01],
       [ 7.75829434e-01],
       [ 7.14750469e-01],
       [ 6.57121480e-01],
       [ 8.97096872e-01],
       [ 8.98016095e-01],
       [ 7.07363605e-01],
       [ 5.97645879e-01],
       [ 1.12679198e-01],
       [ 1.49560496e-02],
       [ 9.81866941e-03],
       [ 6.12625666e-02],
       [ 1.85750663e-01],
       [ 7.56480157e-01],
       [ 8.27467442e-01],
       [ 8.43989134e-01],
       [ 8.49501729e-01],
       [ 8.98984015e-01],
       [ 8.78026843e-01],
       [ 9.62121904e-01],
       [ 8.48476648e-01],
       [ 7.85827041e-01],
       [ 7.18281269e-01],
       [ 7.96376467e-01],
       [ 3.40089977e-01],
       [ 1.50554627e-02],
       [ 7.27367075e-03],
       [ 2.47438047e-02],
       [ 2.26250410e-01],
       [ 7.68928587e-01],
       [ 9.00509596e-01],
       [ 9.31632161e-01],
       [ 8.98457527e-01],
       [ 6.13901794e-01],
       [ 6.15237772e-01],
       [ 5.25741875e-01],
       [ 2.47787431e-01],
       [ 1.94577053e-02],
       [ 1.14868153e-02],
       [ 6.50681555e-02],
       [ 2.74392009e-01],
       [ 7.93321967e-01],
       [ 7.87054658e-01],
       [ 9.08751488e-01],
       [ 9.45136309e-01],
       [ 8.48836184e-01],
       [ 7.57874727e-01],
       [ 1.02058601e+00],
       [ 1.10419571e+00],
       [ 8.88618469e-01],
       [ 6.85086906e-01],
       [ 2.74378747e-01],
       [ 1.36589799e-02],
       [ 9.30226222e-03],
       [ 5.78687899e-02],
       [ 3.33812863e-01],
       [ 8.36918533e-01],
       [ 7.54871249e-01],
       [ 6.40841901e-01],
       [ 5.17332911e-01],
       [ 5.00989556e-01],
       [ 4.17879485e-02],
       [ 2.57996142e-01],
       [ 8.33936393e-01],
       [ 9.06549990e-01],
       [ 8.75681043e-01],
       [ 8.48606050e-01],
       [ 7.99614131e-01],
       [ 8.53740931e-01],
       [ 9.19001102e-01],
       [ 7.17745841e-01],
       [ 4.43136781e-01],
       [ 2.12083116e-01],
       [ 5.74726798e-03],
       [ 1.98504310e-02],
       [ 3.18561912e-01],
       [ 5.87733626e-01],
       [ 4.87549067e-01],
       [ 4.12966944e-02],
       [ 2.88281441e-01],
       [ 6.23987556e-01],
       [ 6.55618608e-01],
       [ 5.63511372e-01],
       [ 4.72850353e-01],
       [ 1.54553298e-02],
       [ 7.26765860e-03],
       [ 2.51696743e-02],
       [ 2.73913592e-01],
       [ 6.92763448e-01],
       [ 6.83819771e-01],
       [ 5.09672582e-01],
       [ 3.99263129e-02],
       [ 3.54908973e-01],
       [ 7.37226963e-01],
       [ 6.04712725e-01],
       [ 7.73747563e-02],
       [ 2.86073774e-01],
       [ 5.28595626e-01],
       [ 3.37904006e-01],
       [ 5.13976738e-02],
       [ 2.92871535e-01],
       [ 7.36208856e-01],
       [ 6.28098071e-01],
       [ 5.08590758e-01],
       [ 4.05215353e-01],
       [ 2.74523765e-01],
       [ 8.43220856e-03],
       [ 5.04842401e-03],
       [ 2.56201476e-02],
       [ 2.92675644e-01],
       [ 6.74041927e-01],
       [ 6.99696660e-01],
       [ 3.98075134e-01],
       [ 3.35729212e-01],
       [ 6.05934739e-01],
       [ 7.56154239e-01],
       [ 3.75461057e-02],
       [ 2.96846151e-01],
       [ 5.57268500e-01],
       [ 5.41710258e-01],
       [ 3.18447620e-01],
       [ 4.46914658e-02],
       [ 1.68128684e-01],
       [ 5.90020537e-01],
       [ 4.30826873e-01],
       [ 1.65152196e-02],
       [ 2.23264061e-02],
       [ 2.44995549e-01],
       [ 3.28293294e-01],
       [ 3.92037719e-01],
       [ 3.77270073e-01],
       [ 9.02933896e-01],
       [ 8.05658281e-01],
       [ 1.18102647e-01],
       [ 1.95949540e-01],
       [ 6.85333669e-01],
       [ 7.57755995e-01],
       [ 7.85406709e-01],
       [ 6.66129112e-01],
       [ 2.57198691e-01],
       [ 3.28621194e-02],
       [ 1.06734633e-02],
       [ 5.72556956e-03],
       [ 1.90314613e-02],
       [ 2.25295871e-01],
       [ 7.02412963e-01],
       [ 7.67695665e-01],
       [ 4.78619158e-01],
       [ 4.10498708e-01],
       [ 2.66403109e-01],
       [ 9.15158838e-02],
       [ 2.25484557e-02],
       [ 1.04627907e-02],
       [ 2.28721350e-02],
       [ 3.34199518e-01],
       [ 7.40371644e-01],
       [ 9.12859261e-01],
       [ 9.27934945e-01],
       [ 8.64972830e-01],
       [ 8.20306182e-01],
       [ 7.94533372e-01],
       [ 8.16906154e-01],
       [ 8.13008249e-01],
       [ 7.97948480e-01],
       [ 3.93520474e-01],
       [ 7.68001005e-02],
       [ 1.03243254e-03],
       [ 1.95113383e-03],
       [ 2.96012089e-02],
       [ 4.83295828e-01],
       [ 7.06901073e-01],
       [ 6.57715023e-01],
       [ 8.15336108e-01],
       [ 9.00388896e-01],
       [ 1.03680432e+00],
       [ 8.73383582e-01],
       [ 5.54838538e-01],
       [ 1.99962035e-02],
       [ 3.15452553e-03],
       [ 1.82388257e-03],
       [ 2.51516737e-02],
       [ 3.89826566e-01],
       [ 7.98731446e-01],
       [ 8.71022105e-01],
       [ 9.76873994e-01],
       [ 9.90205109e-01],
       [ 9.92547870e-01],
       [ 9.41740155e-01],
       [ 4.34641808e-01],
       [ 7.61821447e-03],
       [ 1.90527197e-02],
       [ 3.09243172e-01],
       [ 7.56591380e-01],
       [ 8.64511371e-01],
       [ 7.83709049e-01],
       [ 7.05693483e-01],
       [ 7.74984717e-01],
       [ 7.92774141e-01],
       [ 4.76022393e-01],
       [ 4.53462303e-01],
       [ 1.91174403e-01],
       [ 1.33057619e-02],
       [ 5.92260389e-03],
       [ 2.11895294e-02],
       [ 3.04527074e-01],
       [ 8.52634668e-01],
       [ 9.20449018e-01],
       [ 9.40388322e-01],
       [ 9.78503823e-01],
       [ 9.75702882e-01],
       [ 9.62588251e-01],
       [ 9.49158549e-01],
       [ 9.34807777e-01],
       [ 7.69268513e-01],
       [ 5.84085524e-01],
       [ 4.43978906e-01],
       [ 6.17526211e-02],
       [ 1.20259263e-02],
       [ 6.38705306e-03],
       [ 3.68476808e-02],
       [ 3.07164252e-01],
       [ 8.10981512e-01],
       [ 8.71608019e-01],
       [ 7.64486909e-01],
       [ 9.07482505e-01],
       [ 1.03026080e+00],
       [ 9.87046897e-01],
       [ 4.75735158e-01],
       [ 1.99672207e-02],
       [ 3.73579655e-03],
       [ 5.99623471e-03],
       [ 3.30942422e-02],
       [ 3.25423628e-01],
       [ 7.47915268e-01],
       [ 5.97997844e-01],
       [ 5.79505920e-01],
       [ 5.79681754e-01],
       [ 5.86873114e-01],
       [ 3.75908375e-01],
       [ 2.32125632e-02],
       [ 7.72503717e-03],
       [ 1.21392440e-02],
       [ 3.39006595e-02],
       [ 3.30935806e-01],
       [ 8.61903310e-01],
       [ 9.16599393e-01],
       [ 8.11012864e-01],
       [ 8.51788759e-01],
       [ 8.86670589e-01],
       [ 9.05445158e-01],
       [ 4.58987206e-01],
       [ 1.86833162e-02],
       [ 2.80508678e-03],
       [ 5.05411904e-03],
       [ 3.44087332e-02],
       [ 4.26367939e-01],
       [ 8.20148230e-01],
       [ 5.45361578e-01],
       [ 1.77333400e-01],
       [ 2.51188539e-02],
       [ 1.21235736e-02],
       [ 1.38852913e-02],
       [ 4.00289409e-02],
       [ 3.80826980e-01],
       [ 7.94289112e-01],
       [ 5.62895060e-01],
       [ 1.04479633e-01],
       [ 2.37969793e-02],
       [ 4.93547231e-01],
       [ 3.12378593e-02],
       [ 9.58198216e-03],
       [ 1.12803634e-02],
       [ 3.76149192e-02],
       [ 3.08205903e-01],
       [ 7.90510654e-01],
       [ 9.15371895e-01],
       [ 9.40982342e-01],
       [ 5.80481589e-01],
       [ 2.16717988e-01],
       [ 5.93893491e-02],
       [ 1.32441558e-02],
       [ 6.87758299e-03],
       [ 3.12412754e-02],
       [ 3.71701270e-01],
       [ 8.14813852e-01],
       [ 7.34469414e-01],
       [ 5.66872478e-01],
       [ 3.82752232e-02],
       [ 3.45403224e-01],
       [ 7.16237187e-01],
       [ 5.98492920e-01],
       [ 4.02307585e-02],
       [ 5.23907039e-03],
       [ 2.94191651e-02],
       [ 3.54222387e-01],
       [ 7.33254015e-01],
       [ 6.96198165e-01],
       [ 5.43540418e-01],
       [ 7.18753457e-01],
       [ 8.83928984e-02],
       [ 5.64720146e-02],
       [ 3.74585003e-01],
       [ 6.58750057e-01],
       [ 6.07936144e-01],
       [ 5.69123805e-01],
       [ 4.68369961e-01],
       [ 7.18158841e-01],
       [ 1.01598752e+00],
       [ 5.20212173e-01],
       [ 2.15325058e-02],
       [ 5.25436271e-03],
       [ 4.68047056e-03],
       [ 2.74953842e-02],
       [ 3.48854572e-01],
       [ 5.32675028e-01],
       [ 4.05476600e-01],
       [ 4.19507533e-01],
       [ 4.40473944e-01],
       [ 6.87833875e-02],
       [ 9.64471418e-03],
       [ 4.60504275e-03],
       [ 2.89611518e-02],
       [ 2.91290671e-01],
       [ 7.83528328e-01],
       [ 7.67482996e-01],
       [ 7.21207738e-01],
       [ 6.39508963e-01],
       [ 1.68302760e-01],
       [ 1.36456266e-01],
       [ 3.98447216e-02],
       [ 1.77695677e-02],
       [ 9.58425086e-03],
       [ 3.67668234e-02],
       [ 3.05325896e-01],
       [ 7.71032751e-01],
       [ 6.77847743e-01],
       [ 5.33677459e-01],
       [ 4.34594125e-01],
       [ 4.35585320e-01],
       [ 5.86260498e-01],
       [ 4.23141509e-01],
       [ 4.53119203e-02],
       [ 1.59857683e-02],
       [ 1.20722987e-02],
       [ 3.65217149e-01],
       [ 4.19864506e-01],
       [ 6.61572397e-01],
       [ 6.85525656e-01],
       [ 5.80042541e-01],
       [ 1.33423179e-01],
       [ 5.28777316e-02],
       [ 2.86425129e-02],
       [ 1.97565109e-02],
       [ 1.59814898e-02],
       [ 2.97571003e-01],
       [ 4.83757287e-01],
       [ 7.53037751e-01],
       [ 7.77182341e-01],
       [ 7.24130869e-01],
       [ 6.37464404e-01],
       [ 5.77119470e-01],
       [ 5.59361041e-01],
       [ 3.96013290e-01],
       [ 1.94955513e-01],
       [ 4.59583290e-02],
       [ 2.12888084e-02],
       [ 2.35288534e-02],
       [ 1.72639996e-01],
       [ 2.44859472e-01],
       [ 5.49964249e-01],
       [ 5.65085351e-01],
       [ 5.00157773e-01],
       [ 4.33430046e-01],
       [ 4.65220481e-01],
       [ 4.56677735e-01],
       [ 5.09836435e-01],
       [ 7.09652379e-02],
       [ 2.21767537e-02],
       [ 9.65441018e-03],
       [ 1.13712177e-02],
       [ 8.78665447e-02],
       [ 2.89772689e-01],
       [ 5.03817797e-01],
       [ 5.52546442e-01],
       [ 6.35459602e-01],
       [ 5.39533496e-01],
       [ 4.94539529e-01],
       [ 4.99746352e-01],
       [ 3.70211542e-01],
       [ 2.03484893e-02],
       [ 8.67707096e-03],
       [ 1.11059994e-02],
       [ 5.36236949e-02],
       [ 2.52069056e-01],
       [ 5.13364732e-01],
       [ 4.84326690e-01],
       [ 5.33010304e-01],
       [ 3.94727588e-01],
       [ 4.85319227e-01],
       [ 6.79230809e-01],
       [ 5.69628417e-01],
       [ 3.94159585e-01],
       [ 4.10668880e-01],
       [ 3.89932156e-01],
       [ 1.11168049e-01],
       [ 1.38978101e-02],
       [ 1.08385887e-02],
       [ 1.02994367e-02],
       [ 3.39650474e-02],
       [ 2.46828780e-01],
       [ 4.28062201e-01],
       [ 4.71425802e-01],
       [ 4.02877957e-01],
       [ 4.76949632e-01],
       [ 5.25860548e-01],
       [ 6.24567509e-01],
       [ 5.46667755e-01],
       [ 5.51959693e-01],
       [ 3.34427923e-01],
       [ 3.96548867e-01],
       [ 6.32760450e-02],
       [ 3.47377919e-02],
       [ 1.68661755e-02],
       [ 1.61804184e-02],
       [ 4.03035320e-02],
       [ 8.98939893e-02],
       [ 4.98383433e-01],
       [ 4.85817224e-01],
       [ 7.17883348e-01],
       [ 7.56477058e-01],
       [ 6.04281664e-01],
       [ 5.98068833e-01],
       [ 3.96197259e-01],
       [ 9.70804021e-02],
       [ 1.35485455e-02],
       [ 2.41075456e-03],
       [ 3.79863475e-03],
       [ 2.37086769e-02],
       [ 4.03609961e-01],
       [ 5.13167918e-01],
       [ 5.21443963e-01],
       [ 7.28836060e-01],
       [ 7.77175784e-01],
       [ 6.76460147e-01],
       [ 2.20958605e-01],
       [ 7.08490703e-03],
       [-8.21540132e-04],
       [ 1.66110750e-02],
       [ 1.94131702e-01],
       [ 5.72595596e-01],
       [ 5.68919182e-01],
       [ 3.43671083e-01],
       [ 4.06785041e-01],
       [ 5.35410158e-02],
       [ 2.20230967e-01],
       [ 6.08170629e-01],
       [ 7.45158851e-01],
       [ 8.24116409e-01],
       [ 8.78571033e-01],
       [ 8.38382900e-01],
       [ 8.69167805e-01],
       [ 8.66745114e-01],
       [ 8.62677217e-01],
       [ 7.25302160e-01],
       [ 6.24971628e-01],
       [ 3.94334346e-01],
       [ 1.49707552e-02],
       [ 7.07366504e-04],
       [ 6.59103459e-03],
       [ 6.73903972e-02],
       [ 2.85557330e-01],
       [ 6.94884956e-01],
       [ 6.24424100e-01],
       [ 8.29735994e-01],
       [ 8.65113378e-01],
       [ 7.39803910e-01],
       [ 6.55642033e-01],
       [ 6.09511018e-01],
       [ 6.67500570e-02],
       [ 1.17448512e-02],
       [ 9.25860927e-03],
       [ 3.13512646e-02],
       [ 2.32350528e-01],
       [ 7.26049960e-01],
       [ 7.51686990e-01],
       [ 7.49537528e-01],
       [ 7.96080232e-01],
       [ 8.86556804e-01],
       [ 8.38882804e-01],
       [ 7.37804890e-01],
       [ 8.85680914e-01],
       [ 7.98892260e-01],
       [ 8.56738567e-01],
       [ 6.05917871e-01],
       [ 3.06378752e-02],
       [ 5.61097637e-03],
       [ 1.59424171e-02],
       [ 3.48751366e-01],
       [ 3.98713231e-01],
       [ 8.80917370e-01],
       [ 8.49287748e-01],
       [ 7.86549807e-01],
       [ 7.41572976e-01],
       [ 7.42451429e-01],
       [ 7.50881553e-01],
       [ 7.66335487e-01],
       [ 8.11618388e-01],
       [ 7.37705648e-01],
       [ 5.31629086e-01],
       [ 4.01350081e-01],
       [ 2.56646946e-02],
       [ 1.62515379e-02],
       [ 1.84347648e-02],
       [ 1.15784764e-01],
       [ 2.64017850e-01],
       [ 7.51306951e-01],
       [ 8.77522707e-01],
       [ 9.02908206e-01],
       [ 8.66113663e-01],
       [ 8.42861652e-01],
       [ 7.68362522e-01],
       [ 9.03633237e-01],
       [ 9.46936131e-01],
       [ 8.49970937e-01],
       [ 4.87138659e-01],
       [ 3.55886281e-01],
       [ 2.87881047e-02],
       [ 1.11021269e-02],
       [ 2.08130497e-02],
       [ 1.24299593e-01],
       [ 2.12893263e-01],
       [ 7.30110526e-01],
       [ 8.09831262e-01],
       [ 8.55629563e-01],
       [ 9.06003058e-01],
       [ 7.74561286e-01],
       [ 7.00201035e-01],
       [ 9.44929481e-01],
       [ 8.57582808e-01],
       [ 6.90178871e-01],
       [ 2.15630338e-01],
       [ 1.87494941e-02],
       [ 6.91293785e-03],
       [ 2.28072777e-02],
       [ 1.51272520e-01],
       [ 4.04945284e-01],
       [ 6.18808329e-01],
       [ 7.38045096e-01],
       [ 9.25259173e-01],
       [ 7.91546643e-01],
       [ 6.25298083e-01],
       [ 6.28093243e-01],
       [ 6.95126832e-01],
       [ 6.90771818e-01],
       [ 7.38465011e-01],
       [ 4.09223258e-01],
       [ 1.38135001e-01],
       [ 3.37881409e-02],
       [ 1.50989639e-02],
       [ 1.52681107e-02],
       [ 5.87033890e-02],
       [ 2.11462542e-01],
       [ 6.60124898e-01],
       [ 7.23350763e-01],
       [ 7.37883091e-01],
       [ 9.25807178e-01],
       [ 8.63768458e-01],
       [ 9.23697710e-01],
       [ 7.18977809e-01],
       [ 6.66368484e-01],
       [ 4.70612049e-01],
       [ 3.66527945e-01],
       [ 1.59257010e-01],
       [ 2.03908402e-02],
       [ 9.73816682e-03],
       [ 1.63847078e-02],
       [ 2.75108844e-01],
       [ 4.00489450e-01],
       [ 6.91918135e-01],
       [ 7.35824406e-01],
       [ 6.20036364e-01],
       [ 5.14959335e-01],
       [ 1.44960880e-02],
       [ 5.14302813e-02],
       [ 3.25440019e-01],
       [ 6.12221539e-01],
       [ 7.77145982e-01],
       [ 9.57697392e-01],
       [ 7.65203476e-01],
       [ 5.32034934e-01],
       [ 1.10144407e-01],
       [ 3.42904955e-01],
       [ 7.92687774e-01],
       [ 8.96740556e-01],
       [ 9.54996765e-01],
       [ 5.62030196e-01],
       [ 3.66342396e-01],
       [ 9.96190459e-02],
       [ 3.24902296e-01],
       [ 7.66602933e-01],
       [ 8.47337365e-01],
       [ 8.68976533e-01],
       [ 7.03717828e-01],
       [ 4.44820046e-01],
       [ 1.01023473e-01],
       [ 2.93106467e-01],
       [ 7.32228100e-01],
       [ 6.09221935e-01],
       [ 4.67816561e-01],
       [ 4.29598391e-01],
       [ 6.19499013e-02],
       [ 3.80144686e-01],
       [ 6.17176890e-01],
       [ 3.95961136e-01],
       [ 5.39844409e-02],
       [ 2.99338877e-01],
       [ 5.86186647e-01],
       [ 5.59298992e-01],
       [ 4.44714934e-01],
       [ 4.50208724e-01],
       [ 6.10007569e-02],
       [ 2.87855297e-01],
       [ 7.05844700e-01],
       [ 7.57319033e-01],
       [ 8.37746143e-01],
       [ 4.74988312e-01],
       [ 1.03685714e-01],
       [ 3.26514006e-01],
       [ 5.03925502e-01],
       [ 5.51320672e-01],
       [ 8.50157559e-01],
       [ 8.34912539e-01],
       [ 3.75902951e-02],
       [ 5.41074462e-02],
       [ 1.66276187e-01],
       [ 6.10490859e-01],
       [ 7.37294614e-01],
       [ 7.84542799e-01],
       [ 7.87479997e-01],
       [ 9.02375579e-01],
       [ 7.94561386e-01],
       [ 7.97809362e-01],
       [ 6.90642893e-01],
       [ 6.89074874e-01],
       [ 5.23350477e-01],
       [ 2.06877932e-01],
       [ 8.84734094e-03],
       [ 5.78040024e-03],
       [ 4.03958838e-03],
       [ 1.25893336e-02],
       [ 5.47190793e-02],
       [ 4.89744157e-01],
       [ 6.32272065e-01],
       [ 6.80074096e-01],
       [ 7.37562716e-01],
       [ 8.05863619e-01],
       [ 7.57002354e-01],
       [ 7.93751836e-01],
       [ 8.10903907e-01],
       [ 7.20427215e-01],
       [ 4.12293881e-01],
       [ 3.82065065e-02],
       [ 4.78892773e-03],
       [ 3.74470931e-03],
       [ 3.83812655e-03],
       [ 4.70184125e-02],
       [ 4.90849108e-01],
       [ 5.13823628e-01],
       [ 6.48879707e-01],
       [ 7.87461817e-01],
       [ 1.04357970e+00],
       [ 8.48728359e-01],
       [ 2.20972344e-01],
       [ 2.34174449e-03],
       [ 3.77912354e-03],
       [ 3.28847356e-02],
       [ 2.38436446e-01],
       [ 5.15474916e-01],
       [ 2.98152775e-01],
       [ 3.55580598e-01],
       [ 4.88061994e-01],
       [ 6.28204226e-01],
       [ 4.10814077e-01],
       [ 4.05146867e-01]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
16400,642.0,1485.421686,1850.979413,NaN,NaN,NaN
16401,6804.0,11718.606066,11182.089488,NaN,NaN,NaN
16402,10501.0,18614.042112,19279.054526,NaN,NaN,NaN
16403,13147.0,17689.00615,17438.807493,NaN,NaN,NaN
16404,15536.0,17039.389972,16974.916203,NaN,NaN,NaN
...,...,...,...,...,...,...
18273,7356.0,6900.654023,5846.106045,712.266174,11134.365234,10667.417969
18274,17638.0,20543.60541,19516.687678,16165.256836,17797.712891,14641.859375
18275,23339.0,23189.371101,21231.472263,20088.689453,18955.470703,18846.126953
18276,26323.0,26104.467998,24456.544978,24133.009766,14881.110352,12324.421875
18278,25598.0,26678.02481,26577.9225,11201.456055,13956.507812,12154.406250

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1424.1067
RMSE: 2418.9925
R²: 0.9503
Random Forest
MAE: 1391.4381
RMSE: 2497.2550
R²: 0.9470
CTNET
MAE: 4856.1916
RMSE: 6664.5809
R²: 0.6342
Forecast
MAE: 4399.2846
RMSE: 6111.5054
R²: 0.6924
Photovoltaic
MAE: 4019.0234
RMSE: 5994.1247
R²: 0.7041

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

113/113 ━━━━━━━━━━━━━━━━━━━━ 19s 94ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

113/113 ━━━━━━━━━━━━━━━━━━━━ 21s 152ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

113/113 ━━━━━━━━━━━━━━━━━━━━ 12s 59ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
30,0.000000,38.404720,0.000000,NaN,NaN,NaN
31,0.000000,38.243795,33.638347,NaN,NaN,NaN
32,438.814997,743.496439,708.929118,NaN,NaN,NaN
33,5908.000884,9112.736385,6958.973311,NaN,NaN,NaN
34,5030.740421,9605.211233,6928.488764,NaN,NaN,NaN
...,...,...,...,...,...,...
12958,0.000000,0.000000,0.000000,337.538696,0.000000,746.106812
12967,0.000000,86.816623,0.000000,284.666016,0.000000,425.357269
12968,0.000000,50.108601,0.000000,350.532196,0.000000,672.581909
12969,295.000000,335.095107,282.147500,890.763672,0.000000,1797.385864
12970,9478.000000,5593.245834,8013.640000,4720.634766,6958.205566,8481.420898

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1192.3439
RMSE: 2165.4793
R²: 0.9500
Random Forest
MAE: 503.4792
RMSE: 979.1845
R²: 0.9898
CTNET
MAE: 3696.0014
RMSE: 5815.7206
R²: 0.6368
Forecast
MAE: 3715.3918
RMSE: 5986.6397
R²: 0.6151
Photovoltaic
MAE: 3427.5738
RMSE: 5252.4921
R²: 0.7037

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,...,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.3_Predicciones_Conjunto_nublado KMeans.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_3_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_3_RandomForest_model.pkl")

['4_3_RandomForest_model.pkl']

In [87]:
CTNET.save("4_3_CTNET_model.keras")
Forecast_model.save("4_3_Forecast_model.keras")
Photo_model.save("4_3_Photo_model.keras")