# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,7,77,0,4,15,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,7,82,0,4,16,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,9,85,0,3,16,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,11,87,0,3,16,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,11,88,0,3,16,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,15,86,0,3,14,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,47,89,0,3,16,6,Nublado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,51,95,0,4,17,7,Nublado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,47,100,0,3,18,8,Nublado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,5,100,1,4,18,9,Nublado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,5,93,2,4,18,10,Nublado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,5,79,2,4,17,11,Nublado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,5,64,6,3,15,12,Nublado,Lluvioso
13,2022-09-01 13:00:00,25478.471342,23,5,51,11,3,13,13,Soleado,Lluvioso
14,2022-09-01 14:00:00,29057.585772,25,3,41,12,1,11,14,Soleado,Lluvioso
15,2022-09-01 15:00:00,30000.000000,26,0,35,11,1,9,15,Soleado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,0,33,8,1,9,16,Soleado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,0,34,5,1,11,17,Soleado,Soleado
18,2022-09-01 18:00:00,29900.303971,27,0,37,3,2,11,18,Soleado,Soleado
19,2022-09-01 19:00:00,18282.505369,26,0,41,2,3,12,19,Soleado,Soleado
20,2022-09-01 20:00:00,3411.083740,24,2,48,0,3,12,20,Nublado,Lluvioso
21,2022-09-01 21:00:00,382.187718,22,6,55,0,3,13,21,Nublado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,6,61,0,4,13,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,6,68,0,4,14,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster GMM"] == "Soleado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
37,2022-09-02 13:00:00,20596.278869,23,0,45,5,2,11,13,Soleado,Soleado,27523.885172,25478.471342
207,2022-09-09 15:00:00,26098.851182,24,0,43,5,2,11,15,Soleado,Soleado,24394.058046,18959.491592
208,2022-09-09 16:00:00,28500.000000,25,0,39,4,2,10,16,Soleado,Soleado,26098.851182,16494.208425
209,2022-09-09 17:00:00,28500.000000,25,0,38,3,2,10,17,Soleado,Soleado,28500.000000,8718.476156
210,2022-09-09 18:00:00,28500.000000,26,0,36,2,2,10,18,Soleado,Soleado,28500.000000,23968.849012
211,2022-09-09 19:00:00,17303.091873,25,0,37,1,2,9,19,Soleado,Soleado,28500.000000,17559.996819
212,2022-09-09 20:00:00,2230.131403,24,0,40,0,2,9,20,Soleado,Soleado,17303.091873,2087.543919
229,2022-09-10 13:00:00,28500.000000,22,0,53,10,2,12,13,Soleado,Soleado,28976.805233,14247.046020
230,2022-09-10 14:00:00,28500.000000,23,0,47,11,2,11,14,Soleado,Soleado,28500.000000,24394.058046
231,2022-09-10 15:00:00,27067.944242,24,0,43,10,2,11,15,Soleado,Soleado,28500.000000,26098.851182

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
37,23,0,45,5,2,11,13,27523.885172,25478.471342
207,24,0,43,5,2,11,15,24394.058046,18959.491592
208,25,0,39,4,2,10,16,26098.851182,16494.208425
209,25,0,38,3,2,10,17,28500.000000,8718.476156
210,26,0,36,2,2,10,18,28500.000000,23968.849012
...,...,...,...,...,...,...,...,...,...
18280,25,0,34,5,3,8,15,25399.000000,25443.000000
18281,26,0,31,4,2,8,16,25562.000000,25385.000000
18282,26,0,32,2,1,8,17,25386.000000,22664.000000
18283,25,0,33,1,1,8,18,22872.000000,15736.000000
18284,23,0,38,0,1,8,19,15825.000000,1407.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
37     20596.278869
207    26098.851182
208    28500.000000
209    28500.000000
210    28500.000000
...             ...
18280  25562.000000
18281  25386.000000
18282  22872.000000
18283  15825.000000
18284   1450.000000

[3447 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 2412, y_train: 2412
X_val: 517, y_val: 517
X_test: 518, y_test: 518

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.39130435 0.         0.73076923 ... 0.46666667 0.91746284 0.84928238]
 [0.43478261 0.         0.69230769 ... 0.6        0.81313527 0.63198305]
 [0.47826087 0.         0.61538462 ... 0.66666667 0.86996171 0.54980695]
 ...
 [0.30434783 0.         0.40384615 ... 0.46666667 0.76026667 0.73196667]
 [0.34782609 0.         0.40384615 ... 0.53333333 0.73196667 0.70156667]
 [0.39130435 0.         0.42307692 ... 0.6        0.70156667 0.7206    ]]
(2412, 9)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
37,0.391304,0.0,0.730769,0.357143,0.333333,0.6875,0.466667,0.917463,0.849282
207,0.434783,0.0,0.692308,0.357143,0.333333,0.6875,0.600000,0.813135,0.631983
208,0.478261,0.0,0.615385,0.285714,0.333333,0.6250,0.666667,0.869962,0.549807
209,0.478261,0.0,0.596154,0.214286,0.333333,0.6250,0.733333,0.950000,0.290616
210,0.521739,0.0,0.557692,0.142857,0.333333,0.6250,0.800000,0.950000,0.798962
...,...,...,...,...,...,...,...,...,...
12286,0.260870,0.0,0.423077,0.000000,0.000000,0.1250,1.000000,0.000000,0.000000
12301,0.217391,0.0,0.442308,0.357143,0.000000,0.0625,0.400000,0.783667,0.760267
12302,0.304348,0.0,0.403846,0.357143,0.000000,0.1250,0.466667,0.760267,0.731967
12303,0.347826,0.0,0.403846,0.357143,0.000000,0.1875,0.533333,0.731967,0.701567
12304,0.391304,0.0,0.423077,0.285714,0.000000,0.2500,0.600000,0.701567,0.720600

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.47826087 0.         0.44230769 ... 0.66666667 0.7034     0.7193    ]
 [0.39130435 0.         0.57692308 ... 0.73333333 0.65726667 0.65726667]
 [0.34782609 0.         0.71153846 ... 0.8        0.6976     0.31023333]
 ...
 [0.82608696 0.         0.09615385 ... 0.46666667 0.77843333 0.77773333]
 [0.34782609 0.         0.34615385 ... 0.2        0.48006667 0.69496667]
 [0.56521739 0.         0.21153846 ... 0.26666667 0.81946667 0.7502    ]]
(517, 9)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
12305,0.478261,0.0,0.442308,0.214286,0.000000,0.3750,0.666667,0.703400,0.719300
12306,0.391304,0.0,0.576923,0.142857,0.000000,0.5000,0.733333,0.657267,0.657267
12307,0.347826,0.0,0.711538,0.071429,0.000000,0.5625,0.800000,0.697600,0.310233
12423,0.217391,0.0,0.788462,0.357143,0.333333,0.5000,0.533333,0.792533,0.490433
12424,0.304348,0.0,0.634615,0.285714,0.333333,0.4375,0.600000,0.783967,0.504200
...,...,...,...,...,...,...,...,...,...
14940,0.608696,0.0,0.250000,0.642857,0.000000,0.2500,0.333333,0.750200,0.785633
14941,0.739130,0.0,0.153846,0.857143,0.000000,0.1250,0.400000,0.766967,0.786967
14942,0.826087,0.0,0.096154,1.000000,0.000000,0.0000,0.466667,0.778433,0.777733
14962,0.347826,0.0,0.346154,0.214286,0.000000,0.0625,0.200000,0.480067,0.694967
14963,0.565217,0.0,0.211538,0.357143,0.000000,0.0625,0.266667,0.819467,0.750200

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.69565217 0.         0.11538462 ... 0.33333333 0.92343333 0.76696667]
 [0.82608696 0.         0.03846154 ... 0.4        0.95496667 0.77843333]
 [0.91304348 0.         0.         ... 0.46666667 0.95866667 0.78513333]
 ...
 [0.52173913 0.         0.48076923 ... 0.73333333 0.8462     0.75546667]
 [0.47826087 0.         0.5        ... 0.8        0.7624     0.52453333]
 [0.39130435 0.         0.59615385 ... 0.86666667 0.5275     0.0469    ]]
(518, 9)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
14964,0.695652,0.0,0.115385,0.642857,0.000000,0.0625,0.333333,0.923433,0.766967
14965,0.826087,0.0,0.038462,0.857143,0.000000,0.2500,0.400000,0.954967,0.778433
14966,0.913043,0.0,0.000000,1.000000,0.000000,0.3750,0.466667,0.958667,0.785133
14967,0.956522,0.0,-0.019231,0.857143,0.000000,0.3750,0.533333,0.960967,0.775267
14968,1.000000,0.0,-0.019231,0.642857,0.000000,0.3750,0.600000,0.860433,0.873567
...,...,...,...,...,...,...,...,...,...
18280,0.478261,0.0,0.519231,0.357143,0.666667,0.5000,0.600000,0.846633,0.848100
18281,0.521739,0.0,0.461538,0.285714,0.333333,0.5000,0.666667,0.852067,0.846167
18282,0.521739,0.0,0.480769,0.142857,0.000000,0.5000,0.733333,0.846200,0.755467
18283,0.478261,0.0,0.500000,0.071429,0.000000,0.5000,0.800000,0.762400,0.524533
18284,0.391304,0.0,0.596154,0.000000,0.000000,0.5000,0.866667,0.527500,0.046900

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.36       0.         0.73584906 ... 0.46666667 0.91746284 0.84928238]
 [0.4        0.         0.69811321 ... 0.6        0.81313527 0.63198305]
 [0.44       0.         0.62264151 ... 0.66666667 0.86996171 0.54980695]
 ...
 [0.48       0.         0.49056604 ... 0.73333333 0.8462     0.75546667]
 [0.44       0.         0.50943396 ... 0.8        0.7624     0.52453333]
 [0.36       0.         0.60377358 ... 0.86666667 0.5275     0.0469    ]]
(3447, 9)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
37,0.36,0.0,0.735849,0.357143,0.333333,0.6875,0.466667,0.917463,0.849282
207,0.40,0.0,0.698113,0.357143,0.333333,0.6875,0.600000,0.813135,0.631983
208,0.44,0.0,0.622642,0.285714,0.333333,0.6250,0.666667,0.869962,0.549807
209,0.44,0.0,0.603774,0.214286,0.333333,0.6250,0.733333,0.950000,0.290616
210,0.48,0.0,0.566038,0.142857,0.333333,0.6250,0.800000,0.950000,0.798962
...,...,...,...,...,...,...,...,...,...
18280,0.44,0.0,0.528302,0.357143,0.666667,0.5000,0.600000,0.846633,0.848100
18281,0.48,0.0,0.471698,0.285714,0.333333,0.5000,0.666667,0.852067,0.846167
18282,0.48,0.0,0.490566,0.142857,0.000000,0.5000,0.733333,0.846200,0.755467
18283,0.44,0.0,0.509434,0.071429,0.000000,0.5000,0.800000,0.762400,0.524533
18284,0.36,0.0,0.603774,0.000000,0.000000,0.5000,0.866667,0.527500,0.046900

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.68654263]
 [0.86996171]
 [0.95      ]
 ...
 [0.73196667]
 [0.70156667]
 [0.7034    ]]
(2412, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
37       0.686543
207      0.869962
208      0.950000
209      0.950000
210      0.950000
...           ...
12286    0.000000
12301    0.760267
12302    0.731967
12303    0.701567
12304    0.703400

[2412 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[6.57266667e-01]
 [6.97600000e-01]
 [2.98400000e-01]
 [7.83966667e-01]
 [7.82933333e-01]
 [7.82600000e-01]
 [7.53100000e-01]
 [4.56700000e-01]
 [4.34666667e-02]
 [0.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [2.00766667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.00000000e+00]
 [2.29400000e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [6.56666667e-01]
 [7.13833333e-01]
 [6.27166667e-01]
 [6.26333333e-01]
 [6.26066667e-01]
 [5.27166667e-01]
 [3.19666667e-01]
 [2.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.57766667e-01]
 [6.34033333e-01]
 [6.36166667e-01]
 [6.55400000e-01]
 [7.37566667e-01]
 [6.63633333e-01]
 [6.37766667e-01]
 [8.02466667e-01]
 [7.83966667e-01]
 [8.05566667e-01]
 [8.13566667e-01]
 [7.97433333e-01]
 [4.59833333e-01]
 [4.69333333e-02]
 [0.00000000e+00]
 [8.12700000e-01]
 [7.91266667e-01]
 [7.82000000e-01]
 [7.75200000e-01]
 [7.80900000e-01]
 [7.62700000e-01]
 [4.56633333e-01]
 [4.81000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.29366667e-01]
 [7.92533333e-01]
 [7.83966667e-01]
 [4.66666667e-01]
 [4.67666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.30866667e-01]
 [6.64266667e-01]
 [6.49600000e-01]
 [7.98233333e-01]
 [7.92033333e-01]
 [7.82033333e-01]
 [8.03066667e-01]
 [6.93200000e-01]
 [4.26033333e-01]
 [6.04666667e-02]
 [6.27166667e-01]
 [7.04633333e-01]
 [6.26066667e-01]
 [6.77800000e-01]
 [4.34333333e-01]
 [4.24666667e-02]
 [8.34500000e-01]
 [7.94033333e-01]
 [7.83966667e-01]
 [7.88233333e-01]
 [7.85266667e-01]
 [7.53400000e-01]
 [4.82533333e-01]
 [5.28333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.68100000e-01]
 [6.34033333e-01]
 [6.27166667e-01]
 [6.40133333e-01]
 [0.00000000e+00]
 [6.59100000e-01]
 [7.16500000e-01]
 [7.84200000e-01]
 [7.82933333e-01]
 [6.77800000e-01]
 [4.21233333e-01]
 [3.88333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.47166667e-01]
 [6.39833333e-01]
 [4.34033333e-01]
 [6.20000000e-02]
 [8.18533333e-01]
 [8.95366667e-01]
 [8.77033333e-01]
 [8.57166667e-01]
 [8.45600000e-01]
 [8.99033333e-01]
 [9.35800000e-01]
 [9.30666667e-01]
 [9.73033333e-01]
 [9.93833333e-01]
 [8.74733333e-01]
 [5.55833333e-01]
 [3.56000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.48066667e-01]
 [9.48866667e-01]
 [0.00000000e+00]
 [6.86233333e-01]
 [7.82533333e-01]
 [7.05233333e-01]
 [6.93266667e-01]
 [5.18433333e-01]
 [9.64333333e-02]
 [7.10033333e-01]
 [6.94200000e-01]
 [7.03733333e-01]
 [6.26766667e-01]
 [7.09333333e-01]
 [7.83833333e-01]
 [6.76500000e-01]
 [6.85366667e-01]
 [6.87533333e-01]
 [6.60733333e-01]
 [4.83800000e-01]
 [9.24333333e-02]
 [6.76500000e-01]
 [6.89666667e-01]
 [7.04466667e-01]
 [6.53366667e-01]
 [4.85666667e-01]
 [6.10033333e-01]
 [5.91933333e-01]
 [5.99333333e-01]
 [6.08266667e-01]
 [6.53366667e-01]
 [4.23333333e-01]
 [9.31666667e-02]
 [7.89800000e-01]
 [8.75533333e-01]
 [8.66100000e-01]
 [8.54000000e-01]
 [7.82533333e-01]
 [7.58700000e-01]
 [8.95366667e-01]
 [8.78733333e-01]
 [8.57166667e-01]
 [8.45600000e-01]
 [8.68233333e-01]
 [9.48333333e-01]
 [9.95633333e-01]
 [9.94466667e-01]
 [9.95933333e-01]
 [8.95366667e-01]
 [8.88700000e-01]
 [8.63266667e-01]
 [8.45600000e-01]
 [6.92400000e-01]
 [6.88233333e-01]
 [7.55933333e-01]
 [4.88400000e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.98466667e-01]
 [7.95000000e-01]
 [7.71466667e-01]
 [8.98300000e-01]
 [8.68166667e-01]
 [8.62933333e-01]
 [8.52733333e-01]
 [8.66466667e-01]
 [8.47600000e-01]
 [6.41966667e-01]
 [4.83833333e-01]
 [9.58000000e-02]
 [7.97966667e-01]
 [8.61000000e-01]
 [8.58433333e-01]
 [8.62066667e-01]
 [8.27033333e-01]
 [6.72166667e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [9.62433333e-01]
 [8.77033333e-01]
 [8.78666667e-01]
 [8.45600000e-01]
 [9.33600000e-01]
 [8.93933333e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.34900000e-01]
 [2.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.41633333e-01]
 [9.27633333e-01]
 [9.38033333e-01]
 [8.38033333e-01]
 [7.15233333e-01]
 [8.17833333e-01]
 [8.14000000e-01]
 [5.41133333e-01]
 [9.63333333e-02]
 [7.49966667e-01]
 [8.63900000e-01]
 [8.60000000e-01]
 [8.59233333e-01]
 [8.16733333e-01]
 [6.04733333e-01]
 [8.88066667e-01]
 [8.60833333e-01]
 [8.59400000e-01]
 [8.73633333e-01]
 [8.16733333e-01]
 [6.57833333e-01]
 [1.33966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.03966667e-01]
 [8.77033333e-01]
 [7.06200000e-01]
 [7.16300000e-01]
 [7.01633333e-01]
 [6.85733333e-01]
 [6.80666667e-01]
 [6.82566667e-01]
 [4.99900000e-01]
 [0.00000000e+00]
 [3.49533333e-01]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.48700000e-01]
 [7.42566667e-01]
 [9.28233333e-01]
 [9.26366667e-01]
 [9.25733333e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.45666667e-01]
 [9.38600000e-01]
 [9.28233333e-01]
 [9.26366667e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.77900000e-01]
 [7.15266667e-01]
 [9.43233333e-01]
 [9.40500000e-01]
 [9.26366667e-01]
 [9.32266667e-01]
 [9.13333333e-01]
 [8.77900000e-01]
 [7.08766667e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.95566667e-01]
 [9.94200000e-01]
 [9.87666667e-01]
 [1.18833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.48766667e-01]
 [7.60500000e-01]
 [7.42566667e-01]
 [7.41066667e-01]
 [7.40600000e-01]
 [8.18700000e-01]
 [5.67033333e-01]
 [1.55000000e-01]
 [0.00000000e+00]
 [7.40466667e-01]
 [7.53133333e-01]
 [7.69133333e-01]
 [7.50566667e-01]
 [7.42333333e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.72700000e-01]
 [1.58866667e-01]
 [0.00000000e+00]
 [7.48766667e-01]
 [7.56266667e-01]
 [7.60966667e-01]
 [7.49200000e-01]
 [7.40600000e-01]
 [6.36766667e-01]
 [0.00000000e+00]
 [9.35966667e-01]
 [9.38666667e-01]
 [8.46000000e-01]
 [8.37066667e-01]
 [7.42366667e-01]
 [7.27733333e-01]
 [7.90133333e-01]
 [6.37900000e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [7.49766667e-01]
 [7.54766667e-01]
 [5.72466667e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [8.42266667e-01]
 [7.42566667e-01]
 [9.28733333e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.85233333e-01]
 [6.39533333e-01]
 [1.65300000e-01]
 [7.48766667e-01]
 [7.55500000e-01]
 [7.48433333e-01]
 [8.33766667e-01]
 [7.43200000e-01]
 [7.98633333e-01]
 [6.37900000e-01]
 [2.08033333e-01]
 [9.35966667e-01]
 [9.35866667e-01]
 [9.30333333e-01]
 [9.34100000e-01]
 [9.35533333e-01]
 [5.46000000e-01]
 [5.34800000e-01]
 [4.25333333e-01]
 [1.48633333e-01]
 [0.00000000e+00]
 [8.57766667e-01]
 [8.80800000e-01]
 [7.52700000e-01]
 [8.79100000e-01]
 [8.84933333e-01]
 [9.96700000e-01]
 [9.97000000e-01]
 [9.97600000e-01]
 [9.94600000e-01]
 [9.61233333e-01]
 [9.12066667e-01]
 [8.52033333e-01]
 [5.46600000e-01]
 [9.53066667e-01]
 [9.50766667e-01]
 [9.40866667e-01]
 [9.51733333e-01]
 [9.49866667e-01]
 [3.46666667e-03]
 [0.00000000e+00]
 [7.62466667e-01]
 [7.62033333e-01]
 [8.50033333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [8.43900000e-01]
 [8.10266667e-01]
 [6.97233333e-01]
 [9.85466667e-01]
 [9.71233333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.74700000e-01]
 [9.68300000e-01]
 [9.85466667e-01]
 [9.71233333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [8.40366667e-01]
 [7.17966667e-01]
 [3.80000000e-03]
 [0.00000000e+00]
 [9.96533333e-01]
 [9.95033333e-01]
 [9.83733333e-01]
 [1.00000000e+00]
 [9.84933333e-01]
 [7.18566667e-01]
 [1.62233333e-01]
 [8.85433333e-01]
 [9.77866667e-01]
 [9.44766667e-01]
 [0.00000000e+00]
 [9.43300000e-01]
 [9.80200000e-01]
 [9.70766667e-01]
 [9.51266667e-01]
 [9.57466667e-01]
 [9.40866667e-01]
 [9.07500000e-01]
 [2.60000000e-03]
 [0.00000000e+00]
 [9.70566667e-01]
 [9.83000000e-01]
 [8.74100000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [6.09200000e-01]
 [2.20066667e-01]
 [4.03333333e-03]
 [9.58833333e-01]
 [9.36833333e-01]
 [9.39366667e-01]
 [9.40033333e-01]
 [0.00000000e+00]
 [7.45533333e-01]
 [7.42033333e-01]
 [7.50933333e-01]
 [7.49466667e-01]
 [7.54333333e-01]
 [8.42366667e-01]
 [8.33833333e-01]
 [9.09966667e-01]
 [9.42600000e-01]
 [9.46833333e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.26466667e-01]
 [8.09866667e-01]
 [0.00000000e+00]
 [8.39866667e-01]
 [9.36833333e-01]
 [9.36533333e-01]
 [9.33733333e-01]
 [9.33333333e-01]
 [9.38766667e-01]
 [9.45133333e-01]
 [8.40200000e-01]
 [1.03333333e-02]
 [0.00000000e+00]
 [7.47700000e-01]
 [7.49466667e-01]
 [4.22800000e-01]
 [6.52300000e-01]
 [8.98300000e-01]
 [9.42600000e-01]
 [9.40133333e-01]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.05200000e-01]
 [9.38133333e-01]
 [9.36833333e-01]
 [8.93333333e-03]
 [0.00000000e+00]
 [9.20300000e-01]
 [9.67966667e-01]
 [9.48966667e-01]
 [9.36900000e-01]
 [8.31733333e-01]
 [9.62566667e-01]
 [9.53566667e-01]
 [8.45700000e-01]
 [8.41600000e-01]
 [9.63333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.88366667e-01]
 [9.64300000e-01]
 [9.57766667e-01]
 [9.34333333e-01]
 [9.34400000e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.49966667e-01]
 [7.32000000e-01]
 [2.46333333e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [9.09966667e-01]
 [9.33200000e-01]
 [9.36833333e-01]
 [8.36033333e-01]
 [8.40566667e-01]
 [2.49333333e-01]
 [7.85633333e-01]
 [7.86966667e-01]
 [7.77733333e-01]
 [7.53266667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [0.00000000e+00]
 [6.94966667e-01]
 [7.50200000e-01]
 [7.66966667e-01]
 [7.78433333e-01]
 [7.85133333e-01]
 [8.19466667e-01]
 [9.23433333e-01]]
(517, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
12305    0.657267
12306    0.697600
12307    0.298400
12423    0.783967
12424    0.782933
...           ...
14940    0.766967
14941    0.778433
14942    0.785133
14962    0.819467
14963    0.923433

[517 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.95496667]
 [0.95866667]
 [0.96096667]
 [0.86043333]
 [0.85716667]
 [0.74293333]
 [0.73216667]
 [0.59493333]
 [0.21896667]
 [0.00806667]
 [0.        ]
 [0.93476667]
 [0.942     ]
 [0.92893333]
 [0.9326    ]
 [0.9653    ]
 [0.95383333]
 [0.85996667]
 [0.72946667]
 [0.2737    ]
 [0.9442    ]
 [0.93683333]
 [0.92893333]
 [0.9326    ]
 [0.97063333]
 [0.95473333]
 [0.8543    ]
 [0.71996667]
 [0.2737    ]
 [0.0095    ]
 [0.        ]
 [0.94696667]
 [0.9369    ]
 [0.92893333]
 [0.9326    ]
 [0.97063333]
 [0.95686667]
 [0.72766667]
 [0.01016667]
 [0.        ]
 [0.72796667]
 [0.751     ]
 [0.9429    ]
 [0.93506667]
 [0.885     ]
 [0.32096667]
 [0.0174    ]
 [0.        ]
 [0.95563333]
 [0.98136667]
 [0.97883333]
 [0.94683333]
 [0.92646667]
 [0.2737    ]
 [0.02876667]
 [0.        ]
 [0.9025    ]
 [0.9426    ]
 [0.93683333]
 [0.93753333]
 [0.9363    ]
 [0.92646667]
 [0.01706667]
 [0.        ]
 [0.90996667]
 [0.9332    ]
 [0.94056667]
 [0.93186667]
 [0.95676667]
 [0.83383333]
 [0.01043333]
 [0.        ]
 [0.9332    ]
 [0.9537    ]
 [0.85843333]
 [0.0191    ]
 [0.        ]
 [0.9332    ]
 [0.9479    ]
 [0.95776667]
 [0.96316667]
 [0.28226667]
 [0.01946667]
 [0.        ]
 [0.9348    ]
 [0.9332    ]
 [0.9484    ]
 [0.84483333]
 [0.96416667]
 [0.80986667]
 [0.67996667]
 [0.50303333]
 [0.11496667]
 [0.94396667]
 [0.97616667]
 [0.97016667]
 [0.97313333]
 [0.94583333]
 [0.9501    ]
 [0.94036667]
 [0.85836667]
 [0.79713333]
 [0.3988    ]
 [0.02593333]
 [0.93826667]
 [0.9582    ]
 [0.95276667]
 [0.94963333]
 [0.95856667]
 [0.9593    ]
 [0.82156667]
 [0.3956    ]
 [0.02733333]
 [0.        ]
 [0.94006667]
 [0.96873333]
 [0.95253333]
 [0.95486667]
 [0.97816667]
 [0.95946667]
 [0.02876667]
 [0.        ]
 [0.94243333]
 [0.94176667]
 [0.93916667]
 [0.93993333]
 [0.9288    ]
 [0.35676667]
 [0.0301    ]
 [0.        ]
 [0.77463333]
 [0.7569    ]
 [0.75133333]
 [0.8674    ]
 [0.77346667]
 [0.78006667]
 [0.94856667]
 [0.97976667]
 [0.9742    ]
 [0.98153333]
 [0.02813333]
 [0.91103333]
 [0.94243333]
 [0.94176667]
 [0.94386667]
 [0.9725    ]
 [0.03346667]
 [0.        ]
 [0.91103333]
 [0.943     ]
 [0.94176667]
 [0.94886667]
 [0.95573333]
 [0.95593333]
 [0.91103333]
 [0.9482    ]
 [0.94176667]
 [0.9482    ]
 [0.96123333]
 [0.95666667]
 [0.6952    ]
 [0.37006667]
 [0.03346667]
 [0.91103333]
 [0.9482    ]
 [0.94463333]
 [0.93916667]
 [0.6743    ]
 [0.8359    ]
 [0.8208    ]
 [0.70683333]
 [0.55156667]
 [0.38056667]
 [0.03136667]
 [0.        ]
 [0.97846667]
 [0.9731    ]
 [0.974     ]
 [0.9657    ]
 [0.8589    ]
 [0.7531    ]
 [0.818     ]
 [0.74176667]
 [0.3495    ]
 [0.02446667]
 [0.        ]
 [0.94716667]
 [0.9805    ]
 [0.9791    ]
 [0.9787    ]
 [0.9808    ]
 [0.98196667]
 [0.97453333]
 [0.96563333]
 [0.96843333]
 [0.96723333]
 [0.9436    ]
 [0.93903333]
 [0.92876667]
 [0.89913333]
 [0.6494    ]
 [0.9482    ]
 [0.94176667]
 [0.94283333]
 [0.93653333]
 [0.93116667]
 [0.9193    ]
 [0.785     ]
 [0.7128    ]
 [0.32696667]
 [0.9554    ]
 [0.94776667]
 [0.94003333]
 [0.93653333]
 [0.9356    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.40376667]
 [0.95456667]
 [0.97073333]
 [0.97656667]
 [0.94936667]
 [0.9278    ]
 [0.9074    ]
 [0.68956667]
 [0.6108    ]
 [0.37246667]
 [0.7711    ]
 [0.60836667]
 [0.85406667]
 [0.94046667]
 [0.9288    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.39786667]
 [0.03346667]
 [0.        ]
 [0.96963333]
 [0.97063333]
 [0.95266667]
 [0.9444    ]
 [0.9288    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.404     ]
 [0.03453333]
 [0.        ]
 [0.96546667]
 [0.96666667]
 [0.95023333]
 [0.94056667]
 [0.9288    ]
 [0.912     ]
 [0.86706667]
 [0.77026667]
 [0.41783333]
 [0.03356667]
 [0.        ]
 [0.94683333]
 [0.94586667]
 [0.93916667]
 [0.93653333]
 [0.9356    ]
 [0.3964    ]
 [0.03346667]
 [0.        ]
 [0.90956667]
 [0.93696667]
 [0.94776667]
 [0.94386667]
 [0.94176667]
 [0.94543333]
 [0.95876667]
 [0.94533333]
 [0.9314    ]
 [0.8848    ]
 [0.7935    ]
 [0.9218    ]
 [0.9522    ]
 [0.9401    ]
 [0.8244    ]
 [0.444     ]
 [0.42223333]
 [0.69733333]
 [0.32013333]
 [0.316     ]
 [0.37496667]
 [0.35636667]
 [0.3083    ]
 [0.336     ]
 [0.32383333]
 [0.9       ]
 [0.89676667]
 [0.8788    ]
 [0.89866667]
 [0.842     ]
 [0.85893333]
 [0.80036667]
 [0.7702    ]
 [0.91613333]
 [0.91063333]
 [0.90623333]
 [0.86173333]
 [0.77143333]
 [0.8048    ]
 [0.3632    ]
 [0.37996667]
 [0.83566667]
 [0.84806667]
 [0.85176667]
 [0.8617    ]
 [0.80903333]
 [0.78476667]
 [0.70753333]
 [0.824     ]
 [0.82563333]
 [0.5772    ]
 [0.49453333]
 [0.31843333]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.81956667]
 [0.82336667]
 [0.86173333]
 [0.79553333]
 [0.92623333]
 [0.92043333]
 [0.9242    ]
 [0.9156    ]
 [0.9099    ]
 [0.865     ]
 [0.69463333]
 [0.8345    ]
 [0.92103333]
 [0.9068    ]
 [0.91263333]
 [0.90873333]
 [0.9093    ]
 [0.87486667]
 [0.78106667]
 [0.38866667]
 [0.02246667]
 [0.92593333]
 [0.90816667]
 [0.92106667]
 [0.9109    ]
 [0.9121    ]
 [0.86623333]
 [0.78116667]
 [0.39193333]
 [0.92456667]
 [0.90863333]
 [0.9157    ]
 [0.91783333]
 [0.8249    ]
 [0.78143333]
 [0.69826667]
 [0.39193333]
 [0.9093    ]
 [0.90856667]
 [0.90463333]
 [0.88623333]
 [0.87336667]
 [0.8009    ]
 [0.92103333]
 [0.90856667]
 [0.9144    ]
 [0.8783    ]
 [0.80133333]
 [0.36993333]
 [0.92103333]
 [0.91476667]
 [0.9144    ]
 [0.90236667]
 [0.87806667]
 [0.85183333]
 [0.71376667]
 [0.30506667]
 [0.72986667]
 [0.90236667]
 [0.87826667]
 [0.76673333]
 [0.67466667]
 [0.93346667]
 [0.90503333]
 [0.87786667]
 [0.74743333]
 [0.44653333]
 [0.1602    ]
 [0.9386    ]
 [0.9374    ]
 [0.90716667]
 [0.81213333]
 [0.88676667]
 [0.83873333]
 [0.93563333]
 [0.9105    ]
 [0.90826667]
 [0.73996667]
 [0.92056667]
 [0.9436    ]
 [0.66456667]
 [0.5003    ]
 [0.75153333]
 [0.73483333]
 [0.75106667]
 [0.74076667]
 [0.70643333]
 [0.7315    ]
 [0.7242    ]
 [0.69666667]
 [0.66436667]
 [0.92286667]
 [0.95126667]
 [0.93203333]
 [0.8664    ]
 [0.832     ]
 [0.8181    ]
 [0.9275    ]
 [0.92473333]
 [0.91503333]
 [0.9171    ]
 [0.9446    ]
 [0.8959    ]
 [0.87016667]
 [0.86333333]
 [0.96596667]
 [0.96363333]
 [0.9583    ]
 [0.9552    ]
 [0.95      ]
 [0.92596667]
 [0.8974    ]
 [0.76766667]
 [0.20596667]
 [0.96363333]
 [0.9616    ]
 [0.9552    ]
 [0.95      ]
 [0.92596667]
 [0.88663333]
 [0.75743333]
 [0.93206667]
 [0.93726667]
 [0.91026667]
 [0.7636    ]
 [0.92233333]
 [0.90866667]
 [0.90966667]
 [0.90236667]
 [0.87976667]
 [0.8222    ]
 [0.8321    ]
 [0.58226667]
 [0.71526667]
 [0.71113333]
 [0.91693333]
 [0.91146667]
 [0.8941    ]
 [0.89443333]
 [0.71126667]
 [0.91443333]
 [0.87146667]
 [0.906     ]
 [0.87833333]
 [0.9114    ]
 [0.91413333]
 [0.906     ]
 [0.87833333]
 [0.59856667]
 [0.89613333]
 [0.89583333]
 [0.88786667]
 [0.86076667]
 [0.5905    ]
 [0.8883    ]
 [0.82103333]
 [0.85373333]
 [0.7758    ]
 [0.59476667]
 [0.8923    ]
 [0.89613333]
 [0.89583333]
 [0.78563333]
 [0.71536667]
 [0.52683333]
 [0.87756667]
 [0.8949    ]
 [0.88706667]
 [0.8509    ]
 [0.77896667]
 [0.53383333]
 [0.84156667]
 [0.84376667]
 [0.75776667]
 [0.85263333]
 [0.84776667]
 [0.8391    ]
 [0.76006667]
 [0.52973333]
 [0.8762    ]
 [0.8551    ]
 [0.8454    ]
 [0.8481    ]
 [0.84616667]
 [0.75546667]
 [0.52453333]
 [0.8759    ]
 [0.84663333]
 [0.85206667]
 [0.8462    ]
 [0.7624    ]
 [0.5275    ]
 [0.04833333]]
(518, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
14964    0.954967
14965    0.958667
14966    0.960967
14967    0.860433
14968    0.857167
...           ...
18280    0.852067
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333

[518 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.68654263]
 [0.86996171]
 [0.95      ]
 ...
 [0.7624    ]
 [0.5275    ]
 [0.04833333]]
(3447, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
37       0.686543
207      0.869962
208      0.950000
209      0.950000
210      0.950000
...           ...
18280    0.852067
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333

[3447 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.136681 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 634
[LightGBM] [Info] Number of data points in the train set: 2412, number of used features: 8
[LightGBM] [Info] Start training from score 0.648351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
14964  27185.207433
14965  27412.001868
14966  27287.213123
14967  27286.866434
14968  25854.662495
...             ...
18280  26531.749471
18281  26682.293871
18282  23121.786144
18283  14935.714871
18284   1709.206578

[518 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
14964     28649.0
14965     28760.0
14966     28829.0
14967     25813.0
14968     25715.0
...           ...
18280     25562.0
18281     25386.0
18282     22872.0
18283     15825.0
18284      1450.0

[518 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
14964     28649.0  27185.207433
14965     28760.0  27412.001868
14966     28829.0  27287.213123
14967     25813.0  27286.866434
14968     25715.0  25854.662495
...           ...           ...
18280     25562.0  26531.749471
18281     25386.0  26682.293871
18282     22872.0  23121.786144
18283     15825.0  14935.714871
18284      1450.0   1709.206578

[518 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1019.5988
RMSE: 1823.2087
R²: 0.9533

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
14964     28649.0  27185.207433  28570.205916
14965     28760.0  27412.001868  28087.903653
14966     28829.0  27287.213123  28487.044034
14967     25813.0  27286.866434  28368.003603
14968     25715.0  25854.662495      25979.49
...           ...           ...           ...
18280     25562.0  26531.749471  26013.520588
18281     25386.0  26682.293871   26161.99488
18282     22872.0  23121.786144  22550.322475
18283     15825.0  14935.714871  16669.129145
18284      1450.0   1709.206578   1857.219074

[518 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (2364, 48, 9), y_train: (2364, 1)
X_val: (469, 48, 9), y_val: (469, 1)
X_test: (470, 48, 9), y_test: (470, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 60s 3s/step - loss: 0.5577 - mean_absolute_error: 0.6581 - mean_absolute_percentage_error: 119361.3438 - root_mean_squared_error: 0.7468 - val_loss: 0.4494 - val_mean_absolute_error: 0.5933 - val_mean_absolute_percentage_error: 697790.1875 - val_root_mean_squared_error: 0.6704
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 9s 2s/step - loss: 0.5517 - mean_absolute_error: 0.6572 - mean_absolute_percentage_error: 693157.3125 - root_mean_squared_error: 0.7427 - val_loss: 0.4396 - val_mean_absolute_error: 0.5867 - val_mean_absolute_percentage_error: 1513854.8750 - val_root_mean_squared_error: 0.6630
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 15s 3s/step - loss: 0.5370 - mean_absolute_error: 0.6459 - mean_absolute_percentage_error: 1352204.8750 - root_mean_squared_error: 0.7328 - val_loss: 0.4284 - val_mean_absolute_error: 0.5792 - val_mean_absolute_percentage_error: 2459601.7500 - val_root_mean_squared_error: 0.6545
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 17s 1s/step - loss: 0.5142 - mean_absolute_error: 0.6287 - mean_absolute_percentage_error: 2111813.0000 - root_mean_squared_error: 0.7170 - val_loss: 0.4155 - val_mean_absolute_error: 0.5705 - val_mean_absolute_percentage_error: 3561953.2500 - val_root_mean_squared_error: 0.6446
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 2s/step - loss: 0.5017 - mean_absolute_error: 0.6220 - mean_absolute_percentage_error: 3251728.0000 - root_mean_squared_error: 0.7083 - val_loss: 0.4008 - val_mean_absolute_error: 0.5608 - val_mean_absolute_percentage_error: 4854878.5000 - val_root_mean_squared_error: 0.6331
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.4956 - mean_absolute_error: 0.6216 - mean_absolute_percentage_error: 4143533.5000 - root_mean_squared_error: 0.7040 - val_loss: 0.3838 - val_mean_absolute_error: 0.5494 - val_mean_absolute_percentage_error: 6385217.0000 - val_root_mean_squared_error: 0.6195
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.4785 - mean_absolute_error: 0.6115 - mean_absolute_percentage_error: 5463350.5000 - root_mean_squared_error: 0.6917 - val_loss: 0.3642 - val_mean_absolute_error: 0.5363 - val_mean_absolute_percentage_error: 8200452.0000 - val_root_mean_squared_error: 0.6035
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 12s 2s/step - loss: 0.4494 - mean_absolute_error: 0.5924 - mean_absolute_percentage_error: 6882520.5000 - root_mean_squared_error: 0.6704 - val_loss: 0.3420 - val_mean_absolute_error: 0.5211 - val_mean_absolute_percentage_error: 10353772.0000 - val_root_mean_squared_error: 0.5848
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 13s 3s/step - loss: 0.4203 - mean_absolute_error: 0.5722 - mean_absolute_percentage_error: 9385202.0000 - root_mean_squared_error: 0.6483 - val_loss: 0.3170 - val_mean_absolute_error: 0.5038 - val_mean_absolute_percentage_error: 12899406.0000 - val_root_mean_squared_error: 0.5630
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.3923 - mean_absolute_error: 0.5546 - mean_absolute_percentage_error: 11160728.0000 - root_mean_squared_error: 0.6263 - val_loss: 0.2892 - val_mean_absolute_error: 0.4845 - val_mean_absolute_percentage_error: 15894766.0000 - val_root_mean_squared_error: 0.5378
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 2s/step - loss: 0.3667 - mean_absolute_error: 0.5368 - mean_absolute_percentage_error: 13683528.0000 - root_mean_squared_error: 0.6055 - val_loss: 0.2591 - val_mean_absolute_error: 0.4624 - val_mean_absolute_percentage_error: 19411222.0000 - val_root_mean_squared_error: 0.5090
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 15s 3s/step - loss: 0.3259 - mean_absolute_error: 0.5067 - mean_absolute_percentage_error: 17948050.0000 - root_mean_squared_error: 0.5709 - val_loss: 0.2273 - val_mean_absolute_error: 0.4368 - val_mean_absolute_percentage_error: 23500180.0000 - val_root_mean_squared_error: 0.4768
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.2900 - mean_absolute_error: 0.4797 - mean_absolute_percentage_error: 20976548.0000 - root_mean_squared_error: 0.5385 - val_loss: 0.1950 - val_mean_absolute_error: 0.4072 - val_mean_absolute_percentage_error: 28229652.0000 - val_root_mean_squared_error: 0.4416
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 14s 3s/step - loss: 0.2582 - mean_absolute_error: 0.4574 - mean_absolute_percentage_error: 24346274.0000 - root_mean_squared_error: 0.5081 - val_loss: 0.1638 - val_mean_absolute_error: 0.3752 - val_mean_absolute_percentage_error: 33620760.0000 - val_root_mean_squared_error: 0.4047
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 24s 4s/step - loss: 0.2252 - mean_absolute_error: 0.4325 - mean_absolute_percentage_error: 29795160.0000 - root_mean_squared_error: 0.4744 - val_loss: 0.1363 - val_mean_absolute_error: 0.3412 - val_mean_absolute_percentage_error: 39626144.0000 - val_root_mean_squared_error: 0.3692
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1890 - mean_absolute_error: 0.3992 - mean_absolute_percentage_error: 33717728.0000 - root_mean_squared_error: 0.4347 - val_loss: 0.1153 - val_mean_absolute_error: 0.3068 - val_mean_absolute_percentage_error: 46058500.0000 - val_root_mean_squared_error: 0.3395
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 13s 3s/step - loss: 0.1632 - mean_absolute_error: 0.3731 - mean_absolute_percentage_error: 39962816.0000 - root_mean_squared_error: 0.4039 - val_loss: 0.1027 - val_mean_absolute_error: 0.2770 - val_mean_absolute_percentage_error: 52696684.0000 - val_root_mean_squared_error: 0.3205
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 2s/step - loss: 0.1458 - mean_absolute_error: 0.3481 - mean_absolute_percentage_error: 42737900.0000 - root_mean_squared_error: 0.3818 - val_loss: 0.0994 - val_mean_absolute_error: 0.2569 - val_mean_absolute_percentage_error: 58977832.0000 - val_root_mean_squared_error: 0.3152
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 961ms/step - loss: 0.1371 - mean_absolute_error: 0.3257 - mean_absolute_percentage_error: 52742880.0000 - root_mean_squared_error: 0.3702 - val_loss: 0.1028 - val_mean_absolute_error: 0.2484 - val_mean_absolute_percentage_error: 64091592.0000 - val_root_mean_squared_error: 0.3207
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.1380 - mean_absolute_error: 0.3161 - mean_absolute_percentage_error: 54613504.0000 - root_mean_squared_error: 0.3714 - val_loss: 0.1077 - val_mean_absolute_error: 0.2472 - val_mean_absolute_percentage_error: 67196304.0000 - val_root_mean_squared_error: 0.3281
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 2s/step - loss: 0.1414 - mean_absolute_error: 0.3138 - mean_absolute_percentage_error: 58976480.0000 - root_mean_squared_error: 0.3759 - val_loss: 0.1088 - val_mean_absolute_error: 0.2471 - val_mean_absolute_percentage_error: 67763592.0000 - val_root_mean_squared_error: 0.3298
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.1361 - mean_absolute_error: 0.3069 - mean_absolute_percentage_error: 54025364.0000 - root_mean_squared_error: 0.3688 - val_loss: 0.1066 - val_mean_absolute_error: 0.2469 - val_mean_absolute_percentage_error: 66590560.0000 - val_root_mean_squared_error: 0.3264
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.1371 - mean_absolute_error: 0.3085 - mean_absolute_percentage_error: 54790944.0000 - root_mean_squared_error: 0.3702 - val_loss: 0.1031 - val_mean_absolute_error: 0.2476 - val_mean_absolute_percentage_error: 64392540.0000 - val_root_mean_squared_error: 0.3211
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.1369 - mean_absolute_error: 0.3162 - mean_absolute_percentage_error: 51865956.0000 - root_mean_squared_error: 0.3700 - val_loss: 0.1006 - val_mean_absolute_error: 0.2502 - val_mean_absolute_percentage_error: 62109084.0000 - val_root_mean_squared_error: 0.3172
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 2s/step - loss: 0.1341 - mean_absolute_error: 0.3182 - mean_absolute_percentage_error: 53045072.0000 - root_mean_squared_error: 0.3662 - val_loss: 0.0995 - val_mean_absolute_error: 0.2528 - val_mean_absolute_percentage_error: 60494100.0000 - val_root_mean_squared_error: 0.3154
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1332 - mean_absolute_error: 0.3207 - mean_absolute_percentage_error: 50352032.0000 - root_mean_squared_error: 0.3650 - val_loss: 0.0991 - val_mean_absolute_error: 0.2538 - val_mean_absolute_percentage_error: 59871712.0000 - val_root_mean_squared_error: 0.3148
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 2s/step - loss: 0.1358 - mean_absolute_error: 0.3243 - mean_absolute_percentage_error: 55639048.0000 - root_mean_squared_error: 0.3685 - val_loss: 0.0990 - val_mean_absolute_error: 0.2536 - val_mean_absolute_percentage_error: 59883752.0000 - val_root_mean_squared_error: 0.3147
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 877ms/step - loss: 0.1294 - mean_absolute_error: 0.3142 - mean_absolute_percentage_error: 51514276.0000 - root_mean_squared_error: 0.3597 - val_loss: 0.0993 - val_mean_absolute_error: 0.2519 - val_mean_absolute_percentage_error: 60630412.0000 - val_root_mean_squared_error: 0.3151
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.1282 - mean_absolute_error: 0.3126 - mean_absolute_percentage_error: 50820412.0000 - root_mean_squared_error: 0.3580 - val_loss: 0.0996 - val_mean_absolute_error: 0.2503 - val_mean_absolute_percentage_error: 61399472.0000 - val_root_mean_squared_error: 0.3157
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1301 - mean_absolute_error: 0.3101 - mean_absolute_percentage_error: 53174812.0000 - root_mean_squared_error: 0.3607 - val_loss: 0.1000 - val_mean_absolute_error: 0.2490 - val_mean_absolute_percentage_error: 62045984.0000 - val_root_mean_squared_error: 0.3163
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1286 - mean_absolute_error: 0.3085 - mean_absolute_percentage_error: 48862676.0000 - root_mean_squared_error: 0.3586 - val_loss: 0.0999 - val_mean_absolute_error: 0.2485 - val_mean_absolute_percentage_error: 62094148.0000 - val_root_mean_squared_error: 0.3161
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1239 - mean_absolute_error: 0.3003 - mean_absolute_percentage_error: 49711672.0000 - root_mean_squared_error: 0.3521 - val_loss: 0.0993 - val_mean_absolute_error: 0.2491 - val_mean_absolute_percentage_error: 61487668.0000 - val_root_mean_squared_error: 0.3151
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.1288 - mean_absolute_error: 0.3070 - mean_absolute_percentage_error: 52038344.0000 - root_mean_squared_error: 0.3588 - val_loss: 0.0985 - val_mean_absolute_error: 0.2503 - val_mean_absolute_percentage_error: 60591268.0000 - val_root_mean_squared_error: 0.3139
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.1244 - mean_absolute_error: 0.2996 - mean_absolute_percentage_error: 48048920.0000 - root_mean_squared_error: 0.3527 - val_loss: 0.0979 - val_mean_absolute_error: 0.2517 - val_mean_absolute_percentage_error: 59648444.0000 - val_root_mean_squared_error: 0.3129
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1274 - mean_absolute_error: 0.3026 - mean_absolute_percentage_error: 50138124.0000 - root_mean_squared_error: 0.3570 - val_loss: 0.0975 - val_mean_absolute_error: 0.2526 - val_mean_absolute_percentage_error: 59045084.0000 - val_root_mean_squared_error: 0.3123
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.1233 - mean_absolute_error: 0.2980 - mean_absolute_percentage_error: 50599120.0000 - root_mean_squared_error: 0.3511 - val_loss: 0.0973 - val_mean_absolute_error: 0.2534 - val_mean_absolute_percentage_error: 58666828.0000 - val_root_mean_squared_error: 0.3119
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 895ms/step - loss: 0.1217 - mean_absolute_error: 0.2948 - mean_absolute_percentage_error: 51711296.0000 - root_mean_squared_error: 0.3488 - val_loss: 0.0971 - val_mean_absolute_error: 0.2542 - val_mean_absolute_percentage_error: 58371976.0000 - val_root_mean_squared_error: 0.3117
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.1191 - mean_absolute_error: 0.2918 - mean_absolute_percentage_error: 50898296.0000 - root_mean_squared_error: 0.3451 - val_loss: 0.0971 - val_mean_absolute_error: 0.2552 - val_mean_absolute_percentage_error: 58104440.0000 - val_root_mean_squared_error: 0.3116
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1163 - mean_absolute_error: 0.2857 - mean_absolute_percentage_error: 46673500.0000 - root_mean_squared_error: 0.3410 - val_loss: 0.0972 - val_mean_absolute_error: 0.2566 - val_mean_absolute_percentage_error: 57849544.0000 - val_root_mean_squared_error: 0.3118
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1186 - mean_absolute_error: 0.2830 - mean_absolute_percentage_error: 48554384.0000 - root_mean_squared_error: 0.3444 - val_loss: 0.0978 - val_mean_absolute_error: 0.2620 - val_mean_absolute_percentage_error: 56597252.0000 - val_root_mean_squared_error: 0.3127
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1174 - mean_absolute_error: 0.2827 - mean_absolute_percentage_error: 50556376.0000 - root_mean_squared_error: 0.3427 - val_loss: 0.0987 - val_mean_absolute_error: 0.2670 - val_mean_absolute_percentage_error: 55574356.0000 - val_root_mean_squared_error: 0.3141
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.1179 - mean_absolute_error: 0.2837 - mean_absolute_percentage_error: 52298132.0000 - root_mean_squared_error: 0.3433 - val_loss: 0.0995 - val_mean_absolute_error: 0.2701 - val_mean_absolute_percentage_error: 55003672.0000 - val_root_mean_squared_error: 0.3155
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1156 - mean_absolute_error: 0.2813 - mean_absolute_percentage_error: 53961828.0000 - root_mean_squared_error: 0.3400 - val_loss: 0.1005 - val_mean_absolute_error: 0.2734 - val_mean_absolute_percentage_error: 54401308.0000 - val_root_mean_squared_error: 0.3170
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1164 - mean_absolute_error: 0.2760 - mean_absolute_percentage_error: 51747704.0000 - root_mean_squared_error: 0.3412 - val_loss: 0.1008 - val_mean_absolute_error: 0.2737 - val_mean_absolute_percentage_error: 54545488.0000 - val_root_mean_squared_error: 0.3175
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - loss: 0.1122 - mean_absolute_error: 0.2696 - mean_absolute_percentage_error: 52206472.0000 - root_mean_squared_error: 0.3349 - val_loss: 0.1007 - val_mean_absolute_error: 0.2713 - val_mean_absolute_percentage_error: 55265960.0000 - val_root_mean_squared_error: 0.3173
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 9s 3s/step - loss: 0.1168 - mean_absolute_error: 0.2727 - mean_absolute_percentage_error: 51481520.0000 - root_mean_squared_error: 0.3418 - val_loss: 0.1020 - val_mean_absolute_error: 0.2775 - val_mean_absolute_percentage_error: 53725340.0000 - val_root_mean_squared_error: 0.3194
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 2s/step - loss: 0.1123 - mean_absolute_error: 0.2665 - mean_absolute_percentage_error: 50448296.0000 - root_mean_squared_error: 0.3351 - val_loss: 0.1032 - val_mean_absolute_error: 0.2821 - val_mean_absolute_percentage_error: 52408620.0000 - val_root_mean_squared_error: 0.3213
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 2s/step - loss: 0.1098 - mean_absolute_error: 0.2710 - mean_absolute_percentage_error: 48847120.0000 - root_mean_squared_error: 0.3314 - val_loss: 0.1033 - val_mean_absolute_error: 0.2821 - val_mean_absolute_percentage_error: 52254368.0000 - val_root_mean_squared_error: 0.3214
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.1127 - mean_absolute_error: 0.2733 - mean_absolute_percentage_error: 49825396.0000 - root_mean_squared_error: 0.3357 - val_loss: 0.1038 - val_mean_absolute_error: 0.2833 - val_mean_absolute_percentage_error: 51793568.0000 - val_root_mean_squared_error: 0.3221
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - loss: 0.1089 - mean_absolute_error: 0.2662 - mean_absolute_percentage_error: 46043748.0000 - root_mean_squared_error: 0.3299 - val_loss: 0.1038 - val_mean_absolute_error: 0.2832 - val_mean_absolute_percentage_error: 51656284.0000 - val_root_mean_squared_error: 0.3223

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

15/15 ━━━━━━━━━━━━━━━━━━━━ 7s 211ms/step

array([[0.6555535 ],
       [0.657108  ],
       [0.66575843],
       [0.67059064],
       [0.67342776],
       [0.6734868 ],
       [0.6588155 ],
       [0.65137315],
       [0.6465503 ],
       [0.65660775],
       [0.68172014],
       [0.7023173 ],
       [0.7032907 ],
       [0.69911325],
       [0.6897924 ],
       [0.6595206 ],
       [0.64228725],
       [0.64479864],
       [0.66371757],
       [0.68432707],
       [0.7015709 ],
       [0.70158476],
       [0.69555736],
       [0.6653968 ],
       [0.6422406 ],
       [0.638246  ],
       [0.64928025],
       [0.6652941 ],
       [0.65014344],
       [0.6521908 ],
       [0.6711165 ],
       [0.69056696],
       [0.6881078 ],
       [0.6806459 ],
       [0.6550373 ],
       [0.6355596 ],
       [0.6199139 ],
       [0.6243264 ],
       [0.6434951 ],
       [0.668917  ],
       [0.68629766],
       [0.69210255],
       [0.67970866],
       [0.6623308 ],
       [0.6507131 ],
       [0.63970923],
       [0.65185446],
       [0.6772718 ],
       [0.7013463 ],
       [0.7021515 ],
       [0.6999046 ],
       [0.69650656],
       [0.68802375],
       [0.68016195],
       [0.6796826 ],
       [0.6833284 ],
       [0.6860558 ],
       [0.68829805],
       [0.6944808 ],
       [0.6982843 ],
       [0.7017667 ],
       [0.7016818 ],
       [0.70508367],
       [0.70658267],
       [0.7029021 ],
       [0.68691415],
       [0.6687103 ],
       [0.6638971 ],
       [0.67390686],
       [0.68380606],
       [0.6959042 ],
       [0.71242756],
       [0.72386926],
       [0.69847673],
       [0.67961204],
       [0.68750995],
       [0.7113294 ],
       [0.72786576],
       [0.729593  ],
       [0.7289143 ],
       [0.71070796],
       [0.69706774],
       [0.69620734],
       [0.7126041 ],
       [0.7305842 ],
       [0.73598564],
       [0.7339349 ],
       [0.7293015 ],
       [0.71638936],
       [0.71274   ],
       [0.72499746],
       [0.7355284 ],
       [0.7458689 ],
       [0.7418178 ],
       [0.74385995],
       [0.74764705],
       [0.74893135],
       [0.74730974],
       [0.7430975 ],
       [0.723619  ],
       [0.7134374 ],
       [0.7174209 ],
       [0.73117   ],
       [0.746961  ],
       [0.7608718 ],
       [0.7616572 ],
       [0.7575678 ],
       [0.75049376],
       [0.74983364],
       [0.74982315],
       [0.7521592 ],
       [0.7591766 ],
       [0.7670751 ],
       [0.76892394],
       [0.7706473 ],
       [0.7644766 ],
       [0.7604363 ],
       [0.76280504],
       [0.76567584],
       [0.76637655],
       [0.76875764],
       [0.7747093 ],
       [0.7788089 ],
       [0.7740618 ],
       [0.7652994 ],
       [0.7565421 ],
       [0.74789304],
       [0.74078643],
       [0.7529066 ],
       [0.7675058 ],
       [0.7765824 ],
       [0.7772753 ],
       [0.77684563],
       [0.7747459 ],
       [0.7677358 ],
       [0.7592228 ],
       [0.7561683 ],
       [0.7494975 ],
       [0.73891366],
       [0.73453516],
       [0.74520534],
       [0.7576684 ],
       [0.7579339 ],
       [0.754494  ],
       [0.7548504 ],
       [0.7546193 ],
       [0.75296104],
       [0.7640739 ],
       [0.77471954],
       [0.7766214 ],
       [0.7770392 ],
       [0.77652955],
       [0.77336735],
       [0.76901054],
       [0.77100605],
       [0.77334297],
       [0.77383375],
       [0.7727272 ],
       [0.77179265],
       [0.7702294 ],
       [0.7684278 ],
       [0.7668467 ],
       [0.7646707 ],
       [0.7736087 ],
       [0.77906936],
       [0.7803119 ],
       [0.77979463],
       [0.77978885],
       [0.77703255],
       [0.77199817],
       [0.7678308 ],
       [0.7622606 ],
       [0.76661944],
       [0.7772494 ],
       [0.78685874],
       [0.79438037],
       [0.7948871 ],
       [0.79173636],
       [0.78709006],
       [0.78184325],
       [0.77332157],
       [0.77350485],
       [0.7796456 ],
       [0.78553885],
       [0.7911962 ],
       [0.79660946],
       [0.80018836],
       [0.7991556 ],
       [0.7956792 ],
       [0.78913784],
       [0.780151  ],
       [0.7730591 ],
       [0.7728345 ],
       [0.7770401 ],
       [0.7799626 ],
       [0.7803657 ],
       [0.77707833],
       [0.7713799 ],
       [0.7654198 ],
       [0.7594472 ],
       [0.75320065],
       [0.7463998 ],
       [0.7342778 ],
       [0.7350065 ],
       [0.7385436 ],
       [0.73959386],
       [0.74127346],
       [0.74446625],
       [0.74294543],
       [0.7452057 ],
       [0.74756587],
       [0.7315333 ],
       [0.7120927 ],
       [0.69469565],
       [0.6961925 ],
       [0.70512307],
       [0.7137352 ],
       [0.72260314],
       [0.728625  ],
       [0.7198975 ],
       [0.69797117],
       [0.67254966],
       [0.6649514 ],
       [0.6732828 ],
       [0.68436575],
       [0.68556815],
       [0.6952227 ],
       [0.7123859 ],
       [0.7266888 ],
       [0.7236231 ],
       [0.715733  ],
       [0.70424414],
       [0.68611807],
       [0.68998694],
       [0.7032325 ],
       [0.71845824],
       [0.7316241 ],
       [0.7424963 ],
       [0.74470145],
       [0.7448805 ],
       [0.735679  ],
       [0.72650355],
       [0.71807486],
       [0.7096683 ],
       [0.6874365 ],
       [0.67444634],
       [0.6706851 ],
       [0.67609084],
       [0.69361377],
       [0.71317154],
       [0.72845954],
       [0.7176364 ],
       [0.69649863],
       [0.67379344],
       [0.65379703],
       [0.66156   ],
       [0.6693824 ],
       [0.67036575],
       [0.67410535],
       [0.68097574],
       [0.6857931 ],
       [0.6851217 ],
       [0.66135967],
       [0.65322757],
       [0.64211214],
       [0.6342055 ],
       [0.62431914],
       [0.62594277],
       [0.637277  ],
       [0.6428265 ],
       [0.6462697 ],
       [0.63313776],
       [0.6137832 ],
       [0.59448785],
       [0.56739324],
       [0.5680003 ],
       [0.5725133 ],
       [0.5754687 ],
       [0.57880884],
       [0.58304507],
       [0.5827651 ],
       [0.55888265],
       [0.5584287 ],
       [0.5674482 ],
       [0.57659274],
       [0.58911425],
       [0.59658194],
       [0.6025762 ],
       [0.59320873],
       [0.607801  ],
       [0.61889404],
       [0.64357936],
       [0.6697948 ],
       [0.687549  ],
       [0.6918905 ],
       [0.6843127 ],
       [0.66868716],
       [0.6459388 ],
       [0.62684655],
       [0.64600736],
       [0.6727333 ],
       [0.696443  ],
       [0.71373355],
       [0.70839375],
       [0.69682235],
       [0.6894284 ],
       [0.68399346],
       [0.69913054],
       [0.719109  ],
       [0.738215  ],
       [0.7550475 ],
       [0.7570065 ],
       [0.754722  ],
       [0.74950916],
       [0.738814  ],
       [0.7473222 ],
       [0.7552044 ],
       [0.7645051 ],
       [0.76317096],
       [0.7597755 ],
       [0.7599986 ],
       [0.7709532 ],
       [0.7801059 ],
       [0.77596647],
       [0.7661562 ],
       [0.75795835],
       [0.7450281 ],
       [0.7530022 ],
       [0.76186544],
       [0.7687506 ],
       [0.76493794],
       [0.75867826],
       [0.75012165],
       [0.7383259 ],
       [0.7242072 ],
       [0.73519695],
       [0.74196166],
       [0.7355607 ],
       [0.72497207],
       [0.70333105],
       [0.69436026],
       [0.68885   ],
       [0.6830744 ],
       [0.6825139 ],
       [0.6832488 ],
       [0.6766431 ],
       [0.6984316 ],
       [0.7018257 ],
       [0.7024006 ],
       [0.7020846 ],
       [0.6964577 ],
       [0.68322414],
       [0.69091433],
       [0.69864553],
       [0.702953  ],
       [0.6908248 ],
       [0.68277526],
       [0.6728675 ],
       [0.6608232 ],
       [0.6469255 ],
       [0.65020186],
       [0.6559222 ],
       [0.6584223 ],
       [0.6418434 ],
       [0.62006664],
       [0.60818106],
       [0.6025306 ],
       [0.5978479 ],
       [0.59629035],
       [0.5967255 ],
       [0.6007708 ],
       [0.6097084 ],
       [0.6205508 ],
       [0.6233856 ],
       [0.62515354],
       [0.62634206],
       [0.6296429 ],
       [0.6362012 ],
       [0.641733  ],
       [0.6445834 ],
       [0.64266455],
       [0.6461688 ],
       [0.6689728 ],
       [0.6637034 ],
       [0.6704805 ],
       [0.68092763],
       [0.69543546],
       [0.70393616],
       [0.70344675],
       [0.6976642 ],
       [0.6938074 ],
       [0.69045824],
       [0.7080088 ],
       [0.726191  ],
       [0.7257376 ],
       [0.7220041 ],
       [0.7175697 ],
       [0.71028394],
       [0.70741385],
       [0.71635526],
       [0.7160127 ],
       [0.7157598 ],
       [0.7140141 ],
       [0.72547024],
       [0.7342286 ],
       [0.73902947],
       [0.74288803],
       [0.74878484],
       [0.74609464],
       [0.75058025],
       [0.74634296],
       [0.74675745],
       [0.74948454],
       [0.75796586],
       [0.7628189 ],
       [0.76542026],
       [0.7619342 ],
       [0.7541644 ],
       [0.7507953 ],
       [0.7449289 ],
       [0.7418949 ],
       [0.74157304],
       [0.7440344 ],
       [0.7354166 ],
       [0.7253004 ],
       [0.710685  ],
       [0.69063   ],
       [0.6873086 ],
       [0.6905281 ],
       [0.6916904 ],
       [0.6862344 ],
       [0.67030114],
       [0.6600771 ],
       [0.64313334],
       [0.62871414],
       [0.61286676],
       [0.59891945],
       [0.61037344],
       [0.6288511 ],
       [0.6401069 ],
       [0.6202525 ],
       [0.5965788 ],
       [0.5694689 ],
       [0.5664696 ],
       [0.57460004],
       [0.58288896],
       [0.5828999 ],
       [0.5687918 ],
       [0.54989403],
       [0.5480196 ],
       [0.54879236],
       [0.5315979 ],
       [0.526133  ],
       [0.5207431 ],
       [0.50934976],
       [0.504342  ],
       [0.49918085],
       [0.50800604],
       [0.527227  ],
       [0.53983235],
       [0.55193675],
       [0.54574317],
       [0.53945994],
       [0.5310646 ],
       [0.5480446 ],
       [0.56888294],
       [0.569479  ],
       [0.572169  ],
       [0.57412595],
       [0.5692696 ]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
14964     28649.0  27185.207433  28570.205916           NaN
14965     28760.0  27412.001868  28087.903653           NaN
14966     28829.0  27287.213123  28487.044034           NaN
14967     25813.0  27286.866434  28368.003603           NaN
14968     25715.0  25854.662495      25979.49           NaN
...           ...           ...           ...           ...
18280     25562.0  26531.749471  26013.520588  17066.488281
18281     25386.0  26682.293871   26161.99488  17084.369141
18282     22872.0  23121.786144  22550.322475  17165.070312
18283     15825.0  14935.714871  16669.129145  17223.779297
18284      1450.0   1709.206578   1857.219074  17078.087891

[518 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 72s 4s/step - loss: 0.5277 - mean_absolute_error: 0.6353 - mean_absolute_percentage_error: 1164696.1250 - root_mean_squared_error: 0.7264 - val_loss: 0.3474 - val_mean_absolute_error: 0.5249 - val_mean_absolute_percentage_error: 9804954.0000 - val_root_mean_squared_error: 0.5894
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 18s 3s/step - loss: 0.3916 - mean_absolute_error: 0.5519 - mean_absolute_percentage_error: 11790484.0000 - root_mean_squared_error: 0.6253 - val_loss: 0.1535 - val_mean_absolute_error: 0.3634 - val_mean_absolute_percentage_error: 35614028.0000 - val_root_mean_squared_error: 0.3918
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step - loss: 0.1754 - mean_absolute_error: 0.3769 - mean_absolute_percentage_error: 36111816.0000 - root_mean_squared_error: 0.4185 - val_loss: 0.1772 - val_mean_absolute_error: 0.2947 - val_mean_absolute_percentage_error: 85370072.0000 - val_root_mean_squared_error: 0.4209
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 22s 4s/step - loss: 0.1873 - mean_absolute_error: 0.3087 - mean_absolute_percentage_error: 70933008.0000 - root_mean_squared_error: 0.4327 - val_loss: 0.1176 - val_mean_absolute_error: 0.2507 - val_mean_absolute_percentage_error: 71425232.0000 - val_root_mean_squared_error: 0.3430
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 22s 6s/step - loss: 0.1351 - mean_absolute_error: 0.3089 - mean_absolute_percentage_error: 53204660.0000 - root_mean_squared_error: 0.3676 - val_loss: 0.1032 - val_mean_absolute_error: 0.2791 - val_mean_absolute_percentage_error: 52045320.0000 - val_root_mean_squared_error: 0.3213
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 15s 3s/step - loss: 0.1445 - mean_absolute_error: 0.3509 - mean_absolute_percentage_error: 41243488.0000 - root_mean_squared_error: 0.3801 - val_loss: 0.1037 - val_mean_absolute_error: 0.2805 - val_mean_absolute_percentage_error: 51730520.0000 - val_root_mean_squared_error: 0.3220
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 22s 3s/step - loss: 0.1452 - mean_absolute_error: 0.3508 - mean_absolute_percentage_error: 45921684.0000 - root_mean_squared_error: 0.3810 - val_loss: 0.0999 - val_mean_absolute_error: 0.2525 - val_mean_absolute_percentage_error: 60932024.0000 - val_root_mean_squared_error: 0.3161
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 24s 4s/step - loss: 0.1324 - mean_absolute_error: 0.3169 - mean_absolute_percentage_error: 52543896.0000 - root_mean_squared_error: 0.3639 - val_loss: 0.1116 - val_mean_absolute_error: 0.2478 - val_mean_absolute_percentage_error: 69092232.0000 - val_root_mean_squared_error: 0.3341
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 20s 5s/step - loss: 0.1362 - mean_absolute_error: 0.3039 - mean_absolute_percentage_error: 53377884.0000 - root_mean_squared_error: 0.3691 - val_loss: 0.1075 - val_mean_absolute_error: 0.2468 - val_mean_absolute_percentage_error: 67121456.0000 - val_root_mean_squared_error: 0.3278
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step - loss: 0.1293 - mean_absolute_error: 0.3038 - mean_absolute_percentage_error: 52195828.0000 - root_mean_squared_error: 0.3595 - val_loss: 0.0996 - val_mean_absolute_error: 0.2521 - val_mean_absolute_percentage_error: 60895020.0000 - val_root_mean_squared_error: 0.3156
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 20s 4s/step - loss: 0.1310 - mean_absolute_error: 0.3228 - mean_absolute_percentage_error: 51058808.0000 - root_mean_squared_error: 0.3619 - val_loss: 0.0983 - val_mean_absolute_error: 0.2578 - val_mean_absolute_percentage_error: 57939876.0000 - val_root_mean_squared_error: 0.3135
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.1274 - mean_absolute_error: 0.3209 - mean_absolute_percentage_error: 49257420.0000 - root_mean_squared_error: 0.3569 - val_loss: 0.1005 - val_mean_absolute_error: 0.2476 - val_mean_absolute_percentage_error: 62907436.0000 - val_root_mean_squared_error: 0.3171
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.1236 - mean_absolute_error: 0.3016 - mean_absolute_percentage_error: 54229228.0000 - root_mean_squared_error: 0.3516 - val_loss: 0.1082 - val_mean_absolute_error: 0.2454 - val_mean_absolute_percentage_error: 67719160.0000 - val_root_mean_squared_error: 0.3290
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 15s 4s/step - loss: 0.1289 - mean_absolute_error: 0.2941 - mean_absolute_percentage_error: 59403384.0000 - root_mean_squared_error: 0.3590 - val_loss: 0.1049 - val_mean_absolute_error: 0.2450 - val_mean_absolute_percentage_error: 66077944.0000 - val_root_mean_squared_error: 0.3239
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - loss: 0.1224 - mean_absolute_error: 0.2940 - mean_absolute_percentage_error: 54097596.0000 - root_mean_squared_error: 0.3498 - val_loss: 0.0983 - val_mean_absolute_error: 0.2474 - val_mean_absolute_percentage_error: 61537012.0000 - val_root_mean_squared_error: 0.3135
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 18s 4s/step - loss: 0.1177 - mean_absolute_error: 0.2923 - mean_absolute_percentage_error: 49507856.0000 - root_mean_squared_error: 0.3431 - val_loss: 0.0970 - val_mean_absolute_error: 0.2517 - val_mean_absolute_percentage_error: 59093140.0000 - val_root_mean_squared_error: 0.3115
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 31s 6s/step - loss: 0.1149 - mean_absolute_error: 0.2824 - mean_absolute_percentage_error: 53910484.0000 - root_mean_squared_error: 0.3389 - val_loss: 0.1028 - val_mean_absolute_error: 0.2689 - val_mean_absolute_percentage_error: 56522972.0000 - val_root_mean_squared_error: 0.3206
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 43s 7s/step - loss: 0.1112 - mean_absolute_error: 0.2653 - mean_absolute_percentage_error: 52704800.0000 - root_mean_squared_error: 0.3334 - val_loss: 0.1055 - val_mean_absolute_error: 0.2689 - val_mean_absolute_percentage_error: 56475708.0000 - val_root_mean_squared_error: 0.3248
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 39s 5s/step - loss: 0.1088 - mean_absolute_error: 0.2575 - mean_absolute_percentage_error: 51578284.0000 - root_mean_squared_error: 0.3298 - val_loss: 0.1037 - val_mean_absolute_error: 0.2754 - val_mean_absolute_percentage_error: 53129624.0000 - val_root_mean_squared_error: 0.3220
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 19s 4s/step - loss: 0.1105 - mean_absolute_error: 0.2628 - mean_absolute_percentage_error: 50554316.0000 - root_mean_squared_error: 0.3324 - val_loss: 0.0956 - val_mean_absolute_error: 0.2454 - val_mean_absolute_percentage_error: 59399880.0000 - val_root_mean_squared_error: 0.3091
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 27s 6s/step - loss: 0.1109 - mean_absolute_error: 0.2672 - mean_absolute_percentage_error: 54022128.0000 - root_mean_squared_error: 0.3330 - val_loss: 0.0946 - val_mean_absolute_error: 0.2566 - val_mean_absolute_percentage_error: 55377796.0000 - val_root_mean_squared_error: 0.3076
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 18s 3s/step - loss: 0.1055 - mean_absolute_error: 0.2594 - mean_absolute_percentage_error: 49407240.0000 - root_mean_squared_error: 0.3248 - val_loss: 0.0945 - val_mean_absolute_error: 0.2541 - val_mean_absolute_percentage_error: 55453312.0000 - val_root_mean_squared_error: 0.3075
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 30s 5s/step - loss: 0.1086 - mean_absolute_error: 0.2673 - mean_absolute_percentage_error: 51920424.0000 - root_mean_squared_error: 0.3295 - val_loss: 0.0945 - val_mean_absolute_error: 0.2500 - val_mean_absolute_percentage_error: 56177860.0000 - val_root_mean_squared_error: 0.3073
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 48s 7s/step - loss: 0.1063 - mean_absolute_error: 0.2460 - mean_absolute_percentage_error: 53867640.0000 - root_mean_squared_error: 0.3261 - val_loss: 0.0978 - val_mean_absolute_error: 0.2718 - val_mean_absolute_percentage_error: 49784692.0000 - val_root_mean_squared_error: 0.3127
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 42s 5s/step - loss: 0.1035 - mean_absolute_error: 0.2605 - mean_absolute_percentage_error: 45939772.0000 - root_mean_squared_error: 0.3217 - val_loss: 0.0935 - val_mean_absolute_error: 0.2520 - val_mean_absolute_percentage_error: 55061672.0000 - val_root_mean_squared_error: 0.3058
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 42s 5s/step - loss: 0.1072 - mean_absolute_error: 0.2517 - mean_absolute_percentage_error: 51876356.0000 - root_mean_squared_error: 0.3274 - val_loss: 0.0970 - val_mean_absolute_error: 0.2698 - val_mean_absolute_percentage_error: 49216288.0000 - val_root_mean_squared_error: 0.3114
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 36s 9s/step - loss: 0.1072 - mean_absolute_error: 0.2631 - mean_absolute_percentage_error: 51061396.0000 - root_mean_squared_error: 0.3274 - val_loss: 0.0941 - val_mean_absolute_error: 0.2574 - val_mean_absolute_percentage_error: 51496428.0000 - val_root_mean_squared_error: 0.3067
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 39s 8s/step - loss: 0.1008 - mean_absolute_error: 0.2442 - mean_absolute_percentage_error: 45884888.0000 - root_mean_squared_error: 0.3175 - val_loss: 0.1000 - val_mean_absolute_error: 0.2772 - val_mean_absolute_percentage_error: 45486176.0000 - val_root_mean_squared_error: 0.3162
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 26s 6s/step - loss: 0.1021 - mean_absolute_error: 0.2553 - mean_absolute_percentage_error: 46969180.0000 - root_mean_squared_error: 0.3195 - val_loss: 0.0913 - val_mean_absolute_error: 0.2480 - val_mean_absolute_percentage_error: 52392292.0000 - val_root_mean_squared_error: 0.3022
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 46s 7s/step - loss: 0.0968 - mean_absolute_error: 0.2388 - mean_absolute_percentage_error: 48717068.0000 - root_mean_squared_error: 0.3110 - val_loss: 0.0986 - val_mean_absolute_error: 0.2749 - val_mean_absolute_percentage_error: 43139784.0000 - val_root_mean_squared_error: 0.3139
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 38s 6s/step - loss: 0.1010 - mean_absolute_error: 0.2511 - mean_absolute_percentage_error: 48887480.0000 - root_mean_squared_error: 0.3178 - val_loss: 0.0936 - val_mean_absolute_error: 0.2579 - val_mean_absolute_percentage_error: 44147536.0000 - val_root_mean_squared_error: 0.3060
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 51s 7s/step - loss: 0.0954 - mean_absolute_error: 0.2387 - mean_absolute_percentage_error: 45395596.0000 - root_mean_squared_error: 0.3088 - val_loss: 0.0953 - val_mean_absolute_error: 0.2645 - val_mean_absolute_percentage_error: 38902460.0000 - val_root_mean_squared_error: 0.3088
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 42s 6s/step - loss: 0.0869 - mean_absolute_error: 0.2300 - mean_absolute_percentage_error: 42877068.0000 - root_mean_squared_error: 0.2948 - val_loss: 0.0799 - val_mean_absolute_error: 0.2363 - val_mean_absolute_percentage_error: 38086428.0000 - val_root_mean_squared_error: 0.2827
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 43s 6s/step - loss: 0.0784 - mean_absolute_error: 0.2156 - mean_absolute_percentage_error: 41157544.0000 - root_mean_squared_error: 0.2800 - val_loss: 0.0646 - val_mean_absolute_error: 0.1861 - val_mean_absolute_percentage_error: 42812916.0000 - val_root_mean_squared_error: 0.2542
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 47s 6s/step - loss: 0.0767 - mean_absolute_error: 0.2006 - mean_absolute_percentage_error: 43671820.0000 - root_mean_squared_error: 0.2767 - val_loss: 0.0770 - val_mean_absolute_error: 0.2315 - val_mean_absolute_percentage_error: 24816530.0000 - val_root_mean_squared_error: 0.2776
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 46s 7s/step - loss: 0.0662 - mean_absolute_error: 0.1976 - mean_absolute_percentage_error: 29707722.0000 - root_mean_squared_error: 0.2574 - val_loss: 0.0499 - val_mean_absolute_error: 0.1577 - val_mean_absolute_percentage_error: 36346896.0000 - val_root_mean_squared_error: 0.2234
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 22s 6s/step - loss: 0.0550 - mean_absolute_error: 0.1738 - mean_absolute_percentage_error: 27752110.0000 - root_mean_squared_error: 0.2344 - val_loss: 0.0519 - val_mean_absolute_error: 0.1709 - val_mean_absolute_percentage_error: 24106324.0000 - val_root_mean_squared_error: 0.2279
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 47s 7s/step - loss: 0.0591 - mean_absolute_error: 0.1773 - mean_absolute_percentage_error: 25331790.0000 - root_mean_squared_error: 0.2431 - val_loss: 0.0481 - val_mean_absolute_error: 0.1510 - val_mean_absolute_percentage_error: 35190004.0000 - val_root_mean_squared_error: 0.2192
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 49s 9s/step - loss: 0.0551 - mean_absolute_error: 0.1679 - mean_absolute_percentage_error: 26754632.0000 - root_mean_squared_error: 0.2348 - val_loss: 0.0463 - val_mean_absolute_error: 0.1622 - val_mean_absolute_percentage_error: 29762798.0000 - val_root_mean_squared_error: 0.2152
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 41s 7s/step - loss: 0.0519 - mean_absolute_error: 0.1659 - mean_absolute_percentage_error: 25922848.0000 - root_mean_squared_error: 0.2278 - val_loss: 0.0449 - val_mean_absolute_error: 0.1518 - val_mean_absolute_percentage_error: 32812306.0000 - val_root_mean_squared_error: 0.2118
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 43s 7s/step - loss: 0.0506 - mean_absolute_error: 0.1629 - mean_absolute_percentage_error: 27109338.0000 - root_mean_squared_error: 0.2250 - val_loss: 0.0460 - val_mean_absolute_error: 0.1647 - val_mean_absolute_percentage_error: 26855104.0000 - val_root_mean_squared_error: 0.2145
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 37s 5s/step - loss: 0.0511 - mean_absolute_error: 0.1641 - mean_absolute_percentage_error: 24256176.0000 - root_mean_squared_error: 0.2261 - val_loss: 0.0456 - val_mean_absolute_error: 0.1472 - val_mean_absolute_percentage_error: 35740280.0000 - val_root_mean_squared_error: 0.2136
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 35s 9s/step - loss: 0.0514 - mean_absolute_error: 0.1626 - mean_absolute_percentage_error: 27807104.0000 - root_mean_squared_error: 0.2266 - val_loss: 0.0461 - val_mean_absolute_error: 0.1580 - val_mean_absolute_percentage_error: 29366654.0000 - val_root_mean_squared_error: 0.2146
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 39s 7s/step - loss: 0.0492 - mean_absolute_error: 0.1594 - mean_absolute_percentage_error: 25250968.0000 - root_mean_squared_error: 0.2218 - val_loss: 0.0427 - val_mean_absolute_error: 0.1435 - val_mean_absolute_percentage_error: 31595450.0000 - val_root_mean_squared_error: 0.2065
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 36s 9s/step - loss: 0.0483 - mean_absolute_error: 0.1582 - mean_absolute_percentage_error: 25693162.0000 - root_mean_squared_error: 0.2197 - val_loss: 0.0426 - val_mean_absolute_error: 0.1496 - val_mean_absolute_percentage_error: 25636822.0000 - val_root_mean_squared_error: 0.2064
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 27s 6s/step - loss: 0.0474 - mean_absolute_error: 0.1558 - mean_absolute_percentage_error: 22343064.0000 - root_mean_squared_error: 0.2177 - val_loss: 0.0414 - val_mean_absolute_error: 0.1429 - val_mean_absolute_percentage_error: 30007424.0000 - val_root_mean_squared_error: 0.2034
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 29s 6s/step - loss: 0.0473 - mean_absolute_error: 0.1534 - mean_absolute_percentage_error: 25082384.0000 - root_mean_squared_error: 0.2176 - val_loss: 0.0437 - val_mean_absolute_error: 0.1483 - val_mean_absolute_percentage_error: 28633326.0000 - val_root_mean_squared_error: 0.2092
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 45s 6s/step - loss: 0.0469 - mean_absolute_error: 0.1532 - mean_absolute_percentage_error: 24544126.0000 - root_mean_squared_error: 0.2165 - val_loss: 0.0424 - val_mean_absolute_error: 0.1426 - val_mean_absolute_percentage_error: 27504498.0000 - val_root_mean_squared_error: 0.2059
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 46s 6s/step - loss: 0.0449 - mean_absolute_error: 0.1495 - mean_absolute_percentage_error: 23848160.0000 - root_mean_squared_error: 0.2118 - val_loss: 0.0432 - val_mean_absolute_error: 0.1500 - val_mean_absolute_percentage_error: 25234950.0000 - val_root_mean_squared_error: 0.2079
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 46s 6s/step - loss: 0.0463 - mean_absolute_error: 0.1531 - mean_absolute_percentage_error: 24601862.0000 - root_mean_squared_error: 0.2151 - val_loss: 0.0419 - val_mean_absolute_error: 0.1399 - val_mean_absolute_percentage_error: 28857286.0000 - val_root_mean_squared_error: 0.2048

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

15/15 ━━━━━━━━━━━━━━━━━━━━ 23s 757ms/step

array([[0.65497905],
       [0.88238037],
       [0.8850447 ],
       [0.8785308 ],
       [0.8704098 ],
       [0.82187617],
       [0.18902595],
       [0.1789166 ],
       [0.53652114],
       [0.87205106],
       [0.9095257 ],
       [0.9113905 ],
       [0.8983334 ],
       [0.8900463 ],
       [0.85778636],
       [0.17602475],
       [0.35612938],
       [0.87855446],
       [0.8983943 ],
       [0.8976761 ],
       [0.8910093 ],
       [0.8879427 ],
       [0.87108535],
       [0.22102083],
       [0.64406234],
       [0.89495546],
       [0.89144117],
       [0.878815  ],
       [0.21772534],
       [0.7048357 ],
       [0.92202634],
       [0.9162462 ],
       [0.8916416 ],
       [0.85927767],
       [0.21677236],
       [0.21813507],
       [0.51766574],
       [0.8932926 ],
       [0.9005584 ],
       [0.9029886 ],
       [0.8976671 ],
       [0.8823766 ],
       [0.8185838 ],
       [0.37822372],
       [0.20419495],
       [0.20817235],
       [0.90178555],
       [0.9273133 ],
       [0.9203438 ],
       [0.9055442 ],
       [0.8949532 ],
       [0.88462466],
       [0.85327333],
       [0.6588513 ],
       [0.20624113],
       [0.2702156 ],
       [0.4486254 ],
       [0.9185565 ],
       [0.93240416],
       [0.92315805],
       [0.90547675],
       [0.89069396],
       [0.863745  ],
       [0.36802226],
       [0.18107033],
       [0.17954652],
       [0.5762173 ],
       [0.908066  ],
       [0.9271694 ],
       [0.9205584 ],
       [0.89963627],
       [0.8852369 ],
       [0.86633676],
       [0.22883427],
       [0.663464  ],
       [0.9011377 ],
       [0.9098818 ],
       [0.906208  ],
       [0.9000688 ],
       [0.87543106],
       [0.17743506],
       [0.17723885],
       [0.3688901 ],
       [0.8911797 ],
       [0.9008068 ],
       [0.87939954],
       [0.8614986 ],
       [0.86336493],
       [0.47050014],
       [0.9082317 ],
       [0.9097153 ],
       [0.9049521 ],
       [0.895491  ],
       [0.33448768],
       [0.9116642 ],
       [0.92121714],
       [0.91018504],
       [0.896694  ],
       [0.88127357],
       [0.25274566],
       [0.6110335 ],
       [0.9035196 ],
       [0.9131826 ],
       [0.9217356 ],
       [0.9200867 ],
       [0.9082946 ],
       [0.8821256 ],
       [0.9139953 ],
       [0.91047484],
       [0.89945126],
       [0.8918696 ],
       [0.890431  ],
       [0.89661425],
       [0.40874135],
       [0.30198827],
       [0.31876534],
       [0.9225047 ],
       [0.9365577 ],
       [0.93113416],
       [0.91333705],
       [0.89583844],
       [0.8286466 ],
       [0.83649784],
       [0.6340126 ],
       [0.24860641],
       [0.22603332],
       [0.22895361],
       [0.5712222 ],
       [0.92649525],
       [0.94338685],
       [0.9340692 ],
       [0.9269345 ],
       [0.9040858 ],
       [0.85472184],
       [0.35445964],
       [0.2607193 ],
       [0.23920693],
       [0.29748115],
       [0.6900812 ],
       [0.9296654 ],
       [0.9452405 ],
       [0.93745893],
       [0.9220567 ],
       [0.92697597],
       [0.91846126],
       [0.9078367 ],
       [0.91304487],
       [0.91677946],
       [0.92118347],
       [0.9280804 ],
       [0.9253321 ],
       [0.9008427 ],
       [0.84343237],
       [0.6579328 ],
       [0.9355596 ],
       [0.9335882 ],
       [0.92689687],
       [0.91282123],
       [0.8965679 ],
       [0.8723934 ],
       [0.82154125],
       [0.23088251],
       [0.19673796],
       [0.93715084],
       [0.9367377 ],
       [0.93138474],
       [0.9283466 ],
       [0.9178613 ],
       [0.89101833],
       [0.77059966],
       [0.41406125],
       [0.33248013],
       [0.91789263],
       [0.9311393 ],
       [0.93436533],
       [0.93546945],
       [0.9208339 ],
       [0.89566016],
       [0.81500757],
       [0.28112966],
       [0.17094025],
       [0.92658275],
       [0.9197955 ],
       [0.8779773 ],
       [0.9310141 ],
       [0.9345569 ],
       [0.90770113],
       [0.7366889 ],
       [0.23947304],
       [0.16312382],
       [0.21512273],
       [0.868107  ],
       [0.93835634],
       [0.94287395],
       [0.9397369 ],
       [0.93063235],
       [0.91100734],
       [0.8670915 ],
       [0.7324518 ],
       [0.2877009 ],
       [0.15577284],
       [0.17996092],
       [0.7260885 ],
       [0.93262404],
       [0.9335751 ],
       [0.92586535],
       [0.9129498 ],
       [0.89499325],
       [0.8394982 ],
       [0.6792329 ],
       [0.27093467],
       [0.14258975],
       [0.14346664],
       [0.54208493],
       [0.92405653],
       [0.92452306],
       [0.9119594 ],
       [0.89214593],
       [0.85997707],
       [0.15282837],
       [0.14767084],
       [0.47777325],
       [0.87974805],
       [0.9001737 ],
       [0.8971941 ],
       [0.8840013 ],
       [0.9302393 ],
       [0.92310816],
       [0.91061634],
       [0.89628154],
       [0.8611749 ],
       [0.79342693],
       [0.55520236],
       [0.9095798 ],
       [0.9053691 ],
       [0.9129961 ],
       [0.91219026],
       [0.8471975 ],
       [0.3538295 ],
       [0.29367346],
       [0.60242397],
       [0.33160007],
       [0.26159623],
       [0.2818219 ],
       [0.16490771],
       [0.15581112],
       [0.19681819],
       [0.9076481 ],
       [0.9096325 ],
       [0.91350263],
       [0.9137992 ],
       [0.90376365],
       [0.7411664 ],
       [0.26201606],
       [0.1528042 ],
       [0.8654509 ],
       [0.863511  ],
       [0.83549565],
       [0.7365473 ],
       [0.5114867 ],
       [0.88593835],
       [0.85857576],
       [0.5396151 ],
       [0.89100635],
       [0.87600404],
       [0.8758515 ],
       [0.8782597 ],
       [0.84296024],
       [0.6372255 ],
       [0.44214076],
       [0.8941575 ],
       [0.84859806],
       [0.7713816 ],
       [0.29993445],
       [0.6390885 ],
       [0.8974413 ],
       [0.88754195],
       [0.8812225 ],
       [0.8656494 ],
       [0.7266934 ],
       [0.6092714 ],
       [0.4997115 ],
       [0.8760228 ],
       [0.8732175 ],
       [0.8683209 ],
       [0.8556215 ],
       [0.7929486 ],
       [0.67871386],
       [0.5082181 ],
       [0.8973309 ],
       [0.8938825 ],
       [0.89224523],
       [0.89312243],
       [0.88111   ],
       [0.829956  ],
       [0.62696296],
       [0.29028505],
       [0.13084422],
       [0.33654773],
       [0.90146095],
       [0.90487397],
       [0.9030863 ],
       [0.8958211 ],
       [0.8654013 ],
       [0.7787158 ],
       [0.4766901 ],
       [0.6413173 ],
       [0.90341413],
       [0.90737647],
       [0.90723044],
       [0.9013415 ],
       [0.86649185],
       [0.6770384 ],
       [0.42755306],
       [0.26369375],
       [0.9145995 ],
       [0.91033524],
       [0.89728826],
       [0.8732651 ],
       [0.8195043 ],
       [0.6093525 ],
       [0.92938334],
       [0.92686826],
       [0.9177637 ],
       [0.7441283 ],
       [0.6514832 ],
       [0.14025147],
       [0.928575  ],
       [0.9255262 ],
       [0.91930366],
       [0.90896183],
       [0.85567087],
       [0.7442973 ],
       [0.45897418],
       [0.16585198],
       [0.8756159 ],
       [0.79061174],
       [0.8368596 ],
       [0.71758705],
       [0.41756177],
       [0.90639186],
       [0.87161386],
       [0.845703  ],
       [0.7044416 ],
       [0.29359633],
       [0.34862685],
       [0.91545427],
       [0.9150538 ],
       [0.91018414],
       [0.8940031 ],
       [0.79386467],
       [0.76451105],
       [0.9153299 ],
       [0.88589925],
       [0.840266  ],
       [0.7980564 ],
       [0.87670594],
       [0.8590242 ],
       [0.8357087 ],
       [0.3426203 ],
       [0.8600244 ],
       [0.8309217 ],
       [0.75226074],
       [0.46908695],
       [0.3116687 ],
       [0.81807256],
       [0.7174085 ],
       [0.39352915],
       [0.23790145],
       [0.9059941 ],
       [0.90022063],
       [0.89308673],
       [0.88702816],
       [0.82251096],
       [0.67402273],
       [0.90612215],
       [0.9055471 ],
       [0.9020471 ],
       [0.89763045],
       [0.89290744],
       [0.8695358 ],
       [0.7343271 ],
       [0.91409755],
       [0.9154004 ],
       [0.9176073 ],
       [0.9174401 ],
       [0.91294396],
       [0.9057191 ],
       [0.8825324 ],
       [0.7686145 ],
       [0.52912164],
       [0.6995247 ],
       [0.9282195 ],
       [0.9268854 ],
       [0.9224401 ],
       [0.90999895],
       [0.87763166],
       [0.81532663],
       [0.64945287],
       [0.90262973],
       [0.8890602 ],
       [0.8751574 ],
       [0.8353216 ],
       [0.92252606],
       [0.91966486],
       [0.9150987 ],
       [0.9039475 ],
       [0.8798123 ],
       [0.8044563 ],
       [0.91393244],
       [0.70224863],
       [0.5927983 ],
       [0.59287125],
       [0.92083365],
       [0.9244841 ],
       [0.880746  ],
       [0.82314914],
       [0.68643814],
       [0.9020663 ],
       [0.873529  ],
       [0.80132836],
       [0.77228814],
       [0.9177771 ],
       [0.8913344 ],
       [0.8188104 ],
       [0.78986233],
       [0.77714187],
       [0.90744346],
       [0.86377084],
       [0.81401956],
       [0.7371184 ],
       [0.63680357],
       [0.9010846 ],
       [0.86079663],
       [0.73115623],
       [0.65499765],
       [0.433656  ],
       [0.9048168 ],
       [0.90348333],
       [0.8778582 ],
       [0.8336876 ],
       [0.44249117],
       [0.26586914],
       [0.89944786],
       [0.88847214],
       [0.86052614],
       [0.80074173],
       [0.51525754],
       [0.23524551],
       [0.80159616],
       [0.753964  ],
       [0.5688806 ],
       [0.8415403 ],
       [0.8258094 ],
       [0.74739593],
       [0.48005348],
       [0.24119225],
       [0.8607351 ],
       [0.86622626],
       [0.84831494],
       [0.8106454 ],
       [0.71411175],
       [0.48187333],
       [0.18786322],
       [0.88207346],
       [0.86643505],
       [0.8247959 ],
       [0.77335864],
       [0.47817072],
       [0.15913762]], dtype=float32)

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
14964     28649.0  27185.207433  28570.205916           NaN
14965     28760.0  27412.001868  28087.903653           NaN
14966     28829.0  27287.213123  28487.044034           NaN
14967     25813.0  27286.866434  28368.003603           NaN
14968     25715.0  25854.662495      25979.49           NaN
...           ...           ...           ...           ...
18280     25562.0  26531.749471  26013.520588  25993.050781
18281     25386.0  26682.293871   26161.99488  24743.876953
18282     22872.0  23121.786144  22550.322475  23200.759766
18283     15825.0  14935.714871  16669.129145  14345.122070
18284      1450.0   1709.206578   1857.219074   4774.128418

[518 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,985 (1.55 MB)

 Trainable params: 405,729 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100

296/296 ━━━━━━━━━━━━━━━━━━━━ 335s 368ms/step - loss: 0.2016 - mae: 0.5333 - val_loss: 0.2066 - val_mae: 0.5816
Epoch 2/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 115s 367ms/step - loss: 0.1407 - mae: 0.4360 - val_loss: 0.0898 - val_mae: 0.3470
Epoch 3/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 143s 362ms/step - loss: 0.1054 - mae: 0.3690 - val_loss: 0.0950 - val_mae: 0.3514
Epoch 4/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 132s 316ms/step - loss: 0.0955 - mae: 0.3496 - val_loss: 0.0624 - val_mae: 0.2526
Epoch 5/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 144s 311ms/step - loss: 0.0858 - mae: 0.3325 - val_loss: 0.0542 - val_mae: 0.2401
Epoch 6/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 144s 306ms/step - loss: 0.0831 - mae: 0.3236 - val_loss: 0.0463 - val_mae: 0.2290
Epoch 7/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 184s 433ms/step - loss: 0.0795 - mae: 0.3147 - val_loss: 0.0418 - val_mae: 0.2132
Epoch 8/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 132s 385ms/step - loss: 0.0709 - mae: 0.2955 - val_loss: 0.0416 - val_mae: 0.2209
Epoch 9/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 156s 415ms/step - loss: 0.0657 - mae: 0.2837 - val_loss: 0.0556 - val_mae: 0.2523
Epoch 10/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 121s 333ms/step - loss: 0.0645 - mae: 0.2774 - val_loss: 0.0452 - val_mae: 0.2091
Epoch 11/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 155s 364ms/step - loss: 0.0711 - mae: 0.2868 - val_loss: 0.0447 - val_mae: 0.2155
Epoch 12/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 148s 364ms/step - loss: 0.0608 - mae: 0.2662 - val_loss: 0.0376 - val_mae: 0.1855
Epoch 13/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 163s 423ms/step - loss: 0.0664 - mae: 0.2808 - val_loss: 0.0427 - val_mae: 0.1978
Epoch 14/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 146s 421ms/step - loss: 0.0628 - mae: 0.2669 - val_loss: 0.0323 - val_mae: 0.1717
Epoch 15/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 130s 409ms/step - loss: 0.0561 - mae: 0.2586 - val_loss: 0.0365 - val_mae: 0.1830
Epoch 16/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 165s 476ms/step - loss: 0.0584 - mae: 0.2565 - val_loss: 0.0337 - val_mae: 0.1786
Epoch 17/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 126s 406ms/step - loss: 0.0607 - mae: 0.2627 - val_loss: 0.0299 - val_mae: 0.1663
Epoch 18/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 148s 412ms/step - loss: 0.0511 - mae: 0.2428 - val_loss: 0.0310 - val_mae: 0.1589
Epoch 19/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 137s 383ms/step - loss: 0.0545 - mae: 0.2460 - val_loss: 0.0290 - val_mae: 0.1619
Epoch 20/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 154s 411ms/step - loss: 0.0505 - mae: 0.2373 - val_loss: 0.0310 - val_mae: 0.1538
Epoch 21/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 150s 418ms/step - loss: 0.0489 - mae: 0.2326 - val_loss: 0.0299 - val_mae: 0.1632
Epoch 22/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 129s 420ms/step - loss: 0.0444 - mae: 0.2215 - val_loss: 0.0300 - val_mae: 0.1567
Epoch 23/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 152s 436ms/step - loss: 0.0424 - mae: 0.2117 - val_loss: 0.0315 - val_mae: 0.1570
Epoch 24/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 136s 401ms/step - loss: 0.0442 - mae: 0.2218 - val_loss: 0.0289 - val_mae: 0.1492
Epoch 25/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 152s 489ms/step - loss: 0.0452 - mae: 0.2199 - val_loss: 0.0286 - val_mae: 0.1523
Epoch 26/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 192s 442ms/step - loss: 0.0418 - mae: 0.2112 - val_loss: 0.0311 - val_mae: 0.1502
Epoch 27/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 132s 390ms/step - loss: 0.0461 - mae: 0.2203 - val_loss: 0.0282 - val_mae: 0.1441
Epoch 28/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 91s 293ms/step - loss: 0.0400 - mae: 0.2063 - val_loss: 0.0296 - val_mae: 0.1510
Epoch 29/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 188s 431ms/step - loss: 0.0402 - mae: 0.2043 - val_loss: 0.0296 - val_mae: 0.1500
Epoch 30/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 162s 479ms/step - loss: 0.0365 - mae: 0.1968 - val_loss: 0.0264 - val_mae: 0.1465
Epoch 31/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 175s 564ms/step - loss: 0.0401 - mae: 0.2043 - val_loss: 0.0279 - val_mae: 0.1461
Epoch 32/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 134s 434ms/step - loss: 0.0387 - mae: 0.2030 - val_loss: 0.0316 - val_mae: 0.1588
Epoch 33/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 172s 517ms/step - loss: 0.0397 - mae: 0.2026 - val_loss: 0.0273 - val_mae: 0.1429
Epoch 34/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 215s 538ms/step - loss: 0.0342 - mae: 0.1878 - val_loss: 0.0275 - val_mae: 0.1436
Epoch 35/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 204s 525ms/step - loss: 0.0324 - mae: 0.1837 - val_loss: 0.0278 - val_mae: 0.1517
Epoch 36/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 151s 490ms/step - loss: 0.0357 - mae: 0.1943 - val_loss: 0.0290 - val_mae: 0.1582
Epoch 37/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 216s 517ms/step - loss: 0.0355 - mae: 0.1925 - val_loss: 0.0290 - val_mae: 0.1536
Epoch 38/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 131s 426ms/step - loss: 0.0352 - mae: 0.1886 - val_loss: 0.0288 - val_mae: 0.1590
Epoch 39/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 130s 413ms/step - loss: 0.0337 - mae: 0.1865 - val_loss: 0.0270 - val_mae: 0.1483
Epoch 40/100
296/296 ━━━━━━━━━━━━━━━━━━━━ 155s 447ms/step - loss: 0.0339 - mae: 0.1862 - val_loss: 0.0284 - val_mae: 0.1582

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

14/15 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

15/15 ━━━━━━━━━━━━━━━━━━━━ 79s 3s/step

array([[0.78187525],
       [0.85450816],
       [0.84117824],
       [0.8430827 ],
       [0.8088846 ],
       [0.78877974],
       [0.17309554],
       [0.15284581],
       [0.72884065],
       [0.85092837],
       [0.8398391 ],
       [0.8487372 ],
       [0.82202095],
       [0.8167394 ],
       [0.7797253 ],
       [0.        ],
       [0.7344668 ],
       [0.82965595],
       [0.83172745],
       [0.82951665],
       [0.8117194 ],
       [0.79736173],
       [0.7722986 ],
       [0.        ],
       [0.82628244],
       [0.82531345],
       [0.822931  ],
       [0.80492985],
       [0.35324183],
       [0.8495433 ],
       [0.84404427],
       [0.8214418 ],
       [0.81820446],
       [0.7749531 ],
       [0.32811058],
       [0.30248684],
       [0.74913025],
       [0.7777006 ],
       [0.77432567],
       [0.80689245],
       [0.7765493 ],
       [0.7603438 ],
       [0.6396581 ],
       [0.42623   ],
       [0.16389963],
       [0.01606916],
       [0.79341495],
       [0.8225659 ],
       [0.82748497],
       [0.8238777 ],
       [0.8123024 ],
       [0.8018614 ],
       [0.7110084 ],
       [0.5407098 ],
       [0.17196399],
       [0.17011224],
       [0.53578454],
       [0.84247226],
       [0.8368012 ],
       [0.83745235],
       [0.81601375],
       [0.80575883],
       [0.7868593 ],
       [0.35469896],
       [0.        ],
       [0.        ],
       [0.744554  ],
       [0.8417571 ],
       [0.8359384 ],
       [0.83665544],
       [0.8057969 ],
       [0.8163106 ],
       [0.79048854],
       [0.1743549 ],
       [0.80002993],
       [0.8389155 ],
       [0.8451659 ],
       [0.8302157 ],
       [0.82892674],
       [0.7965825 ],
       [0.        ],
       [0.        ],
       [0.6612925 ],
       [0.8461087 ],
       [0.8495552 ],
       [0.82949674],
       [0.8135904 ],
       [0.801903  ],
       [0.6029247 ],
       [0.8379955 ],
       [0.8615007 ],
       [0.85679626],
       [0.8501587 ],
       [0.6599635 ],
       [0.88981277],
       [0.86789465],
       [0.859934  ],
       [0.83279043],
       [0.8230405 ],
       [0.40232265],
       [0.79112995],
       [0.85486543],
       [0.86637664],
       [0.8624644 ],
       [0.8552055 ],
       [0.8417536 ],
       [0.8211234 ],
       [0.82433575],
       [0.88327247],
       [0.8633437 ],
       [0.8577926 ],
       [0.83001095],
       [0.82229155],
       [0.44223493],
       [0.09289921],
       [0.        ],
       [0.89636654],
       [0.8865068 ],
       [0.8951944 ],
       [0.86442953],
       [0.8659631 ],
       [0.80671614],
       [0.7585253 ],
       [0.6288396 ],
       [0.16428572],
       [0.        ],
       [0.        ],
       [0.64168   ],
       [0.8817821 ],
       [0.8938582 ],
       [0.88205737],
       [0.8558567 ],
       [0.85954607],
       [0.7794489 ],
       [0.575252  ],
       [0.23046134],
       [0.        ],
       [0.        ],
       [0.77073133],
       [0.8697396 ],
       [0.89398235],
       [0.8908863 ],
       [0.8865974 ],
       [0.8757946 ],
       [0.8897357 ],
       [0.8764316 ],
       [0.87877965],
       [0.8929969 ],
       [0.88821846],
       [0.8952718 ],
       [0.8795829 ],
       [0.84265727],
       [0.7550178 ],
       [0.63492215],
       [0.90462154],
       [0.89405507],
       [0.8974476 ],
       [0.8828029 ],
       [0.86983967],
       [0.80482054],
       [0.7122166 ],
       [0.37088788],
       [0.        ],
       [0.9107469 ],
       [0.8913593 ],
       [0.896729  ],
       [0.87925273],
       [0.868395  ],
       [0.81584907],
       [0.7030767 ],
       [0.54584116],
       [0.46096563],
       [0.879786  ],
       [0.8722731 ],
       [0.8798078 ],
       [0.8749544 ],
       [0.85331154],
       [0.80155563],
       [0.71212906],
       [0.5045151 ],
       [0.1986069 ],
       [0.86080027],
       [0.81747264],
       [0.8057967 ],
       [0.8141408 ],
       [0.83149034],
       [0.7526506 ],
       [0.4954518 ],
       [0.22340612],
       [0.        ],
       [0.        ],
       [0.8702198 ],
       [0.8367269 ],
       [0.82053906],
       [0.82060874],
       [0.8145328 ],
       [0.79780704],
       [0.7288912 ],
       [0.6122801 ],
       [0.18349724],
       [0.        ],
       [0.        ],
       [0.6731477 ],
       [0.80410457],
       [0.8072588 ],
       [0.80360323],
       [0.8196131 ],
       [0.80347526],
       [0.75626665],
       [0.5602988 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2931232 ],
       [0.812358  ],
       [0.8186699 ],
       [0.806514  ],
       [0.79885966],
       [0.7775479 ],
       [0.        ],
       [0.        ],
       [0.73223716],
       [0.84354776],
       [0.83144015],
       [0.82966113],
       [0.80605406],
       [0.8330056 ],
       [0.8470977 ],
       [0.84054106],
       [0.84651715],
       [0.8152338 ],
       [0.72993207],
       [0.61413777],
       [0.8455335 ],
       [0.8422562 ],
       [0.84638274],
       [0.839633  ],
       [0.7886787 ],
       [0.61388195],
       [0.4665175 ],
       [0.7458762 ],
       [0.6387976 ],
       [0.5637446 ],
       [0.40191412],
       [0.07203871],
       [0.        ],
       [0.01325589],
       [0.75113887],
       [0.7612883 ],
       [0.7485627 ],
       [0.71756184],
       [0.71078914],
       [0.65277845],
       [0.5964334 ],
       [0.43968982],
       [0.76436806],
       [0.7624179 ],
       [0.7352044 ],
       [0.65049624],
       [0.57928336],
       [0.7219924 ],
       [0.7081872 ],
       [0.68897027],
       [0.8293939 ],
       [0.8026182 ],
       [0.80505896],
       [0.7670607 ],
       [0.7266523 ],
       [0.6579271 ],
       [0.52369964],
       [0.73804456],
       [0.6930828 ],
       [0.6623032 ],
       [0.44135112],
       [0.6263001 ],
       [0.7823982 ],
       [0.7877803 ],
       [0.802905  ],
       [0.7826613 ],
       [0.6993519 ],
       [0.5877675 ],
       [0.45898223],
       [0.81514615],
       [0.8261459 ],
       [0.82384986],
       [0.80978394],
       [0.75090957],
       [0.65981114],
       [0.40837115],
       [0.83516234],
       [0.86651117],
       [0.85790306],
       [0.86659384],
       [0.8662837 ],
       [0.78756404],
       [0.6614731 ],
       [0.33079755],
       [0.        ],
       [0.2756696 ],
       [0.91583776],
       [0.8878702 ],
       [0.90798163],
       [0.88846314],
       [0.8595965 ],
       [0.7517823 ],
       [0.5484644 ],
       [0.5456471 ],
       [0.89729327],
       [0.87208736],
       [0.89319426],
       [0.875211  ],
       [0.8721384 ],
       [0.70374227],
       [0.3604235 ],
       [0.        ],
       [0.91447616],
       [0.87603974],
       [0.9096474 ],
       [0.8138108 ],
       [0.7603786 ],
       [0.583367  ],
       [0.832371  ],
       [0.81215334],
       [0.83004284],
       [0.6404859 ],
       [0.59112954],
       [0.3295346 ],
       [0.80157864],
       [0.7720978 ],
       [0.7885203 ],
       [0.75341827],
       [0.73109436],
       [0.6361064 ],
       [0.44806105],
       [0.12570283],
       [0.7715314 ],
       [0.7089232 ],
       [0.7424285 ],
       [0.58486325],
       [0.39198714],
       [0.8443694 ],
       [0.83530754],
       [0.77170515],
       [0.64949083],
       [0.4288653 ],
       [0.43517774],
       [0.8146367 ],
       [0.8408411 ],
       [0.84747386],
       [0.8236579 ],
       [0.7484346 ],
       [0.63364893],
       [0.8521269 ],
       [0.77560127],
       [0.77522516],
       [0.66862226],
       [0.7730481 ],
       [0.71682227],
       [0.6729224 ],
       [0.5570533 ],
       [0.7078461 ],
       [0.64506817],
       [0.6000977 ],
       [0.48232144],
       [0.51196903],
       [0.656666  ],
       [0.5968611 ],
       [0.5220611 ],
       [0.51401836],
       [0.8096578 ],
       [0.8029474 ],
       [0.81857514],
       [0.7857585 ],
       [0.709314  ],
       [0.6430697 ],
       [0.87593496],
       [0.85469496],
       [0.86900544],
       [0.8537981 ],
       [0.82265496],
       [0.7626668 ],
       [0.67974174],
       [0.8303616 ],
       [0.83031225],
       [0.84708226],
       [0.84680796],
       [0.8317599 ],
       [0.8044378 ],
       [0.7605697 ],
       [0.65520334],
       [0.48534852],
       [0.49166495],
       [0.8224741 ],
       [0.8172757 ],
       [0.83918846],
       [0.8317234 ],
       [0.79930604],
       [0.68049914],
       [0.50524676],
       [0.7917332 ],
       [0.78914905],
       [0.7444235 ],
       [0.63870764],
       [0.813325  ],
       [0.8105077 ],
       [0.81205964],
       [0.7808807 ],
       [0.737105  ],
       [0.60480773],
       [0.7837008 ],
       [0.6905533 ],
       [0.67888767],
       [0.5378359 ],
       [0.74987733],
       [0.71542865],
       [0.72252584],
       [0.5833166 ],
       [0.4943422 ],
       [0.74966544],
       [0.7544284 ],
       [0.66139245],
       [0.5959471 ],
       [0.7394973 ],
       [0.7219017 ],
       [0.7011935 ],
       [0.6196922 ],
       [0.4923054 ],
       [0.7557696 ],
       [0.72957736],
       [0.68072665],
       [0.5890269 ],
       [0.44019502],
       [0.7751161 ],
       [0.7282195 ],
       [0.6563975 ],
       [0.49251205],
       [0.4843989 ],
       [0.7656963 ],
       [0.7771983 ],
       [0.7372578 ],
       [0.64773726],
       [0.5018748 ],
       [0.5108053 ],
       [0.78416836],
       [0.77005255],
       [0.7520716 ],
       [0.629096  ],
       [0.52182686],
       [0.49007398],
       [0.65924907],
       [0.61491704],
       [0.57487446],
       [0.7663101 ],
       [0.7265084 ],
       [0.6541276 ],
       [0.55600005],
       [0.5192084 ],
       [0.8152161 ],
       [0.8252321 ],
       [0.83385825],
       [0.793248  ],
       [0.7260869 ],
       [0.55900425],
       [0.02361369],
       [0.80845386],
       [0.8210544 ],
       [0.7794982 ],
       [0.74527484],
       [0.56991655],
       [0.3234201 ]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
14964     28649.0  27185.207433  28570.205916           NaN           NaN
14965     28760.0  27412.001868  28087.903653           NaN           NaN
14966     28829.0  27287.213123  28487.044034           NaN           NaN
14967     25813.0  27286.866434  28368.003603           NaN           NaN
14968     25715.0  25854.662495      25979.49           NaN           NaN
...           ...           ...           ...           ...           ...
18280     25562.0  26531.749471  26013.520588  25993.050781  24631.632812
18281     25386.0  26682.293871   26161.99488  24743.876953  23384.947266
18282     22872.0  23121.786144  22550.322475  23200.759766  22358.246094
18283     15825.0  14935.714871  16669.129145  14345.122070  17097.496094
18284      1450.0   1709.206578   1857.219074   4774.128418   9702.603516

[518 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

15084    28669.0
15085    29441.0
15086    29365.0
15087    28405.0
15088    27794.0
          ...
18280    25562.0
18281    25386.0
18282    22872.0
18283    15825.0
18284     1450.0
Name: Generación, Length: 470, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 9)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      2,368 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 474,049 (1.81 MB)

 Trainable params: 474,049 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 290s 469ms/step - loss: 1.3068 - mae: 0.3753 - val_loss: 0.8472 - val_mae: 0.2702
Epoch 2/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 59s 288ms/step - loss: 0.7673 - mae: 0.2646 - val_loss: 0.5581 - val_mae: 0.2503
Epoch 3/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 78s 218ms/step - loss: 0.5081 - mae: 0.2566 - val_loss: 0.3811 - val_mae: 0.2246
Epoch 4/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 53s 275ms/step - loss: 0.3420 - mae: 0.2336 - val_loss: 0.2541 - val_mae: 0.2060
Epoch 5/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 83s 242ms/step - loss: 0.2289 - mae: 0.1952 - val_loss: 0.1967 - val_mae: 0.2041
Epoch 6/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 41s 241ms/step - loss: 0.1633 - mae: 0.1742 - val_loss: 0.1433 - val_mae: 0.1877
Epoch 7/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 43s 247ms/step - loss: 0.1249 - mae: 0.1653 - val_loss: 0.1219 - val_mae: 0.1800
Epoch 8/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 55s 307ms/step - loss: 0.1017 - mae: 0.1619 - val_loss: 0.1033 - val_mae: 0.1849
Epoch 9/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 81s 258ms/step - loss: 0.0862 - mae: 0.1615 - val_loss: 0.0938 - val_mae: 0.1741
Epoch 10/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 41s 226ms/step - loss: 0.0742 - mae: 0.1515 - val_loss: 0.0811 - val_mae: 0.1681
Epoch 11/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 32s 148ms/step - loss: 0.0696 - mae: 0.1564 - val_loss: 0.0779 - val_mae: 0.1689
Epoch 12/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 47s 282ms/step - loss: 0.0599 - mae: 0.1421 - val_loss: 0.0720 - val_mae: 0.1635
Epoch 13/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 92s 307ms/step - loss: 0.0589 - mae: 0.1454 - val_loss: 0.0678 - val_mae: 0.1672
Epoch 14/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 77s 237ms/step - loss: 0.0527 - mae: 0.1398 - val_loss: 0.0719 - val_mae: 0.1952
Epoch 15/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 35s 170ms/step - loss: 0.0503 - mae: 0.1408 - val_loss: 0.0648 - val_mae: 0.1737
Epoch 16/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 66s 303ms/step - loss: 0.0499 - mae: 0.1417 - val_loss: 0.0640 - val_mae: 0.1753
Epoch 17/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 84s 273ms/step - loss: 0.0473 - mae: 0.1396 - val_loss: 0.0637 - val_mae: 0.1786
Epoch 18/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 85s 256ms/step - loss: 0.0446 - mae: 0.1356 - val_loss: 0.0623 - val_mae: 0.1695
Epoch 19/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 31s 160ms/step - loss: 0.0466 - mae: 0.1392 - val_loss: 0.0612 - val_mae: 0.1752
Epoch 20/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 53s 221ms/step - loss: 0.0454 - mae: 0.1433 - val_loss: 0.0596 - val_mae: 0.1625
Epoch 21/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 54s 284ms/step - loss: 0.0397 - mae: 0.1264 - val_loss: 0.0597 - val_mae: 0.1679
Epoch 22/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 89s 289ms/step - loss: 0.0388 - mae: 0.1296 - val_loss: 0.0598 - val_mae: 0.1611
Epoch 23/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 71s 197ms/step - loss: 0.0408 - mae: 0.1309 - val_loss: 0.0599 - val_mae: 0.1649
Epoch 24/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 56s 270ms/step - loss: 0.0366 - mae: 0.1239 - val_loss: 0.0661 - val_mae: 0.1656
Epoch 25/50
148/148 ━━━━━━━━━━━━━━━━━━━━ 45s 259ms/step - loss: 0.0397 - mae: 0.1335 - val_loss: 0.0617 - val_mae: 0.1582

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

15/15 ━━━━━━━━━━━━━━━━━━━━ 42s 1s/step

array([[0.8017259 ],
       [0.9155079 ],
       [0.88351774],
       [0.898451  ],
       [0.8344611 ],
       [0.8089581 ],
       [0.29764456],
       [0.3978417 ],
       [0.7545711 ],
       [0.90653104],
       [0.9168828 ],
       [0.95017827],
       [0.8749721 ],
       [0.8391649 ],
       [0.8362489 ],
       [0.16638964],
       [0.80093336],
       [0.9213102 ],
       [0.95709425],
       [0.9503931 ],
       [0.8900832 ],
       [0.8243661 ],
       [0.84515935],
       [0.28722587],
       [0.9013023 ],
       [0.9299159 ],
       [0.96670616],
       [0.9469912 ],
       [0.48739526],
       [0.94166225],
       [1.0354537 ],
       [0.9799162 ],
       [0.941506  ],
       [0.8552394 ],
       [0.35310417],
       [0.4768762 ],
       [0.7904162 ],
       [0.9710121 ],
       [1.0097541 ],
       [1.0197252 ],
       [0.8331157 ],
       [0.810413  ],
       [0.6927415 ],
       [0.48355907],
       [0.42149493],
       [0.21635062],
       [0.8669723 ],
       [0.91969556],
       [0.9261533 ],
       [0.8306542 ],
       [0.8610259 ],
       [0.8875819 ],
       [0.8024721 ],
       [0.5720477 ],
       [0.33931512],
       [0.30455482],
       [0.5409689 ],
       [0.9323288 ],
       [0.8877617 ],
       [0.935532  ],
       [0.87700975],
       [0.8649431 ],
       [0.8365397 ],
       [0.50821114],
       [0.15260404],
       [0.07277294],
       [0.5786329 ],
       [0.93662053],
       [0.9189901 ],
       [0.94041795],
       [0.8821202 ],
       [0.8673571 ],
       [0.8332176 ],
       [0.2936948 ],
       [0.7950957 ],
       [0.9461887 ],
       [0.91036797],
       [0.90614974],
       [0.86973894],
       [0.84150255],
       [0.18220416],
       [0.24888918],
       [0.6537863 ],
       [0.8912388 ],
       [0.83747196],
       [0.76700175],
       [0.6704162 ],
       [0.6898811 ],
       [0.5245346 ],
       [0.7897203 ],
       [0.8481338 ],
       [0.78642416],
       [0.8009598 ],
       [0.5737861 ],
       [0.89486504],
       [0.851747  ],
       [0.85812545],
       [0.8283378 ],
       [0.80206716],
       [0.3787561 ],
       [0.79475737],
       [0.92142403],
       [0.91480744],
       [0.86701   ],
       [0.8808292 ],
       [0.8555524 ],
       [0.8044797 ],
       [0.86396265],
       [0.90316164],
       [0.8511173 ],
       [0.8070762 ],
       [0.7936535 ],
       [0.81545067],
       [0.57156247],
       [0.31535113],
       [0.36460942],
       [0.91463137],
       [0.89033514],
       [0.8978728 ],
       [0.85816646],
       [0.8584971 ],
       [0.79026026],
       [0.7191434 ],
       [0.57985955],
       [0.34775183],
       [0.12798157],
       [0.19477522],
       [0.6006978 ],
       [0.8674773 ],
       [0.86262333],
       [0.88641155],
       [0.8680778 ],
       [0.87762463],
       [0.8458761 ],
       [0.6456946 ],
       [0.32236293],
       [0.15428331],
       [0.3372809 ],
       [0.6805364 ],
       [0.8951558 ],
       [0.88577884],
       [0.91333914],
       [0.90343654],
       [0.9336077 ],
       [0.9179375 ],
       [0.9088173 ],
       [0.92091703],
       [0.9381487 ],
       [0.90437526],
       [0.9019641 ],
       [0.86345255],
       [0.83980465],
       [0.74667525],
       [0.58104914],
       [0.8784741 ],
       [0.88344836],
       [0.8635951 ],
       [0.8358318 ],
       [0.8527005 ],
       [0.8308994 ],
       [0.73048484],
       [0.42730168],
       [0.2701403 ],
       [0.8983653 ],
       [0.88810164],
       [0.88464224],
       [0.83939266],
       [0.8790082 ],
       [0.8453372 ],
       [0.6666673 ],
       [0.5246006 ],
       [0.49973   ],
       [0.9036102 ],
       [0.91285384],
       [0.8998208 ],
       [0.8568976 ],
       [0.8961573 ],
       [0.85617197],
       [0.7277871 ],
       [0.5440251 ],
       [0.27134824],
       [0.9063341 ],
       [0.8702869 ],
       [0.78569156],
       [0.7005689 ],
       [0.81504005],
       [0.79559636],
       [0.59868264],
       [0.3567862 ],
       [0.15531981],
       [0.22444537],
       [0.82978314],
       [0.8810902 ],
       [0.89691067],
       [0.9054034 ],
       [0.91310596],
       [0.88602847],
       [0.8425046 ],
       [0.6592527 ],
       [0.42025718],
       [0.09802318],
       [0.15252829],
       [0.6987288 ],
       [0.89025825],
       [0.8732903 ],
       [0.90499943],
       [0.87612194],
       [0.8697746 ],
       [0.80029297],
       [0.5998214 ],
       [0.3223856 ],
       [0.0477308 ],
       [0.04103422],
       [0.5261408 ],
       [0.8791982 ],
       [0.85657406],
       [0.8730053 ],
       [0.82446617],
       [0.8023678 ],
       [0.2025381 ],
       [0.20960736],
       [0.70186347],
       [0.86538815],
       [0.9038097 ],
       [0.9032892 ],
       [0.8504979 ],
       [0.8998343 ],
       [0.9218727 ],
       [0.9182639 ],
       [0.9018823 ],
       [0.8493562 ],
       [0.6986587 ],
       [0.51217556],
       [0.92192125],
       [0.8717374 ],
       [0.85744256],
       [0.8592578 ],
       [0.82714295],
       [0.60200155],
       [0.3542447 ],
       [0.5455112 ],
       [0.5036709 ],
       [0.3490864 ],
       [0.21949461],
       [0.16251987],
       [0.18268496],
       [0.2824041 ],
       [0.6258379 ],
       [0.8016366 ],
       [0.81041205],
       [0.8103467 ],
       [0.83157015],
       [0.7661427 ],
       [0.63557035],
       [0.3985529 ],
       [0.85540855],
       [0.8004173 ],
       [0.7658816 ],
       [0.6867056 ],
       [0.6100638 ],
       [0.72641903],
       [0.76467204],
       [0.74130523],
       [0.8099536 ],
       [0.83507144],
       [0.840167  ],
       [0.82113576],
       [0.80751884],
       [0.7818075 ],
       [0.61198664],
       [0.8255578 ],
       [0.8220875 ],
       [0.7967117 ],
       [0.6715544 ],
       [0.6409118 ],
       [0.8474895 ],
       [0.8252237 ],
       [0.83094466],
       [0.8158853 ],
       [0.7991252 ],
       [0.7118557 ],
       [0.5279236 ],
       [0.82070684],
       [0.790936  ],
       [0.79842883],
       [0.761229  ],
       [0.77761126],
       [0.7130107 ],
       [0.55469096],
       [0.8492001 ],
       [0.8293825 ],
       [0.82967997],
       [0.80811113],
       [0.81251854],
       [0.7813209 ],
       [0.60997295],
       [0.40253216],
       [0.15890104],
       [0.39591026],
       [0.8656335 ],
       [0.8221023 ],
       [0.83073515],
       [0.8118584 ],
       [0.8364285 ],
       [0.71234584],
       [0.43560097],
       [0.4862889 ],
       [0.87736684],
       [0.8485241 ],
       [0.84776384],
       [0.8099427 ],
       [0.8238694 ],
       [0.7124834 ],
       [0.45702267],
       [0.2924355 ],
       [0.8710743 ],
       [0.86425745],
       [0.85571545],
       [0.8165388 ],
       [0.7176324 ],
       [0.51454735],
       [0.8605316 ],
       [0.84231406],
       [0.8402904 ],
       [0.7202933 ],
       [0.58038276],
       [0.31210628],
       [0.88971514],
       [0.872496  ],
       [0.85945785],
       [0.7554097 ],
       [0.793651  ],
       [0.72501314],
       [0.52503693],
       [0.30096158],
       [0.8168695 ],
       [0.67753166],
       [0.7251724 ],
       [0.68679166],
       [0.54608154],
       [0.8553492 ],
       [0.85844517],
       [0.8081791 ],
       [0.6034771 ],
       [0.4732203 ],
       [0.44115484],
       [0.8869107 ],
       [0.8354945 ],
       [0.8180162 ],
       [0.8105567 ],
       [0.79245126],
       [0.67474324],
       [0.8713908 ],
       [0.85127115],
       [0.83900017],
       [0.7334368 ],
       [0.7542768 ],
       [0.7777957 ],
       [0.7318575 ],
       [0.6985213 ],
       [0.78644085],
       [0.7678131 ],
       [0.7318227 ],
       [0.60681176],
       [0.6026258 ],
       [0.76063246],
       [0.7394189 ],
       [0.6159647 ],
       [0.5841237 ],
       [0.8203916 ],
       [0.83749133],
       [0.8260746 ],
       [0.8381939 ],
       [0.7907665 ],
       [0.6834301 ],
       [0.8527622 ],
       [0.86535245],
       [0.86175954],
       [0.8033748 ],
       [0.77802336],
       [0.79482186],
       [0.66022253],
       [0.8613228 ],
       [0.8467424 ],
       [0.86763686],
       [0.82851076],
       [0.83305585],
       [0.8349805 ],
       [0.8208089 ],
       [0.64786565],
       [0.48252952],
       [0.514057  ],
       [0.9061837 ],
       [0.87198985],
       [0.8565406 ],
       [0.84132767],
       [0.8627643 ],
       [0.77554965],
       [0.57146204],
       [0.8138894 ],
       [0.83307517],
       [0.78052026],
       [0.76688397],
       [0.86871874],
       [0.8749216 ],
       [0.8653765 ],
       [0.8299858 ],
       [0.7811842 ],
       [0.7489692 ],
       [0.88039285],
       [0.8098198 ],
       [0.7899703 ],
       [0.64270914],
       [0.7895177 ],
       [0.80268264],
       [0.83288634],
       [0.75757444],
       [0.6349708 ],
       [0.8529029 ],
       [0.84088314],
       [0.838102  ],
       [0.76280844],
       [0.89496326],
       [0.8587451 ],
       [0.81349033],
       [0.76368237],
       [0.69264734],
       [0.8601279 ],
       [0.81259143],
       [0.77808213],
       [0.68832064],
       [0.59283125],
       [0.85447085],
       [0.82839507],
       [0.7633008 ],
       [0.66354597],
       [0.56005836],
       [0.8618994 ],
       [0.8243704 ],
       [0.8097086 ],
       [0.72966516],
       [0.5973661 ],
       [0.457502  ],
       [0.8500821 ],
       [0.8165519 ],
       [0.7886971 ],
       [0.6819949 ],
       [0.5524882 ],
       [0.34535637],
       [0.68627393],
       [0.7257118 ],
       [0.6001793 ],
       [0.7099311 ],
       [0.76922256],
       [0.75227255],
       [0.550517  ],
       [0.33450764],
       [0.8245653 ],
       [0.81714094],
       [0.7820717 ],
       [0.7351404 ],
       [0.7091118 ],
       [0.5508766 ],
       [0.25111845],
       [0.8136288 ],
       [0.7960966 ],
       [0.70228666],
       [0.62089336],
       [0.5619072 ],
       [0.3225698 ]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
14964,28649.0,27185.207433,28570.205916,NaN,NaN,NaN
14965,28760.0,27412.001868,28087.903653,NaN,NaN,NaN
14966,28829.0,27287.213123,28487.044034,NaN,NaN,NaN
14967,25813.0,27286.866434,28368.003603,NaN,NaN,NaN
14968,25715.0,25854.662495,25979.49,NaN,NaN,NaN
...,...,...,...,...,...,...
18280,25562.0,26531.749471,26013.520588,25993.050781,24631.632812,23882.898438
18281,25386.0,26682.293871,26161.99488,24743.876953,23384.947266,21068.599609
18282,22872.0,23121.786144,22550.322475,23200.759766,22358.246094,18626.800781
18283,15825.0,14935.714871,16669.129145,14345.122070,17097.496094,16857.214844
18284,1450.0,1709.206578,1857.219074,4774.128418,9702.603516,9677.093750

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1019.5988
RMSE: 1823.2087
R²: 0.9533
Random Forest
MAE: 1132.4972
RMSE: 2125.0614
R²: 0.9366
CTNET
MAE: 3903.6518
RMSE: 6640.9185
R²: 0.3338
Forecast
MAE: 4584.1002
RMSE: 6644.8977
R²: 0.3330
Photovoltaic
MAE: 4021.5300
RMSE: 6103.0076
R²: 0.4374

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

74/74 ━━━━━━━━━━━━━━━━━━━━ 18s 121ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

74/74 ━━━━━━━━━━━━━━━━━━━━ 22s 172ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

74/74 ━━━━━━━━━━━━━━━━━━━━ 12s 64ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
37,20596.278869,25889.087712,23128.419174,NaN,NaN,NaN
207,26098.851182,24843.499368,25386.898087,NaN,NaN,NaN
208,28500.000000,26328.342640,27553.583407,NaN,NaN,NaN
209,28500.000000,24809.626208,28066.727050,NaN,NaN,NaN
210,28500.000000,25409.045786,27100.040132,NaN,NaN,NaN
...,...,...,...,...,...,...
12286,0.000000,0.000000,0.000000,17745.292969,2115.510498,9332.243164
12301,22808.000000,23232.824009,23146.920008,22325.748047,17512.943359,17208.289062
12302,21959.000000,21738.836363,21760.326689,24774.064453,22042.119141,19113.902344
12303,21047.000000,20951.472475,20928.136453,24125.187500,20931.369141,21776.238281
12304,21102.000000,21157.001498,21228.125451,22916.707031,19375.349609,20335.029297

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 883.6183
RMSE: 1507.0696
R²: 0.9789
Random Forest
MAE: 339.1511
RMSE: 632.8372
R²: 0.9963
CTNET
MAE: 3800.2465
RMSE: 5931.6700
R²: 0.6752
Forecast
MAE: 4660.4532
RMSE: 6905.4709
R²: 0.5599
Photovoltaic
MAE: 3791.8976
RMSE: 5738.7618
R²: 0.6960

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,...,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.4_Predicciones_Conjunto_soleado GMM.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_4_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_4_RandomForest_model.pkl")

['4_4_RandomForest_model.pkl']

In [87]:
CTNET.save("4_4_CTNET_model.keras")
Forecast_model.save("4_4_Forecast_model.keras")
Photo_model.save("4_4_Photo_model.keras")