# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,7,77,0,4,15,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,7,82,0,4,16,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,9,85,0,3,16,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,11,87,0,3,16,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,11,88,0,3,16,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,15,86,0,3,14,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,47,89,0,3,16,6,Nublado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,51,95,0,4,17,7,Nublado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,47,100,0,3,18,8,Nublado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,5,100,1,4,18,9,Nublado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,5,93,2,4,18,10,Nublado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,5,79,2,4,17,11,Nublado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,5,64,6,3,15,12,Nublado,Lluvioso
13,2022-09-01 13:00:00,25478.471342,23,5,51,11,3,13,13,Soleado,Lluvioso
14,2022-09-01 14:00:00,29057.585772,25,3,41,12,1,11,14,Soleado,Lluvioso
15,2022-09-01 15:00:00,30000.000000,26,0,35,11,1,9,15,Soleado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,0,33,8,1,9,16,Soleado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,0,34,5,1,11,17,Soleado,Soleado
18,2022-09-01 18:00:00,29900.303971,27,0,37,3,2,11,18,Soleado,Soleado
19,2022-09-01 19:00:00,18282.505369,26,0,41,2,3,12,19,Soleado,Soleado
20,2022-09-01 20:00:00,3411.083740,24,2,48,0,3,12,20,Nublado,Lluvioso
21,2022-09-01 21:00:00,382.187718,22,6,55,0,3,13,21,Nublado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,6,61,0,4,13,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,6,68,0,4,14,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster GMM"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
35,2022-09-02 11:00:00,17036.043251,20,0,71,2,2,14,11,Soleado,Nublado,5030.740421,22189.147406
36,2022-09-02 12:00:00,27523.885172,21,0,57,4,2,13,12,Soleado,Nublado,17036.043251,29196.986647
227,2022-09-10 11:00:00,26530.520060,19,0,74,4,1,14,11,Soleado,Nublado,16754.858938,23013.622622
228,2022-09-10 12:00:00,28976.805233,20,0,62,7,1,13,12,Soleado,Nublado,26530.520060,16313.782163
275,2022-09-12 11:00:00,27101.921674,18,0,82,4,2,15,11,Soleado,Nublado,21597.209964,23484.596732
276,2022-09-12 12:00:00,30000.000000,19,0,69,7,2,13,12,Soleado,Nublado,27101.921674,22800.000000
277,2022-09-12 13:00:00,27281.964164,21,0,58,10,2,12,13,Soleado,Nublado,30000.000000,21600.000000
299,2022-09-13 11:00:00,17821.243227,17,0,72,4,2,12,11,Soleado,Nublado,21580.173881,27101.921674
300,2022-09-13 12:00:00,19421.129165,19,0,61,7,2,12,12,Soleado,Nublado,17821.243227,30000.000000
491,2022-09-21 11:00:00,17160.408876,18,0,76,4,2,13,11,Soleado,Nublado,23029.146524,12327.870821

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
35,20,0,71,2,2,14,11,5030.740421,22189.147406
36,21,0,57,4,2,13,12,17036.043251,29196.986647
227,19,0,74,4,1,14,11,16754.858938,23013.622622
228,20,0,62,7,1,13,12,26530.520060,16313.782163
275,18,0,82,4,2,15,11,21597.209964,23484.596732
...,...,...,...,...,...,...,...,...,...
18250,14,0,93,2,1,13,9,7302.000000,17824.000000
18251,17,0,78,4,1,13,10,18014.000000,23097.000000
18252,20,0,64,6,1,13,11,23010.000000,26140.000000
18285,22,0,45,0,1,9,20,1450.000000,0.000000
18286,20,0,54,0,1,10,21,0.000000,0.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
35     17036.043251
36     27523.885172
227    26530.520060
228    28976.805233
275    27101.921674
...             ...
18250  18014.000000
18251  23010.000000
18252  26156.000000
18285      0.000000
18286      0.000000

[2639 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 1847, y_train: 1847
X_val: 396, y_val: 396
X_test: 396, y_test: 396

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.52631579 0.         0.69473684 ... 0.33333333 0.16769135 0.73963825]
 [0.55263158 0.         0.54736842 ... 0.4        0.56786811 0.97323289]
 [0.5        0.         0.72631579 ... 0.33333333 0.5584953  0.76712075]
 ...
 [0.44736842 0.         0.25263158 ... 1.         0.         0.        ]
 [0.18421053 0.         0.72631579 ... 0.         0.         0.        ]
 [0.18421053 0.         0.75789474 ... 0.06666667 0.         0.        ]]
(1847, 9)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
35,0.526316,0.0,0.694737,0.153846,0.333333,0.777778,0.333333,0.167691,0.739638
36,0.552632,0.0,0.547368,0.307692,0.333333,0.722222,0.400000,0.567868,0.973233
227,0.500000,0.0,0.726316,0.307692,0.000000,0.777778,0.333333,0.558495,0.767121
228,0.526316,0.0,0.600000,0.538462,0.000000,0.722222,0.400000,0.884351,0.543793
275,0.473684,0.0,0.810526,0.307692,0.333333,0.833333,0.333333,0.719907,0.782820
...,...,...,...,...,...,...,...,...,...
11733,0.421053,0.0,0.473684,0.000000,0.333333,0.277778,0.933333,0.036533,0.000000
11757,0.500000,0.0,0.210526,0.000000,0.666667,0.055556,0.933333,0.030500,0.000000
11758,0.447368,0.0,0.252632,0.000000,0.333333,0.055556,1.000000,0.000000,0.000000
11767,0.184211,0.0,0.726316,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000
11768,0.184211,0.0,0.757895,0.000000,0.000000,0.166667,0.066667,0.000000,0.000000

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.13157895 0.         0.84210526 ... 0.13333333 0.         0.00983333]
 [0.18421053 0.         0.78947368 ... 0.2        0.02443333 0.18196667]
 [0.26315789 0.         0.64210526 ... 0.26666667 0.53976667 0.31103333]
 ...
 [0.18421053 0.         0.90526316 ... 0.13333333 0.043      0.34236667]
 [0.23684211 0.         0.85263158 ... 0.2        0.39413333 0.81946667]
 [0.34210526 0.         0.65263158 ... 0.26666667 0.84823333 0.9256    ]]
(396, 9)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
11769,0.131579,0.0,0.842105,0.000000,0.0,0.166667,0.133333,0.000000,0.009833
11770,0.184211,0.0,0.789474,0.076923,0.0,0.222222,0.200000,0.024433,0.181967
11771,0.263158,0.0,0.642105,0.153846,0.0,0.222222,0.266667,0.539767,0.311033
11772,0.368421,0.0,0.463158,0.307692,0.0,0.222222,0.333333,0.914833,0.793067
11773,0.473684,0.0,0.326316,0.307692,0.0,0.166667,0.400000,0.929333,0.853733
...,...,...,...,...,...,...,...,...,...
13951,0.210526,0.0,0.852632,0.000000,0.0,0.333333,0.000000,0.000000,0.000000
13952,0.184211,0.0,0.936842,0.000000,0.0,0.333333,0.066667,0.000000,0.013300
13953,0.184211,0.0,0.905263,0.076923,0.0,0.333333,0.133333,0.043000,0.342367
13954,0.236842,0.0,0.852632,0.230769,0.0,0.333333,0.200000,0.394133,0.819467
13955,0.342105,0.0,0.652632,0.384615,0.0,0.388889,0.266667,0.848233,0.925600

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.44736842 0.         0.45263158 ... 0.33333333 0.97296667 0.94383333]
 [0.71052632 0.         0.08421053 ... 0.6        0.98766667 0.93226667]
 [0.76315789 0.         0.05263158 ... 0.66666667 0.96936667 0.91333333]
 ...
 [0.52631579 0.         0.62105263 ... 0.33333333 0.767      0.87133333]
 [0.57894737 0.         0.42105263 ... 0.93333333 0.04833333 0.        ]
 [0.52631579 0.         0.51578947 ... 1.         0.         0.        ]]
(396, 9)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
13956,0.447368,0.0,0.452632,0.538462,0.0,0.333333,0.333333,0.972967,0.943833
13960,0.710526,0.0,0.084211,0.538462,0.0,0.166667,0.600000,0.987667,0.932267
13961,0.763158,0.0,0.052632,0.384615,0.0,0.277778,0.666667,0.969367,0.913333
13962,0.815789,0.0,0.042105,0.230769,0.0,0.277778,0.733333,0.955300,0.877900
13963,0.763158,0.0,0.073684,0.076923,0.0,0.166667,0.800000,0.880333,0.708767
...,...,...,...,...,...,...,...,...,...
18250,0.368421,0.0,0.926316,0.153846,0.0,0.722222,0.200000,0.243400,0.594133
18251,0.447368,0.0,0.768421,0.307692,0.0,0.722222,0.266667,0.600467,0.769900
18252,0.526316,0.0,0.621053,0.461538,0.0,0.722222,0.333333,0.767000,0.871333
18285,0.578947,0.0,0.421053,0.000000,0.0,0.500000,0.933333,0.048333,0.000000
18286,0.526316,0.0,0.515789,0.000000,0.0,0.555556,1.000000,0.000000,0.000000

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.51282051 0.         0.70103093 ... 0.33333333 0.16769135 0.73963825]
 [0.53846154 0.         0.55670103 ... 0.4        0.56786811 0.97323289]
 [0.48717949 0.         0.73195876 ... 0.33333333 0.5584953  0.76712075]
 ...
 [0.51282051 0.         0.62886598 ... 0.33333333 0.767      0.87133333]
 [0.56410256 0.         0.43298969 ... 0.93333333 0.04833333 0.        ]
 [0.51282051 0.         0.5257732  ... 1.         0.         0.        ]]
(2639, 9)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
35,0.512821,0.0,0.701031,0.153846,0.333333,0.777778,0.333333,0.167691,0.739638
36,0.538462,0.0,0.556701,0.307692,0.333333,0.722222,0.400000,0.567868,0.973233
227,0.487179,0.0,0.731959,0.307692,0.000000,0.777778,0.333333,0.558495,0.767121
228,0.512821,0.0,0.608247,0.538462,0.000000,0.722222,0.400000,0.884351,0.543793
275,0.461538,0.0,0.814433,0.307692,0.333333,0.833333,0.333333,0.719907,0.782820
...,...,...,...,...,...,...,...,...,...
18250,0.358974,0.0,0.927835,0.153846,0.000000,0.722222,0.200000,0.243400,0.594133
18251,0.435897,0.0,0.773196,0.307692,0.000000,0.722222,0.266667,0.600467,0.769900
18252,0.512821,0.0,0.628866,0.461538,0.000000,0.722222,0.333333,0.767000,0.871333
18285,0.564103,0.0,0.432990,0.000000,0.000000,0.500000,0.933333,0.048333,0.000000
18286,0.512821,0.0,0.525773,0.000000,0.000000,0.555556,1.000000,0.000000,0.000000

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.56786811]
 [0.91746284]
 [0.88435067]
 ...
 [0.        ]
 [0.        ]
 [0.        ]]
(1847, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
35       0.567868
36       0.917463
227      0.884351
228      0.965894
275      0.903397
...           ...
11733    0.000000
11757    0.000000
11758    0.000000
11767    0.000000
11768    0.000000

[1847 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[2.44333333e-02]
 [5.39766667e-01]
 [9.14833333e-01]
 [9.29333333e-01]
 [9.46266667e-01]
 [8.36400000e-01]
 [8.03333333e-01]
 [8.37600000e-01]
 [8.36633333e-01]
 [8.09166667e-01]
 [8.36766667e-01]
 [8.12266667e-01]
 [4.06900000e-01]
 [3.18666667e-02]
 [8.06933333e-01]
 [8.85000000e-01]
 [8.08366667e-01]
 [3.55366667e-01]
 [8.36400000e-01]
 [8.50366667e-01]
 [8.51533333e-01]
 [8.37533333e-01]
 [8.05866667e-01]
 [8.36866667e-01]
 [8.09666667e-01]
 [4.06400000e-01]
 [3.15333333e-02]
 [3.15333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.34133333e-01]
 [9.49200000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.45333333e-02]
 [5.35233333e-01]
 [9.49400000e-01]
 [9.30866667e-01]
 [9.48733333e-01]
 [9.43500000e-01]
 [9.33433333e-01]
 [8.93566667e-01]
 [9.29733333e-01]
 [8.98200000e-01]
 [4.51566667e-01]
 [3.57666667e-02]
 [0.00000000e+00]
 [8.30000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.54233333e-01]
 [7.31700000e-01]
 [7.93966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.73333333e-03]
 [2.60933333e-01]
 [7.31700000e-01]
 [7.83666667e-01]
 [1.25666667e-02]
 [5.85600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.59200000e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93000000e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [2.21733333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.39000000e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [2.42266667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.06333333e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [2.56633333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93000000e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.53666667e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.27666667e-02]
 [2.93633333e-01]
 [6.31400000e-01]
 [6.75366667e-01]
 [6.67766667e-01]
 [5.70933333e-01]
 [2.96900000e-01]
 [6.31400000e-01]
 [6.70400000e-01]
 [6.27166667e-01]
 [6.26333333e-01]
 [6.40166667e-01]
 [6.02466667e-01]
 [4.66100000e-01]
 [4.78000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93233333e-01]
 [8.00033333e-01]
 [7.86866667e-01]
 [4.59900000e-01]
 [4.53000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.20833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.78666667e-02]
 [3.81333333e-01]
 [7.91266667e-01]
 [8.30366667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.81333333e-02]
 [3.79500000e-01]
 [7.89233333e-01]
 [8.41900000e-01]
 [7.89666667e-01]
 [7.82600000e-01]
 [7.68333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.70000000e-03]
 [3.30366667e-01]
 [7.11833333e-01]
 [7.55933333e-01]
 [7.38766667e-01]
 [7.13266667e-01]
 [7.10400000e-01]
 [7.04633333e-01]
 [7.07200000e-01]
 [6.77800000e-01]
 [3.80400000e-01]
 [4.24000000e-02]
 [8.22733333e-01]
 [8.54800000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.70333333e-02]
 [3.21866667e-01]
 [6.61933333e-01]
 [6.85000000e-01]
 [0.00000000e+00]
 [3.47000000e-02]
 [3.94633333e-01]
 [6.74166667e-01]
 [6.92266667e-01]
 [6.70433333e-01]
 [6.43100000e-01]
 [6.45766667e-01]
 [6.42366667e-01]
 [8.54000000e-01]
 [8.59233333e-01]
 [8.16733333e-01]
 [2.64400000e-01]
 [7.96266667e-01]
 [9.88166667e-01]
 [9.31333333e-01]
 [8.76566667e-01]
 [8.45000000e-01]
 [7.41766667e-01]
 [5.00300000e-01]
 [3.33333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.64700000e-01]
 [8.31333333e-01]
 [1.00000000e+00]
 [9.96200000e-01]
 [1.00000000e+00]
 [9.91066667e-01]
 [9.83100000e-01]
 [9.71766667e-01]
 [0.00000000e+00]
 [7.62666667e-02]
 [5.93533333e-01]
 [6.20733333e-01]
 [8.89700000e-01]
 [8.95366667e-01]
 [8.77033333e-01]
 [8.61566667e-01]
 [8.45600000e-01]
 [8.54000000e-01]
 [8.67133333e-01]
 [8.29233333e-01]
 [0.00000000e+00]
 [6.79466667e-01]
 [6.84666667e-01]
 [2.61666667e-01]
 [8.47233333e-01]
 [8.92566667e-01]
 [8.91833333e-01]
 [8.84000000e-01]
 [8.81533333e-01]
 [8.92833333e-01]
 [8.93833333e-01]
 [8.53433333e-01]
 [5.14800000e-01]
 [5.18333333e-02]
 [6.37866667e-01]
 [8.21466667e-01]
 [8.27966667e-01]
 [8.79666667e-01]
 [8.79666667e-01]
 [4.74833333e-01]
 [5.50866667e-01]
 [8.79666667e-01]
 [0.00000000e+00]
 [4.33333333e-04]
 [5.93533333e-01]
 [6.12933333e-01]
 [8.81366667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.21133333e-01]
 [7.24333333e-01]
 [5.93533333e-01]
 [6.65166667e-01]
 [9.40666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.93533333e-01]
 [7.69300000e-01]
 [9.28266667e-01]
 [9.40400000e-01]
 [9.29966667e-01]
 [9.21166667e-01]
 [9.04100000e-01]
 [9.32766667e-01]
 [9.17500000e-01]
 [8.86200000e-01]
 [6.76433333e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [5.93533333e-01]
 [7.63766667e-01]
 [9.33933333e-01]
 [0.00000000e+00]
 [7.56900000e-01]
 [7.67166667e-01]
 [5.93533333e-01]
 [7.68333333e-01]
 [9.49966667e-01]
 [9.51900000e-01]
 [9.51733333e-01]
 [9.75366667e-01]
 [9.35800000e-01]
 [9.04766667e-01]
 [9.29900000e-01]
 [9.22133333e-01]
 [6.47666667e-01]
 [1.32900000e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.66666667e-05]
 [5.93533333e-01]
 [7.42033333e-01]
 [9.55433333e-01]
 [8.95366667e-01]
 [9.50333333e-01]
 [9.39933333e-01]
 [9.14666667e-01]
 [8.83566667e-01]
 [8.60766667e-01]
 [8.27766667e-01]
 [6.04733333e-01]
 [1.28500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.93533333e-01]
 [6.12766667e-01]
 [8.79666667e-01]
 [9.16966667e-01]
 [9.83700000e-01]
 [9.76633333e-01]
 [9.70033333e-01]
 [8.54000000e-01]
 [9.44766667e-01]
 [9.41966667e-01]
 [6.38733333e-01]
 [1.34233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.12600000e-01]
 [1.33333333e-04]
 [0.00000000e+00]
 [8.82166667e-01]
 [8.95366667e-01]
 [8.61933333e-01]
 [0.00000000e+00]
 [8.66666667e-04]
 [5.93533333e-01]
 [6.33333333e-01]
 [8.86333333e-01]
 [8.57166667e-01]
 [8.50866667e-01]
 [8.54000000e-01]
 [7.73300000e-01]
 [7.45766667e-01]
 [5.59166667e-01]
 [9.18666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.00000000e-04]
 [4.74833333e-01]
 [4.93366667e-01]
 [6.88833333e-01]
 [6.87366667e-01]
 [6.55566667e-01]
 [9.19733333e-01]
 [8.77900000e-01]
 [7.23600000e-01]
 [1.56333333e-02]
 [2.00866667e-01]
 [1.60000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.33000000e-02]
 [3.42366667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [9.43833333e-01]
 [0.00000000e+00]
 [4.30000000e-02]
 [3.94133333e-01]
 [8.48233333e-01]
 [9.72966667e-01]]
(396, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
11769    0.024433
11770    0.539767
11771    0.914833
11772    0.929333
11773    0.946267
...           ...
13951    0.000000
13952    0.043000
13953    0.394133
13954    0.848233
13955    0.972967

[396 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[9.95466667e-01]
 [9.69366667e-01]
 [9.55300000e-01]
 [8.80333333e-01]
 [5.72166667e-01]
 [7.90133333e-01]
 [0.00000000e+00]
 [1.43000000e-02]
 [2.74900000e-01]
 [6.55566667e-01]
 [1.53333333e-03]
 [2.79866667e-01]
 [6.67100000e-01]
 [7.40466667e-01]
 [6.19600000e-01]
 [5.03100000e-01]
 [1.34666667e-02]
 [3.42366667e-01]
 [8.34100000e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.50600000e-01]
 [9.28233333e-01]
 [9.34933333e-01]
 [9.27933333e-01]
 [0.00000000e+00]
 [1.81666667e-02]
 [3.80700000e-01]
 [8.66833333e-01]
 [9.74500000e-01]
 [9.95466667e-01]
 [9.95433333e-01]
 [9.94366667e-01]
 [9.85700000e-01]
 [9.95466667e-01]
 [9.61066667e-01]
 [8.29166667e-01]
 [5.44333333e-01]
 [1.08133333e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.35666667e-02]
 [3.43266667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [0.00000000e+00]
 [6.71400000e-01]
 [7.48566667e-01]
 [8.18700000e-01]
 [0.00000000e+00]
 [1.19666667e-02]
 [3.10700000e-01]
 [7.17966667e-01]
 [7.62200000e-01]
 [7.96900000e-01]
 [8.68333333e-01]
 [4.08833333e-01]
 [9.03766667e-01]
 [9.83200000e-01]
 [8.85433333e-01]
 [9.61066667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.73033333e-01]
 [2.57900000e-01]
 [0.00000000e+00]
 [2.89000000e-02]
 [4.12033333e-01]
 [8.97266667e-01]
 [8.66900000e-01]
 [9.58300000e-01]
 [9.71333333e-01]
 [9.74766667e-01]
 [3.83966667e-01]
 [1.00000000e+00]
 [9.84066667e-01]
 [9.95766667e-01]
 [9.31033333e-01]
 [8.86033333e-01]
 [7.33966667e-01]
 [2.35400000e-01]
 [6.50000000e-03]
 [0.00000000e+00]
 [9.78233333e-01]
 [9.71066667e-01]
 [9.53666667e-01]
 [9.46333333e-01]
 [9.36966667e-01]
 [9.04700000e-01]
 [7.61466667e-01]
 [2.68533333e-01]
 [0.00000000e+00]
 [3.40333333e-02]
 [4.63500000e-01]
 [8.89200000e-01]
 [9.82566667e-01]
 [9.59700000e-01]
 [9.80800000e-01]
 [9.82000000e-01]
 [9.54566667e-01]
 [9.52566667e-01]
 [9.41300000e-01]
 [9.06166667e-01]
 [7.84833333e-01]
 [2.75000000e-01]
 [4.23333333e-03]
 [7.73100000e-01]
 [2.98533333e-01]
 [7.50133333e-01]
 [7.21133333e-01]
 [9.18133333e-01]
 [8.82033333e-01]
 [7.18600000e-01]
 [0.00000000e+00]
 [4.49666667e-02]
 [3.75833333e-01]
 [4.69800000e-01]
 [8.15366667e-01]
 [7.69533333e-01]
 [5.74900000e-01]
 [2.20233333e-01]
 [7.80000000e-03]
 [8.33833333e-01]
 [8.10266667e-01]
 [7.64966667e-01]
 [7.18600000e-01]
 [6.52300000e-01]
 [8.11933333e-01]
 [7.42666667e-01]
 [8.09866667e-01]
 [8.51300000e-01]
 [7.18600000e-01]
 [2.86200000e-01]
 [6.63266667e-01]
 [7.26833333e-01]
 [0.00000000e+00]
 [4.39333333e-02]
 [9.34366667e-01]
 [8.39366667e-01]
 [8.33833333e-01]
 [6.33700000e-01]
 [5.11333333e-01]
 [6.46766667e-01]
 [2.46333333e-01]
 [9.73333333e-03]
 [0.00000000e+00]
 [5.05666667e-02]
 [4.22800000e-01]
 [9.33733333e-01]
 [8.33833333e-01]
 [8.09866667e-01]
 [8.72800000e-01]
 [7.55366667e-01]
 [3.07166667e-01]
 [0.00000000e+00]
 [5.62000000e-02]
 [4.92866667e-01]
 [8.57133333e-01]
 [0.00000000e+00]
 [4.87666667e-02]
 [4.49533333e-01]
 [7.76633333e-01]
 [7.42200000e-01]
 [6.29900000e-01]
 [5.10000000e-01]
 [5.07933333e-01]
 [2.18966667e-01]
 [0.00000000e+00]
 [5.62000000e-02]
 [4.69900000e-01]
 [8.15366667e-01]
 [8.33833333e-01]
 [7.61866667e-01]
 [9.10933333e-01]
 [6.93933333e-01]
 [0.00000000e+00]
 [5.84000000e-02]
 [4.83633333e-01]
 [8.53433333e-01]
 [9.02733333e-01]
 [9.26466667e-01]
 [8.09866667e-01]
 [8.49966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [4.55333333e-02]
 [4.11600000e-01]
 [7.75266667e-01]
 [8.73566667e-01]
 [8.55633333e-01]
 [9.04733333e-01]
 [7.97366667e-01]
 [2.79900000e-01]
 [8.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.65000000e-02]
 [4.80066667e-01]
 [8.19733333e-01]
 [9.00233333e-01]
 [4.95533333e-01]
 [8.28300000e-01]
 [9.11866667e-01]
 [5.01233333e-01]
 [8.22900000e-01]
 [9.08266667e-01]
 [8.54666667e-01]
 [2.82700000e-01]
 [0.00000000e+00]
 [7.07333333e-02]
 [4.56866667e-01]
 [6.93166667e-01]
 [8.64733333e-01]
 [7.58300000e-01]
 [7.37733333e-01]
 [6.49833333e-01]
 [0.00000000e+00]
 [8.30000000e-01]
 [8.98300000e-01]
 [8.99866667e-01]
 [8.53966667e-01]
 [7.22833333e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [4.69800000e-01]
 [8.15366667e-01]
 [8.99866667e-01]
 [8.57966667e-01]
 [7.18600000e-01]
 [2.73700000e-01]
 [0.00000000e+00]
 [8.82333333e-02]
 [4.69800000e-01]
 [8.30000000e-01]
 [8.09866667e-01]
 [7.72500000e-01]
 [6.46766667e-01]
 [2.47566667e-01]
 [4.88033333e-01]
 [8.48166667e-01]
 [9.34533333e-01]
 [0.00000000e+00]
 [5.83333333e-02]
 [4.95000000e-01]
 [8.62800000e-01]
 [9.31033333e-01]
 [9.62400000e-01]
 [9.08200000e-01]
 [8.59200000e-01]
 [7.24766667e-01]
 [5.02466667e-01]
 [8.75933333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.13000000e-02]
 [4.96666667e-01]
 [8.77200000e-01]
 [0.00000000e+00]
 [7.08666667e-02]
 [5.71066667e-01]
 [8.96300000e-01]
 [9.57033333e-01]
 [8.80700000e-01]
 [0.00000000e+00]
 [7.96333333e-02]
 [5.60133333e-01]
 [8.67366667e-01]
 [9.44466667e-01]
 [8.92933333e-01]
 [7.68000000e-01]
 [3.49533333e-01]
 [5.66833333e-01]
 [8.46533333e-01]
 [9.11033333e-01]
 [8.20800000e-01]
 [7.88566667e-01]
 [6.89433333e-01]
 [4.25033333e-01]
 [6.58966667e-01]
 [7.28800000e-01]
 [8.51266667e-01]
 [0.00000000e+00]
 [1.05133333e-01]
 [5.73300000e-01]
 [8.67300000e-01]
 [0.00000000e+00]
 [9.30000000e-02]
 [5.36466667e-01]
 [8.44133333e-01]
 [9.30800000e-01]
 [7.29600000e-01]
 [8.09333333e-01]
 [7.88033333e-01]
 [4.05066667e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.16633333e-01]
 [8.24300000e-01]
 [9.24100000e-01]
 [8.66766667e-01]
 [7.66066667e-01]
 [8.51000000e-02]
 [5.16633333e-01]
 [8.23700000e-01]
 [9.19266667e-01]
 [8.66766667e-01]
 [5.16633333e-01]
 [8.27433333e-01]
 [4.55633333e-01]
 [7.05200000e-01]
 [7.59600000e-01]
 [5.74433333e-01]
 [8.71966667e-01]
 [5.65000000e-01]
 [8.78500000e-01]
 [9.49500000e-01]
 [5.86000000e-01]
 [8.67033333e-01]
 [9.37566667e-01]
 [8.47733333e-01]
 [9.34900000e-01]
 [5.64833333e-01]
 [8.47533333e-01]
 [9.33066667e-01]
 [7.46966667e-01]
 [8.31900000e-01]
 [8.23700000e-01]
 [9.15200000e-01]
 [8.24766667e-01]
 [9.15400000e-01]
 [5.28400000e-01]
 [8.30066667e-01]
 [9.18766667e-01]
 [0.00000000e+00]
 [8.09666667e-02]
 [5.16633333e-01]
 [8.23700000e-01]
 [9.16233333e-01]
 [9.12000000e-01]
 [8.66766667e-01]
 [7.73366667e-01]
 [0.00000000e+00]
 [8.12666667e-02]
 [5.11733333e-01]
 [8.20866667e-01]
 [9.30666667e-01]
 [8.93433333e-01]
 [3.78000000e-01]
 [8.93500000e-01]
 [8.97400000e-01]
 [2.55333333e-02]
 [0.00000000e+00]
 [8.94266667e-01]
 [9.24766667e-01]
 [4.08566667e-01]
 [7.90500000e-01]
 [9.00666667e-01]
 [9.21966667e-01]
 [9.22366667e-01]
 [9.21966667e-01]
 [0.00000000e+00]
 [8.86833333e-01]
 [9.21966667e-01]
 [8.87600000e-01]
 [9.21966667e-01]
 [9.22933333e-01]
 [7.97200000e-01]
 [8.82066667e-01]
 [9.50000000e-01]
 [9.77966667e-01]
 [9.96500000e-01]
 [9.96033333e-01]
 [3.46566667e-01]
 [7.90066667e-01]
 [8.84333333e-01]
 [9.21966667e-01]
 [8.81166667e-01]
 [9.68466667e-01]
 [8.81166667e-01]
 [7.76066667e-01]
 [6.06900000e-01]
 [9.00300000e-01]
 [8.30633333e-01]
 [9.10633333e-01]
 [9.03566667e-01]
 [7.19333333e-02]
 [8.91366667e-01]
 [5.71333333e-02]
 [8.74633333e-01]
 [2.43400000e-01]
 [6.00466667e-01]
 [7.67000000e-01]
 [8.71866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]]
(396, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
13956    0.995467
13960    0.969367
13961    0.955300
13962    0.880333
13963    0.572167
...           ...
18250    0.600467
18251    0.767000
18252    0.871867
18285    0.000000
18286    0.000000

[396 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.56786811]
 [0.91746284]
 [0.88435067]
 ...
 [0.87186667]
 [0.        ]
 [0.        ]]
(2639, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
35       0.567868
36       0.917463
227      0.884351
228      0.965894
275      0.903397
...           ...
18250    0.600467
18251    0.767000
18252    0.871867
18285    0.000000
18286    0.000000

[2639 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000397 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 696
[LightGBM] [Info] Number of data points in the train set: 1847, number of used features: 8
[LightGBM] [Info] Start training from score 0.454230
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
13956  29802.736495
13960   29095.19111
13961  29136.770699
13962  28333.916793
13963  18488.082907
...             ...
18250  21351.153925
18251  22831.557606
18252  24912.539517
18285           0.0
18286           0.0

[396 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
13956     29864.0
13960     29081.0
13961     28659.0
13962     26410.0
13963     17165.0
...           ...
18250     18014.0
18251     23010.0
18252     26156.0
18285         0.0
18286         0.0

[396 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
13956     29864.0  29802.736495
13960     29081.0   29095.19111
13961     28659.0  29136.770699
13962     26410.0  28333.916793
13963     17165.0  18488.082907
...           ...           ...
18250     18014.0  21351.153925
18251     23010.0  22831.557606
18252     26156.0  24912.539517
18285         0.0           0.0
18286         0.0           0.0

[396 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1180.6107
RMSE: 1838.9254
R²: 0.9682

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
13956     29864.0  29802.736495      29306.46
13960     29081.0   29095.19111    29272.7725
13961     28659.0  29136.770699     29224.675
13962     26410.0  28333.916793     28923.955
13963     17165.0  18488.082907      20188.37
...           ...           ...           ...
18250     18014.0  21351.153925      20554.05
18251     23010.0  22831.557606  24302.920607
18252     26156.0  24912.539517  25643.327875
18285         0.0           0.0           0.0
18286         0.0           0.0           0.0

[396 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (1799, 48, 9), y_train: (1799, 1)
X_val: (348, 48, 9), y_val: (348, 1)
X_test: (348, 48, 9), y_test: (348, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 56s 2s/step - loss: 0.3589 - mean_absolute_error: 0.4593 - mean_absolute_percentage_error: 164553.2500 - root_mean_squared_error: 0.5991 - val_loss: 0.3000 - val_mean_absolute_error: 0.4022 - val_mean_absolute_percentage_error: 1593694.6250 - val_root_mean_squared_error: 0.5477
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 804ms/step - loss: 0.3572 - mean_absolute_error: 0.4576 - mean_absolute_percentage_error: 1157786.2500 - root_mean_squared_error: 0.5977 - val_loss: 0.2955 - val_mean_absolute_error: 0.4007 - val_mean_absolute_percentage_error: 3351443.2500 - val_root_mean_squared_error: 0.5436
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 427ms/step - loss: 0.3476 - mean_absolute_error: 0.4508 - mean_absolute_percentage_error: 2253094.5000 - root_mean_squared_error: 0.5895 - val_loss: 0.2906 - val_mean_absolute_error: 0.3991 - val_mean_absolute_percentage_error: 5255581.0000 - val_root_mean_squared_error: 0.5391
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 479ms/step - loss: 0.3401 - mean_absolute_error: 0.4465 - mean_absolute_percentage_error: 3502333.5000 - root_mean_squared_error: 0.5831 - val_loss: 0.2854 - val_mean_absolute_error: 0.3974 - val_mean_absolute_percentage_error: 7323240.0000 - val_root_mean_squared_error: 0.5343
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - loss: 0.3397 - mean_absolute_error: 0.4492 - mean_absolute_percentage_error: 4705010.5000 - root_mean_squared_error: 0.5828 - val_loss: 0.2798 - val_mean_absolute_error: 0.3956 - val_mean_absolute_percentage_error: 9587677.0000 - val_root_mean_squared_error: 0.5290
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.3394 - mean_absolute_error: 0.4512 - mean_absolute_percentage_error: 6047704.5000 - root_mean_squared_error: 0.5826 - val_loss: 0.2737 - val_mean_absolute_error: 0.3937 - val_mean_absolute_percentage_error: 12119535.0000 - val_root_mean_squared_error: 0.5232
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.3264 - mean_absolute_error: 0.4426 - mean_absolute_percentage_error: 7638386.0000 - root_mean_squared_error: 0.5713 - val_loss: 0.2671 - val_mean_absolute_error: 0.3916 - val_mean_absolute_percentage_error: 14958519.0000 - val_root_mean_squared_error: 0.5168
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 3s/step - loss: 0.3212 - mean_absolute_error: 0.4414 - mean_absolute_percentage_error: 9382270.0000 - root_mean_squared_error: 0.5668 - val_loss: 0.2597 - val_mean_absolute_error: 0.3892 - val_mean_absolute_percentage_error: 18193228.0000 - val_root_mean_squared_error: 0.5096
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.3088 - mean_absolute_error: 0.4314 - mean_absolute_percentage_error: 11680778.0000 - root_mean_squared_error: 0.5557 - val_loss: 0.2515 - val_mean_absolute_error: 0.3865 - val_mean_absolute_percentage_error: 21869858.0000 - val_root_mean_squared_error: 0.5015
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 3s/step - loss: 0.2973 - mean_absolute_error: 0.4240 - mean_absolute_percentage_error: 13366954.0000 - root_mean_squared_error: 0.5452 - val_loss: 0.2426 - val_mean_absolute_error: 0.3835 - val_mean_absolute_percentage_error: 26050048.0000 - val_root_mean_squared_error: 0.4926
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 12s 3s/step - loss: 0.2931 - mean_absolute_error: 0.4250 - mean_absolute_percentage_error: 16471843.0000 - root_mean_squared_error: 0.5414 - val_loss: 0.2329 - val_mean_absolute_error: 0.3802 - val_mean_absolute_percentage_error: 30813002.0000 - val_root_mean_squared_error: 0.4826
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 5s/step - loss: 0.2812 - mean_absolute_error: 0.4179 - mean_absolute_percentage_error: 18524106.0000 - root_mean_squared_error: 0.5303 - val_loss: 0.2225 - val_mean_absolute_error: 0.3765 - val_mean_absolute_percentage_error: 36229272.0000 - val_root_mean_squared_error: 0.4717
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 694ms/step - loss: 0.2673 - mean_absolute_error: 0.4104 - mean_absolute_percentage_error: 23580620.0000 - root_mean_squared_error: 0.5170 - val_loss: 0.2114 - val_mean_absolute_error: 0.3725 - val_mean_absolute_percentage_error: 42387600.0000 - val_root_mean_squared_error: 0.4598
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 2s/step - loss: 0.2558 - mean_absolute_error: 0.4063 - mean_absolute_percentage_error: 27236386.0000 - root_mean_squared_error: 0.5058 - val_loss: 0.1998 - val_mean_absolute_error: 0.3684 - val_mean_absolute_percentage_error: 49378236.0000 - val_root_mean_squared_error: 0.4469
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 3s/step - loss: 0.2391 - mean_absolute_error: 0.3950 - mean_absolute_percentage_error: 29117392.0000 - root_mean_squared_error: 0.4890 - val_loss: 0.1879 - val_mean_absolute_error: 0.3644 - val_mean_absolute_percentage_error: 57267716.0000 - val_root_mean_squared_error: 0.4335
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 3s/step - loss: 0.2253 - mean_absolute_error: 0.3900 - mean_absolute_percentage_error: 36169492.0000 - root_mean_squared_error: 0.4746 - val_loss: 0.1762 - val_mean_absolute_error: 0.3602 - val_mean_absolute_percentage_error: 66098568.0000 - val_root_mean_squared_error: 0.4197
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.2053 - mean_absolute_error: 0.3764 - mean_absolute_percentage_error: 40703224.0000 - root_mean_squared_error: 0.4531 - val_loss: 0.1652 - val_mean_absolute_error: 0.3558 - val_mean_absolute_percentage_error: 75900800.0000 - val_root_mean_squared_error: 0.4064
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 4s/step - loss: 0.1967 - mean_absolute_error: 0.3774 - mean_absolute_percentage_error: 48710480.0000 - root_mean_squared_error: 0.4434 - val_loss: 0.1554 - val_mean_absolute_error: 0.3523 - val_mean_absolute_percentage_error: 86693296.0000 - val_root_mean_squared_error: 0.3942
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 12s 3s/step - loss: 0.1814 - mean_absolute_error: 0.3684 - mean_absolute_percentage_error: 53327776.0000 - root_mean_squared_error: 0.4259 - val_loss: 0.1477 - val_mean_absolute_error: 0.3517 - val_mean_absolute_percentage_error: 98283976.0000 - val_root_mean_squared_error: 0.3843
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 3s/step - loss: 0.1707 - mean_absolute_error: 0.3630 - mean_absolute_percentage_error: 58903756.0000 - root_mean_squared_error: 0.4131 - val_loss: 0.1427 - val_mean_absolute_error: 0.3520 - val_mean_absolute_percentage_error: 110379328.0000 - val_root_mean_squared_error: 0.3778
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 10s 2s/step - loss: 0.1611 - mean_absolute_error: 0.3594 - mean_absolute_percentage_error: 68975608.0000 - root_mean_squared_error: 0.4013 - val_loss: 0.1409 - val_mean_absolute_error: 0.3530 - val_mean_absolute_percentage_error: 122390312.0000 - val_root_mean_squared_error: 0.3754
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 3s/step - loss: 0.1536 - mean_absolute_error: 0.3551 - mean_absolute_percentage_error: 77536280.0000 - root_mean_squared_error: 0.3919 - val_loss: 0.1420 - val_mean_absolute_error: 0.3544 - val_mean_absolute_percentage_error: 133555200.0000 - val_root_mean_squared_error: 0.3768
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 12s 3s/step - loss: 0.1569 - mean_absolute_error: 0.3642 - mean_absolute_percentage_error: 84682480.0000 - root_mean_squared_error: 0.3961 - val_loss: 0.1449 - val_mean_absolute_error: 0.3560 - val_mean_absolute_percentage_error: 142877936.0000 - val_root_mean_squared_error: 0.3806
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 4s/step - loss: 0.1541 - mean_absolute_error: 0.3602 - mean_absolute_percentage_error: 86357144.0000 - root_mean_squared_error: 0.3926 - val_loss: 0.1479 - val_mean_absolute_error: 0.3574 - val_mean_absolute_percentage_error: 149096320.0000 - val_root_mean_squared_error: 0.3845
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 10s 3s/step - loss: 0.1545 - mean_absolute_error: 0.3606 - mean_absolute_percentage_error: 90745872.0000 - root_mean_squared_error: 0.3930 - val_loss: 0.1493 - val_mean_absolute_error: 0.3579 - val_mean_absolute_percentage_error: 151634176.0000 - val_root_mean_squared_error: 0.3864
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 4s/step - loss: 0.1557 - mean_absolute_error: 0.3621 - mean_absolute_percentage_error: 93687320.0000 - root_mean_squared_error: 0.3946 - val_loss: 0.1488 - val_mean_absolute_error: 0.3577 - val_mean_absolute_percentage_error: 150945104.0000 - val_root_mean_squared_error: 0.3858
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 4s/step - loss: 0.1580 - mean_absolute_error: 0.3653 - mean_absolute_percentage_error: 92188024.0000 - root_mean_squared_error: 0.3975 - val_loss: 0.1470 - val_mean_absolute_error: 0.3569 - val_mean_absolute_percentage_error: 147764496.0000 - val_root_mean_squared_error: 0.3834
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1513 - mean_absolute_error: 0.3554 - mean_absolute_percentage_error: 86971384.0000 - root_mean_squared_error: 0.3890 - val_loss: 0.1448 - val_mean_absolute_error: 0.3558 - val_mean_absolute_percentage_error: 143301408.0000 - val_root_mean_squared_error: 0.3805
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 3s/step - loss: 0.1522 - mean_absolute_error: 0.3558 - mean_absolute_percentage_error: 87656288.0000 - root_mean_squared_error: 0.3901 - val_loss: 0.1430 - val_mean_absolute_error: 0.3549 - val_mean_absolute_percentage_error: 138817648.0000 - val_root_mean_squared_error: 0.3781
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1483 - mean_absolute_error: 0.3509 - mean_absolute_percentage_error: 82784128.0000 - root_mean_squared_error: 0.3851 - val_loss: 0.1419 - val_mean_absolute_error: 0.3543 - val_mean_absolute_percentage_error: 135345680.0000 - val_root_mean_squared_error: 0.3767
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.1515 - mean_absolute_error: 0.3561 - mean_absolute_percentage_error: 82007512.0000 - root_mean_squared_error: 0.3892 - val_loss: 0.1412 - val_mean_absolute_error: 0.3538 - val_mean_absolute_percentage_error: 132783864.0000 - val_root_mean_squared_error: 0.3757
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1514 - mean_absolute_error: 0.3543 - mean_absolute_percentage_error: 81279856.0000 - root_mean_squared_error: 0.3890 - val_loss: 0.1407 - val_mean_absolute_error: 0.3535 - val_mean_absolute_percentage_error: 130980888.0000 - val_root_mean_squared_error: 0.3751
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - loss: 0.1487 - mean_absolute_error: 0.3502 - mean_absolute_percentage_error: 78348720.0000 - root_mean_squared_error: 0.3856 - val_loss: 0.1405 - val_mean_absolute_error: 0.3534 - val_mean_absolute_percentage_error: 130649472.0000 - val_root_mean_squared_error: 0.3748
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 10s 3s/step - loss: 0.1486 - mean_absolute_error: 0.3509 - mean_absolute_percentage_error: 79984104.0000 - root_mean_squared_error: 0.3855 - val_loss: 0.1404 - val_mean_absolute_error: 0.3534 - val_mean_absolute_percentage_error: 131092800.0000 - val_root_mean_squared_error: 0.3747
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.1473 - mean_absolute_error: 0.3507 - mean_absolute_percentage_error: 84321160.0000 - root_mean_squared_error: 0.3838 - val_loss: 0.1403 - val_mean_absolute_error: 0.3534 - val_mean_absolute_percentage_error: 131713744.0000 - val_root_mean_squared_error: 0.3746
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 3s/step - loss: 0.1479 - mean_absolute_error: 0.3500 - mean_absolute_percentage_error: 75536736.0000 - root_mean_squared_error: 0.3845 - val_loss: 0.1404 - val_mean_absolute_error: 0.3534 - val_mean_absolute_percentage_error: 133023904.0000 - val_root_mean_squared_error: 0.3747
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 808ms/step - loss: 0.1466 - mean_absolute_error: 0.3489 - mean_absolute_percentage_error: 79573784.0000 - root_mean_squared_error: 0.3828 - val_loss: 0.1403 - val_mean_absolute_error: 0.3534 - val_mean_absolute_percentage_error: 133803512.0000 - val_root_mean_squared_error: 0.3746
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1460 - mean_absolute_error: 0.3471 - mean_absolute_percentage_error: 81168384.0000 - root_mean_squared_error: 0.3821 - val_loss: 0.1400 - val_mean_absolute_error: 0.3532 - val_mean_absolute_percentage_error: 133564064.0000 - val_root_mean_squared_error: 0.3742
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 10s 3s/step - loss: 0.1417 - mean_absolute_error: 0.3423 - mean_absolute_percentage_error: 82644688.0000 - root_mean_squared_error: 0.3764 - val_loss: 0.1396 - val_mean_absolute_error: 0.3530 - val_mean_absolute_percentage_error: 132968936.0000 - val_root_mean_squared_error: 0.3737
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 12s 3s/step - loss: 0.1410 - mean_absolute_error: 0.3405 - mean_absolute_percentage_error: 78185856.0000 - root_mean_squared_error: 0.3754 - val_loss: 0.1393 - val_mean_absolute_error: 0.3528 - val_mean_absolute_percentage_error: 132420992.0000 - val_root_mean_squared_error: 0.3732
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.1420 - mean_absolute_error: 0.3422 - mean_absolute_percentage_error: 80860528.0000 - root_mean_squared_error: 0.3768 - val_loss: 0.1387 - val_mean_absolute_error: 0.3524 - val_mean_absolute_percentage_error: 130755480.0000 - val_root_mean_squared_error: 0.3724
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1366 - mean_absolute_error: 0.3332 - mean_absolute_percentage_error: 81099368.0000 - root_mean_squared_error: 0.3696 - val_loss: 0.1382 - val_mean_absolute_error: 0.3521 - val_mean_absolute_percentage_error: 129385696.0000 - val_root_mean_squared_error: 0.3718
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.1390 - mean_absolute_error: 0.3368 - mean_absolute_percentage_error: 78427240.0000 - root_mean_squared_error: 0.3728 - val_loss: 0.1379 - val_mean_absolute_error: 0.3518 - val_mean_absolute_percentage_error: 128956144.0000 - val_root_mean_squared_error: 0.3713
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 6s 2s/step - loss: 0.1358 - mean_absolute_error: 0.3321 - mean_absolute_percentage_error: 81665840.0000 - root_mean_squared_error: 0.3684 - val_loss: 0.1375 - val_mean_absolute_error: 0.3515 - val_mean_absolute_percentage_error: 128061656.0000 - val_root_mean_squared_error: 0.3708
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 7s 2s/step - loss: 0.1356 - mean_absolute_error: 0.3314 - mean_absolute_percentage_error: 85057952.0000 - root_mean_squared_error: 0.3682 - val_loss: 0.1371 - val_mean_absolute_error: 0.3512 - val_mean_absolute_percentage_error: 126518320.0000 - val_root_mean_squared_error: 0.3703
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 4s/step - loss: 0.1300 - mean_absolute_error: 0.3227 - mean_absolute_percentage_error: 75150176.0000 - root_mean_squared_error: 0.3605 - val_loss: 0.1368 - val_mean_absolute_error: 0.3508 - val_mean_absolute_percentage_error: 125922944.0000 - val_root_mean_squared_error: 0.3699
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 3s/step - loss: 0.1266 - mean_absolute_error: 0.3163 - mean_absolute_percentage_error: 78222784.0000 - root_mean_squared_error: 0.3558 - val_loss: 0.1366 - val_mean_absolute_error: 0.3505 - val_mean_absolute_percentage_error: 124517136.0000 - val_root_mean_squared_error: 0.3696
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 3s/step - loss: 0.1298 - mean_absolute_error: 0.3230 - mean_absolute_percentage_error: 82036128.0000 - root_mean_squared_error: 0.3602 - val_loss: 0.1363 - val_mean_absolute_error: 0.3502 - val_mean_absolute_percentage_error: 122012744.0000 - val_root_mean_squared_error: 0.3693
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.1272 - mean_absolute_error: 0.3166 - mean_absolute_percentage_error: 74209152.0000 - root_mean_squared_error: 0.3566 - val_loss: 0.1363 - val_mean_absolute_error: 0.3499 - val_mean_absolute_percentage_error: 121016000.0000 - val_root_mean_squared_error: 0.3691
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1253 - mean_absolute_error: 0.3115 - mean_absolute_percentage_error: 72770224.0000 - root_mean_squared_error: 0.3540 - val_loss: 0.1362 - val_mean_absolute_error: 0.3497 - val_mean_absolute_percentage_error: 117947344.0000 - val_root_mean_squared_error: 0.3691

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

11/11 ━━━━━━━━━━━━━━━━━━━━ 6s 313ms/step

array([[0.6225866 ],
       [0.6233591 ],
       [0.62186766],
       [0.6111368 ],
       [0.6027219 ],
       [0.5947629 ],
       [0.5947823 ],
       [0.60276794],
       [0.6079874 ],
       [0.6095917 ],
       [0.6050049 ],
       [0.6135638 ],
       [0.619771  ],
       [0.62020206],
       [0.6221294 ],
       [0.6245698 ],
       [0.6250838 ],
       [0.6237534 ],
       [0.6192645 ],
       [0.6125192 ],
       [0.6021797 ],
       [0.593387  ],
       [0.59552056],
       [0.5996876 ],
       [0.6002264 ],
       [0.60282457],
       [0.61459076],
       [0.60892594],
       [0.60789967],
       [0.6073985 ],
       [0.6086134 ],
       [0.60723835],
       [0.60607016],
       [0.6013486 ],
       [0.59059244],
       [0.5723063 ],
       [0.5556365 ],
       [0.5594185 ],
       [0.56825876],
       [0.5832755 ],
       [0.60320747],
       [0.61356807],
       [0.6208199 ],
       [0.6212069 ],
       [0.61301637],
       [0.6066049 ],
       [0.603166  ],
       [0.6104226 ],
       [0.61532193],
       [0.6131937 ],
       [0.61672986],
       [0.6267716 ],
       [0.63075435],
       [0.6312569 ],
       [0.63008916],
       [0.6291064 ],
       [0.6277312 ],
       [0.6265566 ],
       [0.62157106],
       [0.61147916],
       [0.61024606],
       [0.6031686 ],
       [0.6049199 ],
       [0.6062143 ],
       [0.60700375],
       [0.60861385],
       [0.6113503 ],
       [0.61342824],
       [0.6153933 ],
       [0.6182531 ],
       [0.6155191 ],
       [0.61885345],
       [0.616598  ],
       [0.6107534 ],
       [0.604429  ],
       [0.5954261 ],
       [0.5974515 ],
       [0.5963624 ],
       [0.59357697],
       [0.59321976],
       [0.5914135 ],
       [0.5963959 ],
       [0.6057919 ],
       [0.6154491 ],
       [0.6203321 ],
       [0.61959064],
       [0.6132608 ],
       [0.61263436],
       [0.6120918 ],
       [0.60365057],
       [0.5988258 ],
       [0.60518706],
       [0.61164516],
       [0.61666983],
       [0.61926126],
       [0.6162272 ],
       [0.6112998 ],
       [0.6020603 ],
       [0.59267163],
       [0.58481526],
       [0.57458043],
       [0.56964236],
       [0.5753865 ],
       [0.5734749 ],
       [0.57350117],
       [0.57735026],
       [0.5871122 ],
       [0.5910929 ],
       [0.5812671 ],
       [0.57376015],
       [0.5672752 ],
       [0.5725089 ],
       [0.554573  ],
       [0.5446724 ],
       [0.54352015],
       [0.56020814],
       [0.5694209 ],
       [0.5705464 ],
       [0.5733991 ],
       [0.5689695 ],
       [0.5624028 ],
       [0.55247873],
       [0.55128974],
       [0.5552865 ],
       [0.5596461 ],
       [0.5626875 ],
       [0.564588  ],
       [0.5673245 ],
       [0.56848466],
       [0.5521954 ],
       [0.53869605],
       [0.53144294],
       [0.5336245 ],
       [0.5417065 ],
       [0.5458904 ],
       [0.55037844],
       [0.5536236 ],
       [0.5480285 ],
       [0.544091  ],
       [0.5324471 ],
       [0.535537  ],
       [0.53250515],
       [0.5361453 ],
       [0.53973794],
       [0.5453106 ],
       [0.5494925 ],
       [0.5523492 ],
       [0.54994774],
       [0.54279226],
       [0.53767204],
       [0.5294229 ],
       [0.5311187 ],
       [0.5333247 ],
       [0.5433537 ],
       [0.5377062 ],
       [0.545484  ],
       [0.55854917],
       [0.56198823],
       [0.5669894 ],
       [0.57218903],
       [0.58359134],
       [0.5855478 ],
       [0.5739573 ],
       [0.5633533 ],
       [0.5560292 ],
       [0.5574914 ],
       [0.562592  ],
       [0.57085943],
       [0.578297  ],
       [0.587448  ],
       [0.58439505],
       [0.58476055],
       [0.58494186],
       [0.5796862 ],
       [0.5789982 ],
       [0.5763217 ],
       [0.56542945],
       [0.56382173],
       [0.5689288 ],
       [0.57509017],
       [0.5762327 ],
       [0.5752175 ],
       [0.57508326],
       [0.56804013],
       [0.5561767 ],
       [0.55547935],
       [0.5595875 ],
       [0.5666984 ],
       [0.5733212 ],
       [0.57490015],
       [0.5730003 ],
       [0.5646402 ],
       [0.55616   ],
       [0.5591586 ],
       [0.56987727],
       [0.56833005],
       [0.5670083 ],
       [0.5716249 ],
       [0.57729554],
       [0.5782577 ],
       [0.5784249 ],
       [0.5778191 ],
       [0.5817661 ],
       [0.5784109 ],
       [0.5721264 ],
       [0.5770005 ],
       [0.5592231 ],
       [0.54422396],
       [0.53444356],
       [0.5364877 ],
       [0.554421  ],
       [0.551497  ],
       [0.5443406 ],
       [0.5382921 ],
       [0.53755707],
       [0.5369829 ],
       [0.53910035],
       [0.5339384 ],
       [0.5306728 ],
       [0.5278958 ],
       [0.5311382 ],
       [0.5318259 ],
       [0.5343611 ],
       [0.5404868 ],
       [0.5472652 ],
       [0.5477317 ],
       [0.55199575],
       [0.5586713 ],
       [0.5627078 ],
       [0.56267464],
       [0.56432354],
       [0.5656103 ],
       [0.57948005],
       [0.5913083 ],
       [0.59512997],
       [0.58470184],
       [0.57110333],
       [0.5663049 ],
       [0.5721971 ],
       [0.5639787 ],
       [0.55716646],
       [0.5553165 ],
       [0.56205213],
       [0.57700837],
       [0.59156805],
       [0.5976559 ],
       [0.59424984],
       [0.5876785 ],
       [0.57356286],
       [0.56323355],
       [0.5617744 ],
       [0.5681236 ],
       [0.5730103 ],
       [0.5758903 ],
       [0.5847573 ],
       [0.5842416 ],
       [0.58875626],
       [0.5945238 ],
       [0.60031396],
       [0.60981774],
       [0.61190456],
       [0.6155721 ],
       [0.6127689 ],
       [0.6149427 ],
       [0.61777663],
       [0.62058157],
       [0.62723446],
       [0.6267847 ],
       [0.6293123 ],
       [0.6302918 ],
       [0.6276419 ],
       [0.63134956],
       [0.6352242 ],
       [0.6371043 ],
       [0.6382127 ],
       [0.6356621 ],
       [0.63702327],
       [0.63869584],
       [0.6368508 ],
       [0.6393254 ],
       [0.63999164],
       [0.64062953],
       [0.6415353 ],
       [0.6473316 ],
       [0.6477992 ],
       [0.6500989 ],
       [0.6523652 ],
       [0.6508173 ],
       [0.64923257],
       [0.6476877 ],
       [0.64844316],
       [0.6487539 ],
       [0.64904237],
       [0.6509156 ],
       [0.6517494 ],
       [0.6491691 ],
       [0.64866984],
       [0.65037656],
       [0.6522542 ],
       [0.65313846],
       [0.6548711 ],
       [0.65665436],
       [0.6593669 ],
       [0.66092336],
       [0.6531722 ],
       [0.64507425],
       [0.6459175 ],
       [0.6472057 ],
       [0.64707285],
       [0.64736485],
       [0.65042186],
       [0.65232   ],
       [0.6506958 ],
       [0.6516878 ],
       [0.64047873],
       [0.6432439 ],
       [0.642189  ],
       [0.6413616 ],
       [0.6438111 ],
       [0.6446959 ],
       [0.64659905],
       [0.6453257 ],
       [0.64233255],
       [0.6441322 ],
       [0.64519376],
       [0.64477664],
       [0.6403196 ],
       [0.64188355],
       [0.64320683],
       [0.6432925 ],
       [0.64311546],
       [0.6428566 ],
       [0.64436066],
       [0.6415237 ],
       [0.6372065 ],
       [0.64382684],
       [0.64776224],
       [0.64918256],
       [0.64977276],
       [0.6409209 ],
       [0.64351785],
       [0.6363834 ],
       [0.63881004],
       [0.63704216],
       [0.6390356 ],
       [0.64230746],
       [0.64237285],
       [0.63084364]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
13956     29864.0  29802.736495      29306.46           NaN
13960     29081.0   29095.19111    29272.7725           NaN
13961     28659.0  29136.770699     29224.675           NaN
13962     26410.0  28333.916793     28923.955           NaN
13963     17165.0  18488.082907      20188.37           NaN
...           ...           ...           ...           ...
18250     18014.0  21351.153925      20554.05  19111.265625
18251     23010.0  22831.557606  24302.920607  19171.068359
18252     26156.0  24912.539517  25643.327875  19269.224609
18285         0.0           0.0           0.0  19271.185547
18286         0.0           0.0           0.0  18925.308594

[396 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 58s 6s/step - loss: 0.3495 - mean_absolute_error: 0.4538 - mean_absolute_percentage_error: 2203426.2500 - root_mean_squared_error: 0.5912 - val_loss: 0.2467 - val_mean_absolute_error: 0.3849 - val_mean_absolute_percentage_error: 24101522.0000 - val_root_mean_squared_error: 0.4967
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 4s/step - loss: 0.2783 - mean_absolute_error: 0.4162 - mean_absolute_percentage_error: 19725554.0000 - root_mean_squared_error: 0.5275 - val_loss: 0.1655 - val_mean_absolute_error: 0.3560 - val_mean_absolute_percentage_error: 75683224.0000 - val_root_mean_squared_error: 0.4068
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1848 - mean_absolute_error: 0.3722 - mean_absolute_percentage_error: 55936064.0000 - root_mean_squared_error: 0.4297 - val_loss: 0.1626 - val_mean_absolute_error: 0.3627 - val_mean_absolute_percentage_error: 168309504.0000 - val_root_mean_squared_error: 0.4032
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 3s/step - loss: 0.1683 - mean_absolute_error: 0.3718 - mean_absolute_percentage_error: 106992416.0000 - root_mean_squared_error: 0.4102 - val_loss: 0.1762 - val_mean_absolute_error: 0.3680 - val_mean_absolute_percentage_error: 180884656.0000 - val_root_mean_squared_error: 0.4198
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 12s 3s/step - loss: 0.1638 - mean_absolute_error: 0.3679 - mean_absolute_percentage_error: 102965344.0000 - root_mean_squared_error: 0.4048 - val_loss: 0.1421 - val_mean_absolute_error: 0.3546 - val_mean_absolute_percentage_error: 134947632.0000 - val_root_mean_squared_error: 0.3769
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 3s/step - loss: 0.1495 - mean_absolute_error: 0.3517 - mean_absolute_percentage_error: 80404336.0000 - root_mean_squared_error: 0.3866 - val_loss: 0.1417 - val_mean_absolute_error: 0.3522 - val_mean_absolute_percentage_error: 113455152.0000 - val_root_mean_squared_error: 0.3764
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 5s/step - loss: 0.1568 - mean_absolute_error: 0.3553 - mean_absolute_percentage_error: 68405192.0000 - root_mean_squared_error: 0.3960 - val_loss: 0.1409 - val_mean_absolute_error: 0.3526 - val_mean_absolute_percentage_error: 117867648.0000 - val_root_mean_squared_error: 0.3754
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 22s 4s/step - loss: 0.1564 - mean_absolute_error: 0.3583 - mean_absolute_percentage_error: 72682816.0000 - root_mean_squared_error: 0.3954 - val_loss: 0.1421 - val_mean_absolute_error: 0.3546 - val_mean_absolute_percentage_error: 135174160.0000 - val_root_mean_squared_error: 0.3770
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step - loss: 0.1519 - mean_absolute_error: 0.3573 - mean_absolute_percentage_error: 84371520.0000 - root_mean_squared_error: 0.3897 - val_loss: 0.1480 - val_mean_absolute_error: 0.3574 - val_mean_absolute_percentage_error: 149718272.0000 - val_root_mean_squared_error: 0.3846
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - loss: 0.1482 - mean_absolute_error: 0.3534 - mean_absolute_percentage_error: 91157576.0000 - root_mean_squared_error: 0.3850 - val_loss: 0.1482 - val_mean_absolute_error: 0.3572 - val_mean_absolute_percentage_error: 151249344.0000 - val_root_mean_squared_error: 0.3850
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 17s 4s/step - loss: 0.1453 - mean_absolute_error: 0.3492 - mean_absolute_percentage_error: 87935136.0000 - root_mean_squared_error: 0.3811 - val_loss: 0.1400 - val_mean_absolute_error: 0.3534 - val_mean_absolute_percentage_error: 134619040.0000 - val_root_mean_squared_error: 0.3741
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 4s/step - loss: 0.1427 - mean_absolute_error: 0.3448 - mean_absolute_percentage_error: 77904360.0000 - root_mean_squared_error: 0.3777 - val_loss: 0.1385 - val_mean_absolute_error: 0.3524 - val_mean_absolute_percentage_error: 132952664.0000 - val_root_mean_squared_error: 0.3722
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 3s/step - loss: 0.1352 - mean_absolute_error: 0.3351 - mean_absolute_percentage_error: 82232016.0000 - root_mean_squared_error: 0.3677 - val_loss: 0.1417 - val_mean_absolute_error: 0.3514 - val_mean_absolute_percentage_error: 140753552.0000 - val_root_mean_squared_error: 0.3764
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 7s/step - loss: 0.1342 - mean_absolute_error: 0.3304 - mean_absolute_percentage_error: 85949928.0000 - root_mean_squared_error: 0.3664 - val_loss: 0.1407 - val_mean_absolute_error: 0.3494 - val_mean_absolute_percentage_error: 129589360.0000 - val_root_mean_squared_error: 0.3752
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 14s 5s/step - loss: 0.1269 - mean_absolute_error: 0.3156 - mean_absolute_percentage_error: 76201680.0000 - root_mean_squared_error: 0.3562 - val_loss: 0.1425 - val_mean_absolute_error: 0.3483 - val_mean_absolute_percentage_error: 114073392.0000 - val_root_mean_squared_error: 0.3774
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 6s/step - loss: 0.1219 - mean_absolute_error: 0.3025 - mean_absolute_percentage_error: 72214912.0000 - root_mean_squared_error: 0.3492 - val_loss: 0.1492 - val_mean_absolute_error: 0.3483 - val_mean_absolute_percentage_error: 115829832.0000 - val_root_mean_squared_error: 0.3862
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.1219 - mean_absolute_error: 0.2986 - mean_absolute_percentage_error: 71987104.0000 - root_mean_squared_error: 0.3492 - val_loss: 0.1486 - val_mean_absolute_error: 0.3501 - val_mean_absolute_percentage_error: 94678456.0000 - val_root_mean_squared_error: 0.3855
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 6s/step - loss: 0.1238 - mean_absolute_error: 0.3046 - mean_absolute_percentage_error: 65800908.0000 - root_mean_squared_error: 0.3518 - val_loss: 0.1466 - val_mean_absolute_error: 0.3504 - val_mean_absolute_percentage_error: 92670096.0000 - val_root_mean_squared_error: 0.3829
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 6s/step - loss: 0.1207 - mean_absolute_error: 0.3047 - mean_absolute_percentage_error: 70641592.0000 - root_mean_squared_error: 0.3474 - val_loss: 0.1411 - val_mean_absolute_error: 0.3489 - val_mean_absolute_percentage_error: 100267648.0000 - val_root_mean_squared_error: 0.3756
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step - loss: 0.1196 - mean_absolute_error: 0.3059 - mean_absolute_percentage_error: 74674112.0000 - root_mean_squared_error: 0.3459 - val_loss: 0.1412 - val_mean_absolute_error: 0.3493 - val_mean_absolute_percentage_error: 98500224.0000 - val_root_mean_squared_error: 0.3758
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step - loss: 0.1166 - mean_absolute_error: 0.3009 - mean_absolute_percentage_error: 72333072.0000 - root_mean_squared_error: 0.3414 - val_loss: 0.1383 - val_mean_absolute_error: 0.3484 - val_mean_absolute_percentage_error: 105278360.0000 - val_root_mean_squared_error: 0.3719
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 23s 4s/step - loss: 0.1144 - mean_absolute_error: 0.2936 - mean_absolute_percentage_error: 69678640.0000 - root_mean_squared_error: 0.3382 - val_loss: 0.1383 - val_mean_absolute_error: 0.3479 - val_mean_absolute_percentage_error: 105078576.0000 - val_root_mean_squared_error: 0.3719
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.1132 - mean_absolute_error: 0.2919 - mean_absolute_percentage_error: 68462192.0000 - root_mean_squared_error: 0.3364 - val_loss: 0.1376 - val_mean_absolute_error: 0.3466 - val_mean_absolute_percentage_error: 107133576.0000 - val_root_mean_squared_error: 0.3709
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 5s/step - loss: 0.1121 - mean_absolute_error: 0.2894 - mean_absolute_percentage_error: 68911472.0000 - root_mean_squared_error: 0.3349 - val_loss: 0.1398 - val_mean_absolute_error: 0.3466 - val_mean_absolute_percentage_error: 96658184.0000 - val_root_mean_squared_error: 0.3739
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 5s/step - loss: 0.1103 - mean_absolute_error: 0.2912 - mean_absolute_percentage_error: 61503348.0000 - root_mean_squared_error: 0.3321 - val_loss: 0.1369 - val_mean_absolute_error: 0.3439 - val_mean_absolute_percentage_error: 101985936.0000 - val_root_mean_squared_error: 0.3699
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - loss: 0.1060 - mean_absolute_error: 0.2779 - mean_absolute_percentage_error: 65285376.0000 - root_mean_squared_error: 0.3255 - val_loss: 0.1368 - val_mean_absolute_error: 0.3425 - val_mean_absolute_percentage_error: 100493928.0000 - val_root_mean_squared_error: 0.3699
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 3s/step - loss: 0.1013 - mean_absolute_error: 0.2735 - mean_absolute_percentage_error: 59797736.0000 - root_mean_squared_error: 0.3183 - val_loss: 0.1362 - val_mean_absolute_error: 0.3406 - val_mean_absolute_percentage_error: 100010032.0000 - val_root_mean_squared_error: 0.3690
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 31s 6s/step - loss: 0.0988 - mean_absolute_error: 0.2643 - mean_absolute_percentage_error: 61035192.0000 - root_mean_squared_error: 0.3143 - val_loss: 0.1325 - val_mean_absolute_error: 0.3342 - val_mean_absolute_percentage_error: 107060944.0000 - val_root_mean_squared_error: 0.3639
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 19s 5s/step - loss: 0.0935 - mean_absolute_error: 0.2495 - mean_absolute_percentage_error: 60209224.0000 - root_mean_squared_error: 0.3058 - val_loss: 0.1349 - val_mean_absolute_error: 0.3317 - val_mean_absolute_percentage_error: 95269304.0000 - val_root_mean_squared_error: 0.3673
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 26s 6s/step - loss: 0.0905 - mean_absolute_error: 0.2479 - mean_absolute_percentage_error: 52758656.0000 - root_mean_squared_error: 0.3008 - val_loss: 0.1281 - val_mean_absolute_error: 0.3191 - val_mean_absolute_percentage_error: 109578344.0000 - val_root_mean_squared_error: 0.3579
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - loss: 0.0846 - mean_absolute_error: 0.2325 - mean_absolute_percentage_error: 56743356.0000 - root_mean_squared_error: 0.2909 - val_loss: 0.1296 - val_mean_absolute_error: 0.3223 - val_mean_absolute_percentage_error: 98209440.0000 - val_root_mean_squared_error: 0.3600
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 13s 5s/step - loss: 0.0775 - mean_absolute_error: 0.2251 - mean_absolute_percentage_error: 49758208.0000 - root_mean_squared_error: 0.2784 - val_loss: 0.1259 - val_mean_absolute_error: 0.3148 - val_mean_absolute_percentage_error: 104591256.0000 - val_root_mean_squared_error: 0.3548
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 5s/step - loss: 0.0776 - mean_absolute_error: 0.2226 - mean_absolute_percentage_error: 53146368.0000 - root_mean_squared_error: 0.2784 - val_loss: 0.1236 - val_mean_absolute_error: 0.3085 - val_mean_absolute_percentage_error: 102541856.0000 - val_root_mean_squared_error: 0.3515
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 22s 6s/step - loss: 0.0706 - mean_absolute_error: 0.2094 - mean_absolute_percentage_error: 48859736.0000 - root_mean_squared_error: 0.2657 - val_loss: 0.1212 - val_mean_absolute_error: 0.2998 - val_mean_absolute_percentage_error: 100952152.0000 - val_root_mean_squared_error: 0.3481
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 7s/step - loss: 0.0706 - mean_absolute_error: 0.2057 - mean_absolute_percentage_error: 46240340.0000 - root_mean_squared_error: 0.2658 - val_loss: 0.1188 - val_mean_absolute_error: 0.3001 - val_mean_absolute_percentage_error: 104351632.0000 - val_root_mean_squared_error: 0.3446
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 23s 8s/step - loss: 0.0681 - mean_absolute_error: 0.2002 - mean_absolute_percentage_error: 46527300.0000 - root_mean_squared_error: 0.2609 - val_loss: 0.1161 - val_mean_absolute_error: 0.2901 - val_mean_absolute_percentage_error: 108156712.0000 - val_root_mean_squared_error: 0.3407
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 16s 4s/step - loss: 0.0659 - mean_absolute_error: 0.1919 - mean_absolute_percentage_error: 48426056.0000 - root_mean_squared_error: 0.2567 - val_loss: 0.1138 - val_mean_absolute_error: 0.2880 - val_mean_absolute_percentage_error: 104079824.0000 - val_root_mean_squared_error: 0.3373
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 12s 5s/step - loss: 0.0633 - mean_absolute_error: 0.1907 - mean_absolute_percentage_error: 46023292.0000 - root_mean_squared_error: 0.2517 - val_loss: 0.1132 - val_mean_absolute_error: 0.2821 - val_mean_absolute_percentage_error: 95611288.0000 - val_root_mean_squared_error: 0.3364
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 9s/step - loss: 0.0569 - mean_absolute_error: 0.1822 - mean_absolute_percentage_error: 39291488.0000 - root_mean_squared_error: 0.2384 - val_loss: 0.1115 - val_mean_absolute_error: 0.2780 - val_mean_absolute_percentage_error: 101993952.0000 - val_root_mean_squared_error: 0.3339
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 46s 9s/step - loss: 0.0586 - mean_absolute_error: 0.1782 - mean_absolute_percentage_error: 41691604.0000 - root_mean_squared_error: 0.2420 - val_loss: 0.1099 - val_mean_absolute_error: 0.2750 - val_mean_absolute_percentage_error: 105325240.0000 - val_root_mean_squared_error: 0.3316
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 41s 7s/step - loss: 0.0537 - mean_absolute_error: 0.1729 - mean_absolute_percentage_error: 42052336.0000 - root_mean_squared_error: 0.2317 - val_loss: 0.1123 - val_mean_absolute_error: 0.2800 - val_mean_absolute_percentage_error: 87338296.0000 - val_root_mean_squared_error: 0.3351
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 32s 13s/step - loss: 0.0553 - mean_absolute_error: 0.1770 - mean_absolute_percentage_error: 37507184.0000 - root_mean_squared_error: 0.2352 - val_loss: 0.1086 - val_mean_absolute_error: 0.2769 - val_mean_absolute_percentage_error: 101812040.0000 - val_root_mean_squared_error: 0.3295
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 36s 9s/step - loss: 0.0511 - mean_absolute_error: 0.1665 - mean_absolute_percentage_error: 39351524.0000 - root_mean_squared_error: 0.2260 - val_loss: 0.1081 - val_mean_absolute_error: 0.2706 - val_mean_absolute_percentage_error: 95535184.0000 - val_root_mean_squared_error: 0.3288
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 25s 8s/step - loss: 0.0487 - mean_absolute_error: 0.1642 - mean_absolute_percentage_error: 37082872.0000 - root_mean_squared_error: 0.2205 - val_loss: 0.1116 - val_mean_absolute_error: 0.2765 - val_mean_absolute_percentage_error: 81096792.0000 - val_root_mean_squared_error: 0.3341
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 27s 9s/step - loss: 0.0498 - mean_absolute_error: 0.1730 - mean_absolute_percentage_error: 31344296.0000 - root_mean_squared_error: 0.2231 - val_loss: 0.1059 - val_mean_absolute_error: 0.2709 - val_mean_absolute_percentage_error: 106240400.0000 - val_root_mean_squared_error: 0.3255
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 44s 8s/step - loss: 0.0445 - mean_absolute_error: 0.1585 - mean_absolute_percentage_error: 37005408.0000 - root_mean_squared_error: 0.2107 - val_loss: 0.1068 - val_mean_absolute_error: 0.2751 - val_mean_absolute_percentage_error: 86695888.0000 - val_root_mean_squared_error: 0.3268
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 42s 7s/step - loss: 0.0446 - mean_absolute_error: 0.1622 - mean_absolute_percentage_error: 35537152.0000 - root_mean_squared_error: 0.2112 - val_loss: 0.1082 - val_mean_absolute_error: 0.2672 - val_mean_absolute_percentage_error: 82453696.0000 - val_root_mean_squared_error: 0.3289
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 28s 10s/step - loss: 0.0427 - mean_absolute_error: 0.1563 - mean_absolute_percentage_error: 30011278.0000 - root_mean_squared_error: 0.2066 - val_loss: 0.1072 - val_mean_absolute_error: 0.2720 - val_mean_absolute_percentage_error: 112394480.0000 - val_root_mean_squared_error: 0.3275
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 43s 9s/step - loss: 0.0455 - mean_absolute_error: 0.1603 - mean_absolute_percentage_error: 38970368.0000 - root_mean_squared_error: 0.2133 - val_loss: 0.1133 - val_mean_absolute_error: 0.2795 - val_mean_absolute_percentage_error: 74098520.0000 - val_root_mean_squared_error: 0.3365
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 4s/step - loss: 0.0418 - mean_absolute_error: 0.1557 - mean_absolute_percentage_error: 31306872.0000 - root_mean_squared_error: 0.2045 - val_loss: 0.1032 - val_mean_absolute_error: 0.2656 - val_mean_absolute_percentage_error: 99136128.0000 - val_root_mean_squared_error: 0.3213

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

11/11 ━━━━━━━━━━━━━━━━━━━━ 13s 747ms/step

array([[ 1.1772695 ],
       [ 1.1132349 ],
       [ 0.8773222 ],
       [ 0.19340742],
       [ 0.49704927],
       [ 1.0572242 ],
       [ 0.87262917],
       [ 0.88660127],
       [ 0.8634442 ],
       [ 0.7228949 ],
       [ 0.90323937],
       [ 0.94993466],
       [ 0.7129201 ],
       [ 0.79267323],
       [ 0.80215794],
       [ 0.6029861 ],
       [ 0.5697391 ],
       [ 0.2584605 ],
       [ 0.11226144],
       [ 0.12563016],
       [ 0.19609728],
       [ 0.8391011 ],
       [ 0.8746485 ],
       [ 0.5629952 ],
       [ 0.76774806],
       [ 0.9534504 ],
       [ 0.9786733 ],
       [ 0.73523283],
       [ 0.6431557 ],
       [ 0.69563586],
       [ 0.60527086],
       [ 0.34439832],
       [ 0.63822126],
       [ 0.1499213 ],
       [ 0.00137779],
       [ 0.07005148],
       [ 0.02447502],
       [ 0.5958508 ],
       [ 0.76419413],
       [ 0.6745958 ],
       [ 0.79329455],
       [ 0.8788632 ],
       [ 0.83524084],
       [ 0.38943487],
       [ 0.24909346],
       [ 0.39425647],
       [ 0.1942458 ],
       [ 0.8152708 ],
       [ 0.7770946 ],
       [ 0.69863   ],
       [ 0.77738345],
       [ 0.9726638 ],
       [ 0.88480234],
       [ 0.73190606],
       [ 0.7572557 ],
       [ 0.5880554 ],
       [ 0.5373414 ],
       [ 0.2176331 ],
       [ 0.04746714],
       [ 0.03651576],
       [ 0.63470435],
       [ 0.04040597],
       [ 0.6541188 ],
       [ 0.738467  ],
       [ 0.58796334],
       [ 0.6526525 ],
       [ 0.86996055],
       [ 0.25785825],
       [ 0.33458775],
       [ 1.0986266 ],
       [ 0.88884705],
       [ 0.9091301 ],
       [ 0.2400891 ],
       [ 0.06684792],
       [ 0.11329445],
       [ 0.2062094 ],
       [ 0.8663664 ],
       [ 0.6851629 ],
       [ 0.48552218],
       [ 0.7203778 ],
       [ 0.95273525],
       [ 0.7054233 ],
       [ 0.70504165],
       [ 0.84248286],
       [ 0.9296739 ],
       [ 0.39958835],
       [ 0.05658766],
       [ 0.8895918 ],
       [ 0.9088103 ],
       [ 0.01175208],
       [-0.00335328],
       [ 0.7071272 ],
       [ 0.66919845],
       [ 0.6673542 ],
       [ 1.0479081 ],
       [ 0.39402118],
       [ 0.3069867 ],
       [ 0.21984595],
       [ 0.20634903],
       [ 0.36899915],
       [ 0.04702558],
       [ 0.6696679 ],
       [ 0.7352462 ],
       [ 0.61702824],
       [ 0.5755319 ],
       [ 0.12916233],
       [ 0.31686372],
       [ 0.4154513 ],
       [ 0.4662813 ],
       [ 0.30267966],
       [ 0.829496  ],
       [ 0.7145773 ],
       [ 0.0439091 ],
       [ 0.17542554],
       [ 0.7940983 ],
       [ 0.86625457],
       [ 0.83545005],
       [ 0.9427778 ],
       [ 0.3312604 ],
       [ 0.02807199],
       [ 0.14241509],
       [ 0.2812728 ],
       [ 0.09357829],
       [ 0.6150053 ],
       [ 0.98116046],
       [ 0.7376931 ],
       [ 0.8579623 ],
       [ 1.0091418 ],
       [ 0.65596294],
       [ 0.10400979],
       [ 0.06973892],
       [ 0.64340895],
       [ 0.62913775],
       [ 0.856935  ],
       [ 0.8747879 ],
       [ 0.72724426],
       [ 0.7578125 ],
       [ 0.2525605 ],
       [ 0.36535963],
       [ 0.1243955 ],
       [ 0.8762437 ],
       [ 0.81811225],
       [ 0.705672  ],
       [ 0.57422054],
       [ 0.72232604],
       [ 0.23738593],
       [ 0.17108311],
       [ 0.2942314 ],
       [ 0.30520433],
       [ 0.4178434 ],
       [ 0.06189849],
       [ 0.6241509 ],
       [ 0.7089474 ],
       [ 0.5270893 ],
       [ 0.6898664 ],
       [ 0.94347167],
       [ 1.0207541 ],
       [ 0.81496906],
       [ 0.66653955],
       [ 0.6046441 ],
       [ 0.4963251 ],
       [ 0.00187979],
       [ 0.0647106 ],
       [ 0.00869481],
       [ 0.5947095 ],
       [ 0.7249604 ],
       [ 0.8383508 ],
       [ 0.65027994],
       [ 0.7252212 ],
       [ 0.41130498],
       [ 0.15765573],
       [ 1.053983  ],
       [ 0.8558452 ],
       [ 0.4863315 ],
       [ 0.39758047],
       [ 0.1613021 ],
       [ 0.03832745],
       [ 0.15262   ],
       [ 0.986122  ],
       [ 0.90739214],
       [ 0.64795196],
       [ 0.31796345],
       [ 0.45178336],
       [ 0.3719468 ],
       [ 0.28254122],
       [ 0.12972601],
       [ 0.90995497],
       [ 0.80752265],
       [ 0.5808639 ],
       [ 0.21506427],
       [ 0.18297827],
       [ 0.1338407 ],
       [ 0.6122855 ],
       [ 0.4118634 ],
       [ 0.18509944],
       [ 0.08542189],
       [ 0.32125717],
       [ 0.8525666 ],
       [ 0.71175635],
       [ 0.54098076],
       [ 0.6139307 ],
       [ 0.4150027 ],
       [ 0.31756103],
       [ 0.3042585 ],
       [ 0.91722685],
       [ 0.6772869 ],
       [ 0.04653388],
       [ 0.05058136],
       [ 0.05874266],
       [ 0.5746555 ],
       [ 0.6741866 ],
       [ 0.4754203 ],
       [ 0.487918  ],
       [ 0.8389084 ],
       [ 0.6371349 ],
       [ 0.41941974],
       [ 0.29907355],
       [ 0.23743619],
       [ 0.31980067],
       [ 0.7111732 ],
       [ 0.5568873 ],
       [ 0.57290953],
       [ 0.4785127 ],
       [ 0.24452114],
       [ 0.32399154],
       [ 0.9058233 ],
       [ 0.604108  ],
       [ 0.23302858],
       [ 0.3838991 ],
       [ 0.38615268],
       [ 0.2417501 ],
       [ 0.8155169 ],
       [ 0.87568194],
       [ 0.6227462 ],
       [ 0.33310544],
       [ 0.09402423],
       [ 0.2116874 ],
       [ 0.81411445],
       [ 0.65992326],
       [ 0.18389489],
       [ 0.08170658],
       [ 0.7303535 ],
       [ 0.7772075 ],
       [ 0.82814634],
       [ 0.8979319 ],
       [ 0.8545869 ],
       [ 0.41844076],
       [ 0.05984228],
       [ 0.26177326],
       [ 0.29585245],
       [ 0.86287355],
       [ 0.9925989 ],
       [ 0.8833777 ],
       [ 0.63039225],
       [ 0.68160176],
       [ 0.25493935],
       [ 0.8153862 ],
       [ 1.0564262 ],
       [ 0.91931564],
       [ 0.5444913 ],
       [ 0.6362984 ],
       [ 0.7395172 ],
       [ 0.8232318 ],
       [ 0.9665775 ],
       [ 0.84461784],
       [ 0.69797146],
       [ 0.69285595],
       [ 0.90919065],
       [ 0.6330172 ],
       [ 0.568374  ],
       [ 0.8223921 ],
       [ 0.7545723 ],
       [ 0.6565063 ],
       [ 0.7027533 ],
       [ 0.75651616],
       [ 0.71462846],
       [ 0.7309954 ],
       [ 0.5138075 ],
       [ 0.5611862 ],
       [ 0.5740111 ],
       [ 0.74673325],
       [ 0.80481267],
       [ 0.8863201 ],
       [ 0.57536924],
       [ 0.52715564],
       [ 0.6309394 ],
       [ 0.65186584],
       [ 0.3865855 ],
       [ 0.5267415 ],
       [ 0.9877763 ],
       [ 0.7673605 ],
       [ 0.4576491 ],
       [ 0.6244912 ],
       [ 0.6612844 ],
       [ 0.5761298 ],
       [ 0.3749562 ],
       [ 0.48599583],
       [ 0.8893926 ],
       [ 0.7754148 ],
       [ 0.68356574],
       [ 0.79209507],
       [ 0.74160826],
       [ 0.76804745],
       [ 0.56823695],
       [ 0.22985336],
       [ 0.2997235 ],
       [ 0.7471391 ],
       [ 0.7104553 ],
       [ 0.6972565 ],
       [ 0.76593924],
       [ 0.7031379 ],
       [ 0.65797055],
       [ 0.59632325],
       [ 0.6396944 ],
       [ 0.3023559 ],
       [ 0.8182617 ],
       [ 0.7284205 ],
       [ 0.51520234],
       [ 0.389685  ],
       [ 0.5806887 ],
       [ 0.7185266 ],
       [ 0.6859474 ],
       [ 0.67229104],
       [ 0.54691976],
       [ 0.46949568],
       [ 0.42773604],
       [ 0.54265505],
       [ 0.8002231 ],
       [ 0.7966686 ],
       [ 0.6921463 ],
       [ 0.53394854],
       [ 0.6505624 ],
       [ 0.66111314],
       [ 0.5158096 ],
       [ 0.10839035],
       [ 0.6037744 ],
       [ 0.7288994 ],
       [ 0.65535504],
       [ 0.56415296],
       [ 0.10507649],
       [ 0.660704  ],
       [ 0.36647385],
       [ 0.6398934 ],
       [ 0.6235867 ],
       [ 0.782224  ],
       [ 0.7634654 ],
       [ 0.69286454],
       [ 0.29076603]], dtype=float32)

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
13956     29864.0  29802.736495      29306.46           NaN
13960     29081.0   29095.19111    29272.7725           NaN
13961     28659.0  29136.770699     29224.675           NaN
13962     26410.0  28333.916793     28923.955           NaN
13963     17165.0  18488.082907      20188.37           NaN
...           ...           ...           ...           ...
18250     18014.0  21351.153925      20554.05  18707.601562
18251     23010.0  22831.557606  24302.920607  23466.720703
18252     26156.0  24912.539517  25643.327875  22903.962891
18285         0.0           0.0           0.0  20785.935547
18286         0.0           0.0           0.0   8722.980469

[396 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,985 (1.55 MB)

 Trainable params: 405,729 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 275s 432ms/step - loss: 0.1825 - mae: 0.4561 - val_loss: 0.1867 - val_mae: 0.5005
Epoch 2/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 120s 320ms/step - loss: 0.1358 - mae: 0.3862 - val_loss: 0.1534 - val_mae: 0.4481
Epoch 3/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 91s 353ms/step - loss: 0.1335 - mae: 0.3837 - val_loss: 0.1061 - val_mae: 0.3661
Epoch 4/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 88s 364ms/step - loss: 0.1104 - mae: 0.3601 - val_loss: 0.0972 - val_mae: 0.3575
Epoch 5/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 79s 326ms/step - loss: 0.1012 - mae: 0.3434 - val_loss: 0.0888 - val_mae: 0.3275
Epoch 6/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 85s 326ms/step - loss: 0.0935 - mae: 0.3349 - val_loss: 0.0838 - val_mae: 0.3364
Epoch 7/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 71s 264ms/step - loss: 0.0999 - mae: 0.3409 - val_loss: 0.0939 - val_mae: 0.3517
Epoch 8/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 98s 327ms/step - loss: 0.0946 - mae: 0.3345 - val_loss: 0.0667 - val_mae: 0.2901
Epoch 9/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 80s 311ms/step - loss: 0.0854 - mae: 0.3227 - val_loss: 0.0613 - val_mae: 0.2822
Epoch 10/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 74s 319ms/step - loss: 0.0788 - mae: 0.3073 - val_loss: 0.0590 - val_mae: 0.2713
Epoch 11/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 92s 350ms/step - loss: 0.0770 - mae: 0.2998 - val_loss: 0.0629 - val_mae: 0.2706
Epoch 12/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 78s 332ms/step - loss: 0.0752 - mae: 0.2956 - val_loss: 0.0552 - val_mae: 0.2582
Epoch 13/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 85s 326ms/step - loss: 0.0659 - mae: 0.2813 - val_loss: 0.0560 - val_mae: 0.2529
Epoch 14/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 82s 314ms/step - loss: 0.0620 - mae: 0.2686 - val_loss: 0.0565 - val_mae: 0.2578
Epoch 15/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 80s 291ms/step - loss: 0.0650 - mae: 0.2720 - val_loss: 0.0548 - val_mae: 0.2577
Epoch 16/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 88s 302ms/step - loss: 0.0649 - mae: 0.2736 - val_loss: 0.0528 - val_mae: 0.2511
Epoch 17/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 71s 306ms/step - loss: 0.0623 - mae: 0.2680 - val_loss: 0.0506 - val_mae: 0.2377
Epoch 18/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 80s 281ms/step - loss: 0.0584 - mae: 0.2576 - val_loss: 0.0570 - val_mae: 0.2539
Epoch 19/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 119s 433ms/step - loss: 0.0638 - mae: 0.2733 - val_loss: 0.0526 - val_mae: 0.2376
Epoch 20/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 142s 410ms/step - loss: 0.0610 - mae: 0.2620 - val_loss: 0.0484 - val_mae: 0.2296
Epoch 21/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 146s 411ms/step - loss: 0.0566 - mae: 0.2560 - val_loss: 0.0491 - val_mae: 0.2399
Epoch 22/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 142s 393ms/step - loss: 0.0521 - mae: 0.2450 - val_loss: 0.0475 - val_mae: 0.2302
Epoch 23/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 148s 395ms/step - loss: 0.0577 - mae: 0.2601 - val_loss: 0.0487 - val_mae: 0.2190
Epoch 24/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 144s 392ms/step - loss: 0.0530 - mae: 0.2397 - val_loss: 0.0471 - val_mae: 0.2175
Epoch 25/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 147s 398ms/step - loss: 0.0537 - mae: 0.2412 - val_loss: 0.0496 - val_mae: 0.2237
Epoch 26/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 96s 386ms/step - loss: 0.0545 - mae: 0.2391 - val_loss: 0.0490 - val_mae: 0.2146
Epoch 27/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 171s 484ms/step - loss: 0.0520 - mae: 0.2409 - val_loss: 0.0481 - val_mae: 0.2197
Epoch 28/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 87s 362ms/step - loss: 0.0522 - mae: 0.2368 - val_loss: 0.0487 - val_mae: 0.2138
Epoch 29/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 103s 438ms/step - loss: 0.0459 - mae: 0.2271 - val_loss: 0.0502 - val_mae: 0.2284
Epoch 30/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 96s 408ms/step - loss: 0.0466 - mae: 0.2240 - val_loss: 0.0483 - val_mae: 0.2224
Epoch 31/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 106s 438ms/step - loss: 0.0540 - mae: 0.2389 - val_loss: 0.0481 - val_mae: 0.2197
Epoch 32/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 114s 471ms/step - loss: 0.0445 - mae: 0.2196 - val_loss: 0.0460 - val_mae: 0.2145
Epoch 33/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 100s 428ms/step - loss: 0.0493 - mae: 0.2358 - val_loss: 0.0518 - val_mae: 0.2301
Epoch 34/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 148s 436ms/step - loss: 0.0465 - mae: 0.2226 - val_loss: 0.0493 - val_mae: 0.2202
Epoch 35/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 126s 356ms/step - loss: 0.0461 - mae: 0.2217 - val_loss: 0.0473 - val_mae: 0.2207
Epoch 36/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 100s 422ms/step - loss: 0.0470 - mae: 0.2242 - val_loss: 0.0484 - val_mae: 0.2140
Epoch 37/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 147s 422ms/step - loss: 0.0472 - mae: 0.2259 - val_loss: 0.0470 - val_mae: 0.2123
Epoch 38/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 142s 397ms/step - loss: 0.0462 - mae: 0.2213 - val_loss: 0.0478 - val_mae: 0.2167
Epoch 39/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 151s 422ms/step - loss: 0.0434 - mae: 0.2145 - val_loss: 0.0466 - val_mae: 0.2057
Epoch 40/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 148s 423ms/step - loss: 0.0435 - mae: 0.2137 - val_loss: 0.0458 - val_mae: 0.2112
Epoch 41/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 105s 453ms/step - loss: 0.0435 - mae: 0.2131 - val_loss: 0.0472 - val_mae: 0.2111
Epoch 42/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 99s 425ms/step - loss: 0.0402 - mae: 0.2042 - val_loss: 0.0439 - val_mae: 0.2069
Epoch 43/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 137s 381ms/step - loss: 0.0427 - mae: 0.2118 - val_loss: 0.0524 - val_mae: 0.2193
Epoch 44/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 160s 436ms/step - loss: 0.0396 - mae: 0.2018 - val_loss: 0.0496 - val_mae: 0.2213
Epoch 45/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 164s 514ms/step - loss: 0.0387 - mae: 0.2029 - val_loss: 0.0517 - val_mae: 0.2286
Epoch 46/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 169s 613ms/step - loss: 0.0416 - mae: 0.2115 - val_loss: 0.0498 - val_mae: 0.2183
Epoch 47/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 106s 426ms/step - loss: 0.0399 - mae: 0.2038 - val_loss: 0.0478 - val_mae: 0.2122
Epoch 48/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 181s 571ms/step - loss: 0.0393 - mae: 0.2002 - val_loss: 0.0432 - val_mae: 0.2066
Epoch 49/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 116s 430ms/step - loss: 0.0402 - mae: 0.2012 - val_loss: 0.0453 - val_mae: 0.2000
Epoch 50/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 177s 556ms/step - loss: 0.0414 - mae: 0.2014 - val_loss: 0.0467 - val_mae: 0.2144
Epoch 51/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 130s 475ms/step - loss: 0.0408 - mae: 0.2075 - val_loss: 0.0493 - val_mae: 0.2042
Epoch 52/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 161s 533ms/step - loss: 0.0390 - mae: 0.1985 - val_loss: 0.0601 - val_mae: 0.2220
Epoch 53/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 142s 504ms/step - loss: 0.0418 - mae: 0.2069 - val_loss: 0.0477 - val_mae: 0.2071
Epoch 54/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 149s 503ms/step - loss: 0.0413 - mae: 0.2079 - val_loss: 0.0558 - val_mae: 0.2332
Epoch 55/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 144s 489ms/step - loss: 0.0379 - mae: 0.1959 - val_loss: 0.0633 - val_mae: 0.2302
Epoch 56/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 120s 367ms/step - loss: 0.0378 - mae: 0.1983 - val_loss: 0.0496 - val_mae: 0.2039
Epoch 57/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 163s 438ms/step - loss: 0.0336 - mae: 0.1843 - val_loss: 0.0481 - val_mae: 0.2177
Epoch 58/100
225/225 ━━━━━━━━━━━━━━━━━━━━ 101s 429ms/step - loss: 0.0353 - mae: 0.1864 - val_loss: 0.0475 - val_mae: 0.2026

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

11/11 ━━━━━━━━━━━━━━━━━━━━ 65s 3s/step

array([[0.8515019 ],
       [0.8372051 ],
       [0.67486995],
       [0.01657102],
       [0.48138645],
       [0.7812376 ],
       [0.8378856 ],
       [0.62010723],
       [0.7674374 ],
       [0.42100522],
       [0.66717607],
       [0.71533084],
       [0.31536287],
       [0.75966674],
       [0.32195222],
       [0.33749318],
       [0.28885466],
       [0.03654558],
       [0.        ],
       [0.        ],
       [0.3148396 ],
       [0.7964461 ],
       [0.7926151 ],
       [0.5308808 ],
       [0.5074903 ],
       [0.40932745],
       [0.6625546 ],
       [0.81275207],
       [0.86142665],
       [0.5542529 ],
       [0.33714327],
       [0.32815197],
       [0.38695842],
       [0.24076217],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.69390225],
       [0.6228549 ],
       [0.74144834],
       [0.6559378 ],
       [0.65239197],
       [0.49136537],
       [0.3324894 ],
       [0.        ],
       [0.07898502],
       [0.30697772],
       [0.7375689 ],
       [0.75631374],
       [0.7572365 ],
       [0.6675828 ],
       [0.7172794 ],
       [0.7435809 ],
       [0.7892116 ],
       [0.7052813 ],
       [0.6631585 ],
       [0.55651265],
       [0.41822267],
       [0.        ],
       [0.        ],
       [0.4752811 ],
       [0.        ],
       [0.69786775],
       [0.4011322 ],
       [0.5208033 ],
       [0.37143937],
       [0.12480779],
       [0.48088634],
       [0.57895017],
       [0.76406527],
       [0.8088474 ],
       [0.773031  ],
       [0.6438574 ],
       [0.46578446],
       [0.25776213],
       [0.37124828],
       [0.8303199 ],
       [0.72609365],
       [0.45499596],
       [0.19628341],
       [0.6887006 ],
       [0.51460195],
       [0.600775  ],
       [0.6289714 ],
       [0.49583876],
       [0.35814014],
       [0.01104883],
       [0.6741419 ],
       [0.57505256],
       [0.28653288],
       [0.5968325 ],
       [0.7517968 ],
       [0.8794403 ],
       [0.8362248 ],
       [0.7451871 ],
       [0.5452042 ],
       [0.38316974],
       [0.15264681],
       [0.09682624],
       [0.2253215 ],
       [0.4451863 ],
       [0.7331502 ],
       [0.5934747 ],
       [0.6388954 ],
       [0.537156  ],
       [0.43220386],
       [0.40845117],
       [0.0989213 ],
       [0.10632788],
       [0.4140473 ],
       [0.7022797 ],
       [0.640158  ],
       [0.15542704],
       [0.36478892],
       [0.67231184],
       [0.5985942 ],
       [0.4821841 ],
       [0.57947797],
       [0.28065735],
       [0.12445778],
       [0.02408859],
       [0.        ],
       [0.3307459 ],
       [0.6584858 ],
       [0.60261184],
       [0.5699675 ],
       [0.52774024],
       [0.42121854],
       [0.2975827 ],
       [0.        ],
       [0.3214946 ],
       [0.7340099 ],
       [0.6700762 ],
       [0.39260405],
       [0.4703247 ],
       [0.54996824],
       [0.392428  ],
       [0.        ],
       [0.        ],
       [0.38856494],
       [0.6482499 ],
       [0.75343186],
       [0.82127714],
       [0.7423606 ],
       [0.52240974],
       [0.18429908],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.34940824],
       [0.6839127 ],
       [0.8442583 ],
       [0.5856222 ],
       [0.78002125],
       [0.7768196 ],
       [0.4978336 ],
       [0.7457643 ],
       [0.6725676 ],
       [0.40994954],
       [0.360102  ],
       [0.        ],
       [0.        ],
       [0.2468785 ],
       [0.73269063],
       [0.6548948 ],
       [0.5448796 ],
       [0.62951356],
       [0.48924997],
       [0.3721683 ],
       [0.        ],
       [0.62262774],
       [0.3824828 ],
       [0.4201068 ],
       [0.2626836 ],
       [0.10524532],
       [0.        ],
       [0.33238068],
       [0.7355086 ],
       [0.6563137 ],
       [0.48138905],
       [0.39932114],
       [0.2502934 ],
       [0.        ],
       [0.        ],
       [0.4198309 ],
       [0.8184118 ],
       [0.69919026],
       [0.5525897 ],
       [0.45498633],
       [0.33256778],
       [0.1046069 ],
       [0.69214493],
       [0.5971186 ],
       [0.32999185],
       [0.        ],
       [0.37264153],
       [0.7255731 ],
       [0.63761824],
       [0.25581986],
       [0.49037224],
       [0.49174717],
       [0.4039057 ],
       [0.22336628],
       [0.69137   ],
       [0.7194977 ],
       [0.04712303],
       [0.3077901 ],
       [0.46385184],
       [0.7371884 ],
       [0.6534693 ],
       [0.14493929],
       [0.42451856],
       [0.6650973 ],
       [0.62480694],
       [0.35207635],
       [0.36643147],
       [0.        ],
       [0.42010406],
       [0.7358206 ],
       [0.6840278 ],
       [0.47189853],
       [0.46706727],
       [0.3874219 ],
       [0.09481186],
       [0.65218467],
       [0.657979  ],
       [0.32764703],
       [0.3188042 ],
       [0.36266375],
       [0.24179628],
       [0.6930139 ],
       [0.6861964 ],
       [0.48594075],
       [0.38148132],
       [0.11435809],
       [0.3775521 ],
       [0.7671648 ],
       [0.5682799 ],
       [0.3572481 ],
       [0.48001269],
       [0.7535519 ],
       [0.56805223],
       [0.6065381 ],
       [0.5876702 ],
       [0.4488899 ],
       [0.31282485],
       [0.13109857],
       [0.        ],
       [0.40637392],
       [0.663428  ],
       [0.6134237 ],
       [0.43751013],
       [0.492446  ],
       [0.24016929],
       [0.27782524],
       [0.63664603],
       [0.59508455],
       [0.405031  ],
       [0.43246314],
       [0.5645682 ],
       [0.6258772 ],
       [0.61835456],
       [0.64563775],
       [0.33559278],
       [0.694593  ],
       [0.5025494 ],
       [0.7415985 ],
       [0.60330606],
       [0.34546643],
       [0.7039728 ],
       [0.6684549 ],
       [0.34798342],
       [0.6704443 ],
       [0.327414  ],
       [0.7379805 ],
       [0.6622059 ],
       [0.3987885 ],
       [0.7455286 ],
       [0.426219  ],
       [0.68339926],
       [0.40168086],
       [0.7116732 ],
       [0.41580096],
       [0.7613518 ],
       [0.7348333 ],
       [0.4742411 ],
       [0.        ],
       [0.4895592 ],
       [0.84532076],
       [0.7709015 ],
       [0.45276007],
       [0.5068016 ],
       [0.46658865],
       [0.422243  ],
       [0.        ],
       [0.5186175 ],
       [0.8730916 ],
       [0.77104056],
       [0.44226113],
       [0.7210764 ],
       [0.36194605],
       [0.6528532 ],
       [0.5027301 ],
       [0.43364874],
       [0.67591345],
       [0.68437105],
       [0.34489137],
       [0.70813537],
       [0.80489403],
       [0.4541362 ],
       [0.10929336],
       [0.19945185],
       [0.22983551],
       [0.28995818],
       [0.62334794],
       [0.08974268],
       [0.407211  ],
       [0.01167407],
       [0.08165126],
       [0.40733144],
       [0.4240479 ],
       [0.3222082 ],
       [0.02969604],
       [0.2698131 ],
       [0.0455768 ],
       [0.4199644 ],
       [0.7316989 ],
       [0.39549395],
       [0.18414341],
       [0.45596534],
       [0.16792029],
       [0.48536748],
       [0.6311686 ],
       [0.39532036],
       [0.12304962],
       [0.3856144 ],
       [0.22300315],
       [0.11130661],
       [0.04050203],
       [0.14741465],
       [0.        ],
       [0.2643839 ],
       [0.18292478],
       [0.6564025 ],
       [0.25896028],
       [0.09997828],
       [0.0398537 ]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
13956     29864.0  29802.736495      29306.46           NaN           NaN
13960     29081.0   29095.19111    29272.7725           NaN           NaN
13961     28659.0  29136.770699     29224.675           NaN           NaN
13962     26410.0  28333.916793     28923.955           NaN           NaN
13963     17165.0  18488.082907      20188.37           NaN           NaN
...           ...           ...           ...           ...           ...
18250     18014.0  21351.153925      20554.05  18707.601562   5487.743164
18251     23010.0  22831.557606  24302.920607  23466.720703  19692.076172
18252     26156.0  24912.539517  25643.327875  22903.962891   7768.808105
18285         0.0           0.0           0.0  20785.935547   2999.348389
18286         0.0           0.0           0.0   8722.980469   1195.610962

[396 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

14123    22457.0
14177    24561.0
14191        0.0
14192      359.0
14241     9321.0
          ...
18250    18014.0
18251    23010.0
18252    26156.0
18285        0.0
18286        0.0
Name: Generación, Length: 348, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 9)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      2,368 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 474,049 (1.81 MB)

 Trainable params: 474,049 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 338s 482ms/step - loss: 1.2916 - mae: 0.3610 - val_loss: 0.9644 - val_mae: 0.3835
Epoch 2/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 46s 323ms/step - loss: 0.8491 - mae: 0.3246 - val_loss: 0.6778 - val_mae: 0.3645
Epoch 3/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 41s 277ms/step - loss: 0.5929 - mae: 0.3153 - val_loss: 0.4975 - val_mae: 0.3652
Epoch 4/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 42s 239ms/step - loss: 0.4343 - mae: 0.3149 - val_loss: 0.3849 - val_mae: 0.3683
Epoch 5/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 49s 255ms/step - loss: 0.3285 - mae: 0.3123 - val_loss: 0.3034 - val_mae: 0.3586
Epoch 6/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 54s 324ms/step - loss: 0.2565 - mae: 0.3010 - val_loss: 0.2411 - val_mae: 0.3336
Epoch 7/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 43s 291ms/step - loss: 0.2065 - mae: 0.2894 - val_loss: 0.2055 - val_mae: 0.2856
Epoch 8/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 54s 354ms/step - loss: 0.1644 - mae: 0.2538 - val_loss: 0.1604 - val_mae: 0.2692
Epoch 9/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 66s 172ms/step - loss: 0.1424 - mae: 0.2437 - val_loss: 0.1396 - val_mae: 0.2443
Epoch 10/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 61s 322ms/step - loss: 0.1226 - mae: 0.2281 - val_loss: 0.1271 - val_mae: 0.2342
Epoch 11/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 45s 296ms/step - loss: 0.1077 - mae: 0.2195 - val_loss: 0.1225 - val_mae: 0.2363
Epoch 12/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 54s 361ms/step - loss: 0.1028 - mae: 0.2194 - val_loss: 0.1109 - val_mae: 0.2252
Epoch 13/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 76s 256ms/step - loss: 0.0973 - mae: 0.2142 - val_loss: 0.1048 - val_mae: 0.2272
Epoch 14/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 30s 207ms/step - loss: 0.0913 - mae: 0.2130 - val_loss: 0.1087 - val_mae: 0.2211
Epoch 15/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 58s 334ms/step - loss: 0.0832 - mae: 0.1983 - val_loss: 0.1001 - val_mae: 0.2178
Epoch 16/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 41s 286ms/step - loss: 0.0790 - mae: 0.1966 - val_loss: 0.1038 - val_mae: 0.2205
Epoch 17/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 50s 318ms/step - loss: 0.0859 - mae: 0.2105 - val_loss: 0.1013 - val_mae: 0.2173
Epoch 18/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 39s 282ms/step - loss: 0.0719 - mae: 0.1873 - val_loss: 0.0993 - val_mae: 0.2177
Epoch 19/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 48s 299ms/step - loss: 0.0750 - mae: 0.1991 - val_loss: 0.0927 - val_mae: 0.2152
Epoch 20/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 33s 190ms/step - loss: 0.0677 - mae: 0.1884 - val_loss: 0.0906 - val_mae: 0.2101
Epoch 21/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 22s 168ms/step - loss: 0.0692 - mae: 0.1892 - val_loss: 0.0871 - val_mae: 0.2146
Epoch 22/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 35s 254ms/step - loss: 0.0650 - mae: 0.1849 - val_loss: 0.0862 - val_mae: 0.2141
Epoch 23/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 53s 322ms/step - loss: 0.0659 - mae: 0.1854 - val_loss: 0.0866 - val_mae: 0.2215
Epoch 24/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 43s 290ms/step - loss: 0.0672 - mae: 0.1908 - val_loss: 0.0868 - val_mae: 0.2173
Epoch 25/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 45s 301ms/step - loss: 0.0663 - mae: 0.1877 - val_loss: 0.0838 - val_mae: 0.2049
Epoch 26/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 30s 212ms/step - loss: 0.0643 - mae: 0.1826 - val_loss: 0.0828 - val_mae: 0.2117
Epoch 27/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 45s 225ms/step - loss: 0.0620 - mae: 0.1821 - val_loss: 0.0829 - val_mae: 0.2035
Epoch 28/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 54s 284ms/step - loss: 0.0585 - mae: 0.1737 - val_loss: 0.0905 - val_mae: 0.2109
Epoch 29/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 46s 277ms/step - loss: 0.0601 - mae: 0.1796 - val_loss: 0.0824 - val_mae: 0.2030
Epoch 30/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 42s 235ms/step - loss: 0.0616 - mae: 0.1794 - val_loss: 0.0835 - val_mae: 0.2020
Epoch 31/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 53s 297ms/step - loss: 0.0577 - mae: 0.1735 - val_loss: 0.0814 - val_mae: 0.2003
Epoch 32/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 35s 210ms/step - loss: 0.0608 - mae: 0.1803 - val_loss: 0.0892 - val_mae: 0.2035
Epoch 33/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 27s 199ms/step - loss: 0.0590 - mae: 0.1721 - val_loss: 0.0801 - val_mae: 0.2069
Epoch 34/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 26s 204ms/step - loss: 0.0560 - mae: 0.1724 - val_loss: 0.0916 - val_mae: 0.2098
Epoch 35/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 50s 239ms/step - loss: 0.0539 - mae: 0.1660 - val_loss: 0.0804 - val_mae: 0.2000
Epoch 36/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 47s 257ms/step - loss: 0.0549 - mae: 0.1683 - val_loss: 0.0810 - val_mae: 0.2010
Epoch 37/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 53s 324ms/step - loss: 0.0558 - mae: 0.1698 - val_loss: 0.0853 - val_mae: 0.2043
Epoch 38/50
113/113 ━━━━━━━━━━━━━━━━━━━━ 43s 289ms/step - loss: 0.0501 - mae: 0.1627 - val_loss: 0.1054 - val_mae: 0.2298

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

11/11 ━━━━━━━━━━━━━━━━━━━━ 44s 2s/step

array([[0.9525144 ],
       [0.82304287],
       [0.7715937 ],
       [0.35340005],
       [0.47553745],
       [0.98211807],
       [1.0311407 ],
       [0.78704476],
       [0.6232111 ],
       [0.66775155],
       [0.67811286],
       [0.89676887],
       [0.6977565 ],
       [0.70742834],
       [0.4728002 ],
       [0.64378774],
       [0.6839179 ],
       [0.47063363],
       [0.04632912],
       [0.33674526],
       [0.39373282],
       [0.7967821 ],
       [0.84206843],
       [0.6131705 ],
       [0.4070351 ],
       [0.42673713],
       [0.7569424 ],
       [0.49134055],
       [0.80527455],
       [0.67609   ],
       [0.43713766],
       [0.53601116],
       [0.6870822 ],
       [0.39492196],
       [0.04307859],
       [0.04692937],
       [0.05140426],
       [0.7032567 ],
       [0.7706185 ],
       [0.7869022 ],
       [0.7615446 ],
       [0.5976004 ],
       [0.49246076],
       [0.34301025],
       [0.06125217],
       [0.15350443],
       [0.38795078],
       [0.6839401 ],
       [0.8060171 ],
       [0.7592701 ],
       [0.8072756 ],
       [0.8530923 ],
       [0.8666681 ],
       [0.8286048 ],
       [0.7834102 ],
       [0.63737154],
       [0.5342227 ],
       [0.426432  ],
       [0.09973951],
       [0.09815794],
       [0.5910206 ],
       [0.4168055 ],
       [0.72570026],
       [0.64552045],
       [0.59321   ],
       [0.6359735 ],
       [0.50605893],
       [0.30426216],
       [0.35579506],
       [0.7725345 ],
       [0.91964334],
       [0.7846335 ],
       [0.6654773 ],
       [0.56352574],
       [0.26580164],
       [0.07812738],
       [0.5745705 ],
       [0.6179514 ],
       [0.5718845 ],
       [0.36095646],
       [0.61670685],
       [0.599895  ],
       [0.5700073 ],
       [0.63042706],
       [0.5863348 ],
       [0.39752626],
       [0.1525209 ],
       [0.65360796],
       [0.5849646 ],
       [0.25343028],
       [0.46199983],
       [0.631241  ],
       [0.6472414 ],
       [0.6637561 ],
       [0.5935857 ],
       [0.41686913],
       [0.27533668],
       [0.10568248],
       [0.08319448],
       [0.09498604],
       [0.30402708],
       [0.5263828 ],
       [0.6028834 ],
       [0.5957235 ],
       [0.48476106],
       [0.41882485],
       [0.43517923],
       [0.13977124],
       [0.1472603 ],
       [0.33638823],
       [0.6431235 ],
       [0.6554793 ],
       [0.35294318],
       [0.43579742],
       [0.70389116],
       [0.64661884],
       [0.46402907],
       [0.5363687 ],
       [0.50546247],
       [0.28710473],
       [0.11456923],
       [0.16289386],
       [0.33320835],
       [0.6100888 ],
       [0.5826191 ],
       [0.48022252],
       [0.55811524],
       [0.5034278 ],
       [0.3900376 ],
       [0.20002827],
       [0.3057018 ],
       [0.64587545],
       [0.71359295],
       [0.44914135],
       [0.2961849 ],
       [0.53674   ],
       [0.59058344],
       [0.04266174],
       [0.04829174],
       [0.22153324],
       [0.56831706],
       [0.64770776],
       [0.65136224],
       [0.68288887],
       [0.59714025],
       [0.24702978],
       [0.04544942],
       [0.0414747 ],
       [0.04948648],
       [0.09071186],
       [0.16966428],
       [0.4620946 ],
       [0.80268836],
       [0.65245175],
       [0.48524982],
       [0.6543406 ],
       [0.6354064 ],
       [0.49313918],
       [0.583336  ],
       [0.5120166 ],
       [0.4827186 ],
       [0.28541586],
       [0.22630997],
       [0.4468476 ],
       [0.8150506 ],
       [0.8294421 ],
       [0.61211514],
       [0.62088203],
       [0.5852356 ],
       [0.4699826 ],
       [0.2734331 ],
       [0.74569905],
       [0.6416345 ],
       [0.583331  ],
       [0.61411554],
       [0.3582222 ],
       [0.19725993],
       [0.59016603],
       [0.85842156],
       [0.8020607 ],
       [0.61031383],
       [0.58273256],
       [0.36515442],
       [0.05060978],
       [0.29648194],
       [0.5453292 ],
       [0.83214116],
       [0.7710203 ],
       [0.60755646],
       [0.5608251 ],
       [0.39509606],
       [0.11484085],
       [0.5776257 ],
       [0.71333206],
       [0.5678095 ],
       [0.29326862],
       [0.57926786],
       [0.7900363 ],
       [0.74111366],
       [0.48456284],
       [0.33651832],
       [0.5333447 ],
       [0.5161971 ],
       [0.25704008],
       [0.46205032],
       [0.7117557 ],
       [0.43626085],
       [0.5816822 ],
       [0.70384777],
       [0.75821334],
       [0.6429187 ],
       [0.39067638],
       [0.5517914 ],
       [0.75168467],
       [0.66327584],
       [0.50715584],
       [0.5217157 ],
       [0.11209214],
       [0.39775875],
       [0.8842458 ],
       [0.8019004 ],
       [0.60482764],
       [0.58717155],
       [0.5234312 ],
       [0.09664913],
       [0.66064703],
       [0.7481593 ],
       [0.59279406],
       [0.5837661 ],
       [0.6009908 ],
       [0.40197664],
       [0.63852537],
       [0.8205132 ],
       [0.6776615 ],
       [0.5662756 ],
       [0.19528198],
       [0.49618325],
       [0.89603066],
       [0.7907521 ],
       [0.5119785 ],
       [0.66998744],
       [0.8642806 ],
       [0.73704445],
       [0.60455614],
       [0.75554895],
       [0.60224813],
       [0.4689203 ],
       [0.2075797 ],
       [0.20473006],
       [0.45187128],
       [0.7742471 ],
       [0.7880425 ],
       [0.6160836 ],
       [0.60592544],
       [0.49101454],
       [0.25759214],
       [0.7045002 ],
       [0.774282  ],
       [0.68712735],
       [0.71012163],
       [0.59609616],
       [0.7369964 ],
       [0.833081  ],
       [0.8294952 ],
       [0.6413942 ],
       [0.50977695],
       [0.65923107],
       [0.7564138 ],
       [0.72079945],
       [0.51692945],
       [0.55205977],
       [0.72622633],
       [0.5900487 ],
       [0.48303303],
       [0.4737881 ],
       [0.5829545 ],
       [0.71449363],
       [0.5619706 ],
       [0.58870304],
       [0.45506757],
       [0.54857564],
       [0.51309824],
       [0.56841826],
       [0.5125662 ],
       [0.51322967],
       [0.658111  ],
       [0.5949526 ],
       [0.32136303],
       [0.5799219 ],
       [0.8552084 ],
       [0.8003001 ],
       [0.55444455],
       [0.4627375 ],
       [0.59280014],
       [0.4635143 ],
       [0.29960963],
       [0.5088973 ],
       [0.8752982 ],
       [0.82211053],
       [0.6789767 ],
       [0.47502333],
       [0.56770015],
       [0.6126722 ],
       [0.49479136],
       [0.24658018],
       [0.48795372],
       [0.7757167 ],
       [0.5159174 ],
       [0.3370214 ],
       [0.7317974 ],
       [0.7206486 ],
       [0.45218056],
       [0.54468703],
       [0.53910506],
       [0.2056972 ],
       [0.88867307],
       [0.49427876],
       [0.43325955],
       [0.5146719 ],
       [0.6161611 ],
       [0.53391445],
       [0.6218606 ],
       [0.5326031 ],
       [0.45348805],
       [0.5554549 ],
       [0.4873892 ],
       [0.33763874],
       [0.8970418 ],
       [0.7565571 ],
       [0.5432425 ],
       [0.546728  ],
       [0.6299787 ],
       [0.65939534],
       [0.71751237],
       [0.65055174],
       [0.6576396 ],
       [0.5341388 ],
       [0.5672246 ],
       [0.5471858 ],
       [0.3221919 ],
       [0.7942802 ],
       [0.39032152],
       [0.64805824],
       [0.2633723 ],
       [0.6935192 ],
       [0.8014493 ],
       [0.55949336],
       [0.3707536 ]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
13956,29864.0,29802.736495,29306.46,NaN,NaN,NaN
13960,29081.0,29095.19111,29272.7725,NaN,NaN,NaN
13961,28659.0,29136.770699,29224.675,NaN,NaN,NaN
13962,26410.0,28333.916793,28923.955,NaN,NaN,NaN
13963,17165.0,18488.082907,20188.37,NaN,NaN,NaN
...,...,...,...,...,...,...
18250,18014.0,21351.153925,20554.05,18707.601562,5487.743164,7901.168945
18251,23010.0,22831.557606,24302.920607,23466.720703,19692.076172,20805.576172
18252,26156.0,24912.539517,25643.327875,22903.962891,7768.808105,24043.478516
18285,0.0,0.0,0.0,20785.935547,2999.348389,16784.800781
18286,0.0,0.0,0.0,8722.980469,1195.610962,11122.607422

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1180.6107
RMSE: 1838.9254
R²: 0.9682
Random Forest
MAE: 1137.5189
RMSE: 1896.5673
R²: 0.9661
CTNET
MAE: 7067.9263
RMSE: 9133.8398
R²: 0.1849
Forecast
MAE: 7534.2633
RMSE: 9745.5976
R²: 0.0720
Photovoltaic
MAE: 7003.3658
RMSE: 8643.8998
R²: 0.2700

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

57/57 ━━━━━━━━━━━━━━━━━━━━ 15s 135ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

57/57 ━━━━━━━━━━━━━━━━━━━━ 16s 165ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

57/57 ━━━━━━━━━━━━━━━━━━━━ 11s 77ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
35,17036.043251,18916.650982,18343.081911,NaN,NaN,NaN
36,27523.885172,23625.237046,26484.068664,NaN,NaN,NaN
227,26530.520060,22120.382702,25113.129493,NaN,NaN,NaN
228,28976.805233,27136.696426,28239.947956,NaN,NaN,NaN
275,27101.921674,23336.208873,26119.410594,NaN,NaN,NaN
...,...,...,...,...,...,...
11733,0.000000,813.079838,0.000000,20731.121094,21097.957031,19384.234375
11757,0.000000,126.613609,0.000000,6383.157715,4381.900879,3073.778809
11758,0.000000,180.801138,0.000000,8024.703613,1582.384155,6675.945801
11767,0.000000,0.000000,0.000000,8355.585938,6401.897461,8967.548828
11768,0.000000,0.000000,0.000000,11129.660156,0.000000,1214.146484

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1149.2564
RMSE: 2157.2697
R²: 0.9648
Random Forest
MAE: 421.1439
RMSE: 875.6741
R²: 0.9942
CTNET
MAE: 4924.6953
RMSE: 6616.9018
R²: 0.6707
Forecast
MAE: 5466.7562
RMSE: 7656.0800
R²: 0.5591
Photovoltaic
MAE: 5183.7918
RMSE: 6817.1150
R²: 0.6505

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,...,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.5_Predicciones_Conjunto_nublado GMM.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_5_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_5_RandomForest_model.pkl")

['4_5_RandomForest_model.pkl']

In [87]:
CTNET.save("4_5_CTNET_model.keras")
Forecast_model.save("4_5_Forecast_model.keras")
Photo_model.save("4_5_Photo_model.keras")