# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,7,77,0,4,15,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,7,82,0,4,16,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,9,85,0,3,16,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,11,87,0,3,16,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,11,88,0,3,16,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,15,86,0,3,14,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,47,89,0,3,16,6,Nublado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,51,95,0,4,17,7,Nublado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,47,100,0,3,18,8,Nublado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,5,100,1,4,18,9,Nublado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,5,93,2,4,18,10,Nublado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,5,79,2,4,17,11,Nublado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,5,64,6,3,15,12,Nublado,Lluvioso
13,2022-09-01 13:00:00,25478.471342,23,5,51,11,3,13,13,Soleado,Lluvioso
14,2022-09-01 14:00:00,29057.585772,25,3,41,12,1,11,14,Soleado,Lluvioso
15,2022-09-01 15:00:00,30000.000000,26,0,35,11,1,9,15,Soleado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,0,33,8,1,9,16,Soleado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,0,34,5,1,11,17,Soleado,Soleado
18,2022-09-01 18:00:00,29900.303971,27,0,37,3,2,11,18,Soleado,Soleado
19,2022-09-01 19:00:00,18282.505369,26,0,41,2,3,12,19,Soleado,Soleado
20,2022-09-01 20:00:00,3411.083740,24,2,48,0,3,12,20,Nublado,Lluvioso
21,2022-09-01 21:00:00,382.187718,22,6,55,0,3,13,21,Nublado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,6,61,0,4,13,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,6,68,0,4,14,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster GMM"] == "Lluvioso"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
30,2022-09-02 06:00:00,0.000000,17,7,91,0,4,15,6,Nublado,Lluvioso,0.000000,0.000000
31,2022-09-02 07:00:00,0.000000,17,7,94,0,3,16,7,Nublado,Lluvioso,0.000000,6.584959
32,2022-09-02 08:00:00,438.814997,16,5,97,0,3,15,8,Nublado,Lluvioso,0.000000,560.422022
33,2022-09-02 09:00:00,5908.000884,17,0,93,1,2,16,9,Nublado,Lluvioso,438.814997,7720.582326
34,2022-09-02 10:00:00,5030.740421,18,0,85,2,2,15,10,Nublado,Lluvioso,5908.000884,9433.109309
38,2022-09-02 14:00:00,28500.000000,24,3,37,6,2,9,14,Soleado,Lluvioso,20596.278869,29057.585772
39,2022-09-02 15:00:00,24647.568577,26,7,33,5,4,8,15,Nublado,Lluvioso,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,7,34,4,4,9,16,Nublado,Lluvioso,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,7,36,2,4,12,17,Nublado,Lluvioso,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,7,39,1,4,12,18,Nublado,Lluvioso,24281.956494,29900.303971

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,17,7,91,0,4,15,6,0.000000,0.000000
31,17,7,94,0,3,16,7,0.000000,6.584959
32,16,5,97,0,3,15,8,0.000000,560.422022
33,17,0,93,1,2,16,9,438.814997,7720.582326
34,18,0,85,2,2,15,10,5908.000884,9433.109309
...,...,...,...,...,...,...,...,...,...
18273,14,0,87,1,4,11,8,67.000000,7302.000000
18274,15,0,83,2,4,12,9,7356.000000,18014.000000
18275,17,0,71,4,3,12,10,17638.000000,23010.000000
18276,19,0,60,5,3,11,11,23339.000000,26156.000000
18278,23,0,44,7,4,10,13,26277.000000,25653.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
30         0.000000
31         0.000000
32       438.814997
33      5908.000884
34      5030.740421
...             ...
18273   7356.000000
18274  17638.000000
18275  23339.000000
18276  26323.000000
18278  25598.000000

[6090 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 4263, y_train: 4263
X_val: 913, y_val: 913
X_test: 914, y_test: 914

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[4.70588235e-01 7.77777778e-02 9.04255319e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.70588235e-01 7.77777778e-02 9.36170213e-01 ... 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [4.41176471e-01 5.55555556e-02 9.68085106e-01 ... 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [7.35294118e-01 0.00000000e+00 2.65957447e-01 ... 7.33333333e-01
  8.68733333e-01 6.41966667e-01]
 [6.47058824e-01 0.00000000e+00 3.93617021e-01 ... 8.00000000e-01
  8.07700000e-01 4.83833333e-01]
 [5.88235294e-01 2.22222222e-02 5.21276596e-01 ... 8.66666667e-01
  5.96633333e-01 9.58000000e-02]]
(4263, 9)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.470588,0.077778,0.904255,0.000000,0.75,0.789474,0.000000,0.000000,0.000000
31,0.470588,0.077778,0.936170,0.000000,0.50,0.842105,0.066667,0.000000,0.000219
32,0.441176,0.055556,0.968085,0.000000,0.50,0.789474,0.133333,0.000000,0.018681
33,0.470588,0.000000,0.925532,0.071429,0.25,0.842105,0.200000,0.014627,0.257353
34,0.500000,0.000000,0.840426,0.142857,0.25,0.789474,0.266667,0.196933,0.314437
...,...,...,...,...,...,...,...,...,...
13522,0.382353,0.000000,0.776596,0.142857,0.50,0.578947,0.200000,0.415467,0.612933
13529,0.794118,0.000000,0.202128,0.142857,1.00,0.315789,0.666667,0.862067,0.847600
13530,0.735294,0.000000,0.265957,0.071429,1.00,0.368421,0.733333,0.868733,0.641967
13531,0.647059,0.000000,0.393617,0.071429,1.00,0.526316,0.800000,0.807700,0.483833
13532,0.588235,0.022222,0.521277,0.000000,1.00,0.631579,0.866667,0.596633,0.095800

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.55882353 0.48888889 0.61702128 ... 0.93333333 0.11096667 0.        ]
 [0.5        0.56666667 0.72340426 ... 1.         0.         0.        ]
 [0.38235294 0.22222222 0.82978723 ... 0.         0.         0.        ]
 ...
 [0.58823529 0.56666667 0.65957447 ... 0.33333333 0.89683333 0.92476667]
 [0.64705882 0.52222222 0.57446809 ... 0.4        0.92476667 0.93596667]
 [0.67647059 0.44444444 0.5106383  ... 0.46666667 0.9375     0.9438    ]]
(913, 9)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
13533,0.558824,0.488889,0.617021,0.000000,1.0,0.684211,0.933333,0.110967,0.000000
13534,0.500000,0.566667,0.723404,0.000000,1.0,0.736842,1.000000,0.000000,0.000000
13543,0.382353,0.222222,0.829787,0.000000,1.0,0.578947,0.000000,0.000000,0.000000
13544,0.382353,0.177778,0.840426,0.000000,1.0,0.578947,0.066667,0.000000,0.000300
13545,0.352941,0.077778,0.851064,0.071429,1.0,0.578947,0.133333,0.000067,0.415467
...,...,...,...,...,...,...,...,...,...
16546,0.500000,0.411111,0.819149,0.214286,0.5,0.789474,0.200000,0.435333,0.795400
16547,0.529412,0.444444,0.744681,0.285714,1.0,0.789474,0.266667,0.795400,0.900500
16548,0.588235,0.566667,0.659574,0.571429,1.0,0.789474,0.333333,0.896833,0.924767
16549,0.647059,0.522222,0.574468,0.857143,0.5,0.789474,0.400000,0.924767,0.935967
16550,0.676471,0.444444,0.510638,0.857143,0.5,0.789474,0.466667,0.937500,0.943800

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.73529412 0.35555556 0.46808511 ... 0.53333333 0.95086667 0.95016667]
 [0.73529412 0.35555556 0.44680851 ... 0.6        0.95153333 0.95743333]
 [0.76470588 0.4        0.42553191 ... 0.66666667 0.95743333 0.8989    ]
 ...
 [0.47058824 0.         0.69148936 ... 0.26666667 0.58793333 0.767     ]
 [0.52941176 0.         0.57446809 ... 0.33333333 0.77796667 0.87186667]
 [0.64705882 0.         0.40425532 ... 0.46666667 0.8759     0.8551    ]]
(914, 9)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
16551,0.735294,0.355556,0.468085,0.857143,0.25,0.736842,0.533333,0.950867,0.950167
16552,0.735294,0.355556,0.446809,0.642857,0.25,0.789474,0.600000,0.951533,0.957433
16553,0.764706,0.400000,0.425532,0.357143,0.00,0.789474,0.666667,0.957433,0.898900
16554,0.735294,0.488889,0.446809,0.214286,0.25,0.789474,0.733333,0.898900,0.878400
16555,0.705882,0.488889,0.500000,0.071429,1.00,0.789474,0.800000,0.877867,0.777867
...,...,...,...,...,...,...,...,...,...
18273,0.382353,0.000000,0.861702,0.071429,0.75,0.578947,0.133333,0.002233,0.243400
18274,0.411765,0.000000,0.819149,0.142857,0.75,0.631579,0.200000,0.245200,0.600467
18275,0.470588,0.000000,0.691489,0.285714,0.50,0.631579,0.266667,0.587933,0.767000
18276,0.529412,0.000000,0.574468,0.357143,0.50,0.578947,0.333333,0.777967,0.871867
18278,0.647059,0.000000,0.404255,0.500000,0.75,0.526316,0.466667,0.875900,0.855100

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[4.32432432e-01 7.77777778e-02 9.06250000e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.32432432e-01 7.77777778e-02 9.37500000e-01 ... 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [4.05405405e-01 5.55555556e-02 9.68750000e-01 ... 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [4.32432432e-01 0.00000000e+00 6.97916667e-01 ... 2.66666667e-01
  5.87933333e-01 7.67000000e-01]
 [4.86486486e-01 0.00000000e+00 5.83333333e-01 ... 3.33333333e-01
  7.77966667e-01 8.71866667e-01]
 [5.94594595e-01 0.00000000e+00 4.16666667e-01 ... 4.66666667e-01
  8.75900000e-01 8.55100000e-01]]
(6090, 9)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.432432,0.077778,0.906250,0.000000,0.75,0.75,0.000000,0.000000,0.000000
31,0.432432,0.077778,0.937500,0.000000,0.50,0.80,0.066667,0.000000,0.000219
32,0.405405,0.055556,0.968750,0.000000,0.50,0.75,0.133333,0.000000,0.018681
33,0.432432,0.000000,0.927083,0.071429,0.25,0.80,0.200000,0.014627,0.257353
34,0.459459,0.000000,0.843750,0.142857,0.25,0.75,0.266667,0.196933,0.314437
...,...,...,...,...,...,...,...,...,...
18273,0.351351,0.000000,0.864583,0.071429,0.75,0.55,0.133333,0.002233,0.243400
18274,0.378378,0.000000,0.822917,0.142857,0.75,0.60,0.200000,0.245200,0.600467
18275,0.432432,0.000000,0.697917,0.285714,0.50,0.60,0.266667,0.587933,0.767000
18276,0.486486,0.000000,0.583333,0.357143,0.50,0.55,0.333333,0.777967,0.871867
18278,0.594595,0.000000,0.416667,0.500000,0.75,0.50,0.466667,0.875900,0.855100

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.8077    ]
 [0.59663333]
 [0.11096667]]
(4263, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
13522    0.444233
13529    0.868733
13530    0.807700
13531    0.596633
13532    0.110967

[4263 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.66666667e-05]
 [1.89933333e-01]
 [6.10200000e-01]
 [7.91700000e-01]
 [8.05833333e-01]
 [7.12233333e-01]
 [6.85733333e-01]
 [6.81133333e-01]
 [7.68600000e-01]
 [9.80400000e-01]
 [7.70233333e-01]
 [4.56866667e-01]
 [1.07900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.56133333e-01]
 [4.50066667e-01]
 [6.51266667e-01]
 [9.75433333e-01]
 [9.28733333e-01]
 [9.71900000e-01]
 [9.31933333e-01]
 [5.67633333e-01]
 [6.32233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.74833333e-01]
 [6.28000000e-01]
 [7.55433333e-01]
 [7.36500000e-01]
 [7.29200000e-01]
 [6.37000000e-01]
 [7.18033333e-01]
 [5.17733333e-01]
 [1.03866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.66666667e-04]
 [0.00000000e+00]
 [6.66666667e-05]
 [5.93533333e-01]
 [6.18800000e-01]
 [8.85000000e-01]
 [8.95366667e-01]
 [8.79966667e-01]
 [8.78133333e-01]
 [0.00000000e+00]
 [4.00000000e-04]
 [5.93533333e-01]
 [6.08633333e-01]
 [9.83666667e-02]
 [6.66666667e-05]
 [0.00000000e+00]
 [1.06333333e-02]
 [7.41066667e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.67033333e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.33000000e-02]
 [3.42366667e-01]
 [8.38633333e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38166667e-01]
 [0.00000000e+00]
 [3.52166667e-01]
 [8.19466667e-01]
 [9.29666667e-01]
 [0.00000000e+00]
 [1.32333333e-02]
 [2.79033333e-01]
 [6.55566667e-01]
 [7.40466667e-01]
 [1.23333333e-03]
 [0.00000000e+00]
 [1.65666667e-02]
 [1.43233333e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [9.19733333e-01]
 [8.85233333e-01]
 [7.12900000e-01]
 [1.93533333e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06333333e-02]
 [2.73866667e-01]
 [7.52966667e-01]
 [7.50966667e-01]
 [6.56566667e-01]
 [6.55966667e-01]
 [6.14533333e-01]
 [0.00000000e+00]
 [1.38333333e-02]
 [3.42366667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [1.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.19666667e-02]
 [2.73866667e-01]
 [6.63866667e-01]
 [7.43800000e-01]
 [1.76666667e-03]
 [0.00000000e+00]
 [3.10300000e-01]
 [7.40766667e-01]
 [9.27233333e-01]
 [1.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.34333333e-02]
 [2.91733333e-01]
 [7.18000000e-01]
 [7.64600000e-01]
 [7.68100000e-01]
 [7.65933333e-01]
 [7.58566667e-01]
 [7.55666667e-01]
 [6.59333333e-01]
 [7.54133333e-01]
 [7.20366667e-01]
 [6.26533333e-01]
 [1.58300000e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [1.95000000e-02]
 [8.57333333e-01]
 [7.59900000e-01]
 [7.50133333e-01]
 [7.21133333e-01]
 [5.39600000e-01]
 [1.97433333e-01]
 [2.83333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.01000000e-02]
 [3.54100000e-01]
 [8.48900000e-01]
 [8.57233333e-01]
 [8.53933333e-01]
 [7.48133333e-01]
 [7.17766667e-01]
 [6.09200000e-01]
 [1.62733333e-01]
 [3.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.94666667e-02]
 [7.90333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79333333e-02]
 [3.94066667e-01]
 [2.65466667e-01]
 [4.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38000000e-02]
 [2.01066667e-01]
 [4.30800000e-01]
 [4.64833333e-01]
 [4.58433333e-01]
 [4.54800000e-01]
 [7.52700000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.74700000e-01]
 [2.56866667e-01]
 [5.13333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.10666667e-02]
 [4.37533333e-01]
 [8.85433333e-01]
 [2.49433333e-01]
 [2.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.64000000e-02]
 [3.85233333e-01]
 [8.97466667e-01]
 [6.85333333e-01]
 [2.01966667e-01]
 [0.00000000e+00]
 [2.15666667e-02]
 [2.66666667e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.30666667e-02]
 [2.81900000e-01]
 [5.97866667e-01]
 [7.57933333e-01]
 [9.64766667e-01]
 [9.81133333e-01]
 [9.63200000e-01]
 [9.37400000e-01]
 [9.37700000e-01]
 [9.21500000e-01]
 [0.00000000e+00]
 [3.00666667e-02]
 [4.26866667e-01]
 [4.10000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.46000000e-02]
 [4.65733333e-01]
 [8.82200000e-01]
 [9.89600000e-01]
 [0.00000000e+00]
 [4.58333333e-02]
 [4.38600000e-01]
 [8.90033333e-01]
 [9.74766667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [4.22800000e-01]
 [7.70600000e-01]
 [8.59000000e-01]
 [9.42933333e-01]
 [2.73700000e-01]
 [9.46666667e-03]
 [7.20566667e-01]
 [6.79966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.27333333e-02]
 [0.00000000e+00]
 [4.67666667e-02]
 [3.91000000e-01]
 [6.52300000e-01]
 [6.32733333e-01]
 [2.85100000e-01]
 [9.70000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.62000000e-02]
 [3.79400000e-01]
 [0.00000000e+00]
 [4.92333333e-02]
 [3.97033333e-01]
 [8.50133333e-01]
 [8.45200000e-01]
 [8.39266667e-01]
 [7.20000000e-01]
 [6.84566667e-01]
 [5.74900000e-01]
 [2.98200000e-01]
 [1.05000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [3.93466667e-01]
 [6.52300000e-01]
 [7.27966667e-01]
 [7.46533333e-01]
 [7.53633333e-01]
 [7.46500000e-01]
 [7.46100000e-01]
 [7.41400000e-01]
 [7.23333333e-01]
 [6.80400000e-01]
 [5.75633333e-01]
 [2.28066667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93333333e-02]
 [3.28866667e-01]
 [5.70766667e-01]
 [7.19233333e-01]
 [7.46533333e-01]
 [6.60366667e-01]
 [6.50233333e-01]
 [7.46100000e-01]
 [7.41166667e-01]
 [6.29900000e-01]
 [5.94966667e-01]
 [5.82866667e-01]
 [2.26866667e-01]
 [7.63333333e-03]
 [0.00000000e+00]
 [9.36033333e-01]
 [9.33266667e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [7.64966667e-01]
 [5.11633333e-01]
 [1.64200000e-01]
 [6.30000000e-03]
 [0.00000000e+00]
 [5.74666667e-02]
 [8.66500000e-01]
 [9.17300000e-01]
 [9.00000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.69333333e-02]
 [4.74933333e-01]
 [9.83333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.70000000e-02]
 [0.00000000e+00]
 [5.74000000e-02]
 [8.79000000e-02]
 [4.69800000e-01]
 [0.00000000e+00]
 [6.09333333e-02]
 [7.74533333e-01]
 [7.62633333e-01]
 [7.27633333e-01]
 [7.73966667e-01]
 [6.46766667e-01]
 [2.82900000e-01]
 [0.00000000e+00]
 [6.44000000e-02]
 [9.62033333e-01]
 [9.68766667e-01]
 [9.57766667e-01]
 [7.29533333e-01]
 [6.95366667e-01]
 [5.77333333e-01]
 [2.26266667e-01]
 [1.72666667e-02]
 [0.00000000e+00]
 [9.01000000e-02]
 [4.69800000e-01]
 [8.38900000e-01]
 [9.05900000e-01]
 [9.35533333e-01]
 [9.44133333e-01]
 [8.43766667e-01]
 [8.16666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.16333333e-02]
 [0.00000000e+00]
 [6.44000000e-02]
 [6.95666667e-01]
 [3.56766667e-01]
 [3.35000000e-02]
 [0.00000000e+00]
 [9.47066667e-01]
 [9.45433333e-01]
 [9.45800000e-01]
 [7.96200000e-01]
 [7.39633333e-01]
 [3.73166667e-01]
 [0.00000000e+00]
 [4.23966667e-01]
 [3.38000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.02566667e-01]
 [0.00000000e+00]
 [6.62666667e-02]
 [0.00000000e+00]
 [8.04333333e-02]
 [9.58866667e-01]
 [9.52633333e-01]
 [9.35400000e-01]
 [9.10900000e-01]
 [8.24166667e-01]
 [4.55966667e-01]
 [3.94000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.43666667e-02]
 [9.62800000e-01]
 [9.59466667e-01]
 [9.40766667e-01]
 [9.10900000e-01]
 [8.24166667e-01]
 [4.66833333e-01]
 [3.79000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.46333333e-02]
 [3.55166667e-01]
 [4.67333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.71000000e-02]
 [5.83100000e-01]
 [4.40000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.38000000e-02]
 [5.05000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.76333333e-02]
 [5.28933333e-01]
 [4.12333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.21533333e-01]
 [0.00000000e+00]
 [7.79333333e-02]
 [5.26466667e-01]
 [0.00000000e+00]
 [7.81000000e-02]
 [9.40466667e-01]
 [9.21400000e-01]
 [8.56933333e-01]
 [6.90300000e-01]
 [6.94800000e-01]
 [3.18100000e-01]
 [2.86666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.33333333e-03]
 [4.65666667e-02]
 [7.42000000e-02]
 [8.20000000e-02]
 [8.50000000e-02]
 [8.47666667e-02]
 [8.45333333e-02]
 [8.44333333e-02]
 [8.40333333e-02]
 [9.64666667e-02]
 [7.80000000e-02]
 [6.91000000e-02]
 [1.18933333e-01]
 [1.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.42333333e-02]
 [4.01966667e-01]
 [5.76600000e-01]
 [6.37700000e-01]
 [7.58100000e-01]
 [9.47766667e-01]
 [9.39166667e-01]
 [9.36533333e-01]
 [9.28800000e-01]
 [9.14933333e-01]
 [8.66766667e-01]
 [7.66066667e-01]
 [3.96400000e-01]
 [3.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93666667e-02]
 [5.16633333e-01]
 [8.24633333e-01]
 [5.73933333e-01]
 [5.94400000e-01]
 [5.94600000e-01]
 [5.91666667e-01]
 [5.92500000e-01]
 [5.87833333e-01]
 [9.12000000e-01]
 [8.67033333e-01]
 [7.66066667e-01]
 [3.58066667e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.50000000e-02]
 [4.14800000e-01]
 [6.60433333e-01]
 [5.73933333e-01]
 [5.93733333e-01]
 [5.93833333e-01]
 [9.39700000e-01]
 [9.37200000e-01]
 [9.31833333e-01]
 [9.15333333e-01]
 [8.69733333e-01]
 [7.66066667e-01]
 [2.85400000e-01]
 [2.41000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.02333333e-02]
 [5.16633333e-01]
 [8.24900000e-01]
 [9.11033333e-01]
 [9.44466667e-01]
 [9.44500000e-01]
 [9.40966667e-01]
 [9.39266667e-01]
 [9.34466667e-01]
 [2.74366667e-01]
 [2.60033333e-01]
 [2.31266667e-01]
 [1.94666667e-01]
 [1.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.17866667e-01]
 [8.29166667e-01]
 [9.15400000e-01]
 [9.44733333e-01]
 [9.43500000e-01]
 [9.39166667e-01]
 [9.36966667e-01]
 [9.28800000e-01]
 [9.12000000e-01]
 [7.80066667e-01]
 [6.94600000e-01]
 [3.62366667e-01]
 [4.52666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.46133333e-01]
 [8.40400000e-01]
 [9.17433333e-01]
 [9.47766667e-01]
 [4.29066667e-01]
 [4.73666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.25000000e-02]
 [5.39233333e-01]
 [8.24700000e-01]
 [9.11100000e-01]
 [9.41333333e-01]
 [9.48033333e-01]
 [9.48033333e-01]
 [9.54433333e-01]
 [9.52033333e-01]
 [9.23300000e-01]
 [9.01833333e-01]
 [8.13533333e-01]
 [4.57200000e-01]
 [4.96666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.18166667e-01]
 [8.30233333e-01]
 [9.11033333e-01]
 [9.44333333e-01]
 [9.42833333e-01]
 [9.39166667e-01]
 [9.36533333e-01]
 [9.30366667e-01]
 [9.12000000e-01]
 [8.66766667e-01]
 [7.00066667e-01]
 [4.08500000e-01]
 [4.69000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.81666667e-02]
 [5.21533333e-01]
 [8.27466667e-01]
 [9.11033333e-01]
 [9.48200000e-01]
 [9.41766667e-01]
 [9.39166667e-01]
 [9.36533333e-01]
 [6.73133333e-01]
 [9.12000000e-01]
 [6.24066667e-01]
 [5.01733333e-01]
 [3.64933333e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.21333333e-02]
 [5.18833333e-01]
 [8.27000000e-01]
 [9.11233333e-01]
 [8.55500000e-01]
 [9.41933333e-01]
 [9.39166667e-01]
 [9.36533333e-01]
 [9.33866667e-01]
 [8.21300000e-01]
 [7.80066667e-01]
 [5.63466667e-01]
 [4.56366667e-01]
 [3.40666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.71666667e-02]
 [3.60533333e-01]
 [5.79133333e-01]
 [5.85166667e-01]
 [6.07233333e-01]
 [6.03966667e-01]
 [5.94433333e-01]
 [5.88066667e-01]
 [5.90700000e-01]
 [4.46866667e-01]
 [4.23133333e-01]
 [3.83533333e-01]
 [3.29333333e-01]
 [2.31666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.54666667e-02]
 [4.35333333e-01]
 [7.98266667e-01]
 [8.94266667e-01]
 [9.26166667e-01]
 [9.23133333e-01]
 [9.23166667e-01]
 [9.15533333e-01]
 [9.10633333e-01]
 [8.98900000e-01]
 [8.64466667e-01]
 [7.71566667e-01]
 [3.93133333e-01]
 [3.28333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.59666667e-02]
 [4.37000000e-01]
 [7.98366667e-01]
 [8.97400000e-01]
 [9.27600000e-01]
 [9.21233333e-01]
 [9.18966667e-01]
 [9.15533333e-01]
 [9.10633333e-01]
 [8.98900000e-01]
 [8.61733333e-01]
 [7.76033333e-01]
 [4.13500000e-01]
 [2.87333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [8.01333333e-01]
 [8.94866667e-01]
 [9.24766667e-01]
 [9.21233333e-01]
 [9.18966667e-01]
 [9.17300000e-01]
 [9.13500000e-01]
 [9.04766667e-01]
 [8.61733333e-01]
 [7.70200000e-01]
 [3.63266667e-01]
 [2.91333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93666667e-02]
 [3.98566667e-01]
 [8.03900000e-01]
 [8.94266667e-01]
 [3.93233333e-01]
 [3.23666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.30333333e-02]
 [3.24500000e-01]
 [5.35133333e-01]
 [1.96366667e-01]
 [1.84000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [3.27266667e-01]
 [3.02333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [8.86933333e-01]
 [9.00000000e-01]
 [9.00000000e-01]
 [8.73666667e-01]
 [9.00000000e-01]
 [8.46033333e-01]
 [8.59966667e-01]
 [8.00666667e-01]
 [7.70200000e-01]
 [4.20766667e-01]
 [3.89333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.09666667e-02]
 [4.37133333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.30400000e-01]
 [9.21233333e-01]
 [8.30000000e-01]
 [3.53833333e-01]
 [4.79333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.08333333e-02]
 [2.51400000e-01]
 [4.96333333e-01]
 [5.67933333e-01]
 [6.47633333e-01]
 [6.30766667e-01]
 [6.51766667e-01]
 [7.19033333e-01]
 [7.63500000e-01]
 [7.98700000e-01]
 [7.40133333e-01]
 [6.64433333e-01]
 [2.87466667e-01]
 [1.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.64666667e-01]
 [8.06500000e-01]
 [8.96166667e-01]
 [9.25000000e-01]
 [9.24933333e-01]
 [8.27066667e-01]
 [9.15533333e-01]
 [8.20566667e-01]
 [6.51200000e-01]
 [5.56433333e-01]
 [5.66766667e-01]
 [3.28733333e-01]
 [5.51000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.87666667e-02]
 [2.30066667e-01]
 [4.55966667e-01]
 [6.44833333e-01]
 [6.65833333e-01]
 [6.64366667e-01]
 [6.62500000e-01]
 [6.60866667e-01]
 [5.76833333e-01]
 [3.14633333e-01]
 [3.01600000e-01]
 [4.34866667e-01]
 [3.04900000e-01]
 [3.72000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40333333e-02]
 [1.79900000e-01]
 [4.45933333e-01]
 [3.23633333e-01]
 [2.70000000e-01]
 [2.67866667e-01]
 [2.67633333e-01]
 [2.89733333e-01]
 [1.60966667e-01]
 [2.01200000e-01]
 [2.51800000e-01]
 [3.47666667e-01]
 [1.97800000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.68333333e-02]
 [1.82600000e-01]
 [3.02933333e-01]
 [3.23700000e-01]
 [4.05000000e-01]
 [3.21633333e-01]
 [4.03566667e-01]
 [3.62166667e-01]
 [3.62166667e-01]
 [4.34600000e-01]
 [3.77100000e-01]
 [3.48466667e-01]
 [1.59200000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [4.98800000e-01]
 [8.45100000e-01]
 [8.95933333e-01]
 [9.00000000e-01]
 [8.86300000e-01]
 [9.00000000e-01]
 [8.04800000e-01]
 [3.46933333e-01]
 [2.03733333e-01]
 [1.49000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.14000000e-02]
 [2.26800000e-01]
 [3.50033333e-01]
 [4.38233333e-01]
 [5.17866667e-01]
 [6.63300000e-01]
 [7.36333333e-01]
 [7.55366667e-01]
 [7.56900000e-01]
 [3.86933333e-01]
 [3.65466667e-01]
 [3.29300000e-01]
 [2.42966667e-01]
 [2.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79666667e-02]
 [2.78633333e-01]
 [4.04633333e-01]
 [3.82500000e-01]
 [3.96600000e-01]
 [3.95833333e-01]
 [3.86166667e-01]
 [5.20300000e-01]
 [4.55600000e-01]
 [3.93566667e-01]
 [2.66166667e-01]
 [2.36933333e-01]
 [2.46166667e-01]
 [2.48333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20333333e-02]
 [2.95566667e-01]
 [4.52433333e-01]
 [5.00800000e-01]
 [4.54266667e-01]
 [4.54900000e-01]
 [4.53766667e-01]
 [2.79633333e-01]
 [2.82066667e-01]
 [2.80133333e-01]
 [2.70033333e-01]
 [4.37733333e-01]
 [2.42166667e-01]
 [2.97333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.84000000e-02]
 [2.61400000e-01]
 [5.28433333e-01]
 [5.05033333e-01]
 [3.92000000e-01]
 [4.50100000e-01]
 [3.92066667e-01]
 [3.91766667e-01]
 [4.46200000e-01]
 [5.84066667e-01]
 [8.93633333e-01]
 [7.99433333e-01]
 [3.90766667e-01]
 [4.55000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93000000e-02]
 [3.93100000e-01]
 [7.95400000e-01]
 [9.24766667e-01]
 [3.98433333e-01]
 [4.66000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.00500000e-01]
 [9.24766667e-01]
 [9.35966667e-01]
 [9.43800000e-01]
 [9.50166667e-01]
 [9.57433333e-01]
 [8.98900000e-01]
 [8.78400000e-01]
 [7.77866667e-01]
 [3.56300000e-01]
 [3.35333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.96833333e-01]
 [9.24766667e-01]
 [9.37500000e-01]
 [9.50866667e-01]]
(913, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
13533    0.000000
13534    0.000000
13543    0.000000
13544    0.000067
13545    0.189933
...           ...
16546    0.795400
16547    0.896833
16548    0.924767
16549    0.937500
16550    0.950867

[913 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[9.51533333e-01]
 [9.57433333e-01]
 [8.98900000e-01]
 [8.77866667e-01]
 [7.85400000e-01]
 [3.59033333e-01]
 [3.83666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.33400000e-01]
 [8.52400000e-01]
 [8.32100000e-01]
 [9.52200000e-01]
 [6.61300000e-01]
 [6.58233333e-01]
 [5.76366667e-01]
 [4.95800000e-01]
 [3.77400000e-01]
 [1.65566667e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.93000000e-02]
 [1.40800000e-01]
 [2.47800000e-01]
 [3.81700000e-01]
 [3.92633333e-01]
 [3.94533333e-01]
 [4.66566667e-01]
 [4.48600000e-01]
 [5.12533333e-01]
 [5.03500000e-01]
 [6.21466667e-01]
 [7.75366667e-01]
 [1.92633333e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.38333333e-02]
 [4.69166667e-01]
 [8.33500000e-01]
 [8.16000000e-01]
 [6.67466667e-01]
 [6.60733333e-01]
 [6.64166667e-01]
 [6.88000000e-01]
 [6.62833333e-01]
 [6.58766667e-01]
 [6.36333333e-01]
 [8.15333333e-01]
 [4.41033333e-01]
 [4.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.23966667e-01]
 [9.25500000e-01]
 [9.15766667e-01]
 [9.10633333e-01]
 [8.99166667e-01]
 [8.67500000e-01]
 [7.71733333e-01]
 [3.93133333e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43333333e-02]
 [4.39333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.21233333e-01]
 [9.21500000e-01]
 [9.15533333e-01]
 [9.11333333e-01]
 [8.98900000e-01]
 [8.61733333e-01]
 [7.70200000e-01]
 [4.02500000e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.31433333e-01]
 [9.24466667e-01]
 [9.28533333e-01]
 [9.15533333e-01]
 [9.10633333e-01]
 [9.00833333e-01]
 [8.61766667e-01]
 [7.73533333e-01]
 [3.93266667e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.58666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [7.16600000e-01]
 [7.40700000e-01]
 [7.37000000e-01]
 [8.37933333e-01]
 [5.51500000e-01]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.73900000e-01]
 [9.24566667e-01]
 [9.46466667e-01]
 [9.50366667e-01]
 [9.40766667e-01]
 [9.15500000e-01]
 [8.97933333e-01]
 [7.70200000e-01]
 [3.61466667e-01]
 [2.55333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.38900000e-01]
 [7.95400000e-01]
 [3.72433333e-01]
 [3.53000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.11666667e-02]
 [2.98100000e-01]
 [2.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [2.97733333e-01]
 [7.97666667e-01]
 [8.92133333e-01]
 [7.25433333e-01]
 [8.26266667e-01]
 [9.10100000e-01]
 [7.86433333e-01]
 [6.91966667e-01]
 [6.38066667e-01]
 [3.46200000e-01]
 [2.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.68666667e-02]
 [4.04933333e-01]
 [7.88133333e-01]
 [8.82633333e-01]
 [0.00000000e+00]
 [2.79000000e-02]
 [3.97200000e-01]
 [7.90900000e-01]
 [2.27666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.82000000e-02]
 [4.01833333e-01]
 [7.97833333e-01]
 [2.35333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.41666667e-02]
 [3.93333333e-01]
 [8.23766667e-01]
 [9.00666667e-01]
 [9.26133333e-01]
 [3.41100000e-01]
 [1.93333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.08000000e-02]
 [3.21433333e-01]
 [7.44300000e-01]
 [8.14833333e-01]
 [8.34400000e-01]
 [8.19566667e-01]
 [8.20200000e-01]
 [2.13000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.10000000e-02]
 [3.20100000e-01]
 [6.98633333e-01]
 [9.21966667e-01]
 [1.67000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20666667e-02]
 [3.70033333e-01]
 [7.77866667e-01]
 [8.81166667e-01]
 [8.31533333e-01]
 [7.37833333e-01]
 [7.26966667e-01]
 [2.81066667e-01]
 [1.45000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40666667e-02]
 [3.77433333e-01]
 [7.84366667e-01]
 [9.24733333e-01]
 [9.35033333e-01]
 [9.05133333e-01]
 [6.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.28000000e-02]
 [3.40100000e-01]
 [7.78033333e-01]
 [8.86700000e-01]
 [9.26266667e-01]
 [6.40000000e-01]
 [2.28866667e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.38000000e-02]
 [3.74066667e-01]
 [7.80300000e-01]
 [8.81166667e-01]
 [9.25566667e-01]
 [9.39433333e-01]
 [9.08933333e-01]
 [9.06166667e-01]
 [8.78966667e-01]
 [8.30166667e-01]
 [6.45466667e-01]
 [2.28866667e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06666667e-02]
 [2.83600000e-01]
 [6.43000000e-01]
 [7.04933333e-01]
 [7.41166667e-01]
 [7.39366667e-01]
 [7.27166667e-01]
 [7.26000000e-01]
 [9.05766667e-01]
 [9.07400000e-01]
 [8.90533333e-01]
 [7.13766667e-01]
 [2.54600000e-01]
 [1.52666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.38166667e-01]
 [7.77400000e-01]
 [8.85766667e-01]
 [9.23933333e-01]
 [9.30766667e-01]
 [9.24666667e-01]
 [9.19000000e-01]
 [6.03566667e-01]
 [3.52733333e-01]
 [7.50000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.99333333e-02]
 [3.41533333e-01]
 [7.73633333e-01]
 [9.07933333e-01]
 [9.37200000e-01]
 [9.37400000e-01]
 [9.06800000e-01]
 [9.11566667e-01]
 [8.14766667e-01]
 [7.83766667e-01]
 [7.45333333e-01]
 [5.94366667e-01]
 [3.37800000e-01]
 [5.93333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.63333333e-01]
 [7.73633333e-01]
 [8.95666667e-01]
 [9.39000000e-01]
 [9.42600000e-01]
 [9.48766667e-01]
 [9.54000000e-01]
 [9.46133333e-01]
 [7.09900000e-01]
 [7.39966667e-01]
 [5.75833333e-01]
 [2.85466667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74333333e-02]
 [3.84800000e-01]
 [8.13333333e-01]
 [9.17600000e-01]
 [9.38200000e-01]
 [9.34533333e-01]
 [9.24633333e-01]
 [9.16733333e-01]
 [9.43433333e-01]
 [9.25966667e-01]
 [8.90533333e-01]
 [6.74700000e-01]
 [2.71400000e-01]
 [9.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74000000e-02]
 [3.83966667e-01]
 [8.16733333e-01]
 [9.14666667e-01]
 [9.40133333e-01]
 [9.33866667e-01]
 [9.32600000e-01]
 [6.02600000e-01]
 [2.77466667e-01]
 [8.63333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.84333333e-02]
 [3.84966667e-01]
 [8.08000000e-01]
 [7.33100000e-01]
 [7.46000000e-01]
 [7.52033333e-01]
 [5.51133333e-01]
 [2.46333333e-01]
 [6.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.14333333e-02]
 [2.73366667e-01]
 [6.37833333e-01]
 [7.21900000e-01]
 [7.56166667e-01]
 [7.46266667e-01]
 [7.46633333e-01]
 [5.15266667e-01]
 [1.83066667e-01]
 [9.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.46000000e-02]
 [2.85633333e-01]
 [9.27366667e-01]
 [6.06666667e-01]
 [7.76666667e-02]
 [4.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.52000000e-02]
 [2.73033333e-01]
 [9.27566667e-01]
 [9.41866667e-01]
 [9.33366667e-01]
 [7.44100000e-01]
 [7.14833333e-01]
 [7.25100000e-01]
 [5.23400000e-01]
 [1.26766667e-01]
 [5.33333333e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [7.29566667e-01]
 [2.75333333e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.98300000e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [9.62066667e-01]
 [8.62166667e-01]
 [7.64166667e-01]
 [7.56000000e-01]
 [7.40766667e-01]
 [7.16733333e-01]
 [5.98633333e-01]
 [1.88466667e-01]
 [4.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.99666667e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [5.03333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [4.06533333e-01]
 [8.33866667e-01]
 [2.34266667e-01]
 [7.83333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.39333333e-02]
 [3.30833333e-01]
 [7.73633333e-01]
 [8.81166667e-01]
 [9.21966667e-01]
 [9.21033333e-01]
 [9.06800000e-01]
 [9.06933333e-01]
 [9.03266667e-01]
 [9.02433333e-01]
 [8.79166667e-01]
 [5.79833333e-01]
 [2.10933333e-01]
 [5.03333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.44333333e-02]
 [3.70966667e-01]
 [8.09266667e-01]
 [9.07600000e-01]
 [9.53733333e-01]
 [9.31633333e-01]
 [9.30366667e-01]
 [6.07300000e-01]
 [1.83066667e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.35200000e-01]
 [7.74566667e-01]
 [9.60833333e-01]
 [6.48400000e-01]
 [2.28866667e-01]
 [6.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38666667e-02]
 [2.64666667e-01]
 [6.18900000e-01]
 [7.96200000e-01]
 [8.29766667e-01]
 [9.11966667e-01]
 [8.15833333e-01]
 [6.49700000e-01]
 [4.90866667e-01]
 [5.97933333e-01]
 [5.74700000e-01]
 [2.05966667e-01]
 [4.26666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.30833333e-01]
 [6.96266667e-01]
 [7.06233333e-01]
 [8.29766667e-01]
 [8.28933333e-01]
 [8.16133333e-01]
 [6.59100000e-01]
 [5.80033333e-01]
 [5.57333333e-01]
 [4.02866667e-01]
 [3.13033333e-01]
 [1.28166667e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [1.78433333e-01]
 [3.79433333e-01]
 [3.75233333e-01]
 [3.85633333e-01]
 [3.87033333e-01]
 [3.81100000e-01]
 [3.83566667e-01]
 [3.82533333e-01]
 [4.38100000e-01]
 [3.54066667e-01]
 [1.92900000e-01]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.00000000e-04]
 [2.86666667e-02]
 [6.97000000e-02]
 [8.04000000e-02]
 [8.28000000e-02]
 [8.28333333e-02]
 [8.20000000e-02]
 [8.22000000e-02]
 [8.19000000e-02]
 [8.04666667e-02]
 [7.58666667e-02]
 [5.74000000e-02]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.26666667e-03]
 [9.30666667e-02]
 [3.39300000e-01]
 [3.83733333e-01]
 [3.90233333e-01]
 [2.78633333e-01]
 [2.72633333e-01]
 [2.73966667e-01]
 [2.74900000e-01]
 [5.11933333e-01]
 [4.20900000e-01]
 [3.76766667e-01]
 [6.52000000e-02]
 [1.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.30000000e-03]
 [1.54933333e-01]
 [3.28166667e-01]
 [5.02700000e-01]
 [5.86100000e-01]
 [4.40233333e-01]
 [5.66333333e-01]
 [5.14266667e-01]
 [5.08466667e-01]
 [5.00700000e-01]
 [5.39333333e-01]
 [2.12300000e-01]
 [6.03000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.13333333e-03]
 [1.88500000e-01]
 [6.96900000e-01]
 [5.36066667e-01]
 [4.37866667e-01]
 [3.77233333e-01]
 [2.66866667e-01]
 [8.25666667e-02]
 [2.68533333e-01]
 [3.12933333e-01]
 [4.77433333e-01]
 [6.67000000e-02]
 [5.01333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.96666667e-03]
 [1.77100000e-01]
 [3.93700000e-01]
 [5.02500000e-01]
 [6.47000000e-01]
 [3.82966667e-01]
 [3.78000000e-01]
 [3.83566667e-01]
 [4.38633333e-01]
 [5.06533333e-01]
 [5.61666667e-01]
 [3.48500000e-01]
 [8.61333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [5.00333333e-01]
 [6.83066667e-01]
 [5.24566667e-01]
 [5.60100000e-01]
 [9.21400000e-01]
 [6.55933333e-01]
 [8.94100000e-01]
 [8.00000000e-01]
 [6.40133333e-01]
 [1.37500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.36666667e-03]
 [2.95566667e-01]
 [8.06100000e-01]
 [8.52600000e-01]
 [5.25600000e-01]
 [4.98400000e-01]
 [5.84866667e-01]
 [7.04733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98800000e-01]
 [7.79066667e-01]
 [8.98533333e-01]
 [9.48700000e-01]
 [9.34233333e-01]
 [8.91733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.70000000e-03]
 [3.06733333e-01]
 [8.07833333e-01]
 [9.19166667e-01]
 [9.24300000e-01]
 [8.98133333e-01]
 [8.89033333e-01]
 [9.23800000e-01]
 [9.13700000e-01]
 [9.08666667e-01]
 [8.72366667e-01]
 [6.23966667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98633333e-01]
 [7.87133333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [9.02866667e-01]
 [8.89033333e-01]
 [9.13233333e-01]
 [8.95133333e-01]
 [8.94100000e-01]
 [8.43033333e-01]
 [6.48733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.94566667e-01]
 [7.76166667e-01]
 [8.93433333e-01]
 [9.13266667e-01]
 [9.01833333e-01]
 [8.92866667e-01]
 [9.18500000e-01]
 [8.98700000e-01]
 [8.97766667e-01]
 [8.44533333e-01]
 [6.39566667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.86666667e-03]
 [2.35633333e-01]
 [6.19466667e-01]
 [7.35333333e-01]
 [7.29766667e-01]
 [7.18500000e-01]
 [7.14300000e-01]
 [8.21900000e-01]
 [8.08066667e-01]
 [7.15266667e-01]
 [5.39566667e-01]
 [3.49433333e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [8.97600000e-01]
 [9.12233333e-01]
 [9.00266667e-01]
 [8.92866667e-01]
 [9.13233333e-01]
 [8.09666667e-01]
 [5.72233333e-01]
 [6.07633333e-01]
 [3.05733333e-01]
 [5.46333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.63333333e-03]
 [2.15000000e-01]
 [7.74333333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [8.98133333e-01]
 [8.96733333e-01]
 [9.13233333e-01]
 [8.06333333e-01]
 [8.04666667e-01]
 [5.39566667e-01]
 [2.62066667e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [2.88766667e-01]
 [7.75733333e-01]
 [6.45166667e-01]
 [6.57400000e-01]
 [6.46866667e-01]
 [8.97500000e-01]
 [9.14166667e-01]
 [8.99200000e-01]
 [4.99600000e-01]
 [4.78266667e-01]
 [3.27833333e-01]
 [9.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.70000000e-03]
 [2.50900000e-01]
 [7.80300000e-01]
 [9.22300000e-01]
 [9.05033333e-01]
 [8.92166667e-01]
 [7.82100000e-01]
 [8.68366667e-01]
 [9.14033333e-01]
 [8.74466667e-01]
 [8.31300000e-01]
 [5.14600000e-01]
 [5.67000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.60266667e-01]
 [8.07900000e-01]
 [9.17700000e-01]
 [9.27500000e-01]
 [9.22000000e-01]
 [8.93833333e-01]
 [9.09000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.70000000e-03]
 [2.93166667e-01]
 [8.13733333e-01]
 [9.19500000e-01]
 [9.26933333e-01]
 [9.22000000e-01]
 [9.10500000e-01]
 [8.21333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.26666667e-03]
 [2.75633333e-01]
 [7.94333333e-01]
 [9.03866667e-01]
 [9.07400000e-01]
 [8.98733333e-01]
 [8.92066667e-01]
 [7.90333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.51233333e-01]
 [7.08300000e-01]
 [8.33333333e-01]
 [9.10633333e-01]
 [9.03566667e-01]
 [8.92300000e-01]
 [7.67666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.46666667e-03]
 [2.53400000e-01]
 [7.06433333e-01]
 [8.33366667e-01]
 [9.10633333e-01]
 [8.92300000e-01]
 [8.94666667e-01]
 [8.95833333e-01]
 [7.85400000e-01]
 [6.35866667e-01]
 [4.69966667e-01]
 [6.07000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.63333333e-03]
 [2.55600000e-01]
 [7.08300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.62266667e-01]
 [7.08300000e-01]
 [8.30033333e-01]
 [8.34533333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.32966667e-01]
 [5.81266667e-01]
 [7.39900000e-01]
 [8.51400000e-01]
 [8.78800000e-01]
 [8.74666667e-01]
 [8.76966667e-01]
 [8.44766667e-01]
 [6.96133333e-01]
 [4.64233333e-01]
 [5.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43333333e-03]
 [2.47100000e-01]
 [5.77166667e-01]
 [7.70533333e-01]
 [8.57166667e-01]
 [8.81700000e-01]
 [8.04600000e-01]
 [7.14900000e-01]
 [6.26466667e-01]
 [7.77700000e-01]
 [7.27933333e-01]
 [5.15100000e-01]
 [5.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.56666667e-03]
 [2.38433333e-01]
 [5.76833333e-01]
 [7.49866667e-01]
 [8.57533333e-01]
 [8.71666667e-01]
 [8.51933333e-01]
 [8.49533333e-01]
 [8.38900000e-01]
 [8.40766667e-01]
 [6.19133333e-01]
 [4.17800000e-01]
 [4.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.43333333e-03]
 [1.98000000e-01]
 [5.41133333e-01]
 [6.99333333e-01]
 [8.47766667e-01]
 [7.96533333e-01]
 [8.54333333e-01]
 [8.54066667e-01]
 [8.42000000e-01]
 [8.43133333e-01]
 [7.60066667e-01]
 [4.76266667e-01]
 [4.14000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20000000e-03]
 [2.35666667e-01]
 [5.97333333e-01]
 [7.50633333e-01]
 [8.56600000e-01]
 [8.69633333e-01]
 [8.49933333e-01]
 [8.51833333e-01]
 [5.26033333e-01]
 [4.82666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.36666667e-03]
 [2.41600000e-01]
 [5.94133333e-01]
 [7.69900000e-01]
 [8.71333333e-01]
 [8.72700000e-01]
 [8.51966667e-01]
 [4.58333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.36666667e-03]
 [4.69000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.45200000e-01]
 [5.87933333e-01]
 [7.77966667e-01]
 [8.77433333e-01]
 [8.53266667e-01]]
(914, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
16551    0.951533
16552    0.957433
16553    0.898900
16554    0.877867
16555    0.785400
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18278    0.853267

[914 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.77796667]
 [0.87743333]
 [0.85326667]]
(6090, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18278    0.853267

[6090 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005456 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 756
[LightGBM] [Info] Number of data points in the train set: 4263, number of used features: 9
[LightGBM] [Info] Start training from score 0.312844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
16551  27911.718674
16552  28552.281566
16553  28173.508713
16554  25031.833853
16555   21975.28109
...             ...
18273   5632.366084
18274  18901.861998
18275   24148.93331
18276  25572.670269
18278  26338.372419

[914 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
16551     28546.0
16552     28723.0
16553     26967.0
16554     26336.0
16555     23562.0
...           ...
18273      7356.0
18274     17638.0
18275     23339.0
18276     26323.0
18278     25598.0

[914 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
16551     28546.0  27911.718674
16552     28723.0  28552.281566
16553     26967.0  28173.508713
16554     26336.0  25031.833853
16555     23562.0   21975.28109
...           ...           ...
18273      7356.0   5632.366084
18274     17638.0  18901.861998
18275     23339.0   24148.93331
18276     26323.0  25572.670269
18278     25598.0  26338.372419

[914 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1420.5734
RMSE: 2441.7064
R²: 0.9516

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
16551     28546.0  27911.718674  25071.187461
16552     28723.0  28552.281566  25834.987615
16553     26967.0  28173.508713  26222.885304
16554     26336.0  25031.833853    23317.3981
16555     23562.0   21975.28109  23437.167632
...           ...           ...           ...
18273      7356.0   5632.366084   5438.219944
18274     17638.0  18901.861998  18263.627162
18275     23339.0   24148.93331  21918.767881
18276     26323.0  25572.670269  24646.911253
18278     25598.0  26338.372419   26127.13712

[914 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (4215, 48, 9), y_train: (4215, 1)
X_val: (865, 48, 9), y_val: (865, 1)
X_test: (866, 48, 9), y_test: (866, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 127s 2s/step - loss: 0.2086 - mean_absolute_error: 0.3116 - mean_absolute_percentage_error: 918487.1250 - root_mean_squared_error: 0.4567 - val_loss: 0.1769 - val_mean_absolute_error: 0.2930 - val_mean_absolute_percentage_error: 4978389.5000 - val_root_mean_squared_error: 0.4206
Epoch 2/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.2031 - mean_absolute_error: 0.3107 - mean_absolute_percentage_error: 5341677.0000 - root_mean_squared_error: 0.4506 - val_loss: 0.1664 - val_mean_absolute_error: 0.2897 - val_mean_absolute_percentage_error: 11264108.0000 - val_root_mean_squared_error: 0.4080
Epoch 3/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.1897 - mean_absolute_error: 0.3041 - mean_absolute_percentage_error: 10926729.0000 - root_mean_squared_error: 0.4356 - val_loss: 0.1541 - val_mean_absolute_error: 0.2866 - val_mean_absolute_percentage_error: 19294226.0000 - val_root_mean_squared_error: 0.3926
Epoch 4/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 29s 3s/step - loss: 0.1816 - mean_absolute_error: 0.3062 - mean_absolute_percentage_error: 17688896.0000 - root_mean_squared_error: 0.4261 - val_loss: 0.1398 - val_mean_absolute_error: 0.2833 - val_mean_absolute_percentage_error: 29840410.0000 - val_root_mean_squared_error: 0.3739
Epoch 5/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1651 - mean_absolute_error: 0.3032 - mean_absolute_percentage_error: 28090640.0000 - root_mean_squared_error: 0.4062 - val_loss: 0.1242 - val_mean_absolute_error: 0.2808 - val_mean_absolute_percentage_error: 43658828.0000 - val_root_mean_squared_error: 0.3524
Epoch 6/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 33s 3s/step - loss: 0.1446 - mean_absolute_error: 0.2939 - mean_absolute_percentage_error: 41274432.0000 - root_mean_squared_error: 0.3802 - val_loss: 0.1094 - val_mean_absolute_error: 0.2800 - val_mean_absolute_percentage_error: 61324556.0000 - val_root_mean_squared_error: 0.3308
Epoch 7/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 14s 2s/step - loss: 0.1276 - mean_absolute_error: 0.2948 - mean_absolute_percentage_error: 57706088.0000 - root_mean_squared_error: 0.3572 - val_loss: 0.0995 - val_mean_absolute_error: 0.2819 - val_mean_absolute_percentage_error: 82449416.0000 - val_root_mean_squared_error: 0.3154
Epoch 8/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 30s 3s/step - loss: 0.1173 - mean_absolute_error: 0.2985 - mean_absolute_percentage_error: 75800672.0000 - root_mean_squared_error: 0.3424 - val_loss: 0.0979 - val_mean_absolute_error: 0.2877 - val_mean_absolute_percentage_error: 102814392.0000 - val_root_mean_squared_error: 0.3128
Epoch 9/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 21s 2s/step - loss: 0.1173 - mean_absolute_error: 0.3080 - mean_absolute_percentage_error: 92933952.0000 - root_mean_squared_error: 0.3425 - val_loss: 0.0996 - val_mean_absolute_error: 0.2917 - val_mean_absolute_percentage_error: 111880392.0000 - val_root_mean_squared_error: 0.3156
Epoch 10/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.1179 - mean_absolute_error: 0.3100 - mean_absolute_percentage_error: 93553608.0000 - root_mean_squared_error: 0.3433 - val_loss: 0.0984 - val_mean_absolute_error: 0.2892 - val_mean_absolute_percentage_error: 106754080.0000 - val_root_mean_squared_error: 0.3137
Epoch 11/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 30s 3s/step - loss: 0.1180 - mean_absolute_error: 0.3095 - mean_absolute_percentage_error: 87619120.0000 - root_mean_squared_error: 0.3435 - val_loss: 0.0974 - val_mean_absolute_error: 0.2855 - val_mean_absolute_percentage_error: 97703208.0000 - val_root_mean_squared_error: 0.3121
Epoch 12/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1155 - mean_absolute_error: 0.3014 - mean_absolute_percentage_error: 82330640.0000 - root_mean_squared_error: 0.3398 - val_loss: 0.0976 - val_mean_absolute_error: 0.2838 - val_mean_absolute_percentage_error: 92014952.0000 - val_root_mean_squared_error: 0.3124
Epoch 13/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 29s 3s/step - loss: 0.1157 - mean_absolute_error: 0.3001 - mean_absolute_percentage_error: 79910288.0000 - root_mean_squared_error: 0.3401 - val_loss: 0.0974 - val_mean_absolute_error: 0.2843 - val_mean_absolute_percentage_error: 94271016.0000 - val_root_mean_squared_error: 0.3121
Epoch 14/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.1156 - mean_absolute_error: 0.3024 - mean_absolute_percentage_error: 82866240.0000 - root_mean_squared_error: 0.3400 - val_loss: 0.0973 - val_mean_absolute_error: 0.2848 - val_mean_absolute_percentage_error: 96168272.0000 - val_root_mean_squared_error: 0.3119
Epoch 15/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.1137 - mean_absolute_error: 0.3018 - mean_absolute_percentage_error: 84885480.0000 - root_mean_squared_error: 0.3372 - val_loss: 0.0975 - val_mean_absolute_error: 0.2836 - val_mean_absolute_percentage_error: 91729816.0000 - val_root_mean_squared_error: 0.3123
Epoch 16/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 28s 3s/step - loss: 0.1112 - mean_absolute_error: 0.2976 - mean_absolute_percentage_error: 85903952.0000 - root_mean_squared_error: 0.3335 - val_loss: 0.0984 - val_mean_absolute_error: 0.2823 - val_mean_absolute_percentage_error: 86180672.0000 - val_root_mean_squared_error: 0.3136
Epoch 17/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 39s 2s/step - loss: 0.1150 - mean_absolute_error: 0.3026 - mean_absolute_percentage_error: 81339992.0000 - root_mean_squared_error: 0.3391 - val_loss: 0.0987 - val_mean_absolute_error: 0.2819 - val_mean_absolute_percentage_error: 84711288.0000 - val_root_mean_squared_error: 0.3141
Epoch 18/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.1095 - mean_absolute_error: 0.2949 - mean_absolute_percentage_error: 83485016.0000 - root_mean_squared_error: 0.3309 - val_loss: 0.0997 - val_mean_absolute_error: 0.2812 - val_mean_absolute_percentage_error: 80668880.0000 - val_root_mean_squared_error: 0.3157
Epoch 19/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - loss: 0.1092 - mean_absolute_error: 0.2944 - mean_absolute_percentage_error: 82842672.0000 - root_mean_squared_error: 0.3305 - val_loss: 0.1002 - val_mean_absolute_error: 0.2807 - val_mean_absolute_percentage_error: 78673008.0000 - val_root_mean_squared_error: 0.3165
Epoch 20/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 25s 2s/step - loss: 0.1122 - mean_absolute_error: 0.2989 - mean_absolute_percentage_error: 84240112.0000 - root_mean_squared_error: 0.3349 - val_loss: 0.1011 - val_mean_absolute_error: 0.2800 - val_mean_absolute_percentage_error: 75512072.0000 - val_root_mean_squared_error: 0.3179
Epoch 21/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.1106 - mean_absolute_error: 0.2952 - mean_absolute_percentage_error: 83200144.0000 - root_mean_squared_error: 0.3325 - val_loss: 0.1020 - val_mean_absolute_error: 0.2793 - val_mean_absolute_percentage_error: 72558144.0000 - val_root_mean_squared_error: 0.3193
Epoch 22/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 24s 2s/step - loss: 0.1087 - mean_absolute_error: 0.2913 - mean_absolute_percentage_error: 81673096.0000 - root_mean_squared_error: 0.3297 - val_loss: 0.1009 - val_mean_absolute_error: 0.2783 - val_mean_absolute_percentage_error: 73264648.0000 - val_root_mean_squared_error: 0.3177
Epoch 23/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 26s 3s/step - loss: 0.1054 - mean_absolute_error: 0.2870 - mean_absolute_percentage_error: 85364672.0000 - root_mean_squared_error: 0.3246 - val_loss: 0.0989 - val_mean_absolute_error: 0.2767 - val_mean_absolute_percentage_error: 75234984.0000 - val_root_mean_squared_error: 0.3145
Epoch 24/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 15s 1s/step - loss: 0.1052 - mean_absolute_error: 0.2855 - mean_absolute_percentage_error: 82550856.0000 - root_mean_squared_error: 0.3243 - val_loss: 0.0992 - val_mean_absolute_error: 0.2743 - val_mean_absolute_percentage_error: 71164464.0000 - val_root_mean_squared_error: 0.3149
Epoch 25/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 19s 3s/step - loss: 0.1016 - mean_absolute_error: 0.2805 - mean_absolute_percentage_error: 77831976.0000 - root_mean_squared_error: 0.3187 - val_loss: 0.0958 - val_mean_absolute_error: 0.2715 - val_mean_absolute_percentage_error: 74018264.0000 - val_root_mean_squared_error: 0.3095
Epoch 26/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.1004 - mean_absolute_error: 0.2774 - mean_absolute_percentage_error: 78634688.0000 - root_mean_squared_error: 0.3169 - val_loss: 0.0936 - val_mean_absolute_error: 0.2681 - val_mean_absolute_percentage_error: 72859480.0000 - val_root_mean_squared_error: 0.3059
Epoch 27/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 32s 4s/step - loss: 0.0969 - mean_absolute_error: 0.2714 - mean_absolute_percentage_error: 75326704.0000 - root_mean_squared_error: 0.3114 - val_loss: 0.0899 - val_mean_absolute_error: 0.2636 - val_mean_absolute_percentage_error: 72984128.0000 - val_root_mean_squared_error: 0.2998
Epoch 28/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.0952 - mean_absolute_error: 0.2678 - mean_absolute_percentage_error: 73021880.0000 - root_mean_squared_error: 0.3086 - val_loss: 0.0852 - val_mean_absolute_error: 0.2572 - val_mean_absolute_percentage_error: 72958912.0000 - val_root_mean_squared_error: 0.2919
Epoch 29/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.0900 - mean_absolute_error: 0.2574 - mean_absolute_percentage_error: 67382016.0000 - root_mean_squared_error: 0.3000 - val_loss: 0.0807 - val_mean_absolute_error: 0.2505 - val_mean_absolute_percentage_error: 73137960.0000 - val_root_mean_squared_error: 0.2840
Epoch 30/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.0884 - mean_absolute_error: 0.2561 - mean_absolute_percentage_error: 69234456.0000 - root_mean_squared_error: 0.2974 - val_loss: 0.0772 - val_mean_absolute_error: 0.2430 - val_mean_absolute_percentage_error: 70085952.0000 - val_root_mean_squared_error: 0.2779
Epoch 31/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.0840 - mean_absolute_error: 0.2454 - mean_absolute_percentage_error: 60740908.0000 - root_mean_squared_error: 0.2898 - val_loss: 0.0723 - val_mean_absolute_error: 0.2332 - val_mean_absolute_percentage_error: 70200248.0000 - val_root_mean_squared_error: 0.2690
Epoch 32/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 25s 2s/step - loss: 0.0789 - mean_absolute_error: 0.2375 - mean_absolute_percentage_error: 60913448.0000 - root_mean_squared_error: 0.2809 - val_loss: 0.0699 - val_mean_absolute_error: 0.2228 - val_mean_absolute_percentage_error: 61057356.0000 - val_root_mean_squared_error: 0.2645
Epoch 33/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.0755 - mean_absolute_error: 0.2258 - mean_absolute_percentage_error: 54520904.0000 - root_mean_squared_error: 0.2747 - val_loss: 0.0657 - val_mean_absolute_error: 0.2154 - val_mean_absolute_percentage_error: 66518768.0000 - val_root_mean_squared_error: 0.2564
Epoch 34/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 32s 3s/step - loss: 0.0737 - mean_absolute_error: 0.2240 - mean_absolute_percentage_error: 59121560.0000 - root_mean_squared_error: 0.2716 - val_loss: 0.0644 - val_mean_absolute_error: 0.2057 - val_mean_absolute_percentage_error: 52801008.0000 - val_root_mean_squared_error: 0.2539
Epoch 35/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - loss: 0.0700 - mean_absolute_error: 0.2111 - mean_absolute_percentage_error: 48118636.0000 - root_mean_squared_error: 0.2646 - val_loss: 0.0612 - val_mean_absolute_error: 0.1998 - val_mean_absolute_percentage_error: 53536736.0000 - val_root_mean_squared_error: 0.2474
Epoch 36/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.0696 - mean_absolute_error: 0.2085 - mean_absolute_percentage_error: 45566984.0000 - root_mean_squared_error: 0.2638 - val_loss: 0.0588 - val_mean_absolute_error: 0.1937 - val_mean_absolute_percentage_error: 50704200.0000 - val_root_mean_squared_error: 0.2425
Epoch 37/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 28s 4s/step - loss: 0.0658 - mean_absolute_error: 0.2032 - mean_absolute_percentage_error: 46920408.0000 - root_mean_squared_error: 0.2565 - val_loss: 0.0572 - val_mean_absolute_error: 0.1885 - val_mean_absolute_percentage_error: 46217820.0000 - val_root_mean_squared_error: 0.2392
Epoch 38/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 21s 2s/step - loss: 0.0657 - mean_absolute_error: 0.2009 - mean_absolute_percentage_error: 43043068.0000 - root_mean_squared_error: 0.2564 - val_loss: 0.0557 - val_mean_absolute_error: 0.1838 - val_mean_absolute_percentage_error: 43305476.0000 - val_root_mean_squared_error: 0.2360
Epoch 39/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 30s 3s/step - loss: 0.0616 - mean_absolute_error: 0.1905 - mean_absolute_percentage_error: 38521064.0000 - root_mean_squared_error: 0.2481 - val_loss: 0.0535 - val_mean_absolute_error: 0.1813 - val_mean_absolute_percentage_error: 47968872.0000 - val_root_mean_squared_error: 0.2314
Epoch 40/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 47s 4s/step - loss: 0.0609 - mean_absolute_error: 0.1902 - mean_absolute_percentage_error: 40785376.0000 - root_mean_squared_error: 0.2469 - val_loss: 0.0532 - val_mean_absolute_error: 0.1770 - val_mean_absolute_percentage_error: 40781948.0000 - val_root_mean_squared_error: 0.2307
Epoch 41/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 41s 3s/step - loss: 0.0581 - mean_absolute_error: 0.1843 - mean_absolute_percentage_error: 37672636.0000 - root_mean_squared_error: 0.2410 - val_loss: 0.0513 - val_mean_absolute_error: 0.1725 - val_mean_absolute_percentage_error: 40892684.0000 - val_root_mean_squared_error: 0.2265
Epoch 42/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 49s 4s/step - loss: 0.0556 - mean_absolute_error: 0.1798 - mean_absolute_percentage_error: 36436520.0000 - root_mean_squared_error: 0.2358 - val_loss: 0.0499 - val_mean_absolute_error: 0.1700 - val_mean_absolute_percentage_error: 43326060.0000 - val_root_mean_squared_error: 0.2233
Epoch 43/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 39s 3s/step - loss: 0.0592 - mean_absolute_error: 0.1840 - mean_absolute_percentage_error: 37921324.0000 - root_mean_squared_error: 0.2432 - val_loss: 0.0495 - val_mean_absolute_error: 0.1662 - val_mean_absolute_percentage_error: 37628144.0000 - val_root_mean_squared_error: 0.2225
Epoch 44/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.0559 - mean_absolute_error: 0.1754 - mean_absolute_percentage_error: 35786356.0000 - root_mean_squared_error: 0.2364 - val_loss: 0.0492 - val_mean_absolute_error: 0.1649 - val_mean_absolute_percentage_error: 37629508.0000 - val_root_mean_squared_error: 0.2217
Epoch 45/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 29s 2s/step - loss: 0.0555 - mean_absolute_error: 0.1747 - mean_absolute_percentage_error: 34267304.0000 - root_mean_squared_error: 0.2356 - val_loss: 0.0486 - val_mean_absolute_error: 0.1629 - val_mean_absolute_percentage_error: 36656004.0000 - val_root_mean_squared_error: 0.2204
Epoch 46/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.0538 - mean_absolute_error: 0.1705 - mean_absolute_percentage_error: 33142080.0000 - root_mean_squared_error: 0.2319 - val_loss: 0.0479 - val_mean_absolute_error: 0.1610 - val_mean_absolute_percentage_error: 36425472.0000 - val_root_mean_squared_error: 0.2189
Epoch 47/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.0515 - mean_absolute_error: 0.1657 - mean_absolute_percentage_error: 30643344.0000 - root_mean_squared_error: 0.2268 - val_loss: 0.0474 - val_mean_absolute_error: 0.1616 - val_mean_absolute_percentage_error: 41118344.0000 - val_root_mean_squared_error: 0.2176
Epoch 48/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 42s 3s/step - loss: 0.0508 - mean_absolute_error: 0.1647 - mean_absolute_percentage_error: 32907094.0000 - root_mean_squared_error: 0.2253 - val_loss: 0.0472 - val_mean_absolute_error: 0.1590 - val_mean_absolute_percentage_error: 35274004.0000 - val_root_mean_squared_error: 0.2172
Epoch 49/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 25s 3s/step - loss: 0.0516 - mean_absolute_error: 0.1650 - mean_absolute_percentage_error: 29801786.0000 - root_mean_squared_error: 0.2270 - val_loss: 0.0463 - val_mean_absolute_error: 0.1574 - val_mean_absolute_percentage_error: 37116224.0000 - val_root_mean_squared_error: 0.2151
Epoch 50/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 50s 4s/step - loss: 0.0512 - mean_absolute_error: 0.1656 - mean_absolute_percentage_error: 29591772.0000 - root_mean_squared_error: 0.2262 - val_loss: 0.0466 - val_mean_absolute_error: 0.1563 - val_mean_absolute_percentage_error: 33885752.0000 - val_root_mean_squared_error: 0.2159

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

28/28 ━━━━━━━━━━━━━━━━━━━━ 16s 289ms/step

array([[ 6.08048558e-01],
       [ 6.17382824e-01],
       [ 6.25880361e-01],
       [ 5.97834527e-01],
       [ 5.84949851e-01],
       [ 4.80826020e-01],
       [ 1.82540044e-01],
       [ 3.76355015e-02],
       [-7.93174561e-03],
       [ 3.39207575e-02],
       [ 2.05353290e-01],
       [ 5.15641868e-01],
       [ 6.64154530e-01],
       [ 7.05802619e-01],
       [ 6.93364918e-01],
       [ 6.61562681e-01],
       [ 5.86813569e-01],
       [ 6.17465615e-01],
       [ 6.35779381e-01],
       [ 6.01564169e-01],
       [ 5.53250313e-01],
       [ 4.70212102e-01],
       [ 3.12266260e-01],
       [ 1.29592374e-01],
       [ 1.53262187e-02],
       [ 5.58611900e-02],
       [ 2.12805867e-01],
       [ 5.25018632e-01],
       [ 6.88778043e-01],
       [ 7.23066568e-01],
       [ 7.25709498e-01],
       [ 7.19139159e-01],
       [ 6.70661330e-01],
       [ 6.65848553e-01],
       [ 6.88022196e-01],
       [ 6.76537633e-01],
       [ 6.43085718e-01],
       [ 5.05868614e-01],
       [ 3.03761244e-01],
       [ 1.24874286e-01],
       [ 2.00539585e-02],
       [ 9.87946540e-02],
       [ 2.84884423e-01],
       [ 5.69562554e-01],
       [ 6.96952045e-01],
       [ 7.17779458e-01],
       [ 7.14394569e-01],
       [ 7.14849830e-01],
       [ 6.69789374e-01],
       [ 6.74825311e-01],
       [ 6.87101960e-01],
       [ 6.65020108e-01],
       [ 6.16620183e-01],
       [ 4.77979124e-01],
       [ 2.83670068e-01],
       [ 1.31628796e-01],
       [ 3.04207895e-02],
       [ 1.08927242e-01],
       [ 2.89035738e-01],
       [ 5.61641574e-01],
       [ 6.85240149e-01],
       [ 7.16281950e-01],
       [ 7.14496136e-01],
       [ 6.96438968e-01],
       [ 6.61832511e-01],
       [ 6.25276923e-01],
       [ 5.29529572e-01],
       [ 4.67827231e-01],
       [ 4.75868165e-01],
       [ 4.67059463e-01],
       [ 4.82355297e-01],
       [ 5.85721731e-01],
       [ 6.04563653e-01],
       [ 5.74961066e-01],
       [ 5.94634056e-01],
       [ 6.05727553e-01],
       [ 5.68602443e-01],
       [ 5.55303454e-01],
       [ 4.99958932e-01],
       [ 3.46388996e-01],
       [ 9.68230814e-02],
       [ 1.68758035e-02],
       [ 1.23406038e-01],
       [ 3.10733616e-01],
       [ 5.89594066e-01],
       [ 6.70933604e-01],
       [ 4.50841069e-01],
       [ 1.65037572e-01],
       [ 2.78298184e-02],
       [ 9.84299928e-02],
       [ 2.76233017e-01],
       [ 3.63853723e-01],
       [ 1.26859322e-01],
       [ 1.21203121e-02],
       [ 7.55916610e-02],
       [ 1.99414179e-01],
       [ 4.38765526e-01],
       [ 5.89277864e-01],
       [ 7.02815831e-01],
       [ 7.74336696e-01],
       [ 7.81985760e-01],
       [ 7.06122756e-01],
       [ 6.66553378e-01],
       [ 6.81937456e-01],
       [ 5.46100020e-01],
       [ 1.21293589e-01],
       [-1.28655154e-02],
       [-2.61978451e-02],
       [ 2.30499301e-02],
       [ 1.72051340e-01],
       [ 4.10784274e-01],
       [ 6.41359627e-01],
       [ 7.74279714e-01],
       [ 6.04647398e-01],
       [ 4.25610065e-01],
       [ 3.96872520e-01],
       [ 4.72536951e-01],
       [ 1.33868143e-01],
       [ 3.15660015e-02],
       [ 5.02522141e-02],
       [ 1.09088518e-01],
       [ 2.87882477e-01],
       [ 4.43462223e-01],
       [ 8.73638093e-02],
       [ 6.46117982e-03],
       [ 8.38693008e-02],
       [ 1.65868804e-01],
       [ 3.69833589e-01],
       [ 6.07265115e-01],
       [ 6.77197456e-01],
       [ 7.31035233e-01],
       [ 2.64755309e-01],
       [ 7.67900329e-03],
       [-2.59794313e-02],
       [ 4.20939503e-03],
       [ 1.45278886e-01],
       [ 4.77304578e-01],
       [ 6.31832600e-01],
       [ 6.92877650e-01],
       [ 7.62085080e-01],
       [ 6.94714010e-01],
       [ 5.01604855e-01],
       [ 1.12927221e-01],
       [ 1.95159353e-02],
       [ 7.42192492e-02],
       [ 2.12564155e-01],
       [ 4.17840421e-01],
       [ 4.86871839e-01],
       [ 5.47098458e-01],
       [ 1.91787630e-01],
       [ 2.52043437e-02],
       [ 5.50236702e-02],
       [ 1.80028036e-01],
       [ 4.07452613e-01],
       [ 6.13949180e-01],
       [ 6.97893858e-01],
       [ 7.18039751e-01],
       [ 7.01814175e-01],
       [ 6.21380866e-01],
       [ 1.95104137e-01],
       [-1.93758681e-03],
       [-2.48460714e-02],
       [ 3.97656113e-02],
       [ 2.44314373e-01],
       [ 4.90154624e-01],
       [ 6.85483336e-01],
       [ 6.52757287e-01],
       [ 5.82448483e-01],
       [ 6.76078022e-01],
       [ 2.34426022e-01],
       [ 5.56507707e-02],
       [ 1.09916791e-01],
       [ 2.01846689e-01],
       [ 4.14701760e-01],
       [ 5.83826065e-01],
       [ 6.53086066e-01],
       [ 6.66446209e-01],
       [ 4.15879488e-01],
       [ 6.79297447e-02],
       [-2.04588268e-02],
       [-2.31940579e-02],
       [ 1.31412297e-01],
       [ 3.85475010e-01],
       [ 5.25521755e-01],
       [ 6.05059385e-01],
       [ 6.50520384e-01],
       [ 6.60955191e-01],
       [ 6.54684246e-01],
       [ 6.94591105e-01],
       [ 6.90376580e-01],
       [ 6.50535464e-01],
       [ 6.68358207e-01],
       [ 4.44051355e-01],
       [ 8.28941613e-02],
       [-1.14849638e-02],
       [-2.32486073e-02],
       [ 4.00841534e-02],
       [ 2.58353233e-01],
       [ 5.73617458e-01],
       [ 6.63462341e-01],
       [ 6.63450599e-01],
       [ 7.11164474e-01],
       [ 7.03448653e-01],
       [ 6.62338734e-01],
       [ 6.77292705e-01],
       [ 7.00659692e-01],
       [ 6.96156502e-01],
       [ 5.88632226e-01],
       [ 4.40928459e-01],
       [ 1.08381823e-01],
       [-1.12140849e-02],
       [-1.98322013e-02],
       [ 1.85612757e-02],
       [ 1.57551169e-01],
       [ 4.86361295e-01],
       [ 6.33278906e-01],
       [ 7.06678629e-01],
       [ 7.42950916e-01],
       [ 7.22410560e-01],
       [ 7.11741567e-01],
       [ 6.99959219e-01],
       [ 6.23914659e-01],
       [ 2.07321018e-01],
       [-1.04980730e-02],
       [-3.13800871e-02],
       [ 1.08744344e-02],
       [ 2.34909371e-01],
       [ 4.96518910e-01],
       [ 5.79631686e-01],
       [ 6.44513965e-01],
       [ 6.99478924e-01],
       [ 6.95656180e-01],
       [ 7.02895224e-01],
       [ 7.21789598e-01],
       [ 7.48178840e-01],
       [ 6.88286304e-01],
       [ 5.61212420e-01],
       [ 3.47779989e-01],
       [ 5.60698062e-02],
       [-1.51554309e-02],
       [-2.53713820e-02],
       [ 2.43918374e-02],
       [ 2.80102015e-01],
       [ 5.48806489e-01],
       [ 6.51554227e-01],
       [ 6.81846559e-01],
       [ 7.03898728e-01],
       [ 7.23335564e-01],
       [ 7.49961615e-01],
       [ 7.50689983e-01],
       [ 7.50241637e-01],
       [ 6.50429130e-01],
       [ 4.59430575e-01],
       [ 2.39385560e-01],
       [ 2.23267265e-02],
       [-1.76946558e-02],
       [-2.52068099e-02],
       [ 1.27275297e-02],
       [ 2.06566408e-01],
       [ 5.14514923e-01],
       [ 6.64733410e-01],
       [ 7.17092335e-01],
       [ 7.15844274e-01],
       [ 7.23447084e-01],
       [ 6.95838094e-01],
       [ 6.98993981e-01],
       [ 7.06019163e-01],
       [ 6.20489120e-01],
       [ 5.15835047e-01],
       [ 3.10780317e-01],
       [ 4.76613864e-02],
       [-8.10556207e-03],
       [-2.04560459e-02],
       [ 2.35568658e-02],
       [ 2.22812176e-01],
       [ 5.03413141e-01],
       [ 6.39524996e-01],
       [ 7.04149604e-01],
       [ 7.14530230e-01],
       [ 7.19806433e-01],
       [ 6.92837954e-01],
       [ 5.51760435e-01],
       [ 2.31786638e-01],
       [ 1.98173448e-02],
       [-1.97385419e-02],
       [ 2.50453949e-02],
       [ 1.98964491e-01],
       [ 4.93168592e-01],
       [ 6.09679580e-01],
       [ 6.26370192e-01],
       [ 6.50786519e-01],
       [ 6.85321629e-01],
       [ 5.36945105e-01],
       [ 2.08628625e-01],
       [ 4.53085080e-02],
       [-2.31227372e-03],
       [ 8.93396735e-02],
       [ 2.69663095e-01],
       [ 4.65221196e-01],
       [ 5.74185312e-01],
       [ 6.14314139e-01],
       [ 5.95988274e-01],
       [ 6.32851005e-01],
       [ 7.15032697e-01],
       [ 5.44741631e-01],
       [ 1.60731211e-01],
       [ 6.44460600e-03],
       [-2.23138109e-02],
       [ 4.73316684e-02],
       [ 2.69188493e-01],
       [ 4.56957817e-01],
       [ 5.22528410e-01],
       [ 3.64697933e-01],
       [ 6.76157027e-02],
       [ 6.48912042e-03],
       [-9.00707021e-03],
       [ 1.52043790e-01],
       [ 3.86085033e-01],
       [ 5.40618181e-01],
       [ 6.21162534e-01],
       [ 6.60631776e-01],
       [ 6.33944750e-01],
       [ 5.67169249e-01],
       [ 5.27471721e-01],
       [ 4.81845379e-01],
       [ 3.69582087e-01],
       [ 7.51763657e-02],
       [-1.30889639e-02],
       [-1.89606193e-02],
       [ 5.61434403e-02],
       [ 2.34983951e-01],
       [ 3.79800111e-01],
       [ 1.13900006e-01],
       [ 1.07941488e-02],
       [-1.04400311e-02],
       [ 4.60039005e-02],
       [ 2.46622264e-01],
       [ 5.22074580e-01],
       [ 6.65709138e-01],
       [ 7.31127024e-01],
       [ 7.19113529e-01],
       [ 6.74089849e-01],
       [ 6.03994370e-01],
       [ 5.44140220e-01],
       [ 5.77323616e-01],
       [ 5.56624234e-01],
       [ 4.07425731e-01],
       [ 2.86436174e-02],
       [-1.99671667e-02],
       [-2.80362386e-02],
       [ 1.84770618e-02],
       [ 2.29081929e-01],
       [ 5.47685385e-01],
       [ 6.86317325e-01],
       [ 7.25416303e-01],
       [ 2.20122933e-01],
       [ 2.31163669e-02],
       [ 4.05671522e-02],
       [ 1.84841961e-01],
       [ 5.64731836e-01],
       [ 7.41406739e-01],
       [ 2.07970321e-01],
       [-7.72184506e-03],
       [-2.86403988e-02],
       [-7.29511492e-04],
       [ 1.71872899e-01],
       [ 5.14872074e-01],
       [ 6.34584188e-01],
       [ 6.90051734e-01],
       [ 6.83594108e-01],
       [ 6.22791886e-01],
       [ 6.17261767e-01],
       [ 6.35864317e-01],
       [ 6.72660828e-01],
       [ 6.94115281e-01],
       [ 6.59391165e-01],
       [ 4.95073438e-01],
       [ 9.53387376e-03],
       [-2.23641749e-02],
       [-2.82814112e-02],
       [ 4.05382738e-02],
       [ 3.64793003e-01],
       [ 6.04222596e-01],
       [ 7.11646020e-01],
       [ 7.07035184e-01],
       [ 6.37802124e-01],
       [ 6.43390417e-01],
       [ 7.14972138e-01],
       [ 5.98673940e-01],
       [ 1.43965364e-01],
       [-1.00084655e-02],
       [-3.35948914e-02],
       [-4.69227042e-03],
       [ 2.09817737e-01],
       [ 5.31896353e-01],
       [ 6.44482791e-01],
       [ 6.59686744e-01],
       [ 4.72292989e-01],
       [ 1.34612903e-01],
       [-2.48672254e-03],
       [-1.27369687e-02],
       [ 1.27127588e-01],
       [ 3.61318171e-01],
       [ 5.73795140e-01],
       [ 6.22009575e-01],
       [ 6.12732768e-01],
       [ 6.08326972e-01],
       [ 6.07341945e-01],
       [ 6.21216416e-01],
       [ 6.71963692e-01],
       [ 7.51959562e-01],
       [ 6.54555082e-01],
       [ 4.04111296e-01],
       [ 6.24549240e-02],
       [-1.52482521e-02],
       [-2.62381341e-02],
       [ 4.97564748e-02],
       [ 2.50324100e-01],
       [ 4.85482901e-01],
       [ 5.98309040e-01],
       [ 6.25243902e-01],
       [ 6.71402037e-01],
       [ 7.05036283e-01],
       [ 7.02068448e-01],
       [ 6.85503125e-01],
       [ 6.76630259e-01],
       [ 5.44572830e-01],
       [ 4.23490763e-01],
       [ 2.45710790e-01],
       [ 2.26736143e-02],
       [-1.32101439e-02],
       [-2.10097656e-02],
       [ 3.57088074e-02],
       [ 2.29116693e-01],
       [ 5.01620650e-01],
       [ 6.57604456e-01],
       [ 6.94042087e-01],
       [ 6.94507539e-01],
       [ 6.63920641e-01],
       [ 6.29048049e-01],
       [ 5.70895433e-01],
       [ 5.54124355e-01],
       [ 4.77729917e-01],
       [ 2.05260843e-01],
       [ 1.88227464e-02],
       [-1.19136292e-02],
       [-1.45661198e-02],
       [-7.48004206e-03],
       [ 8.84587467e-02],
       [ 2.81025887e-01],
       [ 4.88185734e-01],
       [ 5.52708626e-01],
       [ 5.25669098e-01],
       [ 4.93075073e-01],
       [ 4.52176899e-01],
       [ 3.98188472e-01],
       [ 3.48913848e-01],
       [ 3.00599217e-01],
       [ 2.56991386e-01],
       [ 1.35436937e-01],
       [ 2.08958387e-02],
       [-8.17180704e-03],
       [-3.70052550e-03],
       [ 1.65039953e-03],
       [ 1.14349186e-01],
       [ 3.05699795e-01],
       [ 4.41145718e-01],
       [ 4.37411070e-01],
       [ 4.12662148e-01],
       [ 3.65962684e-01],
       [ 3.50942969e-01],
       [ 2.96215713e-01],
       [ 2.29386210e-01],
       [ 1.68730006e-01],
       [ 9.11599696e-02],
       [ 4.40486521e-02],
       [ 7.94485956e-03],
       [-2.85269693e-03],
       [ 1.02175213e-03],
       [ 2.63047684e-03],
       [ 1.08323522e-01],
       [ 2.54983753e-01],
       [ 3.74314874e-01],
       [ 4.29307044e-01],
       [ 4.33831900e-01],
       [ 4.61453766e-01],
       [ 4.46594298e-01],
       [ 3.64397377e-01],
       [ 3.38161170e-01],
       [ 2.84170955e-01],
       [ 2.64799178e-01],
       [ 1.87837660e-01],
       [ 7.47557729e-02],
       [ 2.97482964e-03],
       [-3.84739321e-03],
       [-6.59378711e-03],
       [ 6.86334223e-02],
       [ 2.15867996e-01],
       [ 3.63910824e-01],
       [ 4.15583909e-01],
       [ 5.18633008e-01],
       [ 5.39258957e-01],
       [ 4.99971271e-01],
       [ 4.44498837e-01],
       [ 3.62525314e-01],
       [ 2.94731736e-01],
       [ 2.25813285e-01],
       [ 1.62529111e-01],
       [ 1.87730566e-02],
       [-6.04129490e-03],
       [-1.14312973e-02],
       [-1.19627286e-02],
       [ 4.78033572e-02],
       [ 2.19754785e-01],
       [ 4.13499832e-01],
       [ 5.74447453e-01],
       [ 6.03784800e-01],
       [ 5.97668886e-01],
       [ 5.89861691e-01],
       [ 4.15497065e-01],
       [ 2.56820410e-01],
       [ 2.44950920e-01],
       [ 1.30087703e-01],
       [ 1.91342354e-01],
       [ 3.78533155e-02],
       [-1.84408389e-04],
       [-8.74168798e-03],
       [-1.04162619e-02],
       [ 7.38410503e-02],
       [ 2.67216414e-01],
       [ 4.82730687e-01],
       [ 6.04517877e-01],
       [ 6.55665696e-01],
       [ 6.51444137e-01],
       [ 6.30687118e-01],
       [ 5.63898802e-01],
       [ 5.47453642e-01],
       [ 5.96218586e-01],
       [ 5.60213923e-01],
       [ 5.21173775e-01],
       [ 3.07936192e-01],
       [ 1.85424518e-02],
       [-1.88313685e-02],
       [-2.63989922e-02],
       [ 3.14793065e-02],
       [ 2.90380388e-01],
       [ 6.22932136e-01],
       [ 7.58710623e-01],
       [ 7.64166057e-01],
       [ 7.07675397e-01],
       [ 6.34457350e-01],
       [ 5.89448810e-01],
       [ 5.44217944e-01],
       [ 2.55430192e-01],
       [ 8.60180799e-03],
       [-2.39687804e-02],
       [ 2.26665027e-02],
       [ 2.13009775e-01],
       [ 5.14557719e-01],
       [ 6.72731519e-01],
       [ 6.88782573e-01],
       [ 7.34934270e-01],
       [ 7.25905299e-01],
       [ 6.72137618e-01],
       [ 2.73097038e-01],
       [ 3.93563733e-02],
       [-6.51894975e-03],
       [ 6.18724748e-02],
       [ 2.65127450e-01],
       [ 5.10085821e-01],
       [ 5.88730156e-01],
       [ 6.26057625e-01],
       [ 6.50332689e-01],
       [ 6.88433766e-01],
       [ 7.35026002e-01],
       [ 7.27610409e-01],
       [ 6.77215397e-01],
       [ 6.41949356e-01],
       [ 5.33087015e-01],
       [ 4.02050704e-01],
       [ 1.01190910e-01],
       [-1.14872735e-02],
       [-2.68896390e-02],
       [ 5.70058357e-04],
       [ 1.43141106e-01],
       [ 4.76041287e-01],
       [ 6.56065881e-01],
       [ 7.40615666e-01],
       [ 7.33024299e-01],
       [ 6.99370921e-01],
       [ 7.12319255e-01],
       [ 7.31935263e-01],
       [ 7.59243965e-01],
       [ 6.76702738e-01],
       [ 5.33693433e-01],
       [ 2.93191016e-01],
       [ 4.18877900e-02],
       [-8.55927914e-03],
       [-2.37778202e-02],
       [ 3.12414598e-02],
       [ 2.51791954e-01],
       [ 5.37836671e-01],
       [ 6.79086924e-01],
       [ 7.26047814e-01],
       [ 7.21626222e-01],
       [ 6.98755324e-01],
       [ 6.79710090e-01],
       [ 6.74673259e-01],
       [ 6.71671629e-01],
       [ 6.28797889e-01],
       [ 5.32019019e-01],
       [ 3.71115029e-01],
       [ 1.19360670e-01],
       [ 2.65270546e-02],
       [-6.10220432e-03],
       [ 5.90441376e-02],
       [ 2.54696935e-01],
       [ 5.16518772e-01],
       [ 6.42796755e-01],
       [ 6.88362181e-01],
       [ 6.95875227e-01],
       [ 6.89126492e-01],
       [ 6.68046474e-01],
       [ 6.77649617e-01],
       [ 6.98984921e-01],
       [ 6.68401539e-01],
       [ 5.80356240e-01],
       [ 4.07449186e-01],
       [ 1.43708408e-01],
       [ 3.71838883e-02],
       [-1.52056664e-03],
       [ 7.08380938e-02],
       [ 2.64414966e-01],
       [ 5.01603961e-01],
       [ 6.09076738e-01],
       [ 6.51128709e-01],
       [ 6.56375170e-01],
       [ 6.56633914e-01],
       [ 6.43603861e-01],
       [ 6.62368417e-01],
       [ 6.84281468e-01],
       [ 6.40445888e-01],
       [ 5.04452407e-01],
       [ 2.86807656e-01],
       [ 7.29206875e-02],
       [ 1.36431344e-02],
       [-4.86468710e-03],
       [ 7.79191405e-02],
       [ 2.72374034e-01],
       [ 5.00423610e-01],
       [ 6.14584863e-01],
       [ 6.63916647e-01],
       [ 6.81232214e-01],
       [ 7.05119550e-01],
       [ 6.90902352e-01],
       [ 7.06768513e-01],
       [ 7.11202323e-01],
       [ 6.37650967e-01],
       [ 5.50003111e-01],
       [ 2.88119435e-01],
       [ 6.39159903e-02],
       [ 6.73091877e-03],
       [-1.02769993e-02],
       [ 8.28062594e-02],
       [ 3.01668197e-01],
       [ 5.37440598e-01],
       [ 6.61050856e-01],
       [ 7.07042396e-01],
       [ 7.15279758e-01],
       [ 7.16453552e-01],
       [ 7.03514636e-01],
       [ 6.99141800e-01],
       [ 7.08772898e-01],
       [ 6.64380312e-01],
       [ 5.45696855e-01],
       [ 2.61778831e-01],
       [ 3.78972217e-02],
       [-4.82523069e-03],
       [-1.51473302e-02],
       [ 7.94685781e-02],
       [ 3.12817097e-01],
       [ 5.63522637e-01],
       [ 6.88612223e-01],
       [ 6.95213914e-01],
       [ 6.73062146e-01],
       [ 6.82588100e-01],
       [ 6.87749863e-01],
       [ 7.09187329e-01],
       [ 7.34505534e-01],
       [ 6.30240083e-01],
       [ 4.74191189e-01],
       [ 2.74880886e-01],
       [ 6.25023544e-02],
       [ 4.34934441e-03],
       [-9.84402746e-03],
       [ 7.87027329e-02],
       [ 3.11452180e-01],
       [ 5.91311693e-01],
       [ 7.06070423e-01],
       [ 7.22448826e-01],
       [ 7.16649354e-01],
       [ 7.22328544e-01],
       [ 6.61878347e-01],
       [ 3.60671520e-01],
       [ 1.16946280e-01],
       [ 9.16249398e-03],
       [ 9.03747380e-02],
       [ 2.73998797e-01],
       [ 4.75082755e-01],
       [ 6.25248313e-01],
       [ 6.48593187e-01],
       [ 6.23454571e-01],
       [ 6.43154383e-01],
       [ 6.58019185e-01],
       [ 3.36433053e-01],
       [ 8.99519175e-02],
       [ 1.40778739e-02],
       [ 1.07661888e-01],
       [ 2.62601078e-01],
       [ 5.08060932e-01],
       [ 6.16224170e-01],
       [ 6.22109175e-01],
       [ 6.70872569e-01],
       [ 6.77816331e-01],
       [ 6.70298517e-01],
       [ 3.22444439e-01],
       [ 6.84616640e-02],
       [-7.76650663e-03],
       [ 5.59012294e-02],
       [ 2.44550109e-01],
       [ 5.02075016e-01],
       [ 6.11955047e-01],
       [ 5.85000396e-01],
       [ 5.91159582e-01],
       [ 5.87545872e-01],
       [ 6.37194753e-01],
       [ 2.99416691e-01],
       [ 7.89380223e-02],
       [-6.75122254e-04],
       [ 6.32015541e-02],
       [ 2.41141438e-01],
       [ 4.97556746e-01],
       [ 6.33815765e-01],
       [ 6.22449994e-01],
       [ 6.10031843e-01],
       [ 5.91227651e-01],
       [ 6.27809584e-01],
       [ 6.80894613e-01],
       [ 7.16161370e-01],
       [ 6.54816866e-01],
       [ 4.06762332e-01],
       [ 3.70968990e-02],
       [-1.31803621e-02],
       [-1.65700950e-02],
       [ 6.13688082e-02],
       [ 2.15887815e-01],
       [ 4.07906175e-01],
       [ 5.90620518e-01],
       [ 2.47473642e-01],
       [ 6.31650984e-02],
       [ 9.68504995e-02],
       [ 1.86220527e-01],
       [ 4.80665565e-01],
       [ 6.91392064e-01],
       [ 7.47948885e-01],
       [ 7.05566168e-01],
       [ 1.88288212e-01],
       [-1.10084582e-02],
       [ 3.35406326e-03],

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
16551     28546.0  27911.718674  25071.187461           NaN
16552     28723.0  28552.281566  25834.987615           NaN
16553     26967.0  28173.508713  26222.885304           NaN
16554     26336.0  25031.833853    23317.3981           NaN
16555     23562.0   21975.28109  23437.167632           NaN
...           ...           ...           ...           ...
18273      7356.0   5632.366084   5438.219944   6833.204102
18274     17638.0  18901.861998  18263.627162  14250.267578
18275     23339.0   24148.93331  21918.767881  17568.277344
18276     26323.0  25572.670269  24646.911253  20057.130859
18278     25598.0  26338.372419   26127.13712  21843.267578

[914 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 183s 8s/step - loss: 0.1925 - mean_absolute_error: 0.3077 - mean_absolute_percentage_error: 10932750.0000 - root_mean_squared_error: 0.4385 - val_loss: 0.0979 - val_mean_absolute_error: 0.2837 - val_mean_absolute_percentage_error: 90615656.0000 - val_root_mean_squared_error: 0.3129
Epoch 2/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 71s 5s/step - loss: 0.1229 - mean_absolute_error: 0.3154 - mean_absolute_percentage_error: 100067488.0000 - root_mean_squared_error: 0.3505 - val_loss: 0.0976 - val_mean_absolute_error: 0.2863 - val_mean_absolute_percentage_error: 99219888.0000 - val_root_mean_squared_error: 0.3123
Epoch 3/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 50s 6s/step - loss: 0.1179 - mean_absolute_error: 0.3004 - mean_absolute_percentage_error: 76175072.0000 - root_mean_squared_error: 0.3433 - val_loss: 0.0991 - val_mean_absolute_error: 0.2821 - val_mean_absolute_percentage_error: 83843536.0000 - val_root_mean_squared_error: 0.3148
Epoch 4/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 88s 6s/step - loss: 0.1195 - mean_absolute_error: 0.3034 - mean_absolute_percentage_error: 78900704.0000 - root_mean_squared_error: 0.3456 - val_loss: 0.0995 - val_mean_absolute_error: 0.2914 - val_mean_absolute_percentage_error: 111332080.0000 - val_root_mean_squared_error: 0.3154
Epoch 5/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 80s 5s/step - loss: 0.1154 - mean_absolute_error: 0.3072 - mean_absolute_percentage_error: 95702344.0000 - root_mean_squared_error: 0.3397 - val_loss: 0.0978 - val_mean_absolute_error: 0.2876 - val_mean_absolute_percentage_error: 102598424.0000 - val_root_mean_squared_error: 0.3128
Epoch 6/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.1144 - mean_absolute_error: 0.3007 - mean_absolute_percentage_error: 83102352.0000 - root_mean_squared_error: 0.3382 - val_loss: 0.0975 - val_mean_absolute_error: 0.2853 - val_mean_absolute_percentage_error: 96349376.0000 - val_root_mean_squared_error: 0.3123
Epoch 7/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 0.1155 - mean_absolute_error: 0.3026 - mean_absolute_percentage_error: 84549520.0000 - root_mean_squared_error: 0.3398 - val_loss: 0.0977 - val_mean_absolute_error: 0.2872 - val_mean_absolute_percentage_error: 101543816.0000 - val_root_mean_squared_error: 0.3126
Epoch 8/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 43s 5s/step - loss: 0.1143 - mean_absolute_error: 0.3036 - mean_absolute_percentage_error: 88495624.0000 - root_mean_squared_error: 0.3381 - val_loss: 0.0975 - val_mean_absolute_error: 0.2864 - val_mean_absolute_percentage_error: 99540072.0000 - val_root_mean_squared_error: 0.3123
Epoch 9/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 46s 6s/step - loss: 0.1138 - mean_absolute_error: 0.3032 - mean_absolute_percentage_error: 88381048.0000 - root_mean_squared_error: 0.3374 - val_loss: 0.0984 - val_mean_absolute_error: 0.2828 - val_mean_absolute_percentage_error: 86809408.0000 - val_root_mean_squared_error: 0.3138
Epoch 10/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 80s 5s/step - loss: 0.1112 - mean_absolute_error: 0.2976 - mean_absolute_percentage_error: 81359296.0000 - root_mean_squared_error: 0.3334 - val_loss: 0.1015 - val_mean_absolute_error: 0.2807 - val_mean_absolute_percentage_error: 75798408.0000 - val_root_mean_squared_error: 0.3186
Epoch 11/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 50s 6s/step - loss: 0.1102 - mean_absolute_error: 0.2928 - mean_absolute_percentage_error: 81273312.0000 - root_mean_squared_error: 0.3320 - val_loss: 0.0970 - val_mean_absolute_error: 0.2812 - val_mean_absolute_percentage_error: 87968384.0000 - val_root_mean_squared_error: 0.3114
Epoch 12/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 83s 6s/step - loss: 0.1104 - mean_absolute_error: 0.2961 - mean_absolute_percentage_error: 91095048.0000 - root_mean_squared_error: 0.3323 - val_loss: 0.1034 - val_mean_absolute_error: 0.2788 - val_mean_absolute_percentage_error: 69050328.0000 - val_root_mean_squared_error: 0.3216
Epoch 13/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 62s 9s/step - loss: 0.1094 - mean_absolute_error: 0.2905 - mean_absolute_percentage_error: 78440648.0000 - root_mean_squared_error: 0.3307 - val_loss: 0.0967 - val_mean_absolute_error: 0.2756 - val_mean_absolute_percentage_error: 78497488.0000 - val_root_mean_squared_error: 0.3109
Epoch 14/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 7s/step - loss: 0.1062 - mean_absolute_error: 0.2848 - mean_absolute_percentage_error: 77184152.0000 - root_mean_squared_error: 0.3258 - val_loss: 0.0897 - val_mean_absolute_error: 0.2663 - val_mean_absolute_percentage_error: 80238176.0000 - val_root_mean_squared_error: 0.2995
Epoch 15/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 89s 7s/step - loss: 0.0927 - mean_absolute_error: 0.2642 - mean_absolute_percentage_error: 73097368.0000 - root_mean_squared_error: 0.3044 - val_loss: 0.0703 - val_mean_absolute_error: 0.2268 - val_mean_absolute_percentage_error: 73587704.0000 - val_root_mean_squared_error: 0.2652
Epoch 16/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 75s 5s/step - loss: 0.0718 - mean_absolute_error: 0.2176 - mean_absolute_percentage_error: 55662816.0000 - root_mean_squared_error: 0.2679 - val_loss: 0.0591 - val_mean_absolute_error: 0.1785 - val_mean_absolute_percentage_error: 39202620.0000 - val_root_mean_squared_error: 0.2431
Epoch 17/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 62s 9s/step - loss: 0.0603 - mean_absolute_error: 0.1841 - mean_absolute_percentage_error: 40053872.0000 - root_mean_squared_error: 0.2456 - val_loss: 0.0527 - val_mean_absolute_error: 0.1725 - val_mean_absolute_percentage_error: 48580572.0000 - val_root_mean_squared_error: 0.2296
Epoch 18/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 84s 8s/step - loss: 0.0551 - mean_absolute_error: 0.1741 - mean_absolute_percentage_error: 36257780.0000 - root_mean_squared_error: 0.2346 - val_loss: 0.0462 - val_mean_absolute_error: 0.1547 - val_mean_absolute_percentage_error: 35885344.0000 - val_root_mean_squared_error: 0.2149
Epoch 19/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 82s 7s/step - loss: 0.0500 - mean_absolute_error: 0.1610 - mean_absolute_percentage_error: 31374904.0000 - root_mean_squared_error: 0.2236 - val_loss: 0.0445 - val_mean_absolute_error: 0.1529 - val_mean_absolute_percentage_error: 36360140.0000 - val_root_mean_squared_error: 0.2109
Epoch 20/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 83s 7s/step - loss: 0.0480 - mean_absolute_error: 0.1570 - mean_absolute_percentage_error: 30895232.0000 - root_mean_squared_error: 0.2190 - val_loss: 0.0480 - val_mean_absolute_error: 0.1572 - val_mean_absolute_percentage_error: 44364344.0000 - val_root_mean_squared_error: 0.2190
Epoch 21/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 78s 6s/step - loss: 0.0484 - mean_absolute_error: 0.1541 - mean_absolute_percentage_error: 30583990.0000 - root_mean_squared_error: 0.2201 - val_loss: 0.0432 - val_mean_absolute_error: 0.1525 - val_mean_absolute_percentage_error: 40134412.0000 - val_root_mean_squared_error: 0.2078
Epoch 22/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 94s 8s/step - loss: 0.0453 - mean_absolute_error: 0.1560 - mean_absolute_percentage_error: 32043856.0000 - root_mean_squared_error: 0.2129 - val_loss: 0.0439 - val_mean_absolute_error: 0.1451 - val_mean_absolute_percentage_error: 33310826.0000 - val_root_mean_squared_error: 0.2096
Epoch 23/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 75s 6s/step - loss: 0.0442 - mean_absolute_error: 0.1415 - mean_absolute_percentage_error: 25173780.0000 - root_mean_squared_error: 0.2101 - val_loss: 0.0429 - val_mean_absolute_error: 0.1457 - val_mean_absolute_percentage_error: 31157254.0000 - val_root_mean_squared_error: 0.2072
Epoch 24/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 97s 8s/step - loss: 0.0408 - mean_absolute_error: 0.1399 - mean_absolute_percentage_error: 25624704.0000 - root_mean_squared_error: 0.2021 - val_loss: 0.0435 - val_mean_absolute_error: 0.1456 - val_mean_absolute_percentage_error: 26504482.0000 - val_root_mean_squared_error: 0.2085
Epoch 25/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 62s 8s/step - loss: 0.0387 - mean_absolute_error: 0.1345 - mean_absolute_percentage_error: 21497252.0000 - root_mean_squared_error: 0.1967 - val_loss: 0.0446 - val_mean_absolute_error: 0.1415 - val_mean_absolute_percentage_error: 26837704.0000 - val_root_mean_squared_error: 0.2111
Epoch 26/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 66s 5s/step - loss: 0.0363 - mean_absolute_error: 0.1294 - mean_absolute_percentage_error: 24079796.0000 - root_mean_squared_error: 0.1905 - val_loss: 0.0453 - val_mean_absolute_error: 0.1456 - val_mean_absolute_percentage_error: 33223322.0000 - val_root_mean_squared_error: 0.2129
Epoch 27/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 63s 8s/step - loss: 0.0373 - mean_absolute_error: 0.1310 - mean_absolute_percentage_error: 25142952.0000 - root_mean_squared_error: 0.1931 - val_loss: 0.0434 - val_mean_absolute_error: 0.1380 - val_mean_absolute_percentage_error: 24444646.0000 - val_root_mean_squared_error: 0.2083
Epoch 28/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 92s 9s/step - loss: 0.0334 - mean_absolute_error: 0.1211 - mean_absolute_percentage_error: 19446994.0000 - root_mean_squared_error: 0.1828 - val_loss: 0.0454 - val_mean_absolute_error: 0.1451 - val_mean_absolute_percentage_error: 27604066.0000 - val_root_mean_squared_error: 0.2131
Epoch 29/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 69s 6s/step - loss: 0.0323 - mean_absolute_error: 0.1207 - mean_absolute_percentage_error: 21470280.0000 - root_mean_squared_error: 0.1796 - val_loss: 0.0453 - val_mean_absolute_error: 0.1372 - val_mean_absolute_percentage_error: 22849636.0000 - val_root_mean_squared_error: 0.2128
Epoch 30/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 107s 9s/step - loss: 0.0302 - mean_absolute_error: 0.1132 - mean_absolute_percentage_error: 17490544.0000 - root_mean_squared_error: 0.1736 - val_loss: 0.0459 - val_mean_absolute_error: 0.1405 - val_mean_absolute_percentage_error: 24479362.0000 - val_root_mean_squared_error: 0.2143
Epoch 31/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 77s 7s/step - loss: 0.0294 - mean_absolute_error: 0.1164 - mean_absolute_percentage_error: 17440658.0000 - root_mean_squared_error: 0.1714 - val_loss: 0.0489 - val_mean_absolute_error: 0.1413 - val_mean_absolute_percentage_error: 22308574.0000 - val_root_mean_squared_error: 0.2212
Epoch 32/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 94s 8s/step - loss: 0.0267 - mean_absolute_error: 0.1090 - mean_absolute_percentage_error: 16757027.0000 - root_mean_squared_error: 0.1633 - val_loss: 0.0506 - val_mean_absolute_error: 0.1479 - val_mean_absolute_percentage_error: 24244720.0000 - val_root_mean_squared_error: 0.2249
Epoch 33/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 91s 9s/step - loss: 0.0255 - mean_absolute_error: 0.1071 - mean_absolute_percentage_error: 16855784.0000 - root_mean_squared_error: 0.1598 - val_loss: 0.0476 - val_mean_absolute_error: 0.1411 - val_mean_absolute_percentage_error: 26389218.0000 - val_root_mean_squared_error: 0.2182
Epoch 34/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 68s 6s/step - loss: 0.0235 - mean_absolute_error: 0.1038 - mean_absolute_percentage_error: 15787447.0000 - root_mean_squared_error: 0.1532 - val_loss: 0.0511 - val_mean_absolute_error: 0.1518 - val_mean_absolute_percentage_error: 25217012.0000 - val_root_mean_squared_error: 0.2262
Epoch 35/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 106s 9s/step - loss: 0.0222 - mean_absolute_error: 0.1037 - mean_absolute_percentage_error: 18027600.0000 - root_mean_squared_error: 0.1491 - val_loss: 0.0468 - val_mean_absolute_error: 0.1402 - val_mean_absolute_percentage_error: 23972156.0000 - val_root_mean_squared_error: 0.2162
Epoch 36/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 59s 5s/step - loss: 0.0211 - mean_absolute_error: 0.0952 - mean_absolute_percentage_error: 14474316.0000 - root_mean_squared_error: 0.1451 - val_loss: 0.0529 - val_mean_absolute_error: 0.1509 - val_mean_absolute_percentage_error: 22676860.0000 - val_root_mean_squared_error: 0.2300
Epoch 37/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 69s 9s/step - loss: 0.0213 - mean_absolute_error: 0.1003 - mean_absolute_percentage_error: 15054750.0000 - root_mean_squared_error: 0.1459 - val_loss: 0.0467 - val_mean_absolute_error: 0.1449 - val_mean_absolute_percentage_error: 29965140.0000 - val_root_mean_squared_error: 0.2161
Epoch 38/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 61s 4s/step - loss: 0.0205 - mean_absolute_error: 0.0990 - mean_absolute_percentage_error: 16470760.0000 - root_mean_squared_error: 0.1431 - val_loss: 0.0569 - val_mean_absolute_error: 0.1551 - val_mean_absolute_percentage_error: 23196070.0000 - val_root_mean_squared_error: 0.2385
Epoch 39/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 68s 9s/step - loss: 0.0180 - mean_absolute_error: 0.0889 - mean_absolute_percentage_error: 11705801.0000 - root_mean_squared_error: 0.1342 - val_loss: 0.0493 - val_mean_absolute_error: 0.1486 - val_mean_absolute_percentage_error: 25961546.0000 - val_root_mean_squared_error: 0.2221
Epoch 40/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 81s 8s/step - loss: 0.0169 - mean_absolute_error: 0.0874 - mean_absolute_percentage_error: 12403807.0000 - root_mean_squared_error: 0.1300 - val_loss: 0.0507 - val_mean_absolute_error: 0.1476 - val_mean_absolute_percentage_error: 21374308.0000 - val_root_mean_squared_error: 0.2251
Epoch 41/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 86s 8s/step - loss: 0.0148 - mean_absolute_error: 0.0820 - mean_absolute_percentage_error: 10950345.0000 - root_mean_squared_error: 0.1216 - val_loss: 0.0508 - val_mean_absolute_error: 0.1504 - val_mean_absolute_percentage_error: 28376864.0000 - val_root_mean_squared_error: 0.2254
Epoch 42/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 52s 6s/step - loss: 0.0153 - mean_absolute_error: 0.0851 - mean_absolute_percentage_error: 13399299.0000 - root_mean_squared_error: 0.1235 - val_loss: 0.0554 - val_mean_absolute_error: 0.1540 - val_mean_absolute_percentage_error: 21232574.0000 - val_root_mean_squared_error: 0.2355
Epoch 43/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 60s 8s/step - loss: 0.0155 - mean_absolute_error: 0.0829 - mean_absolute_percentage_error: 9609471.0000 - root_mean_squared_error: 0.1246 - val_loss: 0.0522 - val_mean_absolute_error: 0.1537 - val_mean_absolute_percentage_error: 25613396.0000 - val_root_mean_squared_error: 0.2284
Epoch 44/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 85s 8s/step - loss: 0.0137 - mean_absolute_error: 0.0803 - mean_absolute_percentage_error: 12013089.0000 - root_mean_squared_error: 0.1172 - val_loss: 0.0526 - val_mean_absolute_error: 0.1490 - val_mean_absolute_percentage_error: 23212996.0000 - val_root_mean_squared_error: 0.2294
Epoch 45/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 84s 7s/step - loss: 0.0124 - mean_absolute_error: 0.0749 - mean_absolute_percentage_error: 9690746.0000 - root_mean_squared_error: 0.1112 - val_loss: 0.0586 - val_mean_absolute_error: 0.1611 - val_mean_absolute_percentage_error: 23371934.0000 - val_root_mean_squared_error: 0.2421
Epoch 46/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 94s 8s/step - loss: 0.0115 - mean_absolute_error: 0.0722 - mean_absolute_percentage_error: 9708125.0000 - root_mean_squared_error: 0.1073 - val_loss: 0.0535 - val_mean_absolute_error: 0.1514 - val_mean_absolute_percentage_error: 24106710.0000 - val_root_mean_squared_error: 0.2314
Epoch 47/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 66s 9s/step - loss: 0.0109 - mean_absolute_error: 0.0694 - mean_absolute_percentage_error: 9401380.0000 - root_mean_squared_error: 0.1046 - val_loss: 0.0533 - val_mean_absolute_error: 0.1538 - val_mean_absolute_percentage_error: 23498242.0000 - val_root_mean_squared_error: 0.2309
Epoch 48/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 76s 7s/step - loss: 0.0098 - mean_absolute_error: 0.0674 - mean_absolute_percentage_error: 8951600.0000 - root_mean_squared_error: 0.0992 - val_loss: 0.0535 - val_mean_absolute_error: 0.1525 - val_mean_absolute_percentage_error: 22980770.0000 - val_root_mean_squared_error: 0.2312
Epoch 49/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 101s 10s/step - loss: 0.0094 - mean_absolute_error: 0.0659 - mean_absolute_percentage_error: 7943418.5000 - root_mean_squared_error: 0.0971 - val_loss: 0.0570 - val_mean_absolute_error: 0.1575 - val_mean_absolute_percentage_error: 23264198.0000 - val_root_mean_squared_error: 0.2387
Epoch 50/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 76s 9s/step - loss: 0.0090 - mean_absolute_error: 0.0628 - mean_absolute_percentage_error: 7907209.5000 - root_mean_squared_error: 0.0946 - val_loss: 0.0582 - val_mean_absolute_error: 0.1579 - val_mean_absolute_percentage_error: 23268900.0000 - val_root_mean_squared_error: 0.2413

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

28/28 ━━━━━━━━━━━━━━━━━━━━ 30s 432ms/step

array([[ 7.46214509e-01],
       [ 6.49773002e-01],
       [ 4.69265759e-01],
       [ 7.98773408e-01],
       [ 8.21251273e-01],
       [ 8.07953596e-01],
       [ 7.32283741e-02],
       [ 4.81670350e-02],
       [ 1.80917792e-02],
       [ 6.26400113e-02],
       [ 2.09366933e-01],
       [ 3.85104358e-01],
       [ 5.64345598e-01],
       [ 5.70777774e-01],
       [ 6.76092386e-01],
       [ 6.74589396e-01],
       [ 3.67603481e-01],
       [ 2.92470157e-01],
       [ 6.13041103e-01],
       [ 7.05772758e-01],
       [ 5.85287094e-01],
       [ 3.36795270e-01],
       [ 5.33193164e-02],
       [ 9.29204747e-03],
       [ 3.28700095e-02],
       [ 4.66286056e-02],
       [ 2.58020163e-01],
       [ 5.13337314e-01],
       [ 6.00018740e-01],
       [ 4.49948549e-01],
       [ 5.79623103e-01],
       [ 8.78267169e-01],
       [ 7.71459162e-01],
       [ 7.01574564e-01],
       [ 8.22427392e-01],
       [ 8.15851927e-01],
       [ 6.59103453e-01],
       [ 2.71429002e-01],
       [ 4.07581851e-02],
       [ 2.08758637e-02],
       [ 4.42219339e-02],
       [ 2.33689304e-02],
       [ 7.35509992e-02],
       [ 5.02245963e-01],
       [ 7.76437581e-01],
       [ 7.95795441e-01],
       [ 7.47595191e-01],
       [ 9.62755084e-01],
       [ 7.78562188e-01],
       [ 6.93579555e-01],
       [ 7.95768023e-01],
       [ 7.15844035e-01],
       [ 7.77004540e-01],
       [ 7.54829764e-01],
       [ 2.90943384e-01],
       [ 1.25154126e-02],
       [ 2.44311541e-02],
       [ 3.50551456e-02],
       [ 1.49187580e-01],
       [ 5.71586132e-01],
       [ 7.96803236e-01],
       [ 6.74612761e-01],
       [ 6.94105387e-01],
       [ 9.51462328e-01],
       [ 8.14383149e-01],
       [ 5.32126069e-01],
       [ 3.55181918e-02],
       [ 3.72881413e-01],
       [ 6.59708142e-01],
       [ 5.51591516e-01],
       [ 3.97044420e-01],
       [ 4.14824128e-01],
       [ 2.87664294e-01],
       [ 6.74019933e-01],
       [ 7.12424278e-01],
       [ 6.52234674e-01],
       [ 7.78738558e-01],
       [ 8.38092148e-01],
       [ 3.34531426e-01],
       [ 3.69232036e-02],
       [ 4.24750373e-02],
       [ 3.29214633e-02],
       [ 7.40165412e-02],
       [ 6.79700255e-01],
       [ 5.63707173e-01],
       [ 5.06032825e-01],
       [ 1.06112331e-01],
       [-4.15161252e-04],
       [ 1.35522448e-02],
       [ 9.43975896e-03],
       [ 4.28091228e-01],
       [ 5.03454730e-02],
       [ 9.65058245e-03],
       [ 2.64309347e-05],
       [-4.88388911e-03],
       [ 5.10487258e-02],
       [ 1.92530468e-01],
       [ 1.74866095e-01],
       [ 4.73488986e-01],
       [ 1.00133145e+00],
       [ 9.78755236e-01],
       [ 8.60416055e-01],
       [ 8.42885852e-01],
       [ 8.92079949e-01],
       [ 6.36277437e-01],
       [ 2.15913188e-02],
       [ 1.59317721e-02],
       [ 1.52003150e-02],
       [ 3.92645225e-03],
       [ 3.63117099e-01],
       [ 9.03519750e-01],
       [ 8.62511754e-01],
       [ 9.60721791e-01],
       [ 7.92721361e-02],
       [ 3.49534154e-01],
       [ 5.85351884e-01],
       [ 6.21873319e-01],
       [ 1.88699923e-02],
       [ 2.49441117e-02],
       [ 7.86184743e-02],
       [ 3.96734536e-01],
       [ 3.10453534e-01],
       [ 6.29246116e-01],
       [ 1.47734880e-02],
       [ 4.12501693e-02],
       [ 2.87073739e-02],
       [ 1.39631346e-01],
       [ 4.73573983e-01],
       [ 3.40860724e-01],
       [ 7.09671736e-01],
       [ 7.50594378e-01],
       [ 4.16581184e-02],
       [ 2.32362375e-02],
       [ 2.50385888e-02],
       [ 4.13252786e-02],
       [ 3.04800987e-01],
       [ 1.01377940e+00],
       [ 7.52720416e-01],
       [ 7.43597031e-01],
       [ 6.08082473e-01],
       [ 6.95717454e-01],
       [ 8.30337763e-01],
       [ 8.94816406e-03],
       [ 1.94864310e-02],
       [ 1.02383278e-01],
       [ 2.72791207e-01],
       [ 3.10545385e-01],
       [ 3.19721818e-01],
       [ 6.72775149e-01],
       [ 8.18611309e-03],
       [ 3.26686651e-02],
       [ 6.97650015e-03],
       [ 6.91359937e-02],
       [ 5.47246337e-01],
       [ 4.60490048e-01],
       [ 4.82197523e-01],
       [ 6.05437994e-01],
       [ 7.40296960e-01],
       [ 7.14842200e-01],
       [ 2.18547881e-04],
       [ 1.95956174e-02],
       [ 1.43993646e-03],
       [ 2.03703661e-02],
       [ 3.97844434e-01],
       [ 2.89417505e-01],
       [ 1.02278545e-01],
       [ 3.53940129e-01],
       [ 5.62603951e-01],
       [ 6.96830034e-01],
       [-1.83758512e-03],
       [ 2.04903856e-02],
       [ 3.69492173e-02],
       [ 8.24723721e-01],
       [ 6.62797451e-01],
       [ 6.01511359e-01],
       [ 5.95045209e-01],
       [ 5.56310058e-01],
       [ 1.55084834e-01],
       [-2.71655619e-04],
       [ 9.23134014e-03],
       [ 2.68125907e-03],
       [ 1.51512578e-01],
       [ 5.63162565e-01],
       [ 8.09527278e-01],
       [ 1.03048217e+00],
       [ 4.42910790e-01],
       [ 5.43157816e-01],
       [ 9.16491866e-01],
       [ 4.87399161e-01],
       [ 5.84384620e-01],
       [ 8.90888572e-01],
       [ 5.62255859e-01],
       [ 4.06203032e-01],
       [ 7.58479685e-02],
       [ 2.57251561e-02],
       [ 1.40753649e-02],
       [ 8.87524337e-03],
       [ 1.62896216e-01],
       [ 8.17346692e-01],
       [ 5.45822799e-01],
       [ 5.63544989e-01],
       [ 6.78742409e-01],
       [ 9.49326396e-01],
       [ 7.99792349e-01],
       [ 8.90429139e-01],
       [ 8.97645950e-01],
       [ 8.26526761e-01],
       [ 8.93046319e-01],
       [ 5.05414844e-01],
       [ 2.01118384e-02],
       [ 7.76607543e-03],
       [-7.51458853e-03],
       [ 2.24787481e-02],
       [ 3.14474821e-01],
       [ 5.66564560e-01],
       [ 6.51905656e-01],
       [ 8.23845148e-01],
       [ 8.34683418e-01],
       [ 9.92256880e-01],
       [ 7.10119367e-01],
       [ 7.63072193e-01],
       [ 7.37335205e-01],
       [ 1.16573181e-02],
       [ 2.82000490e-02],
       [ 2.43417174e-02],
       [ 3.22088040e-02],
       [ 2.67070472e-01],
       [ 8.21869135e-01],
       [ 6.09078944e-01],
       [ 9.58528042e-01],
       [ 7.00735390e-01],
       [ 6.67298734e-01],
       [ 7.17845082e-01],
       [ 7.57033110e-01],
       [ 8.21964979e-01],
       [ 7.81396508e-01],
       [ 8.47375095e-01],
       [ 4.22929943e-01],
       [ 2.95185633e-02],
       [ 2.93998178e-02],
       [ 1.95721053e-02],
       [ 3.95904183e-02],
       [ 4.92490530e-01],
       [ 1.00212204e+00],
       [ 8.27939272e-01],
       [ 9.25132632e-01],
       [ 5.33899486e-01],
       [ 8.60736370e-01],
       [ 8.72973204e-01],
       [ 7.06800044e-01],
       [ 8.45223248e-01],
       [ 5.09561241e-01],
       [ 2.37144127e-01],
       [ 6.34560347e-01],
       [ 1.01906158e-01],
       [ 4.69390675e-02],
       [ 1.87154077e-02],
       [-1.62637606e-03],
       [ 5.14432602e-02],
       [ 6.24983072e-01],
       [ 7.71129012e-01],
       [ 6.14682376e-01],
       [ 9.58324552e-01],
       [ 8.12724710e-01],
       [ 8.74262214e-01],
       [ 7.94503868e-01],
       [ 4.97935653e-01],
       [ 7.36256123e-01],
       [ 1.04740012e+00],
       [ 8.35530877e-01],
       [ 9.49886665e-02],
       [-5.45422733e-03],
       [ 1.32428482e-02],
       [ 7.22902268e-03],
       [ 5.97644337e-02],
       [ 6.54555857e-01],
       [ 5.79126358e-01],
       [ 5.75346351e-01],
       [ 8.41977715e-01],
       [ 8.73941898e-01],
       [ 6.30851150e-01],
       [-2.62686014e-02],
       [ 4.98504192e-03],
       [ 1.16554480e-02],
       [ 4.19048518e-02],
       [ 2.37470165e-01],
       [ 7.41107464e-02],
       [ 1.44594520e-01],
       [ 6.47267342e-01],
       [ 5.45902550e-01],
       [ 8.25933695e-01],
       [ 7.76705801e-01],
       [ 4.12129819e-01],
       [-1.17516443e-02],
       [ 9.15094279e-03],
       [ 3.85175981e-02],
       [ 2.33496390e-02],
       [ 2.72631049e-01],
       [ 7.84280181e-01],
       [ 1.00749302e+00],
       [ 7.34715462e-01],
       [ 4.91177261e-01],
       [ 5.43624997e-01],
       [ 7.90628433e-01],
       [ 3.14279914e-01],
       [ 3.38963717e-02],
       [ 1.40553892e-01],
       [ 1.12730712e-02],
       [ 3.05290092e-02],
       [ 3.57407212e-01],
       [ 8.42363894e-01],
       [ 2.47791722e-01],
       [-2.28600614e-02],
       [ 1.58284288e-02],
       [ 1.93615593e-02],
       [ 1.69902258e-02],
       [ 1.01646274e-01],
       [ 3.03855181e-01],
       [ 2.94770181e-01],
       [ 2.87597001e-01],
       [ 6.77125216e-01],
       [ 1.06527102e+00],
       [ 5.60723066e-01],
       [ 4.86061633e-01],
       [ 1.83372542e-01],
       [ 1.00175269e-01],
       [ 1.75186247e-02],
       [ 3.33919302e-02],
       [ 9.59236994e-02],
       [ 5.69045022e-02],
       [ 1.26324311e-01],
       [ 1.11696661e-01],
       [ 2.08682902e-02],
       [ 1.45574138e-02],
       [ 1.09132603e-02],
       [-5.96141443e-03],
       [ 5.78714490e-01],
       [ 8.60284746e-01],
       [ 7.28479505e-01],
       [ 6.35191739e-01],
       [ 3.77052963e-01],
       [ 1.07984006e+00],
       [ 9.43132281e-01],
       [ 7.51920342e-01],
       [ 8.54809761e-01],
       [ 7.48525858e-01],
       [ 5.95870435e-01],
       [ 1.72636285e-02],
       [ 2.01091357e-02],
       [ 3.63647193e-03],
       [ 5.00619039e-03],
       [ 7.03907311e-02],
       [ 7.83053637e-01],
       [ 6.25834823e-01],
       [ 8.26543689e-01],
       [-2.22822875e-02],
       [-1.75819173e-03],
       [-6.52182102e-03],
       [ 1.13489464e-01],
       [ 6.72695458e-01],
       [ 4.16331351e-01],
       [-6.27797842e-03],
       [ 3.32073122e-03],
       [ 1.33833662e-02],
       [ 1.01312883e-02],
       [ 5.00284135e-03],
       [ 7.51496196e-01],
       [ 6.07992470e-01],
       [ 9.03002441e-01],
       [ 1.01776087e+00],
       [ 6.99643612e-01],
       [ 2.86070943e-01],
       [ 6.89296007e-01],
       [ 9.73695517e-01],
       [ 8.64832878e-01],
       [ 5.51819265e-01],
       [ 1.27823293e-01],
       [ 1.87693909e-03],
       [ 1.29799955e-02],
       [ 4.52734604e-02],
       [ 5.35456017e-02],
       [ 3.26881588e-01],
       [ 8.97060394e-01],
       [ 8.18379045e-01],
       [ 7.48735428e-01],
       [ 3.51739585e-01],
       [ 9.79565680e-01],
       [ 8.35877776e-01],
       [ 6.60353541e-01],
       [ 1.47751160e-02],
       [ 1.10356174e-02],
       [ 3.10353804e-02],
       [ 1.34083614e-01],
       [ 5.44891536e-01],
       [ 9.33475494e-01],
       [ 5.03392220e-01],
       [ 3.52953136e-01],
       [ 4.69867468e-01],
       [ 5.75408712e-03],
       [ 4.40293550e-03],
       [ 1.06954314e-02],
       [ 2.31740419e-02],
       [ 3.66861343e-01],
       [ 7.35533595e-01],
       [ 7.81739116e-01],
       [ 7.51463175e-01],
       [ 5.01673341e-01],
       [ 4.22006309e-01],
       [ 5.03830314e-01],
       [ 5.30950427e-01],
       [ 7.46912241e-01],
       [ 6.79204345e-01],
       [ 4.21214640e-01],
       [ 2.30804145e-01],
       [ 7.75747374e-03],
       [ 3.10455747e-02],
       [ 1.25801750e-02],
       [ 5.71801104e-02],
       [ 3.33983600e-01],
       [ 2.44879782e-01],
       [ 3.86197090e-01],
       [ 2.87531167e-01],
       [ 7.21359134e-01],
       [ 7.67082095e-01],
       [ 6.54654920e-01],
       [ 9.31557357e-01],
       [ 3.11998665e-01],
       [ 5.94955921e-01],
       [ 8.53108287e-01],
       [-8.66758823e-03],
       [-1.38858110e-02],
       [-1.08071081e-02],
       [ 1.73377432e-02],
       [ 5.36406040e-03],
       [ 6.45707011e-01],
       [ 8.20186496e-01],
       [ 4.97794747e-01],
       [ 5.61628938e-01],
       [ 7.31234491e-01],
       [ 6.39841020e-01],
       [ 2.82402039e-01],
       [ 6.44516110e-01],
       [ 6.50250316e-01],
       [ 3.22093844e-01],
       [ 1.92666668e-02],
       [ 1.00773759e-02],
       [ 6.82120025e-03],
       [ 4.32844460e-03],
       [ 1.67240482e-02],
       [ 5.65984368e-01],
       [ 5.37176430e-01],
       [ 5.11108279e-01],
       [ 5.03452718e-01],
       [ 5.44481397e-01],
       [ 6.66932046e-01],
       [ 7.38564968e-01],
       [ 8.03546906e-01],
       [ 7.23346233e-01],
       [ 6.19740009e-01],
       [ 1.44361183e-01],
       [ 1.55535042e-02],
       [ 2.42876653e-02],
       [ 1.38470978e-02],
       [ 4.86239791e-04],
       [ 8.72440636e-04],
       [ 3.80176425e-01],
       [ 4.55314517e-01],
       [ 1.56120867e-01],
       [ 8.66164863e-02],
       [ 3.70848656e-01],
       [ 7.10009336e-01],
       [ 6.75410867e-01],
       [ 8.18975329e-01],
       [ 7.12825060e-01],
       [ 6.18380785e-01],
       [ 5.13962388e-01],
       [ 4.29216288e-02],
       [ 1.45623181e-02],
       [ 7.47586042e-03],
       [ 4.35951352e-03],
       [ 9.78850760e-03],
       [ 1.82945773e-01],
       [ 4.72095430e-01],
       [ 6.83670402e-01],
       [ 6.50189638e-01],
       [ 4.75024521e-01],
       [ 5.27595520e-01],
       [ 6.98076010e-01],
       [ 9.40935314e-01],
       [ 1.00002003e+00],
       [ 6.48967266e-01],
       [ 1.63993299e-01],
       [ 1.81834754e-02],
       [ 1.65864043e-02],
       [ 1.66012347e-03],
       [ 6.49303570e-03],
       [ 8.49816017e-03],
       [ 1.66324958e-01],
       [ 6.25034213e-01],
       [ 5.68805814e-01],
       [ 3.37450385e-01],
       [ 3.66945148e-01],
       [ 4.29653347e-01],
       [ 8.04154754e-01],
       [ 8.03143501e-01],
       [ 7.62894392e-01],
       [ 8.45993280e-01],
       [ 7.79635847e-01],
       [ 3.04546118e-01],
       [ 4.18165624e-02],
       [ 6.48818910e-03],
       [ 4.52208892e-03],
       [ 6.57745823e-03],
       [ 5.65838665e-02],
       [ 6.43115819e-01],
       [ 2.71743596e-01],
       [ 5.32112718e-01],
       [ 4.23481166e-01],
       [ 7.37971306e-01],
       [ 5.13296545e-01],
       [ 9.77295339e-02],
       [ 5.00796616e-01],
       [ 3.13975990e-01],
       [ 1.87634617e-01],
       [ 7.22563863e-02],
       [ 5.81292696e-02],
       [ 3.15232575e-02],
       [ 9.98460874e-03],
       [ 4.69466299e-03],
       [ 7.00406283e-02],
       [ 6.87591314e-01],
       [ 3.42376351e-01],
       [ 4.28404510e-01],
       [ 6.90549254e-01],
       [ 7.08639622e-01],
       [ 4.83799160e-01],
       [ 7.07171500e-01],
       [ 7.74970531e-01],
       [ 8.89569163e-01],
       [ 9.09669995e-01],
       [ 2.25167677e-01],
       [ 2.36100890e-02],
       [ 3.58066708e-03],
       [ 6.43762201e-03],
       [ 1.70793422e-02],
       [ 4.86887932e-01],
       [ 4.72949743e-01],
       [ 5.72925329e-01],
       [ 8.41729879e-01],
       [ 8.57495606e-01],
       [ 7.86140978e-01],
       [ 6.08226776e-01],
       [ 2.13091120e-01],
       [ 4.06414457e-02],
       [ 3.73545140e-02],
       [ 2.44530179e-02],
       [ 1.09626222e-02],
       [ 7.03111291e-03],
       [ 3.24549794e-01],
       [ 9.31982458e-01],
       [ 4.73629057e-01],
       [ 8.77098978e-01],
       [ 8.58264387e-01],
       [ 9.35755193e-01],
       [-1.51790157e-02],
       [-2.16174871e-03],
       [ 2.41156686e-02],
       [ 3.76968831e-02],
       [ 5.04775584e-01],
       [ 9.01649296e-01],
       [ 1.12463367e+00],
       [ 7.81105876e-01],
       [ 7.16453910e-01],
       [ 6.83054328e-01],
       [ 8.64376128e-01],
       [ 9.28523481e-01],
       [ 9.00977373e-01],
       [ 7.99429178e-01],
       [ 5.73422849e-01],
       [ 5.59056997e-01],
       [ 3.33328471e-02],
       [ 2.83960551e-02],
       [ 1.27955675e-02],
       [ 4.36008088e-02],
       [ 1.51411027e-01],
       [ 2.89983273e-01],
       [ 4.57698524e-01],
       [ 6.51364684e-01],
       [ 5.96692801e-01],
       [ 7.31821358e-01],
       [ 7.29487538e-01],
       [ 1.02763593e+00],
       [ 8.27130318e-01],
       [ 2.04843968e-01],
       [ 4.80043948e-01],
       [ 1.84957728e-01],
       [ 1.12642348e-03],
       [ 1.90652944e-02],
       [ 1.07269809e-02],
       [ 1.11181289e-03],
       [ 2.77638659e-02],
       [ 6.75315738e-01],
       [ 7.57792950e-01],
       [ 7.25896478e-01],
       [ 8.98909986e-01],
       [ 8.20354283e-01],
       [ 4.28728878e-01],
       [ 7.17651546e-01],
       [ 6.60932183e-01],
       [ 5.28330386e-01],
       [ 9.77499366e-01],
       [ 7.81623125e-01],
       [ 1.73135214e-02],
       [-2.79097632e-03],
       [ 2.07954310e-02],
       [ 1.43663716e-02],
       [ 2.83045590e-01],
       [ 6.10221863e-01],
       [ 6.94213748e-01],
       [ 6.44855082e-01],
       [ 8.46481681e-01],
       [ 8.83395076e-01],
       [ 5.73353231e-01],
       [ 4.25395489e-01],
       [ 6.92171276e-01],
       [ 8.37764025e-01],
       [ 8.20333779e-01],
       [ 5.47841311e-01],
       [ 2.92367022e-02],
       [ 6.76105917e-03],
       [ 3.37970480e-02],
       [ 4.14672121e-02],
       [ 1.71902880e-01],
       [ 5.31085551e-01],
       [ 6.63068116e-01],
       [ 6.76882267e-01],
       [ 7.24504709e-01],
       [ 8.58909369e-01],
       [ 5.78040004e-01],
       [ 5.36960244e-01],
       [ 7.88513422e-01],
       [ 7.96858907e-01],
       [ 7.03459978e-01],
       [ 4.32598114e-01],
       [ 2.58655511e-02],
       [ 6.80421293e-03],
       [ 2.76961904e-02],
       [ 2.79157665e-02],
       [ 1.75616905e-01],
       [ 5.86650968e-01],
       [ 6.30928993e-01],
       [ 5.79326391e-01],
       [ 7.74456322e-01],
       [ 8.80732000e-01],
       [ 6.97645903e-01],
       [ 6.40814900e-01],
       [ 8.05052161e-01],
       [ 7.75466681e-01],
       [ 7.07855105e-01],
       [ 2.46585503e-01],
       [ 7.00943917e-03],
       [ 1.09508373e-02],
       [ 2.25520022e-02],
       [ 1.53032318e-02],
       [ 2.64052749e-01],
       [ 6.89724088e-01],
       [ 4.93446052e-01],
       [ 7.26264000e-01],
       [ 8.05384934e-01],
       [ 8.00853610e-01],
       [ 7.09846556e-01],
       [ 6.80059433e-01],
       [ 9.26169038e-01],
       [ 8.37001026e-01],
       [ 3.54289114e-01],
       [ 2.04760298e-01],
       [ 1.99250877e-03],
       [ 2.08751895e-02],
       [ 2.02035531e-02],
       [-5.43035567e-05],
       [ 2.46475376e-02],
       [ 6.92131817e-01],
       [ 5.99285305e-01],
       [ 7.27008760e-01],
       [ 8.98656726e-01],
       [ 8.46624196e-01],
       [ 6.33069038e-01],
       [ 7.90124834e-01],
       [ 8.33286762e-01],
       [ 7.28330016e-01],
       [ 9.39581394e-01],
       [ 5.91997504e-01],
       [ 2.53955312e-02],
       [ 9.04357433e-03],
       [ 9.85086709e-03],
       [ 4.11886498e-02],
       [ 4.05178666e-01],
       [ 7.19470978e-01],
       [ 4.43443120e-01],
       [ 7.41086364e-01],
       [ 7.83583999e-01],
       [ 9.23865259e-01],
       [ 6.21978879e-01],
       [ 6.94397464e-03],
       [ 3.36581208e-02],
       [ 3.00109182e-02],
       [ 6.75419793e-02],
       [ 5.68276525e-01],
       [ 5.21349967e-01],
       [ 5.43462336e-01],
       [ 8.68263721e-01],
       [ 4.73347962e-01],
       [ 7.97144890e-01],
       [ 8.73817682e-01],
       [ 5.47578186e-03],
       [ 1.42284874e-02],
       [ 1.67074259e-02],
       [ 3.66739333e-02],
       [ 3.38510454e-01],
       [ 7.72567093e-01],
       [ 1.00792301e+00],
       [ 8.41813028e-01],
       [ 5.76813519e-01],
       [ 6.50040686e-01],
       [ 6.00159466e-01],
       [-2.09175795e-03],
       [ 2.77234167e-02],
       [ 2.43866339e-01],
       [ 2.17067786e-02],
       [ 8.10987651e-02],
       [ 7.50850916e-01],
       [ 6.40693426e-01],
       [ 3.80116642e-01],
       [ 7.32286930e-01],
       [ 5.70691168e-01],
       [ 4.70376372e-01],
       [ 3.18367034e-03],
       [ 5.32951206e-04],
       [ 7.52594098e-02],
       [ 4.25300747e-03],
       [ 1.01983771e-01],
       [ 7.50001073e-01],
       [ 7.99833894e-01],
       [ 4.80210960e-01],
       [ 5.96967936e-01],
       [ 5.70848644e-01],
       [ 4.82637763e-01],
       [ 6.25371218e-01],
       [ 5.40002644e-01],
       [ 6.00121558e-01],
       [ 1.45359218e-01],
       [ 2.38120407e-02],
       [ 3.89874317e-02],
       [ 1.43542260e-01],
       [ 2.61140391e-02],
       [ 3.75375971e-02],
       [ 4.50645149e-01],
       [ 5.18340409e-01],
       [-1.51208974e-02],
       [ 1.21811498e-02],
       [ 4.45563085e-02],
       [ 8.10565501e-02],
       [ 5.39216638e-01],
       [ 9.41934228e-01],
       [ 6.56165838e-01],
       [ 3.79102230e-01],
       [ 3.42658535e-03],
       [ 2.24048328e-02],
       [ 1.89677402e-02],

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
16551     28546.0  27911.718674  25071.187461           NaN
16552     28723.0  28552.281566  25834.987615           NaN
16553     26967.0  28173.508713  26222.885304           NaN
16554     26336.0  25031.833853    23317.3981           NaN
16555     23562.0   21975.28109  23437.167632           NaN
...           ...           ...           ...           ...
18273      7356.0   5632.366084   5438.219944   3277.965576
18274     17638.0  18901.861998  18263.627162  30000.000000
18275     23339.0   24148.93331  21918.767881  17159.171875
18276     26323.0  25572.670269  24646.911253  12295.125000
18278     25598.0  26338.372419   26127.13712  14554.519531

[914 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,985 (1.55 MB)

 Trainable params: 405,729 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 613s 593ms/step - loss: 0.1061 - mae: 0.3167 - val_loss: 0.1543 - val_mae: 0.4211
Epoch 2/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 244s 451ms/step - loss: 0.1048 - mae: 0.3155 - val_loss: 0.1504 - val_mae: 0.4170
Epoch 3/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 279s 472ms/step - loss: 0.0996 - mae: 0.3041 - val_loss: 0.1385 - val_mae: 0.3922
Epoch 4/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 268s 470ms/step - loss: 0.1008 - mae: 0.3074 - val_loss: 0.1395 - val_mae: 0.3975
Epoch 5/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 273s 479ms/step - loss: 0.0891 - mae: 0.2810 - val_loss: 0.0760 - val_mae: 0.2842
Epoch 6/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 226s 397ms/step - loss: 0.0863 - mae: 0.2806 - val_loss: 0.0898 - val_mae: 0.3007
Epoch 7/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 256s 379ms/step - loss: 0.0726 - mae: 0.2525 - val_loss: 0.0411 - val_mae: 0.1964
Epoch 8/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 202s 372ms/step - loss: 0.0618 - mae: 0.2361 - val_loss: 0.0429 - val_mae: 0.2116
Epoch 9/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 214s 382ms/step - loss: 0.0468 - mae: 0.2016 - val_loss: 0.0305 - val_mae: 0.1716
Epoch 10/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 312s 468ms/step - loss: 0.0478 - mae: 0.2056 - val_loss: 0.0265 - val_mae: 0.1598
Epoch 11/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 276s 483ms/step - loss: 0.0407 - mae: 0.1888 - val_loss: 0.0259 - val_mae: 0.1602
Epoch 12/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 248s 465ms/step - loss: 0.0382 - mae: 0.1816 - val_loss: 0.0241 - val_mae: 0.1545
Epoch 13/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 256s 475ms/step - loss: 0.0392 - mae: 0.1854 - val_loss: 0.0241 - val_mae: 0.1525
Epoch 14/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 243s 431ms/step - loss: 0.0352 - mae: 0.1730 - val_loss: 0.0232 - val_mae: 0.1514
Epoch 15/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 264s 428ms/step - loss: 0.0321 - mae: 0.1655 - val_loss: 0.0239 - val_mae: 0.1496
Epoch 16/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 256s 407ms/step - loss: 0.0315 - mae: 0.1635 - val_loss: 0.0251 - val_mae: 0.1589
Epoch 17/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 284s 439ms/step - loss: 0.0292 - mae: 0.1565 - val_loss: 0.0234 - val_mae: 0.1510
Epoch 18/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 269s 440ms/step - loss: 0.0315 - mae: 0.1644 - val_loss: 0.0265 - val_mae: 0.1618
Epoch 19/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 241s 387ms/step - loss: 0.0307 - mae: 0.1584 - val_loss: 0.0245 - val_mae: 0.1496
Epoch 20/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 214s 397ms/step - loss: 0.0285 - mae: 0.1556 - val_loss: 0.0256 - val_mae: 0.1579
Epoch 21/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 223s 416ms/step - loss: 0.0265 - mae: 0.1483 - val_loss: 0.0240 - val_mae: 0.1449
Epoch 22/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 223s 411ms/step - loss: 0.0252 - mae: 0.1455 - val_loss: 0.0230 - val_mae: 0.1426
Epoch 23/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 254s 385ms/step - loss: 0.0243 - mae: 0.1430 - val_loss: 0.0219 - val_mae: 0.1355
Epoch 24/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 261s 375ms/step - loss: 0.0249 - mae: 0.1442 - val_loss: 0.0215 - val_mae: 0.1340
Epoch 25/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 197s 357ms/step - loss: 0.0246 - mae: 0.1429 - val_loss: 0.0252 - val_mae: 0.1556
Epoch 26/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 211s 390ms/step - loss: 0.0244 - mae: 0.1431 - val_loss: 0.0236 - val_mae: 0.1470
Epoch 27/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 275s 408ms/step - loss: 0.0228 - mae: 0.1390 - val_loss: 0.0213 - val_mae: 0.1381
Epoch 28/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 245s 362ms/step - loss: 0.0244 - mae: 0.1417 - val_loss: 0.0230 - val_mae: 0.1410
Epoch 29/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 210s 392ms/step - loss: 0.0228 - mae: 0.1390 - val_loss: 0.0224 - val_mae: 0.1317
Epoch 30/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 244s 348ms/step - loss: 0.0219 - mae: 0.1356 - val_loss: 0.0215 - val_mae: 0.1373
Epoch 31/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 177s 323ms/step - loss: 0.0229 - mae: 0.1377 - val_loss: 0.0220 - val_mae: 0.1378
Epoch 32/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 236s 380ms/step - loss: 0.0229 - mae: 0.1375 - val_loss: 0.0216 - val_mae: 0.1392
Epoch 33/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 178s 329ms/step - loss: 0.0213 - mae: 0.1327 - val_loss: 0.0226 - val_mae: 0.1454
Epoch 34/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 175s 270ms/step - loss: 0.0209 - mae: 0.1302 - val_loss: 0.0242 - val_mae: 0.1494
Epoch 35/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 139s 261ms/step - loss: 0.0234 - mae: 0.1391 - val_loss: 0.0229 - val_mae: 0.1385
Epoch 36/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 145s 269ms/step - loss: 0.0228 - mae: 0.1379 - val_loss: 0.0237 - val_mae: 0.1514
Epoch 37/100
527/527 ━━━━━━━━━━━━━━━━━━━━ 147s 276ms/step - loss: 0.0200 - mae: 0.1279 - val_loss: 0.0215 - val_mae: 0.1337

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

28/28 ━━━━━━━━━━━━━━━━━━━━ 38s 824ms/step

array([[7.1311688e-01],
       [7.0359111e-01],
       [6.9095010e-01],
       [6.3197130e-01],
       [5.9145850e-01],
       [4.6305358e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.9201040e-01],
       [6.3998175e-01],
       [6.6377026e-01],
       [6.6325420e-01],
       [6.5615195e-01],
       [6.6877878e-01],
       [6.5890861e-01],
       [6.8396306e-01],
       [6.2228876e-01],
       [5.5953974e-01],
       [4.9951997e-01],
       [5.4587513e-01],
       [2.1028824e-02],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.1160601e-01],
       [6.8799460e-01],
       [6.9395137e-01],
       [7.0801079e-01],
       [6.8318254e-01],
       [6.8450898e-01],
       [7.3837411e-01],
       [7.6834816e-01],
       [7.7653617e-01],
       [7.3331827e-01],
       [6.3479710e-01],
       [4.2257011e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.8851789e-01],
       [7.0895863e-01],
       [7.2678167e-01],
       [7.7648813e-01],
       [7.8308290e-01],
       [7.6151556e-01],
       [7.9614496e-01],
       [8.0621541e-01],
       [8.1049514e-01],
       [7.5040746e-01],
       [6.7551506e-01],
       [5.4114401e-01],
       [1.9766355e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.4209048e-01],
       [6.8401355e-01],
       [6.4625204e-01],
       [6.7838943e-01],
       [7.0218074e-01],
       [7.0969373e-01],
       [7.7416086e-01],
       [6.2709248e-01],
       [0.0000000e+00],
       [3.9530963e-01],
       [7.0148927e-01],
       [7.1235067e-01],
       [6.9931346e-01],
       [6.7497170e-01],
       [7.0717776e-01],
       [7.2413456e-01],
       [7.4014223e-01],
       [7.4005294e-01],
       [6.1832774e-01],
       [4.9865511e-01],
       [2.7113423e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.7974280e-01],
       [5.4671401e-01],
       [4.9201763e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.3615226e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.3858276e-01],
       [6.6306514e-01],
       [5.8887643e-01],
       [6.9414747e-01],
       [7.3870581e-01],
       [7.9502338e-01],
       [7.9328763e-01],
       [7.6632458e-01],
       [6.5471327e-01],
       [3.0706912e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.7981723e-01],
       [6.7580318e-01],
       [6.2399232e-01],
       [6.7181915e-01],
       [0.0000000e+00],
       [3.2799944e-01],
       [5.7991588e-01],
       [5.4619068e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.0614409e-01],
       [5.1354480e-01],
       [4.3879259e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.8142616e-01],
       [6.8078506e-01],
       [5.9432286e-01],
       [6.5800130e-01],
       [6.8969780e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.2744029e-01],
       [7.0706761e-01],
       [6.8477207e-01],
       [6.2114739e-01],
       [6.7521036e-01],
       [6.9892257e-01],
       [6.7703301e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.4349394e-01],
       [6.1346412e-01],
       [5.6904858e-01],
       [6.2971687e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.4996406e-01],
       [6.1084932e-01],
       [5.9322309e-01],
       [5.7596576e-01],
       [6.7902815e-01],
       [7.5133938e-01],
       [7.4055117e-01],
       [1.8377957e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.6373001e-01],
       [5.7217431e-01],
       [5.2686805e-01],
       [6.9838494e-01],
       [8.1109250e-01],
       [7.7433413e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.3073232e-01],
       [7.4115372e-01],
       [7.1387571e-01],
       [7.4019086e-01],
       [6.6555703e-01],
       [2.4456039e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.8224331e-01],
       [6.6586083e-01],
       [6.3237959e-01],
       [5.8753353e-01],
       [6.3052404e-01],
       [7.2246230e-01],
       [7.8158760e-01],
       [7.7963638e-01],
       [7.2275102e-01],
       [6.1666137e-01],
       [2.5735903e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.6857632e-01],
       [6.9415760e-01],
       [7.3114252e-01],
       [7.6409775e-01],
       [7.5613081e-01],
       [7.3016858e-01],
       [7.4189407e-01],
       [7.1111012e-01],
       [7.0799953e-01],
       [6.9933558e-01],
       [5.7058543e-01],
       [3.0100411e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.6369738e-01],
       [5.5292571e-01],
       [6.2615782e-01],
       [6.4852494e-01],
       [7.5963569e-01],
       [7.4810064e-01],
       [8.0570465e-01],
       [7.5773340e-01],
       [5.9971058e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.1121883e-01],
       [6.2982500e-01],
       [6.7200476e-01],
       [7.5264871e-01],
       [7.3871458e-01],
       [7.5030017e-01],
       [7.4555951e-01],
       [7.0777237e-01],
       [7.3553538e-01],
       [6.6213113e-01],
       [4.7106746e-01],
       [1.6697086e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.6621402e-01],
       [6.8835455e-01],
       [6.7443061e-01],
       [7.1561086e-01],
       [7.2158521e-01],
       [7.5436985e-01],
       [7.6940596e-01],
       [7.7157676e-01],
       [7.6043057e-01],
       [7.0452642e-01],
       [5.1386619e-01],
       [3.5407084e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.4377742e-01],
       [7.3235214e-01],
       [7.4260271e-01],
       [7.5142115e-01],
       [7.5391829e-01],
       [7.4805731e-01],
       [7.5748074e-01],
       [7.4896115e-01],
       [7.3723143e-01],
       [6.5546149e-01],
       [5.3386968e-01],
       [3.4935784e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.3470445e-01],
       [6.7278117e-01],
       [6.8427044e-01],
       [6.3667941e-01],
       [7.1588469e-01],
       [6.9879824e-01],
       [7.2130030e-01],
       [2.1875194e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.3567183e-01],
       [5.8383852e-01],
       [5.3528154e-01],
       [5.9843260e-01],
       [5.6488800e-01],
       [5.9084940e-01],
       [1.5145203e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.8554422e-01],
       [7.1852565e-01],
       [7.1213895e-01],
       [6.9041693e-01],
       [6.9040346e-01],
       [6.6905940e-01],
       [6.7676592e-01],
       [2.7081630e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.1230283e-01],
       [5.7367164e-01],
       [4.4534314e-01],
       [1.7029035e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.3336225e-01],
       [6.2835515e-01],
       [4.7731170e-01],
       [7.0057464e-01],
       [8.0905306e-01],
       [7.8215158e-01],
       [6.9147432e-01],
       [5.3482109e-01],
       [1.6591239e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.0624706e-01],
       [2.8222200e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [7.6162207e-01],
       [7.7716196e-01],
       [7.9163587e-01],
       [7.0531940e-01],
       [7.6714098e-01],
       [8.0504972e-01],
       [7.9023504e-01],
       [7.0037591e-01],
       [6.2100577e-01],
       [2.7172738e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.4649429e-01],
       [6.4989328e-01],
       [6.1703002e-01],
       [6.5465486e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.5195047e-01],
       [6.2980336e-01],
       [5.8951128e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.1312865e-01],
       [6.3756943e-01],
       [6.0690874e-01],
       [6.5063274e-01],
       [7.0725328e-01],
       [7.7099353e-01],
       [8.2795286e-01],
       [8.4001970e-01],
       [8.3144891e-01],
       [7.7335888e-01],
       [6.7339772e-01],
       [3.8444284e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.6864854e-01],
       [6.6765219e-01],
       [6.4019096e-01],
       [7.1162701e-01],
       [7.4804413e-01],
       [8.0239606e-01],
       [8.0750096e-01],
       [4.2238724e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.2711234e-01],
       [6.0344338e-01],
       [5.4790527e-01],
       [7.0858419e-01],
       [4.0968701e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.5222540e-01],
       [7.5915992e-01],
       [7.3435616e-01],
       [7.3031116e-01],
       [6.5990126e-01],
       [6.7484009e-01],
       [7.3547673e-01],
       [7.1795380e-01],
       [6.0191441e-01],
       [4.4225615e-01],
       [1.9028890e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.0927231e-01],
       [6.5747589e-01],
       [5.9597319e-01],
       [6.2796432e-01],
       [6.5302289e-01],
       [6.9518834e-01],
       [7.6690263e-01],
       [7.7152294e-01],
       [6.7399740e-01],
       [4.5764250e-01],
       [4.2687842e-01],
       [3.3261278e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.2435171e-02],
       [4.5164734e-01],
       [6.1577070e-01],
       [6.2374508e-01],
       [5.6895709e-01],
       [5.2527106e-01],
       [6.0628742e-01],
       [6.5767181e-01],
       [6.5300846e-01],
       [6.5097821e-01],
       [5.4373413e-01],
       [3.7071168e-01],
       [2.0328604e-02],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [6.8028390e-02],
       [4.2543733e-01],
       [6.5243852e-01],
       [6.4701569e-01],
       [6.4706910e-01],
       [6.3299799e-01],
       [6.1832899e-01],
       [6.2288916e-01],
       [5.9625000e-01],
       [5.4760951e-01],
       [4.4128427e-01],
       [3.1902993e-01],
       [1.7239401e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.9633150e-01],
       [4.7168803e-01],
       [5.2899909e-01],
       [5.2066028e-01],
       [5.5342996e-01],
       [5.6132990e-01],
       [5.5482453e-01],
       [5.5495906e-01],
       [5.7072783e-01],
       [4.6509138e-01],
       [3.8824010e-01],
       [1.4950339e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.7311187e-06],
       [2.4027660e-01],
       [4.2527157e-01],
       [5.0036198e-01],
       [5.7329851e-01],
       [5.1906472e-01],
       [5.9550029e-01],
       [5.8354127e-01],
       [6.0701478e-01],
       [5.5899251e-01],
       [5.0737494e-01],
       [3.1091118e-01],
       [6.9810964e-02],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.6307449e-01],
       [5.0410825e-01],
       [5.2903628e-01],
       [5.7548487e-01],
       [5.6526256e-01],
       [5.7402420e-01],
       [6.0555488e-01],
       [5.1566356e-01],
       [4.2163026e-01],
       [3.9088041e-01],
       [3.4471938e-01],
       [7.6418862e-02],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.7549163e-01],
       [4.6044439e-01],
       [4.8740745e-01],
       [4.7413054e-01],
       [5.2939636e-01],
       [5.9538931e-01],
       [5.8217728e-01],
       [5.9585559e-01],
       [6.3834798e-01],
       [4.5924771e-01],
       [3.8816112e-01],
       [1.0382570e-02],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.9726798e-01],
       [5.3378111e-01],
       [5.5728972e-01],
       [6.9880527e-01],
       [6.5675694e-01],
       [6.3504893e-01],
       [6.5052563e-01],
       [6.5750843e-01],
       [6.7584610e-01],
       [6.0595417e-01],
       [5.3719413e-01],
       [7.9423420e-02],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.6830101e-01],
       [4.7210839e-01],
       [6.1645800e-01],
       [6.6455734e-01],
       [7.0941305e-01],
       [6.7742902e-01],
       [6.6816831e-01],
       [3.0364293e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.5470874e-01],
       [5.7175279e-01],
       [5.3839093e-01],
       [6.0297632e-01],
       [6.7511016e-01],
       [6.9723320e-01],
       [7.7068514e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.2079471e-01],
       [7.3799205e-01],
       [7.3990238e-01],
       [7.6548612e-01],
       [7.6394665e-01],
       [7.6379472e-01],
       [7.5033402e-01],
       [7.4872303e-01],
       [7.2863859e-01],
       [6.9519711e-01],
       [6.0783988e-01],
       [4.1863555e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.2663853e-01],
       [6.2197030e-01],
       [6.2234116e-01],
       [7.3159391e-01],
       [7.2567081e-01],
       [7.3035693e-01],
       [7.4665451e-01],
       [7.5857109e-01],
       [7.4721068e-01],
       [7.0039344e-01],
       [5.8882582e-01],
       [3.3959687e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.1148728e-01],
       [7.1406883e-01],
       [6.7714369e-01],
       [7.0745802e-01],
       [7.2370583e-01],
       [7.2146976e-01],
       [7.2266155e-01],
       [7.1265990e-01],
       [6.8699294e-01],
       [6.2991619e-01],
       [6.4940453e-01],
       [3.9306960e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.9871595e-01],
       [6.9569302e-01],
       [6.7972052e-01],
       [6.6792047e-01],
       [6.8523484e-01],
       [6.6788232e-01],
       [6.9221926e-01],
       [6.8027097e-01],
       [6.9127095e-01],
       [6.2172812e-01],
       [4.7810581e-01],
       [2.9326537e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.8167123e-01],
       [6.8051100e-01],
       [7.0153284e-01],
       [7.2039145e-01],
       [6.8891156e-01],
       [7.0992243e-01],
       [6.9450253e-01],
       [7.5070244e-01],
       [7.2545761e-01],
       [6.2614745e-01],
       [3.7281978e-01],
       [2.4271485e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.6452271e-01],
       [6.4552003e-01],
       [6.6401184e-01],
       [7.0156872e-01],
       [7.3034978e-01],
       [6.9760823e-01],
       [7.3840582e-01],
       [7.4824893e-01],
       [7.4746168e-01],
       [6.1308825e-01],
       [5.5407661e-01],
       [2.3410133e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [3.8797864e-01],
       [5.8863592e-01],
       [6.4617431e-01],
       [7.3810780e-01],
       [6.8132228e-01],
       [6.5223074e-01],
       [6.8477243e-01],
       [7.2964287e-01],
       [7.1928614e-01],
       [6.7494047e-01],
       [3.5867265e-01],
       [1.4517750e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.6169599e-01],
       [6.5146023e-01],
       [6.6479260e-01],
       [7.1972442e-01],
       [7.4367809e-01],
       [7.4278510e-01],
       [7.7435857e-01],
       [7.2670376e-01],
       [7.2987854e-01],
       [5.5412531e-01],
       [4.1654205e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [4.1562659e-01],
       [6.4569259e-01],
       [6.2215424e-01],
       [6.4344150e-01],
       [7.1075302e-01],
       [6.9736719e-01],
       [7.7974725e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.8054541e-01],
       [6.4835566e-01],
       [6.9690639e-01],
       [7.9611993e-01],
       [7.3269212e-01],
       [7.3359746e-01],
       [7.6021534e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.6762373e-01],
       [7.1128052e-01],
       [7.5162750e-01],
       [7.7319586e-01],
       [6.6947126e-01],
       [7.3158127e-01],
       [7.5915039e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.6461150e-01],
       [7.0078290e-01],
       [7.4081528e-01],
       [7.5053233e-01],
       [6.9331545e-01],
       [7.0211697e-01],
       [7.4371487e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [9.8736525e-02],
       [6.7827141e-01],
       [5.7765007e-01],
       [6.1094707e-01],
       [6.4914763e-01],
       [6.8968511e-01],
       [7.5116760e-01],
       [6.9959641e-01],
       [6.9870943e-01],
       [4.0032920e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.0002392e-01],
       [5.5119628e-01],
       [4.5538223e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.0185487e-01],
       [6.0299587e-01],
       [5.6795770e-01],
       [6.1206865e-01],
       [6.5658367e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.9586018e-01],
       [6.6141343e-01],
       [6.4486933e-01],
       [7.2315353e-01],
       [5.4660755e-01],
       [6.7503172e-01],
       [7.4991083e-01],
       [7.5160414e-01],
       [6.6819918e-01],
       [4.5765284e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.0113151e-01],
       [5.4737210e-01],
       [5.8819848e-01],
       [7.4814969e-01],
       [6.9156319e-01],
       [7.7034688e-01],
       [8.1787062e-01],
       [8.0611491e-01],
       [7.4283415e-01],
       [6.6213942e-01],
       [3.9999431e-01],
       [2.0362096e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [8.4359840e-02],
       [7.4220216e-01],
       [7.3757458e-01],
       [7.4308527e-01],
       [7.3124874e-01],
       [7.4275255e-01],
       [7.2740448e-01],
       [7.1626633e-01],
       [6.7538697e-01],
       [6.8082929e-01],
       [5.7924777e-01],
       [1.8634018e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [6.2165380e-01],
       [6.3461542e-01],
       [6.2759942e-01],
       [6.2660450e-01],
       [6.4196688e-01],
       [6.3547957e-01],
       [6.5587211e-01],
       [6.4946938e-01],
       [6.2533164e-01],
       [4.1152418e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.8572786e-01],

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
16551     28546.0  27911.718674  25071.187461           NaN           NaN
16552     28723.0  28552.281566  25834.987615           NaN           NaN
16553     26967.0  28173.508713  26222.885304           NaN           NaN
16554     26336.0  25031.833853    23317.3981           NaN           NaN
16555     23562.0   21975.28109  23437.167632           NaN           NaN
...           ...           ...           ...           ...           ...
18273      7356.0   5632.366084   5438.219944   3277.965576      0.000000
18274     17638.0  18901.861998  18263.627162  30000.000000  18738.458984
18275     23339.0   24148.93331  21918.767881  17159.171875  19559.654297
18276     26323.0  25572.670269  24646.911253  12295.125000  18438.984375
18278     25598.0  26338.372419   26127.13712  14554.519531  19441.283203

[914 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

16623    20640.0
16624    19885.0
16625    19763.0
16626    19090.0
16627    24460.0
          ...
18273     7356.0
18274    17638.0
18275    23339.0
18276    26323.0
18278    25598.0
Name: Generación, Length: 866, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 9)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      2,368 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 474,049 (1.81 MB)

 Trainable params: 474,049 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 217s 189ms/step - loss: 1.0846 - mae: 0.2955 - val_loss: 0.5440 - val_mae: 0.3208
Epoch 2/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 70s 132ms/step - loss: 0.4198 - mae: 0.2647 - val_loss: 0.2251 - val_mae: 0.2117
Epoch 3/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 33s 112ms/step - loss: 0.1680 - mae: 0.1744 - val_loss: 0.1180 - val_mae: 0.1853
Epoch 4/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 47s 130ms/step - loss: 0.0950 - mae: 0.1632 - val_loss: 0.0823 - val_mae: 0.1726
Epoch 5/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 41s 139ms/step - loss: 0.0654 - mae: 0.1492 - val_loss: 0.0822 - val_mae: 0.1805
Epoch 6/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 51s 167ms/step - loss: 0.0541 - mae: 0.1420 - val_loss: 0.0643 - val_mae: 0.1610
Epoch 7/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 61s 82ms/step - loss: 0.0467 - mae: 0.1336 - val_loss: 0.0582 - val_mae: 0.1563
Epoch 8/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 49s 110ms/step - loss: 0.0446 - mae: 0.1323 - val_loss: 0.0537 - val_mae: 0.1482
Epoch 9/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 47s 164ms/step - loss: 0.0453 - mae: 0.1353 - val_loss: 0.0538 - val_mae: 0.1478
Epoch 10/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 84s 157ms/step - loss: 0.0402 - mae: 0.1283 - val_loss: 0.0614 - val_mae: 0.1568
Epoch 11/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 85s 154ms/step - loss: 0.0384 - mae: 0.1254 - val_loss: 0.0500 - val_mae: 0.1483
Epoch 12/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 87s 163ms/step - loss: 0.0367 - mae: 0.1245 - val_loss: 0.0519 - val_mae: 0.1529
Epoch 13/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 35s 121ms/step - loss: 0.0373 - mae: 0.1255 - val_loss: 0.0572 - val_mae: 0.1500
Epoch 14/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 42s 120ms/step - loss: 0.0373 - mae: 0.1253 - val_loss: 0.0485 - val_mae: 0.1428
Epoch 15/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 48s 140ms/step - loss: 0.0361 - mae: 0.1233 - val_loss: 0.0501 - val_mae: 0.1415
Epoch 16/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 49s 158ms/step - loss: 0.0358 - mae: 0.1220 - val_loss: 0.0548 - val_mae: 0.1623
Epoch 17/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 35s 124ms/step - loss: 0.0352 - mae: 0.1196 - val_loss: 0.0722 - val_mae: 0.1740
Epoch 18/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 56s 166ms/step - loss: 0.0348 - mae: 0.1186 - val_loss: 0.0485 - val_mae: 0.1369
Epoch 19/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 81s 151ms/step - loss: 0.0330 - mae: 0.1149 - val_loss: 0.0455 - val_mae: 0.1359
Epoch 20/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 34s 119ms/step - loss: 0.0336 - mae: 0.1172 - val_loss: 0.0498 - val_mae: 0.1522
Epoch 21/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 39s 101ms/step - loss: 0.0335 - mae: 0.1181 - val_loss: 0.0448 - val_mae: 0.1367
Epoch 22/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 33s 123ms/step - loss: 0.0297 - mae: 0.1079 - val_loss: 0.0468 - val_mae: 0.1421
Epoch 23/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 39s 143ms/step - loss: 0.0319 - mae: 0.1157 - val_loss: 0.0475 - val_mae: 0.1384
Epoch 24/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 40s 132ms/step - loss: 0.0301 - mae: 0.1105 - val_loss: 0.0466 - val_mae: 0.1410
Epoch 25/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 39s 118ms/step - loss: 0.0316 - mae: 0.1116 - val_loss: 0.0572 - val_mae: 0.1751
Epoch 26/50
264/264 ━━━━━━━━━━━━━━━━━━━━ 45s 129ms/step - loss: 0.0298 - mae: 0.1115 - val_loss: 0.0520 - val_mae: 0.1443

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

28/28 ━━━━━━━━━━━━━━━━━━━━ 30s 519ms/step

array([[0.8722664 ],
       [0.8610749 ],
       [0.8691761 ],
       [0.821877  ],
       [0.71374404],
       [0.47738907],
       [0.05807815],
       [0.0173207 ],
       [0.01323837],
       [0.02024901],
       [0.20001665],
       [0.7839481 ],
       [0.9083557 ],
       [0.83799547],
       [0.7986792 ],
       [0.86305135],
       [0.9068074 ],
       [0.98112106],
       [0.8415758 ],
       [0.8062389 ],
       [0.7197869 ],
       [0.67489254],
       [0.11282066],
       [0.01392541],
       [0.01104676],
       [0.01503696],
       [0.20246555],
       [0.8470067 ],
       [0.9547308 ],
       [0.91959274],
       [0.85805154],
       [0.87668455],
       [0.8636388 ],
       [0.8943397 ],
       [0.83794045],
       [0.7222346 ],
       [0.59073794],
       [0.34947363],
       [0.04083082],
       [0.01950001],
       [0.01458783],
       [0.02578225],
       [0.3405595 ],
       [0.84788346],
       [0.9119539 ],
       [0.92665935],
       [0.9452731 ],
       [0.91458035],
       [0.8587595 ],
       [1.0136844 ],
       [1.0027349 ],
       [0.9237186 ],
       [0.7703843 ],
       [0.53530174],
       [0.05987587],
       [0.01577917],
       [0.01177682],
       [0.02255923],
       [0.36353895],
       [0.9408258 ],
       [0.89436954],
       [0.80607855],
       [0.78428394],
       [0.7171595 ],
       [0.73887426],
       [0.52570456],
       [0.04680768],
       [0.28132835],
       [0.7073895 ],
       [0.75480855],
       [0.7275109 ],
       [0.7530958 ],
       [0.8356768 ],
       [0.8872503 ],
       [0.96937096],
       [0.97525096],
       [0.7136255 ],
       [0.5069644 ],
       [0.22538   ],
       [0.03974687],
       [0.01205982],
       [0.0113688 ],
       [0.01858712],
       [0.29105178],
       [0.6778363 ],
       [0.63249713],
       [0.06027157],
       [0.01437025],
       [0.01258772],
       [0.02014443],
       [0.3060629 ],
       [0.08429933],
       [0.01362329],
       [0.01258534],
       [0.01627348],
       [0.24470223],
       [0.64756715],
       [0.60555357],
       [0.64909434],
       [0.70164686],
       [0.75984985],
       [0.7654991 ],
       [0.7445364 ],
       [0.5765867 ],
       [0.19815929],
       [0.02330766],
       [0.01149905],
       [0.01316394],
       [0.01819209],
       [0.23278053],
       [0.6368882 ],
       [0.58531857],
       [0.61845964],
       [0.04820633],
       [0.20830815],
       [0.6250204 ],
       [0.5293232 ],
       [0.02107931],
       [0.01389582],
       [0.01895867],
       [0.22154512],
       [0.53744066],
       [0.48703507],
       [0.01980483],
       [0.01473086],
       [0.0160321 ],
       [0.24576502],
       [0.6547966 ],
       [0.61940074],
       [0.6070396 ],
       [0.6563868 ],
       [0.14897913],
       [0.01999645],
       [0.01304686],
       [0.0201544 ],
       [0.33249846],
       [0.71196747],
       [0.6566603 ],
       [0.6069745 ],
       [0.6628704 ],
       [0.67876136],
       [0.68818545],
       [0.01713892],
       [0.01408968],
       [0.01973511],
       [0.30283844],
       [0.6799343 ],
       [0.5785688 ],
       [0.5838444 ],
       [0.02096618],
       [0.01479701],
       [0.01972935],
       [0.29314652],
       [0.683756  ],
       [0.5241462 ],
       [0.60656977],
       [0.73106396],
       [0.83444273],
       [0.73197544],
       [0.15020095],
       [0.01852463],
       [0.01262528],
       [0.0209337 ],
       [0.21769263],
       [0.53739524],
       [0.5866533 ],
       [0.6976901 ],
       [0.84542763],
       [0.821734  ],
       [0.024753  ],
       [0.01668315],
       [0.01732613],
       [0.16501497],
       [0.73446035],
       [0.7687204 ],
       [0.7583945 ],
       [0.7127235 ],
       [0.30180356],
       [0.03029054],
       [0.01537363],
       [0.01618617],
       [0.02688594],
       [0.23032758],
       [0.6992599 ],
       [0.728687  ],
       [0.6732158 ],
       [0.72041875],
       [0.7454324 ],
       [0.74595344],
       [0.80646765],
       [0.73352313],
       [0.5152059 ],
       [0.25707418],
       [0.02183335],
       [0.01797735],
       [0.01511108],
       [0.0192846 ],
       [0.27532825],
       [0.69412196],
       [0.7967121 ],
       [0.82657313],
       [0.75230247],
       [0.75425696],
       [0.7329713 ],
       [0.7176037 ],
       [0.7504964 ],
       [0.7480355 ],
       [0.57709706],
       [0.3500202 ],
       [0.02782311],
       [0.01025943],
       [0.01269392],
       [0.02008129],
       [0.28650603],
       [0.55430186],
       [0.6941406 ],
       [0.6862891 ],
       [0.7634957 ],
       [0.79210854],
       [0.8456675 ],
       [0.85610634],
       [0.583521  ],
       [0.03508231],
       [0.01294002],
       [0.01152281],
       [0.01752207],
       [0.27511784],
       [0.6578407 ],
       [0.7032448 ],
       [0.8568384 ],
       [0.8326157 ],
       [0.83294123],
       [0.820559  ],
       [0.8323746 ],
       [0.88020104],
       [0.700214  ],
       [0.50190485],
       [0.2037854 ],
       [0.02221886],
       [0.01121323],
       [0.0119587 ],
       [0.01719683],
       [0.22915675],
       [0.71103674],
       [0.71374583],
       [0.7373092 ],
       [0.736467  ],
       [0.81487393],
       [0.85014135],
       [0.8559923 ],
       [0.80453837],
       [0.7433218 ],
       [0.37824175],
       [0.18225488],
       [0.0566294 ],
       [0.01590174],
       [0.01410346],
       [0.01735382],
       [0.17487429],
       [0.7593414 ],
       [0.8924216 ],
       [0.8755469 ],
       [0.8450145 ],
       [0.867649  ],
       [0.8622765 ],
       [0.88382304],
       [0.8471843 ],
       [0.6970496 ],
       [0.5245478 ],
       [0.36044744],
       [0.04389016],
       [0.01261058],
       [0.01344404],
       [0.01943527],
       [0.26426956],
       [0.754172  ],
       [0.89625704],
       [0.7790141 ],
       [0.8273738 ],
       [0.8389888 ],
       [0.853554  ],
       [0.32538936],
       [0.03046412],
       [0.01170055],
       [0.01198135],
       [0.02053807],
       [0.30132338],
       [0.7032447 ],
       [0.5999677 ],
       [0.6966425 ],
       [0.6941534 ],
       [0.65531623],
       [0.26565835],
       [0.027339  ],
       [0.01148144],
       [0.01582345],
       [0.02356914],
       [0.2954199 ],
       [0.76031446],
       [0.8284602 ],
       [0.7290605 ],
       [0.71436733],
       [0.7164633 ],
       [0.7346531 ],
       [0.39104065],
       [0.02687153],
       [0.01103717],
       [0.01317147],
       [0.02160975],
       [0.36261174],
       [0.67542684],
       [0.506789  ],
       [0.23679033],
       [0.03029906],
       [0.01204073],
       [0.0172764 ],
       [0.03041235],
       [0.27670637],
       [0.6448155 ],
       [0.56219375],
       [0.63704574],
       [0.79713356],
       [0.9036571 ],
       [0.69664705],
       [0.44363478],
       [0.10422457],
       [0.01621483],
       [0.01102776],
       [0.01452856],
       [0.0209014 ],
       [0.22704454],
       [0.29531983],
       [0.02504546],
       [0.01291977],
       [0.01425513],
       [0.0185349 ],
       [0.2499524 ],
       [0.72914654],
       [0.8577688 ],
       [0.83969986],
       [0.70989704],
       [0.74881065],
       [0.7718922 ],
       [0.7908156 ],
       [0.68779814],
       [0.5902724 ],
       [0.18250373],
       [0.01803852],
       [0.01312182],
       [0.01565186],
       [0.02487998],
       [0.28353494],
       [0.6613865 ],
       [0.68724304],
       [0.6671207 ],
       [0.0166656 ],
       [0.01532613],
       [0.01753659],
       [0.24036454],
       [0.6488023 ],
       [0.5942055 ],
       [0.03956652],
       [0.01439452],
       [0.01571104],
       [0.02319818],
       [0.3656113 ],
       [0.69902813],
       [0.65827405],
       [0.6685385 ],
       [0.6978888 ],
       [0.79991424],
       [0.7398666 ],
       [0.68677616],
       [0.7128938 ],
       [0.77288294],
       [0.5954762 ],
       [0.28342843],
       [0.0176192 ],
       [0.01475492],
       [0.0132363 ],
       [0.01947641],
       [0.2724701 ],
       [0.6870232 ],
       [0.5817815 ],
       [0.6848304 ],
       [0.7288542 ],
       [0.8483027 ],
       [0.8615519 ],
       [0.444395  ],
       [0.02955639],
       [0.01209768],
       [0.01435614],
       [0.02508932],
       [0.38463172],
       [0.61398685],
       [0.5744542 ],
       [0.7381282 ],
       [0.40007606],
       [0.03273292],
       [0.0180453 ],
       [0.01679442],
       [0.02876966],
       [0.27868596],
       [0.77855766],
       [0.82839245],
       [0.7744342 ],
       [0.6881392 ],
       [0.710888  ],
       [0.75937104],
       [0.8091854 ],
       [0.6362778 ],
       [0.39253196],
       [0.15349239],
       [0.02692433],
       [0.01460933],
       [0.01692637],
       [0.02817691],
       [0.27427614],
       [0.75516176],
       [0.6766388 ],
       [0.66600275],
       [0.6692731 ],
       [0.7299553 ],
       [0.7330215 ],
       [0.7300299 ],
       [0.62768924],
       [0.4774306 ],
       [0.2819927 ],
       [0.15028815],
       [0.02656163],
       [0.0172505 ],
       [0.01774202],
       [0.05132562],
       [0.49414492],
       [0.78173137],
       [0.8054492 ],
       [0.5976573 ],
       [0.50741863],
       [0.49953553],
       [0.4493265 ],
       [0.42388543],
       [0.4662565 ],
       [0.39111176],
       [0.23668237],
       [0.05041324],
       [0.0193523 ],
       [0.01998826],
       [0.02259338],
       [0.08188421],
       [0.48085365],
       [0.7933567 ],
       [0.75981605],
       [0.6012743 ],
       [0.5421634 ],
       [0.5339229 ],
       [0.5668814 ],
       [0.52605045],
       [0.4147704 ],
       [0.3281602 ],
       [0.1500145 ],
       [0.04481691],
       [0.02838176],
       [0.02694629],
       [0.0275606 ],
       [0.03661419],
       [0.21751408],
       [0.4821662 ],
       [0.5610855 ],
       [0.46637264],
       [0.49699524],
       [0.6026547 ],
       [0.5572016 ],
       [0.57293427],
       [0.62909114],
       [0.6250528 ],
       [0.565364  ],
       [0.09198875],
       [0.02485907],
       [0.02149886],
       [0.02080983],
       [0.05632833],
       [0.36957067],
       [0.62696505],
       [0.7038872 ],
       [0.64759207],
       [0.6896814 ],
       [0.7759882 ],
       [0.7633332 ],
       [0.71529096],
       [0.6352674 ],
       [0.5625247 ],
       [0.36486682],
       [0.18474631],
       [0.01777859],
       [0.01632327],
       [0.02283886],
       [0.04247105],
       [0.37559044],
       [0.6352767 ],
       [0.6526084 ],
       [0.65302527],
       [0.6413728 ],
       [0.5688574 ],
       [0.6711693 ],
       [0.5795531 ],
       [0.4200314 ],
       [0.38790926],
       [0.36562505],
       [0.17447291],
       [0.01680799],
       [0.01874243],
       [0.01913354],
       [0.03484403],
       [0.3470724 ],
       [0.60218894],
       [0.6502971 ],
       [0.59414786],
       [0.593303  ],
       [0.6819832 ],
       [0.523159  ],
       [0.619179  ],
       [0.6555901 ],
       [0.5090796 ],
       [0.45547256],
       [0.14609018],
       [0.04453035],
       [0.02483642],
       [0.02273859],
       [0.02742835],
       [0.20778   ],
       [0.5446099 ],
       [0.6295717 ],
       [0.7806345 ],
       [0.8138045 ],
       [0.6869914 ],
       [0.7389642 ],
       [0.76886916],
       [0.81555563],
       [0.6730051 ],
       [0.5598001 ],
       [0.16626789],
       [0.01980869],
       [0.01289888],
       [0.01412856],
       [0.0228904 ],
       [0.32087412],
       [0.5800107 ],
       [0.82982945],
       [0.8287978 ],
       [0.73327285],
       [0.69479966],
       [0.69376725],
       [0.36520264],
       [0.02865517],
       [0.0098856 ],
       [0.01445301],
       [0.01954374],
       [0.19692643],
       [0.61263144],
       [0.5791369 ],
       [0.6096724 ],
       [0.6907111 ],
       [0.724543  ],
       [0.7901239 ],
       [0.1448225 ],
       [0.01507683],
       [0.01460979],
       [0.01587784],
       [0.0665371 ],
       [0.5879761 ],
       [0.7425406 ],
       [0.7273477 ],
       [0.7867412 ],
       [0.80074954],
       [0.80714947],
       [0.82306075],
       [0.80405873],
       [0.710597  ],
       [0.5368393 ],
       [0.30761197],
       [0.0179471 ],
       [0.01251246],
       [0.01548094],
       [0.0478355 ],
       [0.33054993],
       [0.6732148 ],
       [0.71008384],
       [0.8326437 ],
       [0.8976222 ],
       [0.8877346 ],
       [0.8762336 ],
       [0.84329695],
       [0.77164894],
       [0.6868714 ],
       [0.54758   ],
       [0.32682922],
       [0.03254528],
       [0.01426292],
       [0.0150036 ],
       [0.02583618],
       [0.2579826 ],
       [0.7118258 ],
       [0.8133733 ],
       [0.75434846],
       [0.77371514],
       [0.80728155],
       [0.8248521 ],
       [0.71031785],
       [0.7273127 ],
       [0.74561566],
       [0.73593676],
       [0.3256913 ],
       [0.01795713],
       [0.01110256],
       [0.01433982],
       [0.05259516],
       [0.53002596],
       [0.8856003 ],
       [0.9410912 ],
       [0.77994204],
       [0.7014164 ],
       [0.72618675],
       [0.69612217],
       [0.6754978 ],
       [0.68933636],
       [0.64508474],
       [0.45020142],
       [0.210487  ],
       [0.02379531],
       [0.01511551],
       [0.01871287],
       [0.02713662],
       [0.2660947 ],
       [0.7572412 ],
       [0.8882715 ],
       [0.872612  ],
       [0.79820335],
       [0.86726606],
       [0.825972  ],
       [0.92067736],
       [0.8716229 ],
       [0.7169782 ],
       [0.3074409 ],
       [0.23025301],
       [0.02415983],
       [0.01622635],
       [0.02001636],
       [0.03131437],
       [0.20965438],
       [0.73331606],
       [0.8390539 ],
       [0.8252964 ],
       [0.8762544 ],
       [0.8779111 ],
       [0.8246579 ],
       [0.9104324 ],
       [0.8607741 ],
       [0.7605898 ],
       [0.6057935 ],
       [0.05431154],
       [0.0192528 ],
       [0.01581454],
       [0.01993902],
       [0.04610931],
       [0.42140052],
       [0.7763622 ],
       [0.8912394 ],
       [0.9572629 ],
       [0.83117265],
       [0.7581457 ],
       [0.7810466 ],
       [0.8136973 ],
       [0.7591015 ],
       [0.7442359 ],
       [0.28680035],
       [0.05699041],
       [0.02454997],
       [0.01984062],
       [0.02099364],
       [0.0323161 ],
       [0.23179646],
       [0.72451496],
       [0.7674227 ],
       [0.7733408 ],
       [0.931495  ],
       [0.944779  ],
       [0.9627838 ],
       [0.8964328 ],
       [0.79698145],
       [0.6197947 ],
       [0.4654795 ],
       [0.09766835],
       [0.01846136],
       [0.01307929],
       [0.01591975],
       [0.05119923],
       [0.46786484],
       [0.77875805],
       [0.8355556 ],
       [0.7427689 ],
       [0.72967106],
       [0.7242201 ],
       [0.6749664 ],
       [0.03180642],
       [0.01407269],
       [0.01370162],
       [0.02054678],
       [0.22158064],
       [0.5666778 ],
       [0.67617476],
       [0.86314416],
       [0.77236307],
       [0.7509459 ],
       [0.7772474 ],
       [0.03166316],
       [0.01324637],
       [0.01408515],
       [0.01918208],
       [0.19252153],
       [0.65285045],
       [0.77422774],
       [0.8162763 ],
       [0.66112554],
       [0.7548511 ],
       [0.713167  ],
       [0.03192812],
       [0.01436468],
       [0.01429259],
       [0.01907876],
       [0.16012146],
       [0.6084656 ],
       [0.7501068 ],
       [0.77191854],
       [0.68759656],
       [0.71712255],
       [0.7112872 ],
       [0.03322924],
       [0.01567622],
       [0.01321021],
       [0.01735616],
       [0.15323614],
       [0.6294154 ],
       [0.48887438],
       [0.5221624 ],
       [0.6228973 ],
       [0.6973838 ],
       [0.72560275],
       [0.68762183],
       [0.6752802 ],
       [0.44622606],
       [0.04346991],
       [0.01426332],
       [0.01218008],
       [0.01465548],
       [0.02007368],
       [0.22099778],
       [0.5258989 ],
       [0.40717974],
       [0.01656999],
       [0.01592837],
       [0.01747778],
       [0.18367143],
       [0.50240546],
       [0.5290779 ],
       [0.58084875],
       [0.6151019 ],
       [0.01636947],
       [0.01617099],
       [0.02148036],
       [0.24112712],
       [0.65928024],
       [0.61436665],
       [0.6871629 ],
       [0.56761557],
       [0.59283364],
       [0.6541375 ],
       [0.74148196],
       [0.72326756],
       [0.46229726],
       [0.04563805],
       [0.01589037],
       [0.0122123 ],
       [0.01428885],
       [0.02164281],
       [0.21041705],
       [0.5933521 ],
       [0.55125433],
       [0.7743632 ],
       [0.7723012 ],
       [0.76880795],
       [0.796121  ],
       [0.70265305],
       [0.69532084],
       [0.5527829 ],
       [0.3274226 ],
       [0.06408244],
       [0.02865556],
       [0.01405689],
       [0.01686898],
       [0.01553304],
       [0.07073417],
       [0.5993376 ],
       [0.7128697 ],
       [0.6786585 ],
       [0.7258255 ],
       [0.7585435 ],
       [0.7474601 ],
       [0.7508308 ],
       [0.7057008 ],
       [0.722278  ],
       [0.5500808 ],
       [0.06803986],
       [0.01635517],
       [0.01280415],
       [0.01502691],
       [0.02108822],
       [0.11499237],
       [0.54308593],
       [0.71974504],
       [0.7360928 ],
       [0.7427943 ],
       [0.7709232 ],
       [0.732309  ],
       [0.7733467 ],
       [0.7791021 ],
       [0.72188634],
       [0.47156316],
       [0.12407968],
       [0.01557634],
       [0.0119897 ],
       [0.01385235],
       [0.02221944],
       [0.3177323 ],
       [0.561505  ],
       [0.54555744],
       [0.6018485 ],
       [0.6556262 ],
       [0.71662277],
       [0.8017314 ],
       [0.7513577 ],
       [0.31255305],
       [0.02020698],
       [0.01074927],
       [0.01344369],
       [0.02029158],
       [0.26004305],
       [0.570081  ],
       [0.39181337],
       [0.4730594 ],
       [0.6153227 ],
       [0.6855295 ],
       [0.65068793],
       [0.02876948],
       [0.01478375],
       [0.01496676],
       [0.02010649],
       [0.16742025],
       [0.03633787],
       [0.01298861],
       [0.01283099],
       [0.01590663],
       [0.09675892],
       [0.5803683 ],
       [0.5163229 ],
       [0.52625144],
       [0.539246  ]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
16551,28546.0,27911.718674,25071.187461,NaN,NaN,NaN
16552,28723.0,28552.281566,25834.987615,NaN,NaN,NaN
16553,26967.0,28173.508713,26222.885304,NaN,NaN,NaN
16554,26336.0,25031.833853,23317.3981,NaN,NaN,NaN
16555,23562.0,21975.28109,23437.167632,NaN,NaN,NaN
...,...,...,...,...,...,...
18273,7356.0,5632.366084,5438.219944,3277.965576,0.000000,2902.767578
18274,17638.0,18901.861998,18263.627162,30000.000000,18738.458984,17411.048828
18275,23339.0,24148.93331,21918.767881,17159.171875,19559.654297,15489.687500
18276,26323.0,25572.670269,24646.911253,12295.125000,18438.984375,15787.542969
18278,25598.0,26338.372419,26127.13712,14554.519531,19441.283203,16177.380859

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1420.5734
RMSE: 2441.7064
R²: 0.9516
Random Forest
MAE: 1458.7094
RMSE: 2539.9484
R²: 0.9476
CTNET
MAE: 4970.8306
RMSE: 7254.2356
R²: 0.5778
Forecast
MAE: 3506.8802
RMSE: 5228.1843
R²: 0.7807
Photovoltaic
MAE: 3283.4414
RMSE: 4945.0750
R²: 0.8038

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

132/132 ━━━━━━━━━━━━━━━━━━━━ 15s 78ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

132/132 ━━━━━━━━━━━━━━━━━━━━ 13s 83ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

132/132 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
30,0.000000,23.532782,0.000000,NaN,NaN,NaN
31,0.000000,40.239559,30.457186,NaN,NaN,NaN
32,438.814997,435.553357,607.033307,NaN,NaN,NaN
33,5908.000884,9489.346757,6944.263279,NaN,NaN,NaN
34,5030.740421,8385.395332,7066.862453,NaN,NaN,NaN
...,...,...,...,...,...,...
13522,13327.000000,18687.064058,16171.792612,22546.242188,17675.566406,18765.146484
13529,26062.000000,25593.269947,25721.809674,17246.470703,16239.867188,16280.187500
13530,24231.000000,23192.748917,23637.722526,26464.271484,20261.277344,19342.685547
13531,17899.000000,16396.132314,16887.833162,24251.800781,15183.484375,15574.723633
13532,3329.000000,3321.227712,3370.844621,2308.922607,10911.980469,10926.805664

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1185.4238
RMSE: 2135.2772
R²: 0.9545
Random Forest
MAE: 503.4450
RMSE: 968.4935
R²: 0.9906
CTNET
MAE: 2137.7970
RMSE: 3847.7656
R²: 0.8519
Forecast
MAE: 3588.5238
RMSE: 5638.7994
R²: 0.6819
Photovoltaic
MAE: 3377.7980
RMSE: 5165.0556
R²: 0.7331

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Probabilidad Lluvia,Humedad Relativa,Índice UV,Condición Cielo,DPT,Hora,Cluster KMeans,...,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,6,76,0,4,15,0,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,7,81,0,4,15,1,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,7,84,0,4,15,2,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,7,86,0,4,15,3,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,7,86,0,4,15,4,Noche,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.6_Predicciones_Conjunto_lluvioso GMM.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_6_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_6_RandomForest_model.pkl")

['4_6_RandomForest_model.pkl']

In [87]:
CTNET.save("4_6_CTNET_model.keras")
Forecast_model.save("4_6_Forecast_model.keras")
Photo_model.save("4_6_Photo_model.keras")