# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion_CTNET.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,77,0,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,82,0,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,85,0,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,87,0,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,88,0,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,86,0,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,89,0,6,Soleado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,95,0,7,Soleado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,100,0,8,Soleado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,100,1,9,Soleado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,93,2,10,Soleado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,79,2,11,Soleado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,64,6,12,Nublado,Soleado
13,2022-09-01 13:00:00,25478.471342,23,51,11,13,Nublado,Soleado
14,2022-09-01 14:00:00,29057.585772,25,41,12,14,Nublado,Soleado
15,2022-09-01 15:00:00,30000.000000,26,35,11,15,Nublado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,33,8,16,Nublado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,34,5,17,Nublado,Nublado
18,2022-09-01 18:00:00,29900.303971,27,37,3,18,Nublado,Nublado
19,2022-09-01 19:00:00,18282.505369,26,41,2,19,Nublado,Nublado
20,2022-09-01 20:00:00,3411.083740,24,48,0,20,Nublado,Nublado
21,2022-09-01 21:00:00,382.187718,22,55,0,21,Soleado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,61,0,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,68,0,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster KMeans"] == "Soleado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
30,2022-09-02 06:00:00,0.000000,17,91,0,6,Soleado,Lluvioso,0.000000,0.000000
31,2022-09-02 07:00:00,0.000000,17,94,0,7,Soleado,Lluvioso,0.000000,6.584959
32,2022-09-02 08:00:00,438.814997,16,97,0,8,Soleado,Lluvioso,0.000000,560.422022
33,2022-09-02 09:00:00,5908.000884,17,93,1,9,Soleado,Lluvioso,438.814997,7720.582326
34,2022-09-02 10:00:00,5030.740421,18,85,2,10,Soleado,Lluvioso,5908.000884,9433.109309
35,2022-09-02 11:00:00,17036.043251,20,71,2,11,Soleado,Lluvioso,5030.740421,22189.147406
44,2022-09-02 20:00:00,2370.417542,24,52,0,20,Soleado,Lluvioso,11972.590689,3411.083740
45,2022-09-02 21:00:00,182.435112,22,61,0,21,Soleado,Lluvioso,2370.417542,382.187718
54,2022-09-03 06:00:00,0.000000,18,87,0,6,Soleado,Lluvioso,0.000000,0.000000
55,2022-09-03 07:00:00,13.512200,18,87,0,7,Soleado,Lluvioso,0.000000,0.000000

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
30,17,91,0,6,0.000000,0.000000
31,17,94,0,7,0.000000,6.584959
32,16,97,0,8,0.000000,560.422022
33,17,93,1,9,438.814997,7720.582326
34,18,85,2,10,5908.000884,9433.109309
...,...,...,...,...,...,...
18273,14,87,1,8,67.000000,7302.000000
18274,15,83,2,9,7356.000000,18014.000000
18275,17,71,4,10,17638.000000,23010.000000
18276,19,60,5,11,23339.000000,26156.000000
18286,20,54,0,21,0.000000,0.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
30         0.000000
31         0.000000
32       438.814997
33      5908.000884
34      5030.740421
...             ...
18273   7356.000000
18274  17638.000000
18275  23339.000000
18276  26323.000000
18286      0.000000

[5546 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 3882, y_train: 3882
X_val: 832, y_val: 832
X_test: 832, y_test: 832

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[6.53846154e-01 8.67647059e-01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.53846154e-01 9.11764706e-01 0.00000000e+00 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [6.15384615e-01 9.55882353e-01 0.00000000e+00 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [4.61538462e-01 6.47058824e-01 2.85714286e-01 2.66666667e-01
  2.05400000e-01 5.44266667e-01]
 [6.15384615e-01 3.82352941e-01 2.85714286e-01 3.33333333e-01
  5.85333333e-01 6.35166667e-01]
 [3.84615385e-01 7.20588235e-01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
(3882, 6)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.653846,0.867647,0.000000,0.000000,0.000000,0.000000
31,0.653846,0.911765,0.000000,0.066667,0.000000,0.000219
32,0.615385,0.955882,0.000000,0.133333,0.000000,0.018681
33,0.653846,0.897059,0.142857,0.200000,0.014627,0.257353
34,0.692308,0.779412,0.285714,0.266667,0.196933,0.314437
...,...,...,...,...,...,...
12201,0.269231,0.985294,0.000000,0.133333,0.000000,0.000867
12202,0.346154,0.852941,0.142857,0.200000,0.002433,0.050100
12203,0.461538,0.647059,0.285714,0.266667,0.205400,0.544267
12204,0.615385,0.382353,0.285714,0.333333,0.585333,0.635167
12223,0.384615,0.720588,0.000000,0.000000,0.000000,0.000000

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.38461538 0.76470588 0.         0.06666667 0.         0.        ]
 [0.30769231 0.86764706 0.         0.13333333 0.         0.00243333]
 [0.38461538 0.75       0.14285714 0.2        0.00126667 0.2054    ]
 ...
 [0.76923077 0.64705882 0.57142857 0.26666667 0.82916667 0.91103333]
 [0.92307692 0.38235294 0.14285714 0.86666667 0.6946     0.19466667]
 [0.88461538 0.45588235 0.         0.93333333 0.36236667 0.0164    ]]
(832, 6)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
12224,0.384615,0.764706,0.000000,0.066667,0.000000,0.000000
12225,0.307692,0.867647,0.000000,0.133333,0.000000,0.002433
12226,0.384615,0.750000,0.142857,0.200000,0.001267,0.205400
12227,0.500000,0.558824,0.142857,0.266667,0.083400,0.585333
12228,0.615385,0.352941,0.285714,0.333333,0.585333,0.635167
...,...,...,...,...,...,...
15897,0.692308,0.867647,0.285714,0.133333,0.077467,0.516633
15898,0.730769,0.779412,0.428571,0.200000,0.517867,0.824900
15899,0.769231,0.647059,0.571429,0.266667,0.829167,0.911033
15908,0.923077,0.382353,0.142857,0.866667,0.694600,0.194667
15909,0.884615,0.455882,0.000000,0.933333,0.362367,0.016400

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.84615385 0.57352941 0.         1.         0.04526667 0.        ]
 [0.65384615 0.92647059 0.         0.         0.         0.        ]
 [0.61538462 1.         0.         0.06666667 0.         0.07746667]
 ...
 [0.65384615 0.57352941 0.57142857 0.26666667 0.58793333 0.767     ]
 [0.73076923 0.41176471 0.71428571 0.33333333 0.77796667 0.87186667]
 [0.76923077 0.32352941 0.         1.         0.         0.        ]]
(832, 6)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
15910,0.846154,0.573529,0.000000,1.000000,0.045267,0.000000
15919,0.653846,0.926471,0.000000,0.000000,0.000000,0.000000
15920,0.615385,1.000000,0.000000,0.066667,0.000000,0.077467
15921,0.653846,0.882353,0.285714,0.133333,0.077467,0.517867
15922,0.692308,0.779412,0.428571,0.200000,0.546133,0.829167
...,...,...,...,...,...,...
18273,0.538462,0.808824,0.142857,0.133333,0.002233,0.243400
18274,0.576923,0.750000,0.285714,0.200000,0.245200,0.600467
18275,0.653846,0.573529,0.571429,0.266667,0.587933,0.767000
18276,0.730769,0.411765,0.714286,0.333333,0.777967,0.871867
18286,0.769231,0.323529,0.000000,1.000000,0.000000,0.000000

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[6.53846154e-01 8.75000000e-01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.53846154e-01 9.16666667e-01 0.00000000e+00 6.66666667e-02
  0.00000000e+00 2.19498623e-04]
 [6.15384615e-01 9.58333333e-01 0.00000000e+00 1.33333333e-01
  0.00000000e+00 1.86807341e-02]
 ...
 [6.53846154e-01 5.97222222e-01 4.44444444e-01 2.66666667e-01
  5.87933333e-01 7.67000000e-01]
 [7.30769231e-01 4.44444444e-01 5.55555556e-01 3.33333333e-01
  7.77966667e-01 8.71866667e-01]
 [7.69230769e-01 3.61111111e-01 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00]]
(5546, 6)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
30,0.653846,0.875000,0.000000,0.000000,0.000000,0.000000
31,0.653846,0.916667,0.000000,0.066667,0.000000,0.000219
32,0.615385,0.958333,0.000000,0.133333,0.000000,0.018681
33,0.653846,0.902778,0.111111,0.200000,0.014627,0.257353
34,0.692308,0.791667,0.222222,0.266667,0.196933,0.314437
...,...,...,...,...,...,...
18273,0.538462,0.819444,0.111111,0.133333,0.002233,0.243400
18274,0.576923,0.763889,0.222222,0.200000,0.245200,0.600467
18275,0.653846,0.597222,0.444444,0.266667,0.587933,0.767000
18276,0.730769,0.444444,0.555556,0.333333,0.777967,0.871867
18286,0.769231,0.361111,0.000000,1.000000,0.000000,0.000000

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.58533333]
 [0.63516667]
 [0.        ]]
(3882, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
12201    0.002433
12202    0.205400
12203    0.585333
12204    0.635167
12223    0.000000

[3882 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[0.00000000e+00]
 [1.26666667e-03]
 [8.34000000e-02]
 [5.85333333e-01]
 [6.35166667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.73333333e-03]
 [2.54233333e-01]
 [7.31700000e-01]
 [7.93966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.70000000e-03]
 [2.57933333e-01]
 [7.31700000e-01]
 [7.93966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.73333333e-03]
 [2.60933333e-01]
 [7.31700000e-01]
 [1.25666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.73333333e-03]
 [2.60933333e-01]
 [7.31700000e-01]
 [7.87500000e-01]
 [7.60266667e-01]
 [7.31966667e-01]
 [7.01566667e-01]
 [7.05666667e-01]
 [2.96100000e-01]
 [1.41666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.10000000e-03]
 [8.35000000e-02]
 [5.85333333e-01]
 [6.27833333e-01]
 [6.08200000e-01]
 [1.13333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.46666667e-03]
 [8.35000000e-02]
 [5.85333333e-01]
 [6.33433333e-01]
 [6.08200000e-01]
 [5.84733333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.43333333e-03]
 [2.08333333e-01]
 [4.59333333e-01]
 [4.56033333e-01]
 [5.32166667e-01]
 [5.03666667e-01]
 [2.29833333e-01]
 [6.80000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.49333333e-02]
 [3.67066667e-01]
 [7.89233333e-01]
 [8.34700000e-01]
 [8.20833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.59200000e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93000000e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.39000000e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.06333333e-02]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93000000e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.53666667e-02]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.27666667e-02]
 [2.93633333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.31000000e-02]
 [2.93633333e-01]
 [6.39600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.27000000e-02]
 [2.96900000e-01]
 [6.31400000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.67666667e-02]
 [3.74833333e-01]
 [7.89233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.77000000e-02]
 [3.67066667e-01]
 [7.94100000e-01]
 [4.70333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.64333333e-02]
 [1.17466667e-01]
 [2.52566667e-01]
 [7.51400000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.06666667e-03]
 [1.17466667e-01]
 [6.42700000e-01]
 [6.69633333e-01]
 [6.62066667e-01]
 [4.13333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.11000000e-02]
 [2.20233333e-01]
 [4.73533333e-01]
 [5.09166667e-01]
 [3.94000000e-01]
 [3.81600000e-01]
 [3.32433333e-01]
 [4.17000000e-02]
 [3.90000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.90000000e-03]
 [4.40333333e-02]
 [3.31466667e-01]
 [3.50566667e-01]
 [3.44766667e-01]
 [3.38200000e-01]
 [3.41566667e-01]
 [3.37933333e-01]
 [2.48566667e-01]
 [2.47233333e-01]
 [2.10800000e-01]
 [1.41666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.58666667e-02]
 [3.67066667e-01]
 [7.89233333e-01]
 [8.43733333e-01]
 [8.29000000e-01]
 [7.19133333e-01]
 [7.05566667e-01]
 [7.94833333e-01]
 [7.04333333e-01]
 [7.02000000e-01]
 [4.13800000e-01]
 [4.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.67666667e-02]
 [3.67066667e-01]
 [7.89233333e-01]
 [8.43566667e-01]
 [8.32566667e-01]
 [7.96666667e-01]
 [7.84200000e-01]
 [4.53000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.77000000e-02]
 [3.67066667e-01]
 [7.89233333e-01]
 [8.47333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.78666667e-02]
 [3.81333333e-01]
 [7.91266667e-01]
 [8.30366667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.81333333e-02]
 [3.79500000e-01]
 [7.89233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.70000000e-03]
 [3.30366667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.96666667e-03]
 [3.62200000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.83333333e-03]
 [3.15933333e-01]
 [6.50666667e-01]
 [6.78866667e-01]
 [6.56666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.17000000e-02]
 [4.02500000e-01]
 [8.22733333e-01]
 [8.54800000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.70333333e-02]
 [3.21866667e-01]
 [6.61933333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [3.76966667e-01]
 [7.10300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.47000000e-02]
 [3.94633333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.57333333e-02]
 [4.93300000e-01]
 [8.19466667e-01]
 [8.34700000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.32000000e-02]
 [5.93533333e-01]
 [6.08633333e-01]
 [8.79666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32066667e-01]
 [2.87266667e-01]
 [8.49266667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.34133333e-01]
 [2.64400000e-01]
 [7.96266667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.64700000e-01]
 [8.31333333e-01]
 [0.00000000e+00]
 [7.62666667e-02]
 [5.93533333e-01]
 [6.20733333e-01]
 [0.00000000e+00]
 [2.69333333e-02]
 [4.75066667e-01]
 [5.05100000e-01]
 [7.07666667e-01]
 [7.24233333e-01]
 [0.00000000e+00]
 [5.85666667e-02]
 [4.76400000e-01]
 [4.86900000e-01]
 [7.03733333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.94666667e-02]
 [0.00000000e+00]
 [2.79000000e-02]
 [5.37166667e-01]
 [5.50066667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.35333333e-02]
 [1.42433333e-01]
 [1.70400000e-01]
 [6.15766667e-01]
 [6.26766667e-01]
 [6.28100000e-01]
 [6.09866667e-01]
 [9.53333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.99333333e-02]
 [4.15466667e-01]
 [4.86900000e-01]
 [7.03733333e-01]
 [7.21466667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.68666667e-02]
 [3.79866667e-01]
 [4.05700000e-01]
 [8.21466667e-01]
 [0.00000000e+00]
 [7.32000000e-02]
 [6.09333333e-01]
 [6.15400000e-01]
 [8.79666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.02733333e-01]
 [7.33566667e-01]
 [0.00000000e+00]
 [7.32000000e-02]
 [5.95633333e-01]
 [6.29866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.74833333e-01]
 [5.50866667e-01]
 [0.00000000e+00]
 [4.33333333e-04]
 [5.93533333e-01]
 [6.12933333e-01]
 [8.81366667e-01]
 [0.00000000e+00]
 [3.00000000e-04]
 [4.15466667e-01]
 [4.44233333e-01]
 [6.21133333e-01]
 [1.10966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.66666667e-05]
 [1.89933333e-01]
 [6.10200000e-01]
 [7.91700000e-01]
 [8.05833333e-01]
 [7.12233333e-01]
 [7.70233333e-01]
 [4.56866667e-01]
 [1.07900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.56133333e-01]
 [4.50066667e-01]
 [6.51266667e-01]
 [0.00000000e+00]
 [1.00000000e-04]
 [5.93533333e-01]
 [6.65166667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.93533333e-01]
 [7.69300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.93533333e-01]
 [7.63766667e-01]
 [9.33933333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.74833333e-01]
 [6.28000000e-01]
 [7.55433333e-01]
 [0.00000000e+00]
 [6.66666667e-05]
 [5.93533333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.93533333e-01]
 [0.00000000e+00]
 [6.66666667e-05]
 [5.93533333e-01]
 [6.18800000e-01]
 [8.85000000e-01]
 [8.95366667e-01]
 [1.12600000e-01]
 [1.33333333e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.00000000e-04]
 [5.93533333e-01]
 [6.08633333e-01]
 [8.82166667e-01]
 [0.00000000e+00]
 [8.66666667e-04]
 [5.93533333e-01]
 [6.33333333e-01]
 [0.00000000e+00]
 [7.00000000e-04]
 [4.74833333e-01]
 [0.00000000e+00]
 [1.06333333e-02]
 [3.49533333e-01]
 [0.00000000e+00]
 [1.33000000e-02]
 [3.42366667e-01]
 [8.38633333e-01]
 [0.00000000e+00]
 [1.56333333e-02]
 [3.52166667e-01]
 [8.19466667e-01]
 [9.29666667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.33000000e-02]
 [3.42366667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [0.00000000e+00]
 [4.30000000e-02]
 [3.94133333e-01]
 [8.48233333e-01]
 [9.72966667e-01]
 [0.00000000e+00]
 [1.32333333e-02]
 [2.79033333e-01]
 [6.55566667e-01]
 [0.00000000e+00]
 [1.43000000e-02]
 [2.74900000e-01]
 [0.00000000e+00]
 [1.65666667e-02]
 [2.79866667e-01]
 [6.67100000e-01]
 [0.00000000e+00]
 [1.34666667e-02]
 [0.00000000e+00]
 [1.81666667e-02]
 [0.00000000e+00]
 [1.35666667e-02]
 [3.43266667e-01]
 [8.19466667e-01]
 [0.00000000e+00]
 [1.06333333e-02]
 [2.73866667e-01]
 [6.71400000e-01]
 [0.00000000e+00]
 [1.38333333e-02]
 [3.42366667e-01]
 [8.19466667e-01]
 [9.25600000e-01]
 [0.00000000e+00]
 [1.19666667e-02]
 [2.73866667e-01]
 [6.63866667e-01]
 [7.43800000e-01]
 [0.00000000e+00]
 [1.19666667e-02]
 [3.10300000e-01]
 [7.40766667e-01]
 [9.27233333e-01]
 [0.00000000e+00]
 [1.34333333e-02]
 [2.91733333e-01]
 [7.18000000e-01]
 [0.00000000e+00]
 [1.95000000e-02]
 [3.10700000e-01]
 [7.17966667e-01]
 [0.00000000e+00]
 [2.01000000e-02]
 [3.54100000e-01]
 [7.96900000e-01]
 [8.68333333e-01]
 [0.00000000e+00]
 [2.94666667e-02]
 [4.08833333e-01]
 [9.03766667e-01]
 [9.83200000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79333333e-02]
 [3.94066667e-01]
 [8.85433333e-01]
 [9.61066667e-01]
 [0.00000000e+00]
 [2.89000000e-02]
 [4.12033333e-01]
 [8.97266667e-01]
 [4.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38000000e-02]
 [2.01066667e-01]
 [4.30800000e-01]
 [4.64833333e-01]
 [4.58433333e-01]
 [9.01433333e-01]
 [7.74700000e-01]
 [2.56866667e-01]
 [5.13333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.10666667e-02]
 [4.37533333e-01]
 [8.85433333e-01]
 [9.58300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.64000000e-02]
 [3.85233333e-01]
 [8.97466667e-01]
 [9.74766667e-01]
 [0.00000000e+00]
 [2.15666667e-02]
 [3.83966667e-01]
 [1.00000000e+00]
 [9.84066667e-01]
 [0.00000000e+00]
 [2.30666667e-02]
 [2.81900000e-01]
 [5.97866667e-01]
 [0.00000000e+00]
 [3.00666667e-02]
 [0.00000000e+00]
 [3.46000000e-02]
 [4.65733333e-01]
 [8.82200000e-01]
 [9.89600000e-01]
 [0.00000000e+00]
 [4.58333333e-02]
 [4.38600000e-01]
 [8.90033333e-01]
 [9.74766667e-01]
 [0.00000000e+00]
 [5.05666667e-02]
 [4.22800000e-01]
 [7.70600000e-01]
 [0.00000000e+00]
 [4.49666667e-02]
 [0.00000000e+00]
 [6.27333333e-02]
 [4.69800000e-01]
 [0.00000000e+00]
 [4.67666667e-02]
 [3.91000000e-01]
 [6.52300000e-01]
 [0.00000000e+00]
 [5.62000000e-02]
 [3.79400000e-01]
 [6.52300000e-01]
 [0.00000000e+00]
 [4.92333333e-02]
 [3.97033333e-01]
 [6.63266667e-01]
 [0.00000000e+00]
 [3.93333333e-02]
 [3.28866667e-01]
 [0.00000000e+00]
 [4.39333333e-02]
 [0.00000000e+00]
 [5.05666667e-02]
 [4.22800000e-01]
 [0.00000000e+00]
 [5.62000000e-02]
 [4.92866667e-01]
 [0.00000000e+00]
 [4.87666667e-02]
 [4.49533333e-01]
 [7.76633333e-01]
 [0.00000000e+00]
 [5.74666667e-02]
 [0.00000000e+00]
 [5.62000000e-02]
 [4.69900000e-01]
 [0.00000000e+00]
 [5.84000000e-02]
 [4.83633333e-01]
 [8.53433333e-01]
 [9.02733333e-01]
 [0.00000000e+00]
 [4.55333333e-02]
 [4.11600000e-01]
 [0.00000000e+00]
 [5.69333333e-02]
 [4.74933333e-01]
 [8.19733333e-01]
 [0.00000000e+00]
 [5.70000000e-02]
 [4.95533333e-01]
 [8.28300000e-01]
 [9.11866667e-01]
 [0.00000000e+00]
 [5.74000000e-02]
 [5.01233333e-01]
 [8.22900000e-01]
 [0.00000000e+00]
 [7.07333333e-02]
 [4.56866667e-01]
 [6.93166667e-01]
 [0.00000000e+00]
 [8.79000000e-02]
 [4.69800000e-01]
 [8.30000000e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [4.69800000e-01]
 [8.15366667e-01]
 [0.00000000e+00]
 [8.82333333e-02]
 [4.69800000e-01]
 [8.30000000e-01]
 [0.00000000e+00]
 [6.09333333e-02]
 [4.88033333e-01]
 [8.48166667e-01]
 [0.00000000e+00]
 [5.83333333e-02]
 [4.95000000e-01]
 [8.62800000e-01]
 [0.00000000e+00]
 [6.44000000e-02]
 [5.02466667e-01]
 [8.75933333e-01]
 [0.00000000e+00]
 [9.01000000e-02]
 [4.69800000e-01]
 [0.00000000e+00]
 [7.13000000e-02]
 [4.96666667e-01]
 [8.77200000e-01]
 [0.00000000e+00]
 [7.08666667e-02]
 [5.71066667e-01]
 [8.96300000e-01]
 [0.00000000e+00]
 [7.96333333e-02]
 [5.60133333e-01]
 [8.67366667e-01]
 [0.00000000e+00]
 [9.16333333e-02]
 [5.66833333e-01]
 [8.46533333e-01]
 [0.00000000e+00]
 [6.44000000e-02]
 [4.25033333e-01]
 [6.58966667e-01]
 [0.00000000e+00]
 [1.05133333e-01]
 [5.73300000e-01]
 [0.00000000e+00]
 [9.30000000e-02]
 [5.36466667e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.16633333e-01]
 [0.00000000e+00]
 [8.51000000e-02]
 [5.16633333e-01]
 [0.00000000e+00]
 [1.02566667e-01]
 [5.16633333e-01]
 [8.27433333e-01]
 [0.00000000e+00]
 [6.62666667e-02]
 [4.55633333e-01]
 [7.05200000e-01]
 [0.00000000e+00]
 [8.04333333e-02]
 [5.74433333e-01]
 [8.71966667e-01]
 [0.00000000e+00]
 [8.43666667e-02]
 [5.65000000e-01]
 [8.78500000e-01]
 [0.00000000e+00]
 [9.46333333e-02]
 [5.86000000e-01]
 [8.67033333e-01]
 [9.37566667e-01]
 [0.00000000e+00]
 [9.71000000e-02]
 [5.83100000e-01]
 [8.47733333e-01]
 [0.00000000e+00]
 [9.38000000e-02]
 [5.64833333e-01]
 [8.47533333e-01]
 [0.00000000e+00]
 [7.76333333e-02]
 [5.28933333e-01]
 [7.46966667e-01]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.21533333e-01]
 [8.23700000e-01]
 [9.15200000e-01]
 [0.00000000e+00]
 [7.79333333e-02]
 [5.26466667e-01]
 [8.24766667e-01]
 [0.00000000e+00]
 [7.81000000e-02]
 [5.28400000e-01]
 [8.30066667e-01]
 [0.00000000e+00]
 [8.09666667e-02]
 [5.16633333e-01]
 [8.23700000e-01]
 [0.00000000e+00]
 [8.12666667e-02]
 [5.11733333e-01]
 [8.20866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.33333333e-03]
 [4.65666667e-02]
 [7.42000000e-02]
 [8.20000000e-02]
 [8.50000000e-02]
 [8.47666667e-02]
 [8.45333333e-02]
 [8.44333333e-02]
 [8.40333333e-02]
 [9.64666667e-02]
 [7.80000000e-02]
 [6.91000000e-02]
 [1.18933333e-01]
 [1.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.42333333e-02]
 [4.01966667e-01]
 [5.76600000e-01]
 [6.37700000e-01]
 [7.58100000e-01]
 [8.66766667e-01]
 [7.66066667e-01]
 [3.96400000e-01]
 [3.34666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.93666667e-02]
 [5.16633333e-01]
 [8.24633333e-01]
 [5.73933333e-01]
 [5.94400000e-01]
 [5.94600000e-01]
 [9.12000000e-01]
 [8.67033333e-01]
 [7.66066667e-01]
 [3.58066667e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.50000000e-02]
 [4.14800000e-01]
 [6.60433333e-01]
 [5.73933333e-01]
 [5.93733333e-01]
 [9.39700000e-01]
 [9.37200000e-01]
 [9.31833333e-01]
 [9.15333333e-01]
 [8.69733333e-01]
 [7.66066667e-01]
 [2.85400000e-01]
 [2.41000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.02333333e-02]
 [5.16633333e-01]
 [8.24900000e-01]
 [9.11033333e-01]
 [9.44466667e-01]
 [9.44500000e-01]
 [9.39266667e-01]
 [9.34466667e-01]
 [2.74366667e-01]
 [2.60033333e-01]
 [2.31266667e-01]
 [1.94666667e-01]
 [1.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.17866667e-01]
 [8.29166667e-01]
 [9.15400000e-01]
 [3.62366667e-01]
 [4.52666667e-02]]
(832, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
12224    0.000000
12225    0.001267
12226    0.083400
12227    0.585333
12228    0.635167
...           ...
15897    0.517867
15898    0.829167
15899    0.915400
15908    0.362367
15909    0.045267

[832 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.46133333e-01]
 [8.40400000e-01]
 [9.17433333e-01]
 [4.73666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.25000000e-02]
 [5.39233333e-01]
 [8.24700000e-01]
 [9.11100000e-01]
 [4.57200000e-01]
 [4.96666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.74666667e-02]
 [5.18166667e-01]
 [8.30233333e-01]
 [9.11033333e-01]
 [4.69000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.81666667e-02]
 [5.21533333e-01]
 [8.27466667e-01]
 [9.11033333e-01]
 [9.48200000e-01]
 [5.01733333e-01]
 [3.64933333e-01]
 [3.01000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.21333333e-02]
 [5.18833333e-01]
 [8.27000000e-01]
 [9.11233333e-01]
 [8.55500000e-01]
 [8.21300000e-01]
 [7.80066667e-01]
 [5.63466667e-01]
 [4.56366667e-01]
 [3.40666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.71666667e-02]
 [3.60533333e-01]
 [5.79133333e-01]
 [5.85166667e-01]
 [6.07233333e-01]
 [6.03966667e-01]
 [5.94433333e-01]
 [5.88066667e-01]
 [5.90700000e-01]
 [4.46866667e-01]
 [4.23133333e-01]
 [3.83533333e-01]
 [3.29333333e-01]
 [2.31666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.54666667e-02]
 [4.35333333e-01]
 [7.98266667e-01]
 [8.94266667e-01]
 [3.93133333e-01]
 [3.28333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.59666667e-02]
 [4.37000000e-01]
 [7.98366667e-01]
 [8.97400000e-01]
 [4.13500000e-01]
 [2.87333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [8.01333333e-01]
 [8.94866667e-01]
 [9.24766667e-01]
 [2.91333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93666667e-02]
 [3.98566667e-01]
 [8.03900000e-01]
 [8.94266667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.30333333e-02]
 [3.24500000e-01]
 [5.35133333e-01]
 [8.93433333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [8.93500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [5.15066667e-01]
 [8.49400000e-01]
 [8.86933333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.09666667e-02]
 [4.37133333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.08333333e-02]
 [2.51400000e-01]
 [4.96333333e-01]
 [5.67933333e-01]
 [6.47633333e-01]
 [6.64433333e-01]
 [2.87466667e-01]
 [1.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.64666667e-01]
 [8.06500000e-01]
 [8.96166667e-01]
 [9.25000000e-01]
 [9.24933333e-01]
 [8.27066667e-01]
 [5.66766667e-01]
 [3.28733333e-01]
 [5.51000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.87666667e-02]
 [2.30066667e-01]
 [4.55966667e-01]
 [6.44833333e-01]
 [6.65833333e-01]
 [6.64366667e-01]
 [6.62500000e-01]
 [6.60866667e-01]
 [5.76833333e-01]
 [3.14633333e-01]
 [3.01600000e-01]
 [4.34866667e-01]
 [3.04900000e-01]
 [3.72000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40333333e-02]
 [1.79900000e-01]
 [4.45933333e-01]
 [3.23633333e-01]
 [3.47666667e-01]
 [1.97800000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.68333333e-02]
 [1.82600000e-01]
 [3.02933333e-01]
 [3.23700000e-01]
 [1.59200000e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.73666667e-02]
 [4.98800000e-01]
 [8.45100000e-01]
 [8.95933333e-01]
 [1.49000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.14000000e-02]
 [2.26800000e-01]
 [3.50033333e-01]
 [4.38233333e-01]
 [2.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79666667e-02]
 [2.78633333e-01]
 [4.04633333e-01]
 [3.82500000e-01]
 [4.55600000e-01]
 [2.66166667e-01]
 [2.36933333e-01]
 [2.46166667e-01]
 [2.48333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20333333e-02]
 [2.95566667e-01]
 [4.52433333e-01]
 [5.00800000e-01]
 [2.80133333e-01]
 [2.70033333e-01]
 [4.37733333e-01]
 [2.42166667e-01]
 [2.97333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.84000000e-02]
 [2.61400000e-01]
 [5.28433333e-01]
 [5.05033333e-01]
 [3.90766667e-01]
 [4.55000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.93000000e-02]
 [3.93100000e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [4.66000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.00500000e-01]
 [3.56300000e-01]
 [3.35333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.96833333e-01]
 [3.59033333e-01]
 [3.83666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [9.33400000e-01]
 [1.65566667e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.93000000e-02]
 [1.40800000e-01]
 [2.47800000e-01]
 [3.81700000e-01]
 [7.75366667e-01]
 [1.92633333e-01]
 [1.78666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.38333333e-02]
 [4.69166667e-01]
 [8.33500000e-01]
 [8.16000000e-01]
 [6.67466667e-01]
 [8.15333333e-01]
 [4.41033333e-01]
 [4.64000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [9.23966667e-01]
 [9.25500000e-01]
 [9.15766667e-01]
 [9.10633333e-01]
 [8.99166667e-01]
 [8.67500000e-01]
 [7.71733333e-01]
 [3.93133333e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43333333e-02]
 [4.39333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.24766667e-01]
 [8.61733333e-01]
 [7.70200000e-01]
 [4.02500000e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.49000000e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [9.31433333e-01]
 [9.00833333e-01]
 [8.61766667e-01]
 [7.73533333e-01]
 [3.93266667e-01]
 [3.19000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.58666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [7.16600000e-01]
 [2.55333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.35333333e-01]
 [7.95400000e-01]
 [8.97400000e-01]
 [9.73900000e-01]
 [3.61466667e-01]
 [2.55333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.36666667e-02]
 [4.38900000e-01]
 [7.95400000e-01]
 [8.94266667e-01]
 [3.53000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.11666667e-02]
 [4.08566667e-01]
 [7.90500000e-01]
 [9.00666667e-01]
 [2.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.01333333e-02]
 [2.97733333e-01]
 [7.97666667e-01]
 [8.92133333e-01]
 [2.11666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.68666667e-02]
 [4.04933333e-01]
 [7.88133333e-01]
 [8.82633333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.79000000e-02]
 [3.97200000e-01]
 [7.90900000e-01]
 [8.86833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.82000000e-02]
 [4.01833333e-01]
 [7.97833333e-01]
 [8.87600000e-01]
 [2.35333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.41666667e-02]
 [3.93333333e-01]
 [8.23766667e-01]
 [9.00666667e-01]
 [0.00000000e+00]
 [2.08000000e-02]
 [3.21433333e-01]
 [7.44300000e-01]
 [8.14833333e-01]
 [0.00000000e+00]
 [2.10000000e-02]
 [3.20100000e-01]
 [6.98633333e-01]
 [7.97200000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20666667e-02]
 [3.70033333e-01]
 [7.77866667e-01]
 [8.81166667e-01]
 [1.45000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.40666667e-02]
 [3.77433333e-01]
 [7.84366667e-01]
 [8.82066667e-01]
 [6.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.28000000e-02]
 [3.40100000e-01]
 [7.78033333e-01]
 [8.86700000e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.38000000e-02]
 [3.74066667e-01]
 [7.80300000e-01]
 [8.81166667e-01]
 [2.28866667e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.06666667e-02]
 [2.83600000e-01]
 [6.43000000e-01]
 [7.04933333e-01]
 [7.41166667e-01]
 [2.54600000e-01]
 [1.52666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.38166667e-01]
 [7.77400000e-01]
 [8.85766667e-01]
 [7.50000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.99333333e-02]
 [3.41533333e-01]
 [7.73633333e-01]
 [9.07933333e-01]
 [9.37200000e-01]
 [3.37800000e-01]
 [5.93333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.63333333e-01]
 [7.73633333e-01]
 [8.95666667e-01]
 [2.85466667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74333333e-02]
 [3.84800000e-01]
 [8.13333333e-01]
 [9.17600000e-01]
 [9.38200000e-01]
 [2.71400000e-01]
 [9.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.74000000e-02]
 [3.83966667e-01]
 [8.16733333e-01]
 [9.14666667e-01]
 [9.40133333e-01]
 [8.63333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.84333333e-02]
 [3.84966667e-01]
 [8.08000000e-01]
 [7.33100000e-01]
 [7.46000000e-01]
 [6.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.14333333e-02]
 [2.73366667e-01]
 [6.37833333e-01]
 [7.21900000e-01]
 [7.56166667e-01]
 [9.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.46000000e-02]
 [2.85633333e-01]
 [9.27366667e-01]
 [9.50000000e-01]
 [7.76666667e-02]
 [4.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.52000000e-02]
 [2.73033333e-01]
 [9.27566667e-01]
 [9.96500000e-01]
 [5.33333333e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.46566667e-01]
 [7.90066667e-01]
 [8.84333333e-01]
 [7.53333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.98300000e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [4.73333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.99666667e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [4.06533333e-01]
 [8.33866667e-01]
 [8.81166667e-01]
 [7.83333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.39333333e-02]
 [3.30833333e-01]
 [7.73633333e-01]
 [8.81166667e-01]
 [5.03333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.44333333e-02]
 [3.70966667e-01]
 [8.09266667e-01]
 [9.07600000e-01]
 [5.33333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.35200000e-01]
 [7.74566667e-01]
 [8.81166667e-01]
 [6.96666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.38666667e-02]
 [2.64666667e-01]
 [6.18900000e-01]
 [7.96200000e-01]
 [4.26666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.32666667e-02]
 [3.30833333e-01]
 [6.96266667e-01]
 [7.06233333e-01]
 [3.13033333e-01]
 [1.28166667e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [1.78433333e-01]
 [3.79433333e-01]
 [3.75233333e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.00000000e-04]
 [2.86666667e-02]
 [6.97000000e-02]
 [8.04000000e-02]
 [1.67666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.26666667e-03]
 [9.30666667e-02]
 [3.39300000e-01]
 [3.83733333e-01]
 [5.11933333e-01]
 [4.20900000e-01]
 [3.76766667e-01]
 [6.52000000e-02]
 [1.00000000e-04]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.30000000e-03]
 [1.54933333e-01]
 [3.28166667e-01]
 [5.02700000e-01]
 [5.86100000e-01]
 [6.03000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.13333333e-03]
 [1.88500000e-01]
 [6.96900000e-01]
 [5.36066667e-01]
 [2.66866667e-01]
 [4.77433333e-01]
 [6.67000000e-02]
 [5.01333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.96666667e-03]
 [1.77100000e-01]
 [3.93700000e-01]
 [5.02500000e-01]
 [3.48500000e-01]
 [8.61333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [5.00333333e-01]
 [1.37500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.36666667e-03]
 [2.95566667e-01]
 [7.76066667e-01]
 [8.06100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98800000e-01]
 [7.79066667e-01]
 [8.98533333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.70000000e-03]
 [3.06733333e-01]
 [8.07833333e-01]
 [9.19166667e-01]
 [9.24300000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.73333333e-03]
 [2.98633333e-01]
 [7.87133333e-01]
 [8.93433333e-01]
 [6.48733333e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.94566667e-01]
 [7.76166667e-01]
 [8.93433333e-01]
 [9.13266667e-01]
 [9.01833333e-01]
 [8.97766667e-01]
 [8.44533333e-01]
 [6.39566667e-01]
 [1.30100000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.86666667e-03]
 [2.35633333e-01]
 [6.19466667e-01]
 [7.35333333e-01]
 [7.29766667e-01]
 [3.49433333e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.80000000e-03]
 [2.94566667e-01]
 [7.83200000e-01]
 [8.97600000e-01]
 [9.12233333e-01]
 [9.00266667e-01]
 [6.07633333e-01]
 [3.05733333e-01]
 [5.46333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.63333333e-03]
 [2.15000000e-01]
 [7.74333333e-01]
 [8.93433333e-01]
 [9.12233333e-01]
 [2.62066667e-01]
 [7.28666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.93333333e-03]
 [2.88766667e-01]
 [7.75733333e-01]
 [6.45166667e-01]
 [6.57400000e-01]
 [4.78266667e-01]
 [3.27833333e-01]
 [9.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.70000000e-03]
 [2.50900000e-01]
 [7.80300000e-01]
 [9.22300000e-01]
 [9.05033333e-01]
 [5.14600000e-01]
 [5.67000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.60000000e-03]
 [2.60266667e-01]
 [8.07900000e-01]
 [9.17700000e-01]
 [9.27500000e-01]
 [9.09000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.70000000e-03]
 [2.93166667e-01]
 [8.13733333e-01]
 [9.19500000e-01]
 [9.26933333e-01]
 [8.21333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.26666667e-03]
 [2.75633333e-01]
 [7.94333333e-01]
 [9.03866667e-01]
 [9.07400000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.51233333e-01]
 [7.08300000e-01]
 [8.33333333e-01]
 [9.10633333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.46666667e-03]
 [2.53400000e-01]
 [7.06433333e-01]
 [8.33366667e-01]
 [6.07000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.63333333e-03]
 [2.55600000e-01]
 [7.08300000e-01]
 [8.30633333e-01]
 [7.19333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.62266667e-01]
 [7.08300000e-01]
 [8.30033333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.32966667e-01]
 [5.81266667e-01]
 [7.39900000e-01]
 [8.51400000e-01]
 [5.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [4.43333333e-03]
 [2.47100000e-01]
 [5.77166667e-01]
 [7.70533333e-01]
 [5.55666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.56666667e-03]
 [2.38433333e-01]
 [5.76833333e-01]
 [7.49866667e-01]
 [8.57533333e-01]
 [4.17800000e-01]
 [4.33666667e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.43333333e-03]
 [1.98000000e-01]
 [5.41133333e-01]
 [6.99333333e-01]
 [8.47766667e-01]
 [4.14000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.20000000e-03]
 [2.35666667e-01]
 [5.97333333e-01]
 [7.50633333e-01]
 [8.56600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.36666667e-03]
 [2.41600000e-01]
 [5.94133333e-01]
 [7.69900000e-01]
 [8.71333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.36666667e-03]
 [2.43400000e-01]
 [6.00466667e-01]
 [7.67000000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [2.23333333e-03]
 [2.45200000e-01]
 [5.87933333e-01]
 [7.77966667e-01]
 [8.77433333e-01]
 [0.00000000e+00]]
(832, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
15910    0.000000
15919    0.000000
15920    0.077467
15921    0.546133
15922    0.840400
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18286    0.000000

[832 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.        ]
 [0.        ]
 [0.01462717]
 ...
 [0.77796667]
 [0.87743333]
 [0.        ]]
(5546, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
30       0.000000
31       0.000000
32       0.014627
33       0.196933
34       0.167691
...           ...
18273    0.245200
18274    0.587933
18275    0.777967
18276    0.877433
18286    0.000000

[5546 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.249167 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 628
[LightGBM] [Info] Number of data points in the train set: 3882, number of used features: 6
[LightGBM] [Info] Start training from score 0.263711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
15910           0.0
15919     45.085922
15920   1747.559524
15921  15282.644011
15922  24396.229156
...             ...
18273   6918.407231
18274  19779.365821
18275  24030.007366
18276  24112.268947
18286           0.0

[832 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
15910         0.0
15919         0.0
15920      2324.0
15921     16384.0
15922     25212.0
...           ...
18273      7356.0
18274     17638.0
18275     23339.0
18276     26323.0
18286         0.0

[832 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
15910         0.0           0.0
15919         0.0     45.085922
15920      2324.0   1747.559524
15921     16384.0  15282.644011
15922     25212.0  24396.229156
...           ...           ...
18273      7356.0   6918.407231
18274     17638.0  19779.365821
18275     23339.0  24030.007366
18276     26323.0  24112.268947
18286         0.0           0.0

[832 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1106.0083
RMSE: 2067.4017
R²: 0.9606

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
15910         0.0           0.0           0.0
15919         0.0     45.085922           0.0
15920      2324.0   1747.559524   2931.155236
15921     16384.0  15282.644011  15534.328419
15922     25212.0  24396.229156  25499.346937
...           ...           ...           ...
18273      7356.0   6918.407231   7148.104256
18274     17638.0  19779.365821  21016.223316
18275     23339.0  24030.007366  23687.023299
18276     26323.0  24112.268947  23126.102053
18286         0.0           0.0           0.0

[832 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (3834, 48, 6), y_train: (3834, 1)
X_val: (784, 48, 6), y_val: (784, 1)
X_test: (784, 48, 6), y_test: (784, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 126s 3s/step - loss: 0.1729 - mean_absolute_error: 0.2624 - mean_absolute_percentage_error: 847536.5000 - root_mean_squared_error: 0.4158 - val_loss: 0.1487 - val_mean_absolute_error: 0.2609 - val_mean_absolute_percentage_error: 4711125.5000 - val_root_mean_squared_error: 0.3856
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.1646 - mean_absolute_error: 0.2578 - mean_absolute_percentage_error: 4997073.0000 - root_mean_squared_error: 0.4058 - val_loss: 0.1412 - val_mean_absolute_error: 0.2593 - val_mean_absolute_percentage_error: 10487931.0000 - val_root_mean_squared_error: 0.3757
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.1594 - mean_absolute_error: 0.2575 - mean_absolute_percentage_error: 10245430.0000 - root_mean_squared_error: 0.3993 - val_loss: 0.1325 - val_mean_absolute_error: 0.2580 - val_mean_absolute_percentage_error: 17674666.0000 - val_root_mean_squared_error: 0.3640
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 2s/step - loss: 0.1493 - mean_absolute_error: 0.2563 - mean_absolute_percentage_error: 16563954.0000 - root_mean_squared_error: 0.3864 - val_loss: 0.1226 - val_mean_absolute_error: 0.2567 - val_mean_absolute_percentage_error: 26779464.0000 - val_root_mean_squared_error: 0.3501
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 28s 3s/step - loss: 0.1382 - mean_absolute_error: 0.2524 - mean_absolute_percentage_error: 24185358.0000 - root_mean_squared_error: 0.3718 - val_loss: 0.1117 - val_mean_absolute_error: 0.2557 - val_mean_absolute_percentage_error: 38288008.0000 - val_root_mean_squared_error: 0.3342
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 15s 2s/step - loss: 0.1325 - mean_absolute_error: 0.2604 - mean_absolute_percentage_error: 33841884.0000 - root_mean_squared_error: 0.3638 - val_loss: 0.1008 - val_mean_absolute_error: 0.2561 - val_mean_absolute_percentage_error: 52637776.0000 - val_root_mean_squared_error: 0.3175
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 34s 4s/step - loss: 0.1175 - mean_absolute_error: 0.2606 - mean_absolute_percentage_error: 47317756.0000 - root_mean_squared_error: 0.3428 - val_loss: 0.0917 - val_mean_absolute_error: 0.2595 - val_mean_absolute_percentage_error: 69746968.0000 - val_root_mean_squared_error: 0.3028
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 41s 3s/step - loss: 0.1103 - mean_absolute_error: 0.2684 - mean_absolute_percentage_error: 61196864.0000 - root_mean_squared_error: 0.3320 - val_loss: 0.0865 - val_mean_absolute_error: 0.2651 - val_mean_absolute_percentage_error: 88397568.0000 - val_root_mean_squared_error: 0.2941
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.1049 - mean_absolute_error: 0.2763 - mean_absolute_percentage_error: 77766088.0000 - root_mean_squared_error: 0.3239 - val_loss: 0.0859 - val_mean_absolute_error: 0.2709 - val_mean_absolute_percentage_error: 103226288.0000 - val_root_mean_squared_error: 0.2931
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.1066 - mean_absolute_error: 0.2860 - mean_absolute_percentage_error: 86105656.0000 - root_mean_squared_error: 0.3265 - val_loss: 0.0864 - val_mean_absolute_error: 0.2729 - val_mean_absolute_percentage_error: 107601672.0000 - val_root_mean_squared_error: 0.2939
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - loss: 0.1080 - mean_absolute_error: 0.2892 - mean_absolute_percentage_error: 88979592.0000 - root_mean_squared_error: 0.3286 - val_loss: 0.0858 - val_mean_absolute_error: 0.2702 - val_mean_absolute_percentage_error: 101668720.0000 - val_root_mean_squared_error: 0.2930
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.1068 - mean_absolute_error: 0.2831 - mean_absolute_percentage_error: 81946128.0000 - root_mean_squared_error: 0.3268 - val_loss: 0.0858 - val_mean_absolute_error: 0.2673 - val_mean_absolute_percentage_error: 94650760.0000 - val_root_mean_squared_error: 0.2930
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 27s 5s/step - loss: 0.1065 - mean_absolute_error: 0.2808 - mean_absolute_percentage_error: 80564712.0000 - root_mean_squared_error: 0.3263 - val_loss: 0.0861 - val_mean_absolute_error: 0.2662 - val_mean_absolute_percentage_error: 91682912.0000 - val_root_mean_squared_error: 0.2934
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - loss: 0.1066 - mean_absolute_error: 0.2787 - mean_absolute_percentage_error: 75032496.0000 - root_mean_squared_error: 0.3265 - val_loss: 0.0860 - val_mean_absolute_error: 0.2663 - val_mean_absolute_percentage_error: 92010432.0000 - val_root_mean_squared_error: 0.2933
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step - loss: 0.1064 - mean_absolute_error: 0.2802 - mean_absolute_percentage_error: 79155776.0000 - root_mean_squared_error: 0.3262 - val_loss: 0.0859 - val_mean_absolute_error: 0.2667 - val_mean_absolute_percentage_error: 93241944.0000 - val_root_mean_squared_error: 0.2931
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 2s/step - loss: 0.1055 - mean_absolute_error: 0.2786 - mean_absolute_percentage_error: 79169456.0000 - root_mean_squared_error: 0.3248 - val_loss: 0.0858 - val_mean_absolute_error: 0.2673 - val_mean_absolute_percentage_error: 94681704.0000 - val_root_mean_squared_error: 0.2929
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 28s 3s/step - loss: 0.1069 - mean_absolute_error: 0.2824 - mean_absolute_percentage_error: 81140888.0000 - root_mean_squared_error: 0.3269 - val_loss: 0.0858 - val_mean_absolute_error: 0.2673 - val_mean_absolute_percentage_error: 94906200.0000 - val_root_mean_squared_error: 0.2929
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 19s 3s/step - loss: 0.1043 - mean_absolute_error: 0.2790 - mean_absolute_percentage_error: 82154760.0000 - root_mean_squared_error: 0.3229 - val_loss: 0.0859 - val_mean_absolute_error: 0.2664 - val_mean_absolute_percentage_error: 92833968.0000 - val_root_mean_squared_error: 0.2930
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 29s 3s/step - loss: 0.1044 - mean_absolute_error: 0.2780 - mean_absolute_percentage_error: 80465800.0000 - root_mean_squared_error: 0.3232 - val_loss: 0.0862 - val_mean_absolute_error: 0.2651 - val_mean_absolute_percentage_error: 89246512.0000 - val_root_mean_squared_error: 0.2936
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 19s 3s/step - loss: 0.1050 - mean_absolute_error: 0.2787 - mean_absolute_percentage_error: 81217504.0000 - root_mean_squared_error: 0.3240 - val_loss: 0.0867 - val_mean_absolute_error: 0.2636 - val_mean_absolute_percentage_error: 85325808.0000 - val_root_mean_squared_error: 0.2945
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 3s/step - loss: 0.1029 - mean_absolute_error: 0.2751 - mean_absolute_percentage_error: 79301472.0000 - root_mean_squared_error: 0.3209 - val_loss: 0.0871 - val_mean_absolute_error: 0.2628 - val_mean_absolute_percentage_error: 83240512.0000 - val_root_mean_squared_error: 0.2951
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 27s 4s/step - loss: 0.1025 - mean_absolute_error: 0.2756 - mean_absolute_percentage_error: 79481544.0000 - root_mean_squared_error: 0.3202 - val_loss: 0.0877 - val_mean_absolute_error: 0.2620 - val_mean_absolute_percentage_error: 80617192.0000 - val_root_mean_squared_error: 0.2962
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 2s/step - loss: 0.1002 - mean_absolute_error: 0.2730 - mean_absolute_percentage_error: 82363344.0000 - root_mean_squared_error: 0.3165 - val_loss: 0.0898 - val_mean_absolute_error: 0.2603 - val_mean_absolute_percentage_error: 74215144.0000 - val_root_mean_squared_error: 0.2997
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - loss: 0.0995 - mean_absolute_error: 0.2688 - mean_absolute_percentage_error: 78745680.0000 - root_mean_squared_error: 0.3154 - val_loss: 0.0901 - val_mean_absolute_error: 0.2601 - val_mean_absolute_percentage_error: 73607656.0000 - val_root_mean_squared_error: 0.3002
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.1002 - mean_absolute_error: 0.2705 - mean_absolute_percentage_error: 80119792.0000 - root_mean_squared_error: 0.3165 - val_loss: 0.0922 - val_mean_absolute_error: 0.2589 - val_mean_absolute_percentage_error: 68644904.0000 - val_root_mean_squared_error: 0.3036
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 33s 4s/step - loss: 0.0971 - mean_absolute_error: 0.2643 - mean_absolute_percentage_error: 77825360.0000 - root_mean_squared_error: 0.3116 - val_loss: 0.0944 - val_mean_absolute_error: 0.2579 - val_mean_absolute_percentage_error: 63825892.0000 - val_root_mean_squared_error: 0.3073
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 28s 1s/step - loss: 0.1013 - mean_absolute_error: 0.2685 - mean_absolute_percentage_error: 78006208.0000 - root_mean_squared_error: 0.3182 - val_loss: 0.0941 - val_mean_absolute_error: 0.2579 - val_mean_absolute_percentage_error: 64509972.0000 - val_root_mean_squared_error: 0.3067
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.0972 - mean_absolute_error: 0.2633 - mean_absolute_percentage_error: 78837256.0000 - root_mean_squared_error: 0.3118 - val_loss: 0.0945 - val_mean_absolute_error: 0.2576 - val_mean_absolute_percentage_error: 63472448.0000 - val_root_mean_squared_error: 0.3073
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 22s 3s/step - loss: 0.0993 - mean_absolute_error: 0.2659 - mean_absolute_percentage_error: 78717312.0000 - root_mean_squared_error: 0.3152 - val_loss: 0.0930 - val_mean_absolute_error: 0.2578 - val_mean_absolute_percentage_error: 66071608.0000 - val_root_mean_squared_error: 0.3049
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.0993 - mean_absolute_error: 0.2667 - mean_absolute_percentage_error: 81337232.0000 - root_mean_squared_error: 0.3150 - val_loss: 0.0931 - val_mean_absolute_error: 0.2575 - val_mean_absolute_percentage_error: 65392948.0000 - val_root_mean_squared_error: 0.3052
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.0988 - mean_absolute_error: 0.2662 - mean_absolute_percentage_error: 76219208.0000 - root_mean_squared_error: 0.3143 - val_loss: 0.0925 - val_mean_absolute_error: 0.2576 - val_mean_absolute_percentage_error: 66379680.0000 - val_root_mean_squared_error: 0.3042
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 14s 2s/step - loss: 0.1007 - mean_absolute_error: 0.2682 - mean_absolute_percentage_error: 77419520.0000 - root_mean_squared_error: 0.3173 - val_loss: 0.0935 - val_mean_absolute_error: 0.2571 - val_mean_absolute_percentage_error: 64140304.0000 - val_root_mean_squared_error: 0.3059
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step - loss: 0.0976 - mean_absolute_error: 0.2636 - mean_absolute_percentage_error: 75892000.0000 - root_mean_squared_error: 0.3125 - val_loss: 0.0918 - val_mean_absolute_error: 0.2574 - val_mean_absolute_percentage_error: 67228712.0000 - val_root_mean_squared_error: 0.3030
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.0988 - mean_absolute_error: 0.2667 - mean_absolute_percentage_error: 76405856.0000 - root_mean_squared_error: 0.3144 - val_loss: 0.0917 - val_mean_absolute_error: 0.2571 - val_mean_absolute_percentage_error: 67045020.0000 - val_root_mean_squared_error: 0.3029
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 26s 3s/step - loss: 0.0997 - mean_absolute_error: 0.2668 - mean_absolute_percentage_error: 75838656.0000 - root_mean_squared_error: 0.3157 - val_loss: 0.0939 - val_mean_absolute_error: 0.2561 - val_mean_absolute_percentage_error: 62429736.0000 - val_root_mean_squared_error: 0.3064
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.1012 - mean_absolute_error: 0.2678 - mean_absolute_percentage_error: 76331192.0000 - root_mean_squared_error: 0.3181 - val_loss: 0.0911 - val_mean_absolute_error: 0.2564 - val_mean_absolute_percentage_error: 67272984.0000 - val_root_mean_squared_error: 0.3018
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 28s 4s/step - loss: 0.0954 - mean_absolute_error: 0.2610 - mean_absolute_percentage_error: 76329672.0000 - root_mean_squared_error: 0.3089 - val_loss: 0.0903 - val_mean_absolute_error: 0.2560 - val_mean_absolute_percentage_error: 67984720.0000 - val_root_mean_squared_error: 0.3006
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 2s/step - loss: 0.0958 - mean_absolute_error: 0.2620 - mean_absolute_percentage_error: 77458296.0000 - root_mean_squared_error: 0.3096 - val_loss: 0.0906 - val_mean_absolute_error: 0.2552 - val_mean_absolute_percentage_error: 66499292.0000 - val_root_mean_squared_error: 0.3010
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.0950 - mean_absolute_error: 0.2595 - mean_absolute_percentage_error: 77189584.0000 - root_mean_squared_error: 0.3083 - val_loss: 0.0884 - val_mean_absolute_error: 0.2549 - val_mean_absolute_percentage_error: 70026744.0000 - val_root_mean_squared_error: 0.2973
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 4s/step - loss: 0.0947 - mean_absolute_error: 0.2602 - mean_absolute_percentage_error: 77971264.0000 - root_mean_squared_error: 0.3077 - val_loss: 0.0893 - val_mean_absolute_error: 0.2534 - val_mean_absolute_percentage_error: 66416800.0000 - val_root_mean_squared_error: 0.2988
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - loss: 0.0954 - mean_absolute_error: 0.2593 - mean_absolute_percentage_error: 74973776.0000 - root_mean_squared_error: 0.3089 - val_loss: 0.0869 - val_mean_absolute_error: 0.2525 - val_mean_absolute_percentage_error: 69302784.0000 - val_root_mean_squared_error: 0.2948
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - loss: 0.0933 - mean_absolute_error: 0.2581 - mean_absolute_percentage_error: 75799824.0000 - root_mean_squared_error: 0.3055 - val_loss: 0.0855 - val_mean_absolute_error: 0.2507 - val_mean_absolute_percentage_error: 69472184.0000 - val_root_mean_squared_error: 0.2924
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 5s/step - loss: 0.0930 - mean_absolute_error: 0.2561 - mean_absolute_percentage_error: 75024096.0000 - root_mean_squared_error: 0.3049 - val_loss: 0.0825 - val_mean_absolute_error: 0.2487 - val_mean_absolute_percentage_error: 72545712.0000 - val_root_mean_squared_error: 0.2872
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 26s 1s/step - loss: 0.0906 - mean_absolute_error: 0.2543 - mean_absolute_percentage_error: 75806888.0000 - root_mean_squared_error: 0.3009 - val_loss: 0.0814 - val_mean_absolute_error: 0.2445 - val_mean_absolute_percentage_error: 69124504.0000 - val_root_mean_squared_error: 0.2853
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.0875 - mean_absolute_error: 0.2478 - mean_absolute_percentage_error: 73369664.0000 - root_mean_squared_error: 0.2958 - val_loss: 0.0781 - val_mean_absolute_error: 0.2409 - val_mean_absolute_percentage_error: 71305152.0000 - val_root_mean_squared_error: 0.2794
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 5s/step - loss: 0.0855 - mean_absolute_error: 0.2440 - mean_absolute_percentage_error: 72486440.0000 - root_mean_squared_error: 0.2924 - val_loss: 0.0749 - val_mean_absolute_error: 0.2368 - val_mean_absolute_percentage_error: 72876896.0000 - val_root_mean_squared_error: 0.2737
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 40s 4s/step - loss: 0.0827 - mean_absolute_error: 0.2399 - mean_absolute_percentage_error: 69890472.0000 - root_mean_squared_error: 0.2876 - val_loss: 0.0726 - val_mean_absolute_error: 0.2310 - val_mean_absolute_percentage_error: 70252888.0000 - val_root_mean_squared_error: 0.2694
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 3s/step - loss: 0.0792 - mean_absolute_error: 0.2332 - mean_absolute_percentage_error: 71651168.0000 - root_mean_squared_error: 0.2814 - val_loss: 0.0696 - val_mean_absolute_error: 0.2278 - val_mean_absolute_percentage_error: 74393560.0000 - val_root_mean_squared_error: 0.2637
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 2s/step - loss: 0.0732 - mean_absolute_error: 0.2235 - mean_absolute_percentage_error: 66893448.0000 - root_mean_squared_error: 0.2706 - val_loss: 0.0682 - val_mean_absolute_error: 0.2191 - val_mean_absolute_percentage_error: 66382488.0000 - val_root_mean_squared_error: 0.2611
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 35s 4s/step - loss: 0.0709 - mean_absolute_error: 0.2183 - mean_absolute_percentage_error: 66126568.0000 - root_mean_squared_error: 0.2663 - val_loss: 0.0669 - val_mean_absolute_error: 0.2107 - val_mean_absolute_percentage_error: 59649136.0000 - val_root_mean_squared_error: 0.2586

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

25/25 ━━━━━━━━━━━━━━━━━━━━ 19s 310ms/step

array([[0.51864487],
       [0.51947576],
       [0.36995572],
       [0.3221997 ],
       [0.31213018],
       [0.2766857 ],
       [0.19010359],
       [0.14884573],
       [0.13346739],
       [0.12699404],
       [0.12500148],
       [0.14970689],
       [0.18471438],
       [0.27267084],
       [0.3285569 ],
       [0.4259632 ],
       [0.52271545],
       [0.5643973 ],
       [0.4861768 ],
       [0.3442145 ],
       [0.24992633],
       [0.24163479],
       [0.209963  ],
       [0.21497734],
       [0.36976975],
       [0.38919804],
       [0.26639885],
       [0.15560883],
       [0.1956476 ],
       [0.28019905],
       [0.27933502],
       [0.30307454],
       [0.44420624],
       [0.4746549 ],
       [0.35517877],
       [0.28594497],
       [0.18787032],
       [0.20198777],
       [0.17934641],
       [0.21745878],
       [0.4035918 ],
       [0.41305402],
       [0.28235206],
       [0.16839628],
       [0.18346736],
       [0.32674587],
       [0.5004322 ],
       [0.51914495],
       [0.3408424 ],
       [0.12582767],
       [0.10867312],
       [0.30867368],
       [0.52148074],
       [0.49097192],
       [0.25896347],
       [0.05732225],
       [0.07375069],
       [0.280199  ],
       [0.54553443],
       [0.47501564],
       [0.2436199 ],
       [0.06253111],
       [0.08740624],
       [0.28347367],
       [0.544596  ],
       [0.5240331 ],
       [0.28925788],
       [0.09563135],
       [0.09791224],
       [0.26007384],
       [0.47706908],
       [0.524971  ],
       [0.36316955],
       [0.22833708],
       [0.20488289],
       [0.20125014],
       [0.16937038],
       [0.17723672],
       [0.18494976],
       [0.28318688],
       [0.4492883 ],
       [0.5174093 ],
       [0.42098793],
       [0.33302924],
       [0.32535076],
       [0.30263668],
       [0.2515546 ],
       [0.14408144],
       [0.09193803],
       [0.14627367],
       [0.20509098],
       [0.30895138],
       [0.509666  ],
       [0.52355665],
       [0.39074165],
       [0.29340866],
       [0.2984139 ],
       [0.27478582],
       [0.2445768 ],
       [0.1895533 ],
       [0.17217875],
       [0.18572137],
       [0.20129064],
       [0.16321322],
       [0.15575026],
       [0.24551731],
       [0.31460592],
       [0.4064426 ],
       [0.52399796],
       [0.56333125],
       [0.4749987 ],
       [0.3590784 ],
       [0.26337728],
       [0.23636827],
       [0.20627293],
       [0.15219183],
       [0.179375  ],
       [0.30529702],
       [0.4858094 ],
       [0.42685235],
       [0.2845648 ],
       [0.20028323],
       [0.24256036],
       [0.25091898],
       [0.29335314],
       [0.34426737],
       [0.37665766],
       [0.30757374],
       [0.22665001],
       [0.21554908],
       [0.2137952 ],
       [0.2604699 ],
       [0.3804617 ],
       [0.43635702],
       [0.29723895],
       [0.12173185],
       [0.15493655],
       [0.22524929],
       [0.33436316],
       [0.4310634 ],
       [0.42211753],
       [0.29716223],
       [0.20420147],
       [0.13946685],
       [0.16300587],
       [0.15945253],
       [0.12168153],
       [0.09554894],
       [0.10203242],
       [0.22659422],
       [0.40585834],
       [0.4854597 ],
       [0.38127714],
       [0.22284155],
       [0.14243574],
       [0.13031186],
       [0.14506364],
       [0.11177886],
       [0.12891215],
       [0.13125592],
       [0.21549565],
       [0.36688328],
       [0.4673499 ],
       [0.35748512],
       [0.17414641],
       [0.1126255 ],
       [0.18411186],
       [0.21030581],
       [0.22584188],
       [0.31688297],
       [0.39314622],
       [0.28582734],
       [0.15158296],
       [0.13794926],
       [0.15994677],
       [0.22023425],
       [0.3206603 ],
       [0.4083118 ],
       [0.2887571 ],
       [0.14259441],
       [0.13195312],
       [0.22527605],
       [0.25097212],
       [0.24728295],
       [0.29091567],
       [0.31506193],
       [0.21436381],
       [0.133171  ],
       [0.13744459],
       [0.19676043],
       [0.1995904 ],
       [0.24013564],
       [0.34171912],
       [0.41830266],
       [0.30293226],
       [0.19376138],
       [0.13628778],
       [0.19077143],
       [0.22541556],
       [0.25228685],
       [0.34898055],
       [0.4355366 ],
       [0.37406105],
       [0.24905202],
       [0.18926632],
       [0.19736984],
       [0.2457082 ],
       [0.2156626 ],
       [0.23601094],
       [0.3492766 ],
       [0.45278448],
       [0.43068573],
       [0.33232826],
       [0.27322477],
       [0.180227  ],
       [0.12242485],
       [0.17373055],
       [0.2001391 ],
       [0.2637677 ],
       [0.46762747],
       [0.50018275],
       [0.35423732],
       [0.24130668],
       [0.24269818],
       [0.24954386],
       [0.24425563],
       [0.18045346],
       [0.11386952],
       [0.14481959],
       [0.24047208],
       [0.26324517],
       [0.24708055],
       [0.28720537],
       [0.32062218],
       [0.36714545],
       [0.5133477 ],
       [0.51606345],
       [0.3653176 ],
       [0.270899  ],
       [0.25451994],
       [0.23363009],
       [0.14000224],
       [0.09667809],
       [0.13607621],
       [0.19965434],
       [0.31650138],
       [0.49783885],
       [0.5383128 ],
       [0.4213034 ],
       [0.29793197],
       [0.22940032],
       [0.20556957],
       [0.13976267],
       [0.07166021],
       [0.06384818],
       [0.14569733],
       [0.23011987],
       [0.32174626],
       [0.4632167 ],
       [0.51476276],
       [0.36972538],
       [0.1528326 ],
       [0.15233782],
       [0.19750741],
       [0.2792307 ],
       [0.4080017 ],
       [0.46465158],
       [0.31400338],
       [0.19072768],
       [0.12728646],
       [0.15094373],
       [0.16738595],
       [0.15934983],
       [0.2084214 ],
       [0.39861536],
       [0.47560495],
       [0.3772886 ],
       [0.19952264],
       [0.21151057],
       [0.22545624],
       [0.27563187],
       [0.37852186],
       [0.39186952],
       [0.26078317],
       [0.13434628],
       [0.18068515],
       [0.23484313],
       [0.3248206 ],
       [0.41864946],
       [0.43963125],
       [0.28921086],
       [0.14144357],
       [0.16473353],
       [0.21228415],
       [0.31468052],
       [0.4001493 ],
       [0.49193215],
       [0.33794862],
       [0.15097311],
       [0.09324287],
       [0.28313625],
       [0.51710445],
       [0.50598216],
       [0.25781268],
       [0.05407068],
       [0.06448453],
       [0.2914747 ],
       [0.53749365],
       [0.5506633 ],
       [0.31666487],
       [0.09234073],
       [0.11375848],
       [0.19224566],
       [0.3260834 ],
       [0.44779927],
       [0.50054187],
       [0.38277665],
       [0.12745593],
       [0.18283454],
       [0.4489455 ],
       [0.5617363 ],
       [0.40790328],
       [0.0874729 ],
       [0.11262795],
       [0.4112208 ],
       [0.5190751 ],
       [0.35214084],
       [0.14332592],
       [0.10023119],
       [0.2792167 ],
       [0.48050833],
       [0.51734334],
       [0.33577457],
       [0.14210594],
       [0.16304071],
       [0.2454274 ],
       [0.34414858],
       [0.4723513 ],
       [0.43817335],
       [0.2807569 ],
       [0.143048  ],
       [0.19785857],
       [0.21554866],
       [0.28629088],
       [0.4255437 ],
       [0.48154908],
       [0.3324926 ],
       [0.19709553],
       [0.20287028],
       [0.22691193],
       [0.33374554],
       [0.4996274 ],
       [0.46098766],
       [0.27312624],
       [0.1326215 ],
       [0.18727016],
       [0.32485187],
       [0.3003972 ],
       [0.26202035],
       [0.38999504],
       [0.44025362],
       [0.34916615],
       [0.26640588],
       [0.22192118],
       [0.24565545],
       [0.24423733],
       [0.18131462],
       [0.21181849],
       [0.37778583],
       [0.47658762],
       [0.39657307],
       [0.2720901 ],
       [0.2337267 ],
       [0.19906043],
       [0.26752302],
       [0.3867157 ],
       [0.4561863 ],
       [0.35859042],
       [0.27065355],
       [0.21536876],
       [0.22108096],
       [0.22472532],
       [0.15235141],
       [0.17821762],
       [0.3779593 ],
       [0.50383866],
       [0.40179598],
       [0.25407144],
       [0.23315534],
       [0.25813866],
       [0.2141087 ],
       [0.26470917],
       [0.4005539 ],
       [0.44706082],
       [0.329637  ],
       [0.25412467],
       [0.21491152],
       [0.21676287],
       [0.20632339],
       [0.16720028],
       [0.2237527 ],
       [0.4014445 ],
       [0.507838  ],
       [0.3960867 ],
       [0.27712396],
       [0.20374483],
       [0.2334983 ],
       [0.19145447],
       [0.2492828 ],
       [0.3746094 ],
       [0.44355413],
       [0.33090714],
       [0.2579697 ],
       [0.18518248],
       [0.2187551 ],
       [0.19082925],
       [0.26908845],
       [0.3896162 ],
       [0.48899966],
       [0.39068747],
       [0.28648615],
       [0.2182298 ],
       [0.25364888],
       [0.22737703],
       [0.27463794],
       [0.38815588],
       [0.46838698],
       [0.35378766],
       [0.2372784 ],
       [0.23668337],
       [0.28460723],
       [0.24728987],
       [0.2770668 ],
       [0.40668344],
       [0.4711559 ],
       [0.3262095 ],
       [0.1848789 ],
       [0.19531542],
       [0.21779248],
       [0.3057209 ],
       [0.4223867 ],
       [0.4698299 ],
       [0.3145283 ],
       [0.13370651],
       [0.18257485],
       [0.22523807],
       [0.31494343],
       [0.41768098],
       [0.45787004],
       [0.333971  ],
       [0.1937885 ],
       [0.19545412],
       [0.23151474],
       [0.30873454],
       [0.44243678],
       [0.44155234],
       [0.29433763],
       [0.1283371 ],
       [0.12979835],
       [0.31934014],
       [0.5373648 ],
       [0.500567  ],
       [0.261281  ],
       [0.0654603 ],
       [0.11451156],
       [0.21264012],
       [0.36465582],
       [0.51692784],
       [0.44070825],
       [0.23990472],
       [0.10522862],
       [0.15888993],
       [0.21035424],
       [0.3312229 ],
       [0.45992517],
       [0.46962765],
       [0.28194052],
       [0.13122246],
       [0.15803012],
       [0.21261337],
       [0.35207003],
       [0.4991116 ],
       [0.47276574],
       [0.27135244],
       [0.11784288],
       [0.16341728],
       [0.24197592],
       [0.36734828],
       [0.45867234],
       [0.47121686],
       [0.3118024 ],
       [0.17186263],
       [0.18505946],
       [0.23305552],
       [0.35538125],
       [0.44656882],
       [0.48593256],
       [0.32385027],
       [0.18125175],
       [0.13959661],
       [0.23087671],
       [0.30566096],
       [0.23594567],
       [0.21500161],
       [0.3827394 ],
       [0.45809317],
       [0.3618987 ],
       [0.245588  ],
       [0.22276527],
       [0.2340527 ],
       [0.29840586],
       [0.40375072],
       [0.44298342],
       [0.33976626],
       [0.24161336],
       [0.22256316],
       [0.28382003],
       [0.2526626 ],
       [0.2624871 ],
       [0.30742007],
       [0.38843292],
       [0.3973747 ],
       [0.29412067],
       [0.22481565],
       [0.21631956],
       [0.19848329],
       [0.15466036],
       [0.10215876],
       [0.1019981 ],
       [0.19904442],
       [0.37349993],
       [0.52644366],
       [0.46225476],
       [0.2520517 ],
       [0.1035974 ],
       [0.12478605],
       [0.20180574],
       [0.15688708],
       [0.14811543],
       [0.23803434],
       [0.37435478],
       [0.3343755 ],
       [0.23568219],
       [0.13425986],
       [0.10356361],
       [0.10297608],
       [0.11807422],
       [0.10454936],
       [0.06932369],
       [0.14684175],
       [0.33709592],
       [0.5326578 ],
       [0.45419052],
       [0.20056164],
       [0.05463508],
       [0.09679473],
       [0.20461696],
       [0.19314456],
       [0.18351924],
       [0.2575156 ],
       [0.40129447],
       [0.37659603],
       [0.18967384],
       [0.07904729],
       [0.09214637],
       [0.087881  ],
       [0.14896569],
       [0.25127873],
       [0.39498362],
       [0.27329   ],
       [0.13542609],
       [0.15321463],
       [0.18248911],
       [0.21521848],
       [0.27074158],
       [0.34458306],
       [0.23582175],
       [0.08048051],
       [0.09592491],
       [0.15840662],
       [0.27156454],
       [0.36565417],
       [0.4176351 ],
       [0.24864179],
       [0.1145241 ],
       [0.07495555],
       [0.1388464 ],
       [0.20987299],
       [0.2564792 ],
       [0.32664233],
       [0.42718187],
       [0.3189647 ],
       [0.20105632],
       [0.18096104],
       [0.22162612],
       [0.22623968],
       [0.15554294],
       [0.17123196],
       [0.2915995 ],
       [0.5024952 ],
       [0.4700387 ],
       [0.33072725],
       [0.20919672],
       [0.18064025],
       [0.16046916],
       [0.12650779],
       [0.08893555],
       [0.1109876 ],
       [0.19474167],
       [0.26307395],
       [0.3599682 ],
       [0.48799008],
       [0.5588722 ],
       [0.4330193 ],
       [0.30382442],
       [0.21308044],
       [0.1380602 ],
       [0.15680815],
       [0.22808048],
       [0.22482708],
       [0.2709164 ],
       [0.41442102],
       [0.56191623],
       [0.48401305],
       [0.3397969 ],
       [0.24500382],
       [0.21468772],
       [0.1581559 ],
       [0.12059639],
       [0.16026089],
       [0.24246   ],
       [0.2812527 ],
       [0.3287328 ],
       [0.4444735 ],
       [0.516226  ],
       [0.40788737],
       [0.26493245],
       [0.14966118],
       [0.13152286],
       [0.185108  ],
       [0.2299055 ],
       [0.20181376],
       [0.2414325 ],
       [0.375207  ],
       [0.5236745 ],
       [0.41583312],
       [0.26091206],
       [0.1320619 ],
       [0.12060104],
       [0.12616809],
       [0.14821126],
       [0.17490515],
       [0.19901079],
       [0.28591317],
       [0.45626295],
       [0.5478324 ],
       [0.39499146],
       [0.21720128],
       [0.11904142],
       [0.13792011],
       [0.1825743 ],
       [0.2116809 ],
       [0.19501951],
       [0.24151394],
       [0.4004062 ],
       [0.5334763 ],
       [0.40824187],
       [0.21792006],
       [0.06339428],
       [0.08978308],
       [0.18400675],
       [0.2010966 ],
       [0.21102443],
       [0.33672994],
       [0.52205724],
       [0.44074965],
       [0.2984172 ],
       [0.1406113 ],
       [0.1310094 ],
       [0.12950361],
       [0.14975712],
       [0.20856461],
       [0.32750425],
       [0.49057308],
       [0.4513842 ],
       [0.32725477],
       [0.1880498 ],
       [0.1759499 ],
       [0.13597995],
       [0.19815874],
       [0.3206898 ],
       [0.46190357],
       [0.3707373 ],
       [0.27973086],
       [0.18473637],
       [0.24666026],
       [0.2258673 ],
       [0.25511074],
       [0.3591745 ],
       [0.43525237],
       [0.33227128],
       [0.22115138],
       [0.22076684],
       [0.2844715 ],
       [0.26091796],
       [0.28045464],
       [0.37852287],
       [0.44255835],
       [0.3275668 ],
       [0.19113019],
       [0.21343195],
       [0.26879495],
       [0.23030564],
       [0.24591766],
       [0.3703372 ],
       [0.4848808 ],
       [0.40682578],
       [0.24637759],
       [0.20733023],
       [0.21534935],
       [0.29985422],
       [0.42307842],
       [0.4886561 ],
       [0.36080793],
       [0.20910451],
       [0.17086369],
       [0.22543827],
       [0.2454896 ],
       [0.17346537],
       [0.1925437 ],
       [0.34220278],
       [0.52486795],
       [0.4484754 ],
       [0.27728814],
       [0.2106524 ],
       [0.24447793],
       [0.19376038],
       [0.23434834],
       [0.34037858],
       [0.47329432],
       [0.39895785],
       [0.28591222],
       [0.20818543],
       [0.19175439],
       [0.17447849],
       [0.17536086],
       [0.11647075],
       [0.20749226],
       [0.37662902],
       [0.53293544],
       [0.4249374 ],
       [0.2899219 ],
       [0.17267954],
       [0.1887518 ],
       [0.22489665],
       [0.1727304 ],
       [0.19594777],
       [0.3434087 ],
       [0.5423216 ],
       [0.4676758 ],
       [0.31031257],
       [0.17021835],
       [0.21044534],
       [0.18578534],
       [0.24462983],
       [0.3348834 ],
       [0.45019692],
       [0.38114995],
       [0.28921002],
       [0.2007283 ],
       [0.22923264],
       [0.21996608],
       [0.24338794],
       [0.30459082],
       [0.4346831 ],
       [0.38702548],
       [0.23119822],
       [0.20390913],
       [0.22865105],
       [0.34565178],
       [0.43840367],
       [0.47984383],
       [0.29352444],
       [0.14448252]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
15910         0.0           0.0           0.0           NaN
15919         0.0     45.085922           0.0           NaN
15920      2324.0   1747.559524   2931.155236           NaN
15921     16384.0  15282.644011  15534.328419           NaN
15922     25212.0  24396.229156  25499.346937           NaN
...           ...           ...           ...           ...
18273      7356.0   6918.407231   7148.104256  10369.553711
18274     17638.0  19779.365821  21016.223316  13152.110352
18275     23339.0  24030.007366  23687.023299  14395.314453
18276     26323.0  24112.268947  23126.102053   8805.733398
18286         0.0           0.0           0.0   4334.475586

[832 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 184s 5s/step - loss: 0.1653 - mean_absolute_error: 0.2656 - mean_absolute_percentage_error: 7911420.0000 - root_mean_squared_error: 0.4065 - val_loss: 0.0963 - val_mean_absolute_error: 0.2572 - val_mean_absolute_percentage_error: 60133276.0000 - val_root_mean_squared_error: 0.3103
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 49s 7s/step - loss: 0.1189 - mean_absolute_error: 0.2849 - mean_absolute_percentage_error: 71879704.0000 - root_mean_squared_error: 0.3445 - val_loss: 0.0895 - val_mean_absolute_error: 0.2804 - val_mean_absolute_percentage_error: 121393528.0000 - val_root_mean_squared_error: 0.2992
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 6s/step - loss: 0.1087 - mean_absolute_error: 0.2899 - mean_absolute_percentage_error: 93315784.0000 - root_mean_squared_error: 0.3297 - val_loss: 0.0886 - val_mean_absolute_error: 0.2619 - val_mean_absolute_percentage_error: 78373688.0000 - val_root_mean_squared_error: 0.2977
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 6s/step - loss: 0.1078 - mean_absolute_error: 0.2705 - mean_absolute_percentage_error: 66358680.0000 - root_mean_squared_error: 0.3284 - val_loss: 0.0860 - val_mean_absolute_error: 0.2665 - val_mean_absolute_percentage_error: 92334264.0000 - val_root_mean_squared_error: 0.2933
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 35s 5s/step - loss: 0.1073 - mean_absolute_error: 0.2834 - mean_absolute_percentage_error: 83289400.0000 - root_mean_squared_error: 0.3275 - val_loss: 0.0864 - val_mean_absolute_error: 0.2730 - val_mean_absolute_percentage_error: 107742080.0000 - val_root_mean_squared_error: 0.2939
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 43s 7s/step - loss: 0.1063 - mean_absolute_error: 0.2865 - mean_absolute_percentage_error: 89728384.0000 - root_mean_squared_error: 0.3261 - val_loss: 0.0858 - val_mean_absolute_error: 0.2677 - val_mean_absolute_percentage_error: 95669112.0000 - val_root_mean_squared_error: 0.2930
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 63s 10s/step - loss: 0.1046 - mean_absolute_error: 0.2764 - mean_absolute_percentage_error: 76680104.0000 - root_mean_squared_error: 0.3234 - val_loss: 0.0860 - val_mean_absolute_error: 0.2667 - val_mean_absolute_percentage_error: 92813864.0000 - val_root_mean_squared_error: 0.2933
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 67s 7s/step - loss: 0.1080 - mean_absolute_error: 0.2824 - mean_absolute_percentage_error: 77387760.0000 - root_mean_squared_error: 0.3286 - val_loss: 0.0858 - val_mean_absolute_error: 0.2697 - val_mean_absolute_percentage_error: 100337240.0000 - val_root_mean_squared_error: 0.2929
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 56s 9s/step - loss: 0.1048 - mean_absolute_error: 0.2806 - mean_absolute_percentage_error: 82843672.0000 - root_mean_squared_error: 0.3237 - val_loss: 0.0858 - val_mean_absolute_error: 0.2683 - val_mean_absolute_percentage_error: 97189864.0000 - val_root_mean_squared_error: 0.2929
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 37s 6s/step - loss: 0.1048 - mean_absolute_error: 0.2794 - mean_absolute_percentage_error: 82220448.0000 - root_mean_squared_error: 0.3237 - val_loss: 0.0858 - val_mean_absolute_error: 0.2677 - val_mean_absolute_percentage_error: 95563656.0000 - val_root_mean_squared_error: 0.2930
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 43s 6s/step - loss: 0.1051 - mean_absolute_error: 0.2803 - mean_absolute_percentage_error: 79967064.0000 - root_mean_squared_error: 0.3241 - val_loss: 0.0857 - val_mean_absolute_error: 0.2691 - val_mean_absolute_percentage_error: 99040808.0000 - val_root_mean_squared_error: 0.2928
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 64s 9s/step - loss: 0.1042 - mean_absolute_error: 0.2791 - mean_absolute_percentage_error: 81606424.0000 - root_mean_squared_error: 0.3228 - val_loss: 0.0858 - val_mean_absolute_error: 0.2670 - val_mean_absolute_percentage_error: 94170984.0000 - val_root_mean_squared_error: 0.2930
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 83s 8s/step - loss: 0.1065 - mean_absolute_error: 0.2812 - mean_absolute_percentage_error: 79797936.0000 - root_mean_squared_error: 0.3263 - val_loss: 0.0856 - val_mean_absolute_error: 0.2678 - val_mean_absolute_percentage_error: 96788576.0000 - val_root_mean_squared_error: 0.2925
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 84s 8s/step - loss: 0.1039 - mean_absolute_error: 0.2795 - mean_absolute_percentage_error: 83378752.0000 - root_mean_squared_error: 0.3224 - val_loss: 0.0853 - val_mean_absolute_error: 0.2652 - val_mean_absolute_percentage_error: 93150592.0000 - val_root_mean_squared_error: 0.2920
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 89s 9s/step - loss: 0.1023 - mean_absolute_error: 0.2753 - mean_absolute_percentage_error: 82376400.0000 - root_mean_squared_error: 0.3198 - val_loss: 0.0912 - val_mean_absolute_error: 0.2559 - val_mean_absolute_percentage_error: 67506352.0000 - val_root_mean_squared_error: 0.3020
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 79s 8s/step - loss: 0.0971 - mean_absolute_error: 0.2628 - mean_absolute_percentage_error: 77389208.0000 - root_mean_squared_error: 0.3116 - val_loss: 0.0858 - val_mean_absolute_error: 0.2581 - val_mean_absolute_percentage_error: 80115568.0000 - val_root_mean_squared_error: 0.2930
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 96s 10s/step - loss: 0.0979 - mean_absolute_error: 0.2687 - mean_absolute_percentage_error: 82214816.0000 - root_mean_squared_error: 0.3129 - val_loss: 0.0876 - val_mean_absolute_error: 0.2560 - val_mean_absolute_percentage_error: 72902464.0000 - val_root_mean_squared_error: 0.2960
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 69s 6s/step - loss: 0.0989 - mean_absolute_error: 0.2663 - mean_absolute_percentage_error: 77846304.0000 - root_mean_squared_error: 0.3144 - val_loss: 0.0848 - val_mean_absolute_error: 0.2550 - val_mean_absolute_percentage_error: 79000552.0000 - val_root_mean_squared_error: 0.2913
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 48s 7s/step - loss: 0.0954 - mean_absolute_error: 0.2601 - mean_absolute_percentage_error: 77098720.0000 - root_mean_squared_error: 0.3089 - val_loss: 0.0824 - val_mean_absolute_error: 0.2571 - val_mean_absolute_percentage_error: 88365928.0000 - val_root_mean_squared_error: 0.2870
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 102s 10s/step - loss: 0.0943 - mean_absolute_error: 0.2578 - mean_absolute_percentage_error: 75335144.0000 - root_mean_squared_error: 0.3071 - val_loss: 0.0815 - val_mean_absolute_error: 0.2623 - val_mean_absolute_percentage_error: 101917712.0000 - val_root_mean_squared_error: 0.2855
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 38s 6s/step - loss: 0.0957 - mean_absolute_error: 0.2607 - mean_absolute_percentage_error: 76256904.0000 - root_mean_squared_error: 0.3094 - val_loss: 0.0795 - val_mean_absolute_error: 0.2578 - val_mean_absolute_percentage_error: 100609272.0000 - val_root_mean_squared_error: 0.2820
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 49s 7s/step - loss: 0.0953 - mean_absolute_error: 0.2642 - mean_absolute_percentage_error: 79936840.0000 - root_mean_squared_error: 0.3088 - val_loss: 0.0765 - val_mean_absolute_error: 0.2462 - val_mean_absolute_percentage_error: 82470400.0000 - val_root_mean_squared_error: 0.2767
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 104s 10s/step - loss: 0.0898 - mean_absolute_error: 0.2576 - mean_absolute_percentage_error: 80252752.0000 - root_mean_squared_error: 0.2997 - val_loss: 0.0699 - val_mean_absolute_error: 0.2331 - val_mean_absolute_percentage_error: 79066544.0000 - val_root_mean_squared_error: 0.2645
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 52s 7s/step - loss: 0.0803 - mean_absolute_error: 0.2373 - mean_absolute_percentage_error: 71453056.0000 - root_mean_squared_error: 0.2833 - val_loss: 0.0688 - val_mean_absolute_error: 0.2273 - val_mean_absolute_percentage_error: 91219896.0000 - val_root_mean_squared_error: 0.2623
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 76s 6s/step - loss: 0.0705 - mean_absolute_error: 0.2159 - mean_absolute_percentage_error: 70200664.0000 - root_mean_squared_error: 0.2654 - val_loss: 0.0810 - val_mean_absolute_error: 0.2335 - val_mean_absolute_percentage_error: 76108976.0000 - val_root_mean_squared_error: 0.2847
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 69s 11s/step - loss: 0.0615 - mean_absolute_error: 0.1892 - mean_absolute_percentage_error: 58909444.0000 - root_mean_squared_error: 0.2480 - val_loss: 0.0690 - val_mean_absolute_error: 0.2086 - val_mean_absolute_percentage_error: 58343776.0000 - val_root_mean_squared_error: 0.2627
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 75s 8s/step - loss: 0.0546 - mean_absolute_error: 0.1780 - mean_absolute_percentage_error: 51797368.0000 - root_mean_squared_error: 0.2337 - val_loss: 0.0544 - val_mean_absolute_error: 0.1744 - val_mean_absolute_percentage_error: 40047212.0000 - val_root_mean_squared_error: 0.2332
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 91s 10s/step - loss: 0.0520 - mean_absolute_error: 0.1671 - mean_absolute_percentage_error: 43684744.0000 - root_mean_squared_error: 0.2280 - val_loss: 0.0436 - val_mean_absolute_error: 0.1568 - val_mean_absolute_percentage_error: 34502628.0000 - val_root_mean_squared_error: 0.2089
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 83s 9s/step - loss: 0.0487 - mean_absolute_error: 0.1605 - mean_absolute_percentage_error: 45766608.0000 - root_mean_squared_error: 0.2207 - val_loss: 0.0423 - val_mean_absolute_error: 0.1425 - val_mean_absolute_percentage_error: 21440354.0000 - val_root_mean_squared_error: 0.2056
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 59s 8s/step - loss: 0.0442 - mean_absolute_error: 0.1509 - mean_absolute_percentage_error: 34853840.0000 - root_mean_squared_error: 0.2102 - val_loss: 0.0403 - val_mean_absolute_error: 0.1390 - val_mean_absolute_percentage_error: 20614976.0000 - val_root_mean_squared_error: 0.2008
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 75s 7s/step - loss: 0.0401 - mean_absolute_error: 0.1379 - mean_absolute_percentage_error: 32376514.0000 - root_mean_squared_error: 0.2001 - val_loss: 0.0346 - val_mean_absolute_error: 0.1308 - val_mean_absolute_percentage_error: 24440640.0000 - val_root_mean_squared_error: 0.1860
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 83s 6s/step - loss: 0.0376 - mean_absolute_error: 0.1369 - mean_absolute_percentage_error: 31621470.0000 - root_mean_squared_error: 0.1939 - val_loss: 0.0370 - val_mean_absolute_error: 0.1269 - val_mean_absolute_percentage_error: 12925013.0000 - val_root_mean_squared_error: 0.1924
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 33s 6s/step - loss: 0.0365 - mean_absolute_error: 0.1303 - mean_absolute_percentage_error: 25614006.0000 - root_mean_squared_error: 0.1911 - val_loss: 0.0367 - val_mean_absolute_error: 0.1355 - val_mean_absolute_percentage_error: 18436356.0000 - val_root_mean_squared_error: 0.1916
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 68s 10s/step - loss: 0.0314 - mean_absolute_error: 0.1230 - mean_absolute_percentage_error: 25153546.0000 - root_mean_squared_error: 0.1770 - val_loss: 0.0303 - val_mean_absolute_error: 0.1180 - val_mean_absolute_percentage_error: 17281950.0000 - val_root_mean_squared_error: 0.1740
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 63s 5s/step - loss: 0.0293 - mean_absolute_error: 0.1166 - mean_absolute_percentage_error: 23224772.0000 - root_mean_squared_error: 0.1711 - val_loss: 0.0365 - val_mean_absolute_error: 0.1267 - val_mean_absolute_percentage_error: 12005130.0000 - val_root_mean_squared_error: 0.1910
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 67s 10s/step - loss: 0.0287 - mean_absolute_error: 0.1140 - mean_absolute_percentage_error: 19950862.0000 - root_mean_squared_error: 0.1694 - val_loss: 0.0293 - val_mean_absolute_error: 0.1155 - val_mean_absolute_percentage_error: 19007296.0000 - val_root_mean_squared_error: 0.1713
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 46s 8s/step - loss: 0.0266 - mean_absolute_error: 0.1094 - mean_absolute_percentage_error: 21599814.0000 - root_mean_squared_error: 0.1629 - val_loss: 0.0294 - val_mean_absolute_error: 0.1142 - val_mean_absolute_percentage_error: 15995666.0000 - val_root_mean_squared_error: 0.1716
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 90s 8s/step - loss: 0.0249 - mean_absolute_error: 0.1051 - mean_absolute_percentage_error: 18289196.0000 - root_mean_squared_error: 0.1578 - val_loss: 0.0333 - val_mean_absolute_error: 0.1205 - val_mean_absolute_percentage_error: 14269257.0000 - val_root_mean_squared_error: 0.1825
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 57s 9s/step - loss: 0.0207 - mean_absolute_error: 0.0953 - mean_absolute_percentage_error: 16485455.0000 - root_mean_squared_error: 0.1438 - val_loss: 0.0377 - val_mean_absolute_error: 0.1251 - val_mean_absolute_percentage_error: 11291753.0000 - val_root_mean_squared_error: 0.1941
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 85s 9s/step - loss: 0.0234 - mean_absolute_error: 0.1006 - mean_absolute_percentage_error: 17370328.0000 - root_mean_squared_error: 0.1528 - val_loss: 0.0374 - val_mean_absolute_error: 0.1269 - val_mean_absolute_percentage_error: 11575404.0000 - val_root_mean_squared_error: 0.1933
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 60s 10s/step - loss: 0.0197 - mean_absolute_error: 0.0931 - mean_absolute_percentage_error: 14343923.0000 - root_mean_squared_error: 0.1403 - val_loss: 0.0324 - val_mean_absolute_error: 0.1182 - val_mean_absolute_percentage_error: 18345084.0000 - val_root_mean_squared_error: 0.1799
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 67s 6s/step - loss: 0.0192 - mean_absolute_error: 0.0934 - mean_absolute_percentage_error: 17229504.0000 - root_mean_squared_error: 0.1386 - val_loss: 0.0309 - val_mean_absolute_error: 0.1153 - val_mean_absolute_percentage_error: 15336031.0000 - val_root_mean_squared_error: 0.1759
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 53s 7s/step - loss: 0.0172 - mean_absolute_error: 0.0881 - mean_absolute_percentage_error: 15661197.0000 - root_mean_squared_error: 0.1311 - val_loss: 0.0394 - val_mean_absolute_error: 0.1273 - val_mean_absolute_percentage_error: 12588467.0000 - val_root_mean_squared_error: 0.1985
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 55s 9s/step - loss: 0.0162 - mean_absolute_error: 0.0839 - mean_absolute_percentage_error: 11821030.0000 - root_mean_squared_error: 0.1274 - val_loss: 0.0367 - val_mean_absolute_error: 0.1238 - val_mean_absolute_percentage_error: 14196227.0000 - val_root_mean_squared_error: 0.1915
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 94s 10s/step - loss: 0.0144 - mean_absolute_error: 0.0795 - mean_absolute_percentage_error: 12499223.0000 - root_mean_squared_error: 0.1202 - val_loss: 0.0405 - val_mean_absolute_error: 0.1290 - val_mean_absolute_percentage_error: 12815100.0000 - val_root_mean_squared_error: 0.2013
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 77s 8s/step - loss: 0.0139 - mean_absolute_error: 0.0785 - mean_absolute_percentage_error: 11872236.0000 - root_mean_squared_error: 0.1180 - val_loss: 0.0392 - val_mean_absolute_error: 0.1257 - val_mean_absolute_percentage_error: 12055457.0000 - val_root_mean_squared_error: 0.1981
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 99s 11s/step - loss: 0.0128 - mean_absolute_error: 0.0756 - mean_absolute_percentage_error: 12051082.0000 - root_mean_squared_error: 0.1131 - val_loss: 0.0392 - val_mean_absolute_error: 0.1281 - val_mean_absolute_percentage_error: 14169591.0000 - val_root_mean_squared_error: 0.1981
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 75s 9s/step - loss: 0.0114 - mean_absolute_error: 0.0724 - mean_absolute_percentage_error: 11269364.0000 - root_mean_squared_error: 0.1070 - val_loss: 0.0454 - val_mean_absolute_error: 0.1349 - val_mean_absolute_percentage_error: 10429667.0000 - val_root_mean_squared_error: 0.2130
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 44s 6s/step - loss: 0.0112 - mean_absolute_error: 0.0701 - mean_absolute_percentage_error: 11524541.0000 - root_mean_squared_error: 0.1060 - val_loss: 0.0472 - val_mean_absolute_error: 0.1389 - val_mean_absolute_percentage_error: 11982076.0000 - val_root_mean_squared_error: 0.2173
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 56s 9s/step - loss: 0.0103 - mean_absolute_error: 0.0691 - mean_absolute_percentage_error: 10623755.0000 - root_mean_squared_error: 0.1013 - val_loss: 0.0404 - val_mean_absolute_error: 0.1279 - val_mean_absolute_percentage_error: 12934223.0000 - val_root_mean_squared_error: 0.2011

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

25/25 ━━━━━━━━━━━━━━━━━━━━ 23s 409ms/step

array([[ 7.53708124e-01],
       [ 8.10531199e-01],
       [ 5.62089324e-01],
       [ 8.11576128e-01],
       [ 2.16442049e-01],
       [ 7.95011073e-02],
       [ 4.91415650e-01],
       [ 4.16549116e-01],
       [ 6.67946935e-01],
       [ 2.31645674e-01],
       [-8.43868777e-03],
       [-3.36370245e-03],
       [-1.43427402e-04],
       [ 1.47302840e-02],
       [ 3.61013189e-02],
       [ 2.76758581e-01],
       [ 8.52484524e-01],
       [ 9.86625314e-01],
       [ 1.02069080e-01],
       [ 8.74821842e-03],
       [-4.72890213e-03],
       [-5.26105240e-03],
       [ 5.53645007e-03],
       [ 8.43771547e-02],
       [ 6.32832825e-01],
       [ 1.02343559e+00],
       [ 2.21894234e-02],
       [ 2.56843567e-02],
       [ 2.96005942e-02],
       [ 1.88879892e-02],
       [ 2.62523275e-02],
       [ 2.69189000e-01],
       [ 6.54622912e-01],
       [ 8.65892410e-01],
       [ 9.11053643e-02],
       [ 2.34810919e-01],
       [ 6.65965676e-03],
       [ 1.98730044e-02],
       [ 1.71287823e-02],
       [ 2.05428004e-01],
       [ 8.21119606e-01],
       [ 6.50966465e-01],
       [-2.56656855e-02],
       [ 7.20595941e-03],
       [ 3.02462317e-02],
       [ 1.43660396e-01],
       [ 6.46757483e-01],
       [ 6.21569991e-01],
       [-2.31889300e-02],
       [ 2.43341923e-03],
       [ 1.72246974e-02],
       [ 2.67280489e-01],
       [ 9.47904348e-01],
       [ 7.98697352e-01],
       [ 1.05451792e-02],
       [ 7.21660629e-03],
       [ 4.23645303e-02],
       [ 3.26094359e-01],
       [ 8.24200392e-01],
       [ 5.99538624e-01],
       [ 6.49504736e-03],
       [ 4.62613069e-02],
       [ 4.02672701e-02],
       [ 4.84113932e-01],
       [ 7.73737669e-01],
       [ 8.76763225e-01],
       [ 2.17094161e-02],
       [ 1.52281132e-02],
       [ 7.48013109e-02],
       [ 5.68220019e-01],
       [ 8.88622582e-01],
       [ 9.08814311e-01],
       [ 5.96087277e-01],
       [ 1.84169173e-01],
       [ 6.69607997e-01],
       [ 3.77221964e-02],
       [ 1.82503685e-02],
       [ 5.79493120e-02],
       [ 2.48823669e-02],
       [ 3.96410644e-01],
       [ 9.46977615e-01],
       [ 9.87197101e-01],
       [ 1.08133364e+00],
       [ 1.19864976e+00],
       [ 9.15220618e-01],
       [ 6.81991518e-01],
       [-9.25793126e-03],
       [ 1.09027456e-02],
       [ 1.30487941e-02],
       [ 2.24046111e-02],
       [ 2.78802998e-02],
       [ 4.63549912e-01],
       [ 8.68409514e-01],
       [ 7.71359205e-01],
       [ 8.42023611e-01],
       [ 1.06756938e+00],
       [ 8.56220305e-01],
       [ 2.36087516e-02],
       [ 2.97848210e-02],
       [ 5.49475908e-01],
       [ 1.88689470e-01],
       [ 2.04904191e-03],
       [ 5.96466959e-02],
       [ 1.53097883e-03],
       [ 8.11287388e-03],
       [ 9.96186957e-03],
       [ 2.88468041e-02],
       [ 2.43084729e-01],
       [ 7.21844196e-01],
       [ 6.12576246e-01],
       [ 2.91751511e-02],
       [ 3.05981878e-02],
       [ 4.62761521e-03],
       [-9.15077701e-03],
       [ 3.76634486e-03],
       [ 2.23127119e-02],
       [ 1.76732570e-01],
       [ 6.67170703e-01],
       [ 9.04549241e-01],
       [ 2.07618460e-01],
       [ 3.11490484e-02],
       [ 2.90815532e-02],
       [ 1.63986105e-02],
       [ 3.45464908e-02],
       [ 9.72987711e-02],
       [ 5.62777162e-01],
       [ 8.21735144e-01],
       [ 8.27059388e-01],
       [ 6.22248650e-03],
       [ 3.31596434e-02],
       [ 4.18856889e-02],
       [ 3.88546109e-01],
       [ 6.76086366e-01],
       [ 3.20032895e-01],
       [ 1.64794140e-02],
       [-2.58293003e-04],
       [ 1.91396512e-02],
       [ 3.24512497e-02],
       [ 1.52877167e-01],
       [ 7.38398194e-01],
       [ 5.92752099e-01],
       [ 1.78950295e-01],
       [ 2.62869239e-01],
       [ 2.68930733e-01],
       [ 8.02860409e-03],
       [ 7.30634481e-03],
       [ 1.29926372e-02],
       [ 1.82385445e-02],
       [ 4.27411906e-02],
       [ 1.49806589e-01],
       [ 4.84877229e-01],
       [ 4.23938692e-01],
       [ 7.61568993e-02],
       [ 1.14525571e-01],
       [ 2.11183056e-01],
       [ 6.84541166e-02],
       [ 3.22512053e-02],
       [ 1.68131217e-02],
       [ 1.58214383e-02],
       [ 2.40530707e-02],
       [ 7.30898380e-02],
       [ 4.44489211e-01],
       [ 4.02418405e-01],
       [ 1.76428407e-01],
       [ 6.31371960e-02],
       [ 1.90175921e-02],
       [ 1.74618028e-02],
       [ 2.40191091e-02],
       [ 1.41300455e-01],
       [ 5.00764012e-01],
       [ 5.47162175e-01],
       [ 1.08362317e-01],
       [ 1.51449032e-02],
       [ 2.19647940e-02],
       [ 3.14711817e-02],
       [ 1.70008585e-01],
       [ 4.21459317e-01],
       [ 6.20375156e-01],
       [ 7.30849653e-02],
       [ 3.90876271e-02],
       [ 1.95806324e-02],
       [ 1.91982053e-02],
       [ 2.44672261e-02],
       [ 1.03016883e-01],
       [ 5.05861938e-01],
       [ 6.90065384e-01],
       [ 1.83643922e-01],
       [ 3.06306034e-03],
       [ 1.07285306e-02],
       [ 1.11980848e-02],
       [ 2.33744681e-02],
       [ 3.23420167e-01],
       [ 6.56566501e-01],
       [ 6.82419062e-01],
       [ 3.64582479e-01],
       [ 2.04449724e-02],
       [ 1.58106014e-02],
       [ 1.74728744e-02],
       [ 3.02009284e-02],
       [ 2.26169795e-01],
       [ 6.58114076e-01],
       [ 5.84629357e-01],
       [ 1.28672898e-01],
       [ 1.14487052e-01],
       [ 4.22596335e-02],
       [ 3.51389423e-02],
       [ 2.28432175e-02],
       [ 4.14037034e-02],
       [ 3.33887339e-01],
       [ 5.30728400e-01],
       [ 8.03344071e-01],
       [ 1.16379404e+00],
       [ 7.92874336e-01],
       [ 6.84456706e-01],
       [ 4.22168821e-02],
       [ 1.66681707e-02],
       [ 3.88622805e-02],
       [ 2.62582377e-02],
       [ 2.63717175e-01],
       [ 8.32650065e-01],
       [ 8.73558521e-01],
       [ 7.92806268e-01],
       [ 9.85187411e-01],
       [ 1.02533853e+00],
       [ 9.76386666e-01],
       [ 7.34467387e-01],
       [ 8.47003222e-01],
       [ 4.96294528e-01],
       [ 5.28682888e-01],
       [ 6.70662403e-01],
       [ 1.14078000e-01],
       [ 3.39352377e-02],
       [ 4.77562584e-02],
       [ 9.93016362e-02],
       [ 4.69034433e-01],
       [ 8.34664643e-01],
       [ 8.10885429e-01],
       [ 5.27994037e-01],
       [ 5.26275635e-01],
       [ 7.40426183e-01],
       [ 4.67445850e-01],
       [ 3.57019417e-02],
       [ 3.07850484e-02],
       [ 3.74606512e-02],
       [ 5.70416115e-02],
       [ 3.73954147e-01],
       [ 6.50361657e-01],
       [ 7.76512980e-01],
       [ 7.01971531e-01],
       [ 4.50827777e-01],
       [ 5.98782599e-01],
       [ 6.33693635e-01],
       [ 3.49055886e-01],
       [ 1.65462047e-02],
       [ 3.58092189e-02],
       [ 4.82457429e-02],
       [ 6.20309040e-02],
       [ 3.25473309e-01],
       [ 7.03942060e-01],
       [ 7.99948096e-01],
       [ 2.49369949e-01],
       [-1.06623024e-03],
       [ 5.61580583e-02],
       [ 4.04276624e-02],
       [ 2.93981105e-01],
       [ 7.23786116e-01],
       [ 8.20793509e-01],
       [ 7.19102859e-01],
       [ 4.58686590e-01],
       [ 3.44586819e-02],
       [ 2.91872323e-02],
       [ 3.18947323e-02],
       [ 2.12711617e-02],
       [ 2.48923257e-01],
       [ 8.23187292e-01],
       [ 7.15183556e-01],
       [ 1.38615415e-01],
       [ 1.06842294e-02],
       [ 1.98238268e-02],
       [ 4.07083370e-02],
       [ 3.19228560e-01],
       [ 7.99367547e-01],
       [ 7.10584998e-01],
       [ 1.41994171e-02],
       [-7.30279461e-03],
       [ 3.08365468e-02],
       [ 4.58237976e-02],
       [ 3.52346301e-01],
       [ 7.95585990e-01],
       [ 7.24157572e-01],
       [-7.37077370e-03],
       [ 1.15443207e-02],
       [ 2.12972313e-02],
       [ 2.48907320e-02],
       [ 2.96187162e-01],
       [ 7.96115279e-01],
       [ 8.30385685e-01],
       [ 8.38720724e-02],
       [ 8.50498304e-03],
       [ 3.29732932e-02],
       [ 4.58410412e-01],
       [ 9.18115854e-01],
       [ 1.05194449e+00],
       [-8.60542059e-06],
       [ 5.74087910e-03],
       [ 3.72179523e-02],
       [ 3.04846942e-01],
       [ 7.74847746e-01],
       [ 8.33477914e-01],
       [-4.36483324e-03],
       [ 5.34438342e-03],
       [ 6.94003254e-02],
       [ 6.67394400e-02],
       [ 3.98630857e-01],
       [ 6.48408115e-01],
       [ 9.07888174e-01],
       [ 4.09106910e-01],
       [ 3.37847583e-02],
       [ 3.16325188e-01],
       [ 9.52570796e-01],
       [ 1.03813374e+00],
       [ 1.50118377e-02],
       [ 1.38832759e-02],
       [ 3.29375982e-01],
       [ 9.30988550e-01],
       [ 9.45306838e-01],
       [ 1.03237733e-01],
       [ 2.84580905e-02],
       [ 2.63128113e-02],
       [ 3.49755526e-01],
       [ 8.39919209e-01],
       [ 9.16447699e-01],
       [ 1.74018472e-01],
       [ 3.52828987e-02],
       [ 8.53580609e-02],
       [ 4.57413346e-02],
       [ 4.25212145e-01],
       [ 7.87510395e-01],
       [ 9.30657029e-01],
       [-2.87449956e-02],
       [ 7.65419453e-02],
       [ 9.87861678e-03],
       [ 4.48175706e-02],
       [ 3.59771967e-01],
       [ 7.53662109e-01],
       [ 9.16976213e-01],
       [ 7.53777266e-01],
       [ 1.53990593e-02],
       [ 5.74302375e-02],
       [ 9.54121053e-02],
       [ 3.90324473e-01],
       [ 8.54819059e-01],
       [ 8.84482086e-01],
       [ 1.15280226e-02],
       [ 2.11664625e-02],
       [ 3.21688242e-02],
       [ 1.16033126e-02],
       [ 3.56935188e-02],
       [ 3.04030359e-01],
       [ 8.25280368e-01],
       [ 8.96163285e-01],
       [ 7.47632682e-01],
       [ 2.83792496e-01],
       [ 1.08876526e-02],
       [ 7.26334378e-03],
       [ 5.74880652e-03],
       [ 3.04590389e-02],
       [ 1.40806466e-01],
       [ 8.44046175e-01],
       [ 7.55694032e-01],
       [ 7.28555024e-03],
       [ 1.55069493e-02],
       [ 1.07081801e-01],
       [ 2.85917632e-02],
       [ 2.53818959e-01],
       [ 7.80691564e-01],
       [ 8.12927306e-01],
       [ 5.63672543e-01],
       [ 5.69337010e-01],
       [ 3.81842494e-01],
       [ 3.83090191e-02],
       [ 2.74265707e-02],
       [ 2.82974765e-02],
       [ 2.99045742e-01],
       [ 6.76809907e-01],
       [ 7.59699941e-01],
       [ 5.45890689e-01],
       [ 3.37028727e-02],
       [ 2.01349333e-02],
       [ 1.41700767e-02],
       [ 2.23783385e-02],
       [ 2.95766175e-01],
       [ 6.50188446e-01],
       [ 8.20043564e-01],
       [ 8.24949980e-01],
       [ 6.05671227e-01],
       [ 1.36790395e-01],
       [ 2.80374400e-02],
       [ 1.53052211e-02],
       [ 4.62073088e-02],
       [ 2.21451342e-01],
       [ 7.59046316e-01],
       [ 8.37673008e-01],
       [ 3.39348614e-01],
       [ 4.11070466e-01],
       [ 2.03128904e-02],
       [ 1.81083325e-02],
       [ 2.75568590e-02],
       [ 1.92364618e-01],
       [ 5.73992491e-01],
       [ 9.16318536e-01],
       [ 5.85731089e-01],
       [ 3.33291590e-01],
       [ 3.08434293e-02],
       [ 9.85009596e-03],
       [ 2.33732499e-02],
       [ 2.40865111e-01],
       [ 6.46628797e-01],
       [ 7.41324544e-01],
       [ 4.97455239e-01],
       [ 3.06232393e-01],
       [ 2.49595102e-02],
       [ 1.39755458e-02],
       [ 1.13809705e-02],
       [ 2.03424245e-01],
       [ 6.93594813e-01],
       [ 8.05269420e-01],
       [ 3.32445562e-01],
       [ 8.96538422e-03],
       [ 3.04338597e-02],
       [ 1.50130354e-02],
       [ 1.68148987e-02],
       [ 2.67323405e-01],
       [ 7.22050846e-01],
       [ 8.01743865e-01],
       [ 1.47682101e-01],
       [ 1.72390379e-02],
       [ 2.95311082e-02],
       [ 2.67287381e-02],
       [ 7.94910342e-02],
       [ 7.29605675e-01],
       [ 7.63123214e-01],
       [ 3.11767012e-02],
       [ 2.96588819e-02],
       [ 3.12338322e-02],
       [ 4.23227735e-02],
       [ 2.30877250e-01],
       [ 7.26295888e-01],
       [ 8.13504338e-01],
       [ 6.35291398e-01],
       [ 4.79658321e-03],
       [ 5.04872501e-02],
       [ 3.31973322e-02],
       [ 2.39212230e-01],
       [ 9.15329814e-01],
       [ 7.56838560e-01],
       [ 1.68731697e-02],
       [ 5.87829389e-03],
       [ 2.71210987e-02],
       [ 2.64134854e-01],
       [ 8.55512917e-01],
       [ 9.85230863e-01],
       [ 9.14912671e-03],
       [ 1.96316876e-02],
       [ 2.28915755e-02],
       [ 4.25971523e-02],
       [ 1.06070429e-01],
       [ 8.28848124e-01],
       [ 8.53794456e-01],
       [ 2.72252224e-03],
       [ 4.56736125e-02],
       [ 6.67916238e-02],
       [ 5.12689538e-02],
       [ 1.47624359e-01],
       [ 8.09890985e-01],
       [ 8.59833539e-01],
       [-6.31354749e-03],
       [ 2.94031315e-02],
       [ 5.04734926e-02],
       [ 7.79097676e-02],
       [ 1.78095326e-01],
       [ 8.58040333e-01],
       [ 6.41966105e-01],
       [-2.62417085e-02],
       [ 3.12159956e-02],
       [ 4.29883115e-02],
       [ 2.99127735e-02],
       [ 6.19680248e-02],
       [ 8.51797700e-01],
       [ 7.09193230e-01],
       [ 4.85283911e-01],
       [ 1.95433095e-01],
       [ 4.63985093e-02],
       [ 4.03217338e-02],
       [ 8.89128000e-02],
       [ 8.47105503e-01],
       [ 7.11788714e-01],
       [ 8.59575048e-02],
       [ 2.15197369e-01],
       [ 1.81025416e-02],
       [ 2.44198237e-02],
       [ 1.15701053e-02],
       [ 4.94409315e-02],
       [ 1.92484945e-01],
       [ 9.39912081e-01],
       [ 8.29560637e-01],
       [-7.99774751e-03],
       [ 1.69303585e-02],
       [ 1.79393012e-02],
       [ 3.68004516e-02],
       [ 1.94244251e-01],
       [ 7.39147305e-01],
       [ 8.22260618e-01],
       [ 3.36516351e-01],
       [ 4.16725576e-02],
       [ 6.24042265e-02],
       [ 6.37821034e-02],
       [ 3.84418368e-02],
       [ 2.05726475e-01],
       [ 6.04207754e-01],
       [ 6.05213881e-01],
       [ 7.45048374e-02],
       [ 2.63477534e-01],
       [ 2.50262856e-01],
       [ 5.06674871e-02],
       [ 2.02276614e-02],
       [ 2.73566786e-02],
       [ 2.85136551e-02],
       [ 3.16758901e-02],
       [ 1.05770826e-01],
       [ 5.49732268e-01],
       [ 7.22834229e-01],
       [ 3.20381641e-01],
       [ 2.97783285e-01],
       [ 2.38861777e-02],
       [ 3.63844074e-02],
       [ 2.14884430e-02],
       [ 1.63312368e-02],
       [ 6.67624995e-02],
       [ 4.93482709e-01],
       [ 5.17468810e-01],
       [ 2.64120579e-01],
       [ 1.64129883e-01],
       [ 2.41608411e-01],
       [ 5.63214235e-02],
       [ 1.81085244e-02],
       [ 1.55079532e-02],
       [ 2.64742076e-02],
       [ 4.14209813e-02],
       [ 7.89614320e-02],
       [ 3.38781357e-01],
       [ 5.95265687e-01],
       [ 1.06922776e-01],
       [ 1.59611925e-02],
       [ 1.88218132e-02],
       [ 2.39616744e-02],
       [ 3.45072076e-02],
       [ 4.95724790e-02],
       [ 1.26409054e-01],
       [ 3.62632513e-01],
       [ 4.19791430e-01],
       [ 3.34633768e-01],
       [ 1.82845257e-02],
       [ 2.56275274e-02],
       [ 3.84501964e-02],
       [ 3.62008177e-02],
       [ 1.04062885e-01],
       [ 4.71888959e-01],
       [ 5.11706233e-01],
       [ 1.21751055e-01],
       [ 1.48835406e-02],
       [ 2.06716619e-02],
       [ 2.86111403e-02],
       [ 7.14538470e-02],
       [ 4.05902833e-01],
       [ 4.21553016e-01],
       [ 2.31326416e-01],
       [ 9.69694369e-03],
       [ 2.73588821e-02],
       [ 4.29512113e-02],
       [ 1.55592144e-01],
       [ 5.74888229e-01],
       [ 3.71524274e-01],
       [ 3.27136517e-01],
       [ 3.56461793e-01],
       [ 4.66319919e-03],
       [ 1.36869363e-02],
       [ 2.40230672e-02],
       [ 1.40847579e-01],
       [ 5.53707898e-01],
       [ 7.83137441e-01],
       [ 2.99029797e-01],
       [ 2.73916066e-01],
       [ 9.22128931e-03],
       [ 1.98745113e-02],
       [ 2.25025229e-02],
       [ 3.22300792e-02],
       [ 2.31274843e-01],
       [ 6.05227649e-01],
       [ 4.91373777e-01],
       [ 5.63484550e-01],
       [ 2.34220654e-01],
       [ 4.24096733e-01],
       [ 5.32947361e-01],
       [ 6.26079559e-01],
       [ 2.52626628e-01],
       [ 6.03300817e-02],
       [ 1.66208297e-02],
       [ 1.74219944e-02],
       [ 6.86123371e-02],
       [ 2.18337506e-01],
       [ 7.00646877e-01],
       [ 7.91486621e-01],
       [ 5.77809930e-01],
       [ 1.59617662e-01],
       [ 7.21494853e-02],
       [-2.58884206e-03],
       [ 2.23018285e-02],
       [ 4.31244671e-02],
       [ 3.95534784e-02],
       [ 1.90419257e-01],
       [ 8.00696671e-01],
       [ 7.50531435e-01],
       [ 9.32793617e-01],
       [ 9.25752521e-01],
       [ 5.32415390e-01],
       [ 3.91156644e-01],
       [ 5.04912511e-02],
       [ 2.07555778e-02],
       [ 1.68925710e-02],
       [ 9.12708044e-03],
       [ 2.03596614e-02],
       [ 1.50816157e-01],
       [ 7.10795343e-01],
       [ 5.93061328e-01],
       [ 7.29183018e-01],
       [ 6.05227351e-01],
       [ 3.70051935e-02],
       [ 1.29001290e-02],
       [ 1.23068783e-02],
       [ 1.73375048e-02],
       [ 3.05781756e-02],
       [ 1.56242728e-01],
       [ 7.67189682e-01],
       [ 8.12701106e-01],
       [ 4.99165028e-01],
       [ 1.67628214e-01],
       [ 3.83848131e-01],
       [ 4.29763421e-02],
       [ 2.18449123e-02],
       [ 3.12881023e-02],
       [ 2.30564009e-02],
       [ 3.29400897e-02],
       [ 1.10944763e-01],
       [ 6.91913486e-01],
       [ 7.21470058e-01],
       [ 2.42348656e-01],
       [ 4.81210083e-01],
       [ 3.17515820e-01],
       [ 7.38869980e-03],
       [ 2.42474098e-02],
       [ 3.79202142e-02],
       [ 3.24380212e-02],
       [ 1.07894793e-01],
       [ 6.55851841e-01],
       [ 7.40608871e-01],
       [ 1.61922827e-01],
       [ 1.39150932e-01],
       [ 8.01791064e-03],
       [ 1.71070825e-02],
       [ 1.71088446e-02],
       [ 3.42841633e-02],
       [ 1.50949284e-01],
       [ 5.79882145e-01],
       [ 6.58520699e-01],
       [ 7.11739302e-01],
       [ 1.09670728e-01],
       [-4.81167808e-03],
       [ 9.57470201e-03],
       [ 1.93741024e-02],
       [ 2.70898566e-02],
       [ 2.58695036e-01],
       [ 7.45760977e-01],
       [ 6.22778833e-01],
       [ 5.99758744e-01],
       [ 4.47252154e-01],
       [-8.08811560e-03],
       [ 1.07501671e-02],
       [ 2.54733302e-02],
       [ 1.96881831e-01],
       [ 7.30055809e-01],
       [ 7.08941221e-01],
       [ 4.98245358e-01],
       [ 4.16473448e-01],
       [ 2.01028548e-02],
       [ 2.19241325e-02],
       [ 4.23364863e-02],
       [ 1.67186365e-01],
       [ 6.63600981e-01],
       [ 8.84477556e-01],
       [ 2.74203360e-01],
       [ 6.52186573e-05],
       [ 3.90936583e-02],
       [ 3.17500718e-02],
       [ 2.58777849e-02],
       [ 2.70932198e-01],
       [ 6.92427397e-01],
       [ 7.92464435e-01],
       [ 2.24522203e-01],
       [ 7.10041821e-03],
       [ 4.75736335e-02],
       [ 2.42971797e-02],
       [ 1.80705413e-02],
       [ 2.17031300e-01],
       [ 7.00373411e-01],
       [ 8.08151960e-01],
       [ 5.24137139e-01],
       [ 1.36062931e-02],
       [ 3.66130397e-02],
       [ 3.76509838e-02],
       [ 1.47310466e-01],
       [ 6.68689549e-01],
       [ 7.17924714e-01],
       [ 4.39663440e-01],
       [ 4.26965535e-01],
       [ 2.76906509e-02],
       [ 2.39969995e-02],
       [ 3.50678749e-02],
       [ 2.70740241e-02],
       [ 2.29101121e-01],
       [ 7.47867107e-01],
       [ 6.34466946e-01],
       [ 8.40582371e-01],
       [ 2.35016756e-02],
       [ 2.63652038e-02],
       [ 1.79825015e-02],
       [ 2.24386584e-02],
       [ 1.01379544e-01],
       [ 7.82273471e-01],
       [ 6.16803348e-01],
       [ 8.69195521e-01],
       [ 7.45472074e-01],
       [ 2.58161128e-01],
       [ 1.69271585e-02],
       [ 1.38075091e-02],
       [ 3.25805396e-02],
       [ 4.33980748e-02],
       [ 1.57463223e-01],
       [ 6.43864036e-01],
       [ 8.09772551e-01],
       [ 6.58749223e-01],
       [ 7.58245587e-01],
       [ 2.83847675e-02],
       [ 2.24900749e-02],
       [ 4.93485332e-02],
       [ 1.73645690e-02],
       [ 1.48790061e-01],
       [ 7.29882896e-01],
       [ 7.92707324e-01],
       [ 5.83320975e-01],
       [ 2.05051571e-01],
       [-2.74099782e-03],
       [ 5.08746654e-02],
       [ 6.07170835e-02],
       [ 8.64176154e-02],
       [ 7.22554386e-01],
       [ 7.66144991e-01],
       [ 3.66192609e-01],
       [ 3.57155591e-01],

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
15910         0.0           0.0           0.0           NaN
15919         0.0     45.085922           0.0           NaN
15920      2324.0   1747.559524   2931.155236           NaN
15921     16384.0  15282.644011  15534.328419           NaN
15922     25212.0  24396.229156  25499.346937           NaN
...           ...           ...           ...           ...
18273      7356.0   6918.407231   7148.104256   8764.482422
18274     17638.0  19779.365821  21016.223316  22835.416016
18275     23339.0  24030.007366  23687.023299  20082.384766
18276     26323.0  24112.268947  23126.102053    555.459778
18286         0.0           0.0           0.0   3977.639893

[832 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,601 (1.55 MB)

 Trainable params: 405,345 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 621s 568ms/step - loss: 0.0951 - mae: 0.2865 - val_loss: 0.0955 - val_mae: 0.2996
Epoch 2/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 299s 503ms/step - loss: 0.0844 - mae: 0.2689 - val_loss: 0.0802 - val_mae: 0.2824
Epoch 3/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 258s 482ms/step - loss: 0.0706 - mae: 0.2486 - val_loss: 0.0695 - val_mae: 0.2714
Epoch 4/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 277s 498ms/step - loss: 0.0610 - mae: 0.2284 - val_loss: 0.0642 - val_mae: 0.2531
Epoch 5/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 253s 465ms/step - loss: 0.0550 - mae: 0.2202 - val_loss: 0.0506 - val_mae: 0.2171
Epoch 6/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 251s 429ms/step - loss: 0.0464 - mae: 0.2018 - val_loss: 0.0465 - val_mae: 0.2198
Epoch 7/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 262s 417ms/step - loss: 0.0437 - mae: 0.1908 - val_loss: 0.0406 - val_mae: 0.1949
Epoch 8/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 182s 367ms/step - loss: 0.0368 - mae: 0.1761 - val_loss: 0.0344 - val_mae: 0.1782
Epoch 9/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 208s 419ms/step - loss: 0.0384 - mae: 0.1766 - val_loss: 0.0347 - val_mae: 0.1894
Epoch 10/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 233s 470ms/step - loss: 0.0341 - mae: 0.1688 - val_loss: 0.0311 - val_mae: 0.1706
Epoch 11/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 277s 489ms/step - loss: 0.0307 - mae: 0.1559 - val_loss: 0.0335 - val_mae: 0.1769
Epoch 12/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 264s 484ms/step - loss: 0.0298 - mae: 0.1537 - val_loss: 0.0301 - val_mae: 0.1703
Epoch 13/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 269s 487ms/step - loss: 0.0306 - mae: 0.1590 - val_loss: 0.0302 - val_mae: 0.1647
Epoch 14/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 251s 452ms/step - loss: 0.0271 - mae: 0.1473 - val_loss: 0.0316 - val_mae: 0.1676
Epoch 15/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 260s 439ms/step - loss: 0.0257 - mae: 0.1420 - val_loss: 0.0324 - val_mae: 0.1709
Epoch 16/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 260s 422ms/step - loss: 0.0281 - mae: 0.1495 - val_loss: 0.0301 - val_mae: 0.1581
Epoch 17/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 227s 459ms/step - loss: 0.0240 - mae: 0.1376 - val_loss: 0.0311 - val_mae: 0.1618
Epoch 18/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 252s 431ms/step - loss: 0.0227 - mae: 0.1355 - val_loss: 0.0344 - val_mae: 0.1605
Epoch 19/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 217s 441ms/step - loss: 0.0236 - mae: 0.1364 - val_loss: 0.0321 - val_mae: 0.1629
Epoch 20/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 250s 405ms/step - loss: 0.0229 - mae: 0.1366 - val_loss: 0.0378 - val_mae: 0.1731
Epoch 21/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 200s 404ms/step - loss: 0.0232 - mae: 0.1354 - val_loss: 0.0312 - val_mae: 0.1567
Epoch 22/100
480/480 ━━━━━━━━━━━━━━━━━━━━ 221s 434ms/step - loss: 0.0222 - mae: 0.1331 - val_loss: 0.0308 - val_mae: 0.1553

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

24/25 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

25/25 ━━━━━━━━━━━━━━━━━━━━ 64s 1s/step

array([[0.675473  ],
       [0.6923699 ],
       [0.6739727 ],
       [0.66142535],
       [0.6472259 ],
       [0.51986164],
       [0.5738336 ],
       [0.70059645],
       [0.76306796],
       [0.6090367 ],
       [0.3413704 ],
       [0.15909202],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22674353],
       [0.63749945],
       [0.76000655],
       [0.26309434],
       [0.1428859 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.21698305],
       [0.6726611 ],
       [0.55174243],
       [0.18023853],
       [0.150624  ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22060843],
       [0.64515764],
       [0.73153126],
       [0.38481566],
       [0.17520373],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2770691 ],
       [0.7566146 ],
       [0.6103221 ],
       [0.14495715],
       [0.        ],
       [0.        ],
       [0.30897483],
       [0.8069347 ],
       [0.80867124],
       [0.14803287],
       [0.        ],
       [0.        ],
       [0.3272774 ],
       [0.7443351 ],
       [0.66625917],
       [0.06622364],
       [0.        ],
       [0.        ],
       [0.32890102],
       [0.7737793 ],
       [0.4098424 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.38568366],
       [0.8714849 ],
       [0.7221168 ],
       [0.13019454],
       [0.        ],
       [0.        ],
       [0.38124713],
       [0.78089285],
       [0.78907573],
       [0.463917  ],
       [0.22519757],
       [0.4793121 ],
       [0.11492659],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23896433],
       [0.60125506],
       [0.7927921 ],
       [0.7635629 ],
       [0.76604533],
       [0.63752973],
       [0.6354959 ],
       [0.38302395],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.21325426],
       [0.6598295 ],
       [0.6260613 ],
       [0.6512291 ],
       [0.6596683 ],
       [0.6557356 ],
       [0.6175772 ],
       [0.67441756],
       [0.7080662 ],
       [0.44487163],
       [0.37731948],
       [0.20202182],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2019625 ],
       [0.6145814 ],
       [0.70444477],
       [0.4778866 ],
       [0.15504432],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19639003],
       [0.5384387 ],
       [0.6656023 ],
       [0.50194955],
       [0.05869255],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24896085],
       [0.52518964],
       [0.59798044],
       [0.28458875],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23003235],
       [0.61460626],
       [0.57596123],
       [0.36304423],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.17865252],
       [0.56911004],
       [0.5911165 ],
       [0.4058416 ],
       [0.42990497],
       [0.22675882],
       [0.1806257 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28822252],
       [0.5889146 ],
       [0.62497866],
       [0.44304997],
       [0.33411536],
       [0.30864444],
       [0.2732053 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22083189],
       [0.5859432 ],
       [0.59423006],
       [0.3603822 ],
       [0.06553839],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2131364 ],
       [0.5240629 ],
       [0.59730744],
       [0.19734335],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1750809 ],
       [0.6287328 ],
       [0.6646762 ],
       [0.19352035],
       [0.18613857],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.17839389],
       [0.68350244],
       [0.63332653],
       [0.2479044 ],
       [0.15822078],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1760741 ],
       [0.6481541 ],
       [0.74151015],
       [0.51657444],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.25448677],
       [0.64370465],
       [0.6370449 ],
       [0.20060478],
       [0.18566774],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1244877 ],
       [0.3872855 ],
       [0.51315784],
       [0.5468888 ],
       [0.26395282],
       [0.3524005 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.14519042],
       [0.59455025],
       [0.68261427],
       [0.7134881 ],
       [0.7767084 ],
       [0.7924986 ],
       [0.9207065 ],
       [0.8688324 ],
       [0.85525656],
       [0.73593783],
       [0.64881635],
       [0.63069713],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.10980211],
       [0.6136406 ],
       [0.7360101 ],
       [0.7139138 ],
       [0.56061447],
       [0.71534145],
       [0.6266581 ],
       [0.12705544],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1258621 ],
       [0.6417805 ],
       [0.7299226 ],
       [0.5557555 ],
       [0.17512816],
       [0.71680915],
       [0.6797019 ],
       [0.5688797 ],
       [0.1060629 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.16135359],
       [0.717217  ],
       [0.6457403 ],
       [0.1577032 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23088716],
       [0.73793477],
       [0.79842615],
       [0.5376884 ],
       [0.16748436],
       [0.16269685],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24928544],
       [0.7681196 ],
       [0.65799665],
       [0.15650317],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22427647],
       [0.78518367],
       [0.746526  ],
       [0.16005358],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22286753],
       [0.7970891 ],
       [0.7328421 ],
       [0.14748268],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23195003],
       [0.7051577 ],
       [0.77811545],
       [0.14922364],
       [0.        ],
       [0.        ],
       [0.28000697],
       [0.7553243 ],
       [0.75285256],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3259523 ],
       [0.80412555],
       [0.8434703 ],
       [0.13555726],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.27774414],
       [0.79063016],
       [0.92356676],
       [0.3618155 ],
       [0.        ],
       [0.37658185],
       [0.7211143 ],
       [0.7099114 ],
       [0.04267638],
       [0.        ],
       [0.31580767],
       [0.657811  ],
       [0.6773395 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3442687 ],
       [0.64123935],
       [0.7958212 ],
       [0.07890552],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2617299 ],
       [0.74556196],
       [0.7264465 ],
       [0.13620292],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24555792],
       [0.7531476 ],
       [0.77349854],
       [0.64941883],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2847056 ],
       [0.7386639 ],
       [0.8317063 ],
       [0.22454974],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24405022],
       [0.69080883],
       [0.74218655],
       [0.55054766],
       [0.38079885],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22645654],
       [0.6891123 ],
       [0.8050537 ],
       [0.1654677 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.17722152],
       [0.6968181 ],
       [0.80490065],
       [0.63277817],
       [0.26796672],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2627625 ],
       [0.6638912 ],
       [0.7916944 ],
       [0.36178327],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2560295 ],
       [0.6690576 ],
       [0.7828213 ],
       [0.54161996],
       [0.40467516],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.31936398],
       [0.70918256],
       [0.7831422 ],
       [0.42314255],
       [0.24721542],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.32187325],
       [0.70520246],
       [0.8180463 ],
       [0.3534941 ],
       [0.2702997 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.3388462 ],
       [0.7422788 ],
       [0.78885615],
       [0.6131958 ],
       [0.26625314],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.30245256],
       [0.72905684],
       [0.82455564],
       [0.16473931],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23032124],
       [0.645642  ],
       [0.6378393 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23025547],
       [0.70402765],
       [0.6934743 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.23213457],
       [0.73322004],
       [0.7995789 ],
       [0.66055685],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.27232105],
       [0.8250034 ],
       [0.7716067 ],
       [0.15330498],
       [0.        ],
       [0.        ],
       [0.28379217],
       [0.6843385 ],
       [0.6560203 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.25177118],
       [0.72727454],
       [0.62066066],
       [0.08178686],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24858107],
       [0.69636893],
       [0.73899066],
       [0.13858086],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.25354686],
       [0.80907017],
       [0.76882035],
       [0.09121997],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.25288504],
       [0.72777313],
       [0.7512089 ],
       [0.5127364 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.27482498],
       [0.6938362 ],
       [0.79807436],
       [0.14840202],
       [0.16729456],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22277506],
       [0.67577827],
       [0.71902406],
       [0.15563026],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2157709 ],
       [0.63024306],
       [0.62804323],
       [0.5117408 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28652093],
       [0.40485787],
       [0.5097454 ],
       [0.5248539 ],
       [0.04115655],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.04571171],
       [0.1264755 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.5145733 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.2938258 ],
       [0.17596574],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.42034432],
       [0.4731331 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19451244],
       [0.5080652 ],
       [0.6063741 ],
       [0.15608183],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.16184884],
       [0.5626045 ],
       [0.60332775],
       [0.41738966],
       [0.2947545 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28540418],
       [0.6276712 ],
       [0.80295634],
       [0.41772485],
       [0.3560448 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.18796954],
       [0.52267516],
       [0.75939345],
       [0.5938747 ],
       [0.36013684],
       [0.3618082 ],
       [0.8109743 ],
       [0.663048  ],
       [0.30883837],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.22296342],
       [0.60148275],
       [0.8083901 ],
       [0.55241877],
       [0.24370311],
       [0.29031432],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.17017147],
       [0.56810105],
       [0.7498406 ],
       [0.75356597],
       [0.65978885],
       [0.25011274],
       [0.3996241 ],
       [0.24118613],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1619225 ],
       [0.5412584 ],
       [0.6992074 ],
       [0.6629971 ],
       [0.46112195],
       [0.16121489],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.16091761],
       [0.5284127 ],
       [0.81465393],
       [0.41054776],
       [0.19831523],
       [0.27667332],
       [0.18573481],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1829464 ],
       [0.57310736],
       [0.77797616],
       [0.5539588 ],
       [0.5072747 ],
       [0.2184272 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.14152382],
       [0.49181625],
       [0.7297039 ],
       [0.19500749],
       [0.17913881],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.21507451],
       [0.58261454],
       [0.8107283 ],
       [0.6524819 ],
       [0.26432005],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28304008],
       [0.6603701 ],
       [0.7788312 ],
       [0.710811  ],
       [0.2719385 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28688124],
       [0.6466958 ],
       [0.7634235 ],
       [0.6759436 ],
       [0.19214769],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28137094],
       [0.6261894 ],
       [0.798536  ],
       [0.20859686],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24944465],
       [0.5620029 ],
       [0.7564655 ],
       [0.15723576],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.24736132],
       [0.5550064 ],
       [0.80447936],
       [0.26509055],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.17609647],
       [0.5910703 ],
       [0.6983597 ],
       [0.5570464 ],
       [0.16607632],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.17334038],
       [0.55305743],
       [0.7257767 ],
       [0.42077258],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.18365024],
       [0.5353185 ],
       [0.6568801 ],
       [0.62145585],
       [0.38890147],
       [0.14969066],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1381079 ],
       [0.39747944],
       [0.56476855],
       [0.5614644 ],
       [0.40092555],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.21274622],
       [0.57270575],
       [0.7443366 ],
       [0.3249177 ],
       [0.18194133],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.1719655 ],
       [0.6067095 ],
       [0.7504156 ],
       [0.2627383 ],
       [0.01249423],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.19309591],
       [0.6332675 ],
       [0.77938485],
       [0.34126088],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.15973689],
       [0.56397927],
       [0.68634695],
       [0.15987897],
       [0.03775905]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
15910         0.0           0.0           0.0           NaN           NaN
15919         0.0     45.085922           0.0           NaN           NaN
15920      2324.0   1747.559524   2931.155236           NaN           NaN
15921     16384.0  15282.644011  15534.328419           NaN           NaN
15922     25212.0  24396.229156  25499.346937           NaN           NaN
...           ...           ...           ...           ...           ...
18273      7356.0   6918.407231   7148.104256   8764.482422   4792.106445
18274     17638.0  19779.365821  21016.223316  22835.416016  16919.378906
18275     23339.0  24030.007366  23687.023299  20082.384766  20590.408203
18276     26323.0  24112.268947  23126.102053    555.459778   4796.369141
18286         0.0           0.0           0.0   3977.639893   1132.771362

[832 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

16042    17374.0
16043    17555.0
16044    18217.0
16045    18119.0
16046    17833.0
          ...
18273     7356.0
18274    17638.0
18275    23339.0
18276    26323.0
18286        0.0
Name: Generación, Length: 784, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 6)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      1,600 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 473,281 (1.81 MB)

 Trainable params: 473,281 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 321s 278ms/step - loss: 1.0836 - mae: 0.2749 - val_loss: 0.5556 - val_mae: 0.3015
Epoch 2/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 54s 198ms/step - loss: 0.4411 - mae: 0.2683 - val_loss: 0.2421 - val_mae: 0.2438
Epoch 3/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 85s 194ms/step - loss: 0.1782 - mae: 0.1758 - val_loss: 0.1269 - val_mae: 0.2041
Epoch 4/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 81s 180ms/step - loss: 0.0906 - mae: 0.1490 - val_loss: 0.0866 - val_mae: 0.1901
Epoch 5/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 45s 163ms/step - loss: 0.0622 - mae: 0.1425 - val_loss: 0.0750 - val_mae: 0.1828
Epoch 6/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 50s 183ms/step - loss: 0.0478 - mae: 0.1299 - val_loss: 0.0657 - val_mae: 0.1756
Epoch 7/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 84s 173ms/step - loss: 0.0441 - mae: 0.1291 - val_loss: 0.0618 - val_mae: 0.1720
Epoch 8/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 39s 141ms/step - loss: 0.0408 - mae: 0.1256 - val_loss: 0.0567 - val_mae: 0.1637
Epoch 9/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 53s 187ms/step - loss: 0.0341 - mae: 0.1159 - val_loss: 0.0539 - val_mae: 0.1593
Epoch 10/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 89s 188ms/step - loss: 0.0354 - mae: 0.1195 - val_loss: 0.0590 - val_mae: 0.1691
Epoch 11/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 84s 182ms/step - loss: 0.0322 - mae: 0.1129 - val_loss: 0.0546 - val_mae: 0.1551
Epoch 12/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 87s 181ms/step - loss: 0.0304 - mae: 0.1103 - val_loss: 0.0570 - val_mae: 0.1624
Epoch 13/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 90s 190ms/step - loss: 0.0304 - mae: 0.1101 - val_loss: 0.0532 - val_mae: 0.1552
Epoch 14/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 66s 111ms/step - loss: 0.0301 - mae: 0.1112 - val_loss: 0.0498 - val_mae: 0.1507
Epoch 15/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 67s 205ms/step - loss: 0.0279 - mae: 0.1067 - val_loss: 0.0488 - val_mae: 0.1521
Epoch 16/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 80s 171ms/step - loss: 0.0273 - mae: 0.1040 - val_loss: 0.0571 - val_mae: 0.1602
Epoch 17/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 49s 180ms/step - loss: 0.0294 - mae: 0.1092 - val_loss: 0.0535 - val_mae: 0.1499
Epoch 18/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 76s 145ms/step - loss: 0.0275 - mae: 0.1039 - val_loss: 0.0522 - val_mae: 0.1487
Epoch 19/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 55s 185ms/step - loss: 0.0243 - mae: 0.0986 - val_loss: 0.0510 - val_mae: 0.1480
Epoch 20/50
240/240 ━━━━━━━━━━━━━━━━━━━━ 73s 138ms/step - loss: 0.0257 - mae: 0.0999 - val_loss: 0.0511 - val_mae: 0.1487

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

25/25 ━━━━━━━━━━━━━━━━━━━━ 44s 853ms/step

array([[ 6.99300587e-01],
       [ 8.07209790e-01],
       [ 6.67223036e-01],
       [ 7.34536111e-01],
       [ 7.64608443e-01],
       [ 6.22417033e-01],
       [ 5.80582619e-01],
       [ 6.99197114e-01],
       [ 7.20320761e-01],
       [ 6.99465811e-01],
       [ 3.96431237e-01],
       [ 2.62478411e-01],
       [ 2.28605196e-02],
       [ 1.31486747e-02],
       [ 1.99984927e-02],
       [ 3.18670839e-01],
       [ 7.41774023e-01],
       [ 8.22249591e-01],
       [ 3.20222348e-01],
       [ 3.06693166e-01],
       [ 1.41302105e-02],
       [-1.95833389e-03],
       [ 8.96332599e-03],
       [ 3.17754418e-01],
       [ 7.32415378e-01],
       [ 7.12480664e-01],
       [ 1.60279363e-01],
       [ 2.02087671e-01],
       [ 1.03992913e-02],
       [-8.84965993e-04],
       [ 1.08201690e-02],
       [ 3.25708300e-01],
       [ 7.29987204e-01],
       [ 7.45371461e-01],
       [ 2.97878087e-01],
       [ 2.91646183e-01],
       [ 2.63324380e-03],
       [ 1.11641269e-02],
       [ 1.41802691e-02],
       [ 3.98894459e-01],
       [ 7.63601482e-01],
       [ 6.82711720e-01],
       [ 5.89291751e-02],
       [-2.94207036e-03],
       [ 3.63635719e-02],
       [ 3.76988083e-01],
       [ 7.58098185e-01],
       [ 7.97601461e-01],
       [ 6.50948584e-02],
       [ 2.48631276e-03],
       [ 3.15888375e-02],
       [ 3.75962585e-01],
       [ 7.34087884e-01],
       [ 7.19717801e-01],
       [ 5.47650829e-02],
       [-7.69553706e-03],
       [ 2.36485843e-02],
       [ 4.03262883e-01],
       [ 7.73597896e-01],
       [ 6.31863773e-01],
       [ 2.72046402e-02],
       [-4.39851172e-03],
       [ 4.76132482e-02],
       [ 4.68964666e-01],
       [ 8.38183880e-01],
       [ 7.68710792e-01],
       [ 5.51808029e-02],
       [-1.93448365e-03],
       [ 4.07523438e-02],
       [ 4.47449476e-01],
       [ 7.76111424e-01],
       [ 7.89931118e-01],
       [ 2.66864330e-01],
       [ 2.35932797e-01],
       [ 5.23008525e-01],
       [ 2.57956386e-01],
       [ 4.85144183e-03],
       [ 5.84691297e-03],
       [ 1.64058972e-02],
       [ 2.79070526e-01],
       [ 6.40612006e-01],
       [ 8.08735669e-01],
       [ 6.62665427e-01],
       [ 7.19595850e-01],
       [ 6.88090384e-01],
       [ 6.83903575e-01],
       [ 4.80159372e-01],
       [ 5.43446466e-02],
       [ 2.40834244e-03],
       [ 3.03592533e-05],
       [ 1.16144400e-02],
       [ 2.36212701e-01],
       [ 6.63340390e-01],
       [ 7.13342726e-01],
       [ 6.08600616e-01],
       [ 6.88033342e-01],
       [ 7.30391562e-01],
       [ 6.77017152e-01],
       [ 6.88968122e-01],
       [ 7.30127335e-01],
       [ 5.51358998e-01],
       [ 3.60162616e-01],
       [ 2.61776745e-01],
       [ 1.60390139e-01],
       [ 1.38603654e-02],
       [ 6.85886014e-03],
       [ 1.90603063e-02],
       [ 2.68823355e-01],
       [ 6.86944067e-01],
       [ 7.13651121e-01],
       [ 3.75291258e-01],
       [ 2.82969207e-01],
       [ 1.05484389e-01],
       [ 6.24265894e-03],
       [ 4.77257371e-03],
       [ 1.96765792e-02],
       [ 2.55515426e-01],
       [ 6.43038630e-01],
       [ 6.52942300e-01],
       [ 3.35597873e-01],
       [ 1.87940359e-01],
       [ 1.42734647e-02],
       [-1.26259774e-03],
       [ 8.85363761e-03],
       [ 2.50983685e-01],
       [ 5.99746346e-01],
       [ 6.43534899e-01],
       [ 2.61669099e-01],
       [ 9.18617845e-03],
       [ 5.78859821e-04],
       [ 6.88988157e-03],
       [ 2.13435829e-01],
       [ 6.39883816e-01],
       [ 6.56969845e-01],
       [ 2.90892988e-01],
       [ 1.06593827e-02],
       [ 5.29067591e-03],
       [ 1.05598532e-02],
       [ 2.71974266e-01],
       [ 6.32730246e-01],
       [ 6.16266668e-01],
       [ 2.90913552e-01],
       [ 3.54744345e-01],
       [ 2.58141726e-01],
       [ 1.17689125e-01],
       [ 3.27030942e-02],
       [ 1.12799350e-02],
       [ 6.71057031e-03],
       [ 1.37593802e-02],
       [ 2.01068908e-01],
       [ 6.25564814e-01],
       [ 6.42782867e-01],
       [ 3.06966275e-01],
       [ 3.77281755e-01],
       [ 2.98386157e-01],
       [ 1.13515869e-01],
       [ 6.30460978e-02],
       [ 5.15468605e-03],
       [-9.08078626e-04],
       [ 7.76576251e-03],
       [ 2.05613583e-01],
       [ 6.36620462e-01],
       [ 6.51790559e-01],
       [ 2.41202891e-01],
       [ 2.22950816e-01],
       [ 8.29762593e-03],
       [-7.85785168e-03],
       [ 5.55517152e-03],
       [ 2.24559695e-01],
       [ 6.16942585e-01],
       [ 6.42755508e-01],
       [ 8.72688070e-02],
       [ 1.11972494e-02],
       [ 1.29175745e-03],
       [ 4.87069786e-03],
       [ 2.69806534e-01],
       [ 6.86331868e-01],
       [ 7.27336228e-01],
       [ 1.18101321e-01],
       [ 1.06430307e-01],
       [ 9.75470059e-03],
       [-4.74030431e-03],
       [ 7.99636636e-03],
       [ 2.49792993e-01],
       [ 6.91033304e-01],
       [ 7.06485569e-01],
       [ 1.90072417e-01],
       [ 1.66073769e-01],
       [ 7.40890019e-03],
       [-2.69184355e-03],
       [ 8.93644243e-03],
       [ 2.92074233e-01],
       [ 7.33876765e-01],
       [ 7.46364832e-01],
       [ 3.54912341e-01],
       [ 7.40338266e-02],
       [ 1.39165130e-02],
       [ 9.50347446e-03],
       [ 1.87697262e-02],
       [ 3.26886266e-01],
       [ 6.98330700e-01],
       [ 6.40414655e-01],
       [ 2.12768108e-01],
       [ 2.57372171e-01],
       [ 2.23999619e-01],
       [ 2.91397609e-03],
       [ 3.82195786e-03],
       [ 1.29809417e-02],
       [ 2.22363889e-01],
       [ 5.63452423e-01],
       [ 6.68950975e-01],
       [ 6.15582764e-01],
       [ 4.79989439e-01],
       [ 5.27710736e-01],
       [ 3.77507210e-02],
       [-9.55520570e-03],
       [-6.02454878e-03],
       [ 8.87953117e-03],
       [ 1.70679688e-01],
       [ 5.94321191e-01],
       [ 7.29281425e-01],
       [ 6.48820519e-01],
       [ 7.06708610e-01],
       [ 7.63040721e-01],
       [ 8.00199389e-01],
       [ 7.98148513e-01],
       [ 7.14696646e-01],
       [ 6.39717221e-01],
       [ 5.53865314e-01],
       [ 5.54611623e-01],
       [ 6.84184432e-02],
       [ 2.12211721e-03],
       [-2.30885856e-03],
       [ 5.21877594e-03],
       [ 2.31383294e-01],
       [ 6.62319124e-01],
       [ 7.92677224e-01],
       [ 6.33615792e-01],
       [ 5.87948859e-01],
       [ 6.53843582e-01],
       [ 6.17149770e-01],
       [ 7.28000626e-02],
       [ 6.11870736e-03],
       [-2.83615664e-04],
       [ 1.14491079e-02],
       [ 2.03989923e-01],
       [ 6.57909453e-01],
       [ 7.73860693e-01],
       [ 4.56438005e-01],
       [ 2.49325752e-01],
       [ 5.47259867e-01],
       [ 6.32211745e-01],
       [ 4.01078314e-01],
       [ 9.18856189e-02],
       [ 2.42851209e-03],
       [-2.50242185e-03],
       [ 1.00786965e-02],
       [ 2.63126880e-01],
       [ 6.90642178e-01],
       [ 7.12816596e-01],
       [ 1.08641781e-01],
       [ 2.83253007e-03],
       [ 1.22043621e-02],
       [ 1.50424503e-02],
       [ 3.83635163e-01],
       [ 7.38133192e-01],
       [ 7.84088433e-01],
       [ 4.15355533e-01],
       [ 2.75460631e-01],
       [ 1.38283700e-01],
       [ 1.03073418e-02],
       [-5.47040533e-03],
       [ 1.44205531e-02],
       [ 3.00742000e-01],
       [ 7.72238851e-01],
       [ 7.07787216e-01],
       [ 8.73364359e-02],
       [ 2.96619069e-03],
       [ 1.32674910e-02],
       [ 1.23953717e-02],
       [ 3.89194876e-01],
       [ 7.79691875e-01],
       [ 7.79956996e-01],
       [ 9.72464159e-02],
       [ 2.62441952e-03],
       [ 1.19509157e-02],
       [ 1.57187227e-02],
       [ 3.81746680e-01],
       [ 8.00192893e-01],
       [ 7.66825020e-01],
       [ 9.30147246e-02],
       [ 1.90645084e-03],
       [ 1.03891417e-02],
       [ 1.39409956e-02],
       [ 4.09380943e-01],
       [ 7.55827963e-01],
       [ 8.25949609e-01],
       [ 1.61881179e-01],
       [-1.04819424e-03],
       [ 3.05370539e-02],
       [ 3.79118204e-01],
       [ 7.86193490e-01],
       [ 8.09331477e-01],
       [ 5.52021265e-02],
       [-3.62496264e-03],
       [ 2.85981838e-02],
       [ 3.75478804e-01],
       [ 8.00925016e-01],
       [ 8.52557242e-01],
       [ 7.48381242e-02],
       [ 1.72670558e-03],
       [ 6.76154718e-03],
       [ 1.45744430e-02],
       [ 4.16384667e-01],
       [ 8.24403167e-01],
       [ 9.72419381e-01],
       [ 4.92961347e-01],
       [ 2.27057338e-02],
       [ 3.37062865e-01],
       [ 7.34767854e-01],
       [ 6.74008012e-01],
       [ 4.55425829e-02],
       [ 1.32017154e-02],
       [ 3.44387025e-01],
       [ 7.88577437e-01],
       [ 5.98067105e-01],
       [ 2.42359694e-02],
       [-7.37144426e-03],
       [ 2.70110331e-02],
       [ 3.43822092e-01],
       [ 6.89735591e-01],
       [ 7.35034406e-01],
       [ 5.65449968e-02],
       [-5.24660572e-04],
       [ 9.37048346e-03],
       [ 1.15414895e-02],
       [ 3.66235584e-01],
       [ 7.15769053e-01],
       [ 7.48745739e-01],
       [ 1.01039164e-01],
       [ 1.51630864e-03],
       [ 1.63721666e-02],
       [ 2.01143660e-02],
       [ 4.00243104e-01],
       [ 7.89510489e-01],
       [ 8.16960692e-01],
       [ 4.95499045e-01],
       [ 5.70775941e-03],
       [ 9.31983814e-03],
       [ 2.16188170e-02],
       [ 4.01757419e-01],
       [ 8.03066611e-01],
       [ 8.33370864e-01],
       [ 3.21983784e-01],
       [ 6.50169402e-02],
       [ 1.67384744e-02],
       [ 3.95584665e-03],
       [ 1.94353983e-02],
       [ 3.24091136e-01],
       [ 7.46906459e-01],
       [ 7.61658490e-01],
       [ 4.25247461e-01],
       [ 4.48969573e-01],
       [ 6.37728944e-02],
       [ 6.69628382e-03],
       [-2.40089372e-04],
       [ 1.95557289e-02],
       [ 3.28232914e-01],
       [ 7.33745039e-01],
       [ 7.57493019e-01],
       [ 1.97548181e-01],
       [ 9.71420202e-03],
       [ 8.32271017e-03],
       [ 9.93737951e-03],
       [ 3.52231294e-01],
       [ 7.39035487e-01],
       [ 8.18672478e-01],
       [ 4.62512553e-01],
       [ 2.74847776e-01],
       [ 3.45782749e-02],
       [ 8.94035213e-03],
       [-4.61839885e-03],
       [ 1.43699599e-02],
       [ 3.04852635e-01],
       [ 6.95482552e-01],
       [ 7.46356606e-01],
       [ 2.94281572e-01],
       [ 5.48613034e-02],
       [ 7.73821585e-03],
       [-2.88785528e-03],
       [ 1.34701384e-02],
       [ 3.40318829e-01],
       [ 7.54308343e-01],
       [ 7.62981355e-01],
       [ 3.61638814e-01],
       [ 3.73162419e-01],
       [ 3.48762497e-02],
       [ 2.57141143e-03],
       [-2.26633996e-03],
       [ 2.02334784e-02],
       [ 3.51096541e-01],
       [ 7.21882164e-01],
       [ 7.55872607e-01],
       [ 3.24002385e-01],
       [ 2.92600244e-01],
       [-3.00129317e-03],
       [ 9.07844305e-03],
       [ 1.11813294e-02],
       [ 3.85853916e-01],
       [ 7.33346164e-01],
       [ 7.65508115e-01],
       [ 2.38517255e-01],
       [ 2.75324494e-01],
       [ 2.90154479e-04],
       [ 1.24870632e-02],
       [ 1.47788506e-02],
       [ 4.04474854e-01],
       [ 7.83808231e-01],
       [ 7.85323203e-01],
       [ 4.03286129e-01],
       [ 2.41570234e-01],
       [ 3.31050716e-04],
       [ 8.90948717e-03],
       [ 1.10241426e-02],
       [ 3.51960868e-01],
       [ 7.64778554e-01],
       [ 7.95290053e-01],
       [ 1.26861721e-01],
       [ 2.14121081e-02],
       [ 2.84398533e-03],
       [ 1.24965608e-03],
       [ 9.70496424e-03],
       [ 3.39876741e-01],
       [ 7.40906060e-01],
       [ 7.63233900e-01],
       [ 6.17783070e-02],
       [-5.73953055e-03],
       [ 1.61443595e-02],
       [ 2.06848271e-02],
       [ 3.73104900e-01],
       [ 7.70421088e-01],
       [ 8.04124534e-01],
       [ 8.47183987e-02],
       [ 1.95196457e-03],
       [ 1.86724365e-02],
       [ 2.64411122e-02],
       [ 4.06665146e-01],
       [ 7.51105070e-01],
       [ 8.29539955e-01],
       [ 5.18731475e-01],
       [ 3.99282388e-03],
       [ 1.01023670e-02],
       [ 2.33440604e-02],
       [ 4.05186623e-01],
       [ 8.78155768e-01],
       [ 8.40878785e-01],
       [ 1.89264417e-01],
       [-1.05792098e-03],
       [ 3.29584144e-02],
       [ 3.73078972e-01],
       [ 7.34340608e-01],
       [ 7.91118383e-01],
       [ 5.99204749e-02],
       [-6.40674494e-04],
       [ 1.32994242e-02],
       [ 1.78034008e-02],
       [ 3.84445876e-01],
       [ 7.49997556e-01],
       [ 7.36303031e-01],
       [ 9.91565138e-02],
       [ 3.73641402e-03],
       [ 1.84132159e-02],
       [ 2.26370133e-02],
       [ 4.03934628e-01],
       [ 7.50301659e-01],
       [ 7.98173130e-01],
       [ 1.69830114e-01],
       [ 3.26885656e-03],
       [ 2.12307647e-02],
       [ 2.64311507e-02],
       [ 4.40557688e-01],
       [ 8.26517522e-01],
       [ 8.14030111e-01],
       [ 1.01054788e-01],
       [ 2.92509980e-03],
       [ 2.08647233e-02],
       [ 2.48575080e-02],
       [ 4.51471478e-01],
       [ 7.88805425e-01],
       [ 7.96612203e-01],
       [ 3.89310747e-01],
       [ 1.18816514e-02],
       [ 1.45950243e-02],
       [ 2.29872223e-02],
       [ 4.21005756e-01],
       [ 7.84174025e-01],
       [ 7.78599203e-01],
       [ 1.59163207e-01],
       [ 2.76507586e-01],
       [ 6.89820051e-02],
       [ 1.30398953e-02],
       [ 1.84918419e-02],
       [ 3.22295614e-02],
       [ 3.14224243e-01],
       [ 7.03525305e-01],
       [ 7.35445917e-01],
       [ 1.64242834e-01],
       [ 2.06120722e-02],
       [ 2.55264826e-02],
       [ 3.33978906e-02],
       [ 3.31976324e-01],
       [ 7.06150115e-01],
       [ 6.83837295e-01],
       [ 4.17379767e-01],
       [ 8.20692256e-02],
       [ 2.48671342e-02],
       [ 1.28051136e-02],
       [ 1.44009152e-02],
       [ 2.21248478e-01],
       [ 4.88373309e-01],
       [ 5.59370816e-01],
       [ 3.61910075e-01],
       [ 2.68236578e-01],
       [ 1.83189511e-01],
       [ 4.13150936e-02],
       [ 8.55939649e-03],
       [ 2.07102485e-03],
       [ 1.89856719e-03],
       [ 1.34939561e-02],
       [ 1.82195842e-01],
       [ 5.45753181e-01],
       [ 6.27675295e-01],
       [ 3.88082474e-01],
       [ 1.78297758e-01],
       [ 3.78423966e-02],
       [ 9.45475325e-03],
       [ 1.54408626e-03],
       [ 1.11634806e-02],
       [ 1.88695520e-01],
       [ 4.74368244e-01],
       [ 5.67331970e-01],
       [ 1.94228441e-01],
       [ 2.75271863e-01],
       [ 3.52835834e-01],
       [ 1.42283201e-01],
       [ 3.18959169e-03],
       [ 3.59467231e-03],
       [ 6.29937463e-03],
       [ 1.29600782e-02],
       [ 1.69253886e-01],
       [ 5.57956278e-01],
       [ 6.41186059e-01],
       [ 1.61123931e-01],
       [ 1.00223787e-01],
       [ 4.69826497e-02],
       [ 4.20035981e-03],
       [ 5.42830490e-03],
       [ 1.17193423e-02],
       [ 1.21349186e-01],
       [ 4.93105888e-01],
       [ 5.55717230e-01],
       [ 2.21720427e-01],
       [ 2.99801733e-02],
       [-5.77684492e-04],
       [-7.86139816e-03],
       [ 6.75394945e-03],
       [ 2.06231982e-01],
       [ 5.94193637e-01],
       [ 6.07072651e-01],
       [ 6.22961670e-02],
       [ 2.31033377e-03],
       [ 5.65335527e-03],
       [ 8.75040703e-03],
       [ 2.27212459e-01],
       [ 6.16430938e-01],
       [ 6.51836216e-01],
       [ 8.62927884e-02],
       [-4.10936400e-03],
       [ 8.68903473e-03],
       [ 1.32383667e-02],
       [ 3.08761626e-01],
       [ 6.71008348e-01],
       [ 6.71989858e-01],
       [ 2.97941417e-01],
       [ 3.04103822e-01],
       [-8.06637295e-03],
       [ 1.13317212e-02],
       [ 2.35816482e-02],
       [ 3.54818702e-01],
       [ 6.77312911e-01],
       [ 7.46748030e-01],
       [ 3.21503937e-01],
       [ 3.84960264e-01],
       [ 2.92859897e-02],
       [-2.08782032e-03],
       [ 2.67193466e-03],
       [ 2.27674991e-02],
       [ 3.09292644e-01],
       [ 6.69125140e-01],
       [ 7.98809767e-01],
       [ 5.56851089e-01],
       [ 3.92202944e-01],
       [ 4.72502619e-01],
       [ 6.50309801e-01],
       [ 6.43083632e-01],
       [ 2.48985350e-01],
       [ 1.32920407e-02],
       [ 8.29657540e-04],
       [ 7.88854156e-03],
       [ 2.10974365e-02],
       [ 3.22528064e-01],
       [ 6.72429383e-01],
       [ 8.00799429e-01],
       [ 4.81890887e-01],
       [ 3.39002013e-01],
       [ 4.08097059e-01],
       [ 4.48333770e-02],
       [ 1.55413179e-02],
       [ 2.64901370e-02],
       [ 2.88092867e-02],
       [ 2.54396170e-01],
       [ 6.36803985e-01],
       [ 7.97873557e-01],
       [ 7.08966434e-01],
       [ 6.38677716e-01],
       [ 5.16248643e-01],
       [ 3.96685094e-01],
       [ 2.90003717e-01],
       [ 1.26192719e-02],
       [ 9.38014314e-03],
       [ 1.35621708e-02],
       [ 2.20623389e-02],
       [ 2.17482597e-01],
       [ 6.50762796e-01],
       [ 7.30308831e-01],
       [ 5.67562521e-01],
       [ 4.43405241e-01],
       [ 1.17338300e-01],
       [ 2.26980820e-02],
       [ 9.80344880e-03],
       [ 1.37015302e-02],
       [ 2.44593471e-02],
       [ 2.20999867e-01],
       [ 6.19736791e-01],
       [ 7.26388514e-01],
       [ 3.81992429e-01],
       [ 2.19627112e-01],
       [ 3.06784123e-01],
       [ 2.44770855e-01],
       [ 1.98816732e-02],
       [ 1.61403157e-02],
       [ 1.13885636e-02],
       [ 1.72196664e-02],
       [ 2.12818623e-01],
       [ 6.38403535e-01],
       [ 7.62063384e-01],
       [ 4.89142358e-01],
       [ 4.93659586e-01],
       [ 2.90214926e-01],
       [ 1.74065530e-02],
       [-5.62801678e-03],
       [ 6.85732532e-03],
       [ 1.91205386e-02],
       [ 2.14138389e-01],
       [ 5.94039202e-01],
       [ 7.03744411e-01],
       [ 2.61335015e-01],
       [ 1.69038355e-01],
       [ 9.41760838e-03],
       [ 9.29693598e-03],
       [ 3.83896008e-03],
       [ 2.73241829e-02],
       [ 2.60666102e-01],
       [ 6.27237499e-01],
       [ 7.48823106e-01],
       [ 4.73569185e-01],
       [ 3.10299098e-01],
       [ 9.81530361e-03],
       [ 6.06721826e-03],
       [ 9.47761349e-04],
       [ 2.46839337e-02],
       [ 3.25078368e-01],
       [ 6.77428484e-01],
       [ 8.00897121e-01],
       [ 5.38004935e-01],
       [ 3.22389990e-01],
       [-4.08699363e-03],
       [ 1.67875346e-02],
       [ 1.97449662e-02],
       [ 3.65300864e-01],
       [ 6.74805164e-01],
       [ 7.75242746e-01],
       [ 4.92139220e-01],
       [ 2.83223778e-01],
       [-3.13522667e-03],
       [ 2.03616023e-02],
       [ 2.19732933e-02],
       [ 3.84059161e-01],
       [ 6.71547771e-01],
       [ 7.61117280e-01],
       [ 2.83558190e-01],
       [ 2.16447711e-02],
       [ 1.04997652e-02],
       [ 6.03204221e-03],
       [ 1.89437903e-02],
       [ 3.46325785e-01],
       [ 6.66261375e-01],
       [ 7.73518980e-01],
       [ 2.58071601e-01],
       [ 2.17228681e-02],
       [ 9.50497761e-03],
       [ 4.21892852e-03],
       [ 1.57044157e-02],
       [ 3.28482747e-01],
       [ 6.81775749e-01],
       [ 8.98329914e-01],
       [ 5.07003963e-01],
       [ 6.52206875e-03],
       [ 1.70323104e-02],
       [ 1.99938565e-02],
       [ 3.14734429e-01],
       [ 7.14249194e-01],
       [ 7.70645559e-01],
       [ 5.17499804e-01],
       [ 1.74019933e-01],
       [ 1.08880494e-02],
       [ 1.25193764e-02],
       [ 5.15154190e-03],
       [ 1.96654219e-02],
       [ 2.66119599e-01],
       [ 6.54229939e-01],
       [ 7.39600480e-01],
       [ 4.14952427e-01],
       [ 2.60125101e-02],
       [ 6.73824735e-03],
       [-4.43868339e-05],
       [ 1.07822660e-02],
       [ 2.73681015e-01],
       [ 6.75575435e-01],
       [ 7.18611181e-01],
       [ 5.57898939e-01],
       [ 4.04301196e-01],
       [ 1.95246994e-01],
       [ 1.04444325e-02],
       [-2.46096496e-03],
       [ 3.65333352e-03],
       [ 1.62543096e-02],
       [ 1.80132031e-01],
       [ 5.17202616e-01],
       [ 6.21704757e-01],
       [ 5.26691139e-01],
       [ 4.27979857e-01],
       [ 8.34507868e-03],
       [ 2.21231021e-03],
       [-1.06781628e-03],
       [ 1.71417966e-02],
       [ 2.62655288e-01],
       [ 6.46763802e-01],
       [ 6.96168959e-01],
       [ 3.73450607e-01],
       [ 1.51586711e-01],
       [-3.38066183e-03],
       [ 6.94208965e-03],
       [ 1.13026891e-02],
       [ 2.57585764e-01],
       [ 6.48451746e-01],
       [ 6.92392051e-01],
       [ 3.31405610e-01],
       [ 5.90257123e-02],

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
15910,0.0,0.0,0.0,NaN,NaN,NaN
15919,0.0,45.085922,0.0,NaN,NaN,NaN
15920,2324.0,1747.559524,2931.155236,NaN,NaN,NaN
15921,16384.0,15282.644011,15534.328419,NaN,NaN,NaN
15922,25212.0,24396.229156,25499.346937,NaN,NaN,NaN
...,...,...,...,...,...,...
18273,7356.0,6918.407231,7148.104256,8764.482422,4792.106445,6426.757812
18274,17638.0,19779.365821,21016.223316,22835.416016,16919.378906,19157.732422
18275,23339.0,24030.007366,23687.023299,20082.384766,20590.408203,20639.869141
18276,26323.0,24112.268947,23126.102053,555.459778,4796.369141,7396.311035
18286,0.0,0.0,0.0,3977.639893,1132.771362,1926.788086

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1106.0083
RMSE: 2067.4017
R²: 0.9606
Random Forest
MAE: 1090.0346
RMSE: 2258.6311
R²: 0.9530
CTNET
MAE: 3467.4857
RMSE: 5586.7247
R²: 0.7102
Forecast
MAE: 3091.9189
RMSE: 5056.4349
R²: 0.7626
Photovoltaic
MAE: 2914.2414
RMSE: 4709.7532
R²: 0.7940

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

120/120 ━━━━━━━━━━━━━━━━━━━━ 21s 95ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

120/120 ━━━━━━━━━━━━━━━━━━━━ 22s 137ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

120/120 ━━━━━━━━━━━━━━━━━━━━ 13s 62ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
30,0.000000,60.077787,0.000000,NaN,NaN,NaN
31,0.000000,125.231595,27.698762,NaN,NaN,NaN
32,438.814997,884.746075,725.392330,NaN,NaN,NaN
33,5908.000884,10270.994439,6697.509600,NaN,NaN,NaN
34,5030.740421,8168.208553,7058.407504,NaN,NaN,NaN
...,...,...,...,...,...,...
12201,73.000000,21.688955,78.895340,1237.663940,0.000000,2421.334961
12202,6162.000000,4498.638662,5359.067161,6596.325195,7734.854980,8587.843750
12203,17560.000000,11523.395944,16822.837755,16539.724609,10022.355469,10730.244141
12204,19055.000000,18153.461478,18481.512500,18394.330078,17319.433594,15284.959961
12223,0.000000,71.372983,0.000000,13260.273438,6785.480957,6855.641113

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1250.4265
RMSE: 2294.1852
R²: 0.9420
Random Forest
MAE: 499.6361
RMSE: 1002.8449
R²: 0.9889
CTNET
MAE: 2138.8703
RMSE: 3548.0421
R²: 0.8617
Forecast
MAE: 3760.0102
RMSE: 6126.0682
R²: 0.5876
Photovoltaic
MAE: 3246.3386
RMSE: 4868.2346
R²: 0.7396

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.8_Predicciones_Conjunto_soleado KMeans CTNET.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_8_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_8_RandomForest_model.pkl")

['4_8_RandomForest_model.pkl']

In [87]:
CTNET.save("4_8_CTNET_model.keras")
Forecast_model.save("4_8_Forecast_model.keras")
Photo_model.save("4_8_Photo_model.keras")