# Conjunto de datos completo sin clusterización

In [1]:
#Importaciones
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Lectura de datos
datos = pd.read_excel('03_Clusterizacion_CTNET.xlsx')
datos.head(24)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM
0,2022-09-01 00:00:00,0.000000,19,77,0,0,Noche,Noche
1,2022-09-01 01:00:00,0.000000,19,82,0,1,Noche,Noche
2,2022-09-01 02:00:00,0.000000,18,85,0,2,Noche,Noche
3,2022-09-01 03:00:00,0.000000,18,87,0,3,Noche,Noche
4,2022-09-01 04:00:00,0.000000,18,88,0,4,Noche,Noche
5,2022-09-01 05:00:00,0.000000,17,86,0,5,Noche,Noche
6,2022-09-01 06:00:00,0.000000,18,89,0,6,Soleado,Lluvioso
7,2022-09-01 07:00:00,6.584959,18,95,0,7,Soleado,Lluvioso
8,2022-09-01 08:00:00,560.422022,18,100,0,8,Soleado,Lluvioso
9,2022-09-01 09:00:00,7720.582326,18,100,1,9,Soleado,Lluvioso
10,2022-09-01 10:00:00,9433.109309,19,93,2,10,Soleado,Lluvioso
11,2022-09-01 11:00:00,22189.147406,20,79,2,11,Soleado,Lluvioso
12,2022-09-01 12:00:00,29196.986647,22,64,6,12,Nublado,Soleado
13,2022-09-01 13:00:00,25478.471342,23,51,11,13,Nublado,Soleado
14,2022-09-01 14:00:00,29057.585772,25,41,12,14,Nublado,Soleado
15,2022-09-01 15:00:00,30000.000000,26,35,11,15,Nublado,Soleado
16,2022-09-01 16:00:00,28062.328964,27,33,8,16,Nublado,Soleado
17,2022-09-01 17:00:00,28786.629243,28,34,5,17,Nublado,Nublado
18,2022-09-01 18:00:00,29900.303971,27,37,3,18,Nublado,Nublado
19,2022-09-01 19:00:00,18282.505369,26,41,2,19,Nublado,Nublado
20,2022-09-01 20:00:00,3411.083740,24,48,0,20,Nublado,Nublado
21,2022-09-01 21:00:00,382.187718,22,55,0,21,Soleado,Lluvioso
22,2022-09-01 22:00:00,0.000000,21,61,0,22,Noche,Noche
23,2022-09-01 23:00:00,0.000000,20,68,0,23,Noche,Noche

In [2]:
datos["Generacion_prev_hour"] = datos["Generación"].shift(1)
datos["Generacion_prev_day"] = datos["Generación"].shift(24)
datos = datos.dropna(how="any", axis= 0)

Definimos X y y

In [3]:
datos_dia = datos[datos["Cluster KMeans"] == "Nublado"].copy()
datos_dia.head(10)

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day
36,2022-09-02 12:00:00,27523.885172,21,57,4,12,Nublado,Nublado,17036.043251,29196.986647
37,2022-09-02 13:00:00,20596.278869,23,45,5,13,Nublado,Nublado,27523.885172,25478.471342
38,2022-09-02 14:00:00,28500.000000,24,37,6,14,Nublado,Nublado,20596.278869,29057.585772
39,2022-09-02 15:00:00,24647.568577,26,33,5,15,Nublado,Nublado,28500.000000,30000.000000
40,2022-09-02 16:00:00,25500.000000,27,34,4,16,Nublado,Nublado,24647.568577,28062.328964
41,2022-09-02 17:00:00,24281.956494,28,36,2,17,Nublado,Nublado,25500.000000,28786.629243
42,2022-09-02 18:00:00,22733.515002,26,39,1,18,Nublado,Nublado,24281.956494,29900.303971
43,2022-09-02 19:00:00,11972.590689,25,44,1,19,Nublado,Nublado,22733.515002,18282.505369
60,2022-09-03 12:00:00,17723.695569,21,58,4,12,Nublado,Soleado,11246.659307,27523.885172
61,2022-09-03 13:00:00,20400.000000,23,48,5,13,Nublado,Nublado,17723.695569,20596.278869

In [4]:
columns = datos_dia.drop(columns=["Fecha", "Generación", "Cluster KMeans", "Cluster GMM"]).columns

In [5]:
X = datos_dia[columns]
X

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,21,57,4,12,17036.043251,29196.986647
37,23,45,5,13,27523.885172,25478.471342
38,24,37,6,14,20596.278869,29057.585772
39,26,33,5,15,28500.000000,30000.000000
40,27,34,4,16,24647.568577,28062.328964
...,...,...,...,...,...,...
18281,26,31,4,16,25562.000000,25385.000000
18282,26,32,2,17,25386.000000,22664.000000
18283,25,33,1,18,22872.000000,15736.000000
18284,23,38,0,19,15825.000000,1407.000000
18285,22,45,0,20,1450.000000,0.000000

In [6]:
y = datos_dia[['Generación']]
y

         Generación
36     27523.885172
37     20596.278869
38     28500.000000
39     24647.568577
40     25500.000000
...             ...
18281  25386.000000
18282  22872.000000
18283  15825.000000
18284   1450.000000
18285      0.000000

[6630 rows x 1 columns]

Dividimos entrenamiento, validación y prueba

In [7]:
train_size = int(0.7 * len(X))
val_size = int(0.85 * len(X))

In [8]:
# Entrenamiento, validación y prueba, 75, 15 y 15
X_train, y_train =  X.iloc[:train_size, :], y.iloc[:train_size, :]
X_val, y_val = X.iloc[train_size:val_size, :], y.iloc[train_size:val_size, :]
X_test, y_test = X.iloc[val_size:, :],  y.iloc[val_size:,:]

print(f'X_train: {len(X_train)}, y_train: {len(y_train)}')
print(f'X_val: {len(X_val)}, y_val: {len(y_val)}')
print(f'X_test: {len(X_test)}, y_test: {len(y_test)}')

X_train: 4641, y_train: 4641
X_val: 994, y_val: 994
X_test: 995, y_test: 995

## Escalar con MinMaxScaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
x_scaler = MinMaxScaler().fit(X_train)
x_scaler

MinMaxScaler()

In [11]:
X_train_scaled = x_scaler.transform(X_train)
print(X_train_scaled)
print(X_train_scaled.shape)

[[0.43333333 0.7761194  0.28571429 0.4        0.56786811 0.97323289]
 [0.5        0.59701493 0.35714286 0.46666667 0.91746284 0.84928238]
 [0.53333333 0.47761194 0.42857143 0.53333333 0.68654263 0.96858619]
 ...
 [0.53333333 0.08955224 0.28571429 0.4        0.89256667 0.71003333]
 [0.6        0.04477612 0.28571429 0.46666667 0.89183333 0.6942    ]
 [0.66666667 0.02985075 0.28571429 0.53333333 0.884      0.67946667]]
(4641, 6)

In [12]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)
X_train_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.433333,0.776119,0.285714,0.400000,0.567868,0.973233
37,0.500000,0.597015,0.357143,0.466667,0.917463,0.849282
38,0.533333,0.477612,0.428571,0.533333,0.686543,0.968586
39,0.600000,0.417910,0.357143,0.600000,0.950000,1.000000
40,0.633333,0.432836,0.285714,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
13283,0.266667,0.253731,0.142857,0.266667,0.261667,0.703733
13284,0.400000,0.149254,0.214286,0.333333,0.847233,0.716300
13285,0.533333,0.089552,0.285714,0.400000,0.892567,0.710033
13286,0.600000,0.044776,0.285714,0.466667,0.891833,0.694200
13287,0.666667,0.029851,0.285714,0.533333,0.884000,0.679467

In [13]:
X_val_scaled = x_scaler.transform(X_val)
print(X_val_scaled)
print(X_val_scaled.shape)

[[0.7        0.02985075 0.21428571 0.6        0.88153333 0.68466667]
 [0.76666667 0.02985075 0.14285714 0.66666667 0.89283333 0.6928    ]
 [0.8        0.01492537 0.07142857 0.73333333 0.89383333 0.66686667]
 ...
 [0.73333333 0.41791045 0.85714286 0.4        0.94243333 0.95253333]
 [0.8        0.29850746 1.         0.46666667 0.94176667 0.95486667]
 [0.83333333 0.2238806  0.85714286 0.53333333 0.93916667 0.97816667]]
(994, 6)

In [14]:
X_val_scaled_df = pd.DataFrame(X_val_scaled, index=X_val.index, columns=X_val.columns)
X_val_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
13288,0.700000,0.029851,0.214286,0.600000,0.881533,0.684667
13289,0.766667,0.029851,0.142857,0.666667,0.892833,0.692800
13290,0.800000,0.014925,0.071429,0.733333,0.893833,0.666867
13291,0.766667,0.014925,0.000000,0.800000,0.853433,0.491367
13292,0.700000,0.029851,0.000000,0.866667,0.514800,0.095967
...,...,...,...,...,...,...
15323,0.533333,0.805970,0.357143,0.266667,0.846533,0.940067
15324,0.633333,0.582090,0.642857,0.333333,0.911033,0.968733
15325,0.733333,0.417910,0.857143,0.400000,0.942433,0.952533
15326,0.800000,0.298507,1.000000,0.466667,0.941767,0.954867
15327,0.833333,0.223881,0.857143,0.533333,0.939167,0.978167

In [15]:
X_test_scaled = x_scaler.transform(X_test)
print(X_test_scaled)
print(X_test_scaled.shape)

[[0.9        0.1641791  0.64285714 0.6        0.93993333 0.95946667]
 [0.96666667 0.11940299 0.35714286 0.66666667 0.9288     0.94446667]
 [0.93333333 0.11940299 0.21428571 0.73333333 0.8208     0.89293333]
 ...
 [0.56666667 0.41791045 0.07142857 0.8        0.7624     0.52453333]
 [0.5        0.49253731 0.         0.86666667 0.5275     0.0469    ]
 [0.46666667 0.59701493 0.         0.93333333 0.04833333 0.        ]]
(995, 6)

In [16]:
X_test_scaled_df = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)
X_test_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
15328,0.900000,0.164179,0.642857,0.600000,0.939933,0.959467
15329,0.966667,0.119403,0.357143,0.666667,0.928800,0.944467
15330,0.933333,0.119403,0.214286,0.733333,0.820800,0.892933
15331,0.900000,0.134328,0.142857,0.800000,0.788567,0.768000
15332,0.833333,0.179104,0.071429,0.866667,0.689433,0.349533
...,...,...,...,...,...,...
18281,0.600000,0.388060,0.285714,0.666667,0.852067,0.846167
18282,0.600000,0.402985,0.142857,0.733333,0.846200,0.755467
18283,0.566667,0.417910,0.071429,0.800000,0.762400,0.524533
18284,0.500000,0.492537,0.000000,0.866667,0.527500,0.046900
18285,0.466667,0.597015,0.000000,0.933333,0.048333,0.000000

In [17]:
x_scaller_all = MinMaxScaler().fit(X)
print(x_scaller_all)

MinMaxScaler()

In [18]:
X_scaled = x_scaller_all.transform(X)
print(X_scaled)
print(X_scaled.shape)

[[0.41935484 0.76056338 0.28571429 0.4        0.56786811 0.97323289]
 [0.48387097 0.5915493  0.35714286 0.46666667 0.91746284 0.84928238]
 [0.51612903 0.47887324 0.42857143 0.53333333 0.68654263 0.96858619]
 ...
 [0.5483871  0.42253521 0.07142857 0.8        0.7624     0.52453333]
 [0.48387097 0.49295775 0.         0.86666667 0.5275     0.0469    ]
 [0.4516129  0.5915493  0.         0.93333333 0.04833333 0.        ]]
(6630, 6)

In [19]:
X_scaled_df = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)
X_scaled_df

,Temperatura,Humedad Relativa,Índice UV,Hora,Generacion_prev_hour,Generacion_prev_day
36,0.419355,0.760563,0.285714,0.400000,0.567868,0.973233
37,0.483871,0.591549,0.357143,0.466667,0.917463,0.849282
38,0.516129,0.478873,0.428571,0.533333,0.686543,0.968586
39,0.580645,0.422535,0.357143,0.600000,0.950000,1.000000
40,0.612903,0.436620,0.285714,0.666667,0.821586,0.935411
...,...,...,...,...,...,...
18281,0.580645,0.394366,0.285714,0.666667,0.852067,0.846167
18282,0.580645,0.408451,0.142857,0.733333,0.846200,0.755467
18283,0.548387,0.422535,0.071429,0.800000,0.762400,0.524533
18284,0.483871,0.492958,0.000000,0.866667,0.527500,0.046900
18285,0.451613,0.591549,0.000000,0.933333,0.048333,0.000000

In [20]:
y_scaler = MinMaxScaler().fit(y_train)
print(y_scaler)

MinMaxScaler()

In [21]:
y_train_scaled = y_scaler.transform(y_train)
print(y_train_scaled)
print(y_train_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.89183333]
 [0.884     ]
 [0.88153333]]
(4641, 1)

In [22]:
y_train_scaled_df = pd.DataFrame(y_train_scaled, index=y_train.index, columns=y_train.columns)
y_train_scaled_df

       Generación
36       0.917463
37       0.686543
38       0.950000
39       0.821586
40       0.850000
...           ...
13283    0.847233
13284    0.892567
13285    0.891833
13286    0.884000
13287    0.881533

[4641 rows x 1 columns]

In [23]:
y_val_scaled = y_scaler.transform(y_val)
print(y_val_scaled)
print(y_val_scaled.shape)

[[8.92833333e-01]
 [8.93833333e-01]
 [8.53433333e-01]
 [5.14800000e-01]
 [5.18333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.03733333e-01]
 [6.26766667e-01]
 [7.09333333e-01]
 [7.83833333e-01]
 [6.76500000e-01]
 [6.85366667e-01]
 [6.87533333e-01]
 [6.60733333e-01]
 [4.83800000e-01]
 [9.24333333e-02]
 [0.00000000e+00]
 [6.76500000e-01]
 [6.89666667e-01]
 [7.04466667e-01]
 [6.53366667e-01]
 [4.85666667e-01]
 [6.37866667e-01]
 [6.10033333e-01]
 [5.91933333e-01]
 [5.99333333e-01]
 [6.08266667e-01]
 [6.53366667e-01]
 [4.23333333e-01]
 [9.31666667e-02]
 [8.27966667e-01]
 [7.89800000e-01]
 [8.75533333e-01]
 [8.66100000e-01]
 [8.54000000e-01]
 [7.82533333e-01]
 [7.58700000e-01]
 [5.93666667e-01]
 [1.34566667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.95366667e-01]
 [8.78733333e-01]
 [8.57166667e-01]
 [8.45600000e-01]
 [8.68233333e-01]
 [8.61400000e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.01333333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.48333333e-01]
 [9.95633333e-01]
 [9.94466667e-01]
 [9.95933333e-01]
 [9.86300000e-01]
 [9.94966667e-01]
 [9.92933333e-01]
 [8.74533333e-01]
 [4.33266667e-01]
 [4.10333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79666667e-01]
 [8.95366667e-01]
 [8.88700000e-01]
 [8.63266667e-01]
 [8.45600000e-01]
 [6.92400000e-01]
 [6.88233333e-01]
 [7.55933333e-01]
 [4.88400000e-01]
 [1.12600000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79666667e-01]
 [8.98466667e-01]
 [7.95000000e-01]
 [7.71466667e-01]
 [6.76500000e-01]
 [6.89233333e-01]
 [6.07833333e-01]
 [4.00200000e-01]
 [3.87033333e-01]
 [9.06333333e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.98300000e-01]
 [8.68166667e-01]
 [8.62933333e-01]
 [8.52733333e-01]
 [8.66466667e-01]
 [8.47600000e-01]
 [6.41966667e-01]
 [4.83833333e-01]
 [9.58000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.24333333e-01]
 [7.97966667e-01]
 [8.61000000e-01]
 [8.58433333e-01]
 [8.62066667e-01]
 [8.68733333e-01]
 [8.07700000e-01]
 [5.96633333e-01]
 [6.85733333e-01]
 [6.81133333e-01]
 [7.68600000e-01]
 [9.80400000e-01]
 [9.75433333e-01]
 [9.28733333e-01]
 [9.71900000e-01]
 [9.31933333e-01]
 [5.67633333e-01]
 [6.32233333e-01]
 [8.27033333e-01]
 [6.72166667e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [9.40666667e-01]
 [9.62433333e-01]
 [8.77033333e-01]
 [8.78666667e-01]
 [8.45600000e-01]
 [9.33600000e-01]
 [8.93933333e-01]
 [8.16733333e-01]
 [6.21266667e-01]
 [1.34900000e-01]
 [2.00000000e-04]
 [0.00000000e+00]
 [9.28266667e-01]
 [9.40400000e-01]
 [9.29966667e-01]
 [9.21166667e-01]
 [9.04100000e-01]
 [9.32766667e-01]
 [9.17500000e-01]
 [8.86200000e-01]
 [6.76433333e-01]
 [1.34900000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.41633333e-01]
 [9.27633333e-01]
 [9.38033333e-01]
 [8.38033333e-01]
 [7.15233333e-01]
 [8.17833333e-01]
 [8.14000000e-01]
 [5.41133333e-01]
 [9.63333333e-02]
 [7.49966667e-01]
 [7.56900000e-01]
 [7.67166667e-01]
 [7.36500000e-01]
 [7.29200000e-01]
 [6.37000000e-01]
 [7.18033333e-01]
 [5.17733333e-01]
 [1.03866667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [1.66666667e-04]
 [5.93533333e-01]
 [7.68333333e-01]
 [9.49966667e-01]
 [9.51900000e-01]
 [9.51733333e-01]
 [9.75366667e-01]
 [9.35800000e-01]
 [9.04766667e-01]
 [9.29900000e-01]
 [9.22133333e-01]
 [6.47666667e-01]
 [1.32900000e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [7.42033333e-01]
 [9.55433333e-01]
 [8.95366667e-01]
 [9.50333333e-01]
 [9.39933333e-01]
 [9.14666667e-01]
 [8.83566667e-01]
 [8.60766667e-01]
 [8.27766667e-01]
 [6.04733333e-01]
 [1.28500000e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [6.12766667e-01]
 [8.79666667e-01]
 [9.16966667e-01]
 [9.83700000e-01]
 [9.76633333e-01]
 [9.70033333e-01]
 [8.54000000e-01]
 [9.44766667e-01]
 [9.41966667e-01]
 [6.38733333e-01]
 [1.34233333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.79966667e-01]
 [8.78133333e-01]
 [8.63900000e-01]
 [8.60000000e-01]
 [8.59233333e-01]
 [8.16733333e-01]
 [6.04733333e-01]
 [8.95366667e-01]
 [8.88066667e-01]
 [8.60833333e-01]
 [8.59400000e-01]
 [8.73633333e-01]
 [8.61933333e-01]
 [8.16733333e-01]
 [6.57833333e-01]
 [1.33966667e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [8.86333333e-01]
 [9.03966667e-01]
 [8.77033333e-01]
 [8.57166667e-01]
 [8.50866667e-01]
 [8.54000000e-01]
 [7.73300000e-01]
 [7.45766667e-01]
 [5.59166667e-01]
 [9.18666667e-02]
 [3.33333333e-05]
 [0.00000000e+00]
 [4.93366667e-01]
 [7.06200000e-01]
 [7.16300000e-01]
 [7.01633333e-01]
 [6.85733333e-01]
 [6.80666667e-01]
 [6.88833333e-01]
 [6.87366667e-01]
 [6.82566667e-01]
 [4.99900000e-01]
 [9.83666667e-02]
 [6.66666667e-05]
 [0.00000000e+00]
 [6.55566667e-01]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.48700000e-01]
 [7.42566667e-01]
 [7.41066667e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.67033333e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38166667e-01]
 [9.28233333e-01]
 [9.26366667e-01]
 [9.25733333e-01]
 [9.19733333e-01]
 [8.77900000e-01]
 [7.23600000e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.45666667e-01]
 [9.38600000e-01]
 [9.28233333e-01]
 [9.26366667e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.77900000e-01]
 [7.15266667e-01]
 [2.00866667e-01]
 [1.60000000e-03]
 [9.43833333e-01]
 [9.43233333e-01]
 [9.40500000e-01]
 [9.26366667e-01]
 [9.32266667e-01]
 [9.13333333e-01]
 [8.77900000e-01]
 [7.08766667e-01]
 [1.93533333e-01]
 [1.43333333e-03]
 [0.00000000e+00]
 [9.95466667e-01]
 [9.95566667e-01]
 [9.94200000e-01]
 [9.87666667e-01]
 [9.69366667e-01]
 [9.55300000e-01]
 [8.80333333e-01]
 [5.72166667e-01]
 [1.18833333e-01]
 [0.00000000e+00]
 [0.00000000e+00]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.60500000e-01]
 [7.42566667e-01]
 [7.41066667e-01]
 [7.40600000e-01]
 [8.18700000e-01]
 [7.90133333e-01]
 [5.67033333e-01]
 [1.55000000e-01]
 [1.23333333e-03]
 [0.00000000e+00]
 [6.55566667e-01]
 [7.40466667e-01]
 [7.53133333e-01]
 [7.69133333e-01]
 [7.50566667e-01]
 [7.42333333e-01]
 [7.40600000e-01]
 [7.27733333e-01]
 [7.02333333e-01]
 [5.72700000e-01]
 [1.58866667e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [7.40466667e-01]
 [7.48766667e-01]
 [7.56266667e-01]
 [7.60966667e-01]
 [7.49200000e-01]
 [7.40600000e-01]
 [6.36766667e-01]
 [6.19600000e-01]
 [5.03100000e-01]
 [1.43233333e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [3.42366667e-01]
 [8.34100000e-01]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.50600000e-01]
 [9.28233333e-01]
 [9.34933333e-01]
 [9.27933333e-01]
 [9.19733333e-01]
 [8.85233333e-01]
 [7.12900000e-01]
 [1.93533333e-01]
 [1.53333333e-03]
 [0.00000000e+00]
 [3.80700000e-01]
 [8.66833333e-01]
 [9.74500000e-01]
 [9.95466667e-01]
 [9.95433333e-01]
 [9.94366667e-01]
 [9.85700000e-01]
 [9.95466667e-01]
 [9.61066667e-01]
 [8.29166667e-01]
 [5.44333333e-01]
 [1.08133333e-01]
 [3.33333333e-05]
 [0.00000000e+00]
 [9.25600000e-01]
 [9.35966667e-01]
 [9.38666667e-01]
 [8.46000000e-01]
 [8.37066667e-01]
 [7.42366667e-01]
 [7.27733333e-01]
 [7.90133333e-01]
 [6.37900000e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [7.48566667e-01]
 [7.49766667e-01]
 [7.54766667e-01]
 [7.52966667e-01]
 [7.50966667e-01]
 [6.56566667e-01]
 [6.55966667e-01]
 [6.14533333e-01]
 [5.72466667e-01]
 [1.54833333e-01]
 [1.13333333e-03]
 [0.00000000e+00]
 [9.35966667e-01]
 [8.42266667e-01]
 [7.42566667e-01]
 [9.28733333e-01]
 [9.25733333e-01]
 [9.09666667e-01]
 [8.85233333e-01]
 [6.39533333e-01]
 [1.65300000e-01]
 [1.73333333e-03]
 [0.00000000e+00]
 [7.48766667e-01]
 [7.55500000e-01]
 [7.48433333e-01]
 [8.33766667e-01]
 [7.43200000e-01]
 [8.18700000e-01]
 [7.98633333e-01]
 [6.37900000e-01]
 [2.08033333e-01]
 [1.76666667e-03]
 [0.00000000e+00]
 [9.35966667e-01]
 [9.35866667e-01]
 [9.30333333e-01]
 [9.34100000e-01]
 [9.35533333e-01]
 [5.46000000e-01]
 [5.34800000e-01]
 [4.25333333e-01]
 [1.48633333e-01]
 [1.56666667e-03]
 [0.00000000e+00]
 [7.64600000e-01]
 [7.68100000e-01]
 [7.65933333e-01]
 [7.58566667e-01]
 [7.55666667e-01]
 [6.59333333e-01]
 [7.54133333e-01]
 [7.20366667e-01]
 [6.26533333e-01]
 [1.58300000e-01]
 [1.40000000e-03]
 [0.00000000e+00]
 [7.62200000e-01]
 [8.57766667e-01]
 [8.80800000e-01]
 [7.52700000e-01]
 [8.57333333e-01]
 [7.59900000e-01]
 [7.50133333e-01]
 [7.21133333e-01]
 [5.39600000e-01]
 [1.97433333e-01]
 [2.83333333e-03]
 [0.00000000e+00]
 [8.79100000e-01]
 [8.84933333e-01]
 [8.48900000e-01]
 [8.57233333e-01]
 [8.53933333e-01]
 [7.48133333e-01]
 [7.17766667e-01]
 [6.09200000e-01]
 [1.62733333e-01]
 [3.23333333e-03]
 [0.00000000e+00]
 [9.96700000e-01]
 [9.97000000e-01]
 [9.97600000e-01]
 [9.94600000e-01]
 [9.61233333e-01]
 [9.12066667e-01]
 [8.52033333e-01]
 [5.46600000e-01]
 [7.90333333e-02]
 [0.00000000e+00]
 [9.53066667e-01]
 [9.50766667e-01]
 [9.40866667e-01]
 [9.51733333e-01]
 [9.49866667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.73033333e-01]
 [2.57900000e-01]
 [3.46666667e-03]
 [0.00000000e+00]
 [8.66900000e-01]
 [7.62466667e-01]
 [7.62033333e-01]
 [8.50033333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [8.43900000e-01]
 [8.10266667e-01]
 [6.97233333e-01]
 [2.65466667e-01]
 [4.54800000e-01]
 [7.52700000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [9.37666667e-01]
 [9.71333333e-01]
 [9.85466667e-01]
 [9.71233333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [9.37666667e-01]
 [9.01433333e-01]
 [7.74700000e-01]
 [2.49433333e-01]
 [2.73333333e-03]
 [9.68300000e-01]
 [9.85466667e-01]
 [9.71233333e-01]
 [9.52566667e-01]
 [9.49866667e-01]
 [8.40366667e-01]
 [7.17966667e-01]
 [6.85333333e-01]
 [2.01966667e-01]
 [3.80000000e-03]
 [0.00000000e+00]
 [9.95766667e-01]
 [9.96533333e-01]
 [9.95033333e-01]
 [9.83733333e-01]
 [1.00000000e+00]
 [9.84933333e-01]
 [9.31033333e-01]
 [7.18566667e-01]
 [1.62233333e-01]
 [2.66666667e-04]
 [0.00000000e+00]
 [7.57933333e-01]
 [9.64766667e-01]
 [9.81133333e-01]
 [9.63200000e-01]
 [9.37400000e-01]
 [9.37700000e-01]
 [9.21500000e-01]
 [8.86033333e-01]
 [7.33966667e-01]
 [2.35400000e-01]
 [6.50000000e-03]
 [0.00000000e+00]
 [4.26866667e-01]
 [8.85433333e-01]
 [9.77866667e-01]
 [9.44766667e-01]
 [9.78233333e-01]
 [9.71066667e-01]
 [9.53666667e-01]
 [9.46333333e-01]
 [9.36966667e-01]
 [9.04700000e-01]
 [7.61466667e-01]
 [2.68533333e-01]
 [4.10000000e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [3.40333333e-02]
 [4.63500000e-01]
 [8.89200000e-01]
 [9.82566667e-01]
 [9.59700000e-01]
 [9.80800000e-01]
 [9.82000000e-01]
 [9.54566667e-01]
 [9.52566667e-01]
 [9.41300000e-01]
 [9.06166667e-01]
 [7.84833333e-01]
 [2.75000000e-01]
 [4.23333333e-03]
 [0.00000000e+00]
 [9.43300000e-01]
 [9.80200000e-01]
 [9.70766667e-01]
 [9.51266667e-01]
 [9.57466667e-01]
 [9.40866667e-01]
 [9.07500000e-01]
 [7.73100000e-01]
 [2.98533333e-01]
 [2.60000000e-03]
 [0.00000000e+00]
 [9.70566667e-01]
 [9.83000000e-01]
 [8.74100000e-01]
 [7.62066667e-01]
 [7.59900000e-01]
 [7.50133333e-01]
 [7.21133333e-01]
 [6.09200000e-01]
 [2.20066667e-01]
 [4.03333333e-03]
 [0.00000000e+00]
 [8.59000000e-01]
 [9.58833333e-01]
 [9.36833333e-01]
 [9.42933333e-01]
 [9.39366667e-01]
 [9.40033333e-01]
 [9.18133333e-01]
 [8.82033333e-01]
 [7.18600000e-01]
 [2.73700000e-01]
 [9.46666667e-03]
 [0.00000000e+00]
 [3.75833333e-01]
 [7.45533333e-01]
 [7.42033333e-01]
 [7.50933333e-01]
 [7.49466667e-01]
 [7.54333333e-01]
 [8.42366667e-01]
 [8.33833333e-01]
 [7.20566667e-01]
 [6.79966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.09966667e-01]
 [9.42600000e-01]
 [9.46833333e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.26466667e-01]
 [8.09866667e-01]
 [7.69533333e-01]
 [5.74900000e-01]
 [2.20233333e-01]
 [7.80000000e-03]
 [0.00000000e+00]
 [6.32733333e-01]
 [8.39866667e-01]
 [9.36833333e-01]
 [9.36533333e-01]
 [9.33733333e-01]
 [8.33833333e-01]
 [8.10266667e-01]
 [7.64966667e-01]
 [7.18600000e-01]
 [2.85100000e-01]
 [9.70000000e-03]
 [0.00000000e+00]
 [8.11933333e-01]
 [9.33333333e-01]
 [9.38766667e-01]
 [9.45133333e-01]
 [8.40200000e-01]
 [7.42666667e-01]
 [8.09866667e-01]
 [8.51300000e-01]
 [7.18600000e-01]
 [2.86200000e-01]
 [1.03333333e-02]
 [0.00000000e+00]
 [7.26833333e-01]
 [7.47700000e-01]
 [7.49466667e-01]
 [8.50133333e-01]
 [8.45200000e-01]
 [8.39266667e-01]
 [7.20000000e-01]
 [6.84566667e-01]
 [5.74900000e-01]
 [2.98200000e-01]
 [1.05000000e-02]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.05666667e-02]
 [3.93466667e-01]
 [6.52300000e-01]
 [7.27966667e-01]
 [7.46533333e-01]
 [7.53633333e-01]
 [7.46500000e-01]
 [7.46100000e-01]
 [7.41400000e-01]
 [7.23333333e-01]
 [6.80400000e-01]
 [5.75633333e-01]
 [2.28066667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [5.70766667e-01]
 [7.19233333e-01]
 [7.46533333e-01]
 [6.60366667e-01]
 [6.50233333e-01]
 [7.46100000e-01]
 [7.41166667e-01]
 [6.29900000e-01]
 [5.94966667e-01]
 [5.82866667e-01]
 [2.26866667e-01]
 [7.63333333e-03]
 [0.00000000e+00]
 [4.22800000e-01]
 [6.52300000e-01]
 [8.98300000e-01]
 [9.42600000e-01]
 [9.40133333e-01]
 [9.34366667e-01]
 [8.39366667e-01]
 [8.33833333e-01]
 [6.33700000e-01]
 [5.11333333e-01]
 [6.46766667e-01]
 [2.46333333e-01]
 [9.73333333e-03]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.05200000e-01]
 [9.38133333e-01]
 [9.36833333e-01]
 [9.36033333e-01]
 [9.33733333e-01]
 [8.33833333e-01]
 [8.09866667e-01]
 [8.72800000e-01]
 [7.55366667e-01]
 [3.07166667e-01]
 [8.93333333e-03]
 [0.00000000e+00]
 [8.57133333e-01]
 [9.20300000e-01]
 [9.67966667e-01]
 [9.48966667e-01]
 [9.36900000e-01]
 [9.33266667e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [7.64966667e-01]
 [5.11633333e-01]
 [1.64200000e-01]
 [6.30000000e-03]
 [0.00000000e+00]
 [8.31733333e-01]
 [9.62566667e-01]
 [9.53566667e-01]
 [8.45700000e-01]
 [8.41600000e-01]
 [7.42200000e-01]
 [6.29900000e-01]
 [5.10000000e-01]
 [5.07933333e-01]
 [2.18966667e-01]
 [9.63333333e-03]
 [0.00000000e+00]
 [4.88366667e-01]
 [8.66500000e-01]
 [9.17300000e-01]
 [9.64300000e-01]
 [9.57766667e-01]
 [9.34333333e-01]
 [9.34400000e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.49966667e-01]
 [7.32000000e-01]
 [2.46333333e-01]
 [1.15000000e-02]
 [0.00000000e+00]
 [8.15366667e-01]
 [9.09966667e-01]
 [9.33200000e-01]
 [9.36833333e-01]
 [8.36033333e-01]
 [8.40566667e-01]
 [8.33833333e-01]
 [7.61866667e-01]
 [9.10933333e-01]
 [6.93933333e-01]
 [2.49333333e-01]
 [9.00000000e-03]
 [0.00000000e+00]
 [7.85633333e-01]
 [7.86966667e-01]
 [7.77733333e-01]
 [7.53266667e-01]
 [9.26466667e-01]
 [8.09866667e-01]
 [8.49966667e-01]
 [5.74900000e-01]
 [2.18966667e-01]
 [7.56666667e-03]
 [0.00000000e+00]
 [6.94966667e-01]
 [7.50200000e-01]
 [7.66966667e-01]
 [7.78433333e-01]
 [7.85133333e-01]
 [7.75266667e-01]
 [8.73566667e-01]
 [8.55633333e-01]
 [9.04733333e-01]
 [7.97366667e-01]
 [2.79900000e-01]
 [8.56666667e-03]
 [0.00000000e+00]
 [0.00000000e+00]
 [5.65000000e-02]
 [4.80066667e-01]
 [8.19466667e-01]
 [9.23433333e-01]
 [9.54966667e-01]
 [9.58666667e-01]
 [9.60966667e-01]
 [8.60433333e-01]
 [8.57166667e-01]
 [7.42933333e-01]
 [7.32166667e-01]
 [5.94933333e-01]
 [2.18966667e-01]
 [8.06666667e-03]
 [0.00000000e+00]
 [9.00233333e-01]
 [9.34766667e-01]
 [9.42000000e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.65300000e-01]
 [9.53833333e-01]
 [8.59966667e-01]
 [7.29466667e-01]
 [2.73700000e-01]
 [9.83333333e-03]
 [0.00000000e+00]
 [9.44200000e-01]
 [9.36833333e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.70633333e-01]
 [9.54733333e-01]
 [8.54300000e-01]
 [7.19966667e-01]
 [2.73700000e-01]
 [9.50000000e-03]
 [0.00000000e+00]
 [9.08266667e-01]
 [9.46966667e-01]
 [9.36900000e-01]
 [9.28933333e-01]
 [9.32600000e-01]
 [9.70633333e-01]
 [9.56866667e-01]
 [8.54666667e-01]
 [7.27666667e-01]
 [2.82700000e-01]
 [1.01666667e-02]
 [0.00000000e+00]
 [7.27966667e-01]
 [7.51000000e-01]
 [9.42900000e-01]
 [9.35066667e-01]
 [8.85000000e-01]
 [8.64733333e-01]
 [7.58300000e-01]
 [7.37733333e-01]
 [6.49833333e-01]
 [3.20966667e-01]
 [1.74000000e-02]
 [0.00000000e+00]
 [8.98300000e-01]
 [9.55633333e-01]
 [9.81366667e-01]
 [9.78833333e-01]
 [9.46833333e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.53966667e-01]
 [7.22833333e-01]
 [2.73700000e-01]
 [2.87666667e-02]
 [0.00000000e+00]
 [9.02500000e-01]
 [9.42600000e-01]
 [9.36833333e-01]
 [9.37533333e-01]
 [9.36300000e-01]
 [9.26466667e-01]
 [8.99866667e-01]
 [8.57966667e-01]
 [7.18600000e-01]
 [2.73700000e-01]
 [1.70666667e-02]
 [0.00000000e+00]
 [9.09966667e-01]
 [9.33200000e-01]
 [9.40566667e-01]
 [9.31866667e-01]
 [9.56766667e-01]
 [8.33833333e-01]
 [8.09866667e-01]
 [7.72500000e-01]
 [6.46766667e-01]
 [2.47566667e-01]
 [1.04333333e-02]
 [0.00000000e+00]
 [9.34533333e-01]
 [9.33200000e-01]
 [9.53700000e-01]
 [8.58433333e-01]
 [7.74533333e-01]
 [7.62633333e-01]
 [7.27633333e-01]
 [7.73966667e-01]
 [6.46766667e-01]
 [2.82900000e-01]
 [1.91000000e-02]
 [0.00000000e+00]
 [9.31033333e-01]
 [9.33200000e-01]
 [9.47900000e-01]
 [9.57766667e-01]
 [9.63166667e-01]
 [9.62400000e-01]
 [9.08200000e-01]
 [8.59200000e-01]
 [7.24766667e-01]
 [2.82266667e-01]
 [1.94666667e-02]
 [0.00000000e+00]
 [9.34800000e-01]
 [9.33200000e-01]
 [9.48400000e-01]
 [9.62033333e-01]
 [9.68766667e-01]
 [9.57766667e-01]
 [7.29533333e-01]
 [6.95366667e-01]
 [5.77333333e-01]
 [2.26266667e-01]
 [1.72666667e-02]
 [0.00000000e+00]
 [8.38900000e-01]
 [9.05900000e-01]
 [9.35533333e-01]
 [9.44133333e-01]
 [8.43766667e-01]
 [8.44833333e-01]
 [9.64166667e-01]
 [8.09866667e-01]
 [6.79966667e-01]
 [5.03033333e-01]
 [1.14966667e-01]
 [8.16666667e-03]
 [0.00000000e+00]
 [9.43966667e-01]
 [9.76166667e-01]
 [9.70166667e-01]
 [9.73133333e-01]
 [9.45833333e-01]
 [9.50100000e-01]
 [9.40366667e-01]
 [8.58366667e-01]
 [7.97133333e-01]
 [3.98800000e-01]
 [2.59333333e-02]
 [0.00000000e+00]
 [9.38266667e-01]
 [9.58200000e-01]
 [9.52766667e-01]
 [9.49633333e-01]
 [9.58566667e-01]
 [9.59300000e-01]
 [9.57033333e-01]
 [8.80700000e-01]
 [8.21566667e-01]
 [3.95600000e-01]
 [2.73333333e-02]
 [0.00000000e+00]
 [9.40066667e-01]
 [9.68733333e-01]
 [9.52533333e-01]
 [9.54866667e-01]
 [9.78166667e-01]
 [9.59466667e-01]
 [9.44466667e-01]
 [8.92933333e-01]
 [7.68000000e-01]
 [3.49533333e-01]
 [2.87666667e-02]
 [0.00000000e+00]
 [9.11033333e-01]
 [9.42433333e-01]
 [9.41766667e-01]
 [9.39166667e-01]
 [9.39933333e-01]]
(994, 1)

In [24]:
y_val_scaled_df = pd.DataFrame(y_val_scaled, index=y_val.index, columns=y_val.columns)
y_val_scaled_df

       Generación
13288    0.892833
13289    0.893833
13290    0.853433
13291    0.514800
13292    0.051833
...           ...
15323    0.911033
15324    0.942433
15325    0.941767
15326    0.939167
15327    0.939933

[994 rows x 1 columns]

In [25]:
y_test_scaled = y_scaler.transform(y_test)
print(y_test_scaled)
print(y_test_scaled.shape)

[[0.9288    ]
 [0.8208    ]
 [0.78856667]
 [0.68943333]
 [0.35676667]
 [0.0301    ]
 [0.        ]
 [0.7288    ]
 [0.77463333]
 [0.7569    ]
 [0.75133333]
 [0.8674    ]
 [0.77346667]
 [0.85126667]
 [0.78006667]
 [0.69566667]
 [0.35676667]
 [0.0335    ]
 [0.        ]
 [0.8673    ]
 [0.94856667]
 [0.97976667]
 [0.9742    ]
 [0.98153333]
 [0.94706667]
 [0.94543333]
 [0.9458    ]
 [0.7962    ]
 [0.73963333]
 [0.37316667]
 [0.02813333]
 [0.        ]
 [0.84413333]
 [0.91103333]
 [0.94243333]
 [0.94176667]
 [0.94386667]
 [0.9725    ]
 [0.9308    ]
 [0.7296    ]
 [0.80933333]
 [0.78803333]
 [0.40506667]
 [0.03346667]
 [0.        ]
 [0.8243    ]
 [0.91103333]
 [0.943     ]
 [0.94176667]
 [0.94886667]
 [0.95573333]
 [0.95593333]
 [0.9241    ]
 [0.86676667]
 [0.76606667]
 [0.42396667]
 [0.0338    ]
 [0.        ]
 [0.8237    ]
 [0.91103333]
 [0.9482    ]
 [0.94176667]
 [0.9482    ]
 [0.96123333]
 [0.95666667]
 [0.91926667]
 [0.86676667]
 [0.6952    ]
 [0.37006667]
 [0.03346667]
 [0.        ]
 [0.91103333]
 [0.9482    ]
 [0.94463333]
 [0.93916667]
 [0.6743    ]
 [0.8359    ]
 [0.8208    ]
 [0.70683333]
 [0.55156667]
 [0.38056667]
 [0.03136667]
 [0.        ]
 [0.7596    ]
 [0.97846667]
 [0.9731    ]
 [0.974     ]
 [0.9657    ]
 [0.8589    ]
 [0.7531    ]
 [0.818     ]
 [0.74176667]
 [0.3495    ]
 [0.02446667]
 [0.        ]
 [0.94716667]
 [0.9805    ]
 [0.9791    ]
 [0.9787    ]
 [0.95886667]
 [0.95263333]
 [0.9354    ]
 [0.9109    ]
 [0.82416667]
 [0.45596667]
 [0.0394    ]
 [0.        ]
 [0.9495    ]
 [0.9808    ]
 [0.98196667]
 [0.97453333]
 [0.9628    ]
 [0.95946667]
 [0.94076667]
 [0.9109    ]
 [0.82416667]
 [0.46683333]
 [0.0379    ]
 [0.        ]
 [0.96563333]
 [0.96843333]
 [0.96723333]
 [0.9436    ]
 [0.93903333]
 [0.92876667]
 [0.89913333]
 [0.6494    ]
 [0.35516667]
 [0.04673333]
 [0.        ]
 [0.9349    ]
 [0.9482    ]
 [0.94176667]
 [0.94283333]
 [0.93653333]
 [0.93116667]
 [0.9193    ]
 [0.785     ]
 [0.7128    ]
 [0.32696667]
 [0.044     ]
 [0.        ]
 [0.93306667]
 [0.9554    ]
 [0.94776667]
 [0.94003333]
 [0.93653333]
 [0.9356    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.40376667]
 [0.0505    ]
 [0.        ]
 [0.8319    ]
 [0.95456667]
 [0.97073333]
 [0.97656667]
 [0.94936667]
 [0.9278    ]
 [0.9074    ]
 [0.68956667]
 [0.6108    ]
 [0.37246667]
 [0.04123333]
 [0.        ]
 [0.7711    ]
 [0.60836667]
 [0.85406667]
 [0.94046667]
 [0.9288    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.39786667]
 [0.03346667]
 [0.        ]
 [0.9154    ]
 [0.96963333]
 [0.97063333]
 [0.95266667]
 [0.9444    ]
 [0.9288    ]
 [0.912     ]
 [0.86676667]
 [0.76606667]
 [0.404     ]
 [0.03453333]
 [0.        ]
 [0.91876667]
 [0.96546667]
 [0.96666667]
 [0.95023333]
 [0.94056667]
 [0.9288    ]
 [0.912     ]
 [0.86706667]
 [0.77026667]
 [0.41783333]
 [0.03356667]
 [0.        ]
 [0.91623333]
 [0.94683333]
 [0.94586667]
 [0.93916667]
 [0.93653333]
 [0.9356    ]
 [0.912     ]
 [0.86676667]
 [0.77336667]
 [0.3964    ]
 [0.03346667]
 [0.        ]
 [0.90956667]
 [0.93696667]
 [0.94776667]
 [0.94386667]
 [0.94046667]
 [0.9214    ]
 [0.85693333]
 [0.6903    ]
 [0.6948    ]
 [0.3181    ]
 [0.02866667]
 [0.94776667]
 [0.93916667]
 [0.93653333]
 [0.9288    ]
 [0.91493333]
 [0.59166667]
 [0.5925    ]
 [0.58783333]
 [0.59383333]
 [0.94096667]
 [0.94473333]
 [0.9435    ]
 [0.93916667]
 [0.93696667]
 [0.9288    ]
 [0.912     ]
 [0.78006667]
 [0.6946    ]
 [0.94776667]
 [0.94176667]
 [0.94543333]
 [0.95876667]
 [0.94533333]
 [0.9314    ]
 [0.8848    ]
 [0.7935    ]
 [0.42906667]
 [0.94133333]
 [0.94803333]
 [0.94803333]
 [0.95443333]
 [0.95203333]
 [0.9233    ]
 [0.90183333]
 [0.81353333]
 [0.94433333]
 [0.94283333]
 [0.93916667]
 [0.93653333]
 [0.93036667]
 [0.912     ]
 [0.86676667]
 [0.70006667]
 [0.4085    ]
 [0.94176667]
 [0.93916667]
 [0.93653333]
 [0.67313333]
 [0.912     ]
 [0.62406667]
 [0.94193333]
 [0.93916667]
 [0.93653333]
 [0.93386667]
 [0.92616667]
 [0.92313333]
 [0.92316667]
 [0.91553333]
 [0.91063333]
 [0.8989    ]
 [0.86446667]
 [0.77156667]
 [0.9276    ]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.91063333]
 [0.8989    ]
 [0.86173333]
 [0.77603333]
 [0.92123333]
 [0.91896667]
 [0.9173    ]
 [0.9135    ]
 [0.90476667]
 [0.86173333]
 [0.7702    ]
 [0.36326667]
 [0.93066667]
 [0.9218    ]
 [0.9522    ]
 [0.9401    ]
 [0.8244    ]
 [0.444     ]
 [0.42223333]
 [0.69733333]
 [0.39323333]
 [0.03236667]
 [0.378     ]
 [0.32013333]
 [0.316     ]
 [0.37496667]
 [0.35636667]
 [0.3083    ]
 [0.336     ]
 [0.32383333]
 [0.19636667]
 [0.0184    ]
 [0.9       ]
 [0.89676667]
 [0.8788    ]
 [0.89866667]
 [0.842     ]
 [0.85893333]
 [0.80036667]
 [0.7702    ]
 [0.32726667]
 [0.03023333]
 [0.9       ]
 [0.9       ]
 [0.87366667]
 [0.9       ]
 [0.84603333]
 [0.85996667]
 [0.80066667]
 [0.7702    ]
 [0.42076667]
 [0.03893333]
 [0.9304    ]
 [0.92123333]
 [0.83      ]
 [0.91613333]
 [0.91063333]
 [0.90623333]
 [0.86173333]
 [0.77143333]
 [0.35383333]
 [0.04793333]
 [0.63076667]
 [0.65176667]
 [0.71903333]
 [0.7635    ]
 [0.7987    ]
 [0.74013333]
 [0.91553333]
 [0.82056667]
 [0.6512    ]
 [0.55643333]
 [0.27      ]
 [0.26786667]
 [0.26763333]
 [0.28973333]
 [0.16096667]
 [0.2012    ]
 [0.2518    ]
 [0.405     ]
 [0.32163333]
 [0.40356667]
 [0.36216667]
 [0.36216667]
 [0.4346    ]
 [0.3771    ]
 [0.34846667]
 [0.9       ]
 [0.8863    ]
 [0.9       ]
 [0.8048    ]
 [0.8048    ]
 [0.3632    ]
 [0.37996667]
 [0.34693333]
 [0.20373333]
 [0.51786667]
 [0.6633    ]
 [0.73633333]
 [0.75536667]
 [0.7569    ]
 [0.38693333]
 [0.36546667]
 [0.3293    ]
 [0.24296667]
 [0.3966    ]
 [0.39583333]
 [0.38616667]
 [0.5203    ]
 [0.39356667]
 [0.45426667]
 [0.4549    ]
 [0.45376667]
 [0.27963333]
 [0.28206667]
 [0.392     ]
 [0.4501    ]
 [0.39206667]
 [0.39176667]
 [0.4462    ]
 [0.58406667]
 [0.89363333]
 [0.79943333]
 [0.92476667]
 [0.83566667]
 [0.84806667]
 [0.85176667]
 [0.8617    ]
 [0.80903333]
 [0.78476667]
 [0.70753333]
 [0.39843333]
 [0.92476667]
 [0.93596667]
 [0.9438    ]
 [0.95016667]
 [0.95743333]
 [0.8989    ]
 [0.8784    ]
 [0.77786667]
 [0.92476667]
 [0.9375    ]
 [0.95086667]
 [0.95153333]
 [0.95743333]
 [0.8989    ]
 [0.87786667]
 [0.7854    ]
 [0.8524    ]
 [0.8321    ]
 [0.9522    ]
 [0.6613    ]
 [0.65823333]
 [0.57636667]
 [0.4958    ]
 [0.3774    ]
 [0.39263333]
 [0.39453333]
 [0.46656667]
 [0.4486    ]
 [0.51253333]
 [0.5035    ]
 [0.62146667]
 [0.66073333]
 [0.66416667]
 [0.688     ]
 [0.66283333]
 [0.65876667]
 [0.63633333]
 [0.92123333]
 [0.9215    ]
 [0.91553333]
 [0.91133333]
 [0.8989    ]
 [0.92446667]
 [0.92853333]
 [0.91553333]
 [0.91063333]
 [0.7407    ]
 [0.737     ]
 [0.83793333]
 [0.824     ]
 [0.82563333]
 [0.5772    ]
 [0.5515    ]
 [0.49453333]
 [0.31843333]
 [0.92456667]
 [0.94646667]
 [0.95036667]
 [0.94076667]
 [0.9155    ]
 [0.89793333]
 [0.7702    ]
 [0.92476667]
 [0.92123333]
 [0.91896667]
 [0.91553333]
 [0.81956667]
 [0.82336667]
 [0.86173333]
 [0.79553333]
 [0.37243333]
 [0.92196667]
 [0.92623333]
 [0.92043333]
 [0.9242    ]
 [0.9156    ]
 [0.9099    ]
 [0.865     ]
 [0.69463333]
 [0.2981    ]
 [0.92236667]
 [0.8345    ]
 [0.72543333]
 [0.82626667]
 [0.9101    ]
 [0.78643333]
 [0.69196667]
 [0.63806667]
 [0.3462    ]
 [0.92196667]
 [0.92103333]
 [0.9068    ]
 [0.91263333]
 [0.90873333]
 [0.9093    ]
 [0.87486667]
 [0.78106667]
 [0.38866667]
 [0.02246667]
 [0.92196667]
 [0.92593333]
 [0.90816667]
 [0.92106667]
 [0.9109    ]
 [0.9121    ]
 [0.86623333]
 [0.78116667]
 [0.39193333]
 [0.02276667]
 [0.92196667]
 [0.92456667]
 [0.90863333]
 [0.9157    ]
 [0.91783333]
 [0.8249    ]
 [0.78143333]
 [0.69826667]
 [0.39193333]
 [0.92613333]
 [0.92293333]
 [0.9093    ]
 [0.90856667]
 [0.90463333]
 [0.88623333]
 [0.87336667]
 [0.8009    ]
 [0.3411    ]
 [0.01933333]
 [0.        ]
 [0.8344    ]
 [0.92103333]
 [0.90856667]
 [0.9144    ]
 [0.81956667]
 [0.8202    ]
 [0.8783    ]
 [0.80133333]
 [0.36993333]
 [0.0213    ]
 [0.        ]
 [0.92196667]
 [0.92103333]
 [0.91476667]
 [0.9144    ]
 [0.90236667]
 [0.87806667]
 [0.85183333]
 [0.71376667]
 [0.30506667]
 [0.0167    ]
 [0.83153333]
 [0.73783333]
 [0.72696667]
 [0.72986667]
 [0.90236667]
 [0.87826667]
 [0.76673333]
 [0.67466667]
 [0.28106667]
 [0.92473333]
 [0.93346667]
 [0.93503333]
 [0.90513333]
 [0.90503333]
 [0.87786667]
 [0.74743333]
 [0.44653333]
 [0.1602    ]
 [0.92626667]
 [0.9386    ]
 [0.9374    ]
 [0.90716667]
 [0.81213333]
 [0.88676667]
 [0.83873333]
 [0.64      ]
 [0.22886667]
 [0.92556667]
 [0.93563333]
 [0.93943333]
 [0.90893333]
 [0.90616667]
 [0.87896667]
 [0.83016667]
 [0.64546667]
 [0.73936667]
 [0.72716667]
 [0.726     ]
 [0.90576667]
 [0.9074    ]
 [0.89053333]
 [0.71376667]
 [0.92393333]
 [0.93076667]
 [0.92466667]
 [0.919     ]
 [0.9105    ]
 [0.90826667]
 [0.73996667]
 [0.60356667]
 [0.35273333]
 [0.9374    ]
 [0.9068    ]
 [0.91156667]
 [0.81476667]
 [0.78376667]
 [0.74533333]
 [0.59436667]
 [0.939     ]
 [0.9426    ]
 [0.94876667]
 [0.954     ]
 [0.94613333]
 [0.7099    ]
 [0.73996667]
 [0.57583333]
 [0.93453333]
 [0.92463333]
 [0.91673333]
 [0.94343333]
 [0.92596667]
 [0.89053333]
 [0.6747    ]
 [0.93386667]
 [0.9326    ]
 [0.92056667]
 [0.9436    ]
 [0.66456667]
 [0.5003    ]
 [0.6026    ]
 [0.27746667]
 [0.75203333]
 [0.75153333]
 [0.73483333]
 [0.75106667]
 [0.74076667]
 [0.70643333]
 [0.55113333]
 [0.24633333]
 [0.74626667]
 [0.74663333]
 [0.7315    ]
 [0.7242    ]
 [0.69666667]
 [0.66436667]
 [0.51526667]
 [0.18306667]
 [0.97796667]
 [0.92286667]
 [0.95126667]
 [0.93203333]
 [0.8664    ]
 [0.832     ]
 [0.8181    ]
 [0.60666667]
 [0.99603333]
 [0.9275    ]
 [0.94186667]
 [0.93336667]
 [0.7441    ]
 [0.71483333]
 [0.7251    ]
 [0.5234    ]
 [0.12676667]
 [0.92196667]
 [0.92473333]
 [0.91503333]
 [0.9171    ]
 [0.9446    ]
 [0.8959    ]
 [0.87016667]
 [0.72956667]
 [0.27533333]
 [0.96206667]
 [0.86333333]
 [0.86216667]
 [0.76416667]
 [0.756     ]
 [0.74076667]
 [0.71673333]
 [0.59863333]
 [0.18846667]
 [0.96596667]
 [0.96363333]
 [0.9583    ]
 [0.9552    ]
 [0.95      ]
 [0.92596667]
 [0.8974    ]
 [0.76766667]
 [0.20596667]
 [0.00503333]
 [0.96846667]
 [0.96363333]
 [0.9616    ]
 [0.9552    ]
 [0.95      ]
 [0.92596667]
 [0.88663333]
 [0.75743333]
 [0.23426667]
 [0.92196667]
 [0.92103333]
 [0.9068    ]
 [0.90693333]
 [0.90326667]
 [0.90243333]
 [0.87916667]
 [0.57983333]
 [0.21093333]
 [0.95373333]
 [0.93163333]
 [0.93036667]
 [0.93206667]
 [0.93726667]
 [0.91026667]
 [0.7636    ]
 [0.6073    ]
 [0.18306667]
 [0.96083333]
 [0.92233333]
 [0.90866667]
 [0.90966667]
 [0.90236667]
 [0.87976667]
 [0.8222    ]
 [0.6484    ]
 [0.22886667]
 [0.82976667]
 [0.8321    ]
 [0.91196667]
 [0.81583333]
 [0.6497    ]
 [0.49086667]
 [0.59793333]
 [0.5747    ]
 [0.20596667]
 [0.82976667]
 [0.82893333]
 [0.81613333]
 [0.6591    ]
 [0.58003333]
 [0.55733333]
 [0.40286667]
 [0.38563333]
 [0.38703333]
 [0.3811    ]
 [0.38356667]
 [0.38253333]
 [0.4381    ]
 [0.35406667]
 [0.1929    ]
 [0.01676667]
 [0.0828    ]
 [0.08283333]
 [0.082     ]
 [0.0822    ]
 [0.0819    ]
 [0.08046667]
 [0.07586667]
 [0.0574    ]
 [0.39023333]
 [0.27863333]
 [0.27263333]
 [0.27396667]
 [0.2749    ]
 [0.44023333]
 [0.56633333]
 [0.51426667]
 [0.50846667]
 [0.5007    ]
 [0.53933333]
 [0.2123    ]
 [0.43786667]
 [0.37723333]
 [0.08256667]
 [0.26853333]
 [0.31293333]
 [0.647     ]
 [0.38296667]
 [0.378     ]
 [0.38356667]
 [0.43863333]
 [0.50653333]
 [0.56166667]
 [0.68306667]
 [0.52456667]
 [0.5601    ]
 [0.9214    ]
 [0.65593333]
 [0.8941    ]
 [0.8       ]
 [0.64013333]
 [0.8526    ]
 [0.5256    ]
 [0.4984    ]
 [0.58486667]
 [0.58226667]
 [0.71526667]
 [0.71113333]
 [0.70473333]
 [0.1301    ]
 [0.9487    ]
 [0.93423333]
 [0.89173333]
 [0.91693333]
 [0.91146667]
 [0.8941    ]
 [0.89443333]
 [0.71126667]
 [0.1301    ]
 [0.89813333]
 [0.88903333]
 [0.9238    ]
 [0.9137    ]
 [0.90866667]
 [0.87236667]
 [0.62396667]
 [0.1301    ]
 [0.91223333]
 [0.90286667]
 [0.88903333]
 [0.91323333]
 [0.89513333]
 [0.8941    ]
 [0.84303333]
 [0.89286667]
 [0.9185    ]
 [0.8987    ]
 [0.7185    ]
 [0.7143    ]
 [0.8219    ]
 [0.80806667]
 [0.71526667]
 [0.53956667]
 [0.89286667]
 [0.91323333]
 [0.80966667]
 [0.57223333]
 [0.89813333]
 [0.89673333]
 [0.91323333]
 [0.80633333]
 [0.80466667]
 [0.53956667]
 [0.64686667]
 [0.8975    ]
 [0.91416667]
 [0.8992    ]
 [0.4996    ]
 [0.89216667]
 [0.7821    ]
 [0.86836667]
 [0.91403333]
 [0.87446667]
 [0.8313    ]
 [0.922     ]
 [0.89383333]
 [0.91443333]
 [0.87146667]
 [0.906     ]
 [0.87833333]
 [0.6069    ]
 [0.922     ]
 [0.9105    ]
 [0.9114    ]
 [0.91413333]
 [0.906     ]
 [0.87833333]
 [0.59856667]
 [0.89873333]
 [0.89206667]
 [0.89613333]
 [0.89583333]
 [0.88786667]
 [0.86076667]
 [0.5905    ]
 [0.07903333]
 [0.90356667]
 [0.8923    ]
 [0.8883    ]
 [0.82103333]
 [0.85373333]
 [0.7758    ]
 [0.59476667]
 [0.07676667]
 [0.91063333]
 [0.9003    ]
 [0.8923    ]
 [0.89466667]
 [0.89583333]
 [0.7854    ]
 [0.63586667]
 [0.46996667]
 [0.91063333]
 [0.90356667]
 [0.8923    ]
 [0.89613333]
 [0.89583333]
 [0.78563333]
 [0.71536667]
 [0.52683333]
 [0.83453333]
 [0.89136667]
 [0.87756667]
 [0.8949    ]
 [0.88706667]
 [0.8509    ]
 [0.77896667]
 [0.53383333]
 [0.05713333]
 [0.87463333]
 [0.8788    ]
 [0.87466667]
 [0.87696667]
 [0.84476667]
 [0.69613333]
 [0.46423333]
 [0.85716667]
 [0.8817    ]
 [0.8046    ]
 [0.7149    ]
 [0.62646667]
 [0.7777    ]
 [0.72793333]
 [0.5151    ]
 [0.87166667]
 [0.85193333]
 [0.84953333]
 [0.8389    ]
 [0.84076667]
 [0.61913333]
 [0.79653333]
 [0.85433333]
 [0.85406667]
 [0.842     ]
 [0.84313333]
 [0.76006667]
 [0.47626667]
 [0.86963333]
 [0.84993333]
 [0.85183333]
 [0.84156667]
 [0.84376667]
 [0.75776667]
 [0.52603333]
 [0.04826667]
 [0.8727    ]
 [0.85196667]
 [0.85263333]
 [0.84776667]
 [0.8391    ]
 [0.76006667]
 [0.52973333]
 [0.04583333]
 [0.87186667]
 [0.8762    ]
 [0.8551    ]
 [0.8454    ]
 [0.8481    ]
 [0.84616667]
 [0.75546667]
 [0.52453333]
 [0.0469    ]
 [0.8759    ]
 [0.85326667]
 [0.84663333]
 [0.85206667]
 [0.8462    ]
 [0.7624    ]
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(995, 1)

In [26]:
y_test_scaled_df = pd.DataFrame(y_test_scaled, index=y_test.index, columns=y_test.columns)
y_test_scaled_df

       Generación
15328    0.928800
15329    0.820800
15330    0.788567
15331    0.689433
15332    0.356767
...           ...
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000

[995 rows x 1 columns]

In [27]:
y_scaller_all = MinMaxScaler().fit(y)
print(y_scaller_all)

MinMaxScaler()

In [28]:
y_scaled = y_scaller_all.transform(y)
print(y_scaled)
print(y_scaled.shape)

[[0.91746284]
 [0.68654263]
 [0.95      ]
 ...
 [0.5275    ]
 [0.04833333]
 [0.        ]]
(6630, 1)

In [29]:
y_scaled_df = pd.DataFrame(y_scaled, index=y.index, columns=y.columns)
y_scaled_df

       Generación
36       0.917463
37       0.686543
38       0.950000
39       0.821586
40       0.850000
...           ...
18281    0.846200
18282    0.762400
18283    0.527500
18284    0.048333
18285    0.000000

[6630 rows x 1 columns]

## Definición de modelos

### RandomForest

In [30]:
from lightgbm import LGBMRegressor
import optuna
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.metrics import mean_absolute_percentage_error as mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error as mean_absolute_error
from sklearn.metrics import mean_squared_error as mean_squared_error
from sklearn.metrics import r2_score as r2_score

In [31]:
# Inicializar listas para métricas
LightGBM_model = LGBMRegressor(num_leaves=500, subsample= 0.10698460631792395, colsample_bytree= 0.7272836809565294, min_data_in_leaf= 85)
LightGBM_model.fit(X_train_scaled_df, y_train_scaled_df)
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["LightGBM"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = LightGBM_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.315482 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 635
[LightGBM] [Info] Number of data points in the train set: 4641, number of used features: 6
[LightGBM] [Info] Start training from score 0.608742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85
[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [32]:
resultados

           LightGBM
15328  27737.854623
15329  27486.133289
15330  24127.781396
15331  20469.172397
15332  10001.014624
...             ...
18281  27249.220044
18282  22924.525455
18283  14677.255501
18284   2147.631109
18285     17.321742

[995 rows x 1 columns]

In [33]:
predicciones = y_test.copy()
predicciones

       Generación
15328     27864.0
15329     24624.0
15330     23657.0
15331     20683.0
15332     10703.0
...           ...
18281     25386.0
18282     22872.0
18283     15825.0
18284      1450.0
18285         0.0

[995 rows x 1 columns]

In [34]:
predicciones["LightGBM"] = resultados["LightGBM"]
predicciones

       Generación      LightGBM
15328     27864.0  27737.854623
15329     24624.0  27486.133289
15330     23657.0  24127.781396
15331     20683.0  20469.172397
15332     10703.0  10001.014624
...           ...           ...
18281     25386.0  27249.220044
18282     22872.0  22924.525455
18283     15825.0  14677.255501
18284      1450.0   2147.631109
18285         0.0     17.321742

[995 rows x 2 columns]

In [35]:
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")

MAE: 1509.1542
RMSE: 2532.1425
R²: 0.9059

## Random Forest

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
#Modelo LightGBM
RF_model = RandomForestRegressor(
    criterion="squared_error",
    random_state=0,
    n_estimators=400,
    min_impurity_decrease=0,
    max_depth=None,
    bootstrap=True
)
RF_model.fit(X_train_scaled_df, y_train_scaled_df)
# Inicializar listas para métricas
resultados = pd.DataFrame(index = y_test_scaled_df.index, columns=["Random Forest"])
#Ciclo diario de predicción
for i in range(len(X_test)):
    inicio = i * 1
    fin = inicio + 1

    X_test_seg = X_test_scaled_df.iloc[inicio:fin, :]
    y_test_seg = y_test_scaled_df.iloc[inicio:fin]

    if len(X_test_seg) < 1:
        break

    y_pred = RF_model.predict(X_test_seg)
    y_pred = y_scaler.inverse_transform(y_pred.reshape(-1, 1))
    y_pred = np.clip(y_pred, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

    resultados.iloc[i, 0] = y_pred[0, 0]

In [38]:
predicciones["Random Forest"] = resultados["Random Forest"]
predicciones

       Generación      LightGBM Random Forest
15328     27864.0  27737.854623    27676.1575
15329     24624.0  27486.133289      27436.08
15330     23657.0  24127.781396  24350.938017
15331     20683.0  20469.172397  20043.384431
15332     10703.0  10001.014624      10626.32
...           ...           ...           ...
18281     25386.0  27249.220044  26034.882309
18282     22872.0  22924.525455  23229.408141
18283     15825.0  14677.255501  15735.242934
18284      1450.0   2147.631109   2056.066838
18285         0.0     17.321742           0.0

[995 rows x 3 columns]

## Preparación redes neuronales

In [39]:
import numpy as np
import pandas as pd

def create_sliding_window_with_index(data_X, data_y, lookback):
    X, y, indices = [], [], []
    
    # Asegurar que `data_y` tiene los mismos índices que `data_X`
    data_y = data_y.reindex(data_X.index)

    max_index = len(data_X) - lookback

    for i in range(max_index):
        X.append(data_X.iloc[i:i + lookback].values)  # Ventana de entrada
        
        # Obtener el índice correcto en `data_y`
        y_index = data_X.index[i + lookback]

        # Extraer el valor correspondiente de `data_y`
        if y_index in data_y.index:
            y_value = data_y.loc[y_index]
            if isinstance(y_value, pd.Series):  # Si devuelve una serie, extraer el valor
                y_value = y_value.iloc[0]
        else:
            y_value = np.nan  # Si no está, asignamos NaN

        y.append(y_value)
        indices.append(y_index)  # 🔹 Guardamos el índice original de `data_y`

    # Convertimos `X` en un array y `y` en DataFrame conservando sus índices originales
    X_array = np.array(X)
    y_df = pd.DataFrame(y, index=indices, columns=['y'])  # 🔹 Conservamos los índices originales

    return X_array, y_df

In [40]:
lookback = 48  # Puedes ajustar a 24, 72, etc.

# Aplicar la ventana deslizante a cada conjunto
X_train_windowed, y_train_windowed = create_sliding_window_with_index(X_train_scaled_df, y_train_scaled_df, lookback)
X_val_windowed, y_val_windowed = create_sliding_window_with_index(X_val_scaled_df, y_val_scaled_df, lookback)
X_test_windowed, y_test_windowed = create_sliding_window_with_index(X_test_scaled_df, y_test_scaled_df, lookback)

In [41]:
print(f'X_train: {X_train_windowed.shape}, y_train: {y_train_windowed.shape}')
print(f'X_val: {X_val_windowed.shape}, y_val: {y_val_windowed.shape}')
print(f'X_test: {X_test_windowed.shape}, y_test: {y_test_windowed.shape}')

X_train: (4593, 48, 6), y_train: (4593, 1)
X_val: (946, 48, 6), y_val: (946, 1)
X_test: (947, 48, 6), y_test: (947, 1)

## CTNET

In [42]:
import tensorflow as tf
from tensorflow.keras import layers

In [43]:
def compile_and_fit(model, xtrain=X_train_windowed, ytrain=y_train_windowed, learning_rate=0.0001):
    model.compile(loss=[tf.keras.losses.MeanSquaredError()],
                  optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
                  metrics=[tf.keras.metrics.RootMeanSquaredError(), tf.keras.metrics.MeanAbsolutePercentageError(), tf.keras.metrics.MeanAbsoluteError()])
    
    history = model.fit(xtrain, ytrain, epochs=50,
                        batch_size=512, validation_split=0.2, verbose=1)
    return history

def Loss(train_loss, valid_loss):
    plt.plot(train_loss)
    plt.plot(valid_loss)
    plt.rcParams["figure.figsize"] = (15, 3)
    plt.title('Model Losses')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train Loss', 'Validation Loss'], loc='upper left')
    plt.savefig('out/loss_plot.png')
    plt.show()

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = layers.LayerNormalization()(inputs)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=128, kernel_size=2, activation="relu", padding="same")(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(norm_x, norm_x)
    res = x + inputs
    norm_x = layers.LayerNormalization()(res)
    return norm_x

def build_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, mlp_units, dropout=0, mlp_dropout=0):
    inputs = tf.keras.Input(shape=input_shape)
    x = inputs
    
    for _ in range(num_transformer_blocks):
        enc_out = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    
    x = layers.MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(enc_out, enc_out)
    res = x + enc_out
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    x = layers.Dense(832, activation="relu")(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(mlp_dropout)(x)

    outputs = layers.Dense(1)(x)
    
    return tf.keras.Model(inputs, outputs)

In [44]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=4, num_heads=3, ff_dim=32, num_transformer_blocks=3, mlp_units=[256], mlp_dropout=0.3, dropout=0.2)

In [45]:
history = compile_and_fit(CTNET)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 167s 4s/step - loss: 0.5130 - mean_absolute_error: 0.6209 - mean_absolute_percentage_error: 219284.8906 - root_mean_squared_error: 0.7162 - val_loss: 0.3864 - val_mean_absolute_error: 0.5393 - val_mean_absolute_percentage_error: 1300079.7500 - val_root_mean_squared_error: 0.6216
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 27s 2s/step - loss: 0.4971 - mean_absolute_error: 0.6105 - mean_absolute_percentage_error: 1390103.2500 - root_mean_squared_error: 0.7051 - val_loss: 0.3710 - val_mean_absolute_error: 0.5288 - val_mean_absolute_percentage_error: 3022328.2500 - val_root_mean_squared_error: 0.6091
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 35s 3s/step - loss: 0.4870 - mean_absolute_error: 0.6063 - mean_absolute_percentage_error: 3020765.2500 - root_mean_squared_error: 0.6978 - val_loss: 0.3505 - val_mean_absolute_error: 0.5150 - val_mean_absolute_percentage_error: 5394609.0000 - val_root_mean_squared_error: 0.5920
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 36s 2s/step - loss: 0.4494 - mean_absolute_error: 0.5799 - mean_absolute_percentage_error: 5288728.0000 - root_mean_squared_error: 0.6704 - val_loss: 0.3232 - val_mean_absolute_error: 0.4968 - val_mean_absolute_percentage_error: 8708448.0000 - val_root_mean_squared_error: 0.5685
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - loss: 0.4181 - mean_absolute_error: 0.5611 - mean_absolute_percentage_error: 8095576.5000 - root_mean_squared_error: 0.6466 - val_loss: 0.2872 - val_mean_absolute_error: 0.4712 - val_mean_absolute_percentage_error: 13409408.0000 - val_root_mean_squared_error: 0.5359
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 30s 3s/step - loss: 0.3770 - mean_absolute_error: 0.5365 - mean_absolute_percentage_error: 12861175.0000 - root_mean_squared_error: 0.6140 - val_loss: 0.2420 - val_mean_absolute_error: 0.4377 - val_mean_absolute_percentage_error: 19993380.0000 - val_root_mean_squared_error: 0.4919
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 43s 3s/step - loss: 0.3197 - mean_absolute_error: 0.4966 - mean_absolute_percentage_error: 19096858.0000 - root_mean_squared_error: 0.5653 - val_loss: 0.1903 - val_mean_absolute_error: 0.3944 - val_mean_absolute_percentage_error: 28987584.0000 - val_root_mean_squared_error: 0.4362
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 51s 4s/step - loss: 0.2586 - mean_absolute_error: 0.4520 - mean_absolute_percentage_error: 26294414.0000 - root_mean_squared_error: 0.5084 - val_loss: 0.1397 - val_mean_absolute_error: 0.3405 - val_mean_absolute_percentage_error: 40867196.0000 - val_root_mean_squared_error: 0.3737
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 29s 2s/step - loss: 0.1948 - mean_absolute_error: 0.4007 - mean_absolute_percentage_error: 38793400.0000 - root_mean_squared_error: 0.4413 - val_loss: 0.1054 - val_mean_absolute_error: 0.2850 - val_mean_absolute_percentage_error: 55172132.0000 - val_root_mean_squared_error: 0.3246
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 25s 2s/step - loss: 0.1556 - mean_absolute_error: 0.3616 - mean_absolute_percentage_error: 48757060.0000 - root_mean_squared_error: 0.3944 - val_loss: 0.1002 - val_mean_absolute_error: 0.2522 - val_mean_absolute_percentage_error: 69451008.0000 - val_root_mean_squared_error: 0.3165
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 30s 4s/step - loss: 0.1398 - mean_absolute_error: 0.3294 - mean_absolute_percentage_error: 60193372.0000 - root_mean_squared_error: 0.3739 - val_loss: 0.1105 - val_mean_absolute_error: 0.2492 - val_mean_absolute_percentage_error: 77887408.0000 - val_root_mean_squared_error: 0.3324
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 35s 2s/step - loss: 0.1403 - mean_absolute_error: 0.3185 - mean_absolute_percentage_error: 64034240.0000 - root_mean_squared_error: 0.3746 - val_loss: 0.1068 - val_mean_absolute_error: 0.2477 - val_mean_absolute_percentage_error: 76073784.0000 - val_root_mean_squared_error: 0.3268
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 28s 3s/step - loss: 0.1356 - mean_absolute_error: 0.3160 - mean_absolute_percentage_error: 66127328.0000 - root_mean_squared_error: 0.3681 - val_loss: 0.1004 - val_mean_absolute_error: 0.2484 - val_mean_absolute_percentage_error: 71428912.0000 - val_root_mean_squared_error: 0.3168
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 37s 2s/step - loss: 0.1277 - mean_absolute_error: 0.3101 - mean_absolute_percentage_error: 57288528.0000 - root_mean_squared_error: 0.3574 - val_loss: 0.0990 - val_mean_absolute_error: 0.2490 - val_mean_absolute_percentage_error: 70320000.0000 - val_root_mean_squared_error: 0.3147
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.1237 - mean_absolute_error: 0.3003 - mean_absolute_percentage_error: 56687140.0000 - root_mean_squared_error: 0.3517 - val_loss: 0.0995 - val_mean_absolute_error: 0.2476 - val_mean_absolute_percentage_error: 71159352.0000 - val_root_mean_squared_error: 0.3154
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 27s 3s/step - loss: 0.1218 - mean_absolute_error: 0.2939 - mean_absolute_percentage_error: 58955324.0000 - root_mean_squared_error: 0.3490 - val_loss: 0.0992 - val_mean_absolute_error: 0.2484 - val_mean_absolute_percentage_error: 70666472.0000 - val_root_mean_squared_error: 0.3150
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 38s 2s/step - loss: 0.1196 - mean_absolute_error: 0.2873 - mean_absolute_percentage_error: 54760464.0000 - root_mean_squared_error: 0.3458 - val_loss: 0.0994 - val_mean_absolute_error: 0.2494 - val_mean_absolute_percentage_error: 70306136.0000 - val_root_mean_squared_error: 0.3152
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 22s 2s/step - loss: 0.1214 - mean_absolute_error: 0.2874 - mean_absolute_percentage_error: 59472224.0000 - root_mean_squared_error: 0.3485 - val_loss: 0.0987 - val_mean_absolute_error: 0.2535 - val_mean_absolute_percentage_error: 68196232.0000 - val_root_mean_squared_error: 0.3141
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 19s 2s/step - loss: 0.1233 - mean_absolute_error: 0.2918 - mean_absolute_percentage_error: 60642304.0000 - root_mean_squared_error: 0.3511 - val_loss: 0.0985 - val_mean_absolute_error: 0.2559 - val_mean_absolute_percentage_error: 67083424.0000 - val_root_mean_squared_error: 0.3139
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 27s 2s/step - loss: 0.1189 - mean_absolute_error: 0.2846 - mean_absolute_percentage_error: 59928040.0000 - root_mean_squared_error: 0.3449 - val_loss: 0.0991 - val_mean_absolute_error: 0.2546 - val_mean_absolute_percentage_error: 67929600.0000 - val_root_mean_squared_error: 0.3148
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 18s 2s/step - loss: 0.1193 - mean_absolute_error: 0.2834 - mean_absolute_percentage_error: 59464052.0000 - root_mean_squared_error: 0.3455 - val_loss: 0.0988 - val_mean_absolute_error: 0.2581 - val_mean_absolute_percentage_error: 66280200.0000 - val_root_mean_squared_error: 0.3143
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 23s 2s/step - loss: 0.1186 - mean_absolute_error: 0.2850 - mean_absolute_percentage_error: 58909744.0000 - root_mean_squared_error: 0.3444 - val_loss: 0.0984 - val_mean_absolute_error: 0.2585 - val_mean_absolute_percentage_error: 65831208.0000 - val_root_mean_squared_error: 0.3138
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 25s 2s/step - loss: 0.1151 - mean_absolute_error: 0.2787 - mean_absolute_percentage_error: 55433140.0000 - root_mean_squared_error: 0.3392 - val_loss: 0.0981 - val_mean_absolute_error: 0.2593 - val_mean_absolute_percentage_error: 65180168.0000 - val_root_mean_squared_error: 0.3131
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 34s 1s/step - loss: 0.1157 - mean_absolute_error: 0.2810 - mean_absolute_percentage_error: 58194888.0000 - root_mean_squared_error: 0.3401 - val_loss: 0.0977 - val_mean_absolute_error: 0.2618 - val_mean_absolute_percentage_error: 63829960.0000 - val_root_mean_squared_error: 0.3126
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.1180 - mean_absolute_error: 0.2847 - mean_absolute_percentage_error: 56211412.0000 - root_mean_squared_error: 0.3435 - val_loss: 0.0975 - val_mean_absolute_error: 0.2592 - val_mean_absolute_percentage_error: 64747260.0000 - val_root_mean_squared_error: 0.3122
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 21s 2s/step - loss: 0.1154 - mean_absolute_error: 0.2784 - mean_absolute_percentage_error: 58785192.0000 - root_mean_squared_error: 0.3396 - val_loss: 0.0970 - val_mean_absolute_error: 0.2614 - val_mean_absolute_percentage_error: 63315720.0000 - val_root_mean_squared_error: 0.3115
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 25s 2s/step - loss: 0.1174 - mean_absolute_error: 0.2849 - mean_absolute_percentage_error: 57492268.0000 - root_mean_squared_error: 0.3426 - val_loss: 0.0967 - val_mean_absolute_error: 0.2608 - val_mean_absolute_percentage_error: 63235572.0000 - val_root_mean_squared_error: 0.3109
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 22s 2s/step - loss: 0.1175 - mean_absolute_error: 0.2822 - mean_absolute_percentage_error: 54384816.0000 - root_mean_squared_error: 0.3427 - val_loss: 0.0964 - val_mean_absolute_error: 0.2590 - val_mean_absolute_percentage_error: 63753408.0000 - val_root_mean_squared_error: 0.3105
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 44s 2s/step - loss: 0.1175 - mean_absolute_error: 0.2796 - mean_absolute_percentage_error: 56152636.0000 - root_mean_squared_error: 0.3428 - val_loss: 0.0961 - val_mean_absolute_error: 0.2627 - val_mean_absolute_percentage_error: 61505588.0000 - val_root_mean_squared_error: 0.3101
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.1137 - mean_absolute_error: 0.2767 - mean_absolute_percentage_error: 56122180.0000 - root_mean_squared_error: 0.3373 - val_loss: 0.0955 - val_mean_absolute_error: 0.2577 - val_mean_absolute_percentage_error: 63246368.0000 - val_root_mean_squared_error: 0.3091
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 18s 2s/step - loss: 0.1143 - mean_absolute_error: 0.2769 - mean_absolute_percentage_error: 57010760.0000 - root_mean_squared_error: 0.3381 - val_loss: 0.0952 - val_mean_absolute_error: 0.2622 - val_mean_absolute_percentage_error: 60523904.0000 - val_root_mean_squared_error: 0.3086
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 30s 3s/step - loss: 0.1127 - mean_absolute_error: 0.2786 - mean_absolute_percentage_error: 51873384.0000 - root_mean_squared_error: 0.3357 - val_loss: 0.0944 - val_mean_absolute_error: 0.2594 - val_mean_absolute_percentage_error: 60936964.0000 - val_root_mean_squared_error: 0.3073
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 53s 4s/step - loss: 0.1071 - mean_absolute_error: 0.2668 - mean_absolute_percentage_error: 51183232.0000 - root_mean_squared_error: 0.3272 - val_loss: 0.0940 - val_mean_absolute_error: 0.2589 - val_mean_absolute_percentage_error: 60502812.0000 - val_root_mean_squared_error: 0.3066
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 41s 3s/step - loss: 0.1083 - mean_absolute_error: 0.2722 - mean_absolute_percentage_error: 53174624.0000 - root_mean_squared_error: 0.3290 - val_loss: 0.0947 - val_mean_absolute_error: 0.2660 - val_mean_absolute_percentage_error: 56573988.0000 - val_root_mean_squared_error: 0.3078
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 27s 3s/step - loss: 0.1079 - mean_absolute_error: 0.2715 - mean_absolute_percentage_error: 51466468.0000 - root_mean_squared_error: 0.3284 - val_loss: 0.0930 - val_mean_absolute_error: 0.2591 - val_mean_absolute_percentage_error: 58500076.0000 - val_root_mean_squared_error: 0.3050
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 47s 3s/step - loss: 0.1060 - mean_absolute_error: 0.2624 - mean_absolute_percentage_error: 52908992.0000 - root_mean_squared_error: 0.3256 - val_loss: 0.0923 - val_mean_absolute_error: 0.2603 - val_mean_absolute_percentage_error: 56399128.0000 - val_root_mean_squared_error: 0.3038
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - loss: 0.1037 - mean_absolute_error: 0.2596 - mean_absolute_percentage_error: 52309416.0000 - root_mean_squared_error: 0.3220 - val_loss: 0.0918 - val_mean_absolute_error: 0.2624 - val_mean_absolute_percentage_error: 53758512.0000 - val_root_mean_squared_error: 0.3030
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 26s 3s/step - loss: 0.1013 - mean_absolute_error: 0.2618 - mean_absolute_percentage_error: 48721588.0000 - root_mean_squared_error: 0.3182 - val_loss: 0.0889 - val_mean_absolute_error: 0.2564 - val_mean_absolute_percentage_error: 53687564.0000 - val_root_mean_squared_error: 0.2982
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 43s 2s/step - loss: 0.0990 - mean_absolute_error: 0.2557 - mean_absolute_percentage_error: 51807444.0000 - root_mean_squared_error: 0.3146 - val_loss: 0.0877 - val_mean_absolute_error: 0.2568 - val_mean_absolute_percentage_error: 50854596.0000 - val_root_mean_squared_error: 0.2961
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - loss: 0.0976 - mean_absolute_error: 0.2540 - mean_absolute_percentage_error: 50717108.0000 - root_mean_squared_error: 0.3124 - val_loss: 0.0854 - val_mean_absolute_error: 0.2528 - val_mean_absolute_percentage_error: 49495260.0000 - val_root_mean_squared_error: 0.2922
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 36s 4s/step - loss: 0.0944 - mean_absolute_error: 0.2518 - mean_absolute_percentage_error: 47805824.0000 - root_mean_squared_error: 0.3072 - val_loss: 0.0832 - val_mean_absolute_error: 0.2494 - val_mean_absolute_percentage_error: 47495696.0000 - val_root_mean_squared_error: 0.2884
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 34s 2s/step - loss: 0.0875 - mean_absolute_error: 0.2338 - mean_absolute_percentage_error: 48580148.0000 - root_mean_squared_error: 0.2958 - val_loss: 0.0833 - val_mean_absolute_error: 0.2517 - val_mean_absolute_percentage_error: 43117392.0000 - val_root_mean_squared_error: 0.2887
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 33s 4s/step - loss: 0.0835 - mean_absolute_error: 0.2356 - mean_absolute_percentage_error: 44085980.0000 - root_mean_squared_error: 0.2890 - val_loss: 0.0775 - val_mean_absolute_error: 0.2386 - val_mean_absolute_percentage_error: 43987616.0000 - val_root_mean_squared_error: 0.2784
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - loss: 0.0781 - mean_absolute_error: 0.2207 - mean_absolute_percentage_error: 45506360.0000 - root_mean_squared_error: 0.2794 - val_loss: 0.0832 - val_mean_absolute_error: 0.2506 - val_mean_absolute_percentage_error: 36532992.0000 - val_root_mean_squared_error: 0.2885
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 48s 3s/step - loss: 0.0783 - mean_absolute_error: 0.2267 - mean_absolute_percentage_error: 37046192.0000 - root_mean_squared_error: 0.2798 - val_loss: 0.0709 - val_mean_absolute_error: 0.2242 - val_mean_absolute_percentage_error: 40612924.0000 - val_root_mean_squared_error: 0.2663
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 41s 3s/step - loss: 0.0775 - mean_absolute_error: 0.2210 - mean_absolute_percentage_error: 40022432.0000 - root_mean_squared_error: 0.2783 - val_loss: 0.0736 - val_mean_absolute_error: 0.2296 - val_mean_absolute_percentage_error: 35869560.0000 - val_root_mean_squared_error: 0.2712
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 47s 3s/step - loss: 0.0701 - mean_absolute_error: 0.2091 - mean_absolute_percentage_error: 38784436.0000 - root_mean_squared_error: 0.2647 - val_loss: 0.0745 - val_mean_absolute_error: 0.2303 - val_mean_absolute_percentage_error: 33358786.0000 - val_root_mean_squared_error: 0.2730
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 46s 3s/step - loss: 0.0676 - mean_absolute_error: 0.2070 - mean_absolute_percentage_error: 33775980.0000 - root_mean_squared_error: 0.2601 - val_loss: 0.0695 - val_mean_absolute_error: 0.2195 - val_mean_absolute_percentage_error: 33918224.0000 - val_root_mean_squared_error: 0.2637
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 43s 3s/step - loss: 0.0642 - mean_absolute_error: 0.1999 - mean_absolute_percentage_error: 34353624.0000 - root_mean_squared_error: 0.2534 - val_loss: 0.0684 - val_mean_absolute_error: 0.2157 - val_mean_absolute_percentage_error: 31921050.0000 - val_root_mean_squared_error: 0.2616
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 38s 2s/step - loss: 0.0654 - mean_absolute_error: 0.2035 - mean_absolute_percentage_error: 33563224.0000 - root_mean_squared_error: 0.2557 - val_loss: 0.0679 - val_mean_absolute_error: 0.2146 - val_mean_absolute_percentage_error: 32508442.0000 - val_root_mean_squared_error: 0.2605

In [46]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

30/30 ━━━━━━━━━━━━━━━━━━━━ 20s 345ms/step

array([[1.0051659 ],
       [0.9844358 ],
       [0.9281856 ],
       [0.82589674],
       [0.6822431 ],
       [0.5137037 ],
       [0.413108  ],
       [0.424401  ],
       [0.46983272],
       [0.589653  ],
       [0.71471566],
       [0.90906227],
       [0.99732184],
       [1.0190831 ],
       [1.0057576 ],
       [0.9430485 ],
       [0.8490745 ],
       [0.71833706],
       [0.5719695 ],
       [0.46737096],
       [0.42903793],
       [0.44474506],
       [0.57215726],
       [0.7105497 ],
       [0.9269676 ],
       [1.0104309 ],
       [1.0308535 ],
       [1.0132079 ],
       [0.9524594 ],
       [0.831304  ],
       [0.6687016 ],
       [0.4870611 ],
       [0.31443477],
       [0.30039173],
       [0.45712364],
       [0.67290497],
       [0.9284841 ],
       [1.0110314 ],
       [1.0216775 ],
       [1.0044352 ],
       [0.95721793],
       [0.8643916 ],
       [0.68307805],
       [0.43146735],
       [0.28537363],
       [0.30590123],
       [0.45054734],
       [0.6488544 ],
       [0.91077334],
       [1.0042212 ],
       [1.0106416 ],
       [0.98080504],
       [0.93030334],
       [0.83912086],
       [0.6639001 ],
       [0.47467527],
       [0.28817093],
       [0.32293037],
       [0.4641648 ],
       [0.6327327 ],
       [0.9015127 ],
       [0.99397624],
       [1.0063794 ],
       [0.9706011 ],
       [0.91744643],
       [0.82758504],
       [0.67072797],
       [0.4859863 ],
       [0.28462127],
       [0.28693816],
       [0.40388736],
       [0.5974972 ],
       [0.88378954],
       [0.9801712 ],
       [0.9932718 ],
       [0.9798608 ],
       [0.94217384],
       [0.84441537],
       [0.657865  ],
       [0.3440838 ],
       [0.20949489],
       [0.26437563],
       [0.45382118],
       [0.8262434 ],
       [0.96620804],
       [0.9967083 ],
       [0.98534346],
       [0.94932026],
       [0.8756232 ],
       [0.7258237 ],
       [0.5423182 ],
       [0.2952993 ],
       [0.28620893],
       [0.41171548],
       [0.5911938 ],
       [0.8811915 ],
       [0.9829141 ],
       [0.994932  ],
       [0.98292005],
       [0.9377018 ],
       [0.850248  ],
       [0.68715084],
       [0.4854734 ],
       [0.27648816],
       [0.29462105],
       [0.43376464],
       [0.61175716],
       [0.889592  ],
       [0.9802846 ],
       [1.0028943 ],
       [0.9832695 ],
       [0.9329213 ],
       [0.83176315],
       [0.66071993],
       [0.47175813],
       [0.23998678],
       [0.25630584],
       [0.40073696],
       [0.5940397 ],
       [0.89478457],
       [0.9859109 ],
       [0.99062335],
       [0.9824276 ],
       [0.94913304],
       [0.83951396],
       [0.56627905],
       [0.27625436],
       [0.2028623 ],
       [0.2939496 ],
       [0.48273054],
       [0.8364177 ],
       [0.9588949 ],
       [0.979705  ],
       [0.96639955],
       [0.92457044],
       [0.84117746],
       [0.6881983 ],
       [0.52060264],
       [0.33360943],
       [0.2988773 ],
       [0.3905798 ],
       [0.5467502 ],
       [0.843943  ],
       [0.9538559 ],
       [0.9710596 ],
       [0.9605222 ],
       [0.9267074 ],
       [0.84612024],
       [0.6891258 ],
       [0.5149195 ],
       [0.32931656],
       [0.28746092],
       [0.390483  ],
       [0.5601585 ],
       [0.86314297],
       [0.96340823],
       [0.9833136 ],
       [0.97029585],
       [0.9288744 ],
       [0.8399885 ],
       [0.6796508 ],
       [0.50354725],
       [0.35209072],
       [0.28195968],
       [0.37920427],
       [0.5668671 ],
       [0.8722429 ],
       [0.97381353],
       [0.99278414],
       [0.97991806],
       [0.93944114],
       [0.84896946],
       [0.6738149 ],
       [0.43451354],
       [0.27051425],
       [0.28715438],
       [0.43596673],
       [0.7174126 ],
       [0.8453067 ],
       [0.88527656],
       [0.89217156],
       [0.8784304 ],
       [0.9003774 ],
       [0.85662466],
       [0.74070305],
       [0.68308586],
       [0.6568756 ],
       [0.66635126],
       [0.6801288 ],
       [0.7000823 ],
       [0.727991  ],
       [0.7682817 ],
       [0.7342148 ],
       [0.7347479 ],
       [0.7382183 ],
       [0.87059474],
       [0.9114038 ],
       [0.90401244],
       [0.88113046],
       [0.8547524 ],
       [0.8144696 ],
       [0.72174233],
       [0.5984547 ],
       [0.53943074],
       [0.73190403],
       [0.84045285],
       [0.9100602 ],
       [0.9333773 ],
       [0.93053466],
       [0.8967461 ],
       [0.82699037],
       [0.72288084],
       [0.7448052 ],
       [0.76862687],
       [0.8092494 ],
       [0.84335357],
       [0.85155   ],
       [0.8485105 ],
       [0.82184196],
       [0.78818125],
       [0.7462785 ],
       [0.82720333],
       [0.8645927 ],
       [0.8911294 ],
       [0.899223  ],
       [0.8797625 ],
       [0.8581289 ],
       [0.851194  ],
       [0.83723664],
       [0.8235345 ],
       [0.8010917 ],
       [0.8275827 ],
       [0.8570523 ],
       [0.8711045 ],
       [0.863017  ],
       [0.8501909 ],
       [0.83558214],
       [0.8300725 ],
       [0.821288  ],
       [0.8702632 ],
       [0.88487864],
       [0.88283855],
       [0.88559556],
       [0.8746225 ],
       [0.8567077 ],
       [0.8173936 ],
       [0.7578849 ],
       [0.7946954 ],
       [0.8309243 ],
       [0.86265457],
       [0.8872965 ],
       [0.89473516],
       [0.8741531 ],
       [0.8293943 ],
       [0.76821816],
       [0.83143264],
       [0.86225784],
       [0.87766325],
       [0.88996637],
       [0.8928289 ],
       [0.871541  ],
       [0.7966331 ],
       [0.7330845 ],
       [0.68262446],
       [0.6848769 ],
       [0.8517568 ],
       [0.9158483 ],
       [0.9327263 ],
       [0.94016945],
       [0.9237085 ],
       [0.79870385],
       [0.6716727 ],
       [0.6096101 ],
       [0.5600235 ],
       [0.61669976],
       [0.8365692 ],
       [0.93348897],
       [0.9466473 ],
       [0.9202848 ],
       [0.87384325],
       [0.7542569 ],
       [0.6216326 ],
       [0.52527016],
       [0.514343  ],
       [0.59661627],
       [0.8379053 ],
       [0.9268637 ],
       [0.92641985],
       [0.9015397 ],
       [0.83320725],
       [0.6696859 ],
       [0.41519743],
       [0.31590652],
       [0.34673768],
       [0.45056623],
       [0.75821304],
       [0.8815385 ],
       [0.9126839 ],
       [0.9020835 ],
       [0.8569762 ],
       [0.77207524],
       [0.5283149 ],
       [0.33557156],
       [0.24078667],
       [0.321187  ],
       [0.6574973 ],
       [0.81371754],
       [0.8565011 ],
       [0.85320544],
       [0.8369671 ],
       [0.68078387],
       [0.6790629 ],
       [0.61579144],
       [0.5515593 ],
       [0.47604817],
       [0.65415394],
       [0.7368942 ],
       [0.7591392 ],
       [0.76679254],
       [0.7585264 ],
       [0.70205754],
       [0.6890751 ],
       [0.7845615 ],
       [0.80990815],
       [0.79673415],
       [0.78183836],
       [0.75670385],
       [0.65433574],
       [0.58545256],
       [0.5638346 ],
       [0.728047  ],
       [0.7872053 ],
       [0.8478145 ],
       [0.8675281 ],
       [0.82751197],
       [0.7135231 ],
       [0.5501946 ],
       [0.49559176],
       [0.54590786],
       [0.7423901 ],
       [0.8407896 ],
       [0.88083696],
       [0.89856905],
       [0.869486  ],
       [0.67010105],
       [0.47456902],
       [0.39988962],
       [0.46027476],
       [0.6798923 ],
       [0.8017764 ],
       [0.85990226],
       [0.8708532 ],
       [0.811573  ],
       [0.76503855],
       [0.6744549 ],
       [0.5906685 ],
       [0.6007029 ],
       [0.63909745],
       [0.71003854],
       [0.7319354 ],
       [0.72527546],
       [0.705011  ],
       [0.67540026],
       [0.62200916],
       [0.6202774 ],
       [0.66766953],
       [0.7694894 ],
       [0.80077815],
       [0.7977777 ],
       [0.78792524],
       [0.77064013],
       [0.7226764 ],
       [0.6883824 ],
       [0.6122688 ],
       [0.5611358 ],
       [0.7158276 ],
       [0.80149317],
       [0.83882296],
       [0.833894  ],
       [0.81996465],
       [0.80415577],
       [0.74845886],
       [0.6565851 ],
       [0.70509285],
       [0.7355461 ],
       [0.7743613 ],
       [0.81053054],
       [0.8239744 ],
       [0.8262761 ],
       [0.7964268 ],
       [0.7422528 ],
       [0.7732553 ],
       [0.7954085 ],
       [0.81834155],
       [0.84637487],
       [0.8520882 ],
       [0.83428884],
       [0.78343064],
       [0.73213756],
       [0.7651479 ],
       [0.77796334],
       [0.7994016 ],
       [0.83135474],
       [0.83473945],
       [0.79549587],
       [0.7618946 ],
       [0.81560504],
       [0.82227445],
       [0.81536597],
       [0.8219253 ],
       [0.8154134 ],
       [0.81049466],
       [0.8626349 ],
       [0.86176836],
       [0.845273  ],
       [0.8367795 ],
       [0.8325816 ],
       [0.8373105 ],
       [0.82907045],
       [0.8178225 ],
       [0.81465185],
       [0.82493025],
       [0.8475941 ],
       [0.86151826],
       [0.86781776],
       [0.8631403 ],
       [0.8490722 ],
       [0.8018676 ],
       [0.77707183],
       [0.7436613 ],
       [0.841066  ],
       [0.876793  ],
       [0.89286613],
       [0.89525014],
       [0.86652994],
       [0.82934475],
       [0.7841126 ],
       [0.81502116],
       [0.81898034],
       [0.82966363],
       [0.8533816 ],
       [0.87642443],
       [0.8684847 ],
       [0.82299316],
       [0.75661373],
       [0.69818413],
       [0.7931967 ],
       [0.8572852 ],
       [0.8936819 ],
       [0.90734965],
       [0.89825845],
       [0.87262803],
       [0.8313669 ],
       [0.77321947],
       [0.70141983],
       [0.78675234],
       [0.8500318 ],
       [0.88944423],
       [0.9047322 ],
       [0.90749115],
       [0.89569044],
       [0.83199203],
       [0.7147403 ],
       [0.60975087],
       [0.7575932 ],
       [0.84573245],
       [0.89235425],
       [0.91477543],
       [0.9177167 ],
       [0.88352114],
       [0.7530652 ],
       [0.58385444],
       [0.46683896],
       [0.49367046],
       [0.80806875],
       [0.9315778 ],
       [0.962233  ],
       [0.9617153 ],
       [0.94181263],
       [0.8963698 ],
       [0.7453686 ],
       [0.47093964],
       [0.34168655],
       [0.4325896 ],
       [0.7796385 ],
       [0.93027127],
       [0.9691899 ],
       [0.9765241 ],
       [0.96812725],
       [0.89468896],
       [0.66184473],
       [0.4538904 ],
       [0.36328328],
       [0.6282904 ],
       [0.77933747],
       [0.8682843 ],
       [0.90477645],
       [0.928211  ],
       [0.901247  ],
       [0.6864859 ],
       [0.52722293],
       [0.46836257],
       [0.50357646],
       [0.6135479 ],
       [0.86391103],
       [0.95709777],
       [0.98162186],
       [0.94815683],
       [0.8842657 ],
       [0.7034646 ],
       [0.51147926],
       [0.34122103],
       [0.30732045],
       [0.40791216],
       [0.61161745],
       [0.87928176],
       [0.9758481 ],
       [0.99246055],
       [0.9499638 ],
       [0.88783073],
       [0.78746235],
       [0.56706613],
       [0.30036542],
       [0.20577365],
       [0.33404636],
       [0.7269081 ],
       [0.9021131 ],
       [0.937751  ],
       [0.93716   ],
       [0.9072765 ],
       [0.8746698 ],
       [0.6607536 ],
       [0.38042325],
       [0.27889556],
       [0.59412986],
       [0.7776468 ],
       [0.8572587 ],
       [0.8676703 ],
       [0.8597591 ],
       [0.8277332 ],
       [0.59143555],
       [0.3829441 ],
       [0.32928106],
       [0.64711463],
       [0.83170915],
       [0.9087628 ],
       [0.92391205],
       [0.9042469 ],
       [0.8388093 ],
       [0.56180656],
       [0.34945875],
       [0.30320352],
       [0.6289934 ],
       [0.83207613],
       [0.926002  ],
       [0.9531796 ],
       [0.94443524],
       [0.8958227 ],
       [0.72038513],
       [0.49086994],
       [0.6003493 ],
       [0.7000743 ],
       [0.81148446],
       [0.8705183 ],
       [0.8752136 ],
       [0.78206533],
       [0.65441453],
       [0.78209794],
       [0.78312767],
       [0.789055  ],
       [0.8197832 ],
       [0.86879873],
       [0.8882072 ],
       [0.8094612 ],
       [0.6168629 ],
       [0.53446627],
       [0.7740636 ],
       [0.8620335 ],
       [0.8931804 ],
       [0.9032679 ],
       [0.9078157 ],
       [0.80569446],
       [0.66356903],
       [0.7433878 ],
       [0.7612884 ],
       [0.79298204],
       [0.8378581 ],
       [0.8760992 ],
       [0.87426734],
       [0.7505055 ],
       [0.65642786],
       [0.76927936],
       [0.81272584],
       [0.86309385],
       [0.89815557],
       [0.8746686 ],
       [0.8153449 ],
       [0.7144049 ],
       [0.801776  ],
       [0.817346  ],
       [0.82360435],
       [0.84312725],
       [0.8633789 ],
       [0.7997459 ],
       [0.6859893 ],
       [0.5752341 ],
       [0.77697444],
       [0.864618  ],
       [0.9040778 ],
       [0.92515576],
       [0.7830657 ],
       [0.6808638 ],
       [0.55665123],
       [0.51007354],
       [0.7316859 ],
       [0.82946366],
       [0.89966774],
       [0.93650943],
       [0.75433946],
       [0.5400046 ],
       [0.36147875],
       [0.33729857],
       [0.60493994],
       [0.77642846],
       [0.88586444],
       [0.9560737 ],
       [0.94322896],
       [0.8054888 ],
       [0.43212706],
       [0.2777189 ],
       [0.52956784],
       [0.66945523],
       [0.7871143 ],
       [0.866524  ],
       [0.88574994],
       [0.84695   ],
       [0.55135894],
       [0.35264218],
       [0.30495358],
       [0.6263623 ],
       [0.8048154 ],
       [0.88319266],
       [0.91224015],
       [0.9020127 ],
       [0.84023654],
       [0.5041764 ],
       [0.24781841],
       [0.23377904],
       [0.5785723 ],
       [0.8139633 ],
       [0.9046836 ],
       [0.93271065],
       [0.9182481 ],
       [0.8524287 ],
       [0.5714914 ],
       [0.33874243],
       [0.28122264],
       [0.6024163 ],
       [0.80308264],
       [0.90437424],
       [0.92883015],
       [0.9162008 ],
       [0.8737937 ],
       [0.67526686],
       [0.50341845],
       [0.43901587],
       [0.50745696],
       [0.8120627 ],
       [0.9479545 ],
       [0.9821494 ],
       [0.9692365 ],
       [0.939108  ],
       [0.8706944 ],
       [0.6711096 ],
       [0.39066845],
       [0.32564402],
       [0.6447438 ],
       [0.82835835],
       [0.90922666],
       [0.92584956],
       [0.9309228 ],
       [0.9088681 ],
       [0.7589081 ],
       [0.5392158 ],
       [0.43621314],
       [0.68539286],
       [0.8321725 ],
       [0.8841854 ],
       [0.9032784 ],
       [0.9072694 ],
       [0.8837501 ],
       [0.73762894],
       [0.48362237],
       [0.41459125],
       [0.708156  ],
       [0.87618303],
       [0.936421  ],
       [0.95274943],
       [0.9411961 ],
       [0.8969989 ],
       [0.6420882 ],
       [0.4495923 ],
       [0.37185645],
       [0.6530176 ],
       [0.8377914 ],
       [0.92492497],
       [0.9526705 ],
       [0.9441418 ],
       [0.85608804],
       [0.66427565],
       [0.45444903],
       [0.39103615],
       [0.6704496 ],
       [0.8457037 ],
       [0.9452364 ],
       [0.9597825 ],
       [0.81758165],
       [0.67505884],
       [0.57347786],
       [0.651     ],
       [0.68474305],
       [0.72820044],
       [0.8131482 ],
       [0.8749906 ],
       [0.72004414],
       [0.5881144 ],
       [0.4839867 ],
       [0.5023299 ],
       [0.6675507 ],
       [0.7606459 ],
       [0.81160665],
       [0.826424  ],
       [0.7505224 ],
       [0.5543257 ],
       [0.44031242],
       [0.40269536],
       [0.54093546],
       [0.59129035],
       [0.6266624 ],
       [0.6568494 ],
       [0.6488763 ],
       [0.6718662 ],
       [0.623267  ],
       [0.5753052 ],
       [0.5343464 ],
       [0.48817104],
       [0.49069557],
       [0.5033751 ],
       [0.64764977],
       [0.6865164 ],
       [0.6445549 ],
       [0.5837698 ],
       [0.5347721 ],
       [0.5729896 ],
       [0.55322033],
       [0.53146005],
       [0.5348387 ],
       [0.5582527 ],
       [0.56776744],
       [0.57116413],
       [0.65096295],
       [0.64844143],
       [0.6256651 ],
       [0.6222594 ],
       [0.6460719 ],
       [0.57948875],
       [0.5526716 ],
       [0.52388227],
       [0.6461795 ],
       [0.70452935],
       [0.72407824],
       [0.7405555 ],
       [0.6813436 ],
       [0.67145705],
       [0.61847806],
       [0.5496655 ],
       [0.52341926],
       [0.6808169 ],
       [0.74401224],
       [0.7703818 ],
       [0.78055346],
       [0.7891784 ],
       [0.78608614],
       [0.75342685],
       [0.6917373 ],
       [0.6108883 ],
       [0.7139828 ],
       [0.78195   ],
       [0.81549966],
       [0.81966877],
       [0.8132931 ],
       [0.77076757],
       [0.6966754 ],
       [0.5933151 ],
       [0.70327294],
       [0.7720734 ],
       [0.8199365 ],
       [0.8528664 ],
       [0.85775876],
       [0.844279  ],
       [0.7878065 ],
       [0.7695824 ],
       [0.7384517 ],
       [0.7344789 ],
       [0.77604616],
       [0.8258267 ],
       [0.85559666],
       [0.86026835],
       [0.8327505 ],
       [0.79933643],
       [0.83249104],
       [0.8383565 ],
       [0.8299718 ],
       [0.81138086],
       [0.845587  ],
       [0.86309975],
       [0.85507107],
       [0.8411882 ],
       [0.7957972 ],
       [0.77919793],
       [0.8283789 ],
       [0.84809875],
       [0.8606094 ],
       [0.861807  ],
       [0.8693534 ],
       [0.86909777],
       [0.8651192 ],
       [0.8526819 ],
       [0.83810675],
       [0.81261486],
       [0.8038036 ],
       [0.8488961 ],
       [0.8685231 ],
       [0.8760519 ],
       [0.87015   ],
       [0.8653003 ],
       [0.85864234],
       [0.82812977],
       [0.8477482 ],
       [0.8545596 ],
       [0.85474   ],
       [0.8638584 ],
       [0.8686305 ],
       [0.8653872 ],
       [0.8358952 ],
       [0.84397537],
       [0.8465371 ],
       [0.8530821 ],
       [0.8618106 ],
       [0.87110627],
       [0.86473745],
       [0.8263887 ],
       [0.7695508 ],
       [0.830365  ],
       [0.86837244],
       [0.88909054],
       [0.892931  ],
       [0.8936735 ],
       [0.8679366 ],
       [0.7926628 ],
       [0.7044991 ],
       [0.78098327],
       [0.8377479 ],
       [0.8802408 ],
       [0.9104417 ],
       [0.9144085 ],
       [0.89882004],
       [0.79794604],
       [0.6826218 ],
       [0.7572422 ],
       [0.7960179 ],
       [0.84312177],
       [0.8848117 ],
       [0.9047247 ],
       [0.8917818 ],
       [0.73732173],
       [0.6183021 ],
       [0.7557432 ],
       [0.81030744],
       [0.86154   ],
       [0.9100205 ],
       [0.93074214],
       [0.92034817],
       [0.7152474 ],
       [0.57524407],
       [0.50435024],
       [0.7129066 ],
       [0.85220546],
       [0.92747587],
       [0.9546281 ],
       [0.9472551 ],
       [0.79571354],
       [0.5956613 ],
       [0.6652124 ],
       [0.6878061 ],
       [0.751535  ],
       [0.8271032 ],
       [0.8752259 ],
       [0.80157924],
       [0.7026636 ],
       [0.5800451 ],
       [0.7451243 ],
       [0.81323504],
       [0.8721409 ],
       [0.83685464],
       [0.847546  ],
       [0.79773664],
       [0.8383485 ],
       [0.79496086],
       [0.76176715],
       [0.7611777 ],
       [0.76250374],
       [0.6900469 ],
       [0.655596  ],
       [0.83992416],
       [0.8768756 ],
       [0.8898165 ],
       [0.89485   ],
       [0.8938619 ],
       [0.77322763],
       [0.5838005 ],
       [0.47736466],
       [0.6844927 ],
       [0.81530064],
       [0.89490116],
       [0.9285426 ],
       [0.9329568 ],
       [0.7599893 ],
       [0.55793   ],
       [0.44862324],
       [0.6588496 ],
       [0.790777  ],
       [0.8711802 ],
       [0.9309497 ],
       [0.9491708 ],
       [0.9062679 ],
       [0.62414724],
       [0.40829134],
       [0.37664363],
       [0.6790664 ],
       [0.83723736],
       [0.9246306 ],
       [0.9556459 ],
       [0.95168567],
       [0.7469108 ],
       [0.5356339 ],
       [0.39597416]], dtype=float32)

In [47]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [48]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [49]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
15328     27864.0  27737.854623    27676.1575           NaN
15329     24624.0  27486.133289      27436.08           NaN
15330     23657.0  24127.781396  24350.938017           NaN
15331     20683.0  20469.172397  20043.384431           NaN
15332     10703.0  10001.014624      10626.32           NaN
...           ...           ...           ...           ...
18281     25386.0  27249.220044  26034.882309  28669.376953
18282     22872.0  22924.525455  23229.408141  28550.570312
18283     15825.0  14677.255501  15735.242934  22407.324219
18284      1450.0   2147.631109   2056.066838  16069.017578
18285         0.0     17.321742           0.0  11879.224609

[995 rows x 4 columns]

In [50]:
predicciones["CTNET"] = predicciones["CTNET"].fillna(0)

In [51]:
# import optuna
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Definir la función objetivo para Optuna
# def objective(trial):
#     # Sugerir valores para los hiperparámetros
#     head_size = trial.suggest_int("head_size", 8, 64, step=8)
#     num_heads = trial.suggest_int("num_heads", 2, 8, step=2)
#     ff_dim = trial.suggest_int("ff_dim", 32, 256, step=32)
#     num_transformer_blocks = trial.suggest_int("num_transformer_blocks", 1, 4)
#     mlp_units = trial.suggest_categorical("mlp_units", [[128, 64], [256, 128, 64], [512, 256, 128]])
#     dropout = trial.suggest_float("dropout", 0.1, 0.5, step=0.1)
#     mlp_dropout = trial.suggest_float("mlp_dropout", 0.1, 0.5, step=0.1)
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)

#     # Construcción del modelo con los hiperparámetros sugeridos
#     model = build_model(
#         input_shape=X_train_windowed.shape[1:],
#         head_size=head_size,
#         num_heads=num_heads,
#         ff_dim=ff_dim,
#         num_transformer_blocks=num_transformer_blocks,
#         mlp_units=mlp_units,
#         dropout=dropout,
#         mlp_dropout=mlp_dropout
#     )

#     # Compilar el modelo con los hiperparámetros sugeridos
#     model.compile(
#         loss=tf.keras.losses.MeanSquaredError(),
#         optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
#         metrics=[tf.keras.metrics.RootMeanSquaredError()]
#     )

#     # Entrenamiento con un número reducido de épocas para acelerar la búsqueda
#     history = model.fit(
#         X_train_windowed, y_train_windowed,
#         validation_split=0.2,
#         epochs=50,  # Reducimos las épocas para acelerar la búsqueda
#         batch_size=512,
#         verbose=0
#     )

#     # Obtener la métrica de validación (RMSE) y minimizarla
#     val_rmse = min(history.history["val_root_mean_squared_error"])
    
#     return val_rmse  # Queremos minimizar el RMSE

# # Ejecutar la optimización de hiperparámetros
# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=20, timeout=3600)  # 20 iteraciones, máximo 1 hora

# # Mostrar los mejores hiperparámetros encontrados
# best_params = study.best_params
# print(f"Mejores hiperparámetros: {best_params}")

In [52]:
CTNET = build_model((X_train_windowed.shape[1], X_train_windowed.shape[2]), head_size=16, num_heads=8, ff_dim=256, num_transformer_blocks=1, mlp_units=[128,64], mlp_dropout=0.2, dropout=0.2)

In [53]:
history = compile_and_fit(CTNET, learning_rate = 0.0010762230908145116)

Epoch 1/50

8/8 ━━━━━━━━━━━━━━━━━━━━ 265s 9s/step - loss: 0.4692 - mean_absolute_error: 0.5923 - mean_absolute_percentage_error: 4315734.5000 - root_mean_squared_error: 0.6844 - val_loss: 0.1393 - val_mean_absolute_error: 0.3402 - val_mean_absolute_percentage_error: 41023272.0000 - val_root_mean_squared_error: 0.3732
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 44s 5s/step - loss: 0.1742 - mean_absolute_error: 0.3572 - mean_absolute_percentage_error: 55173304.0000 - root_mean_squared_error: 0.4171 - val_loss: 0.1280 - val_mean_absolute_error: 0.2622 - val_mean_absolute_percentage_error: 85287856.0000 - val_root_mean_squared_error: 0.3578
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 57s 7s/step - loss: 0.1403 - mean_absolute_error: 0.3244 - mean_absolute_percentage_error: 64999780.0000 - root_mean_squared_error: 0.3746 - val_loss: 0.1019 - val_mean_absolute_error: 0.2766 - val_mean_absolute_percentage_error: 58134472.0000 - val_root_mean_squared_error: 0.3192
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 99s 8s/step - loss: 0.1439 - mean_absolute_error: 0.3483 - mean_absolute_percentage_error: 51809184.0000 - root_mean_squared_error: 0.3794 - val_loss: 0.1139 - val_mean_absolute_error: 0.2509 - val_mean_absolute_percentage_error: 79619696.0000 - val_root_mean_squared_error: 0.3375
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 69s 6s/step - loss: 0.1392 - mean_absolute_error: 0.3143 - mean_absolute_percentage_error: 69143016.0000 - root_mean_squared_error: 0.3730 - val_loss: 0.1022 - val_mean_absolute_error: 0.2493 - val_mean_absolute_percentage_error: 72156560.0000 - val_root_mean_squared_error: 0.3196
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 106s 9s/step - loss: 0.1345 - mean_absolute_error: 0.3303 - mean_absolute_percentage_error: 58644860.0000 - root_mean_squared_error: 0.3667 - val_loss: 0.0991 - val_mean_absolute_error: 0.2510 - val_mean_absolute_percentage_error: 69447672.0000 - val_root_mean_squared_error: 0.3148
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 75s 8s/step - loss: 0.1264 - mean_absolute_error: 0.3099 - mean_absolute_percentage_error: 58334172.0000 - root_mean_squared_error: 0.3555 - val_loss: 0.1123 - val_mean_absolute_error: 0.2512 - val_mean_absolute_percentage_error: 78851512.0000 - val_root_mean_squared_error: 0.3351
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 55s 7s/step - loss: 0.1217 - mean_absolute_error: 0.2943 - mean_absolute_percentage_error: 62596136.0000 - root_mean_squared_error: 0.3488 - val_loss: 0.1027 - val_mean_absolute_error: 0.2520 - val_mean_absolute_percentage_error: 71683800.0000 - val_root_mean_squared_error: 0.3205
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 84s 6s/step - loss: 0.1177 - mean_absolute_error: 0.2919 - mean_absolute_percentage_error: 59606936.0000 - root_mean_squared_error: 0.3431 - val_loss: 0.1103 - val_mean_absolute_error: 0.2576 - val_mean_absolute_percentage_error: 74000760.0000 - val_root_mean_squared_error: 0.3320
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 97s 7s/step - loss: 0.1129 - mean_absolute_error: 0.2727 - mean_absolute_percentage_error: 60531476.0000 - root_mean_squared_error: 0.3360 - val_loss: 0.1051 - val_mean_absolute_error: 0.2629 - val_mean_absolute_percentage_error: 66926800.0000 - val_root_mean_squared_error: 0.3241
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 71s 6s/step - loss: 0.1151 - mean_absolute_error: 0.2826 - mean_absolute_percentage_error: 57179260.0000 - root_mean_squared_error: 0.3393 - val_loss: 0.1008 - val_mean_absolute_error: 0.2719 - val_mean_absolute_percentage_error: 60012764.0000 - val_root_mean_squared_error: 0.3176
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 68s 8s/step - loss: 0.1109 - mean_absolute_error: 0.2743 - mean_absolute_percentage_error: 56072664.0000 - root_mean_squared_error: 0.3330 - val_loss: 0.0998 - val_mean_absolute_error: 0.2748 - val_mean_absolute_percentage_error: 55918304.0000 - val_root_mean_squared_error: 0.3159
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 64s 5s/step - loss: 0.1033 - mean_absolute_error: 0.2637 - mean_absolute_percentage_error: 55800576.0000 - root_mean_squared_error: 0.3214 - val_loss: 0.0935 - val_mean_absolute_error: 0.2662 - val_mean_absolute_percentage_error: 52284284.0000 - val_root_mean_squared_error: 0.3058
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 103s 7s/step - loss: 0.0898 - mean_absolute_error: 0.2416 - mean_absolute_percentage_error: 47921312.0000 - root_mean_squared_error: 0.2996 - val_loss: 0.0723 - val_mean_absolute_error: 0.2273 - val_mean_absolute_percentage_error: 41762556.0000 - val_root_mean_squared_error: 0.2689
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 89s 8s/step - loss: 0.0694 - mean_absolute_error: 0.2087 - mean_absolute_percentage_error: 39998212.0000 - root_mean_squared_error: 0.2634 - val_loss: 0.0595 - val_mean_absolute_error: 0.1990 - val_mean_absolute_percentage_error: 39592076.0000 - val_root_mean_squared_error: 0.2439
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 81s 7s/step - loss: 0.0602 - mean_absolute_error: 0.1939 - mean_absolute_percentage_error: 35424340.0000 - root_mean_squared_error: 0.2453 - val_loss: 0.0606 - val_mean_absolute_error: 0.2017 - val_mean_absolute_percentage_error: 40159832.0000 - val_root_mean_squared_error: 0.2462
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 89s 7s/step - loss: 0.0506 - mean_absolute_error: 0.1756 - mean_absolute_percentage_error: 31519776.0000 - root_mean_squared_error: 0.2249 - val_loss: 0.0544 - val_mean_absolute_error: 0.1829 - val_mean_absolute_percentage_error: 27722758.0000 - val_root_mean_squared_error: 0.2333
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 82s 7s/step - loss: 0.0447 - mean_absolute_error: 0.1586 - mean_absolute_percentage_error: 23908972.0000 - root_mean_squared_error: 0.2113 - val_loss: 0.0512 - val_mean_absolute_error: 0.1759 - val_mean_absolute_percentage_error: 33633956.0000 - val_root_mean_squared_error: 0.2264
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 96s 8s/step - loss: 0.0382 - mean_absolute_error: 0.1466 - mean_absolute_percentage_error: 22814200.0000 - root_mean_squared_error: 0.1954 - val_loss: 0.0414 - val_mean_absolute_error: 0.1537 - val_mean_absolute_percentage_error: 20583478.0000 - val_root_mean_squared_error: 0.2035
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 75s 6s/step - loss: 0.0411 - mean_absolute_error: 0.1507 - mean_absolute_percentage_error: 20099452.0000 - root_mean_squared_error: 0.2028 - val_loss: 0.0501 - val_mean_absolute_error: 0.1705 - val_mean_absolute_percentage_error: 27781844.0000 - val_root_mean_squared_error: 0.2239
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 96s 8s/step - loss: 0.0352 - mean_absolute_error: 0.1384 - mean_absolute_percentage_error: 18091960.0000 - root_mean_squared_error: 0.1876 - val_loss: 0.0507 - val_mean_absolute_error: 0.1734 - val_mean_absolute_percentage_error: 26058550.0000 - val_root_mean_squared_error: 0.2251
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 91s 8s/step - loss: 0.0333 - mean_absolute_error: 0.1374 - mean_absolute_percentage_error: 22364054.0000 - root_mean_squared_error: 0.1825 - val_loss: 0.0472 - val_mean_absolute_error: 0.1615 - val_mean_absolute_percentage_error: 23584344.0000 - val_root_mean_squared_error: 0.2172
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 73s 6s/step - loss: 0.0315 - mean_absolute_error: 0.1285 - mean_absolute_percentage_error: 18245618.0000 - root_mean_squared_error: 0.1775 - val_loss: 0.0464 - val_mean_absolute_error: 0.1618 - val_mean_absolute_percentage_error: 24066260.0000 - val_root_mean_squared_error: 0.2153
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 104s 8s/step - loss: 0.0298 - mean_absolute_error: 0.1269 - mean_absolute_percentage_error: 17689224.0000 - root_mean_squared_error: 0.1727 - val_loss: 0.0429 - val_mean_absolute_error: 0.1580 - val_mean_absolute_percentage_error: 20745238.0000 - val_root_mean_squared_error: 0.2071
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 80s 8s/step - loss: 0.0297 - mean_absolute_error: 0.1255 - mean_absolute_percentage_error: 16371076.0000 - root_mean_squared_error: 0.1723 - val_loss: 0.0447 - val_mean_absolute_error: 0.1574 - val_mean_absolute_percentage_error: 21467502.0000 - val_root_mean_squared_error: 0.2115
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 78s 7s/step - loss: 0.0280 - mean_absolute_error: 0.1211 - mean_absolute_percentage_error: 14435016.0000 - root_mean_squared_error: 0.1674 - val_loss: 0.0413 - val_mean_absolute_error: 0.1550 - val_mean_absolute_percentage_error: 25595618.0000 - val_root_mean_squared_error: 0.2033
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 83s 6s/step - loss: 0.0269 - mean_absolute_error: 0.1215 - mean_absolute_percentage_error: 15975042.0000 - root_mean_squared_error: 0.1639 - val_loss: 0.0415 - val_mean_absolute_error: 0.1507 - val_mean_absolute_percentage_error: 19491394.0000 - val_root_mean_squared_error: 0.2037
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 77s 6s/step - loss: 0.0263 - mean_absolute_error: 0.1177 - mean_absolute_percentage_error: 12867453.0000 - root_mean_squared_error: 0.1622 - val_loss: 0.0404 - val_mean_absolute_error: 0.1485 - val_mean_absolute_percentage_error: 22116416.0000 - val_root_mean_squared_error: 0.2011
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 96s 6s/step - loss: 0.0250 - mean_absolute_error: 0.1152 - mean_absolute_percentage_error: 13699474.0000 - root_mean_squared_error: 0.1581 - val_loss: 0.0395 - val_mean_absolute_error: 0.1476 - val_mean_absolute_percentage_error: 25798106.0000 - val_root_mean_squared_error: 0.1986
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 100s 8s/step - loss: 0.0249 - mean_absolute_error: 0.1179 - mean_absolute_percentage_error: 14718101.0000 - root_mean_squared_error: 0.1577 - val_loss: 0.0428 - val_mean_absolute_error: 0.1524 - val_mean_absolute_percentage_error: 15334782.0000 - val_root_mean_squared_error: 0.2069
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 65s 7s/step - loss: 0.0256 - mean_absolute_error: 0.1166 - mean_absolute_percentage_error: 11950343.0000 - root_mean_squared_error: 0.1601 - val_loss: 0.0395 - val_mean_absolute_error: 0.1454 - val_mean_absolute_percentage_error: 13590420.0000 - val_root_mean_squared_error: 0.1986
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 102s 9s/step - loss: 0.0239 - mean_absolute_error: 0.1131 - mean_absolute_percentage_error: 10254242.0000 - root_mean_squared_error: 0.1547 - val_loss: 0.0405 - val_mean_absolute_error: 0.1487 - val_mean_absolute_percentage_error: 22747922.0000 - val_root_mean_squared_error: 0.2012
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 82s 9s/step - loss: 0.0229 - mean_absolute_error: 0.1101 - mean_absolute_percentage_error: 12313118.0000 - root_mean_squared_error: 0.1513 - val_loss: 0.0398 - val_mean_absolute_error: 0.1458 - val_mean_absolute_percentage_error: 23859674.0000 - val_root_mean_squared_error: 0.1994
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 65s 6s/step - loss: 0.0238 - mean_absolute_error: 0.1128 - mean_absolute_percentage_error: 13822920.0000 - root_mean_squared_error: 0.1543 - val_loss: 0.0394 - val_mean_absolute_error: 0.1456 - val_mean_absolute_percentage_error: 17652606.0000 - val_root_mean_squared_error: 0.1986
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 104s 8s/step - loss: 0.0223 - mean_absolute_error: 0.1081 - mean_absolute_percentage_error: 12076721.0000 - root_mean_squared_error: 0.1493 - val_loss: 0.0394 - val_mean_absolute_error: 0.1457 - val_mean_absolute_percentage_error: 13032317.0000 - val_root_mean_squared_error: 0.1986
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 92s 8s/step - loss: 0.0217 - mean_absolute_error: 0.1058 - mean_absolute_percentage_error: 9727072.0000 - root_mean_squared_error: 0.1471 - val_loss: 0.0388 - val_mean_absolute_error: 0.1427 - val_mean_absolute_percentage_error: 22525938.0000 - val_root_mean_squared_error: 0.1970
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 80s 7s/step - loss: 0.0197 - mean_absolute_error: 0.1040 - mean_absolute_percentage_error: 11483610.0000 - root_mean_squared_error: 0.1404 - val_loss: 0.0400 - val_mean_absolute_error: 0.1462 - val_mean_absolute_percentage_error: 23585756.0000 - val_root_mean_squared_error: 0.2001
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 89s 8s/step - loss: 0.0210 - mean_absolute_error: 0.1077 - mean_absolute_percentage_error: 12605481.0000 - root_mean_squared_error: 0.1449 - val_loss: 0.0403 - val_mean_absolute_error: 0.1484 - val_mean_absolute_percentage_error: 19123510.0000 - val_root_mean_squared_error: 0.2009
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 97s 9s/step - loss: 0.0201 - mean_absolute_error: 0.1048 - mean_absolute_percentage_error: 11861755.0000 - root_mean_squared_error: 0.1416 - val_loss: 0.0404 - val_mean_absolute_error: 0.1477 - val_mean_absolute_percentage_error: 18642508.0000 - val_root_mean_squared_error: 0.2011
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 64s 6s/step - loss: 0.0184 - mean_absolute_error: 0.1001 - mean_absolute_percentage_error: 9370850.0000 - root_mean_squared_error: 0.1356 - val_loss: 0.0406 - val_mean_absolute_error: 0.1471 - val_mean_absolute_percentage_error: 11857758.0000 - val_root_mean_squared_error: 0.2015
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 106s 9s/step - loss: 0.0206 - mean_absolute_error: 0.1041 - mean_absolute_percentage_error: 9824413.0000 - root_mean_squared_error: 0.1436 - val_loss: 0.0363 - val_mean_absolute_error: 0.1389 - val_mean_absolute_percentage_error: 14558617.0000 - val_root_mean_squared_error: 0.1905
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 83s 8s/step - loss: 0.0191 - mean_absolute_error: 0.1017 - mean_absolute_percentage_error: 9409699.0000 - root_mean_squared_error: 0.1381 - val_loss: 0.0398 - val_mean_absolute_error: 0.1459 - val_mean_absolute_percentage_error: 20880414.0000 - val_root_mean_squared_error: 0.1995
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 70s 8s/step - loss: 0.0185 - mean_absolute_error: 0.1007 - mean_absolute_percentage_error: 10515901.0000 - root_mean_squared_error: 0.1360 - val_loss: 0.0408 - val_mean_absolute_error: 0.1480 - val_mean_absolute_percentage_error: 22568398.0000 - val_root_mean_squared_error: 0.2021
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 62s 7s/step - loss: 0.0182 - mean_absolute_error: 0.0996 - mean_absolute_percentage_error: 10290658.0000 - root_mean_squared_error: 0.1349 - val_loss: 0.0400 - val_mean_absolute_error: 0.1463 - val_mean_absolute_percentage_error: 17378240.0000 - val_root_mean_squared_error: 0.1999
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 70s 8s/step - loss: 0.0163 - mean_absolute_error: 0.0950 - mean_absolute_percentage_error: 8538113.0000 - root_mean_squared_error: 0.1278 - val_loss: 0.0411 - val_mean_absolute_error: 0.1476 - val_mean_absolute_percentage_error: 22419312.0000 - val_root_mean_squared_error: 0.2028
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 82s 10s/step - loss: 0.0152 - mean_absolute_error: 0.0919 - mean_absolute_percentage_error: 8384205.0000 - root_mean_squared_error: 0.1234 - val_loss: 0.0373 - val_mean_absolute_error: 0.1408 - val_mean_absolute_percentage_error: 19310464.0000 - val_root_mean_squared_error: 0.1931
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 65s 7s/step - loss: 0.0158 - mean_absolute_error: 0.0945 - mean_absolute_percentage_error: 8817396.0000 - root_mean_squared_error: 0.1257 - val_loss: 0.0426 - val_mean_absolute_error: 0.1518 - val_mean_absolute_percentage_error: 21677324.0000 - val_root_mean_squared_error: 0.2065
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 92s 8s/step - loss: 0.0160 - mean_absolute_error: 0.0938 - mean_absolute_percentage_error: 8057527.0000 - root_mean_squared_error: 0.1264 - val_loss: 0.0403 - val_mean_absolute_error: 0.1460 - val_mean_absolute_percentage_error: 14843510.0000 - val_root_mean_squared_error: 0.2008
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 86s 8s/step - loss: 0.0161 - mean_absolute_error: 0.0930 - mean_absolute_percentage_error: 7154581.5000 - root_mean_squared_error: 0.1270 - val_loss: 0.0407 - val_mean_absolute_error: 0.1462 - val_mean_absolute_percentage_error: 22118364.0000 - val_root_mean_squared_error: 0.2017
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 68s 5s/step - loss: 0.0147 - mean_absolute_error: 0.0910 - mean_absolute_percentage_error: 7749795.0000 - root_mean_squared_error: 0.1211 - val_loss: 0.0397 - val_mean_absolute_error: 0.1452 - val_mean_absolute_percentage_error: 21370766.0000 - val_root_mean_squared_error: 0.1991

In [54]:
CTNET_predictions = CTNET.predict(X_test_windowed)
CTNET_predictions

30/30 ━━━━━━━━━━━━━━━━━━━━ 38s 556ms/step

array([[ 0.9231799 ],
       [ 0.93275493],
       [ 0.9066461 ],
       [ 0.9251513 ],
       [ 0.90455097],
       [ 0.9325918 ],
       [ 0.7116323 ],
       [ 0.4825462 ],
       [ 0.06643067],
       [ 0.00985141],
       [ 0.78841317],
       [ 0.80829096],
       [ 0.8828202 ],
       [ 0.9338947 ],
       [ 0.9249007 ],
       [ 0.896619  ],
       [ 0.9282765 ],
       [ 0.915404  ],
       [ 0.92563146],
       [ 0.7448062 ],
       [ 0.42824343],
       [ 0.0573285 ],
       [ 0.01263061],
       [ 0.7984353 ],
       [ 0.97259206],
       [ 0.94351447],
       [ 0.93121165],
       [ 0.9197299 ],
       [ 0.9079058 ],
       [ 0.9026924 ],
       [ 0.8444239 ],
       [ 0.6743317 ],
       [ 0.29396802],
       [ 0.03359183],
       [ 0.11938273],
       [ 0.82338786],
       [ 0.8983918 ],
       [ 0.9402831 ],
       [ 0.9267015 ],
       [ 0.8943697 ],
       [ 0.93465585],
       [ 0.92359567],
       [ 0.86624485],
       [ 0.5976077 ],
       [ 0.19347075],
       [ 0.06049917],
       [-0.01058332],
       [ 0.8618878 ],
       [ 0.93961173],
       [ 0.9570889 ],
       [ 0.94814813],
       [ 0.9096417 ],
       [ 0.9216434 ],
       [ 0.9257573 ],
       [ 0.8829519 ],
       [ 0.7950492 ],
       [ 0.60479426],
       [ 0.5431279 ],
       [ 0.7236827 ],
       [ 0.9491051 ],
       [ 0.8733943 ],
       [ 0.9023806 ],
       [ 0.92567587],
       [ 0.9202437 ],
       [ 0.9368609 ],
       [ 0.92954546],
       [ 0.89023733],
       [ 0.8162574 ],
       [ 0.4931587 ],
       [ 0.10620013],
       [ 0.02854183],
       [ 1.0427674 ],
       [ 0.94119936],
       [ 0.94441277],
       [ 0.9521293 ],
       [ 0.9284408 ],
       [ 0.9337351 ],
       [ 0.9084975 ],
       [ 0.81200147],
       [ 0.5986513 ],
       [ 0.07349734],
       [ 0.24150959],
       [ 0.90549666],
       [ 0.94499516],
       [ 0.88963884],
       [ 0.89581496],
       [ 0.9078296 ],
       [ 0.92195976],
       [ 0.9202748 ],
       [ 0.87630045],
       [ 0.7924355 ],
       [ 0.32449633],
       [ 0.05224012],
       [ 0.0247476 ],
       [ 0.93213063],
       [ 0.9211051 ],
       [ 0.91014844],
       [ 0.905165  ],
       [ 0.9175145 ],
       [ 0.9312956 ],
       [ 0.9216837 ],
       [ 0.8954285 ],
       [ 0.7264149 ],
       [ 0.3815205 ],
       [ 0.05117526],
       [ 0.05836863],
       [ 1.0406401 ],
       [ 0.85608643],
       [ 0.87528414],
       [ 0.9022572 ],
       [ 0.8876524 ],
       [ 0.9349469 ],
       [ 0.9262759 ],
       [ 0.90003854],
       [ 0.7933073 ],
       [ 0.38446188],
       [ 0.07878297],
       [ 0.23807618],
       [ 1.0488997 ],
       [ 0.9249471 ],
       [ 0.9187667 ],
       [ 0.9275722 ],
       [ 0.91739875],
       [ 0.93664294],
       [ 0.9028128 ],
       [ 0.68939036],
       [ 0.32594213],
       [ 0.05460011],
       [ 0.09847351],
       [ 0.9130845 ],
       [ 0.9449072 ],
       [ 0.8912312 ],
       [ 0.9005235 ],
       [ 0.908261  ],
       [ 0.9213508 ],
       [ 0.9187054 ],
       [ 0.8745441 ],
       [ 0.7808837 ],
       [ 0.48195338],
       [ 0.04903442],
       [ 0.01394777],
       [ 0.94527227],
       [ 0.9224683 ],
       [ 0.9102711 ],
       [ 0.904363  ],
       [ 0.9181101 ],
       [ 0.9328932 ],
       [ 0.9247013 ],
       [ 0.8979858 ],
       [ 0.78054166],
       [ 0.47834817],
       [ 0.04871371],
       [-0.01191106],
       [ 0.8968091 ],
       [ 0.8688083 ],
       [ 0.88852364],
       [ 0.90737057],
       [ 0.89153004],
       [ 0.93856555],
       [ 0.9299706 ],
       [ 0.90803367],
       [ 0.82319623],
       [ 0.43915418],
       [ 0.06973793],
       [ 0.00801337],
       [ 0.89743966],
       [ 0.9128699 ],
       [ 0.9289039 ],
       [ 0.9469245 ],
       [ 0.9279139 ],
       [ 0.94192135],
       [ 0.9184434 ],
       [ 0.8396633 ],
       [ 0.6856996 ],
       [ 0.40932816],
       [ 0.07626971],
       [ 0.9298763 ],
       [ 0.98744327],
       [ 0.9075671 ],
       [ 0.9047982 ],
       [ 0.9138104 ],
       [ 0.8899796 ],
       [ 0.78125626],
       [ 0.7695422 ],
       [ 0.7219353 ],
       [ 0.7168248 ],
       [ 0.8919746 ],
       [ 0.89379984],
       [ 0.86039406],
       [ 0.85574895],
       [ 0.83999723],
       [ 0.84155524],
       [ 0.87411064],
       [ 0.8130813 ],
       [ 0.8762924 ],
       [ 0.9562578 ],
       [ 0.9296338 ],
       [ 0.90055645],
       [ 0.891983  ],
       [ 0.84498996],
       [ 0.79884815],
       [ 0.68030304],
       [ 0.39150074],
       [ 0.8429552 ],
       [ 1.0125774 ],
       [ 0.967596  ],
       [ 0.9136296 ],
       [ 0.89995694],
       [ 0.8947093 ],
       [ 0.8423055 ],
       [ 0.6985444 ],
       [ 0.5670545 ],
       [ 0.7648093 ],
       [ 0.86279136],
       [ 0.8362719 ],
       [ 0.83405626],
       [ 0.82798034],
       [ 0.8253296 ],
       [ 0.7536939 ],
       [ 0.581368  ],
       [ 0.79952985],
       [ 0.8259432 ],
       [ 0.80973476],
       [ 0.75710505],
       [ 0.7281806 ],
       [ 0.6810215 ],
       [ 0.6838314 ],
       [ 0.73067266],
       [ 0.7892815 ],
       [ 0.80441236],
       [ 0.78192633],
       [ 0.7734221 ],
       [ 0.77050185],
       [ 0.7651429 ],
       [ 0.7712853 ],
       [ 0.8014618 ],
       [ 0.7888351 ],
       [ 0.76705307],
       [ 0.72215897],
       [ 0.77116144],
       [ 0.7870238 ],
       [ 0.78337634],
       [ 0.7727414 ],
       [ 0.8048243 ],
       [ 0.8210187 ],
       [ 0.76390713],
       [ 0.72389936],
       [ 0.89137477],
       [ 0.85862106],
       [ 0.8075977 ],
       [ 0.7649177 ],
       [ 0.7451084 ],
       [ 0.713088  ],
       [ 0.5826519 ],
       [ 0.7656267 ],
       [ 0.8508047 ],
       [ 0.8836365 ],
       [ 0.8497883 ],
       [ 0.80538267],
       [ 0.80187196],
       [ 0.74858135],
       [ 0.6190914 ],
       [ 0.53852797],
       [ 0.10392286],
       [ 0.84930056],
       [ 0.9142074 ],
       [ 0.80228096],
       [ 0.7053248 ],
       [ 0.4992211 ],
       [ 0.314283  ],
       [ 0.13913663],
       [ 0.04216911],
       [ 0.21695906],
       [ 0.4210462 ],
       [ 0.8278455 ],
       [ 0.9416112 ],
       [ 0.89524007],
       [ 0.89314765],
       [ 0.9094947 ],
       [ 0.90907085],
       [ 0.79580516],
       [ 0.33355555],
       [ 0.10145165],
       [-0.00167943],
       [ 0.75923544],
       [ 0.8938788 ],
       [ 0.8654637 ],
       [ 0.8399469 ],
       [ 0.8984071 ],
       [ 0.8979024 ],
       [ 0.7936891 ],
       [ 0.6405465 ],
       [ 0.55459744],
       [ 0.36799204],
       [ 0.8281673 ],
       [ 0.8582489 ],
       [ 0.8783121 ],
       [ 0.9074423 ],
       [ 0.8603084 ],
       [ 0.8641707 ],
       [ 0.8305965 ],
       [ 0.68198425],
       [ 0.33189255],
       [ 0.44043532],
       [ 0.95264626],
       [ 0.9036808 ],
       [ 0.8879568 ],
       [ 0.8899062 ],
       [ 0.8499782 ],
       [ 0.77332777],
       [ 0.67296386],
       [ 0.79082817],
       [ 0.9679655 ],
       [ 0.9058616 ],
       [ 0.78710437],
       [ 0.6697152 ],
       [ 0.43376237],
       [ 0.1497233 ],
       [ 0.17288426],
       [-0.03837398],
       [ 0.6774927 ],
       [ 0.8450864 ],
       [ 0.0573456 ],
       [ 0.10263527],
       [ 0.17454442],
       [ 0.6171996 ],
       [ 0.72799844],
       [ 0.05600238],
       [ 0.61194676],
       [ 0.6720778 ],
       [ 0.8019938 ],
       [ 0.88127285],
       [ 0.89544445],
       [ 0.90694255],
       [ 0.92451024],
       [ 0.46567523],
       [ 0.25335056],
       [ 0.24774393],
       [ 0.64762706],
       [ 0.65045196],
       [ 0.8425682 ],
       [ 0.7846394 ],
       [ 0.74249154],
       [ 0.7995519 ],
       [ 0.46841925],
       [ 0.1905962 ],
       [ 0.3742872 ],
       [ 0.74627674],
       [ 0.1633518 ],
       [ 0.4472062 ],
       [ 0.44106707],
       [ 0.34129086],
       [ 0.64602816],
       [ 0.54691094],
       [ 0.41195035],
       [ 0.57188034],
       [ 0.60406363],
       [ 0.4562477 ],
       [ 0.46130943],
       [ 0.4221448 ],
       [ 0.6941343 ],
       [ 0.6787986 ],
       [ 0.5210922 ],
       [ 0.47680172],
       [ 0.59872377],
       [ 0.66993326],
       [ 0.77869266],
       [ 0.822147  ],
       [ 0.8169797 ],
       [ 0.85436845],
       [ 0.92088825],
       [ 0.84087867],
       [ 0.79047155],
       [ 0.51596195],
       [ 0.74955815],
       [ 0.75221723],
       [ 0.797113  ],
       [ 0.78308433],
       [ 0.69965243],
       [ 0.771079  ],
       [ 0.80096203],
       [ 0.7678456 ],
       [ 0.70164305],
       [ 0.7946512 ],
       [ 0.8308777 ],
       [ 0.7235422 ],
       [ 0.7974531 ],
       [ 0.83263505],
       [ 0.80627984],
       [ 0.7255674 ],
       [ 0.6462381 ],
       [ 0.7785844 ],
       [ 0.83082086],
       [ 0.80779344],
       [ 0.78652406],
       [ 0.7549891 ],
       [ 0.68779457],
       [ 0.6546281 ],
       [ 0.6914008 ],
       [ 0.23025182],
       [ 0.51662576],
       [ 0.7095831 ],
       [ 0.29603806],
       [ 0.1527259 ],
       [ 0.5554559 ],
       [ 0.8174802 ],
       [ 0.8085579 ],
       [ 0.90314364],
       [ 0.8640503 ],
       [ 0.7737946 ],
       [ 0.77262443],
       [ 0.74631894],
       [ 0.7820198 ],
       [ 0.7876374 ],
       [ 0.7824003 ],
       [ 0.78211683],
       [ 0.80210084],
       [ 0.76398873],
       [ 0.7722843 ],
       [ 0.7929293 ],
       [ 0.7585568 ],
       [ 0.6900321 ],
       [ 0.7111283 ],
       [ 0.74595946],
       [ 0.7724785 ],
       [ 0.76643056],
       [ 0.7202856 ],
       [ 0.5846725 ],
       [ 0.56352   ],
       [ 0.71483487],
       [ 0.83882636],
       [ 0.83213073],
       [ 0.83609825],
       [ 0.804949  ],
       [ 0.81543255],
       [ 0.7727604 ],
       [ 0.66420144],
       [ 0.6726088 ],
       [ 0.7622568 ],
       [ 0.78869784],
       [ 0.7918153 ],
       [ 0.80359405],
       [ 0.7339865 ],
       [ 0.6543668 ],
       [ 0.55492395],
       [ 0.74667686],
       [ 0.8186528 ],
       [ 0.8433067 ],
       [ 0.8217394 ],
       [ 0.7895067 ],
       [ 0.76555043],
       [ 0.70041263],
       [ 0.64401644],
       [ 0.49353814],
       [ 0.6815654 ],
       [ 0.8647394 ],
       [ 0.852398  ],
       [ 0.844301  ],
       [ 0.79522455],
       [ 0.7892309 ],
       [ 0.7562626 ],
       [ 0.623383  ],
       [ 0.26451644],
       [ 0.7510393 ],
       [ 0.9963419 ],
       [ 0.9284517 ],
       [ 0.88289964],
       [ 0.8551282 ],
       [ 0.87574065],
       [ 0.86538655],
       [ 0.5454137 ],
       [ 0.21075457],
       [ 0.06177866],
       [ 0.83850354],
       [ 0.90444773],
       [ 0.88750774],
       [ 0.8527717 ],
       [ 0.9095624 ],
       [ 0.90214807],
       [ 0.8594316 ],
       [ 0.7386294 ],
       [ 0.43120173],
       [ 0.13210103],
       [ 0.844575  ],
       [ 0.9159066 ],
       [ 0.90419775],
       [ 0.90873045],
       [ 0.90892965],
       [ 0.8800715 ],
       [ 0.86259747],
       [ 0.7048927 ],
       [ 0.38633686],
       [ 0.3104056 ],
       [ 0.87881726],
       [ 0.8276662 ],
       [ 0.8876752 ],
       [ 0.8918643 ],
       [ 0.875287  ],
       [ 0.83493406],
       [ 0.66937464],
       [ 0.23223469],
       [ 0.03095346],
       [ 0.8269231 ],
       [ 0.89182454],
       [ 0.8492287 ],
       [ 0.92146736],
       [ 0.939769  ],
       [ 0.8947316 ],
       [ 0.8687793 ],
       [ 0.77943456],
       [ 0.6138622 ],
       [ 0.408898  ],
       [ 0.02845897],
       [ 0.5489982 ],
       [ 0.935754  ],
       [ 0.946725  ],
       [ 0.93931025],
       [ 0.8642908 ],
       [ 0.8924747 ],
       [ 0.87249887],
       [ 0.8581983 ],
       [ 0.74883884],
       [ 0.51446414],
       [ 0.09144022],
       [ 0.842632  ],
       [ 0.97321045],
       [ 0.90559936],
       [ 0.9090069 ],
       [ 0.90112853],
       [ 0.8423975 ],
       [ 0.8043332 ],
       [ 0.6285098 ],
       [ 0.5292272 ],
       [ 0.9231632 ],
       [ 0.9295531 ],
       [ 0.9569416 ],
       [ 0.92096025],
       [ 0.92404985],
       [ 0.8221214 ],
       [ 0.80634433],
       [ 0.64496356],
       [ 0.25323504],
       [ 0.780533  ],
       [ 1.0134226 ],
       [ 0.9391547 ],
       [ 0.9235327 ],
       [ 0.90948254],
       [ 0.88187295],
       [ 0.7921832 ],
       [ 0.53683853],
       [ 0.13569677],
       [ 0.9011625 ],
       [ 1.0699794 ],
       [ 0.9216211 ],
       [ 0.9109375 ],
       [ 0.915085  ],
       [ 0.9121702 ],
       [ 0.8938984 ],
       [ 0.7758704 ],
       [ 0.68297815],
       [ 0.8476875 ],
       [ 0.8829213 ],
       [ 0.7276712 ],
       [ 0.71953577],
       [ 0.6333203 ],
       [ 0.7971018 ],
       [ 0.839765  ],
       [ 0.8934993 ],
       [ 0.9270908 ],
       [ 0.90223163],
       [ 0.8929367 ],
       [ 0.87779695],
       [ 0.83213514],
       [ 0.74641156],
       [ 0.6248577 ],
       [ 0.76742184],
       [ 0.7602878 ],
       [ 0.858423  ],
       [ 0.88307613],
       [ 0.8270358 ],
       [ 0.6997497 ],
       [ 0.6422097 ],
       [ 0.5256921 ],
       [ 0.7994266 ],
       [ 0.9272806 ],
       [ 0.8964695 ],
       [ 0.8379229 ],
       [ 0.8892315 ],
       [ 0.81631684],
       [ 0.6592853 ],
       [ 0.55774933],
       [ 0.8541136 ],
       [ 0.9511849 ],
       [ 0.88792914],
       [ 0.82049954],
       [ 0.7231156 ],
       [ 0.5464156 ],
       [ 0.7703596 ],
       [ 0.8148424 ],
       [ 0.84423155],
       [ 0.8294452 ],
       [ 0.84181374],
       [ 0.8399895 ],
       [ 0.58733803],
       [ 0.26900715],
       [ 0.7672963 ],
       [ 0.86411643],
       [ 0.8288415 ],
       [ 0.8222321 ],
       [ 0.8001361 ],
       [ 0.4569806 ],
       [ 0.06856108],
       [ 0.07806625],
       [ 0.41072077],
       [ 0.7613439 ],
       [ 0.7328165 ],
       [ 0.70937675],
       [ 0.6330305 ],
       [ 0.37431595],
       [ 0.21966568],
       [ 0.02692662],
       [ 0.2893361 ],
       [ 0.75935036],
       [ 0.6755546 ],
       [ 0.7219634 ],
       [ 0.7773867 ],
       [ 0.8075025 ],
       [ 0.81145114],
       [ 0.62247396],
       [ 0.5329004 ],
       [ 0.490485  ],
       [ 0.75711685],
       [ 0.8041702 ],
       [ 0.7881474 ],
       [ 0.80520755],
       [ 0.73581415],
       [ 0.5562883 ],
       [ 0.12272555],
       [ 0.78482896],
       [ 1.0420256 ],
       [ 0.9541984 ],
       [ 0.85363466],
       [ 0.86975783],
       [ 0.9355626 ],
       [ 0.8965431 ],
       [ 0.653207  ],
       [ 0.3284424 ],
       [ 0.8327694 ],
       [ 0.810145  ],
       [ 0.84910005],
       [ 0.83905846],
       [ 0.8190825 ],
       [ 0.82262456],
       [ 0.7741984 ],
       [ 0.6604747 ],
       [ 0.4330966 ],
       [ 0.8765667 ],
       [ 1.0009689 ],
       [ 0.88235945],
       [ 0.8998831 ],
       [ 0.89244646],
       [ 0.91997224],
       [ 0.93523675],
       [ 0.6556735 ],
       [ 0.17935848],
       [ 0.47362542],
       [ 0.78959197],
       [ 0.9045612 ],
       [ 0.87828964],
       [ 0.8399564 ],
       [ 0.8835452 ],
       [ 0.8815406 ],
       [ 0.8793331 ],
       [ 0.7652592 ],
       [ 0.47932357],
       [ 0.81708884],
       [ 0.9004169 ],
       [ 0.8875449 ],
       [ 0.900326  ],
       [ 0.9103647 ],
       [ 0.8696915 ],
       [ 0.8486606 ],
       [ 0.68428063],
       [ 0.3484981 ],
       [ 0.7247887 ],
       [ 0.94752795],
       [ 0.8326207 ],
       [ 0.8150241 ],
       [ 0.86435276],
       [ 0.89485234],
       [ 0.8929877 ],
       [ 0.7103452 ],
       [ 0.26029423],
       [ 0.7883497 ],
       [ 0.99022454],
       [ 0.89672446],
       [ 0.88170135],
       [ 0.86126494],
       [ 0.9028865 ],
       [ 0.89388424],
       [ 0.6559864 ],
       [ 0.32341087],
       [ 0.89028215],
       [ 0.9591456 ],
       [ 0.8463665 ],
       [ 0.86957574],
       [ 0.8455549 ],
       [ 0.8988491 ],
       [ 0.7647863 ],
       [ 0.38945782],
       [ 0.29768378],
       [ 0.87447345],
       [ 0.9429562 ],
       [ 0.8657504 ],
       [ 0.81921905],
       [ 0.8536096 ],
       [ 0.7805477 ],
       [ 0.60053927],
       [ 0.34992456],
       [ 0.16004883],
       [ 0.11882254],
       [ 0.25348732],
       [ 0.12888435],
       [ 0.05950737],
       [ 0.19336522],
       [ 0.46521962],
       [ 0.73473567],
       [ 0.6889146 ],
       [ 0.10909416],
       [ 0.08699639],
       [ 0.05038384],
       [-0.03289127],
       [ 0.0428611 ],
       [ 0.13826966],
       [ 0.3602746 ],
       [ 0.48745897],
       [ 0.0641131 ],
       [ 0.04747287],
       [ 0.02560823],
       [ 0.029783  ],
       [ 0.06243096],
       [ 0.36555064],
       [ 0.08658889],
       [ 0.64597803],
       [ 0.12912582],
       [ 0.25575194],
       [ 0.3246276 ],
       [ 0.7556465 ],
       [ 0.5016283 ],
       [ 0.377363  ],
       [ 0.36205575],
       [ 0.34209114],
       [ 0.45156068],
       [ 0.20657608],
       [ 0.42404765],
       [ 0.291736  ],
       [ 0.34452718],
       [ 0.40982246],
       [ 0.50394374],
       [ 0.53882754],
       [ 0.3705791 ],
       [ 0.48294458],
       [ 0.43871763],
       [ 0.5316948 ],
       [ 0.7145424 ],
       [ 0.6487052 ],
       [ 0.60428375],
       [ 0.6454263 ],
       [ 0.689177  ],
       [ 0.72920424],
       [ 0.5780104 ],
       [ 0.6396101 ],
       [ 0.5632117 ],
       [ 0.5305096 ],
       [ 0.48144662],
       [ 0.47840717],
       [ 0.7268133 ],
       [ 0.8049113 ],
       [ 0.81903666],
       [ 0.8475334 ],
       [ 0.8482476 ],
       [ 0.89147663],
       [ 0.827377  ],
       [ 0.70143384],
       [ 0.45546877],
       [ 0.6981103 ],
       [ 0.83022606],
       [ 0.84298104],
       [ 0.80277777],
       [ 0.7864118 ],
       [ 0.77412564],
       [ 0.7342314 ],
       [ 0.51305854],
       [ 0.7834715 ],
       [ 0.86708254],
       [ 0.9217351 ],
       [ 0.86410207],
       [ 0.91843694],
       [ 0.9128075 ],
       [ 0.8875415 ],
       [ 0.7637901 ],
       [ 0.71731275],
       [ 0.8018747 ],
       [ 0.7603262 ],
       [ 0.71218103],
       [ 0.7375186 ],
       [ 0.66768557],
       [ 0.71854997],
       [ 0.74734277],
       [ 0.78869075],
       [ 0.8479765 ],
       [ 0.86665195],
       [ 0.8405344 ],
       [ 0.7422487 ],
       [ 0.779489  ],
       [ 0.855227  ],
       [ 0.8385336 ],
       [ 0.8545453 ],
       [ 0.79379356],
       [ 0.75456625],
       [ 0.69325316],
       [ 0.726282  ],
       [ 0.703092  ],
       [ 0.68081397],
       [ 0.67600983],
       [ 0.68703705],
       [ 0.69553596],
       [ 0.6771261 ],
       [ 0.676106  ],
       [ 0.67548376],
       [ 0.6445468 ],
       [ 0.64477736],
       [ 0.66325456],
       [ 0.6708144 ],
       [ 0.6636076 ],
       [ 0.6287313 ],
       [ 0.6020836 ],
       [ 0.6050152 ],
       [ 0.62383384],
       [ 0.650584  ],
       [ 0.6519958 ],
       [ 0.64789504],
       [ 0.63113904],
       [ 0.6080646 ],
       [ 0.58692133],
       [ 0.6184489 ],
       [ 0.6573894 ],
       [ 0.6566928 ],
       [ 0.6447975 ],
       [ 0.63244873],
       [ 0.5968146 ],
       [ 0.5730259 ],
       [ 0.6436145 ],
       [ 0.6736844 ],
       [ 0.7150009 ],
       [ 0.73088664],
       [ 0.7009409 ],
       [ 0.6646352 ],
       [ 0.5538861 ],
       [ 0.5030383 ],
       [ 0.7719391 ],
       [ 0.77522796],
       [ 0.7866417 ],
       [ 0.793934  ],
       [ 0.78891784],
       [ 0.75690395],
       [ 0.6946189 ],
       [ 0.568487  ],
       [ 0.3415854 ],
       [ 0.7488907 ],
       [ 0.6886509 ],
       [ 0.6827546 ],
       [ 0.7577401 ],
       [ 0.7867998 ],
       [ 0.7061849 ],
       [ 0.4896313 ],
       [ 0.42766026],
       [ 0.79227865],
       [ 0.8320864 ],
       [ 0.8386789 ],
       [ 0.83128613],
       [ 0.81010294],
       [ 0.76784694],
       [ 0.61262685],
       [ 0.13220695],
       [ 0.68973845],
       [ 1.0033458 ],
       [ 0.94021434],
       [ 0.8583494 ],
       [ 0.80136603],
       [ 0.76290315],
       [ 0.69235706],
       [ 0.66647655],
       [ 0.7919871 ],
       [ 0.921481  ],
       [ 0.83083826],
       [ 0.8638728 ],
       [ 0.7597996 ],
       [ 0.6925551 ],
       [ 0.4320643 ],
       [ 0.60829324],
       [ 0.8890333 ],
       [ 0.88597316],
       [ 0.7931032 ],
       [ 0.79048365],
       [ 0.5127642 ],
       [ 0.64168084],
       [ 0.79353124],
       [ 0.80638963],

In [55]:
CTNET_predictions = y_scaler.inverse_transform(CTNET_predictions.reshape(-1, 1))
CTNET_predictions = np.clip(CTNET_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [56]:
resultados = pd.DataFrame(CTNET_predictions, index = y_test_windowed.index, columns=["CTNET"])

In [57]:
predicciones["CTNET"] = resultados["CTNET"]
predicciones

       Generación      LightGBM Random Forest         CTNET
15328     27864.0  27737.854623    27676.1575           NaN
15329     24624.0  27486.133289      27436.08           NaN
15330     23657.0  24127.781396  24350.938017           NaN
15331     20683.0  20469.172397  20043.384431           NaN
15332     10703.0  10001.014624      10626.32           NaN
...           ...           ...           ...           ...
18281     25386.0  27249.220044  26034.882309  23223.203125
18282     22872.0  22924.525455  23229.408141  22499.527344
18283     15825.0  14677.255501  15735.242934  15411.343750
18284      1450.0   2147.631109   2056.066838   2882.268066
18285         0.0     17.321742           0.0  16132.508789

[995 rows x 4 columns]

## Forecasting

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import Huber
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
Forecast_model = Sequential()
Forecast_model.add(InputLayer((X_train_windowed.shape[1], X_train_windowed.shape[2])))

#CNN
Forecast_model.add(Conv1D(filters=64, kernel_size=2, padding='same', activation='relu'))
Forecast_model.add(BatchNormalization())  # 🔹 Nueva Normalización aquí
Forecast_model.add(MaxPooling1D(pool_size=2))

#model_Soleado.add(Flatten())
#BiLSTM
Forecast_model.add(Bidirectional(LSTM(128, return_sequences=True)))
Forecast_model.add(Bidirectional(LSTM(64, return_sequences=True)))
Forecast_model.add(Dropout(0.2))  # 🔹 Mayor regularización en BiLSTM
Forecast_model.add(Bidirectional(LSTM(32, return_sequences=False)))

#Normalización y Dropout
Forecast_model.add(BatchNormalization())
Forecast_model.add(Dropout(0.3))

# Capas Densas
Forecast_model.add(Dense(16, activation='relu'))
Forecast_model.add(Dense(1, 'relu'))

Forecast_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 48, 64)         │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 256)        │       197,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 24, 128)        │       164,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        41,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405,601 (1.55 MB)

 Trainable params: 405,345 (1.55 MB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
cp = ModelCheckpoint('Forcasting_model.keras', save_best_only=True)
Forecast_model.compile(optimizer=Adam(learning_rate=0.0001), loss=Huber(delta=1000), metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [61]:
history = Forecast_model.fit(X_train_windowed, y_train_windowed, validation_data=(X_val_windowed, y_val_windowed), epochs=100, batch_size=8, callbacks=[cp, early_stop])

Epoch 1/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 673s 548ms/step - loss: 0.1583 - mae: 0.4603 - val_loss: 0.0535 - val_mae: 0.2761
Epoch 2/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 275s 468ms/step - loss: 0.1040 - mae: 0.3641 - val_loss: 0.0379 - val_mae: 0.1964
Epoch 3/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 268s 460ms/step - loss: 0.0789 - mae: 0.3144 - val_loss: 0.0165 - val_mae: 0.1326
Epoch 4/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 271s 463ms/step - loss: 0.0722 - mae: 0.2945 - val_loss: 0.0192 - val_mae: 0.1354
Epoch 5/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 313s 434ms/step - loss: 0.0594 - mae: 0.2643 - val_loss: 0.0142 - val_mae: 0.1203
Epoch 6/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 245s 391ms/step - loss: 0.0560 - mae: 0.2564 - val_loss: 0.0143 - val_mae: 0.1130
Epoch 7/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 291s 434ms/step - loss: 0.0489 - mae: 0.2378 - val_loss: 0.0172 - val_mae: 0.1178
Epoch 8/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 264s 423ms/step - loss: 0.0458 - mae: 0.2271 - val_loss: 0.0129 - val_mae: 0.1122
Epoch 9/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 277s 441ms/step - loss: 0.0422 - mae: 0.2159 - val_loss: 0.0122 - val_mae: 0.1050
Epoch 10/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 223s 378ms/step - loss: 0.0411 - mae: 0.2116 - val_loss: 0.0127 - val_mae: 0.1031
Epoch 11/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 244s 415ms/step - loss: 0.0418 - mae: 0.2092 - val_loss: 0.0126 - val_mae: 0.1028
Epoch 12/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 274s 426ms/step - loss: 0.0331 - mae: 0.1885 - val_loss: 0.0128 - val_mae: 0.1046
Epoch 13/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 209s 326ms/step - loss: 0.0338 - mae: 0.1889 - val_loss: 0.0113 - val_mae: 0.1011
Epoch 14/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 216s 366ms/step - loss: 0.0301 - mae: 0.1784 - val_loss: 0.0124 - val_mae: 0.1084
Epoch 15/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 280s 391ms/step - loss: 0.0311 - mae: 0.1804 - val_loss: 0.0104 - val_mae: 0.1024
Epoch 16/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 263s 384ms/step - loss: 0.0252 - mae: 0.1631 - val_loss: 0.0116 - val_mae: 0.1049
Epoch 17/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 272s 397ms/step - loss: 0.0251 - mae: 0.1612 - val_loss: 0.0184 - val_mae: 0.1154
Epoch 18/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 219s 378ms/step - loss: 0.0238 - mae: 0.1572 - val_loss: 0.0099 - val_mae: 0.0960
Epoch 19/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 256s 359ms/step - loss: 0.0225 - mae: 0.1513 - val_loss: 0.0139 - val_mae: 0.1128
Epoch 20/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 196s 335ms/step - loss: 0.0228 - mae: 0.1511 - val_loss: 0.0129 - val_mae: 0.1053
Epoch 21/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 206s 332ms/step - loss: 0.0207 - mae: 0.1453 - val_loss: 0.0093 - val_mae: 0.0903
Epoch 22/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 218s 373ms/step - loss: 0.0188 - mae: 0.1385 - val_loss: 0.0111 - val_mae: 0.0999
Epoch 23/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 230s 308ms/step - loss: 0.0191 - mae: 0.1390 - val_loss: 0.0113 - val_mae: 0.0976
Epoch 24/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 153s 259ms/step - loss: 0.0182 - mae: 0.1345 - val_loss: 0.0093 - val_mae: 0.0847
Epoch 25/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 226s 293ms/step - loss: 0.0167 - mae: 0.1306 - val_loss: 0.0086 - val_mae: 0.0860
Epoch 26/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 184s 261ms/step - loss: 0.0161 - mae: 0.1267 - val_loss: 0.0077 - val_mae: 0.0826
Epoch 27/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 195s 245ms/step - loss: 0.0158 - mae: 0.1255 - val_loss: 0.0117 - val_mae: 0.0947
Epoch 28/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 155s 263ms/step - loss: 0.0152 - mae: 0.1235 - val_loss: 0.0202 - val_mae: 0.1255
Epoch 29/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 215s 277ms/step - loss: 0.0154 - mae: 0.1220 - val_loss: 0.0085 - val_mae: 0.0821
Epoch 30/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 205s 276ms/step - loss: 0.0142 - mae: 0.1167 - val_loss: 0.0083 - val_mae: 0.0836
Epoch 31/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 219s 299ms/step - loss: 0.0136 - mae: 0.1137 - val_loss: 0.0076 - val_mae: 0.0802
Epoch 32/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 205s 298ms/step - loss: 0.0136 - mae: 0.1146 - val_loss: 0.0077 - val_mae: 0.0813
Epoch 33/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 193s 277ms/step - loss: 0.0149 - mae: 0.1172 - val_loss: 0.0083 - val_mae: 0.0810
Epoch 34/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 200s 267ms/step - loss: 0.0130 - mae: 0.1098 - val_loss: 0.0085 - val_mae: 0.0818
Epoch 35/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 191s 243ms/step - loss: 0.0116 - mae: 0.1052 - val_loss: 0.0122 - val_mae: 0.1012
Epoch 36/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 106s 175ms/step - loss: 0.0118 - mae: 0.1052 - val_loss: 0.0096 - val_mae: 0.0875
Epoch 37/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 165s 212ms/step - loss: 0.0122 - mae: 0.1062 - val_loss: 0.0085 - val_mae: 0.0785
Epoch 38/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 110s 190ms/step - loss: 0.0128 - mae: 0.1095 - val_loss: 0.0074 - val_mae: 0.0782
Epoch 39/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 129s 166ms/step - loss: 0.0138 - mae: 0.1105 - val_loss: 0.0079 - val_mae: 0.0791
Epoch 40/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 162s 198ms/step - loss: 0.0111 - mae: 0.1029 - val_loss: 0.0086 - val_mae: 0.0818
Epoch 41/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 113s 145ms/step - loss: 0.0108 - mae: 0.0971 - val_loss: 0.0103 - val_mae: 0.0887
Epoch 42/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 215s 269ms/step - loss: 0.0110 - mae: 0.0995 - val_loss: 0.0106 - val_mae: 0.0834
Epoch 43/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 172s 211ms/step - loss: 0.0121 - mae: 0.1019 - val_loss: 0.0080 - val_mae: 0.0795
Epoch 44/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 138s 202ms/step - loss: 0.0104 - mae: 0.0993 - val_loss: 0.0118 - val_mae: 0.0908
Epoch 45/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 145s 200ms/step - loss: 0.0093 - mae: 0.0914 - val_loss: 0.0131 - val_mae: 0.1016
Epoch 46/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 122s 210ms/step - loss: 0.0102 - mae: 0.0967 - val_loss: 0.0108 - val_mae: 0.0925
Epoch 47/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 112s 192ms/step - loss: 0.0091 - mae: 0.0904 - val_loss: 0.0120 - val_mae: 0.1012
Epoch 48/100
575/575 ━━━━━━━━━━━━━━━━━━━━ 151s 204ms/step - loss: 0.0092 - mae: 0.0932 - val_loss: 0.0076 - val_mae: 0.0745

In [62]:
Forecast_predictions = Forecast_model.predict(X_test_windowed)
Forecast_predictions

30/30 ━━━━━━━━━━━━━━━━━━━━ 28s 689ms/step

array([[0.90593344],
       [0.89468503],
       [0.8679791 ],
       [0.8659721 ],
       [0.8694522 ],
       [0.8163233 ],
       [0.66185194],
       [0.3333025 ],
       [0.        ],
       [0.        ],
       [0.6921209 ],
       [0.8798448 ],
       [0.86563236],
       [0.8994745 ],
       [0.8923542 ],
       [0.8746653 ],
       [0.872284  ],
       [0.88262314],
       [0.82266086],
       [0.7106226 ],
       [0.4136085 ],
       [0.        ],
       [0.        ],
       [0.75302255],
       [0.9105719 ],
       [0.88341695],
       [0.8959858 ],
       [0.8710844 ],
       [0.8619146 ],
       [0.75655013],
       [0.7633082 ],
       [0.63623786],
       [0.27426973],
       [0.        ],
       [0.        ],
       [0.7483559 ],
       [0.86896545],
       [0.8295423 ],
       [0.8873877 ],
       [0.8794565 ],
       [0.8727062 ],
       [0.90841347],
       [0.81934977],
       [0.62559754],
       [0.29584363],
       [0.        ],
       [0.        ],
       [0.77108765],
       [0.9261088 ],
       [0.9197213 ],
       [0.91318375],
       [0.8909691 ],
       [0.8737511 ],
       [0.8814973 ],
       [0.83346957],
       [0.7706313 ],
       [0.37958956],
       [0.4044293 ],
       [0.83917946],
       [0.9527761 ],
       [0.93109745],
       [0.9544192 ],
       [0.9244539 ],
       [0.92672473],
       [0.88020104],
       [0.91041774],
       [0.8265323 ],
       [0.74677575],
       [0.38610843],
       [0.        ],
       [0.        ],
       [0.9220379 ],
       [0.9419021 ],
       [0.9295467 ],
       [0.8975996 ],
       [0.9014958 ],
       [0.869741  ],
       [0.84637886],
       [0.6853657 ],
       [0.42997473],
       [0.        ],
       [0.2124089 ],
       [0.85578364],
       [0.915769  ],
       [0.88781327],
       [0.92658323],
       [0.86691403],
       [0.87573296],
       [0.84932524],
       [0.8239035 ],
       [0.6729357 ],
       [0.27083662],
       [0.        ],
       [0.        ],
       [0.7829405 ],
       [0.8696632 ],
       [0.8778392 ],
       [0.8801623 ],
       [0.8576873 ],
       [0.8271772 ],
       [0.8362867 ],
       [0.7752815 ],
       [0.635123  ],
       [0.27483147],
       [0.        ],
       [0.        ],
       [0.8732695 ],
       [0.847039  ],
       [0.85108143],
       [0.87480664],
       [0.877842  ],
       [0.845895  ],
       [0.8543368 ],
       [0.77664256],
       [0.66022134],
       [0.32043877],
       [0.        ],
       [0.27969593],
       [0.8698156 ],
       [0.89333326],
       [0.8146904 ],
       [0.70601094],
       [0.770704  ],
       [0.7935491 ],
       [0.788452  ],
       [0.49318594],
       [0.298002  ],
       [0.        ],
       [0.        ],
       [0.79478544],
       [0.8839572 ],
       [0.86750346],
       [0.9425048 ],
       [0.8901348 ],
       [0.88873047],
       [0.8490726 ],
       [0.8188682 ],
       [0.65698767],
       [0.31911662],
       [0.        ],
       [0.        ],
       [0.71288836],
       [0.8840216 ],
       [0.87093586],
       [0.9010647 ],
       [0.8671898 ],
       [0.8540094 ],
       [0.8518984 ],
       [0.7992918 ],
       [0.6813593 ],
       [0.30966836],
       [0.        ],
       [0.        ],
       [0.7178263 ],
       [0.88251257],
       [0.89593   ],
       [0.901974  ],
       [0.886538  ],
       [0.8633514 ],
       [0.88060015],
       [0.8121733 ],
       [0.7021475 ],
       [0.3624969 ],
       [0.        ],
       [0.        ],
       [0.8175836 ],
       [0.89296347],
       [0.9108644 ],
       [0.8945869 ],
       [0.91040546],
       [0.8843444 ],
       [0.8619093 ],
       [0.74605286],
       [0.65203184],
       [0.2659775 ],
       [0.        ],
       [0.8213899 ],
       [0.97541577],
       [0.96777064],
       [0.9850585 ],
       [0.9541983 ],
       [0.9643052 ],
       [0.8529737 ],
       [0.8306412 ],
       [0.7704429 ],
       [0.8324939 ],
       [0.8623646 ],
       [0.892019  ],
       [0.87836415],
       [0.89960974],
       [0.8570619 ],
       [0.8437387 ],
       [0.8007116 ],
       [0.867387  ],
       [0.85930496],
       [0.91409713],
       [0.88748866],
       [0.8743306 ],
       [0.84754276],
       [0.83211344],
       [0.77758974],
       [0.61185586],
       [0.3409689 ],
       [0.4122033 ],
       [0.8871651 ],
       [0.84608334],
       [0.8543444 ],
       [0.8182902 ],
       [0.81575316],
       [0.76268923],
       [0.62715626],
       [0.4141688 ],
       [0.8255041 ],
       [0.81019956],
       [0.83170265],
       [0.79143244],
       [0.7889477 ],
       [0.7371775 ],
       [0.6413145 ],
       [0.4955696 ],
       [0.7161927 ],
       [0.8905631 ],
       [0.8632317 ],
       [0.85830635],
       [0.81349623],
       [0.72729313],
       [0.6977881 ],
       [0.8393409 ],
       [0.80205387],
       [0.80915684],
       [0.81145066],
       [0.88526434],
       [0.8772351 ],
       [0.8941632 ],
       [0.87126315],
       [0.88524956],
       [0.83505654],
       [0.83147746],
       [0.7986885 ],
       [0.88766176],
       [0.87971514],
       [0.8703776 ],
       [0.8453812 ],
       [0.8245827 ],
       [0.7594491 ],
       [0.6193217 ],
       [0.5271654 ],
       [0.8130924 ],
       [0.7910437 ],
       [0.7914458 ],
       [0.7707424 ],
       [0.7428566 ],
       [0.6183567 ],
       [0.4069443 ],
       [0.552134  ],
       [0.83307475],
       [0.8189052 ],
       [0.80571634],
       [0.8167414 ],
       [0.8011933 ],
       [0.72801065],
       [0.4255309 ],
       [0.29272068],
       [0.12962705],
       [0.75515914],
       [0.84427595],
       [0.6973864 ],
       [0.59563565],
       [0.5366066 ],
       [0.48268414],
       [0.4583948 ],
       [0.45018893],
       [0.43167531],
       [0.25848553],
       [0.6381977 ],
       [0.82375324],
       [0.8367441 ],
       [0.8457143 ],
       [0.83163357],
       [0.83616406],
       [0.74821156],
       [0.6261823 ],
       [0.20918888],
       [0.        ],
       [0.5622082 ],
       [0.8099302 ],
       [0.79938334],
       [0.8009064 ],
       [0.7699023 ],
       [0.7734301 ],
       [0.6620024 ],
       [0.5748465 ],
       [0.47329575],
       [0.29891035],
       [0.74542254],
       [0.8482166 ],
       [0.8231563 ],
       [0.8080525 ],
       [0.76786613],
       [0.78828114],
       [0.7593127 ],
       [0.60739136],
       [0.39631176],
       [0.21059899],
       [0.79882175],
       [0.7637078 ],
       [0.7020655 ],
       [0.6913789 ],
       [0.7001871 ],
       [0.65212667],
       [0.6325816 ],
       [0.74319845],
       [0.7938215 ],
       [0.7257174 ],
       [0.7208641 ],
       [0.72439945],
       [0.6570233 ],
       [0.6601416 ],
       [0.6316894 ],
       [0.6269529 ],
       [0.68986565],
       [0.6990467 ],
       [0.7402581 ],
       [0.69027567],
       [0.6384207 ],
       [0.5282828 ],
       [0.5992475 ],
       [0.4944085 ],
       [0.5092488 ],
       [0.37987828],
       [0.752291  ],
       [0.7892323 ],
       [0.8155031 ],
       [0.8295768 ],
       [0.7840007 ],
       [0.74149334],
       [0.30910787],
       [0.31447557],
       [0.5368096 ],
       [0.58182037],
       [0.5532828 ],
       [0.59690166],
       [0.53755295],
       [0.55456066],
       [0.418101  ],
       [0.2937346 ],
       [0.28327447],
       [0.45152256],
       [0.56968725],
       [0.43985194],
       [0.41588295],
       [0.3108762 ],
       [0.5605057 ],
       [0.62362015],
       [0.55499214],
       [0.5493823 ],
       [0.472572  ],
       [0.359564  ],
       [0.5543628 ],
       [0.42169124],
       [0.4124481 ],
       [0.3545115 ],
       [0.35056496],
       [0.35486156],
       [0.33998525],
       [0.33056653],
       [0.7650595 ],
       [0.8005857 ],
       [0.81222796],
       [0.76631105],
       [0.8168698 ],
       [0.7213562 ],
       [0.61495   ],
       [0.32203066],
       [0.3188278 ],
       [0.79265124],
       [0.7829135 ],
       [0.80659723],
       [0.78732127],
       [0.78196394],
       [0.7190966 ],
       [0.5606384 ],
       [0.49788207],
       [0.8106574 ],
       [0.78977716],
       [0.8125896 ],
       [0.78697497],
       [0.7952481 ],
       [0.7282313 ],
       [0.62720555],
       [0.5366332 ],
       [0.8541295 ],
       [0.80957395],
       [0.8215166 ],
       [0.8384773 ],
       [0.7191932 ],
       [0.66941875],
       [0.5738231 ],
       [0.5484482 ],
       [0.7053054 ],
       [0.68933004],
       [0.66740906],
       [0.62953746],
       [0.61808926],
       [0.62484634],
       [0.6702386 ],
       [0.7992438 ],
       [0.7689155 ],
       [0.7358681 ],
       [0.7284812 ],
       [0.7207046 ],
       [0.7055118 ],
       [0.85967535],
       [0.8276972 ],
       [0.82091993],
       [0.76040435],
       [0.71691775],
       [0.80220336],
       [0.78204364],
       [0.7505371 ],
       [0.7417073 ],
       [0.71359694],
       [0.7070494 ],
       [0.6906476 ],
       [0.6783867 ],
       [0.63320976],
       [0.5957277 ],
       [0.4075452 ],
       [0.34578943],
       [0.5360452 ],
       [0.8222607 ],
       [0.77718323],
       [0.78139585],
       [0.749209  ],
       [0.71435016],
       [0.64642715],
       [0.63608843],
       [0.83460325],
       [0.83139783],
       [0.83576125],
       [0.78601086],
       [0.77075416],
       [0.662926  ],
       [0.55022997],
       [0.3706361 ],
       [0.7054108 ],
       [0.84943086],
       [0.8402614 ],
       [0.84115523],
       [0.8256993 ],
       [0.82133114],
       [0.7912515 ],
       [0.6667887 ],
       [0.39916223],
       [0.5214107 ],
       [0.8619345 ],
       [0.84419686],
       [0.824328  ],
       [0.75233084],
       [0.7820857 ],
       [0.76278186],
       [0.5742761 ],
       [0.30232683],
       [0.6083609 ],
       [0.86403996],
       [0.84582096],
       [0.8600284 ],
       [0.8451855 ],
       [0.85190785],
       [0.80320174],
       [0.6622601 ],
       [0.29393518],
       [0.        ],
       [0.4932246 ],
       [0.8937652 ],
       [0.87133646],
       [0.87902737],
       [0.8431473 ],
       [0.8497074 ],
       [0.78504354],
       [0.6641991 ],
       [0.3230703 ],
       [0.        ],
       [0.7635186 ],
       [0.90195376],
       [0.88162774],
       [0.87373424],
       [0.84522873],
       [0.8356413 ],
       [0.8070082 ],
       [0.63758343],
       [0.39233112],
       [0.312787  ],
       [0.8970615 ],
       [0.8760139 ],
       [0.877747  ],
       [0.83042336],
       [0.83205956],
       [0.781177  ],
       [0.69153965],
       [0.3928947 ],
       [0.        ],
       [0.5867673 ],
       [0.8876401 ],
       [0.8714754 ],
       [0.8389556 ],
       [0.84304893],
       [0.8410624 ],
       [0.8265024 ],
       [0.69995475],
       [0.61599565],
       [0.39345643],
       [0.        ],
       [0.15216884],
       [0.8347812 ],
       [0.84686714],
       [0.8219439 ],
       [0.83789843],
       [0.8066818 ],
       [0.80782884],
       [0.7569131 ],
       [0.63314164],
       [0.36533463],
       [0.        ],
       [0.7272539 ],
       [0.83484095],
       [0.7757566 ],
       [0.7387681 ],
       [0.69270694],
       [0.6629019 ],
       [0.7076868 ],
       [0.5499363 ],
       [0.37727186],
       [0.69018835],
       [0.825771  ],
       [0.79615504],
       [0.8354179 ],
       [0.82096726],
       [0.8139352 ],
       [0.7413943 ],
       [0.59583354],
       [0.3240534 ],
       [0.560282  ],
       [0.80548173],
       [0.80748004],
       [0.81187385],
       [0.811624  ],
       [0.7954224 ],
       [0.7277514 ],
       [0.566704  ],
       [0.        ],
       [0.47328737],
       [0.8773935 ],
       [0.85413873],
       [0.85443836],
       [0.8324357 ],
       [0.82647663],
       [0.7926375 ],
       [0.67622364],
       [0.7129289 ],
       [0.7762287 ],
       [0.7494585 ],
       [0.7286178 ],
       [0.7083493 ],
       [0.69993234],
       [0.6200803 ],
       [0.5119196 ],
       [0.8409355 ],
       [0.8317765 ],
       [0.84481144],
       [0.8429021 ],
       [0.8304215 ],
       [0.7864362 ],
       [0.666836  ],
       [0.40675   ],
       [0.64446145],
       [0.8238124 ],
       [0.8151725 ],
       [0.8052947 ],
       [0.7899675 ],
       [0.7109877 ],
       [0.5491791 ],
       [0.35693336],
       [0.8025477 ],
       [0.79873496],
       [0.8151061 ],
       [0.798217  ],
       [0.80402905],
       [0.7775212 ],
       [0.5773372 ],
       [0.31384295],
       [0.8201566 ],
       [0.81126964],
       [0.80825436],
       [0.77869374],
       [0.71671087],
       [0.5563804 ],
       [0.44788662],
       [0.8303269 ],
       [0.8522219 ],
       [0.8392166 ],
       [0.815525  ],
       [0.7329016 ],
       [0.5658011 ],
       [0.37530813],
       [0.659031  ],
       [0.7485026 ],
       [0.73239034],
       [0.7223582 ],
       [0.69043785],
       [0.5047381 ],
       [0.26336473],
       [0.28240722],
       [0.45594043],
       [0.7018281 ],
       [0.68147343],
       [0.6820257 ],
       [0.66796315],
       [0.581347  ],
       [0.38589513],
       [0.05909266],
       [0.21717843],
       [0.76535034],
       [0.77844405],
       [0.76574   ],
       [0.77365875],
       [0.77444214],
       [0.72289395],
       [0.5500349 ],
       [0.30531484],
       [0.8269562 ],
       [0.80933625],
       [0.7766976 ],
       [0.76567215],
       [0.763092  ],
       [0.6515808 ],
       [0.48832002],
       [0.        ],
       [0.46798328],
       [0.81699306],
       [0.78935796],
       [0.80388695],
       [0.7806613 ],
       [0.7905428 ],
       [0.78093475],
       [0.64395505],
       [0.28984952],
       [0.7044536 ],
       [0.84880406],
       [0.8728439 ],
       [0.83300275],
       [0.812972  ],
       [0.74327546],
       [0.67985386],
       [0.54200745],
       [0.21394923],
       [0.62409985],
       [0.85228246],
       [0.85060054],
       [0.87372833],
       [0.8513027 ],
       [0.8593827 ],
       [0.8198461 ],
       [0.6915673 ],
       [0.2697521 ],
       [0.        ],
       [0.8524658 ],
       [0.912148  ],
       [0.8956174 ],
       [0.91205925],
       [0.87738603],
       [0.86962503],
       [0.8018966 ],
       [0.652775  ],
       [0.322618  ],
       [0.21257785],
       [0.8774459 ],
       [0.86741847],
       [0.866876  ],
       [0.8248088 ],
       [0.82589334],
       [0.75054365],
       [0.6614138 ],
       [0.32616207],
       [0.5121653 ],
       [0.8756269 ],
       [0.8807636 ],
       [0.8692032 ],
       [0.8600282 ],
       [0.83850557],
       [0.8023129 ],
       [0.65112454],
       [0.25566396],
       [0.67507386],
       [0.85971755],
       [0.86201334],
       [0.8608611 ],
       [0.82169646],
       [0.82074434],
       [0.76267236],
       [0.6074766 ],
       [0.12484689],
       [0.60678273],
       [0.83049846],
       [0.8245881 ],
       [0.8158423 ],
       [0.82480997],
       [0.77156156],
       [0.64763194],
       [0.45896035],
       [0.26445034],
       [0.6402056 ],
       [0.7751547 ],
       [0.77567905],
       [0.7789386 ],
       [0.7497913 ],
       [0.6529762 ],
       [0.6309345 ],
       [0.54199654],
       [0.63893664],
       [0.5388991 ],
       [0.5486301 ],
       [0.4755677 ],
       [0.48536032],
       [0.44995397],
       [0.46827197],
       [0.4829605 ],
       [0.63736594],
       [0.49121147],
       [0.39593297],
       [0.38760167],
       [0.2990584 ],
       [0.30332777],
       [0.27821732],
       [0.2842922 ],
       [0.46743917],
       [0.5891106 ],
       [0.5938914 ],
       [0.50383544],
       [0.5106179 ],
       [0.5663955 ],
       [0.6589204 ],
       [0.5223237 ],
       [0.53566027],
       [0.4762913 ],
       [0.3323103 ],
       [0.29539   ],
       [0.2852241 ],
       [0.46147555],
       [0.33202708],
       [0.2994715 ],
       [0.3004282 ],
       [0.3168738 ],
       [0.37630853],
       [0.4388017 ],
       [0.41750732],
       [0.45643824],
       [0.3113884 ],
       [0.31486556],
       [0.31245995],
       [0.30501184],
       [0.31121972],
       [0.31317908],
       [0.30305734],
       [0.620376  ],
       [0.31787673],
       [0.3914141 ],
       [0.32544294],
       [0.58846   ],
       [0.6313334 ],
       [0.38212028],
       [0.3564354 ],
       [0.32256737],
       [0.37736508],
       [0.35260123],
       [0.28413075],
       [0.333906  ],
       [0.7565721 ],
       [0.7640953 ],
       [0.8061785 ],
       [0.77769965],
       [0.8188781 ],
       [0.79801536],
       [0.6767654 ],
       [0.33447856],
       [0.32545748],
       [0.83473593],
       [0.8244229 ],
       [0.8101081 ],
       [0.7887606 ],
       [0.6980078 ],
       [0.57451725],
       [0.25109968],
       [0.45257694],
       [0.82395583],
       [0.81773275],
       [0.80000633],
       [0.7844313 ],
       [0.7763806 ],
       [0.75850004],
       [0.67580557],
       [0.7804368 ],
       [0.7650346 ],
       [0.7784446 ],
       [0.71190786],
       [0.67018116],
       [0.6464784 ],
       [0.6851587 ],
       [0.67719394],
       [0.63489735],
       [0.7408461 ],
       [0.72648287],
       [0.7195085 ],
       [0.69880354],
       [0.78337646],
       [0.7427529 ],
       [0.7308285 ],
       [0.73460734],
       [0.68889916],
       [0.7264821 ],
       [0.70281905],
       [0.64858043],
       [0.7178906 ],
       [0.7056107 ],
       [0.6969843 ],
       [0.7955765 ],
       [0.7439073 ],
       [0.6585663 ],
       [0.65069634],
       [0.66849476],
       [0.6976855 ],
       [0.77872807],
       [0.7348287 ],
       [0.73091096],
       [0.7187865 ],
       [0.6689606 ],
       [0.56823003],
       [0.5085702 ],
       [0.77607125],
       [0.7662843 ],
       [0.736778  ],
       [0.74638337],
       [0.7252046 ],
       [0.6153458 ],
       [0.28344035],
       [0.7771378 ],
       [0.7268448 ],
       [0.73851824],
       [0.7304148 ],
       [0.7223882 ],
       [0.6005458 ],
       [0.23895852],
       [0.6974807 ],
       [0.81225264],
       [0.7831884 ],
       [0.7747148 ],
       [0.7679233 ],
       [0.69911563],
       [0.57555866],
       [0.25264215],
       [0.73390776],
       [0.79973763],
       [0.79490656],
       [0.790261  ],
       [0.76296175],
       [0.7551568 ],
       [0.74966806],
       [0.5170553 ],
       [0.3594713 ],
       [0.7179427 ],
       [0.7451982 ],
       [0.7546702 ],
       [0.7308451 ],
       [0.74336344],
       [0.70373255],
       [0.37864992],
       [0.25203902],
       [0.747045  ],
       [0.7325091 ],
       [0.75103086],
       [0.72723126],
       [0.75219196],
       [0.71153235],
       [0.46352756],
       [0.04274504],
       [0.68457335],
       [0.8044032 ],
       [0.7554682 ],
       [0.76299274],
       [0.7446248 ],
       [0.7107562 ],
       [0.53741217],
       [0.54432285],
       [0.7352815 ],
       [0.7483254 ],
       [0.76355845],
       [0.71828616],
       [0.67143965],
       [0.5657978 ],
       [0.3779071 ],
       [0.2454372 ],
       [0.7257487 ],
       [0.72997695],
       [0.732105  ],
       [0.68255585],
       [0.68761486],
       [0.5569167 ],
       [0.74720746],
       [0.73431355],
       [0.76194113],
       [0.7049248 ],
       [0.65031314],
       [0.5843037 ],
       [0.63417554],
       [0.7561234 ],
       [0.7742166 ],
       [0.76065016],
       [0.7408992 ],
       [0.66940856],
       [0.4725392 ],
       [0.25871754],
       [0.6927356 ],
       [0.782654  ],
       [0.7533699 ],
       [0.75085205],
       [0.75135   ],
       [0.70299315],
       [0.48575002],
       [0.15582414],
       [0.7136687 ],
       [0.7599912 ],
       [0.7688958 ],
       [0.76658624],
       [0.76070124],
       [0.7638019 ],
       [0.7021126 ],
       [0.4155105 ],
       [0.        ],
       [0.6058129 ],
       [0.79601616],
       [0.7755411 ],
       [0.7545319 ],
       [0.75644404],
       [0.70153934],
       [0.4080882 ],
       [0.        ],
       [0.17391956]], dtype=float32)

In [63]:
Forecast_predictions = y_scaler.inverse_transform(Forecast_predictions.reshape(-1, 1))
Forecast_predictions = np.clip(Forecast_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [64]:
Forecast_resultados = pd.DataFrame(Forecast_predictions, index = y_test_windowed.index, columns=["Forecast"])

In [65]:
predicciones["Forecast"] = Forecast_resultados["Forecast"]
predicciones

       Generación      LightGBM Random Forest         CTNET      Forecast
15328     27864.0  27737.854623    27676.1575           NaN           NaN
15329     24624.0  27486.133289      27436.08           NaN           NaN
15330     23657.0  24127.781396  24350.938017           NaN           NaN
15331     20683.0  20469.172397  20043.384431           NaN           NaN
15332     10703.0  10001.014624      10626.32           NaN           NaN
...           ...           ...           ...           ...           ...
18281     25386.0  27249.220044  26034.882309  23223.203125  22693.320312
18282     22872.0  22924.525455  23229.408141  22499.527344  21046.179688
18283     15825.0  14677.255501  15735.242934  15411.343750  12242.646484
18284      1450.0   2147.631109   2056.066838   2882.268066      0.000000
18285         0.0     17.321742           0.0  16132.508789   5217.586914

[995 rows x 5 columns]

## Métricas

In [66]:
predicciones.loc[~predicciones['CTNET'].isna(),'Generación']

15421    28253.0
15422    28466.0
15423    28672.0
15424    28678.0
15425    27723.0
          ...
18281    25386.0
18282    22872.0
18283    15825.0
18284     1450.0
18285        0.0
Name: Generación, Length: 947, dtype: float64

## Photovoltaic

In [67]:
from tensorflow.keras.models import Model
inputs = Input(shape=(X_train_windowed.shape[1], X_train_windowed.shape[2]))

# Primera capa CNN
x = Conv1D(filters=64, kernel_size=4, padding='same', activation='relu')(inputs)
x = MaxPooling1D(pool_size=2)(x)

# Segunda capa CNN
x = Conv1D(filters=128, kernel_size=4, padding='same', activation='relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# Capa BiGRU
x = Bidirectional(GRU(64, return_sequences=True))(x)

# Atención: se define de forma explícita
attention = MultiHeadAttention(num_heads=4, key_dim=128)(x, x)

# Aplanar y agregar Dropout
x = Flatten()(attention)
x = Dropout(0.4)(x)
initializer = tf.keras.initializers.HeNormal()
x = Dense(64, activation="relu", kernel_regularizer=l2(0.01))(x)
x = Dense(32, activation="relu")(x)  # Otra capa intermedia

# Capa de salida
outputs = Dense(1, activation="linear")(x)

# Definir el modelo
Photo_model = Model(inputs=inputs, outputs=outputs)

# Resumen del modelo
Photo_model.summary()

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 48, 6)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_13 (Conv1D)  │ (None, 48, 64)    │      1,600 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 24, 64)    │          0 │ conv1d_13[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_14 (Conv1D)  │ (None, 24, 128)   │     32,896 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_2     │ (None, 12, 128)   │          0 │ conv1d_14[0][0]   │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 12, 128)   │     74,496 │ max_pooling1d_2[… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 12, 128)   │    263,808 │ bidirectional_3[… │
│ (MultiHeadAttentio… │                   │            │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 1536)      │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_11          │ (None, 1536)      │          0 │ flatten[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │     98,368 │ dropout_11[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 32)        │      2,080 │ dense_10[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 1)         │         33 │ dense_11[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 473,281 (1.81 MB)

 Trainable params: 473,281 (1.81 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
cp2 = ModelCheckpoint('Photovoltaic_model.keras', save_best_only=True)
Photo_model.compile(optimizer=Adam(learning_rate=0.0001), loss="mean_squared_error", metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [69]:
history = Photo_model.fit(
    X_train_windowed, y_train_windowed,
    validation_data=(X_val_windowed, y_val_windowed),
    epochs=50,
    batch_size=16,
    callbacks=[cp, early_stop]
)

Epoch 1/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 174s 151ms/step - loss: 1.1302 - mae: 0.3101 - val_loss: 0.5877 - val_mae: 0.3451
Epoch 2/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 32s 97ms/step - loss: 0.4581 - mae: 0.2543 - val_loss: 0.2157 - val_mae: 0.1701
Epoch 3/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 39s 89ms/step - loss: 0.1826 - mae: 0.1560 - val_loss: 0.0988 - val_mae: 0.1214
Epoch 4/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 42s 87ms/step - loss: 0.0949 - mae: 0.1307 - val_loss: 0.0654 - val_mae: 0.1318
Epoch 5/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 43s 87ms/step - loss: 0.0621 - mae: 0.1254 - val_loss: 0.0650 - val_mae: 0.1642
Epoch 6/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 46s 94ms/step - loss: 0.0491 - mae: 0.1243 - val_loss: 0.0348 - val_mae: 0.1087
Epoch 7/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 43s 99ms/step - loss: 0.0403 - mae: 0.1186 - val_loss: 0.0283 - val_mae: 0.0964
Epoch 8/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 41s 93ms/step - loss: 0.0342 - mae: 0.1131 - val_loss: 0.0375 - val_mae: 0.1335
Epoch 9/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 42s 93ms/step - loss: 0.0306 - mae: 0.1106 - val_loss: 0.0232 - val_mae: 0.0974
Epoch 10/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 42s 90ms/step - loss: 0.0296 - mae: 0.1110 - val_loss: 0.0276 - val_mae: 0.1073
Epoch 11/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 49s 116ms/step - loss: 0.0274 - mae: 0.1054 - val_loss: 0.0198 - val_mae: 0.0900
Epoch 12/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 35s 90ms/step - loss: 0.0238 - mae: 0.1010 - val_loss: 0.0197 - val_mae: 0.0913
Epoch 13/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 44s 93ms/step - loss: 0.0232 - mae: 0.0977 - val_loss: 0.0193 - val_mae: 0.0910
Epoch 14/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 40s 84ms/step - loss: 0.0237 - mae: 0.1021 - val_loss: 0.0174 - val_mae: 0.0847
Epoch 15/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - loss: 0.0222 - mae: 0.0979 - val_loss: 0.0187 - val_mae: 0.0887
Epoch 16/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 48s 105ms/step - loss: 0.0221 - mae: 0.0979 - val_loss: 0.0172 - val_mae: 0.0851
Epoch 17/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 38s 127ms/step - loss: 0.0221 - mae: 0.0945 - val_loss: 0.0164 - val_mae: 0.0804
Epoch 18/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 36s 98ms/step - loss: 0.0209 - mae: 0.0943 - val_loss: 0.0175 - val_mae: 0.0911
Epoch 19/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 39s 85ms/step - loss: 0.0212 - mae: 0.0948 - val_loss: 0.0159 - val_mae: 0.0816
Epoch 20/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 37s 70ms/step - loss: 0.0202 - mae: 0.0912 - val_loss: 0.0156 - val_mae: 0.0808
Epoch 21/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 30s 96ms/step - loss: 0.0194 - mae: 0.0911 - val_loss: 0.0200 - val_mae: 0.0969
Epoch 22/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 41s 91ms/step - loss: 0.0203 - mae: 0.0919 - val_loss: 0.0201 - val_mae: 0.0973
Epoch 23/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 29s 94ms/step - loss: 0.0185 - mae: 0.0893 - val_loss: 0.0203 - val_mae: 0.1020
Epoch 24/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0189 - mae: 0.0894 - val_loss: 0.0173 - val_mae: 0.0914
Epoch 25/50
288/288 ━━━━━━━━━━━━━━━━━━━━ 41s 139ms/step - loss: 0.0182 - mae: 0.0891 - val_loss: 0.0164 - val_mae: 0.0831

In [70]:
Photo_predictions = Photo_model.predict(X_test_windowed)
Photo_predictions

30/30 ━━━━━━━━━━━━━━━━━━━━ 25s 219ms/step

array([[0.944848  ],
       [0.9413351 ],
       [0.89030194],
       [0.9196884 ],
       [0.88631845],
       [0.83406425],
       [0.71732914],
       [0.4793254 ],
       [0.00896139],
       [0.00492401],
       [0.44046012],
       [0.84171927],
       [0.88459235],
       [0.9415931 ],
       [0.9180594 ],
       [0.90378505],
       [0.9089012 ],
       [0.8947825 ],
       [0.8709169 ],
       [0.75766456],
       [0.44970965],
       [0.01809145],
       [0.01185508],
       [0.62786245],
       [0.93421346],
       [0.9429063 ],
       [0.9565627 ],
       [0.9267876 ],
       [0.90782785],
       [0.8534126 ],
       [0.8263086 ],
       [0.7197625 ],
       [0.30606046],
       [0.01599721],
       [0.02010973],
       [0.66034687],
       [0.89905584],
       [0.8755655 ],
       [0.9363746 ],
       [0.9323505 ],
       [0.895312  ],
       [0.9152453 ],
       [0.8792418 ],
       [0.66820395],
       [0.2719837 ],
       [0.01914129],
       [0.01500765],
       [0.62843037],
       [0.90968347],
       [0.94601977],
       [0.9382936 ],
       [0.9439633 ],
       [0.91075444],
       [0.8846339 ],
       [0.8486795 ],
       [0.79090965],
       [0.57768744],
       [0.46969005],
       [0.8653858 ],
       [0.952817  ],
       [0.94001025],
       [0.97250557],
       [0.98069364],
       [0.98149884],
       [0.95127213],
       [0.9359443 ],
       [0.8983135 ],
       [0.7888622 ],
       [0.4552736 ],
       [0.03703899],
       [0.36104038],
       [0.92826694],
       [0.96306616],
       [0.9728838 ],
       [0.960251  ],
       [0.9616287 ],
       [0.92879546],
       [0.89297384],
       [0.7428468 ],
       [0.48621628],
       [0.03104858],
       [0.27963835],
       [0.86215615],
       [0.97748274],
       [0.9605571 ],
       [0.96760243],
       [0.9560473 ],
       [0.9823724 ],
       [0.9335375 ],
       [0.87808126],
       [0.7409258 ],
       [0.24423106],
       [0.01307579],
       [0.04747888],
       [0.80945617],
       [0.9436655 ],
       [0.9204141 ],
       [0.95327115],
       [0.939577  ],
       [0.94155926],
       [0.90589964],
       [0.87182903],
       [0.70210785],
       [0.34161225],
       [0.03066603],
       [0.38300902],
       [0.91777545],
       [0.90763515],
       [0.8950503 ],
       [0.9421223 ],
       [0.94238204],
       [0.934816  ],
       [0.9078301 ],
       [0.86338174],
       [0.726338  ],
       [0.31079733],
       [0.02887843],
       [0.37114504],
       [0.91072965],
       [0.9267454 ],
       [0.885843  ],
       [0.79882556],
       [0.82093716],
       [0.86317   ],
       [0.8403748 ],
       [0.6190258 ],
       [0.32940242],
       [0.01716444],
       [0.144223  ],
       [0.76599085],
       [0.9342623 ],
       [0.89634025],
       [0.9678055 ],
       [0.9837494 ],
       [0.98150396],
       [0.9151249 ],
       [0.8637785 ],
       [0.706593  ],
       [0.35537565],
       [0.01018781],
       [0.02281306],
       [0.68948793],
       [0.9190039 ],
       [0.9244164 ],
       [0.9499239 ],
       [0.93094516],
       [0.9245639 ],
       [0.9011252 ],
       [0.8660734 ],
       [0.74569434],
       [0.3829812 ],
       [0.01097987],
       [0.00594196],
       [0.5990625 ],
       [0.92088926],
       [0.92480254],
       [0.9326638 ],
       [0.9390744 ],
       [0.9065739 ],
       [0.89735246],
       [0.8678327 ],
       [0.7769598 ],
       [0.42929545],
       [0.0136091 ],
       [0.00508101],
       [0.63989466],
       [0.9230071 ],
       [0.9378995 ],
       [0.9382898 ],
       [0.9689135 ],
       [0.9078679 ],
       [0.925388  ],
       [0.81864953],
       [0.6216556 ],
       [0.28127024],
       [0.20729281],
       [0.749537  ],
       [1.021993  ],
       [1.0045097 ],
       [1.0040941 ],
       [0.9759786 ],
       [1.0043101 ],
       [0.9211978 ],
       [0.7901778 ],
       [0.80498016],
       [0.86169195],
       [0.94367313],
       [0.92887294],
       [0.96351504],
       [0.94909835],
       [0.92263645],
       [0.91232187],
       [0.9212347 ],
       [0.99636436],
       [1.0387838 ],
       [0.9853698 ],
       [0.96435773],
       [0.9819183 ],
       [0.9354489 ],
       [0.91857576],
       [0.8713682 ],
       [0.6735122 ],
       [0.37392887],
       [0.5323772 ],
       [0.9619381 ],
       [0.9248214 ],
       [0.91590124],
       [0.88103145],
       [0.8854742 ],
       [0.86714876],
       [0.740203  ],
       [0.5540123 ],
       [0.8872869 ],
       [0.9281039 ],
       [0.9075841 ],
       [0.86047107],
       [0.8429908 ],
       [0.8468738 ],
       [0.7594141 ],
       [0.6530913 ],
       [0.7558138 ],
       [0.9645735 ],
       [0.9292462 ],
       [0.9335683 ],
       [0.8822669 ],
       [0.8094181 ],
       [0.8310214 ],
       [0.9582777 ],
       [0.9486339 ],
       [0.95806503],
       [0.9331151 ],
       [0.96474135],
       [1.0038533 ],
       [1.026471  ],
       [1.0118163 ],
       [0.9983781 ],
       [0.93881655],
       [0.89366317],
       [0.942038  ],
       [1.017391  ],
       [0.97013617],
       [0.9714757 ],
       [0.93908787],
       [0.9260993 ],
       [0.87514436],
       [0.75033796],
       [0.69395757],
       [0.9262432 ],
       [0.9321157 ],
       [0.9157336 ],
       [0.9043797 ],
       [0.8624865 ],
       [0.77971405],
       [0.6065832 ],
       [0.67681444],
       [0.9388895 ],
       [0.93599397],
       [0.9254214 ],
       [0.9150882 ],
       [0.8841219 ],
       [0.8287519 ],
       [0.5767827 ],
       [0.38553503],
       [0.21098498],
       [0.66801274],
       [0.93702507],
       [0.7719016 ],
       [0.6206318 ],
       [0.5428816 ],
       [0.4727731 ],
       [0.292071  ],
       [0.3176424 ],
       [0.53657454],
       [0.34599513],
       [0.34991655],
       [0.82633245],
       [0.9401797 ],
       [0.94885945],
       [0.94782007],
       [0.9183569 ],
       [0.844886  ],
       [0.61098754],
       [0.40280023],
       [0.24184449],
       [0.5482104 ],
       [0.82750607],
       [0.87426174],
       [0.8662039 ],
       [0.8553876 ],
       [0.8342557 ],
       [0.81757045],
       [0.73137224],
       [0.6612007 ],
       [0.54794085],
       [0.88454545],
       [0.93110144],
       [0.9357648 ],
       [0.9253484 ],
       [0.9050423 ],
       [0.8853358 ],
       [0.86994517],
       [0.68869054],
       [0.4619629 ],
       [0.29126063],
       [0.8406831 ],
       [0.87809926],
       [0.77615595],
       [0.7705731 ],
       [0.7755625 ],
       [0.7641039 ],
       [0.74756205],
       [0.82510877],
       [0.9060206 ],
       [0.8567742 ],
       [0.8374119 ],
       [0.7500669 ],
       [0.69026303],
       [0.6414766 ],
       [0.59155655],
       [0.45324466],
       [0.451578  ],
       [0.56175137],
       [0.7030247 ],
       [0.6935635 ],
       [0.6745215 ],
       [0.6699413 ],
       [0.6598978 ],
       [0.5714925 ],
       [0.512774  ],
       [0.46556506],
       [0.7019808 ],
       [0.8162766 ],
       [0.8570466 ],
       [0.8475169 ],
       [0.82369447],
       [0.7824516 ],
       [0.5906293 ],
       [0.52952063],
       [0.5114224 ],
       [0.66272044],
       [0.64822805],
       [0.6482606 ],
       [0.62102175],
       [0.67143303],
       [0.6076133 ],
       [0.51195323],
       [0.5771685 ],
       [0.6122626 ],
       [0.698238  ],
       [0.62236524],
       [0.5808728 ],
       [0.4962939 ],
       [0.58114576],
       [0.70456326],
       [0.73593664],
       [0.7204428 ],
       [0.6950071 ],
       [0.61227906],
       [0.6487149 ],
       [0.65508807],
       [0.6872317 ],
       [0.64148587],
       [0.6348945 ],
       [0.5533311 ],
       [0.6071899 ],
       [0.6504749 ],
       [0.8647723 ],
       [0.90142846],
       [0.87886673],
       [0.8361293 ],
       [0.8583339 ],
       [0.8051756 ],
       [0.7609183 ],
       [0.5356865 ],
       [0.39401886],
       [0.9067025 ],
       [0.884295  ],
       [0.8918287 ],
       [0.8710691 ],
       [0.86779076],
       [0.83871233],
       [0.7360516 ],
       [0.72592556],
       [0.92544734],
       [0.9296637 ],
       [0.9128524 ],
       [0.8928207 ],
       [0.8744059 ],
       [0.855789  ],
       [0.775098  ],
       [0.73977613],
       [0.93563735],
       [0.93915856],
       [0.9028582 ],
       [0.90169024],
       [0.80550563],
       [0.73199093],
       [0.64487803],
       [0.5616901 ],
       [0.70925033],
       [0.7071196 ],
       [0.654366  ],
       [0.60549164],
       [0.57934165],
       [0.60863155],
       [0.64600223],
       [0.7941513 ],
       [0.80515546],
       [0.82753325],
       [0.7971876 ],
       [0.7578909 ],
       [0.7232748 ],
       [0.84635204],
       [0.8554243 ],
       [0.8735893 ],
       [0.82411027],
       [0.83317125],
       [0.8808524 ],
       [0.9272685 ],
       [0.90066636],
       [0.9022932 ],
       [0.81597173],
       [0.82826275],
       [0.841418  ],
       [0.8411801 ],
       [0.79429996],
       [0.7503315 ],
       [0.6200464 ],
       [0.49863318],
       [0.5888471 ],
       [0.9486393 ],
       [0.94591737],
       [0.932511  ],
       [0.9049798 ],
       [0.8733283 ],
       [0.84046113],
       [0.8782127 ],
       [0.9721856 ],
       [0.92837304],
       [0.93926156],
       [0.891223  ],
       [0.8816296 ],
       [0.811625  ],
       [0.70396364],
       [0.551642  ],
       [0.73852587],
       [0.9887719 ],
       [0.9500975 ],
       [0.94797343],
       [0.91636646],
       [0.9003781 ],
       [0.8731935 ],
       [0.7610499 ],
       [0.4761677 ],
       [0.47900873],
       [0.9634577 ],
       [0.93335956],
       [0.9063325 ],
       [0.8439294 ],
       [0.84408045],
       [0.8078896 ],
       [0.6775995 ],
       [0.37510905],
       [0.58862233],
       [0.9398449 ],
       [0.91462296],
       [0.9331137 ],
       [0.9166004 ],
       [0.9107543 ],
       [0.8508439 ],
       [0.67801696],
       [0.39698455],
       [0.0399161 ],
       [0.5796807 ],
       [0.9295359 ],
       [0.9052932 ],
       [0.91973305],
       [0.915179  ],
       [0.8978003 ],
       [0.8684573 ],
       [0.7324048 ],
       [0.42508233],
       [0.0787482 ],
       [0.7457021 ],
       [0.9404012 ],
       [0.9352986 ],
       [0.92682314],
       [0.92270637],
       [0.8988714 ],
       [0.8936744 ],
       [0.711065  ],
       [0.43850654],
       [0.2838482 ],
       [0.980401  ],
       [0.9307984 ],
       [0.9360819 ],
       [0.8808775 ],
       [0.9019739 ],
       [0.8565167 ],
       [0.75124395],
       [0.481286  ],
       [0.10086668],
       [0.6494876 ],
       [0.89944905],
       [0.8985705 ],
       [0.9030114 ],
       [0.9163718 ],
       [0.8949306 ],
       [0.9061736 ],
       [0.78730273],
       [0.5663818 ],
       [0.35803786],
       [0.01866154],
       [0.45069316],
       [0.88824576],
       [0.8865006 ],
       [0.9124432 ],
       [0.9161259 ],
       [0.8882942 ],
       [0.9115764 ],
       [0.85699373],
       [0.69832706],
       [0.3936232 ],
       [0.04433683],
       [0.7185888 ],
       [0.89719677],
       [0.85047984],
       [0.8216853 ],
       [0.7953541 ],
       [0.7822664 ],
       [0.7868942 ],
       [0.69548655],
       [0.44567028],
       [0.719917  ],
       [0.943627  ],
       [0.9107028 ],
       [0.9555143 ],
       [0.90736127],
       [0.93500674],
       [0.86579376],
       [0.6597756 ],
       [0.37467906],
       [0.52678794],
       [0.89357376],
       [0.8790763 ],
       [0.89186144],
       [0.8698    ],
       [0.87009037],
       [0.79710996],
       [0.66553366],
       [0.3072815 ],
       [0.6671715 ],
       [0.9516234 ],
       [0.90619195],
       [0.9204229 ],
       [0.88676697],
       [0.8838135 ],
       [0.8744061 ],
       [0.76542306],
       [0.77515715],
       [0.8984135 ],
       [0.84826636],
       [0.8166263 ],
       [0.7877605 ],
       [0.8070918 ],
       [0.7676191 ],
       [0.71027696],
       [0.9406161 ],
       [0.9324282 ],
       [0.9385997 ],
       [0.9138262 ],
       [0.9297726 ],
       [0.8608734 ],
       [0.72406536],
       [0.5037304 ],
       [0.6801468 ],
       [0.92620593],
       [0.89294267],
       [0.9051247 ],
       [0.8991954 ],
       [0.8476063 ],
       [0.7120241 ],
       [0.5653497 ],
       [0.89283967],
       [0.8820988 ],
       [0.907549  ],
       [0.89111006],
       [0.8796052 ],
       [0.8390879 ],
       [0.63272095],
       [0.547532  ],
       [0.85055214],
       [0.86594486],
       [0.86748624],
       [0.8600677 ],
       [0.78313875],
       [0.71016604],
       [0.6675395 ],
       [0.9006778 ],
       [0.86349285],
       [0.8618327 ],
       [0.85779303],
       [0.82370317],
       [0.6213037 ],
       [0.41071978],
       [0.65646195],
       [0.84464717],
       [0.79221416],
       [0.76765466],
       [0.7346542 ],
       [0.6393472 ],
       [0.413963  ],
       [0.50947696],
       [0.52637017],
       [0.79412687],
       [0.76255834],
       [0.75262344],
       [0.74107766],
       [0.6663128 ],
       [0.47196928],
       [0.21502519],
       [0.41446504],
       [0.8252696 ],
       [0.8775434 ],
       [0.8771076 ],
       [0.8708645 ],
       [0.8488189 ],
       [0.8025975 ],
       [0.6197306 ],
       [0.4523897 ],
       [0.8845545 ],
       [0.903383  ],
       [0.8763472 ],
       [0.8625649 ],
       [0.8267462 ],
       [0.77682835],
       [0.61472636],
       [0.32117137],
       [0.5359613 ],
       [0.912117  ],
       [0.85688007],
       [0.89969164],
       [0.84964204],
       [0.858438  ],
       [0.8584094 ],
       [0.7320782 ],
       [0.44778603],
       [0.76333714],
       [0.9474221 ],
       [0.9261402 ],
       [0.91220427],
       [0.8895631 ],
       [0.8510715 ],
       [0.78398204],
       [0.6534756 ],
       [0.34730634],
       [0.5535019 ],
       [0.9398833 ],
       [0.909382  ],
       [0.94790334],
       [0.9130192 ],
       [0.9376184 ],
       [0.90228105],
       [0.7314391 ],
       [0.3747231 ],
       [0.4168814 ],
       [0.86883247],
       [0.92501736],
       [0.93069136],
       [0.94197404],
       [0.94278944],
       [0.9280369 ],
       [0.89756054],
       [0.72611725],
       [0.40780413],
       [0.46088937],
       [0.9713093 ],
       [0.9090165 ],
       [0.9255149 ],
       [0.88573146],
       [0.8840028 ],
       [0.8351548 ],
       [0.70826626],
       [0.42209533],
       [0.5053028 ],
       [0.94943494],
       [0.9220362 ],
       [0.9203891 ],
       [0.90650564],
       [0.92945814],
       [0.9099497 ],
       [0.7501376 ],
       [0.4395744 ],
       [0.69442165],
       [0.92634934],
       [0.90740097],
       [0.9237485 ],
       [0.88507426],
       [0.8863244 ],
       [0.83785534],
       [0.67440057],
       [0.3328415 ],
       [0.6201751 ],
       [0.92293316],
       [0.85645974],
       [0.8643032 ],
       [0.8698923 ],
       [0.8445085 ],
       [0.7438956 ],
       [0.5844311 ],
       [0.4190879 ],
       [0.50844395],
       [0.87332606],
       [0.8558233 ],
       [0.85526454],
       [0.80793524],
       [0.7866155 ],
       [0.6903479 ],
       [0.652735  ],
       [0.7334876 ],
       [0.6271876 ],
       [0.5367481 ],
       [0.48452488],
       [0.47491714],
       [0.49968877],
       [0.5286313 ],
       [0.5135257 ],
       [0.5797143 ],
       [0.5736227 ],
       [0.5027259 ],
       [0.44548103],
       [0.40434286],
       [0.3623373 ],
       [0.34890923],
       [0.3202652 ],
       [0.36967626],
       [0.58766073],
       [0.68313384],
       [0.6683674 ],
       [0.6470149 ],
       [0.6261547 ],
       [0.684845  ],
       [0.6775147 ],
       [0.66993845],
       [0.62706953],
       [0.62579525],
       [0.49872845],
       [0.4274254 ],
       [0.617895  ],
       [0.5968584 ],
       [0.56677157],
       [0.48512545],
       [0.49934056],
       [0.5564448 ],
       [0.69149065],
       [0.66949   ],
       [0.647768  ],
       [0.65383434],
       [0.6081419 ],
       [0.5493952 ],
       [0.5712119 ],
       [0.6670866 ],
       [0.67502356],
       [0.6841165 ],
       [0.72486806],
       [0.66700673],
       [0.64171654],
       [0.617787  ],
       [0.7775663 ],
       [0.80261207],
       [0.72896194],
       [0.6744666 ],
       [0.6515995 ],
       [0.5985803 ],
       [0.48109898],
       [0.3908721 ],
       [0.5745531 ],
       [0.862785  ],
       [0.8606554 ],
       [0.92565036],
       [0.87912196],
       [0.8626232 ],
       [0.84768593],
       [0.6813591 ],
       [0.45727137],
       [0.573338  ],
       [0.90675545],
       [0.8423503 ],
       [0.8488876 ],
       [0.8383975 ],
       [0.7866918 ],
       [0.6631477 ],
       [0.4377294 ],
       [0.64363307],
       [0.9160448 ],
       [0.878425  ],
       [0.8920911 ],
       [0.86891234],
       [0.8477148 ],
       [0.7914866 ],
       [0.6938251 ],
       [0.8559135 ],
       [0.8271768 ],
       [0.8330523 ],
       [0.8195938 ],
       [0.7865933 ],
       [0.750133  ],
       [0.7591496 ],
       [0.7322984 ],
       [0.7267148 ],
       [0.8529436 ],
       [0.8975704 ],
       [0.8819798 ],
       [0.82739216],
       [0.8775301 ],
       [0.8794699 ],
       [0.8833669 ],
       [0.85291207],
       [0.7938585 ],
       [0.87476444],
       [0.8846656 ],
       [0.7940345 ],
       [0.8322251 ],
       [0.8365324 ],
       [0.81726545],
       [0.9210968 ],
       [0.9527824 ],
       [0.86133695],
       [0.8289709 ],
       [0.8459215 ],
       [0.92983794],
       [0.95993865],
       [0.9262674 ],
       [0.9271148 ],
       [0.8808859 ],
       [0.80562544],
       [0.72036   ],
       [0.69594026],
       [0.9602032 ],
       [0.9013595 ],
       [0.89706486],
       [0.85586274],
       [0.8346534 ],
       [0.73974884],
       [0.57148015],
       [0.92963815],
       [0.8623174 ],
       [0.87367404],
       [0.8337083 ],
       [0.8150126 ],
       [0.69832015],
       [0.45373914],
       [0.84615767],
       [0.91073763],
       [0.881554  ],
       [0.8986714 ],
       [0.8765666 ],
       [0.81743836],
       [0.6811199 ],
       [0.42416045],
       [0.82363254],
       [0.9063492 ],
       [0.8837501 ],
       [0.9100237 ],
       [0.8917594 ],
       [0.85297066],
       [0.83829755],
       [0.5830647 ],
       [0.46444446],
       [0.84227204],
       [0.86978567],
       [0.8632503 ],
       [0.85031396],
       [0.8197844 ],
       [0.77005434],
       [0.4990314 ],
       [0.4935338 ],
       [0.8417554 ],
       [0.84406173],
       [0.84023166],
       [0.83241177],
       [0.81095797],
       [0.77379525],
       [0.57358456],
       [0.33435374],
       [0.7506435 ],
       [0.8871079 ],
       [0.8521565 ],
       [0.8755575 ],
       [0.8295949 ],
       [0.8102513 ],
       [0.66778696],
       [0.63284683],
       [0.8722918 ],
       [0.8413625 ],
       [0.863675  ],
       [0.82758605],
       [0.7673223 ],
       [0.6564503 ],
       [0.5139702 ],
       [0.47164187],
       [0.8487083 ],
       [0.8338149 ],
       [0.83818257],
       [0.8223537 ],
       [0.812981  ],
       [0.7302556 ],
       [0.8459219 ],
       [0.82162184],
       [0.81514454],
       [0.81617683],
       [0.796203  ],
       [0.73304343],
       [0.80334973],
       [0.8900231 ],
       [0.8660275 ],
       [0.8444532 ],
       [0.8199265 ],
       [0.77887   ],
       [0.60965747],
       [0.4719018 ],
       [0.8027208 ],
       [0.8854859 ],
       [0.8728341 ],
       [0.88401675],
       [0.8451186 ],
       [0.7990033 ],
       [0.5704274 ],
       [0.31138143],
       [0.75941133],
       [0.87006456],
       [0.8390214 ],
       [0.87792736],
       [0.85512924],
       [0.8257211 ],
       [0.76166284],
       [0.4648762 ],
       [0.09194852],
       [0.6096869 ],
       [0.87502027],
       [0.81590617],
       [0.8347581 ],
       [0.8085785 ],
       [0.7835895 ],
       [0.5664702 ],
       [0.0669339 ],
       [0.473972  ]], dtype=float32)

In [71]:
Photo_predictions = y_scaler.inverse_transform(Photo_predictions.reshape(-1, 1))
Photo_predictions = np.clip(Photo_predictions, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000

In [72]:
Photo_resultados = pd.DataFrame(Photo_predictions, index = y_test_windowed.index, columns=["Photo"])

In [73]:
predicciones["Photo"] = Photo_resultados["Photo"]
predicciones

,Generación,LightGBM,Random Forest,CTNET,Forecast,Photo
15328,27864.0,27737.854623,27676.1575,NaN,NaN,NaN
15329,24624.0,27486.133289,27436.08,NaN,NaN,NaN
15330,23657.0,24127.781396,24350.938017,NaN,NaN,NaN
15331,20683.0,20469.172397,20043.384431,NaN,NaN,NaN
15332,10703.0,10001.014624,10626.32,NaN,NaN,NaN
...,...,...,...,...,...,...
18281,25386.0,27249.220044,26034.882309,23223.203125,22693.320312,24257.355469
18282,22872.0,22924.525455,23229.408141,22499.527344,21046.179688,23507.683594
18283,15825.0,14677.255501,15735.242934,15411.343750,12242.646484,16994.105469
18284,1450.0,2147.631109,2056.066838,2882.268066,0.000000,2008.016968
18285,0.0,17.321742,0.0,16132.508789,5217.586914,14219.160156

In [74]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['LightGBM'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['LightGBM']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones['Generación'], predicciones['Random Forest'])):.4f}")
print(f"R²: {r2_score(predicciones['Generación'], predicciones['Random Forest']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['CTNET'].isna(),'Generación'], predicciones.loc[~predicciones['CTNET'].isna(),'CTNET']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Forecast'].isna(),'Generación'], predicciones.loc[~predicciones['Forecast'].isna(),'Forecast']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo'])):.4f}")
print(f"R²: {r2_score(predicciones.loc[~predicciones['Photo'].isna(),'Generación'], predicciones.loc[~predicciones['Photo'].isna(),'Photo']):.4f}")

LightGBM
MAE: 1509.1542
RMSE: 2532.1425
R²: 0.9059
Random Forest
MAE: 1666.8296
RMSE: 3025.3681
R²: 0.8657
CTNET
MAE: 3449.8432
RMSE: 4889.9729
R²: 0.6403
Forecast
MAE: 3800.3562
RMSE: 5225.2845
R²: 0.5893
Photovoltaic
MAE: 3210.1219
RMSE: 4913.9671
R²: 0.6368

In [75]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones.loc[:, "LightGBM":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN

## X_train para hacer análisis de sobreajuste

In [76]:
predicciones_train = y_train.copy()

In [77]:
LightGBM_predictions_train = LightGBM_model.predict(X_train_scaled_df)
LightGBM_predictions_train = y_scaler.inverse_transform(LightGBM_predictions_train.reshape(-1, 1))
LightGBM_predictions_train = np.clip(LightGBM_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
LightGBM_resultados = pd.DataFrame(LightGBM_predictions_train, index = y_train_scaled_df.index, columns=["LightGBM_train"])
predicciones_train["LightGBM_train"] = LightGBM_resultados["LightGBM_train"]

[LightGBM] [Warning] min_data_in_leaf is set=85, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=85

In [78]:
RandomForest_predictions_train = RF_model.predict(X_train_scaled_df)
RandomForest_predictions_train = y_scaler.inverse_transform(RandomForest_predictions_train.reshape(-1, 1))
RandomForest_predictions_train = np.clip(RandomForest_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
RandomForest_resultados = pd.DataFrame(RandomForest_predictions_train, index = y_train_scaled_df.index, columns=["RandomForest_train"])
predicciones_train["RandomForest_train"] = RandomForest_resultados["RandomForest_train"]

In [79]:
CTNET_predictions_train = CTNET.predict(X_train_windowed)
CTNET_predictions_train = y_scaler.inverse_transform(CTNET_predictions_train.reshape(-1, 1))
CTNET_predictions_train = np.clip(CTNET_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
CTNET_resultados = pd.DataFrame(CTNET_predictions_train, index = y_train_windowed.index, columns=["CTNET_train"])
predicciones_train["CTNET_train"] = CTNET_resultados["CTNET_train"]

144/144 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step

In [80]:
Forecast_predictions_train = Forecast_model.predict(X_train_windowed)
Forecast_predictions_train = y_scaler.inverse_transform(Forecast_predictions_train.reshape(-1, 1))
Forecast_predictions_train = np.clip(Forecast_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Forecast_resultados = pd.DataFrame(Forecast_predictions_train, index = y_train_windowed.index, columns=["Forecast_train"])
predicciones_train["Forecast_train"] = Forecast_resultados["Forecast_train"]

144/144 ━━━━━━━━━━━━━━━━━━━━ 15s 68ms/step

In [81]:
Photo_predictions_train = Photo_model.predict(X_train_windowed)
Photo_predictions_train = y_scaler.inverse_transform(Photo_predictions_train.reshape(-1, 1))
Photo_predictions_train = np.clip(Photo_predictions_train, 0, 30000)  # 🔹 Limitamos entre 0 y 30,000
Photo_resultados = pd.DataFrame(Photo_predictions_train, index = y_train_windowed.index, columns=["Photo_train"])
predicciones_train["Photo_train"] = Photo_resultados["Photo_train"]

144/144 ━━━━━━━━━━━━━━━━━━━━ 10s 31ms/step

In [82]:
predicciones_train

,Generación,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
36,27523.885172,21098.213009,23664.907604,NaN,NaN,NaN
37,20596.278869,26744.462625,23380.516505,NaN,NaN,NaN
38,28500.000000,22151.143748,25756.058073,NaN,NaN,NaN
39,24647.568577,27274.650131,25507.277645,NaN,NaN,NaN
40,25500.000000,24396.094841,25178.124908,NaN,NaN,NaN
...,...,...,...,...,...,...
13283,25417.000000,21338.219266,23812.422852,25327.320312,22362.228516,16248.473633
13284,26777.000000,26322.373558,26513.410000,22346.621094,22139.007812,18893.138672
13285,26755.000000,26662.111071,26720.286252,24434.644531,26526.132812,23050.728516
13286,26520.000000,26047.924317,26574.692071,25905.248047,27783.910156,25191.732422
13287,26446.000000,25722.889248,26357.781310,28127.304688,28160.974609,25504.152344

In [83]:
print("LightGBM")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['LightGBM_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['LightGBM_train']):.4f}")
print("Random Forest")
print(f"MAE: {mean_absolute_error(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train['Generación'], predicciones_train['RandomForest_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train['Generación'], predicciones_train['RandomForest_train']):.4f}")
print("CTNET")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['CTNET_train'].isna(),'CTNET_train']):.4f}")
print("Forecast")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Forecast_train'].isna(),'Forecast_train']):.4f}")
print("Photovoltaic")
print(f"MAE: {mean_absolute_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train'])):.4f}")
print(f"R²: {r2_score(predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Generación'], predicciones_train.loc[~predicciones_train['Photo_train'].isna(),'Photo_train']):.4f}")

LightGBM
MAE: 1023.3294
RMSE: 1845.5986
R²: 0.9693
Random Forest
MAE: 381.6334
RMSE: 739.3641
R²: 0.9951
CTNET
MAE: 2548.7851
RMSE: 3779.4295
R²: 0.8719
Forecast
MAE: 2604.5511
RMSE: 3853.4461
R²: 0.8668
Photovoltaic
MAE: 2500.8966
RMSE: 3935.4282
R²: 0.8611

In [84]:
# Seleccionar las columnas desde "LightGBM" en adelante
columnas_nuevas = predicciones_train.loc[:, "LightGBM_train":]

# Unir con `datos` usando el índice, manteniendo todo en `datos`
datos = datos.merge(columnas_nuevas, left_index=True, right_index=True, how='left')

# Ver resultado
datos.head()

,Fecha,Generación,Temperatura,Humedad Relativa,Índice UV,Hora,Cluster KMeans,Cluster GMM,Generacion_prev_hour,Generacion_prev_day,LightGBM,Random Forest,CTNET,Forecast,Photo,LightGBM_train,RandomForest_train,CTNET_train,Forecast_train,Photo_train
24,2022-09-02 00:00:00,0.0,19,76,0,0,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-09-02 01:00:00,0.0,18,81,0,1,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-09-02 02:00:00,0.0,18,84,0,2,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-09-02 03:00:00,0.0,18,86,0,3,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-09-02 04:00:00,0.0,17,86,0,4,Noche,Noche,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
datos.to_excel("04.9_Predicciones_Conjunto_nublado KMeans CTNET.xlsx", index=True)

## Guardamos los modelos

In [86]:
import joblib

# Guardar modelo LightGBM
joblib.dump(LightGBM_model, "4_9_LightGBM_model.pkl")

# Guardar modelo Random Forest
joblib.dump(RF_model, "4_9_RandomForest_model.pkl")

['4_9_RandomForest_model.pkl']

In [87]:
CTNET.save("4_9_CTNET_model.keras")
Forecast_model.save("4_9_Forecast_model.keras")
Photo_model.save("4_9_Photo_model.keras")